---
permalink: audit/audit-message-format.html 
sidebar: sidebar 
keywords: storagegrid, audit, message formats, message format 
summary: StorageGRID 시스템 내에서 교환되는 감사 메시지에는 모든 메시지에 공통되는 표준 정보 및 보고되는 이벤트 또는 활동을 설명하는 특정 콘텐츠가 포함됩니다. 
---
= 감사 메시지 형식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템 내에서 교환되는 감사 메시지에는 모든 메시지에 공통되는 표준 정보 및 보고되는 이벤트 또는 활동을 설명하는 특정 콘텐츠가 포함됩니다.

및 link:using-audit-sum-tool.html["감사 합계"]도구에서 제공하는 요약 정보가 충분하지 않은 경우 link:using-audit-explain-tool.html["감사 - 설명"]이 섹션을 참조하여 모든 감사 메시지의 일반적인 형식을 이해합니다.

다음은 감사 로그 파일에 표시될 수 있는 감사 메시지의 예입니다.

[listing]
----
2014-07-17T03:50:47.484627
[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][ATYP(FC32):SYSU][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
각 감사 메시지에는 특성 요소의 문자열이 포함됩니다. 전체 문자열은 대괄호로 묶임)(`[ ]`, 문자열의 각 특성 요소는 다음과 같은 특성을 갖습니다.

* 대괄호로 묶입니다 `[ ]`
* 감사 메시지를 나타내는 문자열에 의해 도입되었습니다 `AUDT`
* 앞 또는 뒤에 구분 기호(쉼표 또는 공백 없음)를 사용하지 않습니다
* 줄 바꿈 문자에 의해 종료됩니다 `\n`


각 요소에는 특성 코드, 데이터 형식 및 다음 형식으로 보고된 값이 포함됩니다.

[listing]
----
[ATTR(type):value][ATTR(type):value]...
[ATTR(type):value]\n
----
메시지의 특성 요소 수는 메시지의 이벤트 유형에 따라 달라집니다. 특성 요소가 특정 순서로 나열되지 않습니다.

다음 목록에서는 특성 요소에 대해 설명합니다.

* `ATTR` 보고되는 특성에 대한 4자리 코드입니다. 모든 감사 메시지에 공통적으로 적용되는 일부 특성 및 이벤트별 특성이 있습니다.
* `type` UI64, FC32 등과 같은 값의 프로그래밍 데이터 형식에 대한 4자리 식별자입니다. 형식은 괄호로 묶여 `( )` 있습니다.
* `value` 특성의 내용, 일반적으로 숫자 또는 텍스트 값입니다. 값은 항상 콜론 뒤에 (`:`옵니다.) 데이터 형식 CStr의 값은 큰따옴표 ""로 둘러싸여 있습니다.

