---
permalink: audit/audit-log-file-rotation.html 
sidebar: sidebar 
keywords: storagegrid, audit, log file, audit.log, audit.log file, rotation, save, autosave, auto save, auto-save 
summary: 감사 로그 파일은 관리자 노드의 /var/local/log 디렉토리에 저장됩니다. 활성 감사 로그 파일의 이름은 audit.log입니다. 
---
= 로그 파일 회전을 감사합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 로그 파일은 관리자 노드의 `/var/local/log` 디렉터리에 저장됩니다. 활성 감사 로그 파일의 이름이 `audit.log`지정됩니다.


NOTE: 선택적으로 감사 로그의 대상을 변경하고 감사 정보를 외부 syslog 서버로 보낼 수 있습니다. 외부 syslog 서버가 구성되면 감사 레코드의 로컬 로그가 계속 생성되고 저장됩니다. 을 link:../monitor/configure-audit-messages.html["감사 메시지 및 외부 syslog 서버를 구성합니다"]참조하십시오.

하루에 한 번 활성 `audit.log` 파일이 저장되고 새 `audit.log` 파일이 시작됩니다. 저장된 파일의 이름은 해당 파일이 저장된 시점을 형식으로 `_yyyy-mm-dd.txt_` 나타냅니다. 하루에 감사 로그가 두 개 이상 만들어지는 경우 파일 이름은 파일이 저장된 날짜(숫자 뒤에 붙음)를 형식으로 `_yyyy-mm-dd.txt.n_` 사용합니다. 예를 `2018-04-15.txt` 들어, 및 `2018-04-15.txt.1` 는 2018년 4월 15일에 생성되고 저장되는 첫 번째 및 두 번째 로그 파일입니다.

하루가 지나면 저장된 파일이 압축되고 원래 날짜가 보존되는 형식으로 이름이 `_yyyy-mm-dd.txt.gz_` 변경됩니다. 시간이 지남에 따라 이로 인해 관리 노드의 감사 로그에 할당된 스토리지가 소비됩니다. 스크립트는 감사 로그 공간 소비를 모니터링하고 필요에 따라 로그 파일을 삭제하여 디렉토리의 공간을 `/var/local/log` 확보합니다. 감사 로그는 작성된 날짜를 기준으로 삭제되며 가장 오래된 로그가 먼저 삭제됩니다. 다음 파일에서 스크립트의 작업을 모니터링할 수 있습니다 `/var/local/log/manage-audit.log`.

이 예에서는 활성 파일, 전날의 파일(`2018-04-15.txt`) 및 전날의 압축된 파일을 보여 `audit.log`(`2018-04-14.txt.gz` 줍니다.

[listing]
----
audit.log
2018-04-15.txt
2018-04-14.txt.gz
----