---
permalink: audit/cbrb-object-receive-begin.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, CBRB, Object Receive Begin 
summary: 정상적인 시스템 작업 중에 데이터 액세스, 복제 및 보존에 따라 컨텐츠 블록이 서로 다른 노드 간에 지속적으로 전송됩니다. 한 노드에서 다른 노드로 콘텐츠 블록 전송이 시작되면 대상 엔터티가 이 메시지를 발행합니다. 
---
= CBRB: 객체 수신 시작
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
정상적인 시스템 작업 중에 데이터 액세스, 복제 및 보존에 따라 컨텐츠 블록이 서로 다른 노드 간에 지속적으로 전송됩니다. 한 노드에서 다른 노드로 콘텐츠 블록 전송이 시작되면 대상 엔터티가 이 메시지를 발행합니다.

[cols="1a,1a,4a"]
|===
| 코드 | 필드에 입력합니다 | 설명 


 a| 
CNID
 a| 
연결 식별자
 a| 
노드 간 세션/연결의 고유 식별자입니다.



 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
전송 중인 컨텐츠 블록의 고유 식별자입니다.



 a| 
CTDR
 a| 
전송 방향
 a| 
CBID 전송이 푸시 시작 또는 풀 초기화되었는지 여부를 나타냅니다.

PUSH: 전송 작업이 전송 엔티티에 의해 요청되었습니다.

Pull(풀): 수신 엔티티가 전송 작업을 요청했습니다.



 a| 
CTSR
 a| 
원본 요소
 a| 
CBID 전송 소스(보낸 사람)의 노드 ID입니다.



 a| 
CTDS
 a| 
대상 요소
 a| 
CBID 전송 대상(수신기)의 노드 ID입니다.



 a| 
CTSS
 a| 
시작 시퀀스 수
 a| 
요청된 첫 번째 시퀀스 수를 나타냅니다. 성공한 경우 이 시퀀스 개수로 전송이 시작됩니다.



 a| 
CTES
 a| 
예상 종료 시퀀스 수입니다
 a| 
요청된 마지막 시퀀스 수를 나타냅니다. 성공한 경우 이 시퀀스 카운트가 수신되면 전송이 완료된 것으로 간주됩니다.



 a| 
RSLT
 a| 
전송 시작 상태
 a| 
전송이 시작된 시점의 상태:

SUCS: 전송이 시작되었습니다.

|===
이 감사 메시지는 컨텐츠 블록 식별자로 식별되는 단일 컨텐츠 부분에 대해 노드 간 데이터 전송 작업이 시작되었음을 의미합니다. 작업이 "시작 시퀀스 수"에서 "예상 종료 시퀀스 수"로 데이터를 요청합니다. 송신 및 수신 노드는 해당 노드 ID로 식별됩니다. 이 정보를 사용하여 시스템 데이터 흐름을 추적하고 스토리지 감사 메시지와 결합할 경우 복제본 수를 확인할 수 있습니다.
