---
permalink: audit/cbre-object-receive-end.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, CBRE, Object Receive End 
summary: 한 노드에서 다른 노드로 콘텐츠 블록 전송이 완료되면 대상 엔터티가 이 메시지를 발행합니다. 
---
= CBRE: 객체 수신 종료
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
한 노드에서 다른 노드로 콘텐츠 블록 전송이 완료되면 대상 엔터티가 이 메시지를 발행합니다.

[cols="1a,1a,4a"]
|===
| 코드 | 필드에 입력합니다 | 설명 


 a| 
CNID
 a| 
연결 식별자
 a| 
노드 간 세션/연결의 고유 식별자입니다.



 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
전송 중인 컨텐츠 블록의 고유 식별자입니다.



 a| 
CTDR
 a| 
전송 방향
 a| 
CBID 전송이 푸시 시작 또는 풀 초기화되었는지 여부를 나타냅니다.

PUSH: 전송 작업이 전송 엔티티에 의해 요청되었습니다.

Pull(풀): 수신 엔티티가 전송 작업을 요청했습니다.



 a| 
CTSR
 a| 
원본 요소
 a| 
CBID 전송 소스(보낸 사람)의 노드 ID입니다.



 a| 
CTDS
 a| 
대상 요소
 a| 
CBID 전송 대상(수신기)의 노드 ID입니다.



 a| 
CTSS
 a| 
시작 시퀀스 수
 a| 
전송이 시작된 시퀀스 수를 나타냅니다.



 a| 
CTAS
 a| 
실제 종료 시퀀스 수입니다
 a| 
성공적으로 전송된 마지막 시퀀스 수를 나타냅니다. 실제 End Sequence Count가 Start Sequence Count와 동일하고 Transfer Result가 성공하지 못한 경우 데이터가 교환되지 않았습니다.



 a| 
RSLT
 a| 
전송 결과
 a| 
전송 작업의 결과(전송 요소의 관점에서):

SUCS: 전송이 완료되었습니다. 요청된 모든 시퀀스 수가 전송되었습니다.

CONL: 전송 중에 연결이 끊어졌습니다

CTMO: 설정 또는 전송 중 연결 시간이 초과되었습니다

UNRE: 대상 노드 ID에 연결할 수 없습니다

CRPT: 손상되거나 잘못된 데이터가 수신되어 전송이 종료되었습니다

|===
이 감사 메시지는 노드 간 데이터 전송 작업이 완료되었음을 의미합니다. 전송 결과가 성공적이면 작업이 "시작 시퀀스 수"에서 "실제 종료 시퀀스 수"로 데이터를 전송합니다. 송신 및 수신 노드는 해당 노드 ID로 식별됩니다. 이 정보는 시스템 데이터 흐름을 추적하고 오류를 찾고, 도표하고, 분석하는 데 사용할 수 있습니다. 스토리지 감사 메시지와 함께 사용할 경우 복제본 수를 확인하는 데도 사용할 수 있습니다.
