---
permalink: audit/common-elements-in-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message, common elements, AMID, ANID, ASES, ASQN, ATID, ATIM, ATYP, AVER, RSLT 
summary: 모든 감사 메시지에는 공통 요소가 포함됩니다. 
---
= 감사 메시지의 공통 요소
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 감사 메시지에는 공통 요소가 포함됩니다.

[cols="1a,1a,4a"]
|===
| 코드 | 유형 | 설명 


 a| 
있습니다
 a| 
에프씨32
 a| 
모듈 ID: 메시지를 생성한 모듈 ID의 4자리 식별자입니다. 이것은 감사 메시지가 생성된 코드 세그먼트를 나타냅니다.



 a| 
ANID
 a| 
UI32 를 참조하십시오
 a| 
노드 ID: 메시지를 생성한 서비스에 할당된 그리드 노드 ID입니다. 각 서비스는 StorageGRID 시스템을 구성하고 설치할 때 고유 식별자를 할당합니다. 이 ID는 변경할 수 없습니다.



 a| 
ASE
 a| 
UI64 를 참조하십시오
 a| 
감사 세션 식별자: 이전 릴리즈에서는 이 요소는 서비스가 시작된 후 감사 시스템이 초기화된 시간을 나타냅니다. 이 시간 값은 운영 체제 Epoch(1970년 1월 1일 00:00:00 UTC) 이후 마이크로초 단위로 측정되었습니다.

* 참고: * 이 요소는 사용되지 않으며 감사 메시지에 더 이상 나타나지 않습니다.



 a| 
ASQN
 a| 
UI64 를 참조하십시오
 a| 
시퀀스 수: 이전 릴리즈에서는 그리드 노드(ANID)에서 생성된 각 감사 메시지에 대해 이 카운터가 증가했으며 서비스 재시작 시 0으로 재설정됩니다.

* 참고: * 이 요소는 사용되지 않으며 감사 메시지에 더 이상 나타나지 않습니다.



 a| 
ATID
 a| 
UI64 를 참조하십시오
 a| 
추적 ID: 단일 이벤트에 의해 트리거된 메시지 집합에서 공유하는 식별자입니다.



 a| 
ATIM
 a| 
UI64 를 참조하십시오
 a| 
Timestamp: 감사 메시지를 트리거한 이벤트가 생성된 시간으로, 운영 체제 Epoch(1970년 1월 1일 00:00:00 UTC) 이후 마이크로초 단위로 측정됩니다. 타임 스탬프를 로컬 날짜 및 시간으로 변환하는 데 사용할 수 있는 대부분의 도구는 밀리초를 기반으로 합니다.

로깅된 타임스탬프의 반올림 또는 잘라내기가 필요할 수 있습니다. 파일의 감사 메시지 시작 부분에 나타나는 사람이 읽을 수 있는 시간은 `audit.log` ISO 8601 형식의 ATIM 속성입니다. 날짜 및 시간은 로 `_YYYY-MMDDTHH:MM:SS.UUUUUU_` 표시되며, 여기서 는 `T` 날짜의 시간 세그먼트의 시작을 나타내는 리터럴 문자열 문자입니다. `_UUUUUU_` 마이크로초입니다.



 a| 
ATYP
 a| 
에프씨32
 a| 
이벤트 유형: 기록되는 이벤트의 4자리 식별자입니다. 이는 메시지의 "페이로드" 콘텐츠, 즉 포함된 속성을 제어합니다.



 a| 
비버
 a| 
UI32 를 참조하십시오
 a| 
버전: 감사 메시지의 버전입니다. StorageGRID 소프트웨어가 발전함에 따라 새로운 버전의 서비스에는 감사 보고에 새로운 기능이 포함될 수 있습니다. 이 필드를 사용하면 AMS 서비스의 이전 버전과의 호환성을 통해 이전 버전의 서비스에서 보낸 메시지를 처리할 수 있습니다.



 a| 
RSLT
 a| 
에프씨32
 a| 
결과: 이벤트, 프로세스 또는 트랜잭션의 결과. 이 메시지와 관련이 없으면 메시지가 실수로 필터링되지 않도록 SUCS 대신 사용되지 않습니다.

|===