---
permalink: audit/gtsu-grid-task-submitted.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, GTSU, Grid Task Submitted 
summary: 이 감사 메시지는 그리드 작업이 CMN 서비스로 제출되었음을 나타냅니다. 
---
= GTSU: 그리드 작업 제출됨
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 감사 메시지는 그리드 작업이 CMN 서비스로 제출되었음을 나타냅니다.

[cols="1a,1a,4a"]
|===
| 코드 | 필드에 입력합니다 | 설명 


 a| 
TSID
 a| 
태스크 ID입니다
 a| 
생성된 그리드 작업을 고유하게 식별하고 해당 수명 주기 동안 작업을 관리할 수 있습니다.

* 참고: * 작업 ID는 그리드 작업이 생성될 때 할당되며, 전송 시간이 아닙니다. 지정된 그리드 작업을 여러 번 제출할 수 있으며, 이 경우 작업 ID 필드만으로는 제출됨, 시작됨 및 종료된 감사 메시지를 고유하게 연결할 수 없습니다.



 a| 
TTYP
 a| 
태스크 유형
 a| 
그리드 작업의 유형입니다.



 a| 
버전
 a| 
작업 버전
 a| 
그리드 작업의 버전을 나타내는 숫자입니다.



 a| 
TDSC
 a| 
작업 설명
 a| 
그리드 작업에 대한 사람이 읽을 수 있는 설명입니다.



 a| 
귀리
 a| 
타임스탬프 이후에 유효합니다
 a| 
그리드 작업이 유효한 가장 빠른 시간(1970년 1월 1일부터 UNIX 시간으로 UInt64 마이크로초)입니다.



 a| 
VBTS
 a| 
타임스탬프 전에 유효합니다
 a| 
그리드 작업이 유효한 최신 시간(1970년 1월 1일 - UNIX 시간)입니다.



 a| 
TsRC
 a| 
출처
 a| 
작업의 출처:

* TXTB: 그리드 작업이 StorageGRID 시스템을 통해 서명된 텍스트 블록으로 제출되었습니다.
* 그리드: 그리드 작업이 내부 그리드 작업 제출 서비스를 통해 제출되었습니다.




 a| 
ACTV
 a| 
활성화 유형
 a| 
활성화 유형:

* 자동: 그리드 작업이 자동 활성화를 위해 제출되었습니다.
* PEND: 그리드 작업이 보류 중인 테이블에 제출되었습니다. TXTB 소스에 대한 유일한 가능성은 다음과 같은 것입니다.




 a| 
RSLT
 a| 
결과
 a| 
제출 결과:

* SUCS: 그리드 작업이 성공적으로 제출되었습니다.
* 실패: 작업이 내역 테이블로 직접 이동되었습니다.


|===