---
permalink: audit/idel-ilm-initiated-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, IDEL, ILM Initiated Delete 
summary: ILM이 개체 삭제 프로세스를 시작할 때 이 메시지가 생성됩니다. 
---
= IDEL: ILM 삭제 시작
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM이 개체 삭제 프로세스를 시작할 때 이 메시지가 생성됩니다.

IDEL 메시지는 다음 상황 중 하나에서 생성됩니다.

* * 규격 S3 버킷을 사용하는 오브젝트 *: ILM이 보존 기간이 만료되어(자동 삭제 설정이 활성화되고 법적 증거 자료 보관 기능이 꺼진 경우) 오브젝트를 자동 삭제하는 프로세스를 시작할 때 이 메시지가 생성됩니다.
* * 비준수 S3 버킷 * 의 객체용. 이 메시지는 현재 활성 ILM 정책의 배치 명령이 개체에 적용되지 않기 때문에 ILM이 개체 삭제 프로세스를 시작할 때 생성됩니다.


[cols="1a,1a,4a"]
|===
| 코드 | 필드에 입력합니다 | 설명 


 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
객체의 CBID입니다.



 a| 
CMPA
 a| 
준수: 자동 삭제
 a| 
규정 준수 S3 버킷에 있는 오브젝트에만 해당. 버킷을 법적 보관에 포함시키지 않는 한, 준수 객체가 보존 기간이 끝날 때 자동으로 삭제되어야 하는지 여부를 나타내는 0(false) 또는 1(true).



 a| 
CMPL
 a| 
규정 준수: 법적 증거 자료 보관
 a| 
규정 준수 S3 버킷에 있는 오브젝트에만 해당. 버킷이 현재 법적 증거 자료 보관 중인지 여부를 나타내는 0(거짓) 또는 1(참)입니다.



 a| 
CMPR
 a| 
규정 준수: 보존 기간
 a| 
규정 준수 S3 버킷에 있는 오브젝트에만 해당. 객체의 보존 기간(분)입니다.



 a| 
CTME
 a| 
규정 준수: 수집 시간
 a| 
규정 준수 S3 버킷에 있는 오브젝트에만 해당. 개체의 수집 시간입니다. 이 값에 분 단위로 보존 기간을 추가하여 버킷에서 오브젝트를 삭제할 수 있는 시기를 결정할 수 있습니다.



 a| 
DMRK
 a| 
마커 버전 ID를 삭제합니다
 a| 
버전이 있는 버킷에서 오브젝트를 삭제할 때 생성된 삭제 마커의 버전 ID입니다. 버킷에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
CSRZ
 a| 
콘텐츠 크기
 a| 
오브젝트의 크기(바이트)입니다.



 a| 
위치
 a| 
위치
 a| 
StorageGRID 시스템 내에서 오브젝트 데이터의 저장 위치입니다. 오브젝트에 위치가 없는 경우(예: 삭제된 경우) Locs 값은 ""입니다.

CLEC: 삭제 코딩 개체의 경우 삭제 코딩 프로필 ID 및 개체의 데이터에 적용되는 삭제 코딩 그룹 ID입니다.

CLDI: 복제된 개체의 경우 LDR 노드 ID 및 개체 위치의 볼륨 ID입니다.

CLNL: 객체 데이터가 아카이빙된 경우 객체 위치의 ARC 노드 ID입니다.



 a| 
경로
 a| 
S3 버킷/키
 a| 
S3 버킷 이름 및 S3 키 이름.



 a| 
RSLT
 a| 
결과
 a| 
ILM 작업의 결과.

SUCS: ILM 작업이 성공했습니다.



 a| 
규칙
 a| 
규칙 레이블
 a| 
* 보존 기간이 만료되어 호환 S3 버킷의 오브젝트가 자동으로 삭제되는 경우 이 필드는 비어 있습니다.
* 현재 개체에 적용되는 배치 지침이 더 이상 없기 때문에 개체를 삭제하는 경우 이 필드에는 개체에 적용된 마지막 ILM 규칙의 사람이 읽을 수 있는 레이블이 표시됩니다.




 a| 
SGRP
 a| 
사이트(그룹)
 a| 
개체가 있는 경우 지정된 사이트에서 해당 개체가 수집된 사이트가 아니라 해당 개체가 삭제되었습니다.



 a| 
UUID입니다
 a| 
범용 고유 식별자
 a| 
StorageGRID 시스템 내의 개체의 식별자입니다.



 a| 
VSID 를 선택합니다
 a| 
버전 ID
 a| 
삭제된 개체의 특정 버전의 버전 ID입니다. 버전이 지정되지 않은 버킷의 버킷 및 오브젝트에 대한 작업에는 이 필드가 포함되지 않습니다.

|===