---
permalink: audit/orlm-object-rules-met.html 
sidebar: sidebar 
keywords: audit message, ORLM, Object Rules Met, ilm rule 
summary: 이 메시지는 ILM 규칙에 지정된 대로 개체가 성공적으로 저장 및 복사될 때 생성됩니다. 
---
= ORLM: 개체 규칙이 충족되었습니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 메시지는 ILM 규칙에 지정된 대로 개체가 성공적으로 저장 및 복사될 때 생성됩니다.


NOTE: 정책의 다른 규칙에서 개체 크기 고급 필터를 사용하는 경우 객체가 기본 복사본 2개 만들기 규칙에 의해 성공적으로 저장되면 ORLM 메시지가 생성되지 않습니다.

[cols="1a,1a,4a"]
|===
| 코드 | 필드에 입력합니다 | 설명 


 a| 
BUID
 a| 
버킷 헤더
 a| 
버킷 ID 필드. 내부 작업에 사용됩니다. STAT가 PRGD인 경우에만 나타납니다.



 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
객체의 CBID입니다.



 a| 
CSRZ
 a| 
콘텐츠 크기
 a| 
오브젝트의 크기(바이트)입니다.



 a| 
위치
 a| 
위치
 a| 
StorageGRID 시스템 내에서 오브젝트 데이터의 저장 위치입니다. 오브젝트에 위치가 없는 경우(예: 삭제된 경우) Locs 값은 ""입니다.

CLEC: 삭제 코딩 개체의 경우 삭제 코딩 프로필 ID 및 개체의 데이터에 적용되는 삭제 코딩 그룹 ID입니다.

CLDI: 복제된 개체의 경우 LDR 노드 ID 및 개체 위치의 볼륨 ID입니다.

CLNL: 객체 데이터가 아카이빙된 경우 객체 위치의 ARC 노드 ID입니다.



 a| 
경로
 a| 
S3 버킷/키
 a| 
S3 버킷 이름 및 S3 키 이름.



 a| 
RSLT
 a| 
결과
 a| 
ILM 작업의 결과.

SUCS: ILM 작업이 성공했습니다.



 a| 
규칙
 a| 
규칙 레이블
 a| 
이 개체에 적용된 ILM 규칙에 지정된 사람이 읽을 수 있는 레이블입니다.



 a| 
SEGC
 a| 
컨테이너 UUID입니다
 a| 
분할된 객체에 대한 컨테이너의 UUID입니다. 이 값은 개체가 분할된 경우에만 사용할 수 있습니다.



 a| 
SGCB
 a| 
컨테이너 CBID입니다
 a| 
분할된 객체에 대한 컨테이너의 CBID입니다. 이 값은 세그먼트화된 개체와 여러 부분으로 구성된 개체에만 사용할 수 있습니다.



 a| 
STAT
 a| 
상태
 a| 
ILM 작업의 상태입니다.

완료: 객체에 대한 ILM 작업이 완료되었습니다.

DFER: 향후 ILM 재평가를 위해 객체가 표시되었습니다.

PRGD: StorageGRID 시스템에서 객체가 삭제되었습니다.

NLOC: 객체 데이터를 더 이상 StorageGRID 시스템에서 찾을 수 없습니다. 이 상태는 오브젝트 데이터의 모든 복사본이 누락 또는 손상되었음을 나타낼 수 있습니다.



 a| 
UUID입니다
 a| 
범용 고유 식별자
 a| 
StorageGRID 시스템 내의 개체의 식별자입니다.



 a| 
VSID 를 선택합니다
 a| 
버전 ID
 a| 
버전 관리되는 버킷에서 생성된 새 개체의 버전 ID입니다. 버전이 지정되지 않은 버킷의 버킷 및 오브젝트에 대한 작업에는 이 필드가 포함되지 않습니다.

|===
단일 객체에 대해 ORLM 감사 메시지를 두 번 이상 발행할 수 있습니다. 예를 들어, 다음 이벤트 중 하나가 발생할 때마다 실행됩니다.

* 개체에 대한 ILM 규칙이 영구 충족됩니다.
* 개체에 대한 ILM 규칙이 이 Epoch에 충족되었습니다.
* ILM 규칙이 개체를 삭제했습니다.
* 백그라운드 검증 프로세스에서는 복제된 개체 데이터의 복사본이 손상되었음을 감지합니다. StorageGRID 시스템은 ILM 평가를 수행하여 손상된 개체를 교체합니다.


.관련 정보
* link:object-ingest-transactions.html["오브젝트 수집 트랜잭션"]
* link:object-delete-transactions.html["객체 삭제 트랜잭션입니다"]

