---
permalink: audit/s3-select-request.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, S3SL, S3 Select request 
summary: 이 메시지는 사용자가 S3 Select 작업을 시작했음을 나타냅니다. 
---
= S3SL:S3 선택 요청
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 메시지는 S3 Select 요청이 클라이언트에 반환된 후 완료를 기록합니다. S3SL 메시지에는 오류 메시지 및 오류 코드 세부 정보가 포함될 수 있습니다. 요청이 성공적으로 완료되지 않았을 수 있습니다.

[cols="1a,1a,4a"]
|===
| 코드 | 필드에 입력합니다 | 설명 


 a| 
BYSC
 a| 
스캔된 바이트 수
 a| 
스토리지 노드에서 스캔(수신)된 바이트 수입니다.

객체가 압축되면 BYSC와 BYPR은 다를 수 있습니다. 개체가 압축된 BYSC인 경우 압축된 바이트 수가 있고, BYPR은 압축 해제 후 바이트가 됩니다.



 a| 
BYPR
 a| 
처리된 바이트 수
 a| 
처리된 바이트 수입니다. S3 Select 작업에서 실제로 처리되거나 작업된 "스캔한 바이트"의 바이트 수를 나타냅니다.



 a| 
BYRT
 a| 
반환된 바이트 수입니다
 a| 
S3 Select 작업이 클라이언트에 반환한 바이트 수입니다.



 a| 
재등록
 a| 
레코드가 처리되었습니다
 a| 
스토리지 노드에서 S3 Select 작업이 수신한 레코드 또는 행 수입니다.



 a| 
오류
 a| 
레코드가 반환되었습니다
 a| 
클라이언트로 반환된 S3 Select 작업의 레코드 또는 행 수입니다.



 a| 
JOFI
 a| 
작업이 완료되었습니다
 a| 
S3 Select 작업의 처리 완료 여부를 나타냅니다. 이 값이 거짓이면 작업이 완료되지 못했으며 오류 필드에 데이터가 있을 수 있습니다. 클라이언트가 일부 결과를 받았거나 전혀 결과를 받지 않았을 수 있습니다.



 a| 
리드
 a| 
요청 ID
 a| 
S3 선택 요청의 식별자입니다.



 a| 
EXTM
 a| 
실행 시간
 a| 
S3 Select 작업을 완료하는 데 걸리는 시간(초)입니다.



 a| 
ERMG
 a| 
오류 메시지
 a| 
S3 Select 작업이 생성되었다는 오류 메시지입니다.



 a| 
어티
 a| 
오류 유형
 a| 
S3 Select 작업이 생성한 오류 유형입니다.



 a| 
ERST
 a| 
오류 StackTrace
 a| 
S3 선택 작업이 생성한 오류 StackTrace.



 a| 
에스쓰리비케이주식회사
 a| 
S3 버킷
 a| 
S3 버킷 이름입니다.



 a| 
S3AK(S3AK
 a| 
S3 액세스 키 ID(요청 발신자)
 a| 
요청을 보낸 사용자의 S3 액세스 키 ID입니다.



 a| 
에스쓰리아이주식회사
 a| 
S3 테넌트 계정 ID(요청 발신자)
 a| 
요청을 보낸 사용자의 테넌트 계정 ID입니다.



 a| 
에스3KY
 a| 
S3 키
 a| 
버킷 이름을 제외한 S3 키 이름.

|===