---
permalink: audit/shea-s3-head.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SHEA, S3 HEAD 
summary: S3 클라이언트에서 헤드 작업을 실행하면 오브젝트 또는 버킷이 있는지 확인하고 오브젝트에 대한 메타데이터를 검색하도록 요청이 수행됩니다. 이 메시지는 작업이 성공하면 서버에서 발행합니다. 
---
= Shea: S3 헤드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 클라이언트에서 헤드 작업을 실행하면 오브젝트 또는 버킷이 있는지 확인하고 오브젝트에 대한 메타데이터를 검색하도록 요청이 수행됩니다. 이 메시지는 작업이 성공하면 서버에서 발행합니다.

[cols="1a,1a,4a"]
|===
| 코드 | 필드에 입력합니다 | 설명 


 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
요청된 콘텐츠 블록의 고유 식별자입니다. CBID를 알 수 없는 경우 이 필드는 0으로 설정됩니다. 버킷에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
CNID
 a| 
연결 식별자
 a| 
TCP/IP 연결에 대한 고유한 시스템 식별자입니다.



 a| 
CSRZ
 a| 
콘텐츠 크기
 a| 
선택한 오브젝트의 크기(바이트)입니다. 버킷에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
HTRH
 a| 
HTTP 요청 헤더
 a| 
구성 중에 선택한 로그 HTTP 요청 헤더 이름 및 값 목록입니다.

 `X-Forwarded-For` 요청이 요청에 있고 값이 요청 보낸 사람 IP 주소(SAIP 감사 필드)와 다른 경우 자동으로 포함됩니다 `X-Forwarded-For`.



 a| 
RSLT
 a| 
결과 코드
 a| 
Get 트랜잭션의 결과. 결과는 항상 다음과 같습니다.

SUCS: 성공했습니다



 a| 
에스쓰리아이주식회사
 a| 
S3 테넌트 계정 ID(요청 발신자)
 a| 
요청을 보낸 사용자의 테넌트 계정 ID입니다. 빈 값은 익명 액세스를 나타냅니다.



 a| 
S3AK(S3AK
 a| 
S3 액세스 키 ID(요청 발신자)
 a| 
요청을 보낸 사용자의 해시된 S3 액세스 키 ID입니다. 빈 값은 익명 액세스를 나타냅니다.



 a| 
에스쓰리비케이주식회사
 a| 
S3 버킷
 a| 
S3 버킷 이름입니다.



 a| 
에스3KY
 a| 
S3 키
 a| 
버킷 이름을 제외한 S3 키 이름. 버킷에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
SACC
 a| 
S3 테넌트 계정 이름(요청 발신자)
 a| 
요청을 보낸 사용자의 테넌트 계정 이름입니다. 익명 요청에 대해 비어 있습니다.



 a| 
SAIP
 a| 
IP 주소(요청 발신자)
 a| 
요청을 한 클라이언트 애플리케이션의 IP 주소입니다.



 a| 
SBAC
 a| 
S3 테넌트 계정 이름(버킷 소유자)
 a| 
버킷 소유자의 테넌트 계정 이름입니다. 교차 계정 또는 익명 액세스를 식별하는 데 사용됩니다.



 a| 
SBAI를 참조하십시오
 a| 
S3 테넌트 계정 ID(버킷 소유자)
 a| 
타겟 버킷의 소유자의 테넌트 계정 ID입니다. 교차 계정 또는 익명 액세스를 식별하는 데 사용됩니다.



 a| 
SUSR
 a| 
S3 사용자 URN(요청 발신자)
 a| 
테넌트 계정 ID 및 요청을 하는 사용자의 사용자 이름입니다. 사용자는 로컬 사용자 또는 LDAP 사용자일 수 있습니다. 예를 들면 다음과 같습니다. `urn:sgws:identity::03393893651506583485:root`

익명 요청에 대해 비어 있습니다.



 a| 
시간
 a| 
시간
 a| 
요청의 총 처리 시간(마이크로초)입니다.



 a| 
TLIP
 a| 
신뢰할 수 있는 로드 밸런서 IP 주소
 a| 
요청이 트러스트된 레이어 7 로드 밸런서에 의해 라우팅된 경우 로드 밸런서의 IP 주소입니다.



 a| 
UUID입니다
 a| 
범용 고유 식별자
 a| 
StorageGRID 시스템 내의 개체의 식별자입니다.



 a| 
VSID 를 선택합니다
 a| 
버전 ID
 a| 
요청된 개체의 특정 버전의 버전 ID입니다. 버전이 지정되지 않은 버킷의 버킷 및 오브젝트에 대한 작업에는 이 필드가 포함되지 않습니다.

|===