---
permalink: audit/svrf-object-store-verify-fail.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SVRF, Object Store Verify Fail 
summary: 이 메시지는 콘텐츠 블록이 확인 프로세스를 통과하지 못할 때마다 발행됩니다. 복제된 오브젝트 데이터를 디스크에서 읽거나 디스크에 쓸 때마다 여러 검증 및 무결성 검사가 수행되어 요청 사용자에게 전송된 데이터가 원래 시스템으로 수집된 데이터와 동일한지 확인합니다. 이러한 검사 중 하나라도 실패하면 시스템이 손상된 복제된 객체 데이터를 자동으로 격리하여 손상된 객체 데이터가 다시 검색되지 않도록 합니다. 
---
= SVRF: Object Store Verify Fail(SVRF: 오브젝트 저장소 확인 실패)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 메시지는 콘텐츠 블록이 확인 프로세스를 통과하지 못할 때마다 발행됩니다. 복제된 오브젝트 데이터를 디스크에서 읽거나 디스크에 쓸 때마다 여러 검증 및 무결성 검사가 수행되어 요청 사용자에게 전송된 데이터가 원래 시스템으로 수집된 데이터와 동일한지 확인합니다. 이러한 검사 중 하나라도 실패하면 시스템이 손상된 복제된 객체 데이터를 자동으로 격리하여 손상된 객체 데이터가 다시 검색되지 않도록 합니다.

[cols="1a,1a,4a"]
|===
| 코드 | 필드에 입력합니다 | 설명 


 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
확인에 실패한 콘텐츠 블록의 고유 식별자입니다.



 a| 
RSLT
 a| 
결과 코드
 a| 
확인 실패 유형:

CRCF: CRC(Cyclic Redundancy Check)에 실패했습니다.

HMAC: HMAC(해시 기반 메시지 인증 코드) 확인에 실패했습니다.

EHSH: 예기치 않은 암호화된 콘텐츠 해시입니다.

PHSH: 예기치 않은 원본 콘텐츠 해시입니다.

SEQC: 디스크에 잘못된 데이터 시퀀스가 있습니다.

PERR: 디스크 파일의 구조가 잘못되었습니다.

DERR: 디스크 오류입니다.

FNAM: 파일 이름이 잘못되었습니다.

|===

NOTE: 이 메시지는 자세히 모니터링해야 합니다. 콘텐츠 검증 실패는 하드웨어 오류가 임박한 것을 의미할 수 있습니다.

메시지를 트리거한 작업을 확인하려면 모듈 ID(amid) 필드의 값을 참조하십시오. 예를 들어, SVFY 값은 메시지가 Storage Verifier 모듈에 의해 생성되었음을 나타냅니다. 즉, 백그라운드 검증 및 스토리지 는 메시지가 콘텐츠 검색에 의해 트리거되었음을 나타냅니다.
