---
permalink: audit/using-audit-explain-tool.html 
sidebar: sidebar 
keywords: storagegrid, audit, tool, audit-explain, audit explain, translate audit messages, translate messages, translate audit message, translate message 
summary: 감사 설명 도구를 사용하여 감사 로그의 감사 메시지를 읽기 쉬운 형식으로 변환할 수 있습니다. 
---
= 감사 설명 도구를 사용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 도구를 사용하여 감사 로그에서 감사 메시지를 읽기 쉬운 형식으로 변환할 수 `audit-explain` 있습니다.

.시작하기 전에
* 있습니다. link:../admin/admin-group-permissions.html["특정 액세스 권한"]
* 파일이 있어야 `Passwords.txt` 합니다.
* 기본 관리 노드의 IP 주소를 알아야 합니다.


.이 작업에 대해
기본 관리자 노드에서 사용할 수 있는 이 `audit-explain` 도구는 감사 로그에 감사 메시지에 대한 간단한 요약을 제공합니다.


NOTE: 이 `audit-explain` 도구는 주로 문제 해결 작업 중에 기술 지원 부서에서 사용하도록 제작되었습니다. 쿼리를 처리하면 `audit-explain` 많은 양의 CPU 성능이 소모될 수 있으며, 이로 인해 StorageGRID 작업에 영향을 줄 수 있습니다.

이 예에서는 도구의 일반적인 출력을 보여 `audit-explain` 줍니다. 이 4개의 link:sput-s3-put.html["SPUT"] 감사 메시지는 계정 ID가 92484777680322627870인 S3 테넌트가 S3 PUT 요청을 사용하여 "bucket1"이라는 버킷을 생성하고 해당 버켓에 3개의 객체를 추가할 때 생성됩니다.

[listing]
----
SPUT S3 PUT bucket bucket1 account:92484777680322627870 usec:124673
SPUT S3 PUT object bucket1/part1.txt tenant:92484777680322627870  cbid:9DCB157394F99FE5 usec:101485
SPUT S3 PUT object bucket1/part2.txt tenant:92484777680322627870  cbid:3CFBB07AB3D32CA9 usec:102804
SPUT S3 PUT object bucket1/part3.txt tenant:92484777680322627870  cbid:5373D73831ECC743 usec:93874
----
이 `audit-explain` 도구는 다음을 수행할 수 있습니다.

* 일반 또는 압축 감사 로그를 처리합니다. 예를 들면 다음과 같습니다.
+
`audit-explain audit.log`

+
`audit-explain 2019-08-12.txt.gz`

* 여러 파일을 동시에 처리합니다. 예를 들면 다음과 같습니다.
+
`audit-explain audit.log 2019-08-12.txt.gz 2019-08-13.txt.gz`

+
`audit-explain /var/local/log/*`

* 파이프의 입력을 수락하면 명령 또는 다른 방법으로 입력을 필터링하고 사전 처리할 수 있습니다. `grep` 예를 들면 다음과 같습니다.
+
`grep SPUT audit.log | audit-explain`

+
`grep bucket-name audit.log | audit-explain`



감사 로그는 매우 크고 구문 분석 속도가 느릴 수 있기 때문에 전체 파일이 아닌 파트에서 보고 실행할 부분을 필터링하여 시간을 절약할 수 `audit-explain` 있습니다.

[NOTE]
====
이 `audit-explain` 도구는 압축된 파일을 파이프 입력 파일로 허용하지 않습니다. 압축된 파일을 처리하려면 파일 이름을 명령줄 인수로 제공하거나 도구를 사용하여 `zcat` 먼저 파일의 압축을 푸십시오. 예를 들면 다음과 같습니다.

`zcat audit.log.gz | audit-explain`

====
옵션을 사용하여 `help (-h)` 사용 가능한 옵션을 확인합니다. 예를 들면 다음과 같습니다.

`$ audit-explain -h`

.단계
. 기본 관리자 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@_primary_Admin_Node_IP_`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
.. 다음 명령을 입력하여 루트로 전환합니다. `su -`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
+
루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.



. 다음 명령을 입력합니다. 여기서 는 분석할 파일의 이름과 위치를 나타냅니다. `/var/local/log/audit.log`
+
`$ audit-explain /var/local/log/audit.log`

+
이 `audit-explain` 도구는 지정된 파일에 있는 모든 메시지에 대해 사람이 읽을 수 있는 해석을 인쇄합니다.

+

NOTE: 선 길이를 줄이고 가독성을 높이기 위해 타임스탬프가 기본적으로 표시되지 않습니다. 타임스탬프를 보려면 타임스탬프(`-t`) 옵션을 사용하십시오.


