---
permalink: audit/whea-swift-head.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WHEA, Swift HEAD 
summary: Swift 클라이언트가 헤드 트랜잭션을 실행할 때 계정, 컨테이너 또는 개체의 존재 여부를 확인하고 관련 메타데이터를 검색하도록 요청합니다. 이 메시지는 트랜잭션이 성공하면 서버에서 발행됩니다. 
---
= WHEA: 스위프트 헤드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Swift 클라이언트가 헤드 트랜잭션을 실행할 때 계정, 컨테이너 또는 개체의 존재 여부를 확인하고 관련 메타데이터를 검색하도록 요청합니다. 이 메시지는 트랜잭션이 성공하면 서버에서 발행됩니다.

[cols="1a,1a,4a"]
|===
| 코드 | 필드에 입력합니다 | 설명 


 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
요청된 콘텐츠 블록의 고유 식별자입니다. CBID를 알 수 없는 경우 이 필드는 0으로 설정됩니다. 계정 및 컨테이너에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
CSRZ
 a| 
콘텐츠 크기
 a| 
검색된 객체의 크기(바이트)입니다. 계정 및 컨테이너에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
HTRH
 a| 
HTTP 요청 헤더
 a| 
구성 중에 선택한 로그 HTTP 요청 헤더 이름 및 값 목록입니다.

 `X-Forwarded-For` 요청이 요청에 있고 값이 요청 보낸 사람 IP 주소(SAIP 감사 필드)와 다른 경우 자동으로 포함됩니다 `X-Forwarded-For`.



 a| 
RSLT
 a| 
결과 코드
 a| 
머리 거래의 결과. 결과는 항상 다음과 같습니다.

SUCS: 성공했습니다



 a| 
SAIP
 a| 
요청 클라이언트의 IP 주소입니다
 a| 
요청을 한 클라이언트 애플리케이션의 IP 주소입니다.



 a| 
시간
 a| 
시간
 a| 
요청의 총 처리 시간(마이크로초)입니다.



 a| 
TLIP
 a| 
신뢰할 수 있는 로드 밸런서 IP 주소
 a| 
요청이 트러스트된 레이어 7 로드 밸런서에 의해 라우팅된 경우 로드 밸런서의 IP 주소입니다.



 a| 
UUID입니다
 a| 
범용 고유 식별자
 a| 
StorageGRID 시스템 내의 개체의 식별자입니다.



 a| 
WACC
 a| 
SWIFT 계정 ID
 a| 
StorageGRID 시스템에서 지정한 고유 계정 ID입니다.



 a| 
WCON
 a| 
SWIFT 컨테이너
 a| 
Swift 컨테이너 이름입니다. 계정 작업에는 이 필드가 포함되지 않습니다.



 a| 
WOBJ
 a| 
Swift 오브젝트
 a| 
Swift 오브젝트 식별자입니다. 계정 및 컨테이너에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
WUSR
 a| 
SwiFT 계정 사용자
 a| 
트랜잭션을 수행하는 클라이언트를 고유하게 식별하는 Swift 계정 사용자 이름입니다.

|===