---
permalink: swnodes/configuring-docker-storage-volume.html 
sidebar: sidebar 
keywords: how to configure container engine storage volume, Docker, Podman 
summary: Docker 또는 Podman 컨테이너 엔진을 설치하기 전에 스토리지 볼륨을 포맷하고 마운트해야 할 수도 있습니다. 
---
= 컨테이너 엔진 스토리지 볼륨 구성(Linux)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Docker 또는 Podman 컨테이너 엔진을 설치하기 전에 스토리지 볼륨을 포맷하고 마운트해야 할 수도 있습니다.


NOTE: 소프트웨어 전용 배포를 위한 컨테이너 엔진으로 Docker에 대한 지원은 더 이상 사용되지 않습니다. Docker는 향후 릴리즈에서 다른 컨테이너 엔진으로 대체될 예정입니다.


NOTE: "Linux"는 RHEL, Ubuntu 또는 Debian 배포를 의미합니다.  지원되는 버전 목록은 다음을 참조하세요. https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴(IMT)"^] .

.이 작업에 대해
Docker 또는 Podman 스토리지 볼륨에 루트 볼륨을 사용하려는 경우 다음이 포함된 호스트 파티션에 충분한 공간이 있는 경우 이 단계를 건너뛸 수 있습니다.

* 포드만: `/var/lib/containers`
* 도커: `/var/lib/docker`


.단계
. 컨테이너 엔진 스토리지 볼륨에 파일 시스템을 생성합니다.
+
[role="tabbed-block"]
====
.RHEL
--
[listing]
----
sudo mkfs.ext4 container-engine-storage-volume-device
----
--
.Ubuntu 또는 Debian
--
[listing]
----
sudo mkfs.ext4 docker-storage-volume-device
----
--
====
. 컨테이너 엔진 저장소 볼륨을 마운트합니다.
+
[role="tabbed-block"]
====
.RHEL
--
** Docker의 경우:
+
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount container-storage-volume-device /var/lib/docker
----
** Podman의 경우:
+
[listing]
----
sudo mkdir -p /var/lib/containers
sudo mount container-storage-volume-device /var/lib/containers
----


--
.Ubuntu 또는 Debian
--
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount docker-storage-volume-device /var/lib/docker
----
** Podman의 경우:
+
[listing]
----
sudo mkdir -p /var/lib/podman
sudo mount container-storage-volume-device /var/lib/podman
----


--
====
. 컨테이너 스토리지 볼륨 장치에 대한 항목을 /etc/fstab에 추가합니다.
+
** RHEL: 컨테이너-스토리지-볼륨-장치
** Ubuntu 또는 Debian: docker-storage-volume-device
+
이 단계를 수행하면 호스트가 재부팅된 후 스토리지 볼륨이 자동으로 다시 마운트됩니다.







== Docker를 설치합니다

StorageGRID 시스템은 컨테이너 컬렉션으로 Linux에서 실행될 수 있습니다.

* Ubuntu 또는 Debian에 StorageGRID 설치하려면 먼저 Docker를 설치해야 합니다.
* Docker 컨테이너 엔진을 사용하기로 선택한 경우 다음 단계에 따라 Docker를 설치하세요.  그렇지 않으면,<<install-podman-rhel,Podman을 설치합니다>> .



NOTE: 소프트웨어 전용 배포를 위한 컨테이너 엔진으로 Docker에 대한 지원은 더 이상 사용되지 않습니다. Docker는 향후 릴리즈에서 다른 컨테이너 엔진으로 대체될 예정입니다.

.단계
. Linux 배포에 대한 지침에 따라 Docker를 설치합니다.
+

NOTE: Docker가 Linux 배포판에 포함되어 있지 않은 경우 Docker 웹 사이트에서 다운로드할 수 있습니다.

. 다음 두 명령을 실행하여 Docker를 활성화하고 시작했는지 확인합니다.
+
[listing]
----
sudo systemctl enable docker
----
+
[listing]
----
sudo systemctl start docker
----
. 다음을 입력하여 예상 버전의 Docker를 설치했는지 확인합니다.
+
[listing]
----
sudo docker version
----
+
클라이언트 및 서버 버전은 1.11.0 이상이어야 합니다.





== Podman을 설치합니다

StorageGRID 시스템은 컨테이너의 컬렉션으로 실행됩니다.  Podman 컨테이너 엔진을 사용하기로 선택한 경우 다음 단계에 따라 Podman을 설치하세요.  그렇지 않으면,<<Docker를 설치합니다,Docker를 설치합니다>> .

.단계
. Linux 배포에 대한 지침에 따라 Podman 및 Podman-Docker를 설치합니다.
+

NOTE: Podman을 설치할 때 Podman-docker 패키지도 설치해야 합니다.

. 다음을 입력하여 예상 버전의 Podman 및 Podman-Docker를 설치했는지 확인합니다.
+
[listing]
----
sudo docker version
----
+

NOTE: Podman-Docker 패키지를 사용하면 Docker 명령을 사용할 수 있습니다.

+
클라이언트 및 서버 버전은 3.2.3 이상이어야 합니다.

+
[listing]
----
Version: 3.2.3
API Version: 3.2.3
Go Version: go1.15.7
Built: Tue Jul 27 03:29:39 2021
OS/Arch: linux/amd64
----


.관련 정보
link:configuring-host-storage.html["호스트 스토리지를 구성합니다"]
