---
permalink: swnodes/creating-node-configuration-files.html 
sidebar: sidebar 
keywords: how to create rhel ubuntu or debian node configuration files, port, remap, port remap 
summary: 노드 구성 파일은 StorageGRID 호스트 서비스에서 노드를 시작하고 적절한 네트워크 및 블록 스토리지 리소스에 연결하는 데 필요한 정보를 제공하는 작은 텍스트 파일입니다. 노드 구성 파일은 가상 노드에 사용되며 어플라이언스 노드에는 사용되지 않습니다. 
---
= Linux 배포를 위한 노드 구성 파일 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 구성 파일은 StorageGRID 호스트 서비스에서 노드를 시작하고 적절한 네트워크 및 블록 스토리지 리소스에 연결하는 데 필요한 정보를 제공하는 작은 텍스트 파일입니다. 노드 구성 파일은 가상 노드에 사용되며 어플라이언스 노드에 사용되지 않습니다.


NOTE: "Linux"는 RHEL, Ubuntu 또는 Debian 배포를 의미합니다.  지원되는 버전 목록은 다음을 참조하세요. https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴(IMT)"^] .



== 노드 구성 파일의 위치입니다

각 StorageGRID 노드의 구성 파일을 `/etc/storagegrid/nodes` 노드가 실행될 호스트의 디렉토리에 배치합니다. 예를 들어 HostA에서 관리자 노드 1개, 게이트웨이 노드 1개 및 스토리지 노드 1개를 실행하려면 HostA에 3개의 노드 구성 파일을 배치해야 `/etc/storagegrid/nodes` 합니다.

vim 또는 nano와 같은 텍스트 편집기를 사용하여 각 호스트에서 직접 구성 파일을 만들거나 다른 곳에서 구성 파일을 만들어 각 호스트로 이동할 수 있습니다.



== 노드 구성 파일 이름 지정

구성 파일의 이름이 중요합니다. 형식은 입니다 `node-name.conf`. 여기서 `node-name` 는 노드에 할당한 이름입니다. 이 이름은 StorageGRID Installer에 나타나며 노드 마이그레이션과 같은 노드 유지 관리 작업에 사용됩니다.

노드 이름은 다음 규칙을 따라야 합니다.

* 고유해야 합니다
* 문자로 시작해야 합니다
* A ~ Z 및 a ~ z 문자를 포함할 수 있습니다
* 0에서 9 사이의 숫자를 포함할 수 있습니다
* 하나 이상의 하이픈(-)을 포함할 수 있습니다.
* 확장자는 32자 이하여야 합니다 `.conf`


에서 이러한 명명 규칙을 따르지 않는 파일은 `/etc/storagegrid/nodes` 호스트 서비스에서 구문 분석되지 않습니다.

그리드에 대해 멀티 사이트 토폴로지를 계획한 경우 일반적인 노드 명명 규칙은 다음과 같습니다.

`site-nodetype-nodenumber.conf`

예를 들어, 데이터 센터 1의 첫 번째 관리자 노드와 `dc2-sn3.conf` 데이터 센터 2의 세 번째 스토리지 노드에 을 사용할 수 `dc1-adm1.conf` 있습니다. 그러나 모든 노드 이름이 명명 규칙을 따른다 하더라도 원하는 스키마를 사용할 수 있습니다.



== 노드 구성 파일의 내용입니다

구성 파일에는 키/값 쌍이 포함되어 있으며 한 줄에 하나의 키와 하나의 값이 있습니다. 각 키/값 쌍에 대해 다음 규칙을 따르십시오.

* 키와 값은 등호(`=`)와 선택적 공백으로 구분해야 합니다.
* 키에는 공백이 포함될 수 없습니다.
* 값에는 포함된 공백이 포함될 수 있습니다.
* 선행 또는 후행 공백은 무시됩니다.


다음 표에서는 지원되는 모든 키의 값을 정의합니다. 각 키에는 다음 중 하나가 지정됩니다.

* * 필수 *: 모든 노드 또는 지정된 노드 유형에 필요합니다
* * 모범 사례 *: 선택 사항이지만 권장됨
* * 선택 사항 *: 모든 노드에 대해 선택 사항입니다




=== 관리 네트워크 키



==== 관리_IP

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
Linux 기반 노드를 설치하는 데 사용하려는 관리 노드의 그리드 네트워크 IPv4 주소입니다.  복구를 위해 기본 관리 노드의 IP가 있으면 이를 사용하고, 그렇지 않으면 기본이 아닌 관리 노드의 IP를 사용합니다.  이 매개변수를 생략하면 노드는 mDNS를 사용하여 기본 관리 노드를 검색하려고 시도합니다.

link:how-grid-nodes-discover-primary-admin-node.html["그리드 노드가 기본 관리자 노드를 검색하는 방법"]

* 참고 *: 이 값은 기본 관리 노드에서 무시되고 금지될 수 있습니다.
 a| 
모범 사례

|===


==== 관리 네트워크 구성

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
DHCP, 정적 또는 비활성
 a| 
선택 사항

|===


==== 관리_네트워크_ESL

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
쉼표로 구분된 서브넷 목록으로, 이 노드가 Admin Network 게이트웨이를 사용하여 통신해야 하는 CIDR 표기법을 사용합니다.

예: `172.16.0.0/21,172.17.0.0/21`
 a| 
선택 사항

|===


==== Admin_network_Gateway를 선택합니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
이 노드에 대한 로컬 관리 네트워크 게이트웨이의 IPv4 주소입니다. admin_network_ip 및 admin_network_mask에 의해 정의된 서브넷에 있어야 합니다. DHCP 구성 네트워크에서는 이 값이 무시됩니다.

예:

`1.1.1.1`

`10.224.4.81`
 a| 
가 지정된 경우 `ADMIN_NETWORK_ESL` 필수입니다. 그렇지 않으면 선택 사항입니다.

|===


==== admin_network_ip을 선택합니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
관리 네트워크에서 이 노드의 IPv4 주소입니다. 이 키는 admin_network_Config=static인 경우에만 필요합니다. 다른 값에 대해서는 지정하지 마십시오.

예:

`1.1.1.1`

`10.224.4.81`
 a| 
admin_network_config = static 인 경우 필요합니다.

그렇지 않으면 선택 사항입니다.

|===


==== admin_network_MAC입니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
컨테이너의 관리 네트워크 인터페이스에 대한 MAC 주소입니다.

이 필드는 선택 사항입니다. 생략할 경우 MAC 주소가 자동으로 생성됩니다.

콜론으로 구분된 6쌍의 16진수 숫자이어야 합니다.

예: `b2:9c:02:c2:27:10`
 a| 
선택 사항

|===


==== admin_network_mask를 선택합니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
이 노드의 IPv4 넷마스크는 관리자 네트워크에서 설정합니다. admin_network_config = static 인 경우 이 키를 지정하고 다른 값에 대해서는 이 키를 지정하지 마십시오.

예:

`255.255.255.0`

`255.255.248.0`
 a| 
admin_network_ip을 지정하고 admin_network_Config=static인 경우 필수입니다.

그렇지 않으면 선택 사항입니다.

|===


==== admin_network_mtu

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
Admin Network의 이 노드에 대한 MTU(Maximum Transmission Unit)입니다. admin_network_Config=DHCP인지 지정하지 마십시오. 지정된 경우 값은 1280에서 9216 사이여야 합니다. 생략하면 1500이 사용됩니다.

점보 프레임을 사용하려면 MTU를 9000과 같은 점보 프레임에 적합한 값으로 설정합니다. 그렇지 않으면 기본값을 유지합니다.

* 중요 *: 네트워크의 MTU 값은 노드가 연결된 스위치 포트에 구성된 값과 일치해야 합니다. 그렇지 않으면 네트워크 성능 문제 또는 패킷 손실이 발생할 수 있습니다.

예:

`1500`

`8192`
 a| 
선택 사항

|===


==== admin_network_target 을 선택합니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
StorageGRID 노드에서 관리자 네트워크 액세스에 사용할 호스트 디바이스의 이름입니다. 네트워크 인터페이스 이름만 지원됩니다. 일반적으로 GRID_NETWORK_TARGET 또는 CLIENT_NETWORK_TARGET에 지정된 것과 다른 인터페이스 이름을 사용합니다.

* 참고 *: 네트워크 대상으로 연결 또는 브리지 장치를 사용하지 마십시오. 연결 디바이스 위에 VLAN(또는 기타 가상 인터페이스)을 구성하거나 브리지 및 가상 이더넷(veth) 쌍을 사용합니다.

* 모범 사례 *: 이 노드에 처음에 관리 네트워크 IP 주소가 없을 경우에도 값을 지정하십시오. 그런 다음 나중에 호스트에서 노드를 다시 구성하지 않고도 관리 네트워크 IP 주소를 추가할 수 있습니다.

예:

`bond0.1002`

`ens256`
 a| 
모범 사례

|===


==== admin_network_target_type입니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
인터페이스(이 값만 지원됩니다.)
 a| 
선택 사항

|===


==== admin_network_target_type_interface_clone_MAC

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
참 또는 거짓

StorageGRID 컨테이너가 관리자 네트워크에서 호스트 호스트 대상 인터페이스의 MAC 주소를 사용하도록 하려면 키를 "true"로 설정합니다.

* 모범 사례: * promiscuous 모드가 필요한 네트워크에서는 admin_network_target_type_interface_clone_MAC 키를 대신 사용합니다.

Linux용 MAC 복제에 대한 자세한 내용은 다음을 참조하세요.link:../swnodes/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 주소 복제에 대한 고려 사항 및 권장 사항"]
 a| 
모범 사례

|===


==== admin_role을 선택합니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
Primary 또는 Non-Primary

이 키는 node_type=vm_Admin_Node인 경우에만 필요하며 다른 노드 유형에 대해서는 지정하지 않습니다.
 a| 
node_type=vm_admin_Node인 경우 필요합니다

그렇지 않으면 선택 사항입니다.

|===


=== 장치 키를 차단합니다



==== Block_device_audit_logs

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
이 노드가 감사 로그의 영구 저장에 사용할 블록 디바이스 특수 파일의 경로 및 이름입니다.

예:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`
 a| 
node_type이 vm_admin_Node인 노드에 필요합니다. 다른 노드 유형에는 지정하지 마십시오.

|===


==== Block_device_RANGEDB_nnn을 선택합니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
이 노드가 영구 오브젝트 스토리지에 사용할 블록 디바이스 특수 파일의 경로 및 이름입니다. 이 키는 node_type=vm_Storage_Node인 노드에만 필요하며 다른 노드 유형에 대해서는 지정하지 않습니다.

block_device_RANGEDB_000 만 필요하며 나머지는 선택 사항입니다. block_device_RANGEDB_000 에 지정된 블록 디바이스는 4TB 이상이어야 하며 다른 블록 디바이스는 더 작을 수 있습니다.

간격을 두지 마십시오. BLOCK_DEVICE_RANGEDB_005를 지정하는 경우 BLOCK_DEVICE_RANGEDB_004도 지정해야 합니다.

* 참고 *: 기존 배포와의 호환성을 위해 업그레이드된 노드에 대해 2자리 키가 지원됩니다.

예:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`
 a| 
필수:

BLOCK_DEVICE_RANGEDB_000

선택 사항:

BLOCK_DEVICE_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002 를 참조하십시오

Block_device_RANGEDB_003 을 참조하십시오

Block_device_RANGEDB_004 를 참조하십시오

Block_device_RANGEDB_005 를 참조하십시오

Block_device_RANGEDB_006

Block_device_RANGEDB_007 을 참조하십시오

Block_device_RANGEDB_008 을 참조하십시오

Block_device_RANGEDB_009 를 참조하십시오

Block_device_RANGEDB_010

Block_device_RANGEDB_011 을 참조하십시오

Block_device_RANGEDB_012 를 참조하십시오

Block_device_RANGEDB_013

Block_device_RANGEDB_014

Block_device_RANGEDB_015 를 참조하십시오

|===


==== BLOCK_DEVICE_Tables

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
이 노드가 데이터베이스 테이블의 영구 저장에 사용할 블록 디바이스 특수 파일의 경로 및 이름입니다. 이 키는 node_type=vm_Admin_Node인 노드에만 필요합니다. 다른 노드 유형에 대해서는 지정하지 마십시오.

예:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`
 a| 
필수 요소입니다

|===


==== BLOCK_DEVICE_VAR_LOCAL

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
이 노드가 영구 스토리지에 사용할 블록 디바이스 특수 파일의 경로 및 `/var/local` 이름입니다.

예:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`
 a| 
필수 요소입니다

|===


=== 클라이언트 네트워크 키



==== client_network_Config

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
DHCP, 정적 또는 비활성
 a| 
선택 사항

|===


==== CLIENT_NETWORK_GATEWAY

[cols="4a,2a"]
|===


 a| 
값
 a| 
지정



 a| 
client_network_ip 및 client_network_mask에 의해 정의된 서브넷에 있어야 하는 이 노드에 대한 로컬 클라이언트 네트워크 게이트웨이의 IPv4 주소입니다. DHCP 구성 네트워크에서는 이 값이 무시됩니다.

예:

`1.1.1.1`

`10.224.4.81`
 a| 
선택 사항

|===


==== client_network_ip

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
클라이언트 네트워크에서 이 노드의 IPv4 주소입니다.

이 키는 client_network_Config = static 일 때만 필요합니다. 다른 값에 대해서는 지정하지 마십시오.

예:

`1.1.1.1`

`10.224.4.81`
 a| 
client_network_Config=static 인 경우 필요합니다

그렇지 않으면 선택 사항입니다.

|===


==== client_network_MAC

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
컨테이너에 있는 클라이언트 네트워크 인터페이스의 MAC 주소입니다.

이 필드는 선택 사항입니다. 생략할 경우 MAC 주소가 자동으로 생성됩니다.

콜론으로 구분된 6쌍의 16진수 숫자이어야 합니다.

예: `b2:9c:02:c2:27:20`
 a| 
선택 사항

|===


==== client_network_mask.(클라이언트 네트워크 마스크

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
클라이언트 네트워크의 이 노드에 대한 IPv4 넷마스크입니다.

client_network_config = static 인 경우 이 키를 지정하고 다른 값에는 이 키를 지정하지 마십시오.

예:

`255.255.255.0`

`255.255.248.0`
 a| 
client_network_ip을 지정하고 client_network_Config=static인 경우 필수입니다

그렇지 않으면 선택 사항입니다.

|===


==== client_network_mtu

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
Client Network의 이 노드에 대한 MTU(Maximum Transmission Unit)입니다. client_network_Config = DHCP인지 지정하지 마십시오. 지정된 경우 값은 1280에서 9216 사이여야 합니다. 생략하면 1500이 사용됩니다.

점보 프레임을 사용하려면 MTU를 9000과 같은 점보 프레임에 적합한 값으로 설정합니다. 그렇지 않으면 기본값을 유지합니다.

* 중요 *: 네트워크의 MTU 값은 노드가 연결된 스위치 포트에 구성된 값과 일치해야 합니다. 그렇지 않으면 네트워크 성능 문제 또는 패킷 손실이 발생할 수 있습니다.

예:

`1500`

`8192`
 a| 
선택 사항

|===


==== client_network_target 을 선택합니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
StorageGRID 노드에서 클라이언트 네트워크 액세스에 사용할 호스트 디바이스의 이름입니다. 네트워크 인터페이스 이름만 지원됩니다. 일반적으로 GRID_NETWORK_TARGET 또는 ADMIN_NETWORK_TARGET에 지정된 것과 다른 인터페이스 이름을 사용합니다.

* 참고 *: 네트워크 대상으로 연결 또는 브리지 장치를 사용하지 마십시오. 연결 디바이스 위에 VLAN(또는 기타 가상 인터페이스)을 구성하거나 브리지 및 가상 이더넷(veth) 쌍을 사용합니다.

* 모범 사례: * 이 노드에 클라이언트 네트워크 IP 주소가 없을 경우에도 값을 지정하십시오. 그런 다음 나중에 호스트에서 노드를 다시 구성하지 않고도 클라이언트 네트워크 IP 주소를 추가할 수 있습니다.

예:

`bond0.1003`

`ens423`
 a| 
모범 사례

|===


==== CLIENT_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
인터페이스(지원되는 값만 해당)
 a| 
선택 사항

|===


==== client_network_target_type_interface_clone_MAC

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
참 또는 거짓

StorageGRID 컨테이너가 클라이언트 네트워크의 호스트 대상 인터페이스의 MAC 주소를 사용하도록 하려면 키를 "true"로 설정합니다.

* 모범 사례: * promiscuous 모드가 필요한 네트워크에서는 대신 client_network_target_type_interface_clone_mac 키를 사용합니다.

Linux용 MAC 복제에 대한 자세한 내용은 다음을 참조하세요.link:../swnodes/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 주소 복제에 대한 고려 사항 및 권장 사항"]
 a| 
모범 사례

|===


=== 그리드 네트워크 키



==== GRID_NETWORK_CONFIG(그리드 네트워크 구성

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
고정 또는 DHCP

지정하지 않으면 기본적으로 정적입니다.
 a| 
모범 사례

|===


==== GRID_NETWORK_Gateway를 참조하십시오

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
GRID_NETWORK_IP 및 GRID_NETWORK_MASK로 정의된 서브넷에 있어야 하는 이 노드에 대한 로컬 Grid Network 게이트웨이의 IPv4 주소입니다. DHCP 구성 네트워크에서는 이 값이 무시됩니다.

그리드 네트워크가 게이트웨이가 없는 단일 서브넷인 경우, 서브넷(X. Y.Z.1)의 표준 게이트웨이 주소 또는 이 노드의 GRID_NETWORK_IP 값을 사용합니다. 두 값 중 하나를 사용하면 미래의 그리드 네트워크 확장이 단순화됩니다.
 a| 
필수 요소입니다

|===


==== GRID_NETWORK_IP입니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
Grid Network에서 이 노드의 IPv4 주소입니다. 이 키는 GRID_NETWORK_CONFIG = static 일 때만 필요합니다. 다른 값에 대해서는 지정하지 마십시오.

예:

`1.1.1.1`

`10.224.4.81`
 a| 
GRID_NETWORK_CONFIG = STATIC인 경우 필요합니다

그렇지 않으면 선택 사항입니다.

|===


==== GRID_NETWORK_MAC을 선택합니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
컨테이너의 그리드 네트워크 인터페이스에 대한 MAC 주소입니다.

콜론으로 구분된 6쌍의 16진수 숫자이어야 합니다.

예: `b2:9c:02:c2:27:30`
 a| 
선택 사항

생략할 경우 MAC 주소가 자동으로 생성됩니다.

|===


==== GRID_NETWORK_MASK 를 참조하십시오

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
그리드 네트워크에서 이 노드에 대한 IPv4 넷마스크입니다. GRID_NETWORK_CONFIG = STATIC인 경우 이 키를 지정하고 다른 값에는 이 키를 지정하지 마십시오.

예:

`255.255.255.0`

`255.255.248.0`
 a| 
GRID_NETWORK_IP를 지정하고 GRID_NETWORK_CONFIG=STATIC인 경우에 필요합니다.

그렇지 않으면 선택 사항입니다.

|===


==== GRID_NETWORK_MTU 를 참조하십시오

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
Grid Network의 이 노드에 대한 MTU(Maximum Transmission Unit)입니다. GRID_NETWORK_CONFIG=DHCP인지 지정하지 마십시오. 지정된 경우 값은 1280에서 9216 사이여야 합니다. 생략하면 1500이 사용됩니다.

점보 프레임을 사용하려면 MTU를 9000과 같은 점보 프레임에 적합한 값으로 설정합니다. 그렇지 않으면 기본값을 유지합니다.

* 중요 *: 네트워크의 MTU 값은 노드가 연결된 스위치 포트에 구성된 값과 일치해야 합니다. 그렇지 않으면 네트워크 성능 문제 또는 패킷 손실이 발생할 수 있습니다.

* 중요 *: 최상의 네트워크 성능을 얻으려면 모든 노드를 그리드 네트워크 인터페이스에서 유사한 MTU 값으로 구성해야 합니다. 개별 노드의 그리드 네트워크에 대한 MTU 설정에 상당한 차이가 있을 경우 * Grid Network MTU mismatch * 경고가 트리거됩니다. MTU 값은 모든 네트워크 유형에 대해 같을 필요는 없습니다.

예:

`1500`

`8192`
 a| 
선택 사항

|===


==== GRID_NETWORK_TARGET

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
StorageGRID 노드에서 그리드 네트워크 액세스에 사용할 호스트 디바이스의 이름입니다. 네트워크 인터페이스 이름만 지원됩니다. 일반적으로 admin_network_target 또는 client_network_target 에 지정된 것과 다른 인터페이스 이름을 사용합니다.

* 참고 *: 네트워크 대상으로 연결 또는 브리지 장치를 사용하지 마십시오. 연결 디바이스 위에 VLAN(또는 기타 가상 인터페이스)을 구성하거나 브리지 및 가상 이더넷(veth) 쌍을 사용합니다.

예:

`bond0.1001`

`ens192`
 a| 
필수 요소입니다

|===


==== GRID_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
인터페이스(이 값만 지원됩니다.)
 a| 
선택 사항

|===


==== GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
참 또는 거짓

StorageGRID 컨테이너가 그리드 네트워크에서 호스트 대상 인터페이스의 MAC 주소를 사용하도록 키 값을 "true"로 설정합니다.

* 모범 사례: * promiscuous 모드가 필요한 네트워크에서는 grid_network_target_type_interface_clone_mac 키를 대신 사용합니다.

Linux용 MAC 복제에 대한 자세한 내용은 다음을 참조하세요.link:../swnodes/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 주소 복제에 대한 고려 사항 및 권장 사항"]
 a| 
모범 사례

|===


=== 설치 암호 키(임시)



==== 사용자 지정_임시_암호_해시

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
기본 관리자 노드의 경우 설치 중에 StorageGRID 설치 API에 대한 기본 임시 암호를 설정합니다.

* 참고 *: 기본 관리자 노드에서만 설치 암호를 설정합니다. 다른 노드 유형에 암호를 설정하려고 하면 노드 구성 파일의 유효성 검사가 실패합니다.

이 값을 설정해도 설치가 완료된 경우 아무런 영향이 없습니다.

이 키를 생략하면 기본적으로 임시 암호가 설정되지 않습니다. 또는 StorageGRID 설치 API를 사용하여 임시 암호를 설정할 수 있습니다.

8자 이상 32자 이하의 암호 형식을 가진 SHA-512 암호 `$6$<salt>$<password hash>` 해시여야 `crypt()` 합니다.

이 해시는 SHA-512 모드의 명령과 같은 CLI 툴을 사용하여 생성할 수 `openssl passwd` 있습니다.
 a| 
모범 사례

|===


=== 인터페이스 키입니다



==== interface_target_nnnn입니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
이 노드에 추가할 추가 인터페이스의 이름 및 선택적 설명입니다. 각 노드에 여러 개의 인터페이스를 추가할 수 있습니다.

_nnnn_의 경우 추가할 각 interface_target 항목의 고유 번호를 지정합니다.

값에 대해 베어 메탈 호스트의 물리적 인터페이스 이름을 지정합니다. 그런 다음 필요에 따라 쉼표를 추가하고 인터페이스에 대한 설명을 입력합니다. 이 설명은 VLAN 인터페이스 페이지와 HA 그룹 페이지에 표시됩니다.

예: `INTERFACE_TARGET_0001=ens256, Trunk`

트렁크 인터페이스를 추가하는 경우 StorageGRID에서 VLAN 인터페이스를 구성해야 합니다. 액세스 인터페이스를 추가할 경우 인터페이스를 HA 그룹에 직접 추가할 수 있으며, VLAN 인터페이스를 구성할 필요가 없습니다.
 a| 
선택 사항

|===


=== 최대 RAM 키



==== 최대 RAM

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
이 노드가 사용할 수 있는 최대 RAM 양입니다. 이 키를 생략하면 노드의 메모리 제한 사항이 없게 됩니다. 운영 레벨 노드에 대해 이 필드를 설정할 때 총 시스템 RAM보다 최소 24GB 및 16 ~ 32GB 적은 값을 지정합니다.

* 참고 *: RAM 값은 노드의 실제 메타데이터 예약 공간에 영향을 줍니다. 를 link:../admin/managing-object-metadata-storage.html["메타데이터 예약된 공간에 대한 설명입니다"]참조하십시오.

이 필드의 형식은 `_numberunit_`, WHERE `_unit_` `b`, `k`, `m` 또는 `g`입니다.

예:

`24g`

`38654705664b`

* 참고 *: 이 옵션을 사용하려면 메모리 cgroup에 대한 커널 지원을 활성화해야 합니다.
 a| 
선택 사항

|===


=== 노드 유형 키입니다



==== node_type입니다

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
노드 유형:

* VM_Admin_Node
* VM_스토리지_노드
* VM_Archive_Node
* VM_API_게이트웨이

 a| 
필수 요소입니다

|===


==== 스토리지 유형

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
스토리지 노드에 포함된 객체 유형을 정의합니다. 자세한 내용은 을 link:../primer/what-storage-node-is.html#types-of-storage-nodes["스토리지 노드 유형"]참조하십시오. 이 키는 node_type=vm_Storage_Node인 노드에만 필요하며 다른 노드 유형에 대해서는 지정하지 않습니다. 스토리지 유형:

* 결합된
* 데이터
* 메타데이터


* 참고 *: storage_type이 지정되지 않은 경우 스토리지 노드 유형은 기본적으로 결합(데이터 및 메타데이터)으로 설정됩니다.
 a| 
선택 사항

|===


=== 포트 재매핑 키


NOTE: 포트 리매핑 지원은 더 이상 제공되지 않으며 향후 릴리스에서 제거될 예정입니다. 재매핑된 포트를 제거하려면 다음을 참조하세요.link:../maintain/removing-port-remaps-on-bare-metal-hosts.html["베어 메탈 호스트에서 포트 재맵을 제거합니다"] .



==== port_remap 을 참조하십시오

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
노드에서 내부 그리드 노드 통신 또는 외부 통신을 위해 사용하는 모든 포트를 다시 매핑합니다. 엔터프라이즈 네트워킹 정책으로 StorageGRID에서 사용하는 하나 이상의 포트를 제한하는 경우 또는 에 설명된 대로 포트를 다시 매핑해야 link:../network/internal-grid-node-communications.html["내부 그리드 노드 통신"]link:../network/external-communications.html["외부 통신"]합니다.

* 중요 *: 로드 밸런서 엔드포인트를 구성하기 위해 사용하려는 포트를 다시 매핑하지 마십시오.

* 참고 *: port_remap 만 설정된 경우 지정하는 매핑이 인바운드 및 아웃바운드 통신 모두에 사용됩니다. port_remap_inbound 도 지정된 경우 port_remap 은 아웃바운드 통신에만 적용됩니다.

사용되는 형식은 다음과 같습니다 `_network type_/_protocol_/_default port used by grid node_/_new port_`. 여기서 `_network type_` 그리드, 관리자 또는 클라이언트이고 `_protocol_` TCP 또는 UDP입니다.

예: `PORT_REMAP = client/tcp/18082/443`

쉼표로 구분된 목록을 사용하여 여러 포트를 다시 매핑할 수도 있습니다.

예: `PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80`
 a| 
선택 사항

|===


==== port_remap_inbound 를 참조하십시오

[cols="4a,2a"]
|===
| 값 | 지정 


 a| 
인바운드 통신을 지정된 포트에 다시 매핑합니다. port_remap_inbound 를 지정하지만 port_remap 의 값을 지정하지 않으면 포트의 아웃바운드 통신이 변경되지 않습니다.

* 중요 *: 로드 밸런서 엔드포인트를 구성하기 위해 사용하려는 포트를 다시 매핑하지 마십시오.

사용되는 형식은 다음과 같습니다 `_network type_/_protocol_/_remapped port_/_default port used by grid node_`. 여기서 `_network type_` 그리드, 관리자 또는 클라이언트이고 `_protocol_` TCP 또는 UDP입니다.

예: `PORT_REMAP_INBOUND = grid/tcp/3022/22`

쉼표로 구분된 목록을 사용하여 여러 인바운드 포트를 다시 매핑할 수도 있습니다.

예: `PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22`
 a| 
선택 사항

|===