---
permalink: swnodes/deploying-storagegrid-node-as-virtual-machine.html 
sidebar: sidebar 
keywords: how to deploy grid nodes in vsphere or vsphere web client, port, remap, port remap, vmware 
summary: VMware vSphere Web Client를 사용하여 각 그리드 노드를 가상 머신으로 구축합니다. 배포 중에는 각 그리드 노드가 하나 이상의 StorageGRID 네트워크에 생성되고 연결됩니다. 
---
= StorageGRID 노드를 가상 머신(VMware)으로 배포
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere Web Client를 사용하여 각 그리드 노드를 가상 머신으로 구축합니다. 배포 중에는 각 그리드 노드가 하나 이상의 StorageGRID 네트워크에 생성되고 연결됩니다.

StorageGRID 어플라이언스 스토리지 노드를 배포해야 하는 경우 를 참조하십시오. https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/deploying-appliance-storage-node.html["어플라이언스 스토리지 노드 구축"^]

선택적으로 노드의 전원을 켜기 전에 노드 포트를 재매핑하거나 노드의 CPU 또는 메모리 설정을 늘릴 수 있습니다.

.시작하기 전에
* link:index.html["설치 계획 및 준비"]소프트웨어, CPU 및 RAM, 스토리지 및 성능에 대한 요구 사항을 검토하고 이해했습니다.
* VMware vSphere 하이퍼바이저에 대해 잘 알고 있으며 이 환경에서 가상 머신을 구축한 경험이 있습니다.
+

NOTE: VMware 툴과 유사한 오픈 소스 구축 패키지인 이 `open-vm-tools` StorageGRID 가상 머신은 포함되어 있습니다. VMware Tools를 수동으로 설치할 필요가 없습니다.

* VMware용 StorageGRID 설치 아카이브의 올바른 버전을 다운로드하고 압축을 풀었습니다.
+

CAUTION: 확장 또는 복구 작업의 일부로 새 노드를 구축하는 경우 현재 그리드에서 실행 중인 StorageGRID 버전을 사용해야 합니다.

* StorageGRID 가상 머신 디스크(`.vmdk`) 파일이 있는 경우:


[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
----
*  `.ovf`배포하려는 각 그리드 노드 유형에 대한 및 `.mf` 파일이 있습니다.
+
[cols="1a,1a"]
|===
| 파일 이름 | 설명 


| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
기본 관리 노드의 템플릿 파일 및 매니페스트 파일



| vsphere - non-primary-admin.ovf vsphere - non-primary-admin.mf  a| 
비 기본 관리 노드에 대한 템플릿 파일 및 매니페스트 파일입니다.



| vsphere-storage.ovf vsphere-storage.mf  a| 
스토리지 노드의 템플릿 파일 및 매니페스트 파일



| vsphere-gateway.ovf vsphere-gateway.mf  a| 
게이트웨이 노드의 템플릿 파일 및 매니페스트 파일

|===
*  `.vdmk` `.ovf`, 및 `.mf` 파일은 모두 같은 디렉터리에 있습니다.
* 장애 도메인을 최소화할 계획이 있습니다. 예를 들어 단일 vSphere ESXi 호스트에 모든 게이트웨이 노드를 배포하면 안 됩니다.
+

CAUTION: 운영 구축 환경에서는 단일 가상 머신에서 스토리지 노드를 두 개 이상 실행하지 마십시오. 허용할 수 없는 장애 도메인 문제가 발생할 경우 동일한 ESXi 호스트에서 여러 가상 머신을 실행하지 마십시오.

* 확장 또는 복구 작업의 일부로 노드를 구축하는 경우 또는 이 있는 link:../expand/index.html["StorageGRID 시스템 확장을 위한 지침"]link:../maintain/index.html["복구 및 유지 관리 지침"]것입니다.
* StorageGRID 노드를 NetApp ONTAP 시스템에서 할당된 스토리지가 있는 가상 머신으로 구축하는 경우 볼륨에 FabricPool 계층화 정책이 설정되어 있지 않은 것이 확인되었습니다. 예를 들어 StorageGRID 노드가 VMware 호스트에서 가상 머신으로 실행 중인 경우 노드의 데이터 저장소를 백업하는 볼륨에 FabricPool 계층화 정책이 설정되어 있지 않은지 확인합니다. StorageGRID 노드와 함께 사용되는 볼륨에 대해 FabricPool 계층화를 사용하지 않도록 설정하면 문제 해결과 스토리지 작업이 간소화됩니다.
+

NOTE: FabricPool를 사용하여 StorageGRID 관련 데이터를 StorageGRID 자체로 계층화하지 마십시오. StorageGRID 데이터를 StorageGRID로 다시 계층화하면 문제 해결과 운영 복잡성이 늘어납니다.



.이 작업에 대해
이 지침에 따라 초기에 VMware 노드를 배포하거나, 확장 시 새 VMware 노드를 추가하거나, 복구 작업의 일부로 VMware 노드를 대체하십시오. 단계에 설명된 경우를 제외하고 노드 구축 절차는 관리 노드, 스토리지 노드 및 게이트웨이 노드를 포함한 모든 노드 유형에 대해 동일합니다.

새 StorageGRID 시스템을 설치하는 경우:

* 노드는 원하는 순서로 배포할 수 있습니다.
* 각 가상 시스템이 그리드 네트워크를 통해 기본 관리 노드에 연결할 수 있는지 확인해야 합니다.
* 그리드를 구성하기 전에 모든 그리드 노드를 배포해야 합니다.


확장 또는 복구 작업을 수행하는 경우:

* 새 가상 머신이 그리드 네트워크를 통해 다른 모든 노드에 연결할 수 있는지 확인해야 합니다.


노드의 포트를 다시 매핑해야 하는 경우 포트 재매핑 구성이 완료될 때까지 새 노드의 전원을 켜서는 안 됩니다.


NOTE: 포트 리매핑 지원은 더 이상 제공되지 않으며 향후 릴리스에서 제거될 예정입니다. 재매핑된 포트를 제거하려면 다음을 참조하세요.link:../maintain/removing-port-remaps-on-bare-metal-hosts.html["베어 메탈 호스트에서 포트 재맵을 제거합니다"] .

.단계
. vCenter를 사용하여 OVF 템플릿을 구축합니다.
+
URL을 지정하는 경우 다음 파일이 포함된 폴더를 가리킵니다. 그렇지 않으면 로컬 디렉토리에서 각 파일을 선택합니다.

+
[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
vsphere-_node_.ovf
vsphere-_node_.mf
----
+
예를 들어 처음 구축하는 노드인 경우 다음 파일을 사용하여 StorageGRID 시스템의 기본 관리 노드를 배포합니다.

+
[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
vsphere-primary-admin.ovf
vsphere-primary-admin.mf
----
. 가상 머신의 이름을 지정합니다.
+
표준 방법은 가상 머신과 그리드 노드 모두에 동일한 이름을 사용하는 것입니다.

. 가상 머신을 적절한 vApp 또는 리소스 풀에 배치합니다.
. 기본 관리자 노드를 배포하는 경우 최종 사용자 라이센스 계약을 읽고 동의합니다.
+
vCenter 버전에 따라 최종 사용자 라이센스 계약에 동의하고, 가상 머신의 이름을 지정하고, 데이터 저장소를 선택할 때 단계의 순서가 달라집니다.

. 가상 머신에 사용할 스토리지를 선택합니다.
+
복구 작업의 일부로 노드를 구축하는 경우 의 지침에 따라 <<step_recovery_storage,스토리지 복구 단계입니다>>새 가상 디스크를 추가하거나, 오류가 발생한 그리드 노드에서 가상 하드 디스크를 다시 연결하거나, 둘 다 수행합니다.

+
스토리지 노드를 구축할 때는 3개 이상의 스토리지 볼륨을 사용하고 각 스토리지 볼륨은 4TB 이상을 사용합니다. 볼륨 0에 4TB 이상을 할당해야 합니다.

+

NOTE: Storage Node.ovf 파일은 스토리지를 위한 여러 VMDK를 정의합니다. 이러한 VMDK가 스토리지 요구 사항을 충족하지 않는 경우 노드의 전원을 켜기 전에 해당 VMDK를 제거하고 스토리지에 적절한 VMDK 또는 RDM을 할당해야 합니다. vmdks는 VMware 환경에서 일반적으로 사용되며 관리하기가 더 쉽습니다. 반면 RDM은 100MB 이상의 큰 개체 크기를 사용하는 워크로드에 더 나은 성능을 제공할 수 있습니다.

+

NOTE: 일부 StorageGRID 설치에서는 일반 가상화 워크로드보다 더 크고 사용 빈도가 높은 스토리지 볼륨을 사용할 수 있습니다. 최적의 성능을 얻으려면 등의 일부 하이퍼바이저 매개 변수를 조정해야 할 수 `MaxAddressableSpaceTB` 있습니다. 성능 저하가 발생하는 경우 가상화 지원 리소스에 문의하여 작업 부하별 구성 조정을 통해 해당 환경이 이점을 누릴 수 있는지 확인하십시오.

. 네트워크를 선택합니다.
+
각 소스 네트워크의 대상 네트워크를 선택하여 노드가 사용할 StorageGRID 네트워크를 결정합니다.

+
** 그리드 네트워크가 필요합니다. vSphere 환경에서 대상 네트워크를 선택해야 합니다. + 그리드 네트워크는 모든 내부 StorageGRID 트래픽에 사용됩니다. 그리드의 모든 노드, 모든 사이트와 서브넷에 걸쳐 연결을 제공합니다. 그리드 네트워크의 모든 노드는 다른 모든 노드와 통신할 수 있어야 합니다.
** 관리 네트워크를 사용하는 경우 vSphere 환경에서 다른 대상 네트워크를 선택합니다. 관리 네트워크를 사용하지 않는 경우 그리드 네트워크에 대해 선택한 것과 동일한 대상을 선택합니다.
** 클라이언트 네트워크를 사용하는 경우 vSphere 환경에서 다른 대상 네트워크를 선택합니다. 클라이언트 네트워크를 사용하지 않는 경우 그리드 네트워크에 대해 선택한 것과 동일한 대상을 선택합니다.
** Admin 또는 Client 네트워크를 사용하는 경우 노드가 동일한 Admin 또는 Client 네트워크에 있을 필요가 없습니다.


. 템플릿 사용자 정의 * 의 경우 필요한 StorageGRID 노드 속성을 구성합니다.
+
.. 노드 이름 * 을 입력합니다.
+

NOTE: 그리드 노드를 복구하는 경우 복구할 노드의 이름을 입력해야 합니다.

.. 임시 설치 암호를 지정하려면 * 임시 설치 암호 * 드롭다운을 사용하십시오. 그러면 새 노드가 그리드에 합류하기 전에 VM 콘솔이나 StorageGRID 설치 API에 액세스하거나 SSH를 사용할 수 있습니다.
+

NOTE: 임시 설치 암호는 노드 설치 중에만 사용됩니다. 노드가 그리드에 추가된 후 복구 패키지의 파일에link:../admin/change-node-console-password.html["노드 콘솔 암호"] 나열된 를 사용하여 액세스할 수 있습니다. `Passwords.txt`

+
*** * 노드 이름 사용 *: * 노드 이름 * 필드에 입력한 값이 임시 설치 암호로 사용됩니다.
*** * 사용자 정의 암호 사용 *: 사용자 정의 암호는 임시 설치 암호로 사용됩니다.
*** * 비밀번호 비활성화 * : 임시 설치 비밀번호가 사용되지 않습니다. 설치 문제를 디버깅하기 위해 VM에 액세스해야 하는 경우 를 참조하십시오link:troubleshooting-installation-issues.html["설치 문제를 해결합니다"].


.. 사용자 정의 암호 사용 * 을 선택한 경우 * 사용자 정의 암호 * 필드에 사용할 임시 설치 암호를 지정합니다.
.. Grid Network(eth0) * 섹션에서 * Grid 네트워크 IP 구성 * 에 대해 static 또는 DHCP를 선택합니다.
+
*** 정자를 선택한 경우 * 그리드 네트워크 IP *, * 그리드 네트워크 마스크 *, * 그리드 네트워크 게이트웨이 * 및 * 그리드 네트워크 MTU * 를 입력합니다.
*** DHCP를 선택하면 * 그리드 네트워크 IP *, * 그리드 네트워크 마스크 * 및 * 그리드 네트워크 게이트웨이 * 가 자동으로 할당됩니다.


.. Primary Admin IP * 필드에 Grid Network에 대한 기본 관리 노드의 IP 주소를 입력합니다.
+

NOTE: 구축하는 노드가 기본 관리 노드인 경우에는 이 단계가 적용되지 않습니다.

+
기본 관리 노드 IP 주소를 생략하면 기본 관리 노드 또는 admin_IP가 구성된 다른 그리드 노드가 동일한 서브넷에 있는 경우 IP 주소가 자동으로 검색됩니다. 그러나 여기서 기본 관리 노드 IP 주소를 설정하는 것이 좋습니다.

.. 관리 네트워크(eth1) * 섹션에서 * 관리 네트워크 IP 구성 * 에 대해 정적, DHCP 또는 비활성화를 선택합니다.
+
*** 관리 네트워크를 사용하지 않으려면 비활성화를 선택하고 관리 네트워크 IP에 * 0.0.0.0 * 을 입력합니다. 다른 필드는 비워 둘 수 있습니다.
*** static을 선택한 경우 * Admin network ip *, * Admin network mask *, * Admin network gateway *, * Admin network mtu * 를 입력합니다.
*** static을 선택한 경우 * Admin network external subnet list * 를 입력합니다. 또한 게이트웨이를 구성해야 합니다.
*** DHCP를 선택하면 * 관리 네트워크 IP *, * 관리 네트워크 마스크 * 및 * 관리 네트워크 게이트웨이 * 가 자동으로 할당됩니다.


.. 클라이언트 네트워크(eth2) * 섹션에서 * 클라이언트 네트워크 IP 구성 * 에 대해 정적, DHCP 또는 비활성화를 선택합니다.
+
*** 클라이언트 네트워크를 사용하지 않으려면 비활성화를 선택하고 클라이언트 네트워크 IP에 * 0.0.0.0 * 을 입력합니다. 다른 필드는 비워 둘 수 있습니다.
*** static을 선택한 경우 * Client network IP *, * Client network mask *, * Client network gateway *, * Client network mtu * 를 입력합니다.
*** DHCP를 선택하면 * 클라이언트 네트워크 IP *, * 클라이언트 네트워크 마스크 * 및 * 클라이언트 네트워크 게이트웨이 * 가 자동으로 할당됩니다.




. 가상 시스템 구성을 검토하고 필요한 사항을 변경합니다.
. 완료할 준비가 되면 * 마침 * 을 선택하여 가상 머신 업로드를 시작합니다.
. [[STEP_RECOVERY_STORAGE]] 이 노드를 복구 작업의 일부로 배포했으며 전체 노드 복구가 아닌 경우 구축이 완료된 후 다음 단계를 수행하십시오.
+
.. 가상 컴퓨터를 마우스 오른쪽 단추로 클릭하고 * 설정 편집 * 을 선택합니다.
.. 스토리지에 지정된 각 기본 가상 하드 디스크를 선택하고 * 제거 * 를 선택합니다.
.. 데이터 복구 상황에 따라 저장소 요구 사항에 따라 새 가상 디스크를 추가하거나 이전에 제거된 장애 그리드 노드에서 보존된 가상 하드 디스크를 다시 연결하거나 두 디스크 모두를 다시 연결합니다.
+
다음 중요 지침을 참고하십시오.

+
*** 새 디스크를 추가하는 경우 노드 복구 전에 사용한 것과 동일한 유형의 스토리지 디바이스를 사용해야 합니다.
*** Storage Node.ovf 파일은 스토리지를 위한 여러 VMDK를 정의합니다. 이러한 VMDK가 스토리지 요구 사항을 충족하지 않는 경우 노드의 전원을 켜기 전에 해당 VMDK를 제거하고 스토리지에 적절한 VMDK 또는 RDM을 할당해야 합니다. vmdks는 VMware 환경에서 일반적으로 사용되며 관리하기가 더 쉽습니다. 반면 RDM은 100MB 이상의 큰 개체 크기를 사용하는 워크로드에 더 나은 성능을 제공할 수 있습니다.




. [[vmware-remap-ports]] 이 노드에서 사용하는 포트를 다시 매핑해야 하는 경우 다음 단계를 수행합니다.
+
엔터프라이즈 네트워킹 정책이 StorageGRID에서 사용하는 하나 이상의 포트에 대한 액세스를 제한하는 경우 포트를 다시 매핑해야 할 수 있습니다. StorageGRID에서 사용하는 포트는 를 link:../network/index.html["네트워킹 지침"]참조하십시오.

+

NOTE: 로드 밸런서 끝점에 사용되는 포트를 다시 매핑하지 마십시오.

+
.. 새 VM을 선택합니다.
.. 구성 탭에서 * 설정 * > * vApp 옵션 * 을 선택합니다. vApp 옵션 * 의 위치는 vCenter 버전에 따라 다릅니다.
.. Properties * 표에서 port_remap_inbound 및 port_remap을 찾습니다.
.. 포트의 인바운드 및 아웃바운드 통신을 대칭적으로 매핑하려면 * port_remap * 을 선택합니다.
+

NOTE: 포트 리매핑 지원은 더 이상 제공되지 않으며 향후 릴리스에서 제거될 예정입니다. 재매핑된 포트를 제거하려면 다음을 참조하세요.link:../maintain/removing-port-remaps-on-bare-metal-hosts.html["베어 메탈 호스트에서 포트 재맵을 제거합니다"] .

+

NOTE: port_remap 만 설정된 경우 지정하는 매핑이 인바운드 및 아웃바운드 통신 모두에 적용됩니다. port_remap_inbound 도 지정된 경우 port_remap 은 아웃바운드 통신에만 적용됩니다.

+
... Set Value * 를 선택합니다.
... 포트 매핑을 입력합니다.
+
`<network type>/<protocol>/<default port used by grid node>/<new port>`

+
`<network type>` 그리드, 관리자 또는 클라이언트이며 `<protocol>` TCP 또는 UDP입니다.

+
예를 들어 포트 22에서 포트 3022로 ssh 트래픽을 재매핑하려면 다음을 입력합니다.

+
`client/tcp/22/3022`

+
쉼표로 구분된 목록을 사용하여 여러 포트를 다시 매핑할 수 있습니다.

+
예를 들면 다음과 같습니다.

+
`client/tcp/18082/443, client/tcp/18083/80`

... OK * 를 선택합니다.


.. 노드에 대한 인바운드 통신에 사용되는 포트를 지정하려면 * port_remap_inbound * 를 선택합니다.
+

NOTE: port_remap_inbound 를 지정하고 port_remap 의 값을 지정하지 않으면 포트의 아웃바운드 통신이 변경되지 않습니다.

+
... Set Value * 를 선택합니다.
... 포트 매핑을 입력합니다.
+
`<network type>/<protocol>/<remapped inbound port>/<default inbound port used by grid node>`

+
`<network type>` 그리드, 관리자 또는 클라이언트이며 `<protocol>` TCP 또는 UDP입니다.

+
예를 들어, 포트 3022로 전송된 인바운드 SSH 트래픽을 그리드 노드가 포트 22에서 수신하도록 재매핑하려면 다음을 입력합니다.

+
`client/tcp/3022/22`

+
쉼표로 구분된 목록을 사용하여 여러 인바운드 포트를 다시 매핑할 수 있습니다.

+
예를 들면 다음과 같습니다.

+
`grid/tcp/3022/22, admin/tcp/3022/22`

... OK * 를 선택합니다




. 노드의 CPU 또는 메모리를 기본 설정에서 늘리려면 다음을 수행합니다.
+
.. 가상 컴퓨터를 마우스 오른쪽 단추로 클릭하고 * 설정 편집 * 을 선택합니다.
.. 필요한 경우 CPU 수 또는 메모리 양을 변경합니다.
+
메모리 예약 * 을 가상 머신에 할당된 * 메모리 * 와 동일한 크기로 설정합니다.

.. OK * 를 선택합니다.


. 가상 머신의 전원을 켭니다.


.작업을 마친 후
이 노드를 확장 또는 복구 절차의 일부로 배포한 경우 해당 지침으로 돌아가 절차를 완료하십시오.
