---
permalink: swnodes/installing-storagegrid-webscale-host-services.html 
sidebar: sidebar 
keywords: how to install StorageGRID host services 
summary: StorageGRID 호스트 서비스를 설치하려면 운영 체제 유형에 맞는 StorageGRID 패키지를 사용합니다. 
---
= StorageGRID 호스트 서비스 설치(Linux)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 호스트 서비스를 설치하려면 운영 체제 유형에 맞는 StorageGRID 패키지를 사용합니다.


NOTE: "Linux"는 RHEL, Ubuntu 또는 Debian 배포를 의미합니다.  지원되는 버전 목록은 다음을 참조하세요. https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴(IMT)"^] .

[role="tabbed-block"]
====
.RHEL
--
StorageGRID RPM 패키지를 사용하여 StorageGRID 호스트 서비스를 설치합니다.

.이 작업에 대해
다음 지침은 RPM 패키지에서 호스트 서비스를 설치하는 방법을 설명합니다. 또는 설치 아카이브에 포함된 DNF 리포지토리 메타데이터를 사용하여 RPM 패키지를 원격으로 설치할 수 있습니다. Linux 운영 체제에 대한 DNF 리포지토리 지침을 참조하십시오.

.단계
. 각 호스트에 StorageGRID RPM 패키지를 복사하거나 공유 스토리지에서 사용할 수 있도록 합니다.
+
예를 들어, `/tmp` 다음 단계에서 예제 명령을 사용할 수 있도록 디렉토리에 배치합니다.

. 각 호스트에 루트로 로그인하거나 sudo 권한이 있는 계정을 사용하여 다음 명령을 지정된 순서대로 실행합니다.
+
[listing]
----
sudo dnf --nogpgcheck localinstall /tmp/StorageGRID-Webscale-Images-version-SHA.rpm
----
+
[listing]
----
sudo dnf --nogpgcheck localinstall /tmp/StorageGRID-Webscale-Service-version-SHA.rpm
----
+

CAUTION: 먼저 이미지 패키지를 설치하고 서비스 패키지를 다시 설치해야 합니다.

+

NOTE: 패키지를 이외의 디렉토리에 배치한 경우 `/tmp` 사용한 경로를 반영하도록 명령을 수정합니다.



--
.Ubuntu 또는 Debian
--
StorageGRID DEB 패키지를 사용하면 Ubuntu 또는 Debian용 StorageGRID 호스트 서비스를 설치할 수 있습니다.

.이 작업에 대해
다음 지침은 DEB 패키지에서 호스트 서비스를 설치하는 방법을 설명합니다. 또는 설치 아카이브에 포함된 APT 리포지토리 메타데이터를 사용하여 DEB 패키지를 원격으로 설치할 수 있습니다. Linux 운영 체제에 대한 APT 리포지토리 지침을 참조하십시오.

.단계
. 각 호스트에 StorageGRID DEB 패키지를 복사하거나 공유 스토리지에서 사용할 수 있도록 합니다.
+
예를 들어, `/tmp` 다음 단계에서 예제 명령을 사용할 수 있도록 디렉토리에 배치합니다.

. 각 호스트에 루트로 로그인하거나 sudo 권한이 있는 계정을 사용하여 다음 명령을 실행합니다.
+
먼저 패키지를 `service` 설치하고 패키지를 두 번째로 설치해야 `images` 합니다. 패키지를 이외의 디렉토리에 배치한 경우 `/tmp` 사용한 경로를 반영하도록 명령을 수정합니다.

+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb
----
+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-service-version-SHA.deb
----
+

NOTE: StorageGRID 패키지를 설치하려면 먼저 Python 3이 설치되어 있어야 합니다.  그만큼 `sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb` 그렇게 하지 않으면 명령은 실패할 것입니다.



--
====