---
permalink: swnodes/installing-linux.html 
sidebar: sidebar 
keywords: how to install Linux 
summary: 모든 Linux 그리드 호스트에 StorageGRID 설치해야 합니다.  지원되는 버전 목록을 보려면 NetApp 상호 운용성 매트릭스 도구를 사용하세요. 
---
= Linux를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 Linux 그리드 호스트에 StorageGRID 설치해야 합니다.  지원되는 버전 목록을 보려면 NetApp 상호 운용성 매트릭스 도구를 사용하세요.

.시작하기 전에
운영 체제가 아래 나열된 StorageGRID의 최소 커널 버전 요구 사항을 충족하는지 확인합니다. 명령을 사용하여 `uname -r` 운영 체제의 커널 버전을 가져오거나 OS 공급업체에 문의하십시오.


NOTE: "Linux"는 RHEL, Ubuntu 또는 Debian 배포를 의미합니다.  지원되는 버전 목록은 다음을 참조하세요. https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴(IMT)"^] .

[role="tabbed-block"]
====
.RHEL
--
[cols="1a,2a,2a"]
|===
| RHEL 버전 | 최소 커널 버전 | 커널 패키지 이름입니다 


 a| 
8.8(폐기됨)
 a| 
4.18.0-477.10.1.el8_8.x86_64
 a| 
커널 - 4.18.0-477.10.1.el8_8.x86_64



 a| 
8.10
 a| 
4.18.0-553.el8_10.x86_64
 a| 
kernel-4.18.0-553.el8_10.x86_64



 a| 
9.0(폐기됨)
 a| 
5.14.0-70.22.1.el9_0.x86_64
 a| 
커널 - 5.14.0-70.22.1.el9_0.x86_64



 a| 
9.2(사용되지 않음)
 a| 
5.14.0-284.11.1.el9_2.x86_64
 a| 
커널 - 5.14.0-284.11.1.el9_2.x86_64



 a| 
9.4 를 참조하십시오
 a| 
5.14.0-427.18.1.el9_4.x86_64
 a| 
커널 - 5.14.0-427.18.1.el9_4.x86_64



 a| 
9.6
 a| 
5.14.0-570.18.1.el9_6.x86_64
 a| 
커널-5.14.0-570.18.1.el9_6.x86_64

|===
--
.우분투
--
* 참고: * Ubuntu 버전 18.04 및 20.04에 대한 지원은 더 이상 사용되지 않으며 향후 릴리스에서 제거될 예정입니다.

[cols="1a,2a,3a"]
|===
| Ubuntu 버전 | 최소 커널 버전 | 커널 패키지 이름입니다 


 a| 
22.04.1
 a| 
5.15.0-47 - 일반
 a| 
linux-image-5.15.0-47-generic/jammy-updates, jammy-security, 현재 5.15.0-47.51



 a| 
24.04
 a| 
6.8.0-31 - 일반
 a| 
linux-image-6.8.0-31-generic/noble, 현재 6.8.0-31.31

|===
--
.데비안
--
*참고:* 데비안 버전 11에 대한 지원은 더 이상 사용되지 않으며 향후 릴리스에서 제거될 예정입니다.

[cols="1a,2a,2a"]
|===
| 데비안 버전 | 최소 커널 버전 | 커널 패키지 이름입니다 


 a| 
11(폐기됨)
 a| 
5.10.0-18-AMD64
 a| 
Linux-image-5.10.0-18-AMD64/stable, 현재 5.10.150-1



 a| 
12
 a| 
6.1.0-9-AMD64
 a| 
linux-image-6.1.0-9-amd64/stable, 현재 6.1.27-1

|===
--
====
.단계
. 배포자의 지침 또는 표준 절차에 따라 모든 물리적 또는 가상 그리드 호스트에 Linux를 설치합니다.
+

NOTE: 그래픽 데스크톱 환경을 설치하지 마세요.

+
** RHEL을 설치할 때 표준 Linux 설치 프로그램을 사용하는 경우, 가능한 경우 "컴퓨트 노드" 소프트웨어 구성을 선택하거나 "최소 설치" 기본 환경을 선택합니다.
** Ubuntu를 설치할 때 *표준 시스템 유틸리티*를 선택해야 합니다.  Ubuntu 호스트에 대한 ssh 액세스를 활성화하려면 *OpenSSH 서버*를 선택하는 것이 좋습니다.  다른 모든 옵션은 지워진 상태로 유지됩니다.


. RHEL의 Extras 채널을 포함하여 모든 호스트가 패키지 저장소에 액세스할 수 있는지 확인하세요.
. 스왑이 활성화된 경우:
+
.. 다음 명령을 실행합니다. `$ sudo swapoff --all`
.. 설정을 유지하려면 에서 모든 스왑 항목을 `/etc/fstab` 제거합니다.
+

NOTE: 스왑을 완전히 사용하지 않도록 설정하면 성능이 크게 저하될 수 있습니다.




