---
permalink: swnodes/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: 가상 머신을 사용하여 모든 유형의 StorageGRID 노드를 호스팅할 수 있습니다. 각 그리드 노드에 대해 하나의 가상 머신이 필요합니다. 
---
= 소프트웨어 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 머신을 사용하여 모든 유형의 StorageGRID 노드를 호스팅할 수 있습니다. 각 그리드 노드에 대해 하나의 가상 머신이 필요합니다.

[role="tabbed-block"]
====
.RHEL
--
RHEL에 StorageGRID 설치하려면 일부 타사 소프트웨어 패키지를 설치해야 합니다.  일부 지원되는 Linux 배포판에는 기본적으로 이러한 패키지가 포함되어 있지 않습니다.  StorageGRID 설치가 테스트된 소프트웨어 패키지 버전은 이 페이지에 나열된 버전을 포함합니다.

이러한 패키지를 필요로 하는 Linux 배포 및 컨테이너 런타임 설치 옵션을 선택했는데 Linux 배포판에 의해 자동으로 설치되지 않은 경우, 해당 공급자 또는 Linux 배포판의 지원 공급업체에서 제공하는 경우 여기에 나열된 버전 중 하나를 설치하십시오. 그렇지 않으면 공급업체에서 제공하는 기본 패키지 버전을 사용하십시오.

모든 설치 옵션에는 Podman 또는 Docker가 필요합니다. 두 패키지를 모두 설치하지 마십시오. 설치 옵션에 필요한 패키지만 설치합니다.


NOTE: 소프트웨어 전용 배포를 위한 컨테이너 엔진으로 Docker에 대한 지원은 더 이상 사용되지 않습니다. Docker는 향후 릴리즈에서 다른 컨테이너 엔진으로 대체될 예정입니다.

*테스트된 Python 버전*

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6


*테스트된 Podman 버전*

* 3.2.3-0
* 3.4.4 + DS1
* 4.1.1-7
* 4.2.0-11
* 4.3.1+DS1-8+B1
* 4.4.1-8
* 4.4.1-12


*테스트된 Docker 버전*


IMPORTANT: Docker 지원은 더 이상 사용되지 않으며 향후 릴리즈에서 제거될 예정입니다.

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3 을 참조하십시오
* Docker-CE 23.0.6-1 을 참조하십시오
* Docker-CE 24.0.2-1 을 참조하십시오
* Docker-CE 24.0.4-1 을 참조하십시오
* Docker-CE 24.0.5-1 을 참조하십시오
* Docker-CE 24.0.7-1 을 참조하십시오
* 1.5-2 을 참조하십시오


--
.Ubuntu 및 Debian
--
Ubuntu 또는 Debian에 StorageGRID를 설치하려면 타사 소프트웨어 패키지를 설치해야 합니다. 지원되는 일부 Linux 배포판에는 기본적으로 이러한 패키지가 포함되어 있지 않습니다. StorageGRID 설치를 테스트하는 소프트웨어 패키지 버전에는 이 페이지에 나열된 버전이 포함됩니다.

이러한 패키지를 필요로 하는 Linux 배포 및 컨테이너 런타임 설치 옵션을 선택했는데 Linux 배포판에 의해 자동으로 설치되지 않은 경우, 해당 공급자 또는 Linux 배포판의 지원 공급업체에서 제공하는 경우 여기에 나열된 버전 중 하나를 설치하십시오. 그렇지 않으면 공급업체에서 제공하는 기본 패키지 버전을 사용하십시오.

모든 설치 옵션에는 Podman 또는 Docker가 필요합니다. 두 패키지를 모두 설치하지 마십시오. 설치 옵션에 필요한 패키지만 설치합니다.


NOTE: 소프트웨어 전용 배포를 위한 컨테이너 엔진으로 Docker에 대한 지원은 더 이상 사용되지 않습니다. Docker는 향후 릴리즈에서 다른 컨테이너 엔진으로 대체될 예정입니다.

*테스트된 Python 버전*

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6


*테스트된 Podman 버전*

* 3.2.3-0
* 3.4.4 + DS1
* 4.1.1-7
* 4.2.0-11
* 4.3.1+DS1-8+B1
* 4.4.1-8
* 4.4.1-12


*테스트된 Docker 버전*


IMPORTANT: Docker 지원은 더 이상 사용되지 않으며 향후 릴리즈에서 제거될 예정입니다.

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3 을 참조하십시오
* Docker-CE 23.0.6-1 을 참조하십시오
* Docker-CE 24.0.2-1 을 참조하십시오
* Docker-CE 24.0.4-1 을 참조하십시오
* Docker-CE 24.0.5-1 을 참조하십시오
* Docker-CE 24.0.7-1 을 참조하십시오
* 1.5-2 을 참조하십시오


--
.VMware
--
*VMware vSphere 하이퍼바이저*

준비된 물리적 서버에 VMware vSphere 하이퍼바이저를 설치해야 합니다. VMware 소프트웨어를 설치하기 전에 하드웨어를 올바르게 구성해야 합니다(펌웨어 버전 및 BIOS 설정 포함).

* 설치할 StorageGRID 시스템에 대한 네트워킹을 지원하기 위해 필요에 따라 하이퍼바이저에서 네트워킹을 구성합니다.
+
link:../network/index.html["네트워킹 지침"]

* 데이터 저장소가 그리드 노드를 호스팅하는 데 필요한 가상 머신 및 가상 디스크에 충분히 큰지 확인합니다.
* 둘 이상의 데이터 저장소를 생성하는 경우 가상 머신을 생성할 때 각 그리드 노드에 사용할 데이터 저장소를 쉽게 식별할 수 있도록 각 데이터 저장소의 이름을 지정합니다.


*ESX 호스트 구성 요구 사항*


CAUTION: 각 ESX 호스트에서 NTP(네트워크 시간 프로토콜)를 적절히 구성해야 합니다. 호스트 시간이 올바르지 않으면 데이터 손실을 비롯한 부정적인 영향이 발생할 수 있습니다.

*VMware 구성 요구 사항*

StorageGRID 노드를 구축하기 전에 VMware vSphere 및 vCenter를 설치하고 구성해야 합니다.

지원되는 VMware vSphere Hypervisor 및 VMware vCenter Server 소프트웨어 버전은 를 참조하십시오 https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴"^].

이러한 VMware 제품을 설치하는 데 필요한 단계는 VMware 설명서를 참조하십시오.

--
====