---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: 업그레이드 소요 시간에 따라 업그레이드 시기를 고려하십시오. 업그레이드의 각 단계에서 수행할 수 있는 작업과 수행할 수 없는 작업에 유의하십시오. 
---
= 업그레이드를 완료하는 데 걸리는 시간을 예상합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드 소요 시간에 따라 업그레이드 시기를 고려하십시오. 업그레이드의 각 단계에서 수행할 수 있는 작업과 수행할 수 없는 작업에 유의하십시오.

.이 작업에 대해
StorageGRID 업그레이드를 완료하는 데 필요한 시간은 클라이언트 로드 및 하드웨어 성능과 같은 다양한 요인에 따라 달라집니다.

이 표에는 주요 업그레이드 작업이 요약되어 있으며 각 작업에 필요한 대략적인 시간이 나와 있습니다. 표 다음에 나오는 단계에서는 시스템의 업그레이드 시간을 추정하는 데 사용할 수 있는 지침을 제공합니다.

[cols="1a,2a,2a,4a"]
|===
| 업그레이드 작업 | 설명 | 필요한 대략적인 시간입니다 | 수행해야 합니다 


 a| 
사전 점검을 실행하고 기본 관리 노드를 업그레이드합니다
 a| 
업그레이드 사전 점검을 실행하고 기본 관리 노드가 중지, 업그레이드 및 재시작됩니다.
 a| 
서비스 어플라이언스 노드에서 가장 많은 시간이 필요한 경우 30분에서 1시간까지 소요됨

해결되지 않은 사전 검사 오류가 발생하면 이 시간이 늘어납니다.
 a| 
기본 관리자 노드에 액세스할 수 없습니다. 연결 오류가 보고될 수 있으며 이 오류는 무시할 수 있습니다.

업그레이드를 시작하기 전에 업그레이드 사전 점검을 실행하면 예약된 업그레이드 유지 관리 기간 전에 오류를 해결할 수 있습니다.



 a| 
업그레이드 서비스를 시작합니다
 a| 
소프트웨어 파일이 배포되고 업그레이드 서비스가 시작됩니다.
 a| 
그리드 노드당 3분
 a| 



 a| 
다른 그리드 노드를 업그레이드합니다
 a| 
다른 모든 그리드 노드의 소프트웨어는 노드를 승인하는 순서대로 업그레이드됩니다. 시스템의 모든 노드가 한 번에 하나씩 다운됩니다.
 a| 
노드당 15분~1시간, 어플라이언스 노드에서 가장 많은 시간이 필요함

* 참고 *: 어플라이언스 노드의 경우 StorageGRID 어플라이언스 설치 프로그램이 자동으로 최신 릴리즈로 업데이트됩니다.
 a| 
* 그리드 구성을 변경하지 마십시오.
* 감사 수준 구성을 변경하지 마십시오.
* ILM 구성을 업데이트하지 마십시오.
* 핫픽스, 서비스 해제 또는 확장과 같은 다른 유지 관리 절차를 수행할 수 없습니다.


* 참고 *: 복구를 수행해야 하는 경우 기술 지원 부서에 문의하십시오.



 a| 
기능을 활성화합니다
 a| 
새 버전의 새 기능이 활성화됩니다.
 a| 
5분 미만
 a| 
* 그리드 구성을 변경하지 마십시오.
* 감사 수준 구성을 변경하지 마십시오.
* ILM 구성을 업데이트하지 마십시오.
* 다른 유지보수 절차는 수행할 수 없습니다.




 a| 
데이터베이스를 업그레이드합니다
 a| 
업그레이드 프로세스에서는 각 노드를 검사하여 Cassandra 데이터베이스를 업데이트할 필요가 없는지 확인합니다.
 a| 
노드당 10초 또는 전체 그리드에 대해 몇 분
 a| 
StorageGRID 11.8에서 11.9로 업그레이드할 때는 Cassandra 데이터베이스를 업그레이드할 필요가 없습니다. 하지만 Cassandra 서비스는 각 스토리지 노드에서 중지했다가 다시 시작됩니다.

향후 StorageGRID 기능 릴리즈를 위해 Cassandra 데이터베이스 업데이트 단계를 완료하는 데 며칠이 걸릴 수 있습니다.



 a| 
최종 업그레이드 단계
 a| 
임시 파일이 제거되고 새 릴리스로의 업그레이드가 완료됩니다.
 a| 
5분
 a| 
최종 업그레이드 단계 * 작업이 완료되면 모든 유지보수 절차를 수행할 수 있습니다.

|===
.단계
. 모든 그리드 노드를 업그레이드하는 데 필요한 시간을 예상합니다.
+
.. StorageGRID 시스템의 노드 수에 노드당 1시간을 곱합니다.
+
일반적으로 어플라이언스 노드는 소프트웨어 기반 노드보다 업그레이드하는 데 더 오래 걸립니다.

.. 이 시간에 1시간을 추가하여 파일을 다운로드하고 사전 검사 검증을 실행하고 최종 업그레이드 단계를 완료하는 데 필요한 시간을 `.upgrade` 설명합니다.


. Linux 노드가 있는 경우 RPM 또는 DEB 패키지를 다운로드하고 설치하는 데 필요한 시간을 고려하여 각 노드에 대해 15분을 추가하십시오.
. 1단계와 2단계의 결과를 추가하여 총 업그레이드 예상 시간을 계산합니다.




== 예: StorageGRID 11.9로 업그레이드하는 데 걸리는 예상 시간입니다

시스템에 14개의 그리드 노드가 있고 그 중 8개가 Linux 노드라고 가정합니다.

. 14에 노드당 1시간을 곱합니다.
. 다운로드, 사전 확인 및 최종 단계를 고려하여 1시간을 추가하십시오.
+
모든 노드의 업그레이드 예상 시간은 15시간입니다.

. Linux 노드에 RPM 또는 DEB 패키지를 설치하는 시간을 고려하려면 노드당 8에 15분을 곱하십시오.
+
이 단계의 예상 시간은 2시간입니다.

. 값을 함께 추가합니다.
+
시스템을 StorageGRID 11.9.0으로 업그레이드하는 데 최대 17시간이 걸릴 수 있습니다.




NOTE: 필요에 따라 여러 세션에서 업그레이드할 그리드 노드의 하위 집합을 승인하여 유지 관리 창을 더 작은 창으로 분할할 수 있습니다. 예를 들어, 한 세션에서 사이트 A의 노드를 업그레이드한 다음 이후 세션에서 사이트 B의 노드를 업그레이드할 수 있습니다. 둘 이상의 세션에서 업그레이드를 수행하도록 선택한 경우 모든 노드가 업그레이드될 때까지 새 기능을 사용할 수 없습니다.
