---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 업그레이드 중에 StorageGRID 시스템이 어떤 영향을 받는지 알아보십시오. 
---
= 업그레이드 중 시스템에 미치는 영향
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드 중에 StorageGRID 시스템이 어떤 영향을 받는지 알아보십시오.



== StorageGRID 업그레이드는 무중단으로 수행할 수 있습니다

StorageGRID 시스템은 업그레이드 프로세스 전반에서 클라이언트 애플리케이션의 데이터를 수집하고 검색할 수 있습니다. 같은 유형의 모든 노드를 업그레이드(예: 스토리지 노드)하도록 승인하면 노드가 한 번에 하나씩 중단되므로 특정 유형의 모든 그리드 노드 또는 모든 그리드 노드를 사용할 수 없게 되는 시간은 없습니다.

지속적인 가용성을 보장하기 위해 ILM 정책에 각 개체의 여러 복사본을 저장하도록 지정하는 규칙이 포함되어 있는지 확인합니다. 또한 모든 외부 S3 클라이언트가 다음 중 하나로 요청을 보내도록 구성되었는지 확인해야 합니다.

* 고가용성(HA) 그룹 가상 IP 주소입니다
* 고가용성 타사 로드 밸런서
* 각 클라이언트에 대해 여러 게이트웨이 노드가 있습니다
* 각 클라이언트에 대해 여러 스토리지 노드




== 클라이언트 애플리케이션은 단기간 동안 중단될 수 있습니다

StorageGRID 시스템은 업그레이드 프로세스 전반에서 클라이언트 애플리케이션에서 데이터를 수집 및 검색할 수 있지만, 업그레이드에 따라 해당 노드에서 서비스를 다시 시작해야 하는 경우 개별 게이트웨이 노드 또는 스토리지 노드에 대한 클라이언트 연결이 일시적으로 중단될 수 있습니다. 업그레이드 프로세스가 완료되고 개별 노드에서 서비스가 재개되면 연결이 복원됩니다.

단기간 동안 연결이 끊길 수 없는 경우 업그레이드를 적용하기 위해 다운타임을 예약해야 할 수도 있습니다. 선택적 승인을 사용하여 특정 노드가 업데이트되는 시기를 예약할 수 있습니다.


NOTE: 여러 게이트웨이 및 고가용성(HA) 그룹을 사용하여 업그레이드 프로세스 중에 자동 페일오버를 제공할 수 있습니다. 의 지침을 link:../admin/configure-high-availability-group.html["고가용성 그룹 구성"]참조하십시오.



== 어플라이언스 펌웨어가 업그레이드되었습니다

StorageGRID 11.9 업그레이드 중:

* 모든 StorageGRID 어플라이언스 노드는 StorageGRID 어플라이언스 설치 프로그램 펌웨어 버전 3.9로 자동 업그레이드됩니다.
* SG6060 및 SGF6024 어플라이언스는 자동으로 BIOS 펌웨어 버전 3B08.EX 및 BMC 펌웨어 버전 4.00.07로 업그레이드됩니다.
* SG100 및 SG1000 어플라이언스는 자동으로 BIOS 펌웨어 버전 3B13.EC 및 BMC 펌웨어 버전 4.74.07로 업그레이드됩니다.
* SGF6112, SG6160, SG110 및 SG1100 어플라이언스는 BMC 펌웨어 버전 3.16.07로 자동 업그레이드됩니다.




== ILM 정책은 상태에 따라 다르게 처리됩니다

* 활성 정책은 업그레이드 후에도 동일하게 유지됩니다.
* 업그레이드 시 최신 10개의 과거 정책만 유지됩니다.
* 제안된 정책이 있는 경우 업그레이드 중에 삭제됩니다.




== 알림이 트리거될 수 있습니다

서비스가 시작 및 중지되거나 StorageGRID 시스템이 혼합 버전 환경으로 작동 중일 때(이전 버전을 실행하는 일부 그리드 노드와 이후 버전으로 업그레이드된 경우) 경고가 트리거될 수 있습니다. 업그레이드가 완료된 후 다른 알림이 트리거될 수 있습니다.

예를 들어, 서비스가 중지될 때 * node와 통신할 수 없음 * 경고가 표시되거나 일부 노드가 StorageGRID 11.9로 업그레이드되었지만 다른 노드는 여전히 StorageGRID 11.8을 실행 중인 경우 * Cassandra 통신 오류 * 경고가 표시될 수 있습니다. 일반적으로 이러한 알림은 업그레이드가 완료되면 지워집니다.

StorageGRID 11.9로 업그레이드 중에 스토리지 노드가 중지되면 * ILM 배치를 달성 불가 * 경고가 트리거될 수 있습니다. 이 알림은 업그레이드가 완료된 후 1일 동안 지속될 수 있습니다.

업그레이드가 완료된 후 Grid Manager 대시보드에서 * Recently Resolved alerts * 또는 * Current alerts * 를 선택하여 업그레이드 관련 경고를 검토할 수 있습니다.



== 구성 변경이 제한됩니다


NOTE: 이 목록은 특히 StorageGRID 11.8에서 StorageGRID 11.9로 업그레이드하는 데 적용됩니다. 다른 StorageGRID 릴리즈로 업그레이드하는 경우 해당 릴리즈의 업그레이드 지침에 있는 제한된 변경 사항 목록을 참조하십시오.

새 기능 사용 * 작업이 완료될 때까지 다음을 수행합니다.

* 그리드 구성을 변경하지 마십시오.
* 새 기능을 사용하거나 사용하지 않도록 설정하지 마십시오.
* ILM 구성을 업데이트하지 마십시오. 그렇지 않으면 일관되지 않고 예기치 않은 ILM 동작이 발생할 수 있습니다.
* 핫픽스를 적용하거나 그리드 노드를 복구하지 마십시오.
+

NOTE: 업그레이드 중에 노드를 복구해야 하는 경우 기술 지원 부서에 문의하십시오.

* StorageGRID 11.9로 업그레이드하는 동안에는 HA 그룹, VLAN 인터페이스 또는 로드 밸런서 엔드포인트를 관리해서는 안 됩니다.
* StorageGRID 11.9로의 업그레이드가 완료될 때까지 HA 그룹을 삭제하지 마십시오. 다른 HA 그룹의 가상 IP 주소에 액세스하지 못할 수 있습니다.


최종 업그레이드 단계 * 작업이 완료될 때까지:

* 확장 절차를 수행하지 마십시오.
* 서비스 해제 절차를 수행하지 마십시오.

