---
permalink: upgrade/troubleshooting-upgrade-issues.html 
sidebar: sidebar 
keywords: upgrade, troubleshoot, troubleshooting, errors, upgrade precheck 
summary: 업그레이드를 수행할 때 문제가 발생하면 직접 문제를 해결할 수 있습니다. 문제를 해결할 수 없는 경우 최대한 많은 정보를 수집한 다음 기술 지원 팀에 문의하십시오. 
---
= 업그레이드 문제를 해결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드를 수행할 때 문제가 발생하면 직접 문제를 해결할 수 있습니다. 문제를 해결할 수 없는 경우 최대한 많은 정보를 수집한 다음 기술 지원 팀에 문의하십시오.



== 업그레이드가 완료되지 않습니다

다음 섹션에서는 업그레이드가 부분적으로 실패한 상황에서 복구하는 방법에 대해 설명합니다.



=== 업그레이드 사전 점검 오류

문제를 감지하고 해결하려면 실제 업그레이드를 시작하기 전에 업그레이드 사전 점검을 수동으로 실행할 수 있습니다. 대부분의 사전 검사 오류는 문제 해결 방법에 대한 정보를 제공합니다.



=== 프로비저닝 실패

자동 프로비저닝 프로세스가 실패하면 기술 지원 팀에 문의하십시오.



=== 그리드 노드가 충돌하거나 시작되지 않습니다

업그레이드 프로세스 중에 그리드 노드가 작동 중단되거나 업그레이드가 완료된 후 성공적으로 시작되지 않는 경우 기술 지원 부서에 문의하여 기본적인 문제를 조사하고 해결하십시오.



=== 수집 또는 데이터 검색이 중단됩니다

그리드 노드를 업그레이드하지 않을 때 데이터 수집 또는 검색이 예기치 않게 중단되면 기술 지원 부서에 문의하십시오.



=== 데이터베이스 업그레이드 오류

데이터베이스 업그레이드에 오류가 발생하면 업그레이드를 다시 시도하십시오. 다시 실패하면 기술 지원 부서에 문의하십시오.

.관련 정보
link:checking-systems-condition-before-upgrading-software.html["소프트웨어를 업그레이드하기 전에 시스템 상태를 확인합니다"]



== 사용자 인터페이스 문제

업그레이드 도중 또는 이후에 Grid Manager 또는 테넌트 관리자에 문제가 발생할 수 있습니다.



=== 그리드 관리자는 업그레이드 중에 여러 오류 메시지를 표시합니다

기본 관리자 노드가 업그레이드되는 동안 브라우저를 새로 고치거나 다른 그리드 관리자 페이지로 이동하는 경우 "503: 서비스를 사용할 수 없음" 및 "서버에 연결하는 데 문제가 있음" 메시지가 여러 개 표시될 수 있습니다. 이러한 메시지는 무시해도 됩니다. 노드가 업그레이드되는 즉시 표시되지 않습니다.

업그레이드를 시작한 후 한 시간 이상 이러한 메시지가 나타나면 기본 관리 노드를 업그레이드하지 못하게 하는 문제가 발생한 것일 수 있습니다. 직접 문제를 해결할 수 없는 경우 기술 지원 부서에 문의하십시오.



=== 웹 인터페이스가 예상대로 응답하지 않습니다

StorageGRID 소프트웨어를 업그레이드한 후 그리드 관리자 또는 테넌트 관리자가 예상대로 응답하지 않을 수 있습니다.

웹 인터페이스에 문제가 있는 경우:

* 를 사용하고 있는지 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]확인합니다.
+

NOTE: 브라우저 지원은 일반적으로 각 StorageGRID 릴리스에 대한 변경 사항을 적용합니다.

* 웹 브라우저 캐시를 지웁니다.
+
캐시를 지우면 이전 버전의 StorageGRID 소프트웨어에서 사용된 오래된 리소스가 제거되고 사용자 인터페이스가 다시 올바르게 작동할 수 있습니다. 자세한 내용은 웹 브라우저 설명서를 참조하십시오.





== "Docker 이미지 가용성 확인" 오류 메시지

업그레이드 프로세스를 시작하려고 할 때 "다음 문제가 Docker 이미지 가용성 검사 유효성 검사 제품군으로 식별되었습니다."라는 오류 메시지가 나타날 수 있습니다. 업그레이드를 완료하기 전에 모든 문제를 해결해야 합니다.

식별된 문제를 해결하는 데 필요한 변경 사항을 잘 모르는 경우 기술 지원 부서에 문의하십시오.

[cols="1a,1a,1a"]
|===
| 메시지 | 원인 | 해결 방법 


 a| 
업그레이드 버전을 확인할 수 없습니다. 업그레이드 버전 정보 파일이 `{file_path}` 예상 형식과 일치하지 않습니다.
 a| 
업그레이드 패키지가 손상되었습니다.
 a| 
업그레이드 패키지를 다시 업로드하고 다시 시도하십시오. 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
업그레이드 버전 정보 파일을 `{file_path}` 찾을 수 없습니다. 업그레이드 버전을 확인할 수 없습니다.
 a| 
업그레이드 패키지가 손상되었습니다.
 a| 
업그레이드 패키지를 다시 업로드하고 다시 시도하십시오. 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
에서 현재 설치된 릴리스 버전을 확인할 수 `{node_name}` 없습니다.
 a| 
노드의 중요 파일이 손상되었습니다.
 a| 
기술 지원 부서에 문의하십시오.



 a| 
에서 버전을 나열하려는 중 연결 오류가 발생했습니다 `{node_name}`
 a| 
노드가 오프라인이거나 연결이 끊어졌습니다.
 a| 
모든 노드가 온라인 상태이고 운영 관리 노드에서 연결할 수 있는지 확인한 후 다시 시도하십시오.



 a| 
노드의 호스트에 `{node_name}` StorageGRID 이미지가 로드되어 있지 `{upgrade_version}` 않습니다. 업그레이드를 진행하기 전에 이미지와 서비스를 호스트에 설치해야 합니다.
 a| 
업그레이드 RPM 또는 DEB 패키지가 노드가 실행 중인 호스트에 설치되지 않았거나 이미지를 가져오는 중입니다.

* 참고: * 이 오류는 Linux에서 컨테이너로 실행되는 노드에만 적용됩니다.
 a| 
노드가 실행 중인 모든 Linux 호스트에 RPM 또는 DEB 패키지가 설치되었는지 확인합니다. 서비스 및 이미지 파일 모두에 대해 버전이 올바른지 확인합니다. 몇 분 정도 기다린 후 다시 시도하십시오.

을 link:../upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html["Linux: 모든 호스트에 RPM 또는 DEB 패키지를 설치합니다"]참조하십시오.



 a| 
노드를 확인하는 동안 오류가 발생했습니다 `{node_name}`
 a| 
예기치 않은 오류가 발생했습니다.
 a| 
몇 분 정도 기다린 후 다시 시도하십시오.



 a| 
사전 점검 실행 중 오류가 발생했습니다. `{error_string}`
 a| 
예기치 않은 오류가 발생했습니다.
 a| 
몇 분 정도 기다린 후 다시 시도하십시오.

|===