---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: 업그레이드를 시작하기 전에 이전 버전의 StorageGRID가 현재 설치되어 있고 사용 가능한 최신 핫픽스가 적용되었는지 확인합니다. 
---
= 설치된 StorageGRID 버전을 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드를 시작하기 전에 이전 버전의 StorageGRID가 현재 설치되어 있고 사용 가능한 최신 핫픽스가 적용되었는지 확인합니다.

.이 작업에 대해
StorageGRID 12.0으로 업그레이드하기 전에 그리드에 StorageGRID 11.9.0.8 이상이 설치되어 있어야 합니다.  현재 StorageGRID 의 이전 버전을 사용하고 있다면 그리드의 현재 버전이 최소한 StorageGRID 11.9.0.8이 될 때까지 모든 이전 업그레이드 파일과 최신 핫픽스를 설치해야 합니다(강력히 권장).

에 가능한 업그레이드 경로 중 하나가 <<example-upgrade-path,예>>나와 있습니다.


CAUTION: NetApp 다음 버전으로 업그레이드하기 전에 각 StorageGRID 버전에 최신 핫픽스를 적용하고, 설치하는 각 새 버전에도 최신 핫픽스를 적용할 것을 강력히 권장합니다.  어떤 경우에는 데이터 손실 위험을 방지하기 위해 핫픽스를 적용해야 합니다.  참조하다 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 다운로드: StorageGRID"^] 자세한 내용은 각 핫픽스의 릴리스 노트를 참조하세요.



== 설치된 버전 확인

.단계
. 을 사용하여 그리드 관리자에 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]로그인합니다.
. 그리드 관리자 상단에서 * 도움말 * > * 정보 * 를 선택합니다.
. *버전*이 11.9.0.8 이상인지 확인하세요.
. *버전*이 11.9.0.8 이상이 아닌 경우 다음으로 이동하세요. https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 다운로드: StorageGRID"^] 필요한 업그레이드 및 핫픽스 파일을 다운로드하세요.
. link:../upgrade/index.html["업그레이드 지침을 따르세요"]다운로드한 각 릴리스에 대해. link:../maintain/storagegrid-hotfix-procedure.html["최신 핫픽스를 적용하세요"] 각 릴리스에 대해 (강력히 권장됨).


다음 업그레이드 예를 참조하세요.



== [[example-upgrade-path]]예: 버전 11.8에서 StorageGRID 12.0으로 업그레이드

다음 예에서는 StorageGRID 12.0 업그레이드를 준비하기 위해 StorageGRID 버전 11.8에서 버전 11.9로 업그레이드하는 단계를 보여줍니다.

시스템을 업그레이드할 수 있도록 다음 순서로 소프트웨어를 다운로드하여 설치합니다.

. StorageGRID 11.8.0 주요 릴리즈로 업그레이드하십시오.
. 최신 StorageGRID 11.8.0._y_hotfix를 적용합니다.
. StorageGRID 11.9.0 주요 릴리스로 업그레이드하세요.
. StorageGRID 11.9.0.8 이상 핫픽스를 적용합니다.

