---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: 업그레이드를 시작하기 전에 이전 버전의 StorageGRID가 현재 설치되어 있고 사용 가능한 최신 핫픽스가 적용되었는지 확인합니다. 
---
= 설치된 StorageGRID 버전을 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드를 시작하기 전에 이전 버전의 StorageGRID가 현재 설치되어 있고 사용 가능한 최신 핫픽스가 적용되었는지 확인합니다.

.이 작업에 대해
StorageGRID 11.9로 업그레이드하기 전에 그리드에 StorageGRID 11.8이 설치되어 있어야 합니다. 현재 이전 버전의 StorageGRID를 사용 중인 경우 그리드의 현재 버전이 StorageGRID 11.8._x.y_가 될 때까지 모든 이전 업그레이드 파일을 최신 핫픽스와 함께 설치해야 합니다(적극 권장).

에 가능한 업그레이드 경로 중 하나가 <<example-upgrade-path,예>>나와 있습니다.


CAUTION: 다음 버전으로 업그레이드하기 전에 각 StorageGRID 버전에 최신 핫픽스를 적용하고 설치하는 각 새 버전에 최신 핫픽스를 적용할 것을 적극 권장합니다. 경우에 따라 데이터 손실 위험을 방지하기 위해 핫픽스를 적용해야 합니다.  https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 다운로드: StorageGRID"^]자세한 내용은 및 각 핫픽스에 대한 릴리스 노트를 참조하십시오.

.단계
. 을 사용하여 그리드 관리자에 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]로그인합니다.
. 그리드 관리자 상단에서 * 도움말 * > * 정보 * 를 선택합니다.
. 버전 * 이 11.8._x.y_인지 확인합니다.
+
StorageGRID 11.8._x.y_version 번호:

+
** major release * 의 _x_value는 0(11.8.0)입니다.
** 핫픽스*가 적용된 경우 _y_value(예: 11.8.0.1)가 있습니다.


. 버전 * 이 11.8._x.y_가 아니면 로 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 다운로드: StorageGRID"^] 이동하여 각 릴리스의 최신 핫픽스를 포함하여 각 이전 릴리스의 파일을 다운로드합니다.
. 다운로드한 각 릴리스에 대한 업그레이드 지침을 확인합니다. 그런 다음 해당 릴리스에 대해 소프트웨어 업그레이드 절차를 수행하고 해당 릴리스에 대한 최신 핫픽스를 적용합니다(적극 권장).
+
를 link:../maintain/storagegrid-hotfix-procedure.html["StorageGRID 핫픽스 절차"]참조하십시오.





== [[example-upgrade-path]] 예: 버전 11.6에서 StorageGRID 11.9로 업그레이드

다음 예에서는 StorageGRID 11.9 업그레이드를 준비하기 위해 StorageGRID 버전 11.6에서 버전 11.8로 업그레이드하는 단계를 보여 줍니다.

시스템을 업그레이드할 수 있도록 다음 순서로 소프트웨어를 다운로드하여 설치합니다.

. StorageGRID 11.6.0 주요 릴리즈로 업그레이드하십시오.
. 최신 StorageGRID 11.6.0._y_hotfix를 적용합니다.
. StorageGRID 11.7.0 주요 릴리즈로 업그레이드하십시오.
. 최신 StorageGRID 11.7.0._y_hotfix를 적용합니다.
. StorageGRID 11.8.0 주요 릴리즈로 업그레이드하십시오.
. 최신 StorageGRID 11.8.0._y_hotfix를 적용합니다.

