---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.0 
summary: 이 StorageGRID 릴리스는 다음과 같은 기능 및 기능 변경 사항을 소개합니다. 
---
= StorageGRID 12.0의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 StorageGRID 릴리스는 다음과 같은 기능 및 기능 변경 사항을 소개합니다.



== S3 오브젝트 잠금을 통한 그리드 간 복제

S3 오브젝트 잠금을 사용하도록 설정한 상태에서 버킷 간 그리드 간 복제를 구성할 수 있습니다. 을 link:../admin/grid-federation-what-is-cross-grid-replication.html#cgr-with-ol["S3 오브젝트 잠금을 통한 그리드 간 복제"]참조하십시오.

NetApp은 StorageGRID 12.0 소스 및 대상 버킷 간에만 이 기능을 사용할 것을 권장합니다. 하지만 이 기능은 S3 오브젝트 잠금이 해제된 StorageGRID 11.9 소스 버킷과 S3 오브젝트 잠금이 설정된 StorageGRID 12.0 대상 버킷 간에 지원됩니다.



== 보안



=== 디스크의 암호화된 암호에 대한 보안 강화

SHA512 암호 해시에 대한 해시 라운드 수가 크게 증가하는 등 암호 보안 기능이 향상되었습니다.



== S3 버킷



=== 분기 버킷

이제 S3 버킷을 사용할 수 link:../tenant/manage-branch-bucket-html["분기 버킷을 만듭니다"]있습니다. 분기 버킷은 S3 버킷 오브젝트를 특정 시점에 액세스할 수 있도록 합니다. 분기 버킷은 백업과 같지 않습니다.



== 사용자 인터페이스



=== 어두운 테마

어두운 테마 및 시스템 테마 설정은 Grid Manager(그리드 관리자) 및 Tenant Manager(테넌트 관리자)의 User(사용자) 메뉴에서 사용할 수 있습니다.



== Grid Manager의 향상된 기능



=== 영역 개선 구성

이제 그리드 관리자의 영역 페이지에 * 기본 영역 * 탭이 포함됩니다. 이 탭을 사용하여 S3 버킷에 대해 정의된 기본 영역을 변경할 수 있습니다. link:../ilm/configuring-regions-optional-and-s3-only.html["자세한 정보"]..
