---
permalink: ubuntu/configuring-host-storage.html 
sidebar: sidebar 
keywords: how to configure host storage 
summary: 각 호스트에 블록 스토리지 볼륨을 할당해야 합니다. 
---
= 호스트 스토리지를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 호스트에 블록 스토리지 볼륨을 할당해야 합니다.

.시작하기 전에
이 과제를 수행하는 데 필요한 정보를 제공하는 다음 주제를 검토했습니다.

* link:storage-and-performance-requirements.html["요구사항을 충족해야 합니다"]
* link:node-container-migration-requirements.html["노드 컨테이너 마이그레이션 요구사항"]


.이 작업에 대해
블록 스토리지 볼륨(LUN)을 호스트에 할당할 때 "스토리지 요구 사항"의 표를 사용하여 다음을 확인합니다.

* 각 호스트에 필요한 볼륨 수(해당 호스트에 구축할 노드 수 및 유형 기준)
* 각 볼륨의 스토리지 범주(즉, 시스템 데이터 또는 오브젝트 데이터)
* 각 볼륨의 크기입니다


호스트에 StorageGRID 노드를 배포할 때 이 정보와 Linux가 각 물리적 볼륨에 할당한 영구 이름을 사용합니다.


NOTE: 이러한 볼륨을 파티션, 포맷 또는 마운트할 필요가 없습니다. 호스트가 볼 수 있도록 해야 합니다.


NOTE: 메타데이터 전용 스토리지 노드에는 하나의 오브젝트 데이터 LUN만 필요합니다.

(`/dev/sdb`볼륨 이름 목록을 작성할 때 "raw" 특수 장치 파일을 사용하지 마십시오. 이러한 파일은 호스트의 재부팅 시 변경될 수 있으며, 이는 시스템의 올바른 작동에 영향을 줍니다. iSCSI LUN 및 Device Mapper Multipathing을 사용하는 경우, 특히 SAN 토폴로지에 공유 스토리지에 대한 중복 네트워크 경로가 포함되어 있는 경우 디렉토리에서 다중 경로 별칭을 사용하는 `/dev/mapper` 것이 좋습니다. 또는 영구 장치 이름에 대해 에서 시스템에서 만든 소프트링크를 사용할 수 `/dev/disk/by-path/` 있습니다.

예를 들면 다음과 같습니다.

[listing]
----
ls -l
$ ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:00:07.1-ata-2 -> ../../sr0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
----
각 설치 환경에 따라 결과가 달라집니다.

각 블록 스토리지 볼륨에 알기 쉬운 이름을 할당하여 초기 StorageGRID 설치 및 향후 유지 관리 절차를 간소화하십시오. 공유 스토리지 볼륨에 대한 중복 액세스를 위해 디바이스 매퍼 다중 경로 드라이버를 사용하는 경우 파일의 필드를 `/etc/multipath.conf` 사용할 수 `alias` 있습니다.

예를 들면 다음과 같습니다.

[listing]
----
multipaths {
     multipath {
          wwid 3600a09800059d6df00005df2573c2c30
          alias docker-storage-volume-hostA
     }
     multipath {
          wwid 3600a09800059d6df00005df3573c2c30
          alias sgws-adm1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df4573c2c30
          alias sgws-adm1-audit-logs
     }
     multipath {
          wwid 3600a09800059d6df00005df5573c2c30
          alias sgws-adm1-tables
     }
     multipath {
          wwid 3600a09800059d6df00005df6573c2c30
          alias sgws-gw1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-rangedb-0
     }
     …
----
이러한 방식으로 별칭 필드를 사용하면 별칭이 호스트의 디렉토리에 블록 디바이스로 나타나므로 구성 또는 유지 관리 작업에서 블록 `/dev/mapper` 스토리지 볼륨을 지정해야 할 때마다 쉽게 검증된 친숙한 이름을 지정할 수 있습니다.

StorageGRID 노드 마이그레이션을 지원하고 장치 매퍼 다중 경로를 사용하도록 공유 스토리지를 설정하는 경우 모든 공동 위치 호스트에 공통 을 생성하고 설치할 수 `/etc/multipath.conf` 있습니다. 각 호스트에서 다른 Docker 스토리지 볼륨을 사용하기만 하면 됩니다. 각 Docker 스토리지 볼륨 LUN의 별칭에 타겟 호스트 이름을 포함하여 별칭을 사용하면 기억하기 쉽고 이 방법이 권장됩니다.


NOTE: 소프트웨어 전용 배포를 위한 컨테이너 엔진으로 Docker에 대한 지원은 더 이상 사용되지 않습니다. Docker는 향후 릴리즈에서 다른 컨테이너 엔진으로 대체될 예정입니다.

.관련 정보
* link:storage-and-performance-requirements.html["요구사항을 충족해야 합니다"]
* link:node-container-migration-requirements.html["노드 컨테이너 마이그레이션 요구사항"]

