---
permalink: ubuntu/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download ubuntu or debian installation files 
summary: StorageGRID 설치 아카이브를 다운로드하고 필요한 파일을 추출해야 합니다. 선택적으로 설치 패키지의 파일을 수동으로 확인할 수 있습니다. 
---
= StorageGRID 설치 파일을 다운로드하고 압축을 풉니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 설치 아카이브를 다운로드하고 필요한 파일을 추출해야 합니다. 선택적으로 설치 패키지의 파일을 수동으로 확인할 수 있습니다.

.단계
. 로 이동합니다 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["StorageGRID용 NetApp 다운로드 페이지"^].
. 최신 릴리스를 다운로드하려면 버튼을 선택하거나 드롭다운 메뉴에서 다른 버전을 선택하고 * GO * 를 선택합니다.
. NetApp 계정의 사용자 이름과 암호를 사용하여 로그인합니다.
. Caution/MustRead 문이 나타나면 해당 문을 읽고 확인란을 선택합니다.
+

CAUTION: StorageGRID 릴리스를 설치한 후 필요한 핫픽스를 적용해야 합니다. 자세한 내용은 를 참조하십시오 link:../maintain/storagegrid-hotfix-procedure.html["복구 및 유지 관리 지침의 핫픽스 절차"]

. 최종 사용자 사용권 계약을 읽고 확인란을 선택한 다음 * 동의 및 계속 * 을 선택합니다.
. StorageGRID 설치 * 열에서 Ubuntu 또는 Debian용 .tgz 또는 .zip 설치 아카이브를 선택합니다.
+

NOTE:  `.zip`서비스 랩톱에서 Windows를 실행하는 경우 파일을 선택합니다.

. 설치 아카이브를 저장합니다.
. [[Ubuntu-download-verification-package]] 설치 아카이브를 확인해야 하는 경우:
+
.. StorageGRID 코드 서명 확인 패키지를 다운로드합니다. 이 패키지의 파일 이름은 StorageGRID 소프트웨어 버전의 형식을 `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz` 사용합니다. `<version-number>`
.. 의 단계를 link:../ubuntu/download-files-verify.html["설치 파일을 수동으로 확인합니다"]따릅니다.


. 설치 아카이브에서 파일 압축을 풉니다.
. 필요한 파일을 선택합니다.
+
필요한 파일은 계획된 그리드 토폴로지와 StorageGRID 시스템 배포 방법에 따라 다릅니다.

+

NOTE: 표에 나열된 경로는 추출된 설치 아카이브에서 설치한 최상위 디렉토리에 상대적입니다.



[cols="1a,1a"]
|===
| 경로 및 파일 이름입니다 | 설명 


| ./debs/README  a| 
StorageGRID 다운로드 파일에 포함된 모든 파일을 설명하는 텍스트 파일입니다.



| /debs/NLF000000.txt 를 참조하십시오  a| 
테스트 및 개념 증명 배포에 사용할 수 있는 비프로덕션 NetApp 라이센스 파일.



| /debs/storagegrid-webscale-images-version-SHA.deb 를 참조하십시오  a| 
StorageGRID 노드 이미지를 Ubuntu 또는 Debian 호스트에 설치하기 위한 DEB 패키지.



| /debs/storagegrid-webscale-images-version-SHA.deb.md5 를 참조하십시오  a| 
파일의 MD5 체크섬 `/debs/storagegrid-webscale-images-version-SHA.deb`.



| /debs/storagegrid-webscale-service-version-SHA.deb 를 참조하십시오  a| 
Ubuntu 또는 Debian 호스트에 StorageGRID 호스트 서비스를 설치하기 위한 DEB 패키지.



| 배포 스크립팅 도구 | 설명 


| /debs/configure-storagegrid.py 를 참조하십시오  a| 
StorageGRID 시스템 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| /debs/configure-sga.py 를 참조하십시오  a| 
StorageGRID 어플라이언스 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| /debs/storagegrid-ssoauth.py 를 참조하십시오  a| 
SSO(Single Sign-On)가 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예제 이 스크립트를 Ping 연합 통합에 사용할 수도 있습니다.



| /debs/configure -StorageGrid.sample.json 을 참조하십시오  a| 
스크립트와 함께 사용할 예제 구성 파일 `configure-storagegrid.py`



| /debs/configure -StorageGrid.blank.json 을 참조하십시오  a| 
스크립트와 함께 사용할 빈 구성 `configure-storagegrid.py` 파일입니다.



| ./debs/Extras/Ansible  a| 
StorageGRID 컨테이너 배포를 위한 Ubuntu 또는 Debian 호스트 구성을 위한 Ansible 역할 및 플레이북 예 필요에 따라 역할 또는 플레이북을 사용자 지정할 수 있습니다.



| ./debs/storagegrid-ssoauth-azure.py  a| 
Active Directory 또는 Ping 연방을 사용하여 SSO(Single Sign-On)를 사용하도록 설정한 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예제



| /debs/StorageGrid-ssoauth-Azure.js를 입력합니다  a| 
Azure와의 SSO 상호 작용을 수행하기 위해 Python 스크립트에 의해 호출되는 도우미 스크립트입니다. `storagegrid-ssoauth-azure.py`



| /debs/Extras/API-schemas  a| 
StorageGRID에 대한 API 스키마입니다.

* 참고 *: 업그레이드를 수행하기 전에 이러한 스키마를 사용하여 StorageGRID 관리 API를 사용하도록 작성한 코드가 업그레이드 호환성 테스트를 위한 비프로덕션 StorageGRID 환경이 없는 경우 새 StorageGRID 릴리스와 호환되는지 확인할 수 있습니다.

|===