---
permalink: network/general-networking-requirements.html 
sidebar: sidebar 
keywords: networking requirements, storagegrid networks 
summary: 모든 StorageGRID 배포에서 다음 연결을 지원할 수 있어야 합니다. 
---
= StorageGRID의 일반 네트워킹 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 StorageGRID 배포에서 다음 연결을 지원할 수 있어야 합니다.

이러한 연결은 네트워크 토폴로지 예에 표시된 대로 그리드, 관리자 또는 클라이언트 네트워크 또는 이러한 네트워크의 조합을 통해 발생할 수 있습니다.

* * 관리 연결 * : 일반적으로 SSH를 통해 관리자로부터 노드로 인바운드 연결. 그리드 관리자, 테넌트 관리자 및 StorageGRID 어플라이언스 설치 프로그램에 대한 웹 브라우저 액세스
* * NTP 서버 연결 * : 인바운드 UDP 응답을 수신하는 아웃바운드 UDP 연결입니다.
+
1차 관리자 노드에서 하나 이상의 NTP 서버에 연결할 수 있어야 합니다.

* * DNS 서버 연결 * : 인바운드 UDP 응답을 수신하는 아웃바운드 UDP 연결입니다.
* * LDAP/Active Directory 서버 연결 *: 스토리지 노드의 ID 서비스에서 아웃바운드 TCP 연결.
* * AutoSupport *: 관리 노드에서 또는 고객이 구성한 프록시로 아웃바운드 TCP 연결 `support.netapp.com`.
* * 외부 키 관리 서버 *: 노드 암호화가 활성화된 각 어플라이언스 노드에서 아웃바운드 TCP 연결.
* S3 클라이언트의 인바운드 TCP 연결
* CloudMirror 복제 또는 클라우드 스토리지 풀과 같은 StorageGRID 플랫폼 서비스의 아웃바운드 요청


StorageGRID가 기본 라우팅 규칙을 사용하여 프로비저닝된 NTP 또는 DNS 서버에 연결할 수 없는 경우 DNS 및 NTP 서버의 IP 주소가 지정된 경우 모든 네트워크(그리드, 관리자 및 클라이언트)에서 자동으로 연결을 시도합니다. 네트워크에서 NTP 또는 DNS 서버에 연결할 수 있는 경우 StorageGRID는 자동으로 추가 라우팅 규칙을 만들어 향후 모든 연결 시도에 네트워크가 사용되도록 합니다.


TIP: 자동으로 검색된 호스트 라우트를 사용할 수 있지만 일반적으로 자동 검색이 실패할 경우 연결을 보장하기 위해 DNS 및 NTP 라우트를 수동으로 구성해야 합니다.

배포 중에 선택적 관리 및 클라이언트 네트워크를 구성할 준비가 되지 않은 경우 구성 단계에서 그리드 노드를 승인할 때 이러한 네트워크를 구성할 수 있습니다. 또한 설치가 완료된 후 Change IP(IP 변경link:../maintain/configuring-ip-addresses.html["IP 주소를 구성합니다"]) 도구를 사용하여 이러한 네트워크를 구성할 수 있습니다(참조).



== 관리 노드 및 게이트웨이 노드에 대한 연결

관리자 노드는 항상 인터넷에 있는 것과 같이 신뢰할 수 없는 클라이언트로부터 보호되어야 합니다. 신뢰할 수 없는 클라이언트가 그리드 네트워크, 관리 네트워크 또는 클라이언트 네트워크의 관리 노드에 액세스할 수 있는지 확인해야 합니다.

고가용성 그룹에 추가하려는 관리 노드 및 게이트웨이 노드는 정적 IP 주소로 구성해야 합니다. 을 link:../admin/managing-high-availability-groups.html["고가용성 그룹 관리"]참조하십시오.



== NAT(Network Address Translation) 사용

그리드 네트워크에서 그리드 노드 간 또는 StorageGRID 사이트 간에 NAT(네트워크 주소 변환)를 사용하지 마십시오. Grid Network에 전용 IPv4 주소를 사용하는 경우, 이러한 주소는 모든 사이트의 모든 그리드 노드에서 직접 라우팅할 수 있어야 합니다. 그러나 필요한 경우 게이트웨이 노드에 대한 공용 IP 주소를 제공하는 등의 NAT를 외부 클라이언트와 그리드 노드 간에 사용할 수 있습니다. NAT를 사용하여 공용 네트워크 세그먼트를 연결하는 것은 그리드의 모든 노드에 투명하고 터널링 응용 프로그램을 사용하는 경우에만 지원됩니다. 즉, 그리드 노드는 공용 IP 주소를 알 필요가 없습니다.
