---
permalink: network/linux-deployments.html 
sidebar: sidebar 
keywords: linux network, container engine, red hat enterprise linux rhel network, ubuntu network 
summary: 효율성, 안정성 및 보안을 위해 StorageGRID 시스템은 Linux에서 컨테이너 엔진의 모음으로 실행됩니다. StorageGRID 시스템에는 컨테이너 엔진 관련 네트워크 구성이 필요하지 않습니다. 
---
= Linux 배포
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
효율성, 안정성 및 보안을 위해 StorageGRID 시스템은 Linux에서 컨테이너 엔진의 모음으로 실행됩니다. StorageGRID 시스템에는 컨테이너 엔진 관련 네트워크 구성이 필요하지 않습니다.

컨테이너 네트워크 인터페이스에 VLAN 또는 가상 이더넷(veth) 쌍과 같은 비결합 장치를 사용합니다. 이 디바이스를 노드 구성 파일의 네트워크 인터페이스로 지정합니다.


CAUTION: Bond 또는 Bridge 장치를 컨테이너 네트워크 인터페이스로 직접 사용하지 마십시오. 이렇게 하면 컨테이너 네임스페이스에서 결합 및 브리지 장치와 함께 macvlan을 사용하는 커널 문제로 인해 노드 시작이 방지될 수 있습니다.

또는 link:../ubuntu/index.html["Ubuntu 또는 Debian"] 배포에 대한 설치 지침을 link:../rhel/index.html["Red Hat Enterprise Linux"]참조하십시오.



== 컨테이너 엔진 구축을 위한 호스트 네트워크 구성

컨테이너 엔진 플랫폼에서 StorageGRID 배포를 시작하기 전에 각 노드에서 사용할 네트워크(그리드, 관리자, 클라이언트)를 결정합니다. 각 노드의 네트워크 인터페이스가 올바른 가상 또는 물리적 호스트 인터페이스에 구성되어 있고 각 네트워크에 충분한 대역폭이 있는지 확인해야 합니다.



=== 물리적 호스트

물리적 호스트를 사용하여 그리드 노드를 지원하는 경우:

* 모든 호스트가 각 노드 인터페이스에 대해 동일한 호스트 인터페이스를 사용해야 합니다. 이 전략은 호스트 구성을 간소화하고 향후 노드 마이그레이션을 지원합니다.
* 물리적 호스트 자체의 IP 주소를 가져옵니다.
+

NOTE: 호스트의 물리적 인터페이스는 호스트 자체와 호스트에서 실행 중인 하나 이상의 노드에서 사용할 수 있습니다. 이 인터페이스를 사용하여 호스트에 할당된 모든 IP 주소는 고유해야 합니다. 호스트와 노드는 IP 주소를 공유할 수 없습니다.

* 호스트에 필요한 포트를 엽니다.
* StorageGRID에서 VLAN 인터페이스를 사용하려면 호스트에 원하는 VLAN에 대한 액세스를 제공하는 하나 이상의 트렁크 인터페이스가 있어야 합니다. 이러한 인터페이스는 eth0, eth2 또는 추가 인터페이스로 노드 컨테이너에 전달될 수 있습니다. 트렁크 또는 액세스 인터페이스를 추가하려면 다음을 참조하십시오.
+
** * RHEL(노드 설치 전) *: link:../rhel/creating-node-configuration-files.html["노드 구성 파일을 생성합니다"]
** * Ubuntu 또는 Debian (노드를 설치하기 전에) *: link:../ubuntu/creating-node-configuration-files.html["노드 구성 파일을 생성합니다"]
** * RHEL, Ubuntu 또는 Debian(노드 설치 후) *: link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["Linux: 노드에 트렁크 또는 액세스 인터페이스를 추가합니다"]






=== 최소 대역폭 권장 사항

다음 표에는 각 유형의 StorageGRID 노드 및 각 네트워크 유형에 대한 최소 LAN 대역폭 권장 사항이 나와 있습니다. 해당 호스트에서 실행하려는 StorageGRID 노드의 총 수와 유형에 대한 총 최소 대역폭 요구 사항을 충족할 수 있도록 충분한 네트워크 대역폭을 사용하여 각 물리적 호스트 또는 가상 호스트를 프로비저닝해야 합니다.

[cols="1a,1a,1a,1a"]
|===
| 노드 유형입니다 3+| 네트워크 유형입니다 


 a| 
 a| 
그리드
 a| 
관리자
 a| 
클라이언트



 a| 
 a| 
* 최소 LAN 대역폭 *



 a| 
관리자
 a| 
10Gbps
 a| 
1Gbps
 a| 
1Gbps



 a| 
게이트웨이
 a| 
10Gbps
 a| 
1Gbps
 a| 
10Gbps



 a| 
스토리지
 a| 
10Gbps
 a| 
1Gbps
 a| 
10Gbps



 a| 
아카이브
 a| 
10Gbps
 a| 
1Gbps
 a| 
10Gbps

|===

NOTE: 이 테이블에는 공유 스토리지에 액세스하는 데 필요한 SAN 대역폭이 포함되지 않습니다. 이더넷(iSCSI 또는 FCoE)을 통해 액세스되는 공유 스토리지를 사용하는 경우 충분한 SAN 대역폭을 제공하기 위해 각 호스트에 별도의 물리적 인터페이스를 프로비저닝해야 합니다. 병목 현상을 방지하기 위해 특정 호스트의 SAN 대역폭은 해당 호스트에서 실행 중인 모든 스토리지 노드의 집계 스토리지 노드 네트워크 대역폭과 거의 일치해야 합니다.

이 표를 사용하여 해당 호스트에서 실행하려는 StorageGRID 노드의 수와 유형에 따라 각 호스트에 프로비저닝할 최소 네트워크 인터페이스 수를 결정합니다.

예를 들어 단일 호스트에서 하나의 관리 노드, 하나의 게이트웨이 노드 및 하나의 스토리지 노드를 실행하려면 다음을 수행합니다.

* 관리 노드에서 그리드 및 관리 네트워크 연결(10 + 1 = 11Gbps 필요)
* 게이트웨이 노드에서 그리드 및 클라이언트 네트워크 연결(10 + 10 = 20Gbps 필요)
* 스토리지 노드에서 그리드 네트워크 연결(10Gbps 필요)


이 시나리오에서는 최소 11 + 20 + 10 = 41Gbps의 네트워크 대역폭을 제공해야 합니다. 이 인터페이스는 2개의 40Gbps 인터페이스 또는 5개의 10Gbps 인터페이스를 통해 충족될 수 있으며, 잠재적으로 트렁크로 집계된 다음 그리드, 관리 및 클라이언트 서브넷을 포함하는 물리적 데이터 센터에 로컬로 전달하는 3개 이상의 VLAN에서 공유할 수 있습니다.

StorageGRID 구축을 준비하기 위해 StorageGRID 클러스터의 호스트에서 물리적 리소스와 네트워크 리소스를 구성하는 몇 가지 권장 방법은 다음을 참조하십시오.

* link:../rhel/configuring-host-network.html["호스트 네트워크 구성(Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html["호스트 네트워크 구성(Ubuntu 또는 Debian)"]

