---
permalink: network/network-installation-and-provisioning.html 
sidebar: sidebar 
keywords: network install, network provisioning 
summary: 노드 배포 및 그리드 구성 중에 그리드 네트워크와 선택적 관리 및 클라이언트 네트워크가 어떻게 사용되는지 이해해야 합니다. 
---
= 네트워크 설치 및 프로비저닝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 배포 및 그리드 구성 중에 그리드 네트워크와 선택적 관리 및 클라이언트 네트워크가 어떻게 사용되는지 이해해야 합니다.



== 노드의 초기 구축

노드를 처음 배포할 때는 노드를 그리드 네트워크에 연결하고 기본 관리 노드에 대한 액세스 권한이 있는지 확인해야 합니다. 그리드 네트워크가 격리된 경우 그리드 네트워크 외부에서 구성 및 설치 액세스를 위해 기본 관리 노드에서 관리 네트워크를 구성할 수 있습니다.

게이트웨이가 구성된 그리드 네트워크는 구축 중에 노드의 기본 게이트웨이가 됩니다. 기본 게이트웨이를 사용하면 그리드를 구성하기 전에 별도의 서브넷의 그리드 노드가 운영 관리자 노드와 통신할 수 있습니다.

필요한 경우 NTP 서버가 포함되어 있거나 그리드 관리자 또는 API에 대한 액세스가 필요한 서브넷을 그리드 서브넷으로 구성할 수도 있습니다.



== 운영 관리 노드를 사용한 자동 노드 등록

노드가 배포된 후 그리드 네트워크를 사용하여 기본 관리 노드에 등록됩니다. 그런 다음 Grid Manager, Python 스크립트 또는 Installation API를 사용하여 그리드를 구성하고 등록된 노드를 승인할 수 `configure-storagegrid.py` 있습니다. 그리드 구성 중에 여러 그리드 서브넷을 구성할 수 있습니다. 그리드 네트워크 게이트웨이를 통해 이러한 서브넷에 대한 정적 라우트는 그리드 구성을 완료하면 각 노드에 생성됩니다.



== 관리 네트워크 또는 클라이언트 네트워크 비활성화

관리 네트워크 또는 클라이언트 네트워크를 사용하지 않도록 설정하려면 노드 승인 프로세스 중에 구성을 제거하거나 설치가 완료된 후 IP 변경 도구를 사용할 수 있습니다(참조link:../maintain/configuring-ip-addresses.html["IP 주소를 구성합니다"]).
