= 
:allow-uri-read: 


[role="tabbed-block"]
====
.복제된 데이터
--
* 복제된 복구의 예상 완료율을 얻으려면 repair-data 명령에 옵션을 추가합니다 `show-replicated-repair-status`.
+
`repair-data show-replicated-repair-status`

* 수리가 완료되었는지 확인하려면:
+
.. 노드 * > * _ 복구되는 스토리지 노드 _ * > * ILM * 을 선택합니다.
.. 평가 섹션의 속성을 검토합니다. 복구가 완료되면 * Awaiting-all * 속성이 0 개체를 나타냅니다.


* 수리를 더 자세히 모니터링하려면:
+
.. 노드 * 를 선택합니다.
.. _GRID NAME_ * > * ILM * 을 선택합니다.
.. ILM 대기열 그래프 위에 커서를 올려 놓고 * Scan rate (objects/sec) * 속성 값을 확인합니다. 이 값은 그리드의 객체가 스캔되고 ILM을 위해 대기하는 속도입니다.
.. ILM 대기열 섹션에서 다음 속성을 확인합니다.
+
*** * 스캔 기간 - 추정 * : 모든 개체의 전체 ILM 스캔을 완료하는 데 걸리는 예상 시간입니다.
+
전체 검사를 수행한다고 해서 ILM이 모든 개체에 적용되었다고 보장할 수는 없습니다.

*** * Repairs attemed *: 시도한 복제된 데이터에 대한 총 개체 복구 작업 수입니다. 이 수는 스토리지 노드가 고위험 객체를 복구하려고 할 때마다 증가합니다. 그리드가 사용 중인 경우 위험이 높은 ILM 수리의 우선 순위가 지정됩니다.
+
복구 후 복제에 실패한 경우 동일한 객체 복구가 다시 증가할 수 있습니다. + 이러한 속성은 스토리지 노드 볼륨 복구 진행률을 모니터링할 때 유용할 수 있습니다. 시도한 수리 수가 더 이상 증가하지 않고 전체 검사가 완료된 경우 수리가 완료된 것일 수 있습니다.



.. 또는 및 `storagegrid_ilm_repairs_attempted` 에 대한 Prometheus 쿼리를 `storagegrid_ilm_scan_period_estimated_minutes` 제출합니다.




--
.삭제 코딩(EC) 데이터
--
삭제 코딩 데이터의 복구를 모니터링하고 실패한 요청을 다시 시도하려면 다음을 수행하십시오.

. 삭제 코딩 데이터 복구 상태를 확인합니다.
+
** 현재 작업의 예상 완료 시간과 완료 비율을 보려면 * 지원 * > * 도구 * > * 메트릭 * 을 선택합니다. 그런 다음 Grafana 섹션에서 * EC 개요 * 를 선택합니다. Grid EC Job Ec Job Estimated Time to Completion * 및 * Grid EC Job Percentage Completed * 대시보드를 확인합니다.
** 다음 명령을 사용하여 특정 작업의 상태를 `repair-data` 확인합니다.
+
`repair-data show-ec-repair-status --repair-id repair ID`

** 이 명령을 사용하여 모든 수리를 나열합니다.
+
`repair-data show-ec-repair-status`

+
출력에는 이전 및 현재 실행 중인 모든 수리에 대한 정보가 `repair ID` 표시됩니다.



. 출력에 복구 작업이 실패했다고 표시되는 경우 옵션을 사용하여 `--repair-id` 복구를 재시도합니다.
+
이 명령은 복구 ID 6949309319275667690을 사용하여 실패한 노드 복구를 재시도합니다.

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
이 명령은 복구 ID 6949309319275667690을 사용하여 실패한 볼륨 복구를 다시 시도합니다.

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====