= 스토리지 노드의 호스트 이름을 찾습니다
:allow-uri-read: 




== 스토리지 노드의 호스트 이름을 찾습니다

. 기본 관리자 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@_primary_Admin_Node_IP_`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
.. 다음 명령을 입력하여 루트로 전환합니다. `su -`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
+
루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.



. 파일을 사용하여 `/etc/hosts` 복구된 스토리지 볼륨에 대한 스토리지 노드의 호스트 이름을 찾습니다. 그리드에 있는 모든 노드의 목록을 보려면 다음을 입력합니다 `cat /etc/hosts`.




== 모든 볼륨이 실패한 경우 데이터를 복구합니다

모든 스토리지 볼륨에 장애가 발생한 경우 전체 노드를 복구합니다. 복제된 데이터 *, * 삭제 코딩(EC) 데이터 * 또는 둘 다에 대한 지침을 따르십시오. 복제된 데이터, 삭제 코딩(EC) 데이터 또는 둘 모두를 사용하는지 여부에 따라 달라집니다.

일부 볼륨에만 장애가 발생한 경우 로 이동합니다<<일부 볼륨만 장애가 발생한 경우 데이터를 복구합니다>>.


NOTE: 둘 이상의 노드에 대한 작업을 동시에 실행할 수 `repair-data` 없습니다. 여러 노드를 복구하려면 기술 지원 팀에 문의하십시오.

[role="tabbed-block"]
====
.복제된 데이터
--
그리드에 복제된 데이터가 포함되어 있는 경우 `repair-data start-replicated-node-repair` 명령을 옵션(여기서 `--nodes` 는 호스트 이름(시스템 이름))과 함께 `--nodes` 사용하여 전체 스토리지 노드를 복구합니다.

이 명령은 SG-DC-SN3이라는 스토리지 노드에서 복제된 데이터를 복구합니다.

`repair-data start-replicated-node-repair --nodes SG-DC-SN3`


NOTE: 개체 데이터가 복원되면 StorageGRID 시스템에서 복제된 개체 데이터를 찾을 수 없는 경우 * 개체 손실 * 경고가 트리거됩니다. 시스템 전체의 스토리지 노드에서 경고가 트리거될 수 있습니다. 손실의 원인과 복구가 가능한지 확인해야 합니다. 을 link:../troubleshoot/investigating-lost-objects.html["손실된 개체를 조사합니다"]참조하십시오.

--
.삭제 코딩(EC) 데이터
--
그리드에 삭제 코딩 데이터가 포함되어 있는 경우 명령을 옵션과 함께 `--nodes` 사용합니다. 여기서 는 호스트 이름(시스템 이름) 옵션을 `--nodes` 사용하여 `repair-data start-ec-node-repair` 전체 스토리지 노드를 복구합니다.

이 명령은 이름이 SG-DC-SN3인 스토리지 노드에서 삭제 코딩 데이터를 복구합니다.

`repair-data start-ec-node-repair --nodes SG-DC-SN3`

이 작업은 이 작업을 식별하는 `repair_data` 고유 을 `repair ID` 반환합니다. 이 버튼을 사용하여 `repair ID` 작업의 진행 상황과 결과를 `repair_data` 추적합니다. 복구 프로세스가 완료되어도 다른 피드백이 반환되지 않습니다.

일부 스토리지 노드가 오프라인인 상태에서 삭제 코딩 데이터 복구를 시작할 수 있습니다. 모든 노드를 사용할 수 있게 되면 복구가 완료됩니다.

--
====


== 일부 볼륨만 장애가 발생한 경우 데이터를 복구합니다

일부 볼륨만 장애가 발생한 경우 영향을 받는 볼륨을 복구합니다. 복제된 데이터 *, * 삭제 코딩(EC) 데이터 * 또는 둘 다에 대한 지침을 따르십시오. 복제된 데이터, 삭제 코딩(EC) 데이터 또는 둘 모두를 사용하는지 여부에 따라 달라집니다.

모든 볼륨에 오류가 발생한 경우 로 이동합니다<<모든 볼륨이 실패한 경우 데이터를 복구합니다>>.

볼륨 ID를 16진수로 입력합니다. 예를 들어 `0000`, 은 첫 번째 볼륨이고 `000F` 는 16번째 볼륨입니다. 하나의 볼륨, 하나의 볼륨 범위 또는 하나의 시퀀스에 없는 여러 볼륨을 지정할 수 있습니다.

모든 볼륨은 동일한 스토리지 노드에 있어야 합니다. 둘 이상의 스토리지 노드에 대한 볼륨을 복원해야 하는 경우 기술 지원 부서에 문의하십시오.

[role="tabbed-block"]
====
.복제된 데이터
--
그리드에 복제된 데이터가 포함되어 있는 경우 `start-replicated-volume-repair` 명령을 옵션과 함께 `--nodes` 사용하여 노드를 식별합니다(여기서 `--nodes` 는 노드의 호스트 이름). 그런 다음 다음 다음 `--volumes` 예제와 같이 또는 `--volume-range` 옵션을 추가합니다.

* 단일 볼륨 *: 이 명령은 복제된 데이터를 SG-DC-SN3이라는 스토리지 노드의 볼륨에 복원합니다 `0002`.

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0002`

* 볼륨 범위 *: 이 명령은 `0009` SG-DC-SN3이라는 이름의 스토리지 노드에 있는 범위 내의 모든 볼륨에 복제된 데이터를 복원합니다 `0003`.

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009`

*연속되지 않은 여러 볼륨 *: 이 명령은 복제된 데이터를 볼륨, `0005` `0008` SG-DC-SN3이라는 스토리지 노드에서 복원합니다. `0001`

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0001,0005,0008`


NOTE: 개체 데이터가 복원되면 StorageGRID 시스템에서 복제된 개체 데이터를 찾을 수 없는 경우 * 개체 손실 * 경고가 트리거됩니다. 시스템 전체의 스토리지 노드에서 경고가 트리거될 수 있습니다. 경고 설명 및 권장 조치를 참고하여 손실의 원인을 파악하고 복구가 가능한지 여부를 확인합니다.

--
.삭제 코딩(EC) 데이터
--
그리드에 삭제 코딩 데이터가 포함되어 있는 경우 `start-ec-volume-repair` 명령을 옵션과 함께 `--nodes` 사용하여 노드를 식별합니다(여기서 `--nodes` 는 노드의 호스트 이름). 그런 다음 다음 다음 `--volumes` 예제와 같이 또는 `--volume-range` 옵션을 추가합니다.

* 단일 볼륨 *: 이 명령은 SG-DC-SN3이라는 이름의 스토리지 노드의 볼륨에 삭제 코딩 데이터를 복원합니다 `0007`.

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 0007`

* 볼륨 범위 *: 이 명령은 `0006` SG-DC-SN3이라는 이름의 스토리지 노드에 있는 범위 내의 모든 볼륨에 삭제 코딩 데이터를 복원합니다 `0004`.

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volume-range 0004,0006`

*연속되지 않은 여러 볼륨 *: 이 명령은 삭제 코딩 데이터를 볼륨, `000C` `000E` SG-DC-SN3이라는 스토리지 노드에서 복원합니다. `000A`

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 000A,000C,000E`

 `repair-data`이 작업은 이 작업을 식별하는 `repair_data` 고유 을 `repair ID` 반환합니다. 이 버튼을 사용하여 `repair ID` 작업의 진행 상황과 결과를 `repair_data` 추적합니다. 복구 프로세스가 완료되어도 다른 피드백이 반환되지 않습니다.


NOTE: 일부 스토리지 노드가 오프라인인 상태에서 삭제 코딩 데이터 복구를 시작할 수 있습니다. 모든 노드를 사용할 수 있게 되면 복구가 완료됩니다.

--
====