= S3 오브젝트 잠금이 설정된 버킷의 요구 사항
:allow-uri-read: 




== S3 오브젝트 잠금이 설정된 버킷의 요구 사항

* StorageGRID 시스템에 대해 글로벌 S3 오브젝트 잠금 설정이 활성화된 경우 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 S3 오브젝트 잠금이 활성화된 버킷을 생성할 수 있습니다.
* S3 오브젝트 잠금을 사용하려는 경우 버킷을 생성할 때 S3 오브젝트 잠금을 활성화해야 합니다. 기존 버킷에 S3 오브젝트 잠금을 설정할 수 없습니다.
* 버킷에 대해 S3 오브젝트 잠금이 활성화된 경우 StorageGRID는 해당 버킷의 버전 관리를 자동으로 활성화합니다. 버킷의 S3 오브젝트 잠금을 비활성화하거나 버전 관리를 일시 중단할 수 없습니다.
* 필요에 따라 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 각 버킷의 기본 보존 모드 및 보존 기간을 지정할 수 있습니다. 버킷의 기본 보존 설정은 고유한 보존 설정이 없는 버킷에 추가된 새 오브젝트에만 적용됩니다. 이 기본 설정은 업로드할 때 각 개체 버전에 대해 보존 모드 및 보존 종료 날짜를 지정하여 재정의할 수 있습니다.
* S3 오브젝트 잠금이 설정된 버킷에 대해 버킷 라이프사이클 구성이 지원됩니다.
* S3 오브젝트 잠금이 설정된 버킷에는 CloudMirror 복제가 지원되지 않습니다.




== S3 오브젝트 잠금이 설정된 버킷의 오브젝트 요구사항

* 개체 버전을 보호하려면 버킷의 기본 보존 설정을 지정하거나 각 오브젝트 버전에 대한 보존 설정을 지정할 수 있습니다. 오브젝트 레벨의 보존 설정은 S3 클라이언트 애플리케이션 또는 S3 REST API를 사용하여 지정할 수 있습니다.
* 보존 설정은 개별 개체 버전에 적용됩니다. 개체 버전에는 보존 기한 및 법적 보류 설정이 둘 다 있을 수 있으며, 둘 중 하나만 설정할 수도 있고 둘 다 가질 수도 없습니다. 개체에 대한 보존 기한 또는 법적 보류 설정을 지정하면 요청에 지정된 버전만 보호됩니다. 이전 버전의 개체는 잠겨 있는 상태에서 새 버전의 개체를 만들 수 있습니다.




== S3 오브젝트 잠금이 설정된 버킷의 오브젝트 라이프사이클

S3 오브젝트 잠금이 설정된 버킷에 저장된 각 오브젝트는 다음 단계를 거칩니다.

. * 오브젝트 수집 *
+
오브젝트 버전이 S3 오브젝트 잠금이 설정된 버킷에 추가되면 보존 설정이 다음과 같이 적용됩니다.

+
** 개체에 대한 보존 설정이 지정된 경우 개체 수준 설정이 적용됩니다. 기본 버킷 설정은 무시됩니다.
** 개체에 대해 보존 설정을 지정하지 않으면 기본 버킷 설정이 적용됩니다(있는 경우).
** 오브젝트 또는 버킷에 대해 보존 설정을 지정하지 않으면 S3 오브젝트 잠금으로 오브젝트가 보호되지 않습니다.


+
보존 설정이 적용되는 경우 오브젝트와 S3 사용자 정의 메타데이터는 모두 보호됩니다.

. * 개체 보존 및 삭제 *
+
StorageGRID는 지정된 보존 기간 동안 보호된 각 개체의 복사본을 여러 개 저장합니다. 오브젝트 복사본 및 스토리지 위치의 정확한 수와 유형은 활성 ILM 정책의 규정 준수 규칙에 따라 결정됩니다. 보존 기한이 되기 전에 보호된 개체를 삭제할 수 있는지 여부는 보존 모드에 따라 다릅니다.

+
** 개체가 법적 보류 중인 경우 보존 모드에 관계없이 개체를 삭제할 수 없습니다.



