---
permalink: tenant/changing-bucket-versioning.html 
sidebar: sidebar 
keywords: how to change bucket versioning, disabled versioning, enabled versioning, suspended versioning 
summary: S3 테넌트를 사용하는 경우 S3 버킷의 버전 관리 상태를 변경할 수 있습니다. 
---
= 버킷의 오브젝트 버전 관리를 변경합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 테넌트를 사용하는 경우 S3 버킷의 버전 관리 상태를 변경할 수 있습니다.

.시작하기 전에
* 를 사용하여 테넌트 관리자에 로그인되어 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 이 있는 사용자 그룹에 속해 link:tenant-management-permissions.html["모든 버킷 또는 루트 액세스 권한을 관리합니다"]있습니다. 이러한 권한은 그룹 또는 버킷 정책의 사용 권한 설정을 재정의합니다.
* 필요한 수의 스토리지 노드 및 사이트를 사용할 수 있는지 확인했습니다. 사이트 내에서 두 개 이상의 스토리지 노드를 사용할 수 없거나 사이트를 사용할 수 없는 경우 이러한 설정을 변경하지 못할 수 있습니다.


.이 작업에 대해
버킷에 대한 오브젝트 버전 관리를 설정하거나 일시 중지할 수 있습니다. 버켓에 대한 버전 관리를 활성화한 후에는 버전이 지정되지 않은 상태로 돌아갈 수 없습니다. 그러나 버킷의 버전 관리를 일시 중단할 수 있습니다.

* 사용 안 함: 버전 관리가 활성화되지 않았습니다
* 사용: 버전 관리가 활성화됩니다
* 일시 중단됨: 버전 관리가 이전에 활성화되었으며 일시 중단되었습니다


자세한 내용은 다음을 참조하십시오.

* link:../s3/object-versioning.html["오브젝트 버전 관리"]
* link:../ilm/example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["S3 버전 오브젝트 ILM 규칙 및 정책(예 4)"]
* link:../ilm/how-objects-are-deleted.html["오브젝트 삭제 방법"]


.단계
. 대시보드에서 * 버킷 보기 * 를 선택하거나 * 스토리지(S3) * > * 버킷 * 을 선택합니다.
. 테이블에서 버킷 이름을 선택합니다.
+
버킷 세부 정보 페이지가 나타납니다.

. Bucket options * 탭에서 * Object Version * 아코디언을 선택합니다.
. 이 버킷의 오브젝트에 대한 버전 관리 상태를 선택합니다.
+
오브젝트 버전 관리는 교차 그리드 복제에 사용되는 버킷에 대해 활성화된 상태를 유지해야 합니다. S3 오브젝트 잠금 또는 레거시 규정 준수를 활성화하면 * 오브젝트 버전 관리 * 옵션이 비활성화됩니다.

+
[cols="1a,3a"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
버전 관리를 활성화합니다
 a| 
이 버킷에 각 오브젝트의 모든 버전을 저장하려면 오브젝트 버전 관리를 활성화하십시오. 그런 다음 필요에 따라 개체의 이전 버전을 검색할 수 있습니다.

버킷에 이미 있던 객체는 사용자가 수정할 때 버전이 적용됩니다.



 a| 
버전 관리를 일시 중단합니다
 a| 
새 개체 버전을 더 이상 만들지 않으려면 개체 버전 관리를 일시 중단합니다. 기존 개체 버전을 검색할 수 있습니다.

|===
. 변경 내용 저장 * 을 선택합니다.

