---
permalink: tenant/configuring-cloudmirror-replication.html 
sidebar: sidebar 
keywords: how to configure CloudMirror replication, replication xml 
summary: 버킷 복제 구성 XML을 생성하고 테넌트 관리자를 사용하여 XML을 버킷에 적용하여 버킷에 대한 CloudMirror 복제를 활성화합니다. 
---
= CloudMirror 복제를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
버킷에 대해 CloudMirror 복제를 활성화하려면 유효한 버킷 복제 구성 XML을 생성하고 적용합니다.

.시작하기 전에
* StorageGRID 관리자가 테넌트 계정에 대해 플랫폼 서비스를 활성화했습니다.
* 복제 소스로 사용할 버킷을 이미 생성했습니다.
* CloudMirror 복제의 대상으로 사용하려는 엔드포인트가 이미 있으며 URN이 있습니다.
* 이 있는 사용자 그룹에 속해 link:tenant-management-permissions.html["모든 버킷 또는 루트 액세스 권한을 관리합니다"]있습니다. 이러한 권한은 테넌트 관리자를 사용하여 버킷을 구성할 때 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.


.이 작업에 대해
CloudMirror 복제는 소스 버킷에서 엔드포인트에 지정된 대상 버킷으로 객체를 복제합니다.

버킷 복제에 대한 일반적인 정보와 이를 구성하는 방법은 을 참조하십시오 https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html["Amazon S3(Simple Storage Service) 문서: 오브젝트 복제"^]. StorageGRID에서 GetBucketReplication, DeleteBucketReplication 및 PutBucketReplication을 구현하는 방법에 대한 자세한 내용은 를 참조하십시오link:../s3/operations-on-buckets.html["버킷 작업"].


NOTE: CloudMirror 복제는 교차 그리드 복제 기능과의 중요한 유사점과 차이점이 있습니다. 자세한 내용은 을 참조하십시오link:../admin/grid-federation-compare-cgr-to-cloudmirror.html["교차 그리드 복제와 CloudMirror 복제를 비교합니다"].

CloudMirror 복제를 구성할 때 다음과 같은 요구 사항 및 특성에 유의하십시오.

* 유효한 버킷 복제 구성 XML을 만들고 적용할 때 각 대상에 대해 S3 버킷 끝점의 URN을 사용해야 합니다.
* S3 오브젝트 잠금이 활성화된 소스 또는 대상 버킷에는 복제가 지원되지 않습니다.
* 객체가 포함된 버킷에서 CloudMirror 복제를 활성화하면 버킷에 추가된 새 객체가 복제되지만 버킷의 기존 객체는 복제되지 않습니다. 복제를 트리거하려면 기존 객체를 업데이트해야 합니다.
* 복제 구성 XML에서 스토리지 클래스를 지정하는 경우 StorageGRID는 대상 S3 끝점에 대해 작업을 수행할 때 해당 클래스를 사용합니다. 대상 끝점은 지정된 저장소 클래스도 지원해야 합니다. 대상 시스템 공급업체에서 제공하는 권장 사항을 따르십시오.


.단계
. 소스 버킷에 대한 복제 지원:
+
** 텍스트 편집기를 사용하여 S3 복제 API에 지정된 대로 복제를 활성화하는 데 필요한 복제 구성 XML을 생성합니다.
** XML을 구성할 때:
+
*** StorageGRID는 복제 구성의 V1만 지원합니다. 즉, StorageGRID는 규칙에 요소 사용을 지원하지 `Filter` 않으며 객체 버전을 삭제하기 위한 V1 규칙을 따릅니다. 자세한 내용은 복제 구성에 대한 Amazon 설명서를 참조하십시오.
*** S3 버킷 엔드포인트의 URN을 대상으로 사용합니다.
*** 선택적으로 `<StorageClass>` 요소를 추가하고 다음 중 하나를 지정합니다.
+
****  `STANDARD`: 기본 스토리지 클래스입니다. 개체를 업로드할 때 저장소 클래스를 지정하지 않으면 `STANDARD` 저장소 클래스가 사용됩니다.
**** `STANDARD_IA`: (표준 - 자주 액세스하지 않음) 자주 액세스하지 않지만 필요할 때 빠르게 액세스해야 하는 데이터에 이 스토리지 클래스를 사용합니다.
**** `REDUCED_REDUNDANCY`: 스토리지 클래스보다 낮은 중복성으로 저장할 수 있는 비중요하고 재현 가능한 데이터에 이 스토리지 클래스를 `STANDARD` 사용합니다.


*** 구성 XML에서 을 `Role` 지정하면 이 작업은 무시됩니다. 이 값은 StorageGRID에서 사용되지 않습니다.
+
[listing]
----
<ReplicationConfiguration>
    <Role></Role>
    <Rule>
        <Status>Enabled</Status>
        <Prefix>2020</Prefix>
        <Destination>
           <Bucket>urn:sgws:s3:::2017-records</Bucket>
           <StorageClass>STANDARD</StorageClass>
         </Destination>
     </Rule>
</ReplicationConfiguration>
----




. 대시보드에서 * 버킷 보기 * 를 선택하거나 * 스토리지(S3) * > * 버킷 * 을 선택합니다.
. 소스 버킷의 이름을 선택합니다.
+
버킷 세부 정보 페이지가 나타납니다.

. 플랫폼 서비스 * > * 복제 * 를 선택합니다.
. 복제 사용 * 확인란을 선택합니다.
. 복제 구성 XML을 텍스트 상자에 붙여 넣고 * 변경 내용 저장 * 을 선택합니다.
+

NOTE: 그리드 관리자 또는 그리드 관리 API를 사용하여 StorageGRID 관리자가 각 테넌트 계정에 대해 플랫폼 서비스를 활성화해야 합니다. 구성 XML을 저장할 때 오류가 발생하면 StorageGRID 관리자에게 문의하십시오.

. 복제가 올바르게 구성되었는지 확인합니다.
+
.. 복제 구성에 지정된 대로 복제 요구 사항을 충족하는 객체를 소스 버킷에 추가합니다.
+
앞에 나와 있는 예에서 접두사 "2020"과 일치하는 객체가 복제됩니다.

.. 객체가 대상 버킷에 복제되었는지 확인합니다.
+
오브젝트 크기가 작은 경우 복제가 빠르게 수행됩니다.





.관련 정보
link:creating-platform-services-endpoint.html["플랫폼 서비스 끝점을 만듭니다"]
