---
permalink: tenant/configuring-cross-origin-resource-sharing-for-buckets-and-objects.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors 
summary: '다른 도메인의 웹 애플리케이션에서 해당 버킷의 버킷 및 오브젝트에 액세스할 수 있도록 하려면 S3 버킷에 대해 CORS(Cross-Origin Resource Sharing)\ 를 구성할 수 있습니다.' 
---
= 버킷 및 객체에 대한 StorageGRID CORS 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다른 도메인의 웹 애플리케이션에서 해당 버킷의 버킷 및 오브젝트에 액세스할 수 있도록 하려면 S3 버킷에 대해 CORS(Cross-Origin Resource Sharing)를 구성할 수 있습니다.

.시작하기 전에
* 를 사용하여 테넌트 관리자에 로그인되어 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* GET CORS 구성 요청의 경우 이 있는 사용자 그룹에 속해 link:tenant-management-permissions.html["모든 버킷을 관리하거나 모든 버킷을 봅니다"]있습니다. 이러한 권한은 그룹 또는 버킷 정책의 사용 권한 설정을 재정의합니다.
* PUT CORS 구성 요청의 경우 이 있는 사용자 그룹에 속해 link:tenant-management-permissions.html["모든 버킷 사용 권한을 관리합니다"]있습니다. 이 권한은 그룹 또는 버킷 정책의 사용 권한 설정을 재정의합니다.
* 는 link:tenant-management-permissions.html["루트 액세스 권한"]모든 CORS 구성 요청에 대한 액세스를 제공합니다.


.이 작업에 대해
CORS(Cross-origin Resource Sharing)는 한 도메인의 클라이언트 웹 애플리케이션이 다른 도메인의 리소스에 액세스할 수 있도록 하는 보안 메커니즘입니다. 예를 들어, 이라는 S3 버킷을 사용하여 그래픽을 저장한다고 가정해 `Images` 보겠습니다. 버킷에 대한 CORS를 구성하면 `Images` 해당 버킷의 이미지가 웹사이트에 표시되도록 할 수 `+http://www.example.com+` 있습니다.



== 버킷에 대해 CORS를 활성화합니다

.단계
. 텍스트 편집기를 사용하여 필요한 XML을 만듭니다. 이 예에서는 S3 버킷에 대해 CORS를 활성화하는 데 사용되는 XML을 보여 줍니다. 주요 내용은 다음과 같습니다.
+
** 모든 도메인이 버킷으로 GET 요청을 보낼 수 있도록 허용합니다
** 도메인에서만 GET, POST 및 삭제 요청을 보낼 수 있습니다 `+http://www.example.com+`
** 모든 요청 헤더가 허용됩니다
+
[listing]
----
<CORSConfiguration
    xmlns="http://s3.amazonaws.com/doc/2020-10-22/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>http://www.example.com</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
----
+
CORS 구성 XML에 대한 자세한 내용은 을 참조하십시오 http://docs.aws.amazon.com/AmazonS3/latest/dev/Welcome.html["AWS(Amazon Web Services) 설명서: Amazon Simple Storage Service 사용 설명서"^].



. 대시보드에서 * 버킷 보기 * 를 선택하거나 * 스토리지(S3) * > * 버킷 * 을 선택합니다.
. 테이블에서 버킷 이름을 선택합니다.
+
버킷 세부 정보 페이지가 나타납니다.

. Bucket access * 탭에서 * CORS(Cross-Origin Resource Sharing) * 아코디언을 선택합니다.
. CORS * 활성화 확인란을 선택합니다.
. 텍스트 상자에 CORS 구성 XML을 붙여 넣습니다.
. 변경 내용 저장 * 을 선택합니다.




== CORS 설정을 수정합니다

.단계
. 텍스트 상자에서 CORS 구성 XML을 업데이트하거나 다시 시작하려면 * Clear * 를 선택합니다.
. 변경 내용 저장 * 을 선택합니다.




== CORS 설정을 비활성화합니다

.단계
. CORS * 활성화 확인란의 선택을 취소합니다.
. 변경 내용 저장 * 을 선택합니다.


.관련 정보
link:../admin/enable-cross-origin-resource-sharing-for-management-interface.html["관리 인터페이스에 대한 StorageGRID CORS 구성"]
