---
permalink: tenant/creating-groups-for-swift-tenant.html 
sidebar: sidebar 
keywords: how to create Swift tenant groups 
summary: 통합 그룹을 가져오거나 로컬 그룹을 생성하여 Swift 테넌트 계정에 대한 액세스 권한을 관리할 수 있습니다. 하나 이상의 그룹에 Swift 관리자 권한이 있어야 합니다. 이 권한은 Swift 테넌트 계정의 컨테이너 및 개체를 관리하는 데 필요합니다. 
---
= Swift 테넌트의 그룹을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
통합 그룹을 가져오거나 로컬 그룹을 생성하여 Swift 테넌트 계정에 대한 액세스 권한을 관리할 수 있습니다. 하나 이상의 그룹에 Swift 관리자 권한이 있어야 합니다. 이 권한은 Swift 테넌트 계정의 컨테이너 및 개체를 관리하는 데 필요합니다.


NOTE: Swift 클라이언트 응용 프로그램에 대한 지원은 더 이상 사용되지 않으며 향후 릴리스에서 제거될 예정입니다.

.시작하기 전에
* 를 사용하여 테넌트 관리자에 로그인되어 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 이 있는 사용자 그룹에 속해 link:tenant-management-permissions.html["루트 액세스 권한"]있습니다.
* 통합 그룹을 가져오려는 경우 이 link:using-identity-federation.html["ID 페더레이션을 구성했습니다"]있으며 페더레이션 그룹이 구성된 ID 원본에 이미 있습니다.




== 그룹 생성 마법사에 액세스합니다

.단계
첫 번째 단계로 그룹 생성 마법사에 액세스합니다.

. 액세스 관리 * > * 그룹 * 을 선택합니다.
. Create group * 을 선택합니다.




== 그룹 유형을 선택합니다

로컬 그룹을 생성하거나 통합 그룹을 가져올 수 있습니다.

.단계
. 로컬 그룹을 생성하려면 * Local group * 탭을 선택하고, 이전에 구성된 ID 소스에서 그룹을 가져오려면 * Federated group * 탭을 선택합니다.
+
StorageGRID 시스템에서 SSO(Single Sign-On)를 사용하는 경우 로컬 그룹에 속한 사용자는 그룹 권한에 따라 클라이언트 애플리케이션을 사용하여 테넌트의 리소스를 관리할 수 있지만 테넌트 관리자에 로그인할 수 없습니다.

. 그룹의 이름을 입력합니다.
+
** * 로컬 그룹 *: 표시 이름과 고유 이름을 모두 입력합니다. 나중에 표시 이름을 편집할 수 있습니다.
** * 페더레이션 그룹 *: 고유한 이름을 입력합니다. Active Directory의 경우 고유 이름은 속성과 연결된 `sAMAccountName` 이름입니다. OpenLDAP의 경우 고유 이름은 속성과 연결된 `uid` 이름입니다.


. Continue * 를 선택합니다.




== 그룹 권한을 관리합니다

그룹 권한은 테넌트 관리자 및 테넌트 관리 API에서 사용자가 수행할 수 있는 작업을 제어합니다.

.단계
. 액세스 모드 * 의 경우 다음 중 하나를 선택합니다.
+
** * 읽기-쓰기 * (기본값): 사용자는 테넌트 관리자에 로그인하여 테넌트 구성을 관리할 수 있습니다.
** * 읽기 전용 *: 사용자는 설정 및 기능만 볼 수 있습니다. 테넌트 관리자 또는 테넌트 관리 API에서 작업을 변경하거나 수행할 수 없습니다. 로컬 읽기 전용 사용자는 자신의 암호를 변경할 수 있습니다.
+

NOTE: 사용자가 여러 그룹에 속해 있고 모든 그룹이 읽기 전용으로 설정되어 있는 경우 사용자는 선택한 모든 설정 및 기능에 대해 읽기 전용 권한을 갖게 됩니다.



. 그룹 사용자가 테넌트 관리자 또는 테넌트 관리 API에 로그인해야 하는 경우 * Root access * 확인란을 선택합니다.
. Continue * 를 선택합니다.




== Swift 그룹 정책을 설정합니다

Swift 사용자는 컨테이너를 생성하고 오브젝트를 수집하려면 Swift REST API에 인증하는 관리자 권한이 필요합니다.

. 그룹 사용자가 Swift REST API를 사용하여 컨테이너 및 객체를 관리해야 하는 경우 * Swift administrator * 확인란을 선택합니다.
. 로컬 그룹을 만드는 경우 * 계속 * 을 선택합니다. 통합 그룹을 만드는 경우 * 그룹 생성 * 및 * 마침 * 을 선택합니다.




== 사용자 추가(로컬 그룹만 해당)

사용자를 추가하지 않고 그룹을 저장하거나 이미 존재하는 로컬 사용자를 선택적으로 추가할 수 있습니다.

.단계
. 필요에 따라 이 그룹에 대해 하나 이상의 로컬 사용자를 선택합니다.
+
아직 로컬 사용자를 만들지 않은 경우 사용자 페이지에서 이 그룹을 사용자에게 추가할 수 있습니다. 을 link:../tenant/managing-local-users.html["로컬 사용자를 관리합니다"]참조하십시오.

. Create group * 과 * Finish * 를 선택합니다.
+
생성한 그룹이 그룹 목록에 나타납니다.


