---
permalink: tenant/deleting-s3-bucket.html 
sidebar: sidebar 
keywords: how to delete S3 bucket 
summary: 테넌트 관리자를 사용하여 비어 있는 S3 버킷을 삭제할 수 있습니다. 
---
= S3 버킷을 삭제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 관리자를 사용하여 비어 있는 하나 이상의 S3 버킷을 삭제할 수 있습니다.

.시작하기 전에
* 를 사용하여 테넌트 관리자에 로그인되어 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 이 있는 사용자 그룹에 속해 link:tenant-management-permissions.html["모든 버킷 또는 루트 액세스 권한을 관리합니다"]있습니다. 이러한 권한은 그룹 또는 버킷 정책의 사용 권한 설정을 재정의합니다.
* 삭제할 버킷이 비어 있습니다. 삭제하려는 버킷이 _NOT_EMIVE인 경우link:../tenant/deleting-s3-bucket-objects.html["버킷에서 오브젝트를 삭제합니다"]


.이 작업에 대해
다음 지침은 Tenant Manager를 사용하여 S3 버킷을 삭제하는 방법을 설명합니다. 또는 를 사용하여 S3 버킷을 삭제할 수도 link:understanding-tenant-management-api.html["테넌트 관리 API"]link:../s3/operations-on-buckets.html["S3 REST API"]있습니다.

S3 버킷에 오브젝트, 비현재 오브젝트 버전이 포함되어 있거나 마커를 삭제할 수 없습니다. S3 버전 개체가 삭제되는 방법에 대한 자세한 내용은 을 참조하십시오link:../ilm/how-objects-are-deleted.html["오브젝트 삭제 방법"].

.단계
. 대시보드에서 * 버킷 보기 * 를 선택하거나 * 스토리지(S3) * > * 버킷 * 을 선택합니다.
+
Bucket 페이지가 나타나고 기존의 모든 S3 버킷을 표시합니다.

. 특정 버킷의 * 작업 * 메뉴 또는 세부 정보 페이지를 사용합니다.
+
[role="tabbed-block"]
====
.작업 메뉴
--
.. 삭제할 각 버킷의 확인란을 선택합니다.
.. Actions * > * Delete Bucket * 을 선택합니다.


--
.세부 정보 페이지
--
.. 버킷 이름을 선택하여 세부 정보를 표시합니다.
.. 버킷 삭제 * 를 선택합니다.


--
====
. 확인 대화 상자가 나타나면 * 예 * 를 선택합니다.
+
StorageGRID는 각 버킷이 비어 있음을 확인한 다음 각 버킷을 삭제합니다. 이 작업은 몇 분 정도 걸릴 수 있습니다.

+
버킷이 비어 있지 않으면 오류 메시지가 나타납니다. 버킷을 삭제하려면 먼저 해야 link:../tenant/deleting-s3-bucket-objects.html["버킷의 모든 오브젝트와 삭제 표식을 삭제합니다"]합니다.


