---
permalink: tenant/duplicating-group.html 
sidebar: sidebar 
keywords: how to duplicate tenant group 
summary: 기존 그룹을 복제하면 새 그룹을 더 빠르게 만들 수 있습니다. 
---
= 그룹이 중복되었습니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 그룹을 복제하면 새 그룹을 더 빠르게 만들 수 있습니다.

.시작하기 전에
* 를 사용하여 테넌트 관리자에 로그인되어 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 루트 액세스 권한이 있는 사용자 그룹에 속해 있습니다. 을 link:tenant-management-permissions.html["테넌트 관리 권한"]참조하십시오.


.단계
. *액세스 관리* > *그룹*을 선택합니다.
. 복제할 그룹의 확인란을 선택합니다.
. *그룹 복제*를 선택하세요.  그룹 생성에 대한 추가 세부 사항은 그룹 생성 지침을 참조하세요.link:creating-groups-for-s3-tenant.html["S3 테넌트"] .
. 로컬 그룹을 생성하려면 * Local group * 탭을 선택하고, 이전에 구성된 ID 소스에서 그룹을 가져오려면 * Federated group * 탭을 선택합니다.
+
StorageGRID 시스템에 SSO(Single Sign-On)가 활성화된 경우 로컬 그룹에 속한 사용자는 에 따라 클라이언트 응용 프로그램을 사용하여 테넌트의 리소스를 관리할 수 있지만 테넌트 관리자에 로그인할 수 link:tenant-management-permissions.html["그룹 권한"]없습니다.

. 그룹의 이름을 입력합니다.
+
** * 로컬 그룹 *: 표시 이름과 고유 이름을 모두 입력합니다. 나중에 표시 이름을 편집할 수 있습니다.
** * 페더레이션 그룹 *: 고유한 이름을 입력합니다. Active Directory의 경우 고유 이름은 속성과 연결된 `sAMAccountName` 이름입니다. OpenLDAP의 경우 고유 이름은 속성과 연결된 `uid` 이름입니다.


. Continue * 를 선택합니다.
. 필요에 따라 이 그룹에 대한 권한을 수정합니다.
. Continue * 를 선택합니다.
. 필요에 따라 S3 테넌트에 대한 그룹을 복제할 경우 * S3 정책 추가 * 라디오 버튼에서 다른 정책을 선택할 수도 있습니다. 사용자 지정 정책을 선택한 경우 필요에 따라 JSON 문자열을 업데이트합니다.
. Create group * 을 선택합니다.

