---
permalink: tenant/enabling-or-disabling-last-access-time-updates.html 
sidebar: sidebar 
keywords: how to enable or disable last access time updates 
summary: '그리드 관리자가 StorageGRID 시스템에 대한 정보 수명 주기 관리 \(ILM\) 규칙을 만들 때 원하는 경우 개체의 마지막 액세스 시간을 사용하여 해당 개체를 다른 스토리지 위치로 이동할지 여부를 결정하도록 지정할 수 있습니다. S3 테넌트를 사용하는 경우 S3 버킷의 오브젝트에 대한 마지막 액세스 시간 업데이트를 활성화하여 이러한 규칙을 활용할 수 있습니다.' 
---
= 마지막 액세스 시간 업데이트를 사용하거나 사용하지 않도록 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리자가 StorageGRID 시스템에 대한 ILM(정보 수명 주기 관리) 규칙을 만들 때 오브젝트의 마지막 액세스 시간을 사용하여 해당 오브젝트를 다른 스토리지 위치로 이동할지 여부를 결정하도록 선택적으로 지정할 수 있습니다. S3 테넌트를 사용하는 경우 S3 버킷의 오브젝트에 대한 마지막 액세스 시간 업데이트를 활성화하여 이러한 규칙을 활용할 수 있습니다.

이 지침은 고급 필터 또는 참조 시간으로 * 마지막 액세스 시간 * 옵션을 사용하는 ILM 규칙을 하나 이상 포함하는 StorageGRID 시스템에만 적용됩니다. StorageGRID 시스템에 이러한 규칙이 포함되어 있지 않으면 이 지침을 무시할 수 있습니다. 자세한 내용은 을 link:../ilm/using-last-access-time-in-ilm-rules.html["ILM 규칙에서 마지막 액세스 시간을 사용합니다"] 참조하십시오.

.시작하기 전에
* 를 사용하여 테넌트 관리자에 로그인되어 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 이 있는 사용자 그룹에 속해 link:tenant-management-permissions.html["모든 버킷 또는 루트 액세스 권한을 관리합니다"]있습니다. 이러한 권한은 그룹 또는 버킷 정책의 사용 권한 설정을 재정의합니다.


.이 작업에 대해
* 마지막 액세스 시간 * 은 ILM 규칙에 대한 * 참조 시간 * 배치 명령에 사용할 수 있는 옵션 중 하나입니다. 규칙의 참조 시간을 마지막 액세스 시간으로 설정하면 그리드 관리자는 해당 개체를 마지막으로 검색한 시기(읽기 또는 보기)에 따라 특정 저장소 위치에 개체가 배치되도록 지정할 수 있습니다.

예를 들어, 최근에 본 오브젝트를 더 빠른 스토리지에 유지하기 위해 그리드 관리자는 다음을 지정하는 ILM 규칙을 생성할 수 있습니다.

* 지난 달 동안 검색된 객체는 로컬 스토리지 노드에 남아 있어야 합니다.
* 지난 달에 검색되지 않은 객체는 오프 사이트 위치로 이동해야 합니다.


기본적으로 마지막 액세스 시간에 대한 업데이트는 사용되지 않습니다. StorageGRID 시스템에 * Last Access Time * 옵션을 사용하는 ILM 규칙이 포함되어 있고 이 옵션이 이 버킷의 오브젝트에 적용되도록 하려면 해당 규칙에 지정된 S3 버킷에 대한 마지막 액세스 시간에 대한 업데이트를 활성화해야 합니다.


CAUTION: 개체가 검색될 때 마지막 액세스 시간을 업데이트하면 특히 작은 개체의 StorageGRID 성능이 저하될 수 있습니다.

StorageGRID는 객체가 검색될 때마다 다음 추가 단계를 수행해야 하므로 마지막 액세스 시간 업데이트 시 성능 영향이 발생합니다.

* 객체를 새 타임스탬프로 업데이트합니다
* ILM 대기열에 개체를 추가하여 현재 ILM 규칙 및 정책에 대해 다시 평가할 수 있습니다


이 표에는 마지막 액세스 시간이 비활성화되거나 활성화될 때 버킷의 모든 오브젝트에 적용되는 동작이 요약되어 있습니다.

[cols="1a,1a,1a,1a,1a"]
|===


.2+| 요청 유형입니다 2+| 마지막 액세스 시간이 비활성화된 경우의 동작(기본값) 2+| 마지막 액세스 시간이 설정된 경우의 동작 


| 마지막 액세스 시간이 업데이트되었습니까? | ILM 평가 대기열에 객체가 추가되었습니까? | 마지막 액세스 시간이 업데이트되었습니까? | ILM 평가 대기열에 객체가 추가되었습니까? 


 a| 
HEAD 작업이 실행될 때 객체의 메타데이터를 검색하라는 요청
 a| 
아니요
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
개체, 해당 액세스 제어 목록 또는 해당 메타데이터를 검색하는 요청입니다
 a| 
아니요
 a| 
아니요
 a| 
예
 a| 
예



 a| 
개체의 메타데이터를 업데이트하도록 요청합니다
 a| 
예
 a| 
예
 a| 
예
 a| 
예



 a| 
개체 또는 개체 버전을 나열하는 요청입니다
 a| 
아니요
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
한 버킷에서 다른 버킷으로 오브젝트 복사 요청
 a| 
* 아니요, 소스 복제본입니다
* 예, 대상 복사본에 대해 입니다

 a| 
* 아니요, 소스 복제본입니다
* 예, 대상 복사본에 대해 입니다

 a| 
* 예. 소스 복제본에 대해 가능합니다
* 예, 대상 복사본에 대해 입니다

 a| 
* 예. 소스 복제본에 대해 가능합니다
* 예, 대상 복사본에 대해 입니다




 a| 
여러 부분 업로드를 완료하도록 요청합니다
 a| 
예. 조립된 개체에 대해 가능합니다
 a| 
예. 조립된 개체에 대해 가능합니다
 a| 
예. 조립된 개체에 대해 가능합니다
 a| 
예. 조립된 개체에 대해 가능합니다

|===
.단계
. 대시보드에서 * 버킷 보기 * 를 선택하거나 * 스토리지(S3) * > * 버킷 * 을 선택합니다.
. 테이블에서 버킷 이름을 선택합니다.
+
버킷 세부 정보 페이지가 나타납니다.

. Bucket options * 탭에서 * Last access time updates * 아코디언을 선택합니다.
. 마지막 액세스 시간 업데이트를 사용하거나 사용하지 않도록 설정합니다.
. 변경 내용 저장 * 을 선택합니다.

