---
permalink: tenant/enable-cross-origin-resource-sharing-for-management-interface.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors, management, api, domain 
summary: '다른 도메인에 대한 관리 API를 사용하여 StorageGRID의 데이터에 액세스할 수 있도록 하려면 StorageGRID에 대한 관리 API 요청에 대해 CORS(Cross-Origin Resource Sharing)를 사용하도록 설정할 수 있습니다.' 
---
= 관리 인터페이스에 대해 StorageGRID CORS를 사용하도록 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다른 도메인에 대한 관리 API를 사용하여 StorageGRID의 데이터에 액세스할 수 있도록 하려면 StorageGRID에 대한 관리 API 요청에 대해 CORS(Cross-Origin Resource Sharing)를 사용하도록 설정할 수 있습니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 는 link:tenant-management-permissions.html["루트 액세스 권한"]모든 CORS 구성 요청에 대한 액세스를 제공합니다.


.이 작업에 대해
CORS는 한 도메인의 클라이언트 웹 응용 프로그램이 다른 도메인의 리소스에 액세스할 수 있도록 하는 보안 메커니즘입니다. 예를 들어 도메인에서 StorageGRID에 대한 모니터링 대시보드를 구축한다고 `\http://www.example.com` 가정합니다. StorageGRID에서 CORS를 활성화하고 `\http://www.example.com` "그리드 관리자"를 활성화하면 StorageGRID 도메인이 의 그리드 관리 API 요청에 `\http://www.example.com` 응답합니다.

또는 `multipart/formdata` 요청이 `Content-Type` 있는 관리 API(mgmt-API) `application/json` 요청은 CORS에 대해 지원됩니다.

.단계
. StorageGRID 구성 페이지의 * 네트워크 * 에서 * 관리 인터페이스 CORS 설정 * 을 선택합니다.
. Grid Manager *, * Tenant Manager * 또는 두 옵션을 모두 선택합니다.
+
** * Grid Manager *: 도메인 간 Grid Management API 요청에 대한 CORS를 활성화합니다.
** * Tenant Manager *: 도메인 간 Tenant Management API 요청에 대해 CORS를 활성화합니다.


. 도메인 * 필드에 다른 도메인의 URL을 입력합니다.
+
둘 이상의 도메인에 대해 StorageGRID에서 CORS를 활성화하려면 * 다른 도메인 추가 * 를 선택합니다.

. 저장 * 을 선택합니다.


.관련 정보
link:configuring-cross-origin-resource-sharing-for-buckets-and-objects.html["버킷 및 객체에 대해 StorageGRID CORS를 구성합니다"]
