---
permalink: tenant/ilm-policy-tags.html 
sidebar: sidebar 
keywords: how to assign ilm policy tag to bucket 
summary: 오브젝트 스토리지 요구사항에 따라 버킷에 할당할 ILM 정책 태그를 선택합니다. 
---
= 버킷에 ILM 정책 태그를 적용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
오브젝트 스토리지 요구사항에 따라 버킷에 적용할 ILM 정책 태그를 선택합니다.

ILM 정책은 오브젝트 데이터의 저장 위치와 일정 기간 후에 삭제되는지 여부를 제어합니다. 그리드 관리자는 ILM 정책을 만들고 활성 정책을 여러 개 사용할 때 ILM 정책 태그에 할당합니다.


NOTE: 버킷의 정책 태그를 자주 재할당하지 마십시오. 그렇지 않으면 성능 문제가 발생할 수 있습니다.

.시작하기 전에
* 를 사용하여 테넌트 관리자에 로그인되어 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 이 있는 사용자 그룹에 속해 link:tenant-management-permissions.html["루트 액세스, 모든 버킷 관리 또는 모든 버킷 보기 권한"]있습니다. 이러한 권한은 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.


.단계
. 대시보드에서 * 버킷 보기 * 를 선택하거나 * 스토리지(S3) * > * 버킷 * 을 선택합니다.
+
Bucket 페이지가 나타납니다. 필요에 따라 모든 열을 기준으로 정보를 정렬하거나 목록 앞뒤에 페이지를 표시할 수 있습니다.

. ILM 정책 태그를 할당할 버킷의 이름을 선택합니다.
+
이미 태그가 할당된 버킷의 ILM 정책 태그 할당을 변경할 수도 있습니다.

+

NOTE: 표시된 개체 수와 사용된 공간 값은 추정값입니다. 이러한 추정치는 베스트 타이밍, 네트워크 연결 및 노드 상태의 영향을 받습니다. 버킷에 버전 관리가 활성화된 경우 삭제된 개체 버전은 오브젝트 수에 포함됩니다.

. Bucket options 탭에서 ILM 정책 태그 아코디언을 확장합니다. 이 아코디언은 그리드 관리자가 사용자 지정 정책 태그를 사용하도록 설정한 경우에만 나타납니다.
. 각 정책 태그에 대한 설명을 읽고 버킷에 적용할 태그를 결정합니다.
+

CAUTION: 버킷의 ILM 정책 태그를 변경하면 버킷의 모든 오브젝트에 대한 ILM 재평가가 트리거됩니다. 새 정책에 따라 제한된 시간 동안 오브젝트를 유지하는 경우 이전 오브젝트는 삭제됩니다.

. 버킷에 할당할 태그의 라디오 버튼을 선택합니다.
. 변경 내용 저장 * 을 선택합니다. 새 S3 버킷 태그는 키와 ILM 정책 태그 이름의 값을 사용하여 버킷에 `NTAP-SG-ILM-BUCKET-TAG` 설정됩니다.
+

CAUTION: S3 애플리케이션이 실수로 새 버킷 태그를 무시하거나 삭제하지 않도록 하십시오. 새 TagSet를 버킷에 적용할 때 이 태그를 생략하면 버킷의 객체가 기본 ILM 정책에 대해 평가되는 것으로 되돌아갑니다.

+

CAUTION: ILM 정책 태그가 검증된 테넌트 관리자 또는 테넌트 관리자 API만 사용하여 ILM 정책 태그를 설정하고 수정합니다. S3 PutBucketTagging API 또는 S3 DeleteBucketTagging API를 사용하여 ILM 정책 태그를 수정하지 마십시오 `NTAP-SG-ILM-BUCKET-TAG`.

+

NOTE: 버킷에 할당된 정책 태그를 변경하면 새로운 ILM 정책을 사용하여 오브젝트를 재평가하는 동안 성능에 일시적으로 영향을 미칩니다.


