---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: '테넌트 계정을 사용하면 S3(Simple Storage Service) REST API를 사용하여 StorageGRID 시스템에 객체를 저장하고 검색할 수 있습니다.' 
---
= 테넌트 계정을 사용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 계정을 사용하면 S3(Simple Storage Service) REST API를 사용하여 StorageGRID 시스템에 오브젝트를 저장하고 검색할 수 있습니다.



== 테넌트 계정이란 무엇입니까?

각 테넌트 계정에는 고유한 페더레이션 또는 로컬 그룹, 사용자, S3 버킷 및 오브젝트가 있습니다.

테넌트 계정은 저장된 객체를 다른 엔터티로 분리하는 데 사용할 수 있습니다. 예를 들어, 다음과 같은 사용 사례에서 여러 테넌트 계정을 사용할 수 있습니다.

* * 기업 활용 사례: * 기업 내에서 StorageGRID 시스템을 사용하는 경우 그리드의 객체 스토리지를 조직의 여러 부서에서 분리할 수 있습니다. 예를 들어 마케팅 부서, 고객 지원 부서, 인사 부서 등의 테넌트 계정이 있을 수 있습니다.
+

NOTE: S3 클라이언트 프로토콜을 사용하면 S3 버킷과 버킷 정책을 사용하여 기업 내 부서 간에 객체를 분리할 수도 있습니다.  별도의 테넌트 계정을 만들 필요가 없습니다.  구현에 대한 지침을 참조하세요.link:../s3/use-access-policies.html["S3 버킷 및 버킷 정책"] 자세한 내용은.

* * 서비스 공급자 사용 사례: * 서비스 공급자가 StorageGRID 시스템을 사용 중인 경우, 스토리지를 임대하는 다른 엔터티로 그리드의 개체 스토리지를 분리할 수 있습니다. 예를 들어 회사 A, 회사 B, 회사 C 등에 대한 테넌트 계정이 있을 수 있습니다.




== 테넌트 계정을 생성하는 방법

테넌트 계정은 에 의해 link:../admin/managing-tenants.html["그리드 관리자를 사용하는 StorageGRID 그리드 관리자"]생성됩니다. 테넌트 계정을 생성할 때 그리드 관리자는 다음을 지정합니다.

* 테넌트 이름, 클라이언트 유형(S3) 및 선택적 스토리지 할당량을 포함한 기본 정보입니다.
* 테넌트 계정에서 S3 플랫폼 서비스를 사용할 수 있는지 여부, 해당 ID 소스를 구성할 수 있는지 여부, S3 Select를 사용할 것인지, 그리드 페더레이션 연결을 사용할 수 있는지 여부 등의 테넌트 계정에 대한 사용 권한
* StorageGRID 시스템에서 로컬 그룹 및 사용자, ID 페더레이션 또는 SSO(Single Sign-On)를 사용하는지 여부에 따라 테넌트의 초기 루트 액세스입니다.


또한, S3 테넌트 계정이 규정 요구 사항을 준수해야 하는 경우 그리드 관리자는 StorageGRID 시스템에 대해 S3 오브젝트 잠금 설정을 활성화할 수 있습니다. S3 오브젝트 잠금이 활성화된 경우 모든 S3 테넌트 계정에서 호환 버킷을 생성하고 관리할 수 있습니다.



=== S3 테넌트를 구성합니다

그런 다음 link:../admin/creating-tenant-account.html["S3 테넌트 계정이 생성됩니다"]테넌트 관리자에 액세스하여 다음과 같은 작업을 수행할 수 있습니다.

* ID 페더레이션 설정(ID 소스가 그리드와 공유되지 않는 경우)
* 그룹 및 사용자를 관리합니다
* 계정 클론 및 교차 그리드 복제에 그리드 페더레이션을 사용합니다
* S3 액세스 키를 관리합니다
* S3 버킷을 생성하고 관리합니다
* S3 플랫폼 서비스 사용
* S3 Select를 사용합니다
* 스토리지 사용량을 모니터링합니다



TIP: 테넌트 관리자로 S3 버킷을 생성하고 관리할 수 있지만, 또는 link:use-s3-console.html["S3 콘솔"]을 사용하여 link:../s3/index.html["S3 클라이언트"]오브젝트를 수집 및 관리해야 합니다.
