---
permalink: tenant/manage-branch-buckets.html 
sidebar: sidebar 
keywords: how to create branch bucket 
summary: 테넌트 관리자를 사용하여 지점 버킷에 대한 세부 정보를 만들고 확인하세요. 
---
= 지점 버킷 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 관리자를 사용하여 지점 버킷에 대한 세부 정보를 만들고 확인하세요.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 귀하는 루트 액세스 권한이 있는 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["모든 버킷 사용 권한을 관리합니다"] .  이러한 권한은 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.
* 브랜치를 생성하려는 기본 버킷에는 다음이 있습니다.link:../tenant/changing-bucket-versioning.html["버전 관리 활성화됨"] .
* 당신은 기본 버킷의 소유자입니다.


.이 작업에 대해
분기 버킷에 대한 다음 정보를 참고하세요.

* 버킷 또는 객체의 S3 객체 잠금 속성을 설정하는 권한은 다음을 통해 부여될 수 있습니다.link:../s3/use-access-policies.html["버킷 정책 또는 그룹 정책"] .
* 기본 버킷에서 버전 관리를 중단하면 기본 버킷의 내용이 더 이상 해당 분기 버킷에 표시되지 않습니다.



CAUTION: 브랜치 버킷을 구성하고 생성한 후에는 구성을 변경할 수 없습니다.



== 브랜치 버킷 생성

.단계
. 대시보드에서 * 버킷 보기 * 를 선택하거나 * 스토리지(S3) * > * 버킷 * 을 선택합니다.
. 브랜치를 만들려는 버킷("기본 버킷")을 선택합니다.
. 버킷 세부 정보 페이지에서 *지점* > *지점 버킷 만들기*를 선택합니다.
+
기본 버킷의 버전 관리가 활성화되어 있지 않으면 *브랜치 버킷 만들기* 버튼이 비활성화됩니다.





== 세부 정보를 입력합니다

.단계
. 지점 버킷에 대한 세부 정보를 입력하세요.
+
[cols="1a,3a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
지점 버킷 이름
 a| 
다음 규칙을 준수하는 브랜치 버킷의 이름:

** 각 StorageGRID 시스템에서 고유해야 합니다(테넌트 계정에서만 고유한 것은 아님).
** DNS를 준수해야 합니다.
** 3자 이상 63자 이하여야 합니다.
** 각 레이블은 소문자 또는 숫자로 시작하고 끝나야 하며 소문자, 숫자 및 하이픈만 사용할 수 있습니다.
** 가상 호스팅 스타일 요청에는 기간을 포함할 수 없습니다. 마침표는 서버 와일드카드 인증서 확인에 문제를 일으킬 수 있습니다.


자세한 내용은 를 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["버킷 명명 규칙에 대한 AWS(Amazon Web Services) 문서입니다"^]참조하십시오.

*참고*: 브랜치 버킷을 만든 후에는 이름을 변경할 수 없습니다.



 a| 
지역(지점 버킷에 대해 수정할 수 없음)
 a| 
지점 버킷의 지역입니다.

지점 버킷의 지역은 기본 버킷의 지역과 일치해야 하므로 이 필드는 지점 버킷에 대해 비활성화됩니다.



 a| 
시간 전에
 a| 
기본 버킷에서 생성된 객체 버전을 브랜치 버킷에서 액세스할 수 있게 되는 마감 시간입니다.  브랜치 버킷은 Before 시간보다 이전에 생성된 객체 버전에 대한 액세스를 제공합니다.

시간 이전에는 이미 지나간 날짜와 시간이 있어야 합니다.  미래의 날짜일 수 없습니다.



 a| 
브랜치 버킷 유형
 a| 
** *읽기-쓰기*: 브랜치 버킷에서 개체 또는 개체 버전을 추가하거나 삭제할 수 있습니다.
** *읽기 전용*: 브랜치 버킷의 객체를 수정할 수 없습니다.


*참고*: 브랜치 버킷이 비어 있는 경우에만 브랜치 버킷 유형을 읽기 전용으로 설정할 수 있습니다.  기존 브랜치 버킷의 유형이 읽기-쓰기로 설정되어 있고 해당 버킷에 쓰지 않은 경우 유형을 읽기 전용으로 변경할 수 있습니다.

|===
. Continue * 를 선택합니다.




== 개체 설정 관리(선택 사항)

브랜치 버킷의 개체 설정은 기본 버킷의 개체 버전에 영향을 미치지 않습니다.

.단계
. 글로벌 S3 개체 잠금 설정이 활성화된 경우 선택적으로 브랜치 버킷에 대한 S3 개체 잠금을 활성화합니다.  S3 객체 잠금을 활성화하려면 브랜치 버킷이 읽기-쓰기 버킷이어야 합니다.
+
예를 들어 특정 규정 요구 사항을 충족하기 위해 객체를 고정된 기간 동안 보관해야 하는 경우에만 지점 버킷에 대해 S3 객체 잠금을 활성화합니다.  S3 객체 잠금은 특정 기간 또는 무기한으로 객체가 삭제되거나 덮어쓰이는 것을 방지하는 데 도움이 되는 영구 설정입니다.

+

CAUTION: 버킷에 대해 S3 개체 잠금 설정을 활성화한 후에는 비활성화할 수 없습니다.  올바른 권한이 있는 사람은 누구나 변경할 수 없는 객체를 브랜치 버킷에 추가할 수 있습니다.  이러한 객체나 브랜치 버킷 자체를 삭제할 수 없을 수도 있습니다.

. *S3 객체 잠금 활성화*를 선택한 경우, 선택적으로 브랜치 버킷에 대해 *기본 보존*을 활성화합니다.
+

NOTE: 그리드 관리자가 사용자에게 권한을 부여해야 link:../tenant/using-s3-object-lock.html["S3 오브젝트 잠금의 특정 기능 사용"]합니다.

+
*기본 보존*을 활성화하면 브랜치 버킷에 추가된 새 개체는 삭제되거나 덮어쓰이지 않도록 자동으로 보호됩니다.  *기본 보존* 설정은 자체 보존 기간이 있는 개체에는 적용되지 않습니다.

+
.. *기본 보존*이 활성화된 경우 브랜치 버킷에 대한 *기본 보존 모드*를 지정합니다.
+
[cols="1a,2a"]
|===
| 기본 보존 모드 | 설명 


 a| 
기대치를 설정합니다
 a| 
***  있는 사용자는 `s3:BypassGovernanceRetention`권한이 요청 헤더를 사용하여 보존 설정을 무시할 수 `x-amz-bypass-governance-retention: true` 있습니다.
*** 이러한 사용자는 보존 기한이 되기 전에 개체 버전을 삭제할 수 있습니다.
*** 이러한 사용자는 개체의 보존 기간(Retain-until-date)을 증가, 감소 또는 제거할 수 있습니다.




 a| 
규정 준수
 a| 
*** 보존 기한 에 도달할 때까지 개체를 삭제할 수 없습니다.
*** 오브젝트의 보존 기한 을 늘릴 수 있지만 줄일 수는 없습니다.
*** 개체의 보존 기한 은 해당 날짜에 도달할 때까지 제거할 수 없습니다.


* 참고 *: 그리드 관리자가 규정 준수 모드를 사용할 수 있도록 허용해야 합니다.

|===
.. *기본 보존*이 활성화된 경우 지점 버킷의 *기본 보존 기간*을 지정합니다.
+
*기본 보존 기간*은 브랜치 버킷에 추가된 새 객체를 수집한 시점부터 보존해야 하는 기간을 나타냅니다.  그리드 관리자가 설정한 테넌트의 최대 보존 기간보다 작거나 같은 값을 지정합니다.

+
그리드 관리자가 테넌트를 생성할 때 1일에서 100년 사이의 값을 지정할 수 있는 _MAXIMUM_RETENTION 기간이 설정됩니다. _default_retention 기간을 설정하면 최대 보존 기간에 설정된 값을 초과할 수 없습니다. 필요한 경우 그리드 관리자에게 최대 보존 기간을 늘리거나 줄이도록 요청하십시오.



. 선택적으로 *용량 제한 활성화*를 선택합니다.
+
용량 한도는 지점 버킷에 사용할 수 있는 최대 용량입니다.  이 값은 물리적인 양(디스크 크기)이 아닌 논리적인 양(객체 크기)을 나타냅니다.

+
제한을 설정하지 않으면 지점 버킷의 용량은 무제한입니다. . link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["용량 제한 사용량"] 자세한 내용은.

+

NOTE: 이 설정은 브랜치 버킷에 직접 수집된 객체에만 적용되며, 브랜치 버킷을 통해 기본 버킷에서 볼 수 있는 객체에는 적용되지 않습니다.

. 선택적으로 *객체 개수 제한 사용*을 선택합니다.
+
객체 수 제한은 브랜치 버킷이 포함할 수 있는 최대 객체 수입니다.  이 값은 논리적인 양(객체 수)을 나타냅니다.  제한을 설정하지 않으면 객체 개수는 무제한입니다.

+

NOTE: 이 설정은 브랜치 버킷에 직접 수집된 객체에만 적용되며, 브랜치 버킷을 통해 기본 버킷에서 볼 수 있는 객체에는 적용되지 않습니다.

. Create bucket * 을 선택합니다.
+
브랜치 버킷이 생성되어 버킷 페이지의 테이블에 추가됩니다.

. 선택적으로 *버킷 세부 정보 페이지로 이동*을 선택하세요.link:viewing-s3-bucket-details.html["지점 버킷 세부 정보 보기"] 추가 구성을 수행합니다.
+
버킷 세부 정보 페이지에서는 읽기 전용 버킷의 개체 수정과 관련된 일부 구성 옵션이 비활성화됩니다.


