---
permalink: tenant/manage-branch-buckets.html 
sidebar: sidebar 
keywords: how to create branch bucket 
summary: 버킷을 사용하면 버킷에 있는 물체가 특정 시점에 존재했던 것처럼 버켓에 있는 물체에 액세스할 수 있습니다. 테넌트 관리자를 사용하여 분기 버킷을 생성하고 봅니다. 
---
= 분기 버킷을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
버킷을 사용하면 버킷에 있는 물체가 특정 시점에 존재했던 것처럼 버켓에 있는 물체에 액세스할 수 있습니다. 테넌트 관리자를 사용하여 분기 버킷을 생성하고 봅니다.

지점 버킷은 보호된 데이터에 대한 액세스를 제공하지만 백업 역할을 하지 않습니다. 데이터를 계속 보호하려면 기본 버킷에서 다음 기능을 사용하십시오.

* link:../tenant/using-s3-object-lock.html["S3 오브젝트 잠금"]
* link:../admin/grid-federation-what-is-cross-grid-replication.html["교차 그리드 복제"] 기본 버킷용
* link:../tenant/manage-bucket-policy.html["버킷 정책"] 이전 객체 버전을 정리하는 버전 버킷을 위한 것입니다


.이 작업에 대해
기존 버킷에서 분기 버킷을 만듭니다. 분기 버킷을 생성한 후에는 이 버킷을 생성한 원래 버킷을 기본 버킷이라고 합니다. 또한 다른 분기 버킷에서 분기 버킷을 생성할 수 있습니다. 기본 버킷에서 작업을 수행할 때, 분기 버킷의 결과는 사용자가 생성한 분기 버킷의 유형과 작업에 따라 달라집니다.

분기 버킷을 사용하여 손상이 발생하기 전의 지점에서 분기 버킷을 만든 다음 손상된 오브젝트가 들어 있는 기본 버킷 대신 애플리케이션을 분기 버킷으로 가리키면 손상된 오브젝트를 제거할 수 있습니다.


CAUTION: 지점 버킷은 백업 역할을 하지 않지만 보호된 데이터에 대한 액세스를 제공합니다. 또는 link:../admin/grid-federation-what-is-cross-grid-replication.html["교차 그리드 복제"]를 계속 사용해야 데이터를 보호할 수 link:../ilm/managing-objects-with-s3-object-lock.html["S3 오브젝트 잠금"]있습니다.

분기 버킷에는 교차 그리드 복제가 지원되지 않습니다.

.시작하기 전에
* 를 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 루트 액세스 또는 모든 버킷을 관리하는 사용자 그룹에 속해 link:tenant-management-permissions.html["권한"]있습니다. 이러한 권한은 그룹 또는 버킷 정책의 사용 권한 설정을 재정의합니다.
* 분기를 만들려는 기본 버킷은 가 있습니다link:../tenant/changing-bucket-versioning.html["버전 관리를 사용하도록 설정되었습니다"].
* 당신은 기본 버킷을 소유합니다.
+

NOTE: 버킷 또는 오브젝트의 S3 오브젝트 잠금 속성을 설정하거나 수정할 수 있는 권한은 에서 부여할 수 link:../s3/bucket-and-group-access-policies.html["버킷 정책 또는 그룹 정책"]있습니다.





== 분기 버킷을 생성합니다

.단계
. 대시보드에서 * 버킷 보기 * 를 선택하거나 * 스토리지(S3) * > * 버킷 * 을 선택합니다.
. 분기를 생성할 버킷("기본 버킷")을 선택합니다.
. 버킷 세부 정보 페이지에서 * branks * > * Create branch bucket * 을 선택합니다.
+
기본 버킷에 버전 관리가 활성화되어 있지 않으면 * 분기 버킷 생성 * 버튼이 비활성화됩니다.





== 세부 정보를 입력합니다

.단계
. 분기 버킷에 대한 세부 정보를 입력합니다.
+
[cols="1a,3a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
분기 버킷 이름입니다
 a| 
다음 규칙을 준수하는 분기 버킷의 이름입니다.

** 각 StorageGRID 시스템에서 고유해야 합니다(테넌트 계정에서만 고유한 것은 아님).
** DNS를 준수해야 합니다.
** 3자 이상 63자 이하여야 합니다.
** 각 레이블은 소문자 또는 숫자로 시작하고 끝나야 하며 소문자, 숫자 및 하이픈만 사용할 수 있습니다.
** 가상 호스팅 스타일 요청에는 기간을 포함할 수 없습니다. 마침표는 서버 와일드카드 인증서 확인에 문제를 일으킬 수 있습니다.


자세한 내용은 를 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["버킷 명명 규칙에 대한 AWS(Amazon Web Services) 문서입니다"^]참조하십시오.

*참고*: 분기 버킷을 만든 후에는 이름을 변경할 수 없습니다.



 a| 
지역(분기 버킷에 대해 수정할 수 없음)
 a| 
가지 버켓의 지역.

분기 버킷의 영역은 기본 버킷의 영역과 일치해야 하므로 분기 버킷에 대해 이 필드가 비활성화됩니다.



 a| 
있습니다
 a| 
기본 버킷에 생성된 객체 버전의 마감 시간을 분기 버킷에서 액세스할 수 있습니다. 분기 버킷은 이전 시간보다 이전에 생성된 오브젝트 버전에 대한 액세스를 제공합니다.



 a| 
분기 버킷 유형
 a| 
** * 읽기-쓰기 * : 분기 버킷에서 오브젝트 또는 오브젝트 버전을 추가하거나 삭제할 수 있습니다.
** * 읽기 전용 * : 분기 버킷에서 오브젝트를 수정할 수 없습니다.


|===
. Continue * 를 선택합니다.




== 설정을 관리합니다

분기 버킷의 설정은 기본 버킷의 오브젝트 버전에 영향을 주지 않습니다.

.단계
. 글로벌 S3 오브젝트 잠금 설정이 활성화된 경우 필요에 따라 지점 버킷에 대해 S3 오브젝트 잠금을 설정합니다. S3 오브젝트 잠금을 활성화하려면 분기 버킷이 읽기-쓰기 버킷이어야 합니다.
+
예를 들어, 특정 규정 요구사항을 충족하기 위해 오브젝트를 일정 시간 동안 유지해야 하는 경우에만 지점 버킷에 대해 S3 오브젝트 잠금을 설정합니다. S3 오브젝트 잠금은 고정된 시간 또는 무기한으로 오브젝트를 삭제 또는 덮어쓰는 것을 방지하는 영구 설정입니다.

+

CAUTION: 버킷에 대해 S3 오브젝트 잠금 설정이 활성화된 후에는 비활성화할 수 없습니다. 올바른 권한을 가진 사람은 변경할 수 없는 객체를 분기 버킷에 추가할 수 있습니다. 이 오브젝트나 분기 버켓 자체를 삭제하지 못할 수 있습니다.

. S3 오브젝트 잠금 활성화 * 를 선택한 경우, 분기 버킷에 대해 * 기본 보존 * 을 선택적으로 활성화합니다.
+

NOTE: 그리드 관리자가 사용자에게 권한을 부여해야 link:../tenant/using-s3-object-lock.html["S3 오브젝트 잠금의 특정 기능 사용"]합니다.

+
기본 보존 * 이 활성화되면 분기 버킷에 추가된 새 객체가 삭제되거나 덮어쓰지 않도록 자동으로 보호됩니다. 기본 보존 * 설정은 고유한 보존 기간이 있는 개체에는 적용되지 않습니다.

+
.. 기본 보존 * 이 활성화된 경우 분기 버킷에 * 기본 보존 모드 * 를 지정합니다.
+
[cols="1a,2a"]
|===
| 기본 보존 모드 | 설명 


 a| 
기대치를 설정합니다
 a| 
***  있는 사용자는 `s3:BypassGovernanceRetention`권한이 요청 헤더를 사용하여 보존 설정을 무시할 수 `x-amz-bypass-governance-retention: true` 있습니다.
*** 이러한 사용자는 보존 기한이 되기 전에 개체 버전을 삭제할 수 있습니다.
*** 이러한 사용자는 개체의 보존 기간(Retain-until-date)을 증가, 감소 또는 제거할 수 있습니다.




 a| 
규정 준수
 a| 
*** 보존 기한 에 도달할 때까지 개체를 삭제할 수 없습니다.
*** 오브젝트의 보존 기한 을 늘릴 수 있지만 줄일 수는 없습니다.
*** 개체의 보존 기한 은 해당 날짜에 도달할 때까지 제거할 수 없습니다.


* 참고 *: 그리드 관리자가 규정 준수 모드를 사용할 수 있도록 허용해야 합니다.

|===
.. 기본 보존 * 이 활성화된 경우 분기 버킷에 * 기본 보존 기간 * 을 지정합니다.
+
기본 보존 기간 * 은 분기 버킷에 추가된 새 객체가 수집된 시점부터 보존되어야 하는 기간을 나타냅니다. 그리드 관리자가 설정한 테넌트의 최대 보존 기간보다 작거나 같은 값을 지정하십시오.

+
그리드 관리자가 테넌트를 생성할 때 1일에서 100년 사이의 값을 지정할 수 있는 _MAXIMUM_RETENTION 기간이 설정됩니다. _default_retention 기간을 설정하면 최대 보존 기간에 설정된 값을 초과할 수 없습니다. 필요한 경우 그리드 관리자에게 최대 보존 기간을 늘리거나 줄이도록 요청하십시오.



. [[capacity-limit]](용량 제한 활성화) 필요에 따라 * Enable capacity limit * 를 선택합니다.
+
용량 제한은 분기 버킷에 사용할 수 있는 최대 용량입니다. 이 값은 물리 크기(디스크의 크기)가 아닌 논리 양(개체 크기)을 나타냅니다.

+
제한을 설정하지 않으면 분기 버킷의 용량은 무제한입니다. 자세한 내용은 을 link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["용량 제한 사용량"] 참조하십시오.

+

NOTE: 이 설정은 분기 버킷에 직접 수집된 오브젝트에만 적용되며, 기본 버킷에서 분기 버킷을 통해 볼 수 있는 오브젝트에는 적용되지 않습니다.

. 필요에 따라 * 개체 수 제한 활성화 * 를 선택합니다.
+
객체 수 제한은 분기 버킷이 포함할 수 있는 최대 객체 수입니다. 이 값은 논리적 양(객체 수)을 나타냅니다. 제한을 설정하지 않으면 개체 수는 무제한입니다.

+

NOTE: 이 설정은 분기 버킷에 직접 수집된 오브젝트에만 적용되며, 기본 버킷에서 분기 버킷을 통해 볼 수 있는 오브젝트에는 적용되지 않습니다.

. Create bucket * 을 선택합니다.
+
분기 버킷이 생성되어 버킷 페이지의 테이블에 추가됩니다.

. 필요에 따라 * 버킷 세부 정보 페이지로 이동 * 을 선택하여 link:viewing-s3-bucket-details.html["분기 버킷 세부 정보를 봅니다"]추가 구성을 수행합니다.
+
Bucket details(버킷 세부 정보) 페이지에서 읽기 전용 버킷에 대해 객체 수정과 관련된 일부 구성 옵션이 비활성화됩니다.


