---
permalink: tenant/signing-in-to-tenant-manager.html 
sidebar: sidebar 
keywords: how to sign in to tenant manager 
summary: 지원되는 웹 브라우저의 주소 표시줄에 테넌트에 대한 URL을 입력하여 테넌트 관리자에 액세스합니다. 
---
= 테넌트 관리자에 로그인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
의 주소 표시줄에 테넌트의 URL을 입력하여 테넌트 관리자에 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]액세스합니다.

.시작하기 전에
* 로그인 자격 증명이 있습니다.
* 그리드 관리자가 제공한 테넌트 관리자 액세스 URL이 있습니다. URL은 다음 예 중 하나로 표시됩니다.
+
`\https://FQDN_or_Admin_Node_IP/`

+
`\https://FQDN_or_Admin_Node_IP:port/`

+
`\https://FQDN_or_Admin_Node_IP/?accountId=20-digit-account-id`

+
`\https://FQDN_or_Admin_Node_IP:port/?accountId=20-digit-account-id`

+
URL에는 항상 FQDN(정규화된 도메인 이름), 관리 노드의 IP 주소 또는 관리 노드의 HA 그룹의 가상 IP 주소가 포함됩니다. 포트 번호, 20자리 테넌트 계정 ID 또는 둘 다 포함될 수도 있습니다.

* URL에 테넌트의 20자리 계정 ID가 포함되어 있지 않은 경우 이 계정 ID가 있는 것입니다.
* 을 사용하고 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 쿠키는 웹 브라우저에서 활성화됩니다.
* 가 있는 사용자 그룹에 속해 link:tenant-management-permissions.html["특정 액세스 권한"]있습니다.


.단계
. 를 실행합니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
. 브라우저의 주소 표시줄에 Tenant Manager에 액세스하기 위한 URL을 입력합니다.
. 보안 경고 메시지가 나타나면 브라우저의 설치 마법사를 사용하여 인증서를 설치합니다.
. 테넌트 관리자에 로그인합니다.
+
표시되는 로그인 화면은 입력한 URL과 StorageGRID에 대해 SSO(Single Sign-On)가 구성되었는지 여부에 따라 달라집니다.

+
[role="tabbed-block"]
====
.SSO를 사용하지 않습니다
--
StorageGRID에서 SSO를 사용하지 않는 경우 다음 화면 중 하나가 나타납니다.

** Grid Manager 로그인 페이지 Tenant Sign-In * 링크를 선택합니다.
** 테넌트 관리자 로그인 페이지.  *계정* 필드는 이미 작성되었을 수 있습니다.
+
... 테넌트의 20자리 계정 ID가 표시되지 않으면 최근 계정 목록에 테넌트 계정 이름이 나타날 경우 해당 계정 이름을 선택하거나 계정 ID를 입력합니다.
... 사용자 이름과 암호를 입력합니다.
... 로그인 * 을 선택합니다.
+
Tenant Manager 대시보드가 나타납니다.

... 다른 사람으로부터 초기 암호를 받은 경우 *_username_ * > * 암호 변경 * 을 선택하여 계정을 보호하십시오.




--
.SSO 사용
--
StorageGRID에서 SSO를 사용하는 경우 다음 화면 중 하나가 나타납니다.

** 귀하의 조직의 SSO 페이지입니다.
+
표준 SSO 자격 증명을 입력하고 * 로그인 * 을 선택합니다.

** Tenant Manager SSO 로그인 페이지.
+
... 테넌트의 20자리 계정 ID가 표시되지 않으면 최근 계정 목록에 테넌트 계정 이름이 나타날 경우 해당 계정 이름을 선택하거나 계정 ID를 입력합니다.
... 로그인 * 을 선택합니다.
... 조직의 SSO 로그인 페이지에서 표준 SSO 자격 증명을 사용하여 로그인합니다.
+
Tenant Manager 대시보드가 나타납니다.





--
====

