---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: 테넌트 그룹을 생성하기 전에 해당 그룹에 할당할 권한을 고려하십시오. 테넌트 관리 권한은 사용자가 테넌트 관리자 또는 테넌트 관리 API를 사용하여 수행할 수 있는 작업을 결정합니다. 사용자는 하나 이상의 그룹에 속할 수 있습니다. 사용자가 여러 그룹에 속한 경우 권한은 누적됩니다. 
---
= 테넌트 관리 권한
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 그룹을 생성하기 전에 해당 그룹에 할당할 권한을 고려하십시오. 테넌트 관리 권한은 사용자가 테넌트 관리자 또는 테넌트 관리 API를 사용하여 수행할 수 있는 작업을 결정합니다. 사용자는 하나 이상의 그룹에 속할 수 있습니다. 사용자가 여러 그룹에 속한 경우 권한은 누적됩니다.

테넌트 관리자에 로그인하거나 테넌트 관리 API를 사용하려면 사용자가 하나 이상의 권한이 있는 그룹에 속해야 합니다. 로그인할 수 있는 모든 사용자는 다음 작업을 수행할 수 있습니다.

* 대시보드 보기
* 자신의 암호 변경(로컬 사용자의 경우)


모든 권한에 대해 그룹의 액세스 모드 설정은 사용자가 설정을 변경하고 작업을 수행할 수 있는지 또는 관련 설정과 기능만 볼 수 있는지 여부를 결정합니다.


NOTE: 사용자가 여러 그룹에 속해 있고 모든 그룹이 읽기 전용으로 설정되어 있는 경우 사용자는 선택한 모든 설정 및 기능에 대해 읽기 전용 권한을 갖게 됩니다.

그룹에 다음과 같은 권한을 할당할 수 있습니다.

[cols="1a,3a,3a"]
|===
| 권한 | 설명 | 세부 정보 


 a| 
루트 액세스
 a| 
테넌트 관리자 및 테넌트 관리 API에 대한 전체 액세스를 제공합니다.
 a| 



 a| 
자체 S3 자격 증명을 관리합니다
 a| 
사용자가 자신의 S3 액세스 키를 생성하고 제거할 수 있습니다.
 a| 
이 권한이 없는 사용자는 * storage(S3) * > * My S3 access keys * 메뉴 옵션을 볼 수 없습니다.



 a| 
모든 버킷을 봅니다
 a| 
사용자가 모든 버킷과 버킷 구성을 볼 수 있습니다.
 a| 
모든 버킷 보기 또는 모든 버킷 관리 권한이 없는 사용자에게는 * Bucket * 메뉴 옵션이 표시되지 않습니다.

이 권한은 모든 버킷 관리 권한으로 대체됩니다.  이는 S3 클라이언트나 S3 콘솔에서 사용하는 S3 버킷이나 그룹 정책에는 영향을 미치지 않습니다.



 a| 
모든 버킷을 관리합니다
 a| 
사용자가 테넌트 관리자와 테넌트 관리 API를 사용하여 S3 버킷을 생성 및 삭제하고, S3 버킷이나 그룹 정책에 관계없이 테넌트 계정의 모든 S3 버킷에 대한 설정을 관리할 수 있도록 합니다.
 a| 
모든 버킷 보기 또는 모든 버킷 관리 권한이 없는 사용자에게는 * Bucket * 메뉴 옵션이 표시되지 않습니다.

이 권한은 모든 버킷 보기 권한보다 우선합니다.  이는 S3 클라이언트나 S3 콘솔에서 사용하는 S3 버킷이나 그룹 정책에는 영향을 미치지 않습니다.



 a| 
엔드포인트 관리
 a| 
사용자가 테넌트 관리자 또는 테넌트 관리 API를 사용하여 플랫폼 서비스 엔드포인트를 생성하거나 편집할 수 있습니다. 이 엔드포인트는 StorageGRID 플랫폼 서비스의 대상으로 사용됩니다.
 a| 
이 권한이 없는 사용자는 * 플랫폼 서비스 끝점 * 메뉴 옵션이 표시되지 않습니다.



 a| 
S3 콘솔 탭을 사용합니다
 a| 
모든 버킷 보기 또는 모든 버킷 관리 권한과 함께 사용하면 사용자가 버킷에 대한 세부 정보 페이지의 S3 콘솔 탭에서 오브젝트를 보고 관리할 수 있습니다.
 a| 

|===