---
permalink: tenant/understanding-cloudmirror-replication-service.html 
sidebar: sidebar 
keywords: cloudmirror replication 
summary: StorageGRID가 버킷에 추가된 지정된 오브젝트를 하나 이상의 대상 버킷에 복제하도록 하려면 S3 버킷에 대해 CloudMirror 복제를 활성화할 수 있습니다. 
---
= CloudMirror 복제 서비스를 이해합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID가 버킷에 추가된 지정된 오브젝트를 하나 이상의 외부 대상 버킷에 복제하도록 하려는 경우 S3 버킷에 대해 CloudMirror 복제를 활성화할 수 있습니다.

예를 들어, CloudMirror 복제를 사용하여 특정 고객 레코드를 Amazon S3에 미러링한 다음 AWS 서비스를 활용하여 데이터에 대한 분석을 수행할 수 있습니다.


NOTE: 소스 버킷에 S3 오브젝트 잠금이 설정된 경우 CloudMirror 복제가 지원되지 않습니다.



== CloudMirror 및 ILM

CloudMirror 복제는 그리드의 활성 ILM 정책과 독립적으로 작동합니다. CloudMirror 서비스는 소스 버킷에 저장된 객체를 복제하여 가능한 한 빨리 대상 버킷에 제공합니다. 오브젝트 수집의 성공 시 복제된 오브젝트 제공이 트리거됩니다.



== CloudMirror 및 교차 그리드 복제

CloudMirror 복제는 교차 그리드 복제 기능과의 중요한 유사점과 차이점이 있습니다. 을 link:../admin/grid-federation-compare-cgr-to-cloudmirror.html["교차 그리드 복제와 CloudMirror 복제를 비교합니다"]참조하십시오.



== CloudMirror 및 S3 버킷

CloudMirror 복제는 일반적으로 외부 S3 버킷을 대상으로 사용하도록 구성됩니다. 그러나 다른 StorageGRID 배포나 S3 호환 서비스를 사용하도록 복제를 구성할 수도 있습니다.

기존 버킷:: 기존 버킷에 대해 CloudMirror 복제를 활성화하면 해당 버킷에 추가된 새 오브젝트만 복제됩니다. 버킷의 기존 객체는 복제되지 않습니다. 기존 오브젝트의 복제를 강제로 수행하려면 오브젝트 복사를 수행하여 기존 오브젝트의 메타데이터를 업데이트할 수 있습니다.
+
--

NOTE: CloudMirror 복제를 사용하여 Amazon S3 대상으로 오브젝트를 복사하는 경우 Amazon S3는 각 PUT 요청 헤더 내의 사용자 정의 메타데이터 크기를 2KB로 제한합니다. 객체에 2KB보다 큰 사용자 정의 메타데이터가 있는 경우 해당 객체가 복제되지 않습니다.

--
다중 대상 버킷:: 단일 버킷의 오브젝트를 여러 대상 버킷으로 복제하려면 복제 구성 XML에서 각 규칙의 대상을 지정합니다. 객체를 둘 이상의 버킷에 동시에 복제할 수 없습니다.
버전 또는 버전 해제된 버킷:: 버전 또는 버전이 지정되지 않은 버킷에서 CloudMirror 복제를 구성할 수 있습니다. 대상 버킷의 버전을 지정하거나 버전을 취소할 수 있습니다. 버전 및 비버전 버킷의 모든 조합을 사용할 수 있습니다. 예를 들어 버전이 지정되지 않은 소스 버킷의 대상으로 버전 관리가 지정된 버킷을 지정하거나 그 반대로 지정할 수 있습니다. 버전이 지정되지 않은 버킷 간에 복제할 수도 있습니다.




== 삭제, 복제 루프 및 이벤트입니다

삭제 동작:: 는 Amazon S3 서비스, 지역 간 복제(CRR)의 삭제 동작과 동일합니다. 소스 버킷에서 오브젝트를 삭제하면 대상에서 복제된 오브젝트가 삭제되지 않습니다. 소스 및 대상 버킷의 버전이 모두 지정된 경우 삭제 마커가 복제됩니다. 대상 버킷의 버전이 지정되지 않은 경우 소스 버킷에서 오브젝트를 삭제해도 삭제 마커가 대상 버킷에 복제되거나 대상 오브젝트를 삭제하지 않습니다.
복제 루프로부터 보호합니다:: 오브젝트가 대상 버킷에 복제되면 StorageGRID는 객체를 "복제본"으로 표시합니다. 대상 StorageGRID 버킷은 복제본으로 표시된 객체를 다시 복제하지 않으므로 실수로 인한 복제 루프가 발생하지 않습니다. 이 복제 마킹은 StorageGRID 내부에 있으며 Amazon S3 버킷을 대상으로 사용할 때 AWS CRR을 활용할 수 없습니다.
+
--

NOTE: 복제본을 표시하는 데 사용되는 사용자 지정 헤더는 입니다 `x-ntap-sg-replica`. 이 표시는 계단식 미러를 방지합니다. StorageGRID는 두 그리드 간의 양방향 CloudMirror를 지원합니다.

--
목적지 버킷의 이벤트:: 목적지 버킷에서 이벤트의 고유성과 순서는 보장되지 않습니다. 전송 성공을 보장하기 위해 수행된 작업의 결과로 소스 객체의 동일한 복제본이 두 개 이상 대상에 제공될 수 있습니다. 드물지만 둘 이상의 서로 다른 StorageGRID 사이트에서 동일한 객체가 동시에 업데이트되는 경우 대상 버킷의 작업 순서가 소스 버킷의 이벤트 순서와 일치하지 않을 수 있습니다.

