---
permalink: tenant/update-default-retention-settings.html 
sidebar: sidebar 
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance 
summary: 버킷을 생성할 때 S3 오브젝트 잠금을 설정한 경우 버킷을 편집하여 기본 보존 설정을 변경할 수 있습니다. 기본 보존을 사용하거나 사용하지 않도록 설정하고 기본 보존 모드 및 보존 기간을 설정할 수 있습니다. 
---
= S3 오브젝트 잠금 기본 보존 업데이트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
버킷을 생성할 때 S3 오브젝트 잠금을 설정한 경우 버킷을 편집하여 기본 보존 설정을 변경할 수 있습니다. 기본 보존을 사용하거나 사용하지 않도록 설정하고 기본 보존 모드 및 보존 기간을 설정할 수 있습니다.

.시작하기 전에
* 를 사용하여 테넌트 관리자에 로그인되어 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 이 있는 사용자 그룹에 속해 link:tenant-management-permissions.html["모든 버킷 또는 루트 액세스 권한을 관리합니다"]있습니다. 이러한 권한은 그룹 또는 버킷 정책의 사용 권한 설정을 재정의합니다.
* S3 오브젝트 잠금은 StorageGRID 시스템에 대해 전역적으로 활성화되며 버킷을 생성할 때 S3 오브젝트 잠금을 활성화했습니다. 을 link:using-s3-object-lock.html["S3 오브젝트 잠금을 사용하여 오브젝트를 보존합니다"]참조하십시오.


.단계
. 대시보드에서 * 버킷 보기 * 를 선택하거나 * 스토리지(S3) * > * 버킷 * 을 선택합니다.
. 테이블에서 버킷 이름을 선택합니다.
+
버킷 세부 정보 페이지가 나타납니다.

. Bucket options * 탭에서 * S3 Object Lock * 아코디언을 선택합니다.
. 이 버킷에 대해 * 기본 보존 * 을 활성화 또는 비활성화할 수 있습니다(선택 사항).
+
이 설정의 변경 사항은 버킷에 이미 있는 오브젝트 또는 자체 보존 기간이 있을 수 있는 오브젝트에는 적용되지 않습니다.

. 기본 보존 * 이 활성화된 경우 버킷에 대한 * 기본 보존 모드 * 를 지정합니다.
+
[cols="1a,2a"]
|===
| 기본 보존 모드 | 설명 


 a| 
기대치를 설정합니다
 a| 
**  있는 사용자는 `s3:BypassGovernanceRetention`권한이 요청 헤더를 사용하여 보존 설정을 무시할 수 `x-amz-bypass-governance-retention: true` 있습니다.
** 이러한 사용자는 보존 기한이 되기 전에 개체 버전을 삭제할 수 있습니다.
** 이러한 사용자는 개체의 보존 기간(Retain-until-date)을 증가, 감소 또는 제거할 수 있습니다.




 a| 
규정 준수
 a| 
** 보존 기한 에 도달할 때까지 개체를 삭제할 수 없습니다.
** 오브젝트의 보존 기한 을 늘릴 수 있지만 줄일 수는 없습니다.
** 개체의 보존 기한 은 해당 날짜에 도달할 때까지 제거할 수 없습니다.


* 참고 *: 그리드 관리자가 규정 준수 모드를 사용할 수 있도록 허용해야 합니다.

|===
. 기본 보존 * 이 활성화된 경우 버킷의 * 기본 보존 기간 * 을 지정합니다.
+
기본 보존 기간 * 은 이 버킷에 추가된 새 오브젝트를 인제스트할 시간부터 보존 기간을 나타냅니다. 그리드 관리자가 설정한 테넌트의 최대 보존 기간보다 작거나 같은 값을 지정하십시오.

+
그리드 관리자가 테넌트를 생성할 때 1일에서 100년 사이의 값을 지정할 수 있는 _MAXIMUM_RETENTION 기간이 설정됩니다. _default_retention 기간을 설정하면 최대 보존 기간에 설정된 값을 초과할 수 없습니다. 필요한 경우 그리드 관리자에게 최대 보존 기간을 늘리거나 줄이도록 요청하십시오.

. 변경 내용 저장 * 을 선택합니다.

