---
permalink: tenant/using-s3-object-lock.html 
sidebar: sidebar 
keywords: how to use s3 object lock 
summary: 버킷과 오브젝트가 보존 규정 요구사항을 준수해야 하는 경우 S3 오브젝트 잠금을 사용할 수 있습니다. 
---
= S3 오브젝트 잠금을 사용하여 오브젝트를 보존합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
버킷과 오브젝트가 보존 규정 요구사항을 준수해야 하는 경우 S3 오브젝트 잠금을 사용할 수 있습니다.


NOTE: 그리드 관리자는 귀하에게 S3 오브젝트 잠금의 특정 기능을 사용할 수 있는 권한을 부여해야 합니다.



== S3 오브젝트 잠금이란 무엇입니까?

StorageGRID S3 오브젝트 잠금 기능은 Amazon S3(Amazon Simple Storage Service)의 S3 오브젝트 잠금과 동등한 오브젝트 보호 솔루션입니다.

StorageGRID 시스템에 대해 글로벌 S3 오브젝트 잠금 설정이 활성화된 경우 S3 테넌트 계정에서 S3 오브젝트 잠금이 활성화되어 있거나 사용되지 않고 버킷을 생성할 수 있습니다. 버킷에 S3 오브젝트 잠금이 활성화된 경우 버킷 버전 관리가 필요하며 자동으로 활성화됩니다.

*S3 오브젝트 잠금이 없는 버킷은 보존 설정이 지정되지 않은 오브젝트만 가질 수 있습니다. 수집된 객체에는 보존 설정이 없습니다.

* S3 오브젝트 잠금이 있는 버킷은 S3 클라이언트 애플리케이션에 지정된 보존 설정이 있거나 없는 객체를 포함할 수 있습니다. 수집된 일부 객체에는 보존 설정이 있습니다.

* S3 오브젝트 잠금 및 기본 보존이 구성된 버킷 * 은 보존 설정이 지정된 객체와 보존 설정이 없는 새 객체를 업로드할 수 있습니다. 개체 수준에서 보존 설정이 구성되지 않았기 때문에 새 개체는 기본 설정을 사용합니다.

기본적으로 보존이 구성되면 새로 수집된 모든 객체에 보존 설정이 적용됩니다. 개체 보존 설정이 없는 기존 개체는 영향을 받지 않습니다.



=== 보존 모드

StorageGRID S3 오브젝트 잠금 기능은 두 가지 보존 모드를 지원하여 오브젝트에 다양한 보호 수준을 적용합니다. 이러한 모드는 Amazon S3 보존 모드에 해당합니다.

* 규정 준수 모드:
+
** 보존 기한 에 도달할 때까지 개체를 삭제할 수 없습니다.
** 오브젝트의 보존 기한 을 늘릴 수 있지만 줄일 수는 없습니다.
** 개체의 보존 기한 은 해당 날짜에 도달할 때까지 제거할 수 없습니다.


* 거버넌스 모드:
+
** 특수 권한이 있는 사용자는 요청에서 우회 헤더를 사용하여 특정 보존 설정을 수정할 수 있습니다.
** 이러한 사용자는 보존 기한이 되기 전에 개체 버전을 삭제할 수 있습니다.
** 이러한 사용자는 개체의 보존 기간(Retain-until-date)을 증가, 감소 또는 제거할 수 있습니다.






=== 개체 버전에 대한 보존 설정입니다

버킷이 S3 오브젝트 잠금이 설정된 상태로 생성된 경우 사용자는 S3 클라이언트 애플리케이션을 사용하여 버킷에 추가되는 각 오브젝트에 대해 다음 보존 설정을 선택적으로 지정할 수 있습니다.

* * 보존 모드 *: 규정 준수 또는 거버넌스 중 하나입니다.
* * Retain-until-date *: 개체 버전의 Retain-until-date가 미래인 경우 개체를 검색할 수 있지만 삭제할 수 없습니다.
* * 법적 증거 자료 보관 *: 개체 버전에 법적 증거 자료 보관 기능을 적용하면 해당 개체가 즉시 잠깁니다. 예를 들어 조사 또는 법적 분쟁과 관련된 객체에 법적 보류를 지정해야 할 수 있습니다. 법적 보류는 만료 날짜가 없지만 명시적으로 제거될 때까지 유지됩니다. 법적 보류는 보존 기한 과 무관합니다.
+

NOTE: 개체가 법적 보류 중인 경우 보존 모드에 관계없이 개체를 삭제할 수 없습니다.

+
개체 설정에 대한 자세한 내용은 을 참조하십시오link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 오브젝트 잠금을 구성합니다"].





=== 버킷을 위한 기본 보존 설정입니다

버킷이 S3 오브젝트 잠금이 활성화된 상태로 생성된 경우 사용자는 버킷에 대해 다음 기본 설정을 선택적으로 지정할 수 있습니다.

* * 기본 보존 모드 *: 규정 준수 또는 거버넌스 중 하나입니다.
* * 기본 보존 기간 *: 이 버킷에 추가된 새 오브젝트 버전이 추가되는 날부터 보존되어야 하는 기간입니다.


기본 버킷 설정은 고유한 보존 설정이 없는 새 오브젝트에만 적용됩니다. 이러한 기본 설정을 추가하거나 변경할 때 기존 버킷 개체는 영향을 받지 않습니다.

link:../tenant/creating-s3-bucket.html["S3 버킷을 생성합니다"]및 을 link:../tenant/update-default-retention-settings.html["S3 오브젝트 잠금 기본 보존 업데이트"]참조하십시오.



== S3 오브젝트 잠금 작업

그리드 관리자 및 테넌트 사용자를 위한 다음 목록에는 S3 오브젝트 잠금 기능을 사용하기 위한 상위 수준의 작업이 포함되어 있습니다.

그리드 관리자::
+
--
* 전체 StorageGRID 시스템에 대해 글로벌 S3 오브젝트 잠금 설정을 사용합니다.
* 정보 수명 주기 관리(ILM) 정책이 _ 준수되는지 확인합니다. 즉, 이 정책이 을link:../ilm/managing-objects-with-s3-object-lock.html["S3 오브젝트 잠금이 설정된 버킷 요구사항"](를) 충족하는지 확인합니다.
* 필요에 따라 테넌트가 규정 준수를 보존 모드로 사용할 수 있도록 허용합니다. 그렇지 않으면 거버넌스 모드만 허용됩니다.
* 필요에 따라 테넌트의 최대 보존 기간을 설정합니다.


--
테넌트 사용자입니다::
+
--
* S3 오브젝트 잠금을 통해 버킷 및 오브젝트에 대한 고려 사항을 검토하십시오.
* 필요한 경우 그리드 관리자에게 문의하여 글로벌 S3 오브젝트 잠금 설정을 활성화하고 권한을 설정합니다.
* S3 오브젝트 잠금이 설정된 상태로 버킷을 생성합니다.
* 필요에 따라 버킷의 기본 보존 설정을 구성합니다.
+
** 기본 보존 모드: 그리드 관리자가 허용하는 경우 거버넌스 또는 규정 준수
** 기본 보존 기간: 그리드 관리자가 설정한 최대 보존 기간 이하여야 합니다.


* S3 클라이언트 애플리케이션을 사용하여 오브젝트를 추가하고 필요에 따라 오브젝트별 보존을 설정합니다.
+
** 보존 모드. 거버넌스 또는 규정 준수(그리드 관리자가 허용하는 경우)
** 보관 종료 날짜: 그리드 관리자가 설정한 최대 보존 기간 이하여야 합니다.




--




== S3 오브젝트 잠금이 설정된 버킷의 요구 사항

* StorageGRID 시스템에 대해 글로벌 S3 오브젝트 잠금 설정이 활성화된 경우 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 S3 오브젝트 잠금이 활성화된 버킷을 생성할 수 있습니다.
* S3 오브젝트 잠금을 사용하려는 경우 버킷을 생성할 때 S3 오브젝트 잠금을 활성화해야 합니다. 기존 버킷에 S3 오브젝트 잠금을 설정할 수 없습니다.
* 버킷에 대해 S3 오브젝트 잠금이 활성화된 경우 StorageGRID는 해당 버킷의 버전 관리를 자동으로 활성화합니다. 버킷의 S3 오브젝트 잠금을 비활성화하거나 버전 관리를 일시 중단할 수 없습니다.
* 필요에 따라 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 각 버킷의 기본 보존 모드 및 보존 기간을 지정할 수 있습니다. 버킷의 기본 보존 설정은 고유한 보존 설정이 없는 버킷에 추가된 새 오브젝트에만 적용됩니다. 이 기본 설정은 업로드할 때 각 개체 버전에 대해 보존 모드 및 보존 종료 날짜를 지정하여 재정의할 수 있습니다.
* S3 오브젝트 잠금이 설정된 버킷에 대해 버킷 라이프사이클 구성이 지원됩니다.
* S3 오브젝트 잠금이 설정된 버킷에는 CloudMirror 복제가 지원되지 않습니다.




== S3 오브젝트 잠금이 설정된 버킷의 오브젝트 요구사항

* 개체 버전을 보호하려면 버킷의 기본 보존 설정을 지정하거나 각 오브젝트 버전에 대한 보존 설정을 지정할 수 있습니다. 오브젝트 레벨의 보존 설정은 S3 클라이언트 애플리케이션 또는 S3 REST API를 사용하여 지정할 수 있습니다.
* 보존 설정은 개별 개체 버전에 적용됩니다. 개체 버전에는 보존 기한 및 법적 보류 설정이 둘 다 있을 수 있으며, 둘 중 하나만 설정할 수도 있고 둘 다 가질 수도 없습니다. 개체에 대한 보존 기한 또는 법적 보류 설정을 지정하면 요청에 지정된 버전만 보호됩니다. 이전 버전의 개체는 잠겨 있는 상태에서 새 버전의 개체를 만들 수 있습니다.




== S3 오브젝트 잠금이 설정된 버킷의 오브젝트 라이프사이클

S3 오브젝트 잠금이 설정된 버킷에 저장된 각 오브젝트는 다음 단계를 거칩니다.

. * 오브젝트 수집 *
+
오브젝트 버전이 S3 오브젝트 잠금이 설정된 버킷에 추가되면 보존 설정이 다음과 같이 적용됩니다.

+
** 개체에 대한 보존 설정이 지정된 경우 개체 수준 설정이 적용됩니다. 기본 버킷 설정은 무시됩니다.
** 개체에 대해 보존 설정을 지정하지 않으면 기본 버킷 설정이 적용됩니다(있는 경우).
** 오브젝트 또는 버킷에 대해 보존 설정을 지정하지 않으면 S3 오브젝트 잠금으로 오브젝트가 보호되지 않습니다.


+
보존 설정이 적용되는 경우 오브젝트와 S3 사용자 정의 메타데이터는 모두 보호됩니다.

. * 개체 보존 및 삭제 *
+
StorageGRID는 지정된 보존 기간 동안 보호된 각 개체의 복사본을 여러 개 저장합니다. 오브젝트 복사본 및 스토리지 위치의 정확한 수와 유형은 활성 ILM 정책의 규정 준수 규칙에 따라 결정됩니다. 보존 기한이 되기 전에 보호된 개체를 삭제할 수 있는지 여부는 보존 모드에 따라 다릅니다.

+
** 개체가 법적 보류 중인 경우 보존 모드에 관계없이 개체를 삭제할 수 없습니다.






== 레거시 준수 버킷을 계속 관리할 수 있습니까?

S3 오브젝트 잠금 기능은 이전 StorageGRID 버전에서 사용할 수 있었던 규정 준수 기능을 대체합니다. 이전 버전의 StorageGRID를 사용하여 준수 버킷을 생성한 경우 이러한 버켓의 설정을 계속 관리할 수 있지만, 더 이상 새로운 준수 버킷을 생성할 수 없습니다. 자세한 내용은 을 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp 기술 자료: StorageGRID 11.5에서 레거시 준수 버킷을 관리하는 방법"^]참조하십시오.
