---
permalink: tenant/using-storagegrid-tenant-account.html 
sidebar: sidebar 
keywords: how to use tenant account 
summary: '테넌트 계정을 사용하면 S3(Simple Storage Service) REST API를 사용하여 StorageGRID 시스템에 객체를 저장하고 검색할 수 있습니다.' 
---
= StorageGRID 테넌트 계정을 사용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 계정을 사용하면 S3(Simple Storage Service) REST API를 사용하여 StorageGRID 시스템에 오브젝트를 저장하고 검색할 수 있습니다.

각 테넌트 계정에는 고유한 페더레이션 또는 로컬 그룹, 사용자, S3 버킷 및 오브젝트가 있습니다.


TIP: 이 버전의 문서 사이트에서 Swift 세부 정보가 제거되었습니다. 을 https://docs.netapp.com/us-en/storagegrid-118/tenant/using-storagegrid-tenant-account.html["StorageGRID 11.8: StorageGRID 테넌트 계정을 사용합니다"^]참조하십시오.

필요한 경우 테넌트 계정을 사용하여 저장된 객체를 다른 엔터티로 분리할 수 있습니다. 예를 들어, 다음과 같은 사용 사례에서 여러 테넌트 계정을 사용할 수 있습니다.

* * 기업 활용 사례: * 기업 내에서 StorageGRID 시스템을 사용하는 경우 그리드의 객체 스토리지를 조직의 여러 부서에서 분리할 수 있습니다. 예를 들어 마케팅 부서, 고객 지원 부서, 인사 부서 등의 테넌트 계정이 있을 수 있습니다.
+

NOTE: S3 클라이언트 프로토콜을 사용하는 경우 S3 버킷 및 버킷 정책을 사용하여 엔터프라이즈의 부서 간에 오브젝트를 분리할 수도 있습니다. 별도의 테넌트 계정을 생성할 필요가 없습니다. 자세한 내용은 구현 지침을 link:../s3/bucket-and-group-access-policies.html["S3 버킷 및 버킷 정책"]참조하십시오.

* * 서비스 공급자 사용 사례: * 서비스 공급자가 StorageGRID 시스템을 사용 중인 경우, 스토리지를 임대하는 다른 엔터티로 그리드의 개체 스토리지를 분리할 수 있습니다. 예를 들어 회사 A, 회사 B, 회사 C 등에 대한 테넌트 계정이 있을 수 있습니다.




== 테넌트 계정을 생성합니다

테넌트 계정은 그리드 관리자를 사용하여 StorageGRID 그리드 관리자가 만듭니다. 테넌트 계정을 생성할 때 그리드 관리자는 다음 정보를 지정합니다.

* 테넌트의 표시 이름(테넌트의 계정 ID가 자동으로 할당되며 변경할 수 없음)
* 테넌트 계정에서 S3 또는 Swift 프로토콜을 사용할지 여부를 나타냅니다.
* S3 테넌트 계정의 경우: 테넌트 계정이 플랫폼 서비스를 사용하도록 허용되는지 여부 플랫폼 서비스를 사용할 수 있는 경우 그리드 사용을 지원하도록 구성해야 합니다.
* 필요한 경우 테넌트 계정의 스토리지 할당량 -- 테넌트의 객체에 사용할 수 있는 최대 GB, 테라바이트 또는 PB입니다. 테넌트의 스토리지 할당량은 물리적 크기(디스크 크기)가 아닌 논리적 양(오브젝트 크기)을 나타냅니다.
* StorageGRID 시스템에 대해 ID 페더레이션이 설정된 경우 테넌트 계정을 구성할 수 있는 루트 액세스 권한이 있는 통합 그룹입니다.
* StorageGRID 시스템에서 SSO(Single Sign-On)를 사용하지 않는 경우 테넌트 계정이 자체 ID 소스를 사용할지 또는 그리드의 ID 소스를 공유할지 여부 및 테넌트의 로컬 루트 사용자의 초기 암호를 공유할지 여부


또한, S3 테넌트 계정이 규정 요구 사항을 준수해야 하는 경우 그리드 관리자는 StorageGRID 시스템에 대해 S3 오브젝트 잠금 설정을 활성화할 수 있습니다. S3 오브젝트 잠금이 활성화된 경우 모든 S3 테넌트 계정에서 호환 버킷을 생성하고 관리할 수 있습니다.



== S3 테넌트를 구성합니다

S3 테넌트 계정이 생성된 후 테넌트 관리자에 액세스하여 다음과 같은 작업을 수행할 수 있습니다.

* ID 통합을 설정하거나(ID 소스를 그리드와 공유하지 않는 경우) 로컬 그룹 및 사용자를 생성합니다
* S3 액세스 키 관리
* 규정 준수 버킷을 포함하여 S3 버킷 생성 및 관리
* 플랫폼 서비스 사용(활성화된 경우)
* 스토리지 사용량 모니터링



TIP: 테넌트 관리자를 사용하여 S3 버킷을 생성 및 관리할 수 있지만, S3 액세스 키를 가지고 S3 REST API를 사용하여 오브젝트를 수집 및 관리해야 합니다.

.관련 정보
* link:../admin/index.html["StorageGRID 관리"]
* link:../s3/index.html["S3 REST API 사용"]

