---
permalink: tenant/viewing-s3-bucket-details.html 
sidebar: sidebar 
keywords: how to view bucket details 
summary: 테넌트 계정의 버킷을 볼 수 있습니다. 
---
= 버킷 세부 정보를 봅니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 계정의 버킷을 볼 수 있습니다.

.시작하기 전에
* 를 사용하여 테넌트 관리자에 로그인되어 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 이 있는 사용자 그룹에 속해 link:tenant-management-permissions.html["루트 액세스, 모든 버킷 관리 또는 모든 버킷 보기 권한"]있습니다. 이러한 권한은 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.


.단계
. 대시보드에서 * 버킷 보기 * 를 선택하거나 * 스토리지(S3) * > * 버킷 * 을 선택합니다.
+
Bucket 페이지가 나타납니다.

. 각 버킷에 대한 요약 표를 검토합니다.
+
필요에 따라 모든 열을 기준으로 정보를 정렬하거나 목록 앞뒤에 페이지를 표시할 수 있습니다.

+

NOTE: 표시되는 개체 수, 사용된 공간 및 사용 현황 값은 추정값입니다. 이러한 추정치는 베스트 타이밍, 네트워크 연결 및 노드 상태의 영향을 받습니다. 버킷에 버전 관리가 활성화된 경우 삭제된 개체 버전은 오브젝트 수에 포함됩니다.

+
이름:: 버킷의 고유한 이름이며 변경할 수 없습니다.
활성화된 기능:: 버킷에 대해 활성화된 기능 목록입니다.
S3 오브젝트 잠금:: 버킷에 대해 S3 오브젝트 잠금이 설정되었는지 여부
+
--
이 열은 그리드에 S3 오브젝트 잠금이 활성화된 경우에만 나타납니다. 또한 이 열에는 레거시 준수 버킷에 대한 정보도 표시됩니다.

--
지역:: 변경할 수 없는 버킷의 영역입니다. 이 열은 기본적으로 숨겨져 있습니다.
개체 수입니다:: 이 버킷의 오브젝트 수 버킷에 버전 관리가 활성화된 경우 현재 버전이 아닌 개체 버전이 이 값에 포함됩니다.
+
--
개체를 추가하거나 삭제할 때 이 값은 즉시 업데이트되지 않을 수 있습니다.

--
사용된 공간:: 버킷에 있는 모든 오브젝트의 논리적 크기입니다. 논리적 크기에는 복제 또는 삭제 코딩 복사본 또는 오브젝트 메타데이터에 필요한 실제 공간이 포함되지 않습니다.
+
--
이 값을 업데이트하는 데 최대 10분이 걸릴 수 있습니다.

--
사용:: 버킷의 용량 제한에 사용된 백분율(설정된 경우).
+
--
사용률은 내부 추정치를 기준으로 하며 경우에 따라 초과될 수 있습니다. 예를 들어, StorageGRID는 테넌트가 객체 업로드를 시작할 때 용량 제한을 확인하고 테넌트가 용량 제한을 초과하는 경우 이 버킷에 대한 새 수신을 거부합니다. 그러나 StorageGRID는 용량 제한을 초과했는지 확인할 때 현재 업로드 크기를 고려하지 않습니다. 객체가 삭제되면 용량 제한 사용량이 다시 계산될 때까지 테넌트가 이 버킷에 새 객체를 업로드하지 못할 수 있습니다. 계산에는 10분 이상이 걸릴 수 있습니다.

이 값은 객체 및 해당 메타데이터를 저장하는 데 필요한 물리적 크기가 아니라 논리적 크기를 나타냅니다.

--
용량:: 설정된 경우 버킷의 용량 제한입니다.
만든 날짜:: 버킷이 생성된 날짜 및 시간입니다. 이 열은 기본적으로 숨겨져 있습니다.


. 특정 버킷의 세부 정보를 보려면 테이블에서 버킷 이름을 선택합니다.
+
.. 웹 페이지 상단에 있는 요약 정보를 확인하여 지역 및 오브젝트 수와 같은 버킷의 세부 정보를 확인합니다.
.. 용량 제한 사용량과 객체 수 제한 사용량 막대를 확인하세요.  사용량이 100%이거나 100%에 가까운 경우 한도를 늘리거나 일부 객체를 삭제하는 것을 고려하세요.
.. 필요에 따라 * Delete objects in bucket * 과 * Delete bucket * 을 선택합니다.
+
[CAUTION]
====
각 옵션을 선택할 때 나타나는 주의 사항에 각별히 주의하십시오. 자세한 내용은 다음을 참조하십시오.

*** link:deleting-s3-bucket-objects.html["버킷의 모든 오브젝트를 삭제합니다"]
*** link:deleting-s3-bucket.html["버킷을 삭제합니다"] (버킷은 비어 있어야 함)


====
.. 필요에 따라 각 탭에서 버킷의 설정을 보거나 변경합니다.
+
*** * S3 콘솔 * : 버킷에 대한 객체를 봅니다. 자세한 내용은 을 link:use-s3-console.html["S3 콘솔 사용"]참조하십시오.
*** * 버킷 옵션 * : 옵션 설정을 보거나 변경합니다. 버킷이 생성된 후에는 S3 Object Lock과 같은 일부 설정을 변경할 수 없습니다.
+
**** link:manage-bucket-consistency.html["버킷 일관성 관리"]
**** link:enabling-or-disabling-last-access-time-updates.html["마지막 액세스 시간 업데이트"]
**** link:../tenant/creating-s3-bucket.html#capacity-limit["용량 제한"]
**** link:../tenant/creating-s3-bucket.html#object-count-limit["객체 개수 제한"]
**** link:changing-bucket-versioning.html["오브젝트 버전 관리"]
**** link:using-s3-object-lock.html["S3 오브젝트 잠금"]
**** link:update-default-retention-settings.html["기본 버킷 보유"]
**** link:grid-federation-manage-cross-grid-replication.html["교차 그리드 복제 관리"] (테넌트에 대해 허용되는 경우)


*** * 플랫폼 서비스 *link:considerations-for-platform-services.html["플랫폼 서비스 관리"]: (테넌트에 대해 허용되는 경우)
*** * 버킷 액세스 * : 옵션 설정을 보거나 변경합니다. 특정 액세스 권한이 있어야 합니다.
+
**** 구성link:configuring-cross-origin-resource-sharing-for-buckets-and-objects.html["버킷 및 객체에 대한 CORS"] 따라서 버킷과 버킷 내의 객체는 다른 도메인의 웹 애플리케이션에서 접근할 수 있습니다.
**** link:../tenant/manage-bucket-policy.html["사용자 액세스를 제어합니다"] S3 버킷과 해당 버킷의 오브젝트용.


*** *지점*: 버킷의 지점 버킷 목록을 봅니다. link:../tenant/manage-branch-buckets.html["새로운 브랜치 버킷을 생성하거나 브랜치 버킷을 관리합니다."] .





