---
permalink: tenant/viewing-your-s3-access-keys.html 
sidebar: sidebar 
keywords: how to view your s3 access key 
summary: S3 테넌트를 사용하는 경우 적절한 권한이 있으면 S3 액세스 키 목록을 볼 수 있습니다. 만료 시간을 기준으로 목록을 정렬할 수 있으므로 곧 만료되는 키를 확인할 수 있습니다. 필요에 따라 새 키를 만들거나 더 이상 사용하지 않는 키를 삭제할 수 있습니다. 
---
= S3 액세스 키를 봅니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 테넌트를 사용 중이고 이 있는 경우 link:tenant-management-permissions.html["적절한 권한"]S3 액세스 키 목록을 볼 수 있습니다. 만료 시간을 기준으로 목록을 정렬할 수 있으므로 곧 만료되는 키를 확인할 수 있습니다. 필요에 따라 를 사용할 수도  있고 link:deleting-your-own-s3-access-keys.html["키를 삭제합니다"]더 이상 사용하지 않을 수도 link:creating-your-own-s3-access-keys.html["새 키를 만듭니다"]있습니다.


CAUTION: 계정에 속한 S3 버킷 및 오브젝트는 테넌트 관리자에 계정에 대해 표시된 액세스 키 ID 및 비밀 액세스 키를 사용하여 액세스할 수 있습니다. 이러한 이유로 액세스 키를 암호로 보호해야 합니다. 액세스 키를 정기적으로 회전하고, 계정에서 사용되지 않는 키를 제거하며, 다른 사용자와 공유하지 마십시오.

.시작하기 전에
* 를 사용하여 테넌트 관리자에 로그인되어 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 자신의 S3 자격 증명을 관리하는 사용자 그룹에 속해 link:tenant-management-permissions.html["권한"]있습니다.


.단계
. 스토리지(S3) * > * 내 액세스 키 * 를 선택합니다.
. 내 액세스 키 페이지에서 * 만료 시간 * 또는 * 액세스 키 ID * 를 기준으로 기존 액세스 키를 정렬합니다.
. 필요에 따라 새 키를 만들거나 더 이상 사용하지 않는 키를 삭제합니다.
+
기존 키가 만료되기 전에 새 키를 만들면 계정의 개체에 대한 액세스 권한을 일시적으로 잃지 않고 새 키를 사용할 수 있습니다.

+
만료된 키는 자동으로 제거됩니다.


