---
permalink: tenant/what-is-branch-bucket.html 
sidebar: sidebar 
keywords: how to create branch bucket 
summary: 분기 버킷은 특정 시간에 존재했던 버킷의 객체에 대한 액세스를 제공합니다. 
---
= 브랜치 버킷이란 무엇인가요?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
분기 버킷은 특정 시간에 존재했던 버킷의 객체에 대한 액세스를 제공합니다.

기존 버킷에서 브랜치 버킷을 만듭니다.  브랜치 버킷을 생성한 후, 해당 버킷이 생성된 원래 버킷을 _기본 버킷_이라고 합니다.  또한 다른 브랜치 버킷에서 브랜치 버킷을 만들 수도 있습니다.

지점 버킷은 보호된 데이터에 대한 액세스를 제공하지만 백업 역할을 하지는 않습니다.  데이터를 계속 보호하려면 기본 버킷에서 다음 기능을 사용하세요.

* link:../tenant/using-s3-object-lock.html["S3 오브젝트 잠금"]
* link:../admin/grid-federation-what-is-cross-grid-replication.html["교차 그리드 복제"]베이스 버킷용
* link:../tenant/manage-bucket-policy.html["버킷 정책"]버전이 지정된 버킷에서 이전 객체 버전을 정리합니다.


지점 버킷의 다음 특성을 참고하세요.

* 다음을 사용하여 브랜치 버킷의 개체에 액세스할 수 있습니다.link:../tenant/use-s3-console.html["객체를 다운로드하기 위한 S3 콘솔"] .
* 클라이언트가 브랜치 버킷의 객체에 액세스하는 경우 브랜치 버킷의link:../s3/use-access-policies.html["액세스 정책"] 기본 버킷의 정책보다는 액세스가 허용되거나 거부되는지 여부를 결정합니다.
* 기본 버킷에 생성된 객체는 다음을 기준으로 평가됩니다.link:../ilm/access-create-ilm-rule-wizard.html["ILM 규칙"] 기본 버킷에 적용합니다.  지점 버킷에 생성된 개체는 ILM 규칙이 지점 버킷에 적용되는 방식에 따라 평가됩니다.
* 브랜치 버킷에서는 크로스 그리드 복제가 지원되지 않습니다.
* 플랫폼 서비스는 지점 버킷에서 지원되지 않습니다.




== 지점 버킷 사용에 대한 예

* 손상된 객체를 제거하려면 손상이 발생하기 전 시점부터 브랜치 버킷을 만든 다음 손상된 객체가 들어 있는 기본 버킷 대신 해당 브랜치 버킷을 애플리케이션에 가리키도록 하면 됩니다.
* 버전이 지정된 버킷에 데이터를 저장합니다.  시간 _T_ 이후에 원치 않는 많은 물건이 섭취되는 우발적인 취약점이 있었습니다.  Before 시간 값인 _T_에 대한 분기 버킷을 생성하고 클라이언트 작업을 해당 분기 버킷으로 리디렉션할 수 있습니다.  그러면 Before time _T_보다 일찍 수집된 객체만 클라이언트에 노출됩니다.




== 브랜치 버킷의 객체에 대한 작업

* 브랜치 버킷에 대한 PUT 객체 작업은 브랜치에 객체를 생성합니다.
* 브랜치 버킷에 대한 GET 객체 작업은 브랜치에서 객체를 검색합니다.  객체가 브랜치 버킷에 없으면 객체는 기본 버킷에서 검색됩니다.
* 브랜치 버킷에서 객체 삭제는 다음과 같이 발생합니다.
+
[cols="1a,1a,2a,2a,2a"]
|===
| 작동 | 목표 | 결과 | 기본 버킷의 객체 가시성 | 브랜치 버킷의 객체 가시성 


 a| 
버전 ID 없이 삭제
 a| 
베이스 버킷
 a| 
삭제 마커는 기본 버킷에 대해서만 생성됩니다.
 a| 
HEAD/GET은 객체가 존재하지 않지만 특정 버전에는 여전히 액세스할 수 있음을 반환합니다.
 a| 
HEAD/GET은 객체가 존재하고 특정 버전에 계속 액세스할 수 있음을 반환합니다.

삭제 마커는 브랜치 버킷 이후에 생성되었을 것입니다. `beforeTime` .



 a| 
버전 ID로 삭제
 a| 
베이스 버킷
 a| 
기본 버킷과 분기 버킷 모두에 대해 특정 개체 버전이 삭제됩니다.
 a| 
HEAD/GET이 개체 버전이 존재하지 않는다는 것을 반환합니다.
 a| 
HEAD/GET이 개체 버전이 존재하지 않는다는 것을 반환합니다.



 a| 
버전 ID 없이 삭제
 a| 
가지 버킷
 a| 
삭제 마커는 브랜치 버킷에 대해서만 생성됩니다.
 a| 
HEAD/GET은 객체를 반환합니다(기본 버킷 객체는 영향을 받지 않음)
 a| 
HEAD/GET이 객체가 존재하지 않는다는 것을 반환합니다.



 a| 
버전 ID로 삭제
 a| 
가지 버킷
 a| 
특정 객체 버전은 브랜치 버킷에 대해서만 삭제됩니다.
 a| 
HEAD/GET은 특정 객체 버전을 반환합니다(기본 버킷 객체는 영향을 받지 않음)
 a| 
HEAD/GET이 개체 버전이 존재하지 않는다는 것을 반환합니다.

|===


또한 참조link:../ilm/how-objects-are-deleted.html#delete-s3-versioned-objects["S3 버전 오브젝트 삭제 방법"] .
