---
permalink: vmware/collecting-information-about-your-deployment-environment.html 
sidebar: sidebar 
keywords: how to collect information about your deployment environment 
summary: 그리드 노드를 구축하기 전에 네트워크 구성 및 VMware 환경에 대한 정보를 수집해야 합니다. 
---
= 배포 환경에 대한 정보를 수집합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 노드를 구축하기 전에 네트워크 구성 및 VMware 환경에 대한 정보를 수집해야 합니다.


NOTE: 일부 노드를 나중에 설치하는 대신 모든 노드를 한 번 설치하는 것이 더 효율적입니다.



== VMware 정보입니다

배포 환경에 액세스하여 VMware 환경, 그리드, 관리자 및 클라이언트 네트워크용으로 생성된 네트워크, 스토리지 노드에 사용할 스토리지 볼륨 유형에 대한 정보를 수집해야 합니다.

다음을 포함하여 VMware 환경에 대한 정보를 수집해야 합니다.

* 구축을 완료할 수 있는 적절한 권한이 있는 VMware vSphere 계정의 사용자 이름 및 암호입니다.
* 각 StorageGRID 노드 가상 머신에 대한 호스트, 데이터 저장소 및 네트워크 구성 정보입니다.



NOTE: VMware Live vMotion을 사용하면 가상 머신 클록 시간이 점프를 일으키며 모든 유형의 그리드 노드에서는 지원되지 않습니다. 드물지만 잘못된 클럭 시간으로 인해 데이터 또는 구성 업데이트가 손실될 수 있습니다.



== 그리드 네트워크 정보

StorageGRID 그리드 네트워크(필수)용으로 생성된 VMware 네트워크에 대한 정보를 수집해야 합니다. 여기에는 다음이 포함됩니다.

* 네트워크 이름입니다.
* 고정 또는 DHCP 중 IP 주소를 할당하는 데 사용되는 방법입니다.
+
** 고정 IP 주소를 사용하는 경우 각 그리드 노드에 필요한 네트워킹 세부 정보(IP 주소, 게이트웨이, 네트워크 마스크)가 표시됩니다.
** DHCP를 사용하는 경우 그리드 네트워크에 있는 기본 관리자 노드의 IP 주소입니다. 자세한 내용은 을 link:how-grid-nodes-discover-primary-admin-node.html["그리드 노드가 기본 관리자 노드를 검색하는 방법"] 참조하십시오.






== 관리자 네트워크 정보

선택적 StorageGRID 관리자 네트워크에 연결될 노드의 경우 이 네트워크에 대해 생성된 VMware 네트워크 관련 정보를 수집해야 합니다. 여기에는 다음이 포함됩니다.

* 네트워크 이름입니다.
* 고정 또는 DHCP 중 IP 주소를 할당하는 데 사용되는 방법입니다.
+
** 고정 IP 주소를 사용하는 경우 각 그리드 노드에 필요한 네트워킹 세부 정보(IP 주소, 게이트웨이, 네트워크 마스크)가 표시됩니다.
** DHCP를 사용하는 경우 그리드 네트워크에 있는 기본 관리자 노드의 IP 주소입니다. 자세한 내용은 을 link:how-grid-nodes-discover-primary-admin-node.html["그리드 노드가 기본 관리자 노드를 검색하는 방법"] 참조하십시오.


* 관리 네트워크의 외부 서브넷 목록(ESL).




== 클라이언트 네트워크 정보

선택적 StorageGRID 클라이언트 네트워크에 연결될 노드의 경우 이 네트워크에 대해 생성된 VMware 네트워크 관련 정보를 수집해야 합니다. 여기에는 다음이 포함됩니다.

* 네트워크 이름입니다.
* 고정 또는 DHCP 중 IP 주소를 할당하는 데 사용되는 방법입니다.
* 고정 IP 주소를 사용하는 경우 각 그리드 노드에 필요한 네트워킹 세부 정보(IP 주소, 게이트웨이, 네트워크 마스크)가 표시됩니다.




== 추가 인터페이스에 대한 정보입니다

노드를 설치한 후 vCenter에서 VM에 트렁크 또는 액세스 인터페이스를 선택적으로 추가할 수 있습니다. 예를 들어, 관리 또는 게이트웨이 노드에 트렁크 인터페이스를 추가하여 VLAN 인터페이스를 사용하여 다른 애플리케이션이나 테넌트에 속한 트래픽을 분리할 수 있습니다. 또는 고가용성(HA) 그룹에서 사용할 액세스 인터페이스를 추가할 수도 있습니다.

추가한 인터페이스는 VLAN 인터페이스 페이지와 Grid Manager의 HA 그룹 페이지에 표시됩니다.

* 트렁크 인터페이스를 추가하는 경우 각각의 새 상위 인터페이스에 대해 하나 이상의 VLAN 인터페이스를 구성합니다. 을 link:../admin/configure-vlan-interfaces.html["VLAN 인터페이스를 구성합니다"]참조하십시오.
* 액세스 인터페이스를 추가할 경우 HA 그룹에 직접 추가해야 합니다. 을 link:../admin/configure-high-availability-group.html["고가용성 그룹을 구성합니다"]참조하십시오.




== 가상 스토리지 노드의 스토리지 볼륨

가상 머신 기반 스토리지 노드에 대한 다음 정보를 수집해야 합니다.

* 추가하려는 스토리지 볼륨(스토리지 LUN)의 수와 크기입니다. 을 참조하십시오.link:storage-and-performance-requirements.html["요구사항을 충족해야 합니다"]




== 그리드 구성 정보

그리드를 구성하려면 정보를 수집해야 합니다.

* 그리드 사용권
* NTP(Network Time Protocol) 서버 IP 주소입니다
* DNS 서버 IP 주소입니다

