---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download vmware installation files 
summary: StorageGRID 설치 아카이브를 다운로드하고 파일을 추출해야 합니다. 선택적으로 설치 패키지의 파일을 수동으로 확인할 수 있습니다. 
---
= StorageGRID 설치 파일을 다운로드하고 압축을 풉니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 설치 아카이브를 다운로드하고 파일을 추출해야 합니다. 선택적으로 설치 패키지의 파일을 수동으로 확인할 수 있습니다.

.단계
. 로 이동합니다 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["StorageGRID용 NetApp 다운로드 페이지"^].
. 최신 릴리스를 다운로드하려면 버튼을 선택하거나 드롭다운 메뉴에서 다른 버전을 선택하고 * GO * 를 선택합니다.
. NetApp 계정의 사용자 이름과 암호를 사용하여 로그인합니다.
. Caution/MustRead 문이 나타나면 해당 문을 읽고 확인란을 선택합니다.
+

CAUTION: StorageGRID 릴리스를 설치한 후 필요한 핫픽스를 적용해야 합니다. 자세한 내용은 를 참조하십시오 link:../maintain/storagegrid-hotfix-procedure.html["복구 및 유지 관리 지침의 핫픽스 절차"]

. 최종 사용자 사용권 계약을 읽고 확인란을 선택한 다음 * 동의 및 계속 * 을 선택합니다.
. StorageGRID 설치 * 열에서 VMware용 .tgz 또는 .zip 설치 아카이브를 선택합니다.
+

NOTE: 서비스 랩톱에서 Windows를 실행하는 경우 이 `.zip` 파일을 사용합니다.

. 설치 아카이브를 저장합니다.
. [[vmware-download-verification-package]] 설치 아카이브를 확인해야 하는 경우:
+
.. StorageGRID 코드 서명 확인 패키지를 다운로드합니다. 이 패키지의 파일 이름은 StorageGRID 소프트웨어 버전의 형식을 `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz` 사용합니다. `<version-number>`
.. 의 단계를 link:../vmware/download-files-verify.html["설치 파일을 수동으로 확인합니다"]따릅니다.


. 설치 아카이브에서 파일 압축을 풉니다.
. 필요한 파일을 선택합니다.
+
필요한 파일은 계획된 그리드 토폴로지와 StorageGRID 시스템을 구축하는 방법에 따라 다릅니다.




NOTE: 표에 나열된 경로는 추출된 설치 아카이브에서 설치한 최상위 디렉토리에 상대적입니다.

[cols="1a,1a"]
|===
| 경로 및 파일 이름입니다 | 설명 


| ./vSphere/README  a| 
StorageGRID 다운로드 파일에 포함된 모든 파일을 설명하는 텍스트 파일입니다.



| ./vSphere/NLF000000.txt  a| 
제품에 대한 지원 권한을 제공하지 않는 무료 라이센스입니다.



| ./vSphere/NetApp-SG-version-SHA.vmdk입니다  a| 
그리드 노드 가상 머신을 생성하기 위한 템플릿으로 사용되는 가상 머신 디스크 파일입니다.



| ./vSphere/vSphere-primary-admin.ovf./vSphere/vSphere-primary-admin.mf  a| 
Open Virtualization Format 템플릿 파일(`.ovf`) 및 매니페스트 파일(`.mf`)을 사용하여 기본 관리자 노드를 배포할 수 있습니다.



| ./vSphere/vSphere-non-primary-admin.ovf./vSphere/vSphere-non-primary-admin.mf  a| 
템플릿 파일(`.ovf`) 및 매니페스트 파일(`.mf`)을 사용하여 비기본 관리 노드를 배포합니다.



| ./vSphere/vSphere-gateway.ovf./vSphere/vSphere-gateway.mf  a| 
템플릿 파일(`.ovf`) 및 매니페스트 파일(`.mf`)을 사용하여 게이트웨이 노드를 배포할 수 있습니다.



| ./vSphere/vSphere-storage.ovf./vSphere/vSphere-storage.mf  a| 
템플릿 파일(`.ovf`) 및 매니페스트 파일(`.mf`)을 사용하여 가상 머신 기반 스토리지 노드를 구축합니다.



| 배포 스크립팅 도구 | 설명 


| ./vSphere/deploy-vsphere-ovftool.sh  a| 
가상 그리드 노드의 배포를 자동화하는 데 사용되는 Bash 쉘 스크립트입니다.



| ./vSphere/deploy-vsphere-ovftool-sample.ini  a| 
스크립트와 함께 사용할 예제 구성 파일 `deploy-vsphere-ovftool.sh`



| ./vSphere/configure-storagegrid.py  a| 
StorageGRID 시스템 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./vSphere/configure-sga.py  a| 
StorageGRID 어플라이언스 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./vSphere/storagegrid-ssoauth.py  a| 
SSO(Single Sign-On)가 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트의 예 이 스크립트를 Ping 연합 통합에 사용할 수도 있습니다.



| /vSphere/configure -StorageGrid.sample.json을 참조하십시오  a| 
스크립트와 함께 사용할 예제 구성 파일 `configure-storagegrid.py`



| /vSphere/configure -StorageGrid.blank.json 을 참조하십시오  a| 
스크립트와 함께 사용할 빈 구성 `configure-storagegrid.py` 파일입니다.



| ./vSphere/storagegrid-ssoauth-azure.py  a| 
Active Directory 또는 Ping 연방을 사용하여 SSO(Single Sign-On)를 사용하도록 설정한 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예제



| /vSphere/StorageGrid-ssoauth-Azure.js  a| 
Azure와의 SSO 상호 작용을 수행하기 위해 Python 스크립트에 의해 호출되는 도우미 스크립트입니다. `storagegrid-ssoauth-azure.py`



| /vSphere/Extras/API-schemas  a| 
StorageGRID에 대한 API 스키마입니다.

* 참고 *: 업그레이드를 수행하기 전에 이러한 스키마를 사용하여 StorageGRID 관리 API를 사용하도록 작성한 코드가 업그레이드 호환성 테스트를 위한 비프로덕션 StorageGRID 환경이 없는 경우 새 StorageGRID 릴리스와 호환되는지 확인할 수 있습니다.

|===