---
permalink: rhel/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: 가상 머신을 사용하여 모든 유형의 StorageGRID 노드를 호스팅할 수 있습니다. 각 그리드 노드에 대해 하나의 가상 머신이 필요합니다. 
---
= Red Hat Enterprise Linux에 대한 소프트웨어 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 머신을 사용하여 모든 유형의 StorageGRID 노드를 호스팅할 수 있습니다. 각 그리드 노드에 대해 하나의 가상 머신이 필요합니다.

RHEL(Red Hat Enterprise Linux)에 StorageGRID를 설치하려면 일부 타사 소프트웨어 패키지를 설치해야 합니다. 지원되는 일부 Linux 배포판에는 기본적으로 이러한 패키지가 포함되어 있지 않습니다. StorageGRID 설치를 테스트하는 소프트웨어 패키지 버전에는 이 페이지에 나열된 버전이 포함됩니다.

이러한 패키지를 필요로 하는 Linux 배포 및 컨테이너 런타임 설치 옵션을 선택했는데 Linux 배포판에 의해 자동으로 설치되지 않은 경우, 해당 공급자 또는 Linux 배포판의 지원 공급업체에서 제공하는 경우 여기에 나열된 버전 중 하나를 설치하십시오. 그렇지 않으면 공급업체에서 제공하는 기본 패키지 버전을 사용하십시오.

모든 설치 옵션에는 Podman 또는 Docker가 필요합니다. 두 패키지를 모두 설치하지 마십시오. 설치 옵션에 필요한 패키지만 설치합니다.


NOTE: 소프트웨어 전용 배포를 위한 컨테이너 엔진으로 Docker에 대한 지원은 더 이상 사용되지 않습니다. Docker는 향후 릴리즈에서 다른 컨테이너 엔진으로 대체될 예정입니다.



== Python 버전을 테스트했습니다

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6




== Podman 버전을 테스트했습니다

* 3.2.3-0
* 3.4.4 + DS1
* 4.1.1-7
* 4.2.0-11
* 4.3.1+DS1-8+B1
* 4.4.1-8
* 4.4.1-12




== Docker 버전을 테스트했습니다


IMPORTANT: Docker 지원은 더 이상 사용되지 않으며 향후 릴리즈에서 제거될 예정입니다.

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3 을 참조하십시오
* Docker-CE 23.0.6-1 을 참조하십시오
* Docker-CE 24.0.2-1 을 참조하십시오
* Docker-CE 24.0.4-1 을 참조하십시오
* Docker-CE 24.0.5-1 을 참조하십시오
* Docker-CE 24.0.7-1 을 참조하십시오
* 1.5-2 을 참조하십시오

