---
permalink: admin/admin-group-permissions.html 
sidebar: sidebar 
keywords: admin group permissions 
summary: 관리자 사용자 그룹을 만들 때 그리드 관리자의 특정 기능에 대한 액세스를 제어하는 권한을 하나 이상 선택합니다. 그런 다음 각 사용자를 이러한 관리 그룹 중 하나 이상에 할당하여 사용자가 수행할 수 있는 작업을 결정할 수 있습니다. 
---
= 관리자 그룹 권한
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리자 사용자 그룹을 만들 때 그리드 관리자의 특정 기능에 대한 액세스를 제어하는 권한을 하나 이상 선택합니다. 그런 다음 각 사용자를 이러한 관리 그룹 중 하나 이상에 할당하여 사용자가 수행할 수 있는 작업을 결정할 수 있습니다.

각 그룹에 적어도 하나의 권한을 할당해야 합니다. 그렇지 않으면 해당 그룹에 속한 사용자가 Grid Manager 또는 Grid Management API에 로그인할 수 없습니다.

기본적으로 하나 이상의 사용 권한이 있는 그룹에 속한 사용자는 다음 작업을 수행할 수 있습니다.

* Grid Manager에 로그인합니다
* 대시보드 보기
* 노드 페이지를 봅니다
* 현재 및 해결된 경고를 봅니다
* 자신의 암호 변경(로컬 사용자만 해당)
* 구성 및 유지 관리 페이지에 제공된 특정 정보를 봅니다




== 사용 권한과 액세스 모드 간의 상호 작용

모든 권한에 대해 그룹의 * 액세스 모드 * 설정은 사용자가 설정을 변경하고 작업을 수행할 수 있는지 또는 관련 설정 및 기능만 볼 수 있는지 여부를 결정합니다. 사용자가 여러 그룹에 속해 있고 모든 그룹이 * 읽기 전용 * 으로 설정된 경우 사용자는 선택된 모든 설정 및 기능에 대한 읽기 전용 액세스 권한을 갖게 됩니다.

다음 섹션에서는 관리자 그룹을 만들거나 편집할 때 할당할 수 있는 권한에 대해 설명합니다. 명시적으로 언급되지 않은 기능을 사용하려면 * 루트 액세스 * 권한이 필요합니다.



== 루트 액세스

이 권한은 모든 그리드 관리 기능에 대한 액세스를 제공합니다.



== 테넌트 루트 암호를 변경합니다

이 권한은 테넌트 페이지의 * 루트 암호 변경 * 옵션에 대한 액세스를 제공하므로 테넌트의 로컬 루트 사용자의 암호를 변경할 수 있는 사용자를 제어할 수 있습니다. 이 권한은 S3 키 가져오기 기능이 활성화된 경우 S3 키를 마이그레이션하는 데도 사용됩니다. 이 권한이 없는 사용자는 * 루트 암호 변경 * 옵션을 볼 수 없습니다.


NOTE: 루트 암호 변경 * 옵션이 포함된 테넌트 페이지에 대한 액세스 권한을 부여하려면 * 테넌트 계정 * 권한도 할당합니다.



== 그리드 토폴로지 페이지 구성

이 권한은 * 지원 * > * 도구 * > * 그리드 토폴로지 * 페이지의 구성 탭에 대한 액세스를 제공합니다.


NOTE: 그리드 토폴로지 페이지는 더 이상 사용되지 않으며 향후 릴리즈에서 제거될 예정입니다.



== ILM을 참조하십시오

이 권한은 다음 * ILM * 메뉴 옵션에 대한 액세스를 제공합니다.

* 규칙
* 정책
* 정책 태그
* 지원합니다
* 보관 등급
* 지역
* 개체 메타데이터 조회



NOTE: 사용자는 * 기타 그리드 구성 * 및 * 그리드 토폴로지 페이지 구성 * 권한이 있어야 스토리지 등급을 관리할 수 있습니다.



== 유지 관리

다음 옵션을 사용하려면 사용자에게 유지 관리 권한이 있어야 합니다.

* * 구성 * > * 액세스 제어 *:
+
** 그리드 암호


* * 구성 * > * 네트워크 *:
+
** S3 끝점 도메인 이름


* * 유지보수 * > * 작업 *:
+
** 서비스 해제
** 확장
** 개체 존재 여부 검사
** 복구


* * 유지보수 * > * 시스템 *:
+
** 복구 패키지
** 소프트웨어 업데이트


* 지원 * > * 툴 *:
+
** 로그




유지 관리 권한이 없는 사용자는 다음 페이지를 볼 수 있지만 편집할 수는 없습니다.

* * 유지보수 * > * 네트워크 *:
+
** DNS 서버
** 그리드 네트워크
** NTP 서버


* * 유지보수 * > * 시스템 *:
+
** 라이센스


* * 구성 * > * 네트워크 *:
+
** S3 끝점 도메인 이름


* * 구성 * > * 보안 *:
+
** 인증서


* * 구성 * > * 모니터링 *:
+
** 감사 및 syslog 서버






== 알림을 관리합니다

이 권한은 알림 관리 옵션에 대한 액세스를 제공합니다. 사용자는 이 권한을 가지고 있어야 Silence, 경고 알림 및 경고 규칙을 관리할 수 있습니다.



== 메트릭 쿼리

이 권한은 다음에 대한 액세스를 제공합니다.

* 지원 * > * 도구 * > * 메트릭 * 페이지
* Grid Management API의 * Metrics * 섹션을 사용하여 맞춤형 Prometheus 메트릭 쿼리를 수행합니다
* 메트릭이 포함된 Grid Manager 대시보드 카드




== 개체 메타데이터 조회

이 권한은 * ILM * > * 개체 메타데이터 조회 * 페이지에 대한 액세스를 제공합니다.



== 기타 그리드 구성

이 권한은 추가 그리드 구성 옵션에 대한 액세스를 제공합니다.


TIP: 이러한 추가 옵션을 보려면 사용자에게 * 그리드 토폴로지 페이지 구성 * 권한도 있어야 합니다.

* * ILM *:
+
** 보관 등급


* * 구성 * > * 시스템 *:
* 지원 * > * 기타 *:
+
** 링크 비용






== 스토리지 어플라이언스 관리자

이 권한은 다음을 제공합니다.

* 그리드 관리자를 통해 스토리지 어플라이언스에서 E-Series SANtricity System Manager에 액세스할 수 있습니다.
* 이러한 작업을 지원하는 어플라이언스에 대한 드라이브 관리 탭에서 문제 해결 및 유지 관리 작업을 수행하는 기능.




== 테넌트 계정

이 권한은 다음 기능을 제공합니다.

* 테넌트 페이지에 액세스하여 테넌트 계정을 생성, 편집 및 제거할 수 있습니다
* 기존 트래픽 분류 정책을 봅니다
* 테넌트 세부 정보가 포함된 Grid Manager 대시보드 카드를 봅니다

