---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: 그리드의 각 노드에는 노드 콘솔 암호가 있으며 이 암호는 노드에 로그인하는 데 사용됩니다. 기본적으로 각 노드에는 고유한 암호가 있습니다. 각 암호를 고유한 새 암호로 변경하거나 모든 노드의 암호를 변경하여 글로벌 암호를 사용할 수 있습니다. 암호는 복구 패키지에 저장됩니다. 
---
= 노드 콘솔 암호를 변경합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드의 각 노드에는 노드 콘솔 암호가 있으며 이 암호는 노드에 로그인하는 데 사용됩니다. 기본적으로 각 노드에는 고유한 암호가 있습니다. 각 암호를 고유한 새 암호로 변경하거나 모든 노드의 암호를 변경하여 글로벌 암호를 사용할 수 있습니다. 암호는 복구 패키지에 저장됩니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:admin-group-permissions.html["유지 관리 또는 루트 액세스 권한"]있습니다.
* 현재 프로비저닝 암호가 있습니다.


.이 작업에 대해
노드 콘솔 암호를 사용하여 SSH를 사용하여 노드에 "admin"으로 로그인하거나 VM/물리적 콘솔 연결의 루트 사용자에게 로그인합니다. 다음 옵션 중 하나를 사용하여 노드 콘솔 암호를 변경할 수 있습니다.

* 각 노드에 무작위 암호를 자동으로 적용합니다
* 모든 노드에 하나의 글로벌 암호를 지정하고 적용합니다
* 하나 이상의 노드에 고유한 암호를 지정하고 적용합니다


암호는 복구 패키지의 업데이트된 `Passwords.txt` 파일에 저장됩니다. 암호는 파일의 암호 열에 나열됩니다.


NOTE: 노드 간 통신에 사용되는 SSH 키의 경우 는 link:../admin/change-ssh-access-passwords.html["SSH 액세스 암호"]노드 콘솔 암호와 별개입니다. 이 절차는 SSH 액세스 암호를 변경하지 않습니다.



== 마법사에 액세스합니다

.단계
. 구성 * > * 액세스 제어 * > * 그리드 비밀번호 * 를 선택합니다.
. 노드 콘솔 암호 변경 * 에서 * 변경 * 을 선택합니다.




== [[download-current]] 현재 복구 패키지를 다운로드합니다

노드 콘솔 암호를 변경하기 전에 현재 복구 패키지를 다운로드하십시오. 노드에 대한 암호 변경 프로세스가 실패할 경우 이 파일의 암호를 사용할 수 있습니다.

.단계
. 그리드의 프로비저닝 암호를 입력합니다.
. 복구 패키지 다운로드 * 를 선택합니다.
. 복구 패키지 파일 복사(`.zip`)를 안전하고 별도의 두 위치에 복사합니다.
+

CAUTION: 복구 패키지 파일은 StorageGRID 시스템에서 데이터를 가져오는 데 사용할 수 있는 암호화 키 및 암호가 포함되어 있으므로 안전하게 보호해야 합니다.

. Continue * 를 선택합니다.




== 새 암호를 입력합니다

. 사용할 암호 변경 방법을 선택합니다.
+
** * 자동 * : StorageGRID는 자동으로 모든 노드에 새로운 임의의 콘솔 암호를 할당합니다.
** * 사용자 정의 * : 콘솔 암호를 제공합니다.




[role="tabbed-block"]
====
.자동
--
. Continue * 를 선택합니다.


--
.맞춤형
--
. 다음 중 하나를 선택합니다.
+
** * 글로벌 콘솔 암호 * : 모든 노드에 동일한 콘솔 암호를 적용합니다.
** * 고유한 콘솔 암호 * : 하나 이상의 노드에 다른 암호를 적용합니다.


. Global console password * 를 선택한 경우 모든 노드에 사용할 암호를 입력합니다.
. 고유한 콘솔 암호 * 를 선택한 경우 하나 이상의 노드에 대해 고유한 암호를 입력합니다.
. Continue * 를 선택합니다.


--
====


== 암호 변경을 완료합니다

. 확인 대화 상자가 나타나면 StorageGRID에서 노드 콘솔 암호 변경을 시작할 준비가 되었으면 * 예 * 를 선택합니다.
+

NOTE: 이 프로세스가 시작된 후에는 취소할 수 없습니다.

+
StorageGRID는 새 암호가 포함된 새 복구 패키지를 생성합니다.

. 새 복구 패키지가 준비되면 * 새 복구 패키지 다운로드 * 를 선택하고 복구 패키지를 저장합니다.
. 파일을 엽니다 `.zip`.
. 새 노드 콘솔 암호가 포함된 파일을 포함하여 콘텐츠에 액세스할 수 있는지 확인합니다 `Passwords.txt`.
. 새 복구 패키지 파일(`.zip`)을 안전하고 별도의 두 위치에 복사합니다.
+

CAUTION: 이전 복구 패키지를 덮어쓰지 마십시오.

+
복구 파일에는 StorageGRID 시스템에서 데이터를 가져오는 데 사용할 수 있는 암호화 키와 암호가 포함되어 있으므로 이 파일을 보호해야 합니다.

. 확인란을 선택하여 새 복구 패키지를 다운로드하고 콘텐츠를 확인했음을 나타냅니다.
. Continue * 를 선택합니다.
+
StorageGRID는 각 노드의 암호를 업데이트합니다.

+
업데이트 프로세스 중에 오류가 발생하면 진행률 표시줄에 암호 변경에 실패한 노드 수가 표시됩니다. 암호가 변경되지 않은 노드에서 프로세스가 자동으로 다시 시도됩니다. 일부 노드의 암호를 변경하지 않고 프로세스가 종료되면 * Retry * (재시도 *) 버튼이 나타납니다.

. 하나 이상의 노드에 대한 암호 업데이트가 실패한 경우:
+
.. 표에 나열된 오류 메시지를 검토합니다.
.. 문제를 해결합니다.
.. 재시도 * 를 선택합니다.
+

NOTE: 다시 시도하면 이전 암호 변경 시도 중에 실패한 노드의 노드 콘솔 암호만 변경됩니다.



. 진행 표시줄에 남아 있는 업데이트가 없다고 표시되면 * Finish * 를 선택합니다.
. 모든 노드에 대해 노드 콘솔 암호를 변경한 후 를 <<download-current,처음 다운로드한 복구 패키지입니다>>삭제합니다.

