---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: 관리 노드의 SSH 액세스 암호를 변경하면 그리드의 각 노드에 대한 내부 SSH 키의 고유한 세트도 업데이트됩니다. 기본 관리자 노드는 이러한 SSH 키를 사용하여 보안 암호 없는 인증을 사용하여 노드에 액세스합니다. 
---
= 관리 노드의 SSH 액세스 암호를 변경합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 노드의 SSH 액세스 암호를 변경하면 그리드의 각 노드에 대한 내부 SSH 키의 고유한 세트도 업데이트됩니다. 기본 관리자 노드는 이러한 SSH 키를 사용하여 보안 암호 없는 인증을 사용하여 노드에 액세스합니다.

SSH 키를 사용하여 노드에 `admin` 또는 VM 또는 물리적 콘솔 연결에서 루트 사용자로 로그인합니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:admin-group-permissions.html["유지 관리 또는 루트 액세스 권한"]있습니다.
* 현재 프로비저닝 암호가 있습니다.


.이 작업에 대해
관리 노드의 새 액세스 암호와 각 노드의 새 내부 키는 `Passwords.txt` 복구 패키지의 파일에 저장됩니다. 해당 파일의 암호 열에 키가 나열됩니다.

노드 간 통신에 사용되는 SSH 키에 대해 별도의 SSH 액세스 암호가 있습니다. 이 절차는 변경되지 않습니다.



== 마법사에 액세스합니다

.단계
. 구성 * > * 액세스 제어 * > * 그리드 비밀번호 * 를 선택합니다.
. SSH 키 변경 * 아래에서 * 변경 * 을 선택합니다.




== [[download-current]] 현재 복구 패키지를 다운로드합니다

SSH 액세스 키를 변경하기 전에 현재 복구 패키지를 다운로드합니다. 노드에 대해 키 변경 프로세스가 실패하면 이 파일에서 키를 사용할 수 있습니다.

.단계
. 그리드의 프로비저닝 암호를 입력합니다.
. 복구 패키지 다운로드 * 를 선택합니다.
. 복구 패키지 파일(`.zip`)을 안전하고 별도의 두 위치에 복사합니다.
+

CAUTION: 복구 패키지 파일은 StorageGRID 시스템에서 데이터를 가져오는 데 사용할 수 있는 암호화 키와 암호가 포함되어 있으므로 보안을 유지해야 합니다.

. Continue * 를 선택합니다.
. 확인 대화 상자가 나타나면 SSH 액세스 키 변경을 시작할 준비가 되었으면 * Yes * 를 선택합니다.
+

CAUTION: 이 프로세스가 시작된 후에는 취소할 수 없습니다.





== SSH 액세스 키를 변경합니다

SSH 액세스 키 변경 프로세스가 시작되면 새 키가 포함된 새 복구 패키지가 생성됩니다. 그런 다음 각 노드에서 키가 업데이트됩니다.

.단계
. 새 복구 패키지가 생성될 때까지 기다립니다. 몇 분 정도 걸릴 수 있습니다.
. 새 복구 패키지 다운로드 버튼이 활성화되면 * 새 복구 패키지 다운로드 * 를 선택하고 새 복구 패키지 파일 저장(`.zip`)을 두 개의 안전한 위치에 각각 저장합니다.
. 다운로드가 완료되면 다음을 수행합니다.
+
.. 파일을 엽니다 `.zip`.
.. 새 SSH 액세스 키가 포함된 파일을 포함하여 콘텐츠에 액세스할 수 있는지 확인합니다 `Passwords.txt`.
.. 새 복구 패키지 파일(`.zip`)을 안전하고 별도의 두 위치에 복사합니다.
+

CAUTION: 이전 복구 패키지를 덮어쓰지 마십시오.

+
복구 패키지 파일은 StorageGRID 시스템에서 데이터를 가져오는 데 사용할 수 있는 암호화 키와 암호가 포함되어 있으므로 보안을 유지해야 합니다.



. 각 노드에서 키가 업데이트될 때까지 기다립니다. 몇 분 정도 걸릴 수 있습니다.
+
모든 노드의 키를 변경하면 녹색 성공 배너가 나타납니다.

+
업데이트 프로세스 중에 오류가 발생하면 배너 메시지에 키 변경에 실패한 노드 수가 나열됩니다. 시스템은 키 변경에 실패한 노드에서 프로세스를 자동으로 재시도합니다. 일부 노드에 변경 키가 없는 경우 * Retry *(재시도) 버튼이 나타납니다.

+
하나 이상의 노드에 대한 키 업데이트가 실패한 경우:

+
.. 표에 나열된 오류 메시지를 검토합니다.
.. 문제를 해결합니다.
.. 재시도 * 를 선택합니다.
+
다시 시도하면 이전 키 변경 시도 중에 장애가 발생한 노드에서 SSH 액세스 키만 변경됩니다.



. 모든 노드의 SSH 액세스 키를 변경한 후 를 <<download-current,다운로드한 첫 번째 복구 패키지>>삭제합니다.
. 필요한 경우 * 유지 관리 * > * 시스템 * > * 복구 패키지 * 를 선택하여 새 복구 패키지의 추가 복사본을 다운로드할 수 있습니다.

