---
permalink: admin/configuring-storage-proxy-settings.html 
sidebar: sidebar 
keywords: storage proxy, non-transparent proxy, platform service endpoint 
summary: 플랫폼 서비스 또는 클라우드 스토리지 풀을 사용하는 경우 스토리지 노드와 외부 S3 엔드포인트 간에 투명하지 않은 프록시를 구성할 수 있습니다. 예를 들어, 플랫폼 서비스 메시지를 인터넷의 끝점과 같은 외부 끝점으로 보내려면 투명하지 않은 프록시가 필요할 수 있습니다. 
---
= 스토리지 프록시를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
플랫폼 서비스 또는 클라우드 스토리지 풀을 사용하는 경우 스토리지 노드와 외부 S3 엔드포인트 간에 투명하지 않은 프록시를 구성할 수 있습니다. 예를 들어, 플랫폼 서비스 메시지를 인터넷의 끝점과 같은 외부 끝점으로 보내려면 투명하지 않은 프록시가 필요할 수 있습니다.


NOTE: 구성된 스토리지 프록시 설정은 Kafka 플랫폼 서비스 엔드포인트에 적용되지 않습니다.

.시작하기 전에
* 있습니다. link:admin-group-permissions.html["특정 액세스 권한"]
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]


.이 작업에 대해
단일 스토리지 프록시에 대한 설정을 구성할 수 있습니다.

.단계
. 구성 * > * 보안 * > * 프록시 설정 * 을 선택합니다.
. Storage * 탭에서 * Enable storage proxy * 확인란을 선택합니다.
. 스토리지 프록시의 프로토콜을 선택합니다.
. 프록시 서버의 호스트 이름 또는 IP 주소를 입력합니다.
. 필요에 따라 프록시 서버에 연결하는 데 사용되는 포트를 입력합니다.
+
프로토콜의 기본 포트(HTTP의 경우 80, SOCKS5의 경우 1080)를 사용하려면 이 필드를 비워 둡니다.

. 저장 * 을 선택합니다.
+
스토리지 프록시가 저장된 후 플랫폼 서비스 또는 클라우드 스토리지 풀의 새 엔드포인트를 구성하고 테스트할 수 있습니다.

+

NOTE: 프록시 변경 사항이 적용되려면 최대 10분이 소요될 수 있습니다.

. 프록시 서버의 설정을 확인하여 StorageGRID의 플랫폼 서비스 관련 메시지가 차단되지 않는지 확인합니다.
. 스토리지 프록시를 비활성화해야 하는 경우 확인란을 선택 취소하고 * 저장 * 을 선택합니다.

