---
permalink: admin/configuring-stored-object-compression.html 
sidebar: sidebar 
keywords: object compression, compress stored objects 
summary: 오브젝트 압축을 활성화하여 StorageGRID에 저장된 오브젝트 크기를 줄일 수 있으므로 오브젝트가 더 적은 스토리지를 소비하도록 할 수 있습니다. 
---
= 저장된 객체를 압축합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
오브젝트 압축을 활성화하여 StorageGRID에 저장된 오브젝트 크기를 줄일 수 있으므로 오브젝트가 더 적은 스토리지를 소비하도록 할 수 있습니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 있습니다. link:admin-group-permissions.html["특정 액세스 권한"]


.이 작업에 대해
기본적으로 오브젝트 압축은 비활성화되어 있습니다. 압축을 설정하면 StorageGRID는 무손실 압축을 사용하여 저장할 때 각 개체의 압축을 시도합니다.


NOTE: 이 설정을 변경하면 새 설정을 적용하는 데 약 1분이 걸립니다. 구성된 값이 성능 및 확장을 위해 캐싱됩니다.

오브젝트 압축을 설정하기 전에 다음 사항을 숙지하십시오.

* 저장 중인 데이터가 압축될 수 있다는 것을 모를 경우 * Compress stored objects * 를 선택하면 안 됩니다.
* 개체를 StorageGRID에 저장하는 응용 프로그램은 개체를 저장하기 전에 압축할 수 있습니다. 클라이언트 응용 프로그램이 개체를 StorageGRID에 저장하기 전에 이미 압축한 경우 이 옵션을 선택하면 개체의 크기가 더 작아지지 않습니다.
* StorageGRID에서 NetApp FabricPool를 사용하는 경우 * 저장된 오브젝트 압축 * 을 선택하지 마십시오.
* 저장된 개체 압축 * 을 선택하면 S3 클라이언트 응용 프로그램에서 반환되는 바이트 범위를 지정하는 GetObject 작업을 수행하지 않도록 해야 합니다. 이러한 "범위 읽기" 작업은 StorageGRID에서 요청된 바이트에 액세스하기 위해 개체의 압축을 효과적으로 해제해야 하기 때문에 비효율적입니다. 매우 큰 개체에서 작은 범위의 바이트를 요청하는 GetObject 작업은 특히 비효율적입니다. 예를 들어, 50GB의 압축된 개체에서 10MB 범위를 읽는 것은 비효율적입니다.
+
압축된 개체에서 범위를 읽으면 클라이언트 요청이 시간 초과될 수 있습니다.

+

NOTE: 개체를 압축해야 하고 클라이언트 응용 프로그램에서 범위 읽기를 사용해야 하는 경우 응용 프로그램의 읽기 시간 초과를 늘리십시오.



.단계
. Select * 구성 * > * 시스템 * > * 스토리지 설정 * > * 오브젝트 압축 * 을 선택합니다.
. 저장된 객체 압축 * 확인란을 선택합니다.
. 저장 * 을 선택합니다.

