---
permalink: admin/configure-autosupport-grid-manager.html 
sidebar: sidebar 
keywords: how to configure autosupport, what is autosupport-on-demand 
summary: 기본적으로 StorageGRID AutoSupport 기능은 StorageGRID를 처음 설치할 때 활성화됩니다. 그러나 각 어플라이언스에서 하드웨어 AutoSupport을 구성해야 합니다. 필요에 따라 AutoSupport 구성을 변경할 수 있습니다. 
---
= AutoSupport를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본적으로 StorageGRID AutoSupport 기능은 StorageGRID를 처음 설치할 때 활성화됩니다. 그러나 각 어플라이언스에서 하드웨어 AutoSupport을 구성해야 합니다. 필요에 따라 AutoSupport 구성을 변경할 수 있습니다.

StorageGRID AutoSupport의 구성을 변경하려면 기본 관리자 노드에서만 변경하십시오. 반드시 각 제품에 부착해야 <<autosupport-for-appliances,하드웨어 AutoSupport를 구성합니다>>합니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:admin-group-permissions.html["루트 액세스 권한"]있습니다.
* AutoSupport 패키지를 보내기 위해 HTTPS를 사용할 경우, 직접 또는  (인바운드 연결 필요 없음) 기본 관리자 노드에 대한 아웃바운드 인터넷 액세스를 제공한 link:configuring-admin-proxy-settings.html["프록시 서버 사용"]것입니다.
* StorageGRID AutoSupport 페이지에서 HTTP를 선택한 경우 AutoSupport 패키지를 HTTPS로 전달해야 link:configuring-admin-proxy-settings.html["프록시 서버를 구성했습니다"]합니다. NetApp의 AutoSupport 서버는 HTTP를 사용하여 전송된 패키지를 거부합니다.
* SMTP를 AutoSupport 패키지의 프로토콜로 사용할 경우 SMTP 메일 서버를 구성한 것입니다.


.이 작업에 대해
다음 옵션 중 원하는 옵션을 조합하여 AutoSupport 패키지를 기술 지원으로 보낼 수 있습니다.

* * 매주 *: 매주 AutoSupport 패키지를 자동으로 발송합니다. 기본 설정: 사용.
* * 이벤트 트리거 *: 매 시간마다 또는 중요한 시스템 이벤트가 발생할 때 자동으로 AutoSupport 패키지를 전송합니다. 기본 설정: 사용.
* * 온디맨드 *: 기술 지원 부서에서 StorageGRID 시스템에서 AutoSupport 패키지를 자동으로 보내도록 요청하도록 허용합니다. 이는 문제가 활발하게 발생할 때 유용합니다(HTTPS AutoSupport 전송 프로토콜 필요). 기본 설정: 사용 안 함
* * 사용자 트리거 * : 언제든지 수동으로 AutoSupport 패키지를 보내십시오.
* *로그 수집*:link:../monitor/collecting-log-files-and-system-data.html["수동으로 로그 파일과 시스템 데이터를 수집하고 AutoSupport 패키지를 보냅니다."] .




== [[Specify-protocol-for-autosupport-packages]] AutoSupport 패키지의 프로토콜을 지정합니다

다음 프로토콜을 사용하여 AutoSupport 패키지를 보낼 수 있습니다.

* * HTTPS *: 새 설치에 대한 기본 권장 설정입니다. 이 프로토콜은 포트 443을 사용합니다. 원하는 경우 <<AutoSupport 온디맨드 를 활성화합니다,AutoSupport 온디맨드 기능을 활성화합니다>>HTTPS를 사용해야 합니다.
* *HTTP*: HTTP를 선택하는 경우 AutoSupport 패키지를 HTTPS로 전달하도록 프록시 서버를 구성해야 합니다. NetApp의 AutoSupport 서버는 HTTP를 사용하여 전송된 패키지를 거부합니다. 이 프로토콜은 포트 80을 사용합니다.
* *SMTP*: AutoSupport 패키지를 이메일로 보내려면 이 옵션을 사용하십시오.


설정한 프로토콜은 모든 유형의 AutoSupport 패키지를 보내는 데 사용됩니다.

.단계
. *지원* > *도구* > * AutoSupport* > *설정*을 선택하세요.
. AutoSupport 패키지를 보내는 데 사용할 프로토콜을 선택합니다.
. HTTPS * 를 선택한 경우 NetApp 지원 인증서(TLS 인증서)를 사용하여 기술 지원 서버에 대한 연결을 보호할지 여부를 선택합니다.
+
** * 인증서 확인 * (기본값): AutoSupport 패키지 전송이 안전한지 확인합니다. NetApp 지원 인증서는 StorageGRID 소프트웨어와 함께 이미 설치되어 있습니다.
** 인증서 확인 안 함 *: 인증서에 일시적인 문제가 있는 경우와 같이 인증서 유효성 검사를 사용하지 않는 것이 좋은 경우에만 이 옵션을 선택합니다.


. 저장 * 을 선택합니다. 모든 주간, 사용자 트리거 및 이벤트 트리거 패키지는 선택한 프로토콜을 사용하여 전송됩니다.




== Weekly AutoSupport를 비활성화합니다

기본적으로 StorageGRID 시스템은 일주일에 한 번 AutoSupport 패키지를 기술 지원부로 보내도록 구성되어 있습니다.

주간 AutoSupport 패키지의 전송 시기를 결정하려면 * AutoSupport * > * 결과 * 탭으로 이동하십시오. Weekly AutoSupport * 섹션에서 * 다음 예약 시간 * 의 값을 확인합니다.

언제든지 주간 AutoSupport 패키지의 자동 전송을 비활성화할 수 있습니다.

.단계
. *지원* > *도구* > * AutoSupport* > *설정*을 선택하세요.
. Weekly AutoSupport * 활성화 확인란의 선택을 취소합니다.
. 저장 * 을 선택합니다.




== 이벤트가 트리거된 AutoSupport를 비활성화합니다

기본적으로 StorageGRID 시스템은 한 시간마다 AutoSupport 패키지를 기술 지원으로 보내도록 구성되어 있습니다.

이벤트에 의해 트리거되는 AutoSupport는 언제든지 비활성화할 수 있습니다.

.단계
. *지원* > *도구* > * AutoSupport* > *설정*을 선택하세요.
. 이벤트 트리거 AutoSupport* 활성화 확인란의 선택을 취소합니다.
. 저장 * 을 선택합니다.




== AutoSupport 온디맨드 를 활성화합니다

AutoSupport On Demand는 기술 지원이 활발하게 진행 중인 문제를 해결하는 데 도움이 될 수 있습니다.

기본적으로 AutoSupport On Demand는 비활성화되어 있습니다. 이 기능을 사용하도록 설정하면 기술 지원 부서에서 StorageGRID 시스템에 AutoSupport 패키지를 자동으로 보내도록 요청할 수 있습니다. 기술 지원 부서에서는 AutoSupport 주문형 쿼리에 대한 폴링 시간 간격을 설정할 수도 있습니다.

기술 지원 부서에서 AutoSupport On Demand를 활성화하거나 비활성화할 수 없습니다.

.단계
. *지원* > *도구* > * AutoSupport* > *설정*을 선택하세요.
. 프로토콜에 대해 * HTTPS * 를 선택합니다.
. Weekly AutoSupport * 활성화 확인란을 선택합니다.
. AutoSupport On Demand * 확인란을 선택합니다.
. 저장 * 을 선택합니다.
+
AutoSupport On Demand가 활성화되어 있으면 기술 지원 부서에서 AutoSupport On Demand 요청을 StorageGRID로 보낼 수 있습니다.





== 소프트웨어 업데이트 확인을 비활성화합니다

기본적으로 StorageGRID은 NetApp에 문의하여 사용 가능한 소프트웨어 업데이트가 있는지 확인합니다. StorageGRID 핫픽스 또는 새 버전을 사용할 수 있는 경우 새 버전이 StorageGRID 업그레이드 페이지에 표시됩니다.

필요에 따라 소프트웨어 업데이트 확인을 비활성화할 수도 있습니다. 예를 들어 시스템에 WAN 액세스가 없는 경우 다운로드 오류를 방지하려면 검사를 비활성화해야 합니다.

.단계
. *지원* > *도구* > * AutoSupport* > *설정*을 선택하세요.
. 소프트웨어 업데이트 확인 * 확인란의 선택을 취소합니다.
. 저장 * 을 선택합니다.




== AutoSupport 대상을 추가합니다

AutoSupport를 활성화하면 상태 패키지와 상태 패키지가 기술 지원으로 전송됩니다. 모든 AutoSupport 패키지에 대해 하나의 추가 대상을 지정할 수 있습니다.

AutoSupport 패키지 전송에 사용되는 프로토콜을 확인하거나 변경하려면 에 있는 지침을 참조하십시오<<specify-protocol-for-autosupport-packages,AutoSupport 패키지의 프로토콜을 지정합니다>>.


NOTE: SMTP 프로토콜을 사용하여 AutoSupport 패키지를 추가 대상으로 보낼 수 없습니다.

.단계
. *지원* > *도구* > * AutoSupport* > *설정*을 선택하세요.
. AutoSupport 대상 추가 활성화 * 를 선택합니다.
. 다음을 지정합니다.
+
호스트 이름:: 추가 AutoSupport 대상 서버의 서버 호스트 이름 또는 IP 주소입니다.
+
--

NOTE: 하나의 추가 대상만 입력할 수 있습니다.

--
포트:: 추가 AutoSupport 대상 서버에 연결하는 데 사용되는 포트입니다. 기본값은 HTTP의 경우 포트 80, HTTPS의 경우 포트 443입니다.
인증서 검증:: TLS 인증서를 사용하여 추가 대상에 대한 연결을 보호할지 여부를 나타냅니다.
+
--
** 인증서 유효성 검사를 사용하려면 * 인증서 확인 * 을 선택합니다.
** 인증서 확인 없이 AutoSupport 패키지를 보내려면 * 인증서 확인 안 함 * 을 선택합니다.
+
인증서에 일시적인 문제가 있는 경우와 같이 인증서 유효성 검사를 사용하지 않는 좋은 이유가 있는 경우에만 이 옵션을 선택합니다.



--


. 인증서 확인 * 을 선택한 경우 다음을 수행합니다.
+
.. CA 인증서의 위치를 찾습니다.
.. CA 인증서 파일을 업로드합니다.
+
CA 인증서 메타데이터가 나타납니다.



. 저장 * 을 선택합니다.
+
향후의 모든 주간, 이벤트 트리거 및 사용자 트리거 AutoSupport 패키지가 추가 대상으로 전송됩니다.





== [[autosupport-for-appliance]] 어플라이언스에 대해 AutoSupport를 구성합니다

어플라이언스용 AutoSupport가 StorageGRID 하드웨어 문제를 보고하며 StorageGRID AutoSupport은 StorageGRID 소프트웨어 문제를 보고하지만, SGF6112의 경우 StorageGRID AutoSupport에서 하드웨어 및 소프트웨어 문제를 모두 보고합니다. 추가 구성이 필요하지 않은 SGF6112를 제외하고 각 어플라이언스에서 AutoSupport을 구성해야 합니다. AutoSupport는 서비스 어플라이언스와 스토리지 어플라이언스에 대해 서로 다르게 구현됩니다.

SANtricity를 사용하여 각 스토리지 어플라이언스에 대해 AutoSupport를 사용하도록 설정할 수 있습니다. 초기 어플라이언스 설정 중 또는 어플라이언스 설치 후 SANtricity AutoSupport를 구성할 수 있습니다.

* SG6000 및 SG5700 어플라이언스의 경우, https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/accessing-and-configuring-santricity-system-manager.html["SANtricity 시스템 관리자에서 AutoSupport를 구성합니다"^]


에서 AutoSupport 제공을 프록시 구성하는 경우 E-Series 어플라이언스의 AutoSupport 패키지를 StorageGRID AutoSupport에 포함할 수 link:../admin/sending-eseries-autosupport-messages-through-storagegrid.html["SANtricity 시스템 관리자"]있습니다.

StorageGRID AutoSupport은 DIMM 또는 HIC(호스트 인터페이스 카드) 오류와 같은 하드웨어 문제를 보고하지 않습니다. 하지만 일부 구성 요소 장애가 트리거될 수 link:../monitor/alerts-reference.html["하드웨어 경고"]있습니다. BMC(베이스보드 관리 컨트롤러)가 있는 StorageGRID 어플라이언스의 경우 e-메일 및 SNMP 트랩을 구성하여 하드웨어 오류를 보고할 수 있습니다.

* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/setting-up-email-notifications-for-alerts.html["BMC 알림에 대한 이메일 알림을 설정합니다"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/configuring-snmp-settings-for-bmc.html["BMC에 대한 SNMP 설정을 구성합니다"^]


.관련 정보
https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"^]
