---
permalink: admin/controlling-access-through-firewalls.html 
sidebar: sidebar 
keywords: firewall access, firewall ports, external firewall 
summary: 외부 방화벽에서 특정 포트를 열거나 닫을 수 있습니다. 
---
= 외부 방화벽에서 액세스를 제어합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
외부 방화벽에서 특정 포트를 열거나 닫을 수 있습니다.

외부 방화벽에서 특정 포트를 열거나 닫아 StorageGRID 관리 노드의 사용자 인터페이스 및 API에 대한 액세스를 제어할 수 있습니다. 예를 들어, 테넌트가 다른 방법을 사용하여 시스템 액세스를 제어하는 것 외에도 방화벽에서 Grid Manager에 연결할 수 없도록 할 수 있습니다.

StorageGRID 내부 방화벽을 구성하려면 를 참조하십시오link:../admin/configure-firewall-controls.html["내부 방화벽을 구성합니다"].

[cols="1a,1a,2a"]
|===
| 포트 | 설명 | 포트가 열려 있는 경우... 


 a| 
443
 a| 
관리 노드의 기본 HTTPS 포트
 a| 
웹 브라우저 및 관리 API 클라이언트는 Grid Manager, Grid Management API, Tenant Manager 및 Tenant Management API에 액세스할 수 있습니다.

* 참고: * 포트 443은 일부 내부 트래픽에도 사용됩니다.



 a| 
8443
 a| 
관리 노드의 제한된 그리드 관리자 포트
 a| 
* 웹 브라우저 및 관리 API 클라이언트는 HTTPS를 사용하여 그리드 관리자 및 그리드 관리 API에 액세스할 수 있습니다.
* 웹 브라우저 및 관리 API 클라이언트는 테넌트 관리자 또는 테넌트 관리 API에 액세스할 수 없습니다.
* 내부 콘텐츠 요청은 거부됩니다.




 a| 
9443
 a| 
관리 노드의 제한된 테넌트 관리자 포트
 a| 
* 웹 브라우저 및 관리 API 클라이언트는 HTTPS를 사용하여 테넌트 관리자 및 테넌트 관리 API에 액세스할 수 있습니다.
* 웹 브라우저 및 관리 API 클라이언트는 그리드 관리자 또는 그리드 관리 API에 액세스할 수 없습니다.
* 내부 콘텐츠 요청은 거부됩니다.


|===

TIP: 제한된 Grid Manager 또는 테넌트 관리자 포트에서는 SSO(Single Sign-On)를 사용할 수 없습니다. 사용자가 SSO(Single Sign-On)로 인증하도록 하려면 기본 HTTPS 포트(443)를 사용해야 합니다.

.관련 정보
* link:signing-in-to-grid-manager.html["Grid Manager에 로그인합니다"]
* link:creating-tenant-account.html["테넌트 계정을 생성합니다"]
* link:../network/external-communications.html["외부 통신"]

