---
permalink: admin/controlling-storagegrid-access.html 
sidebar: sidebar 
keywords: administrator access, single sign on, sso, users, groups, client certificates, passwords, passphrase 
summary: '그룹 및 사용자를 만들거나 가져오고 각 그룹에 권한을 할당하여 StorageGRID에 액세스할 수 있는 사용자와 사용자가 수행할 수 있는 작업을 제어할 수 있습니다. 선택적으로 SSO(Single Sign-On)\(SSO\)를 활성화하고, 클라이언트 인증서를 생성하고, 그리드 암호를 변경할 수 있습니다.' 
---
= StorageGRID 액세스를 제어합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그룹 및 사용자를 만들거나 가져오고 각 그룹에 권한을 할당하여 StorageGRID에 액세스할 수 있는 사용자와 사용자가 수행할 수 있는 작업을 제어할 수 있습니다. 선택적으로 SSO(Single Sign-On)를 활성화하고, 클라이언트 인증서를 생성하고, 그리드 암호를 변경할 수 있습니다.



== 그리드 관리자에 대한 액세스를 제어합니다

ID 페더레이션 서비스에서 그룹과 사용자를 가져오거나 로컬 그룹 및 로컬 사용자를 설정하여 Grid Manager 및 Grid Management API에 액세스할 수 있는 사용자를 결정합니다.

을 link:using-identity-federation.html["ID 제휴"] 사용하면 설정이 link:managing-admin-groups.html["그룹"] link:managing-users.html["사용자"]빨라지고 사용자가 친숙한 자격 증명을 사용하여 StorageGRID에 로그인할 수 있습니다. Active Directory, OpenLDAP 또는 Oracle Directory Server를 사용하는 경우 ID 페더레이션을 구성할 수 있습니다.


NOTE: 다른 LDAP v3 서비스를 사용하려면 기술 지원 부서에 문의하십시오.

각 그룹에 다른 작업을 할당하여 각 사용자가 수행할 수 있는 작업을 link:admin-group-permissions.html["권한"]결정합니다. 예를 들어 한 그룹의 사용자가 ILM 규칙 및 다른 그룹의 사용자를 관리하여 유지 관리 작업을 수행할 수 있도록 할 수 있습니다. 시스템에 액세스하려면 사용자가 하나 이상의 그룹에 속해 있어야 합니다.

선택적으로 그룹을 읽기 전용으로 구성할 수 있습니다. 읽기 전용 그룹의 사용자는 설정과 기능만 볼 수 있습니다. 그리드 관리자 또는 그리드 관리 API에서 어떠한 변경이나 작업도 수행할 수 없습니다.



== SSO(Single Sign-On)를 활성화합니다

StorageGRID 시스템은 SAML 2.0(Security Assertion Markup Language 2.0) 표준을 사용하여 SSO(Single Sign-On)를 지원합니다. 그런 다음 link:configuring-sso.html["SSO를 구성하고 사용하도록 설정합니다"]모든 사용자가 그리드 관리자, 테넌트 관리자, 그리드 관리 API 또는 테넌트 관리 API에 액세스하기 전에 외부 ID 공급자에 의해 인증되어야 합니다. 로컬 사용자는 StorageGRID에 로그인할 수 없습니다.



== 프로비저닝 암호를 변경합니다

프로비저닝 암호는 많은 설치 및 유지 관리 절차와 StorageGRID 복구 패키지 다운로드에 필요합니다. 또한 StorageGRID 시스템에 대한 그리드 토폴로지 정보와 암호화 키의 백업을 다운로드하려면 암호문도 필요합니다. 필요에 따라 할 수 link:changing-provisioning-passphrase.html["암호를 변경합니다"]있습니다.



== 노드 콘솔 암호를 변경합니다

그리드의 각 노드에는 고유한 노드 콘솔 암호가 있습니다. 이 암호는 SSH를 사용하여 노드에 "admin"으로 로그인하거나 VM/물리적 콘솔 연결의 루트 사용자에게 로그인해야 합니다. 필요한 경우 각 노드에 대해 수행할 수 link:change-node-console-password.html["노드 콘솔 암호를 변경합니다"]있습니다.
