---
permalink: admin/creating-tenant-account.html 
sidebar: sidebar 
keywords: create tenant, tenant account 
summary: StorageGRID 시스템의 스토리지에 대한 액세스를 제어하려면 하나 이상의 테넌트 계정을 생성해야 합니다. 
---
= 테넌트 계정을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템의 스토리지에 대한 액세스를 제어하려면 하나 이상의 테넌트 계정을 생성해야 합니다.

테넌트 계정을 만드는 단계는 및 link:configuring-sso.html["SSO(Single Sign-On)"] 의 구성 여부와 테넌트 계정을 만드는 데 사용하는 그리드 관리자 계정이 루트 액세스 권한이 있는 관리자 그룹에 속하는지 여부에 따라 link:using-identity-federation.html["ID 제휴"]다릅니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:admin-group-permissions.html["루트 액세스 또는 테넌트 계정 권한"]있습니다.
* 테넌트 계정에서 Grid Manager에 대해 구성된 ID 소스를 사용하고 테넌트 계정에 대한 루트 액세스 권한을 통합 그룹에 부여하려는 경우 해당 통합 그룹을 Grid Manager로 가져온 것입니다. 이 관리 그룹에 그리드 관리자 권한을 할당할 필요가 없습니다. 을 link:managing-admin-groups.html["관리 그룹을 관리합니다"]참조하십시오.
* S3 테넌트가 계정 데이터를 복제하고 그리드 통합 연결을 사용하여 버킷 오브젝트를 다른 그리드에 복제하도록 허용하려면
+
** 있습니다. link:grid-federation-create-connection.html["그리드 페더레이션 연결을 구성했습니다"]
** 연결 상태는 * 연결됨 * 입니다.
** 루트 액세스 권한이 있습니다.
** 에 대한 고려 사항을 검토했습니다.link:grid-federation-manage-tenants.html["그리드 페더레이션에 허용된 테넌트 관리"]
** 테넌트 계정에서 Grid Manager용으로 구성된 ID 소스를 사용할 경우 동일한 통합 그룹을 두 그리드의 Grid Manager로 가져왔습니다.
+
테넌트를 생성할 때 소스 및 대상 테넌트 계정에 대한 초기 루트 액세스 권한을 가지려면 이 그룹을 선택합니다.

+

TIP: 이 관리 그룹이 테넌트를 생성하기 전에 두 그리드에 없는 경우 테넌트는 대상에 복제되지 않습니다.







== 마법사에 액세스합니다

.단계
. Tenants * 를 선택합니다.
. Create * 를 선택합니다.




== 세부 정보를 입력합니다

.단계
. 테넌트에 대한 세부 정보를 입력합니다.
+
[cols="1a,3a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
이름
 a| 
테넌트 계정의 이름입니다. 테넌트 이름은 고유해야 할 필요가 없습니다. 테넌트 계정이 생성되면 고유한 20자리 계정 ID를 받습니다.



 a| 
설명(선택 사항)
 a| 
테넌트를 식별하는 데 도움이 되는 설명입니다.

그리드 페더레이션 연결을 사용할 테넌트를 생성하는 경우 이 필드를 사용하여 소스 테넌트인지 대상 테넌트인지 확인할 수 있습니다. 예를 들어 그리드 1에서 생성된 테넌트에 대한 이 설명은 그리드 2에 복제된 테넌트에 대해서도 나타납니다. "이 테넌트는 그리드 1에 생성되었습니다."



 a| 
클라이언트 유형입니다
 a| 
이 테넌트가 사용할 클라이언트 프로토콜 유형으로 * S3 * 또는 * Swift * 가 있습니다.

* 참고 *: Swift 클라이언트 응용 프로그램에 대한 지원은 더 이상 사용되지 않으며 향후 릴리스에서 제거될 예정입니다.



 a| 
스토리지 할당량(선택 사항)
 a| 
이 테넌트에 스토리지 할당량을 사용하려면 할당량과 유닛에 대한 숫자 값입니다.

|===
. Continue * 를 선택합니다.




== [[admin-tenant-select-permissions]] 권한을 선택합니다

.단계
. 필요에 따라 이 테넌트에 부여할 기본 권한을 선택합니다.
+

NOTE: 이러한 권한 중 일부는 추가 요구 사항이 있습니다. 자세한 내용을 보려면 각 권한에 대한 도움말 아이콘을 선택합니다.

+
[cols="1a,3a"]
|===
| 권한 | 선택한 경우... 


 a| 
플랫폼 서비스를 허용합니다
 a| 
테넌트는 CloudMirror와 같은 S3 플랫폼 서비스를 사용할 수 있습니다. 을 link:../admin/manage-platform-services-for-tenants.html["S3 테넌트 계정에 대한 플랫폼 서비스 관리"]참조하십시오.



 a| 
고유 ID 소스를 사용합니다
 a| 
테넌트는 통합 그룹 및 사용자에 대한 자체 ID 소스를 구성하고 관리할 수 있습니다. 이 옵션은 StorageGRID 시스템에 대해 비활성화되어 link:../admin/configuring-sso.html["SSO를 구성했습니다"]있습니다.



 a| 
S3 선택 허용
 a| 
테넌트는 오브젝트 데이터를 필터링하고 검색하기 위해 S3 SelectObjectContent API 요청을 실행할 수 있습니다. 을 link:../admin/manage-s3-select-for-tenant-accounts.html["관리 S3 테넌트 계정에 대해 선택"]참조하십시오.

* 중요 *: SelectObjectContent 요청은 모든 S3 클라이언트 및 모든 테넌트의 로드 밸런서 성능을 감소시킬 수 있습니다. 신뢰할 수 있는 테넌트에만 필요한 경우에만 이 기능을 사용하도록 설정합니다.

|===
. 필요에 따라 이 테넌트에 부여할 고급 권한을 선택합니다.
+
[cols="1a,3a"]
|===
| 권한 | 선택한 경우... 


 a| 
그리드 페더레이션 연결
 a| 
테넌트는 다음과 같은 그리드 페더레이션 연결을 사용할 수 있습니다.

** 이 테넌트 및 계정에 추가된 모든 테넌트 그룹 및 사용자가 이 그리드(_source grid_)에서 선택한 연결의 다른 그리드(_destination grid_)로 복제되도록 합니다.
** 이 테넌트가 각 그리드의 해당 버킷 간에 교차 그리드 복제를 구성할 수 있도록 허용합니다.


을 link:../admin/grid-federation-manage-tenants.html["그리드 페더레이션을 위해 허용된 테넌트를 관리합니다"]참조하십시오.



 a| 
S3 오브젝트 잠금
 a| 
테넌트가 S3 오브젝트 잠금의 특정 기능을 사용하도록 허용:

** * 최대 보존 기간 설정 * 이 버킷에 추가된 새 객체가 수집된 시점부터 유지되는 기간을 정의합니다.
** * Allow compliance mode * 는 사용자가 보존 기간 동안 보호된 객체 버전을 덮어쓰거나 삭제할 수 없도록 합니다.


|===
. Continue * 를 선택합니다.




== 루트 액세스를 정의하고 테넌트를 생성합니다

.단계
. StorageGRID 시스템에서 ID 페더레이션, SSO(Single Sign-On) 또는 둘 다를 사용하는지 여부에 따라 테넌트 계정에 대한 루트 액세스를 정의합니다.
+
[cols="1a,2a"]
|===
| 옵션을 선택합니다 | 이렇게 하십시오 


 a| 
ID 페더레이션이 활성화되지 않은 경우
 a| 
테넌트에 로컬 루트 사용자로 로그인할 때 사용할 암호를 지정합니다.



 a| 
ID 페더레이션이 활성화된 경우
 a| 
.. 테넌트에 대한 루트 액세스 권한이 있는 기존 통합 그룹을 선택합니다.
.. 필요에 따라 테넌트에 로컬 루트 사용자로 로그인할 때 사용할 암호를 지정합니다.




 a| 
ID 페더레이션 및 SSO(Single Sign-On)가 모두 활성화된 경우
 a| 
테넌트에 대한 루트 액세스 권한이 있는 기존 통합 그룹을 선택합니다. 로컬 사용자는 로그인할 수 없습니다.

|===
. 테넌트 생성 * 을 선택합니다.
+
성공 메시지가 나타나고 새 테넌트가 테넌트 페이지에 나열됩니다. 테넌트 세부 정보를 보고 테넌트 활동을 모니터링하는 방법에 대한 자세한 내용은 을 참조하십시오link:../monitor/monitoring-tenant-activity.html["테넌트 작업을 모니터링합니다"].

+

NOTE: 네트워크 연결, 노드 상태 및 Cassandra 작업에 따라 그리드 전체에 테넌트 설정을 적용하는 데 15분 이상이 걸릴 수 있습니다.

. 테넌트에 대해 * 그리드 페더레이션 연결 사용 * 권한을 선택한 경우:
+
.. 동일한 테넌트가 연결의 다른 그리드에 복제되었는지 확인합니다. 두 그리드의 테넌트는 동일한 20자리 계정 ID, 이름, 설명, 할당량 및 권한을 갖습니다.
+

NOTE: "Tenant created without a clone"이라는 오류 메시지가 나타나면 의 지침을 참조하십시오link:grid-federation-troubleshoot.html["그리드 통합 오류 문제 해결"].

.. 복제된 테넌트에 대해 루트 액세스를 정의할 때 로컬 루트 사용자 암호를 제공한 경우link:changing-password-for-tenant-local-root-user.html["로컬 루트 사용자의 암호를 변경합니다"]
+

TIP: 로컬 루트 사용자는 암호가 변경될 때까지 대상 그리드의 테넌트 관리자에 로그인할 수 없습니다.







== 테넌트에 로그인(선택 사항)

필요에 따라 새 테넌트에 지금 로그인하여 구성을 완료하거나 나중에 테넌트에 로그인할 수 있습니다. 로그인 단계는 기본 포트(443) 또는 제한된 포트를 사용하여 Grid Manager에 로그인했는지 여부에 따라 달라집니다. 을 link:controlling-access-through-firewalls.html["외부 방화벽에서 액세스를 제어합니다"]참조하십시오.



=== 지금 로그인하십시오

[cols="1a,3a"]
|===
| 사용 중인 경우... | 수행할 작업... 


 a| 
포트 443을 사용하여 로컬 루트 사용자의 암호를 설정합니다
 a| 
. root로 로그인 * 을 선택합니다.
+
로그인하면 버킷, ID 통합, 그룹 및 사용자를 구성하기 위한 링크가 나타납니다.

. 테넌트 계정을 구성할 링크를 선택합니다.
+
각 링크는 테넌트 관리자에서 해당 페이지를 엽니다. 페이지를 완료하려면 을 참조하십시오link:../tenant/index.html["테넌트 계정 사용 지침"].





 a| 
포트 443을 사용하고 로컬 루트 사용자의 암호를 설정하지 않았습니다
 a| 
로그인 * 을 선택하고 루트 액세스 통합 그룹에 사용자의 자격 증명을 입력합니다.



 a| 
제한된 포트
 a| 
. 마침 * 을 선택합니다
. 테넌트 테이블에서 * 제한 * 을 선택하여 이 테넌트 계정에 액세스하는 방법에 대해 자세히 알아보십시오.
+
테넌트 관리자의 URL 형식은 다음과 같습니다.

+
`https://_FQDN_or_Admin_Node_IP:port_/?accountId=_20-digit-account-id_/`

+
** `_FQDN_or_Admin_Node_IP_` 은 관리자 노드의 정규화된 도메인 이름 또는 IP 주소입니다
** `_port_` 는 테넌트 전용 포트입니다
** `_20-digit-account-id_` 테넌트의 고유 계정 ID입니다




|===


=== 나중에 로그인하십시오

[cols="1a,3a"]
|===
| 사용 중인 경우... | 다음 중 하나를 수행합니다. 


 a| 
포트 443
 a| 
* Grid Manager에서 * Tenants * 를 선택하고 테넌트 이름 오른쪽에 있는 * 로그인 * 을 선택합니다.
* 웹 브라우저에 테넌트의 URL을 입력합니다.
+
`https://_FQDN_or_Admin_Node_IP_/?accountId=_20-digit-account-id_/`

+
** `_FQDN_or_Admin_Node_IP_` 은 관리자 노드의 정규화된 도메인 이름 또는 IP 주소입니다
** `_20-digit-account-id_` 테넌트의 고유 계정 ID입니다






 a| 
제한된 포트
 a| 
* Grid Manager에서 * Tenants * 를 선택하고 * Restricted * 를 선택합니다.
* 웹 브라우저에 테넌트의 URL을 입력합니다.
+
`https://_FQDN_or_Admin_Node_IP:port_/?accountId=_20-digit-account-id_`

+
** `_FQDN_or_Admin_Node_IP_` 은 관리자 노드의 정규화된 도메인 이름 또는 IP 주소입니다
** `_port_` 는 테넌트 전용 제한된 포트입니다
** `_20-digit-account-id_` 테넌트의 고유 계정 ID입니다




|===


== 테넌트를 구성합니다

의 지침에 따라 link:../tenant/index.html["테넌트 계정을 사용합니다"]테넌트 그룹 및 사용자, S3 액세스 키, 버킷, 플랫폼 서비스, 계정 클론 및 그리드 간 복제를 관리합니다.
