---
permalink: admin/creating-traffic-classification-policies.html 
sidebar: sidebar 
keywords: traffic classification, network traffic, traffic limits, policy 
summary: 버킷, 테넌트, IP 서브넷 또는 로드 밸런서 끝점별로 네트워크 트래픽을 모니터링하고 선택적으로 제한하려는 경우 트래픽 분류 정책을 생성합니다. 필요에 따라 대역폭, 동시 요청 수 또는 요청 속도를 기준으로 정책에 대한 제한을 설정할 수 있습니다. 
---
= 트래픽 분류 정책을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
트래픽 분류 정책을 생성하고 버킷, 버킷 regex, CIDR, 부하 분산 단말 장치 또는 테넌트별로 네트워크 트래픽을 선택적으로 제한할 수 있습니다. 필요에 따라 대역폭, 동시 요청 수 또는 요청 속도를 기준으로 정책에 대한 제한을 설정할 수 있습니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:admin-group-permissions.html["루트 액세스 권한"]있습니다.
* 일치시킬 로드 밸런서 끝점을 만들었습니다.
* 일치시킬 테넌트를 만들었습니다.


.단계
. *구성* > *네트워크* > *트래픽 분류*를 선택합니다.
. Create * 를 선택합니다.
. 정책의 이름과 설명(선택 사항)을 입력하고 * Continue * 를 선택합니다.
+
예를 들어, 이 트래픽 분류 정책이 적용되는 대상 및 제한할 내용에 대해 설명하십시오.

. 규칙 추가 * 를 선택하고 다음 세부 정보를 지정하여 정책에 일치하는 규칙을 하나 이상 만듭니다. 생성하는 모든 정책에는 하나 이상의 일치하는 규칙이 있어야 합니다. Continue * 를 선택합니다.
+
[cols="1a,3a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
유형
 a| 
일치하는 규칙이 적용되는 트래픽 유형을 선택합니다. 트래픽 유형은 버킷, 버킷 regex, CIDR, 부하 분산 단말 장치 및 테넌트입니다.



 a| 
일치 값
 a| 
선택한 유형과 일치하는 값을 입력합니다.

** 버킷: 하나 이상의 버킷 이름을 입력합니다.
** 버킷 정규식: 버킷 이름 집합과 일치하는 데 사용되는 하나 이상의 정규식을 입력합니다.
+
정규식이 고정 해제됩니다. ^anchor를 사용하여 버킷 이름의 시작 부분에 일치시키고 $ anchor를 사용하여 이름 끝에 일치시킵니다. 정규식 일치는 PCRE(Perl 호환 정규식) 구문의 하위 집합을 지원합니다.

** CIDR: 원하는 서브넷과 일치하는 하나 이상의 IPv4 서브넷을 CIDR 표기법으로 입력합니다.
** 로드 밸런서 끝점: 끝점 이름을 선택합니다. 에서 정의한 로드 밸런서 엔드포인트입니다.link:../admin/configuring-load-balancer-endpoints.html["로드 밸런서 엔드포인트를 구성합니다"]
** 테넌트: 테넌트 일치는 액세스 키 ID를 사용합니다. 요청에 액세스 키 ID(예: 익명 액세스)가 없으면 액세스한 버킷의 소유권이 테넌트를 결정하는 데 사용됩니다.




 a| 
역일치
 a| 
방금 정의한 유형 및 일치 값과 일치하는 모든 network traffic_except_traffic을 일치시키려면 * 역일치 * 확인란을 선택합니다. 그렇지 않으면 확인란을 선택하지 않은 상태로 둡니다.

예를 들어, 이 정책이 로드 밸런서 끝점 중 하나를 제외한 모든 항목에 적용되도록 하려면 제외할 로드 밸런서 끝점을 지정하고 * 역일치 * 를 선택합니다.

하나 이상의 교자가 역마쳐인 여러 마처를 포함하는 정책의 경우 모든 요청과 일치하는 정책을 만들지 않도록 주의하십시오.

|===
. 필요에 따라 * 제한 추가 * 를 선택하고 다음 세부 정보를 선택하여 규칙에 일치하는 네트워크 트래픽을 제어하는 하나 이상의 제한을 추가합니다.
+

NOTE: StorageGRID는 제한을 추가하지 않아도 메트릭을 수집하므로 트래픽 추세를 파악할 수 있습니다.

+
[cols="1a,3a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
유형
 a| 
규칙에 일치하는 네트워크 트래픽에 적용할 제한 유형입니다. 예를 들어, 대역폭 또는 요청 속도를 제한할 수 있습니다.

* 참고 *: 정책을 작성하여 총 대역폭을 제한하거나 요청 당 대역폭을 제한할 수 있습니다. 그러나 StorageGRID는 두 가지 유형의 대역폭을 동시에 제한할 수 없습니다. 애그리게이트 대역폭이 사용 중인 경우 요청당 대역폭을 사용할 수 없습니다. 반대로, 요청 당 대역폭이 사용 중일 때는 총 대역폭을 사용할 수 없습니다. 애그리게이트 대역폭 제한은 제한 없는 트래픽에 약간의 성능 영향을 줄 수 있습니다.

대역폭 제한에 대해 StorageGRID는 설정된 제한 유형과 가장 일치하는 정책을 적용합니다. 예를 들어, 트래픽을 한 방향으로만 제한하는 정책이 있는 경우 대역폭 제한이 있는 추가 정책과 일치하는 트래픽이 있더라도 반대 방향의 트래픽은 무제한입니다. StorageGRID는 대역폭 제한에 대해 다음 순서로 "가장 적합한" 일치 항목을 구현합니다.

** 정확한 IP 주소(/32 마스크)
** 정확한 버킷 이름입니다
** 버킷 regex
** 테넌트
** 엔드포인트
** 일치하지 않는 CIDR 일치(NOT/32)
** 역 일치




 a| 
적용 대상
 a| 
이 제한이 클라이언트 읽기 요청(GET 또는 HEAD) 또는 쓰기 요청(PUT, POST 또는 DELETE)에 적용될지 여부를 나타냅니다.



 a| 
값
 a| 
선택한 장치에 따라 네트워크 트래픽이 로 제한됩니다. 예를 들어, 10을 입력하고 MiB/s를 선택하면 이 규칙에 일치하는 네트워크 트래픽이 10MiB/s를 초과하지 않습니다

* 참고 *: 단위 설정에 따라 사용 가능한 단위는 2진수(예: GiB) 또는 10진수(예: GB)가 됩니다. 단위 설정을 변경하려면 그리드 관리자 오른쪽 상단의 사용자 드롭다운을 선택한 다음 * 사용자 기본 설정 * 을 선택합니다.



 a| 
단위
 a| 
입력한 값을 설명하는 단위입니다.

|===
+
예를 들어, SLA 계층에 대해 4GB/s 대역폭 제한을 생성하려면 GET/HEAD(4GB/s) 및 PUT/POST/DELETE(4GB/s)의 두 가지 집계 대역폭 제한을 생성합니다.

. Continue * 를 선택합니다.
. 트래픽 분류 정책을 읽고 검토하십시오. Previous * (이전 *) 버튼을 사용하여 돌아가서 필요에 따라 변경합니다. 정책에 만족하면 * Save and continue * 를 선택합니다.
+
이제 S3 클라이언트 트래픽이 트래픽 분류 정책에 따라 처리됩니다.



.작업을 마친 후
link:viewing-network-traffic-metrics.html["네트워크 트래픽 메트릭을 확인합니다"] 정책이 예상한 트래픽 제한을 적용하고 있는지 확인합니다.
