---
permalink: admin/deactivate-features-from-api.html 
sidebar: sidebar 
keywords: deactivate features from api 
summary: 그리드 관리 API를 사용하여 StorageGRID 시스템의 특정 기능을 완전히 비활성화할 수 있습니다. 기능이 비활성화되면 해당 기능과 관련된 작업을 수행할 수 있는 권한을 아무도 할당할 수 없습니다. 
---
= API를 사용하여 기능을 비활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리 API를 사용하여 StorageGRID 시스템의 특정 기능을 완전히 비활성화할 수 있습니다. 기능이 비활성화되면 해당 기능과 관련된 작업을 수행할 수 있는 권한을 아무도 할당할 수 없습니다.

.이 작업에 대해
비활성화된 기능 시스템을 사용하면 StorageGRID 시스템의 특정 기능에 액세스하지 못하게 할 수 있습니다. 루트 사용자 또는 * 루트 액세스 * 권한이 있는 관리자 그룹에 속한 사용자가 해당 기능을 사용할 수 없도록 하는 유일한 방법은 기능을 비활성화하는 것입니다.

이 기능이 어떻게 유용한지 이해하려면 다음 시나리오를 고려해 보십시오.

_Company A는 테넌트 계정을 생성하여 StorageGRID 시스템의 스토리지 용량을 임대하는 서비스 공급자입니다. 회사 A는 임차자의 객체 보안을 보호하기 위해 계정이 배포된 후 자신의 직원이 테넌트 계정에 액세스할 수 없도록 하려고 합니다. _

_회사 A는 그리드 관리 API에서 기능 비활성화 시스템을 사용하여 이 목표를 달성할 수 있습니다. 그리드 관리자에서 * 테넌트 루트 암호 변경 * 기능을 완전히 비활성화함으로써(UI 및 API 모두) 회사 A는 루트 사용자 및 * 루트 액세스 * 권한을 가진 그룹에 속한 사용자를 포함하여 관리자 사용자가 테넌트 계정의 루트 사용자에 대한 암호를 변경할 수 없도록 합니다

.단계
. Grid Management API에 대한 Swagger 문서에 액세스합니다. 을 link:using-grid-management-api.html["Grid Management API를 사용합니다"]참조하십시오.
. 기능 비활성화 끝점을 찾습니다.
. 테넌트 루트 암호 변경 등의 기능을 비활성화하려면 다음과 같이 API로 본문을 보냅니다.
+
`{ "grid": {"changeTenantRootPassword": true} }`

+
요청이 완료되면 테넌트 루트 암호 변경 기능이 비활성화됩니다. 테넌트 루트 암호 변경 * 관리 권한이 더 이상 사용자 인터페이스에 표시되지 않으며 테넌트의 루트 암호를 변경하려고 시도하는 모든 API 요청이 "403 사용 권한 없음"과 함께 실패합니다.





== 비활성화된 피처를 다시 활성화합니다

기본적으로 그리드 관리 API를 사용하여 비활성화된 기능을 다시 활성화할 수 있습니다. 그러나 비활성화된 피처가 다시 활성화되지 않도록 하려면 * activateFeatures * 기능 자체를 비활성화할 수 있습니다.


CAUTION: activateFeatures * 기능을 다시 활성화할 수 없습니다. 이 기능을 비활성화하려는 경우 비활성화된 다른 모든 기능을 다시 활성화할 수 있는 기능이 영구적으로 손실됩니다. 손실된 기능을 복원하려면 기술 지원 부서에 문의해야 합니다.

.단계
. Grid Management API에 대한 Swagger 문서에 액세스합니다.
. 기능 비활성화 끝점을 찾습니다.
. 모든 기능을 다시 활성화하려면 다음과 같이 API로 본문을 보내십시오.
+
`{ "grid": null }`

+
이 요청이 완료되면 테넌트 루트 암호 변경 기능을 포함한 모든 기능이 다시 활성화됩니다. 이제 사용자 인터페이스에 * 테넌트 루트 암호 변경 * 관리 권한이 표시되며, 사용자에게 * 루트 액세스 * 또는 * 테넌트 루트 암호 변경 * 관리 권한이 있는 경우 테넌트의 루트 암호를 변경하려고 시도하는 모든 API 요청이 성공합니다.




TIP: 이전 예에서는 _ALL_DEACTED 피처가 재활성화됩니다. 비활성화된 상태로 유지되어야 하는 다른 기능이 비활성화된 경우, PUT 요청에 명시적으로 지정해야 합니다. 예를 들어 테넌트 루트 암호 변경 기능을 다시 활성화하고 StorageAdmin 관리 권한을 계속 비활성화하려면 다음 PUT 요청을 보내십시오. +
`{ "grid": {"storageAdmin": true} }`
