---
permalink: admin/enable-cross-origin-resource-sharing-for-management-interface.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors, management, api, domain 
summary: '다른 도메인의 관리 API를 사용하여 StorageGRID 의 데이터에 액세스할 수 있도록 하려면 StorageGRID 에 대한 관리 API 요청에 대해 CORS(교차 출처 리소스 공유)를 활성화할 수 있습니다.' 
---
= 관리 인터페이스에 StorageGRID CORS 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리자는 StorageGRID 에 대한 관리 API 요청에 대해 CORS(교차 출처 리소스 공유)를 활성화하여 다른 도메인의 관리 API를 사용하여 StorageGRID 의 데이터에 액세스할 수 있도록 할 수 있습니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 그만큼link:../tenant/tenant-management-permissions.html["루트 액세스 권한"] 모든 CORS 구성 요청에 대한 액세스를 제공합니다.


.이 작업에 대해
CORS는 한 도메인의 클라이언트 웹 애플리케이션이 다른 도메인의 리소스에 액세스할 수 있도록 하는 보안 메커니즘입니다.  예를 들어, 도메인에서 StorageGRID 에 대한 모니터링 대시보드를 구축하려고 한다고 가정해 보겠습니다. `\http://www.example.com` .  StorageGRID 에서 CORS를 활성화하여 `\http://www.example.com` 그리고 "Grid Manager", StorageGRID 도메인은 Grid Management API 요청에 응답합니다. `\http://www.example.com` .

관리 API(mgmt-api) 요청 `application/json` 또는 `multipart/formdata` 요청 `Content-Type` CORS가 지원됩니다.

.단계
. Grid Manager에서 *구성* > *네트워크* > *관리 인터페이스 CORS 설정*으로 이동합니다.
. *그리드 관리자*, *테넌트 관리자* 또는 두 옵션을 모두 선택하세요.
+
** *그리드 관리자*: 크로스 도메인 그리드 관리 API 요청에 대해 CORS를 활성화합니다.
** *테넌트 관리자*: 크로스 도메인 테넌트 관리 API 요청에 대해 CORS를 활성화합니다.


. *도메인* 필드에 다른 도메인의 URL을 입력합니다.
+
StorageGRID 에서 두 개 이상의 도메인에 대해 CORS를 활성화하려면 *다른 도메인 추가*를 선택하세요.

. 저장 * 을 선택합니다.


.관련 정보
link:../tenant/configuring-cross-origin-resource-sharing-for-buckets-and-objects.html["버킷 및 객체에 대한 StorageGRID CORS 구성"]
