---
permalink: admin/grid-management-api-operations.html 
sidebar: sidebar 
keywords: Grid Management API,  API operations 
summary: Grid Management API는 사용 가능한 API 작업을 다음 섹션으로 구성합니다. 
---
= Grid Management API 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Grid Management API는 사용 가능한 작업을 다음 섹션으로 구성합니다.


NOTE: 이 목록에는 공용 API에서 사용할 수 있는 작업만 포함됩니다.

* * ACCOUNT *: 새 계정 생성 및 지정된 계정의 스토리지 사용량 검색을 포함하여 스토리지 테넌트 계정을 관리하는 작업입니다.
* * alert-history *: 해결된 알림의 작업.
* 알림 메시지 수신자 *: 경고 알림 수신자(이메일)에 대한 작업.
* * alert-rules *: 경고 규칙에 대한 작업.
* * alert-silences *: 경고 작동 중.
* * 경고 *: 경고 작업.
* * 감사 *: 감사 구성을 나열하고 업데이트하는 작업.
* * auth *: 사용자 세션 인증을 수행하기 위한 작업.
+
Grid Management API는 Bearer Token Authentication Scheme을 지원한다. 로그인하려면 인증 요청의 JSON 본문에 사용자 이름과 암호를 입력합니다(즉, `POST /api/v3/authorize`). 사용자가 성공적으로 인증되면 보안 토큰이 반환됩니다. 이 토큰은 후속 API 요청 헤더("Authorization:Bearer_token_")에 제공되어야 합니다. 토큰은 16시간 후에 만료됩니다.

+

NOTE: StorageGRID 시스템에 대해 Single Sign-On이 활성화된 경우 인증을 위해 다른 단계를 수행해야 합니다. "SSO(Single Sign-On)가 활성화된 경우 API에 로그인 인증"을 참조하십시오.

+
인증 보안 강화에 대한 자세한 내용은 "사이트 간 요청 위조로부터 보호"를 참조하십시오.

* * 클라이언트-인증서 *: 외부 모니터링 도구를 사용하여 StorageGRID에 안전하게 액세스할 수 있도록 클라이언트 인증서를 구성하는 작업
* * config *: 그리드 관리 API 제품 릴리스 및 버전과 관련된 작업. 제품 릴리스 버전과 해당 릴리스에서 지원하는 Grid Management API의 주요 버전을 나열할 수 있으며 더 이상 사용되지 않는 API 버전을 사용하지 않도록 설정할 수 있습니다.
* * 비활성화됨 - 기능 *: 비활성화된 기능을 보기 위한 작업.
* * DNS-서버 *: 구성된 외부 DNS 서버를 나열하고 변경하는 작업.
* * 드라이브 세부 정보 *: 특정 스토리지 어플라이언스 모델을 위한 드라이브 작업.
* * endpoint-domain-names *: S3 끝점 도메인 이름을 나열하고 변경하는 작업.
* * 삭제 코딩 * : 삭제 코딩 프로필에 대한 작업.
* * 확장 *: 확장 작업(절차 수준).
* * 확장 노드 *: 확장 시 작업(노드 레벨).
* * 확장 사이트 *: 확장 시 운영(사이트 레벨)
* * GRID-NETWORKS *: 그리드 네트워크 목록을 나열하고 변경하는 작업.
* * GRID-Passwords *: 그리드 암호 관리 작업.
* * 그룹 *: 로컬 그리드 관리자 그룹을 관리하고 외부 LDAP 서버에서 통합 그리드 관리자 그룹을 검색하는 작업.
* * identity-source *: 외부 ID 소스를 구성하고 통합 그룹 및 사용자 정보를 수동으로 동기화하는 작업
* * ILM *: 정보 수명 주기 관리(ILM)의 운영
* *In-progress-procedures*: 현재 진행 중인 유지보수 절차를 검색합니다.
* 라이센스 *: StorageGRID 라이센스를 검색하고 업데이트하는 작업.
* *logs*: 로그 파일을 수집하고 다운로드하는 작업입니다
* * 메트릭 *: 일정 기간 동안 단일 시점 및 범위 메트릭 쿼리의 인스턴스 메트릭 쿼리를 비롯한 StorageGRID 메트릭의 작업 Grid Management API는 Prometheus 시스템 모니터링 도구를 백엔드 데이터 소스로 사용합니다. Prometheus 쿼리 구성에 대한 자세한 내용은 Prometheus 웹 사이트를 참조하십시오.
+

NOTE: 이름에 포함된 메트릭은 ``_private_``내부용으로만 사용할 수 있습니다. 이러한 메트릭은 사전 통지 없이 StorageGRID 릴리스 간에 변경될 수 있습니다.

* * 노드 세부 정보 *: 노드 세부 정보에 대한 작업.
* * 노드 상태 *: 노드 상태에 대한 작업
* * 노드-스토리지-상태 *: 노드 스토리지 상태의 작업.
* * NTP-서버 *: 외부 NTP(Network Time Protocol) 서버를 나열하거나 업데이트하는 작업.
* * 오브젝트 *: 오브젝트 및 오브젝트 메타데이터의 작동
* * 복구 *: 복구 절차를 위한 작업.
* *recovery-package*: 복구 패키지를 다운로드하는 작업입니다.
* * 지역 *: 영역을 보고 만드는 작업.
* * S3 오브젝트 잠금 *: 글로벌 S3 오브젝트 잠금 설정 시 작업.
* * server-certificate *: Grid Manager 서버 인증서를 보고 업데이트하는 작업.
* * SNMP *: 현재 SNMP 구성에 대한 작업.
* * 스토리지 - 워터마크 *: 스토리지 노드 워터마크입니다.
* * traffic-classes *: 트래픽 분류 정책을 위한 운영.
* * 신뢰할 수 없는 클라이언트-네트워크 *: 신뢰할 수 없는 클라이언트 네트워크 구성에서의 작업.
* * 사용자 *: 그리드 관리자 사용자를 보고 관리하는 작업.

