---
permalink: admin/grid-federation-compare-cgr-to-cloudmirror.html 
sidebar: sidebar 
keywords: cross-grid replication, cloudmirror replication 
summary: 그리드 페더레이션을 사용하기 시작할 때 교차 그리드 복제와 StorageGRID CloudMirror 복제 서비스의 유사점과 차이점을 검토하십시오. 
---
= 교차 그리드 복제와 CloudMirror 복제를 비교합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 페더레이션을 사용하기 시작할 때 및 의 유사점과 차이점을 link:grid-federation-what-is-cross-grid-replication.html["교차 그리드 복제"]link:../tenant/understanding-cloudmirror-replication-service.html["StorageGRID CloudMirror 복제 서비스입니다"]검토하십시오.

[cols="1a,3a,3a"]
|===
|  | 교차 그리드 복제 | CloudMirror 복제 서비스 


 a| 
주요 목적은 무엇입니까?
 a| 
하나의 StorageGRID 시스템이 재해 복구 시스템 역할을 합니다. 버킷의 오브젝트는 한 방향 또는 두 방향으로 그리드 간에 복제될 수 있습니다.
 a| 
테넌트가 StorageGRID(소스)의 버킷에서 외부 S3 버킷(대상)으로 오브젝트를 자동으로 복제할 수 있습니다.

CloudMirror 복제는 독립 S3 인프라에서 개체의 독립적인 복사본을 생성합니다. 이 독립 복제본은 백업으로 사용되지 않고 클라우드에서 추가로 처리되는 경우가 많습니다.



 a| 
어떻게 설정합니까?
 a| 
. 두 그리드 간의 그리드 페더레이션 연결을 구성합니다.
. 다른 그리드에 자동으로 클론이 생성되는 새 테넌트 계정을 추가합니다.
. 클론 복제된 새 테넌트 그룹 및 사용자를 추가합니다.
. 각 그리드에 해당하는 버킷을 생성하고 교차 그리드 복제가 한 방향 또는 양쪽 방향으로 이루어질 수 있도록 합니다.

 a| 
. 테넌트 사용자는 테넌트 관리자 또는 S3 API를 사용하여 CloudMirror 엔드포인트(IP 주소, 자격 증명 등)를 정의하여 CloudMirror 복제를 구성합니다.
. 해당 테넌트 계정이 소유한 버킷은 CloudMirror 엔드포인트를 가리키도록 구성할 수 있습니다.




 a| 
누가 설정해야 합니까?
 a| 
* 그리드 관리자는 접속 및 테넌트를 구성합니다.
* 테넌트 사용자는 그룹, 사용자, 키 및 버킷을 구성합니다.

 a| 
일반적으로 테넌트 사용자입니다.



 a| 
대상은 무엇입니까?
 a| 
그리드 페더레이션 연결에서 다른 StorageGRID 시스템에 있는 상응하는 동일한 S3 버킷.
 a| 
* 모든 호환 가능한 S3 인프라(Amazon S3 포함).
* Google Cloud Platform(GCP)




 a| 
오브젝트 버전 관리가 필요합니까?
 a| 
예. 소스 및 대상 버킷 모두에 오브젝트 버전 관리가 활성화되어 있어야 합니다.
 a| 
아니요. CloudMirror 복제는 소스 및 대상 모두에서 버전이 지정되지 않은 버킷과 버전 관리가 된 버킷의 조합을 지원합니다.



 a| 
오브젝트를 대상으로 이동하는 원인은 무엇입니까?
 a| 
객체가 교차 그리드 복제가 활성화된 버킷에 추가되면 자동으로 복제됩니다.
 a| 
객체는 CloudMirror 엔드포인트로 구성된 버킷에 추가될 때 자동으로 복제됩니다. 버킷이 CloudMirror 엔드포인트로 구성되기 전에 소스 버킷에 있던 객체는 수정되지 않으면 복제되지 않습니다.



 a| 
객체는 어떻게 복제됩니까?
 a| 
교차 그리드 복제는 버전이 있는 오브젝트를 생성하고 소스 버킷에서 대상 버킷으로 버전 ID를 복제합니다. 이렇게 하면 버전 순서가 양쪽 그리드에 걸쳐 유지됩니다.
 a| 
CloudMirror 복제에는 버전 관리가 활성화된 버킷이 필요하지 않으므로 CloudMirror는 사이트 내의 키에 대한 주문만 유지할 수 있습니다. 다른 사이트의 개체에 대한 요청에 대해 주문이 유지되도록 보장하는 것은 없습니다.



 a| 
개체를 복제할 수 없는 경우 어떻게 해야 합니까?
 a| 
객체는 메타데이터 스토리지 제한에 따라 복제 대기열에 추가됩니다.
 a| 
플랫폼 서비스 제한에 따라 객체가 복제를 위해 대기하고 있습니다(참조link:manage-platform-services-for-tenants.html["플랫폼 서비스 사용을 위한 권장 사항"]).



 a| 
개체의 시스템 메타데이터가 복제됩니까?
 a| 
예. 객체가 다른 그리드에 복제되면 해당 시스템 메타데이터도 복제됩니다. 메타데이터는 두 그리드에서 모두 동일합니다.
 a| 
아니요. 객체가 외부 버킷에 복제되면 해당 시스템 메타데이터가 업데이트됩니다. 메타데이터는 수집 시간과 독립적인 S3 인프라의 동작에 따라 여러 위치에 따라 달라집니다.



 a| 
객체를 검색하는 방법은 무엇입니까?
 a| 
애플리케이션은 두 그리드 중 하나의 버킷에 대한 요청을 함으로써 객체를 검색하거나 읽을 수 있습니다.
 a| 
애플리케이션은 StorageGRID 또는 S3 대상을 요청하여 오브젝트를 검색하거나 읽을 수 있습니다. 예를 들어 CloudMirror 복제를 사용하여 객체를 파트너 조직에 미러링한다고 가정합니다. 파트너는 자체 애플리케이션을 사용하여 S3 대상에서 직접 오브젝트를 읽거나 업데이트할 수 있습니다. StorageGRID를 사용할 필요가 없습니다.



 a| 
개체를 삭제하면 어떻게 됩니까?
 a| 
* 버전 ID가 포함된 삭제 요청은 대상 그리드에 복제되지 않습니다.
* 버전 ID가 포함되지 않은 삭제 요청은 소스 버킷에 삭제 마커를 추가합니다. 이 마커는 대상 그리드에 선택적으로 복제할 수 있습니다.
* 교차 그리드 복제가 한 방향으로만 구성된 경우 소스에 영향을 주지 않고 대상 버킷의 오브젝트를 삭제할 수 있습니다.

 a| 
결과는 소스 및 대상 버킷의 버전 관리 상태에 따라 달라집니다(동일할 필요는 없음).

* 두 버킷의 버전이 모두 설정된 경우 삭제 요청은 두 위치에 삭제 마커를 추가합니다.
* 소스 버킷만 버전 관리되는 경우 삭제 요청이 원본에 삭제 표식을 추가하지만 대상에는 추가하지 않습니다.
* 버킷의 버전이 지정되지 않은 경우 삭제 요청이 소스에서 개체를 삭제하지만 대상에서 삭제하지는 않습니다.


마찬가지로, 소스에 영향을 주지 않고 대상 버킷의 오브젝트를 삭제할 수 있습니다.

|===