---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: '테넌트 계정을 사용하면 S3(Simple Storage Service) REST API를 사용하여 StorageGRID 시스템에 객체를 저장하고 검색할 수 있습니다.' 
---
= 테넌트 계정이란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 계정을 사용하면 S3(Simple Storage Service) REST API를 사용하여 StorageGRID 시스템에 오브젝트를 저장하고 검색할 수 있습니다.


TIP: 이 버전의 문서 사이트에서 Swift 세부 정보가 제거되었습니다. 을 https://docs.netapp.com/us-en/storagegrid-118/admin/managing-tenants.html["StorageGRID 11.8: 테넌트 관리"^]참조하십시오.

그리드 관리자는 S3 클라이언트가 오브젝트를 저장하고 검색하는 데 사용하는 테넌트 계정을 만들고 관리합니다.

각 테넌트 계정에는 페더레이션 또는 로컬 그룹, 사용자, S3 버킷 및 오브젝트가 있습니다.

테넌트 계정은 저장된 객체를 다른 엔터티로 분리하는 데 사용할 수 있습니다. 예를 들어, 다음과 같은 사용 사례에서 여러 테넌트 계정을 사용할 수 있습니다.

* * 기업 활용 사례: * 엔터프라이즈 애플리케이션에서 StorageGRID 시스템을 관리하는 경우 조직의 여러 부서에서 그리드의 객체 스토리지를 분리할 수 있습니다. 이 경우 마케팅 부서, 고객 지원 부서, 인사 부서 등에 대한 테넌트 계정을 만들 수 있습니다.
+

NOTE: S3 클라이언트 프로토콜을 사용하면 S3 버킷과 버킷 정책을 사용하여 기업 내 부서 간에 객체를 분리할 수 있습니다.  세입자 계정을 사용할 필요가 없습니다.  구현에 대한 지침을 참조하세요.link:../s3/use-access-policies.html["S3 버킷 및 버킷 정책"] 자세한 내용은.

* * 서비스 공급자 활용 사례: * StorageGRID 시스템을 서비스 공급자로 관리하는 경우 그리드의 객체 스토리지를 그리드의 스토리지를 임대할 다른 엔터티로 분리할 수 있습니다. 이 경우 회사 A, 회사 B, 회사 C 등에 대한 테넌트 계정을 생성합니다.


자세한 내용은 을 link:../tenant/index.html["테넌트 계정을 사용합니다"]참조하십시오.



== 테넌트 계정은 어떻게 생성합니까?

그리드 관리자를 사용하여 테넌트 계정을 생성합니다. 테넌트 계정을 생성할 때 다음 정보를 지정합니다.

* 테넌트 이름, 클라이언트 유형(S3) 및 선택적 스토리지 할당량을 포함한 기본 정보입니다.
* 테넌트 계정에서 S3 플랫폼 서비스를 사용할 수 있는지 여부, 해당 ID 소스를 구성할 수 있는지 여부, S3 Select를 사용할 것인지, 그리드 페더레이션 연결을 사용할 수 있는지 여부 등의 테넌트 계정에 대한 사용 권한
* StorageGRID 시스템에서 로컬 그룹 및 사용자, ID 페더레이션 또는 SSO(Single Sign-On)를 사용하는지 여부에 따라 테넌트의 초기 루트 액세스입니다.


또한 S3 테넌트 계정이 규정 요구 사항을 준수해야 하는 경우 StorageGRID 시스템에 대해 S3 오브젝트 잠금 설정을 활성화할 수 있습니다. S3 오브젝트 잠금이 활성화된 경우 모든 S3 테넌트 계정에서 호환 버킷을 생성하고 관리할 수 있습니다.



== 테넌트 관리자는 무엇에 사용됩니까?

테넌트 계정을 생성한 후 테넌트 사용자는 테넌트 관리자에 로그인하여 다음과 같은 작업을 수행할 수 있습니다.

* ID 페더레이션 설정(ID 소스가 그리드와 공유되지 않는 경우)
* 그룹 및 사용자를 관리합니다
* 계정 클론 및 교차 그리드 복제에 그리드 페더레이션을 사용합니다
* S3 액세스 키를 관리합니다
* S3 버킷을 생성하고 관리합니다
* S3 플랫폼 서비스 사용
* S3 Select를 사용합니다
* 스토리지 사용량을 모니터링합니다



TIP: S3 테넌트 사용자는 테넌트 관리자를 사용하여 S3 액세스 키와 버킷을 생성하고 관리할 수 있지만, S3 클라이언트 애플리케이션을 사용하여 오브젝트를 수집 및 관리해야 합니다. 자세한 내용은 을 link:../s3/index.html["S3 REST API 사용"] 참조하십시오.
