---
permalink: admin/managing-traffic-classification-policies.html 
sidebar: sidebar 
keywords: QoS, quality of service, traffic classification, best practices, limit traffic, monitor traffic 
summary: '트래픽 분류 정책을 사용하면 다양한 유형의 네트워크 트래픽을 식별하고 모니터링할 수 있습니다. 이러한 정책은 트래픽 제한 및 모니터링을 지원하여 QoS(Quality-of-Service) 서비스를 향상시킬 수 있습니다.' 
---
= 트래픽 분류 정책이란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
트래픽 분류 정책을 사용하면 다양한 유형의 네트워크 트래픽을 식별하고 모니터링할 수 있습니다. 이러한 정책은 트래픽 제한 및 모니터링을 지원하여 QoS(Quality-of-Service) 서비스를 향상시킬 수 있습니다.

트래픽 분류 정책은 게이트웨이 노드 및 관리 노드에 대한 StorageGRID 로드 밸런서 서비스의 끝점에 적용됩니다. 트래픽 분류 정책을 생성하려면 로드 밸런서 엔드포인트를 이미 생성해야 합니다.



== 일치하는 규칙

각 트래픽 분류 정책에는 다음 항목 중 하나 이상에 관련된 네트워크 트래픽을 식별하기 위한 하나 이상의 일치하는 규칙이 포함되어 있습니다.

* 버킷
* 서브넷
* 테넌트
* 부하 분산 장치 엔드포인트


StorageGRID는 규칙의 목적에 따라 정책 내의 규칙과 일치하는 트래픽을 모니터링합니다. 정책에 대한 규칙과 일치하는 모든 트래픽은 해당 정책에 의해 처리됩니다. 반대로, 지정된 엔터티를 제외한 모든 트래픽에 일치시키는 규칙을 설정할 수 있습니다.



== 트래픽 제한

필요에 따라 다음 제한 유형을 정책에 추가할 수 있습니다.

* 애그리게이트 대역폭
* 요청 당 대역폭
* 동시 요청
* 요청 속도


제한 값은 부하 분산 장치별로 적용됩니다. 트래픽이 여러 부하 분산 장치에 동시에 분산되는 경우 총 최대 속도는 사용자가 지정한 속도 제한의 배수입니다.


NOTE: 정책을 생성하여 애그리게이트 대역폭을 제한하거나 요청당 대역폭을 제한할 수 있습니다. 그러나 StorageGRID는 두 가지 유형의 대역폭을 동시에 제한할 수 없습니다. 애그리게이트 대역폭 제한은 제한 없는 트래픽에 약간의 성능 영향을 줄 수 있습니다.

애그리게이트 또는 요청별 대역폭 제한의 경우 요청은 사용자가 설정한 속도로 스트림 인 또는 아웃됩니다. StorageGRID는 단 하나의 속도만 적용할 수 있으므로 가장 구체적인 정책 매칭은 매처 유형별로 적용됩니다. 요청에 사용된 대역폭은 총 대역폭 제한 정책을 포함하는 비교적 덜 특정한 다른 정책에 포함되지 않습니다. 다른 모든 제한 유형의 경우 클라이언트 요청이 250밀리초 지연되고 일치하는 정책 제한을 초과하는 요청에 대해 503 느린 응답 응답을 수신합니다.

Grid Manager에서 트래픽 차트를 보고 정책이 기대하는 트래픽 제한을 적용하고 있는지 확인할 수 있습니다.



== SLA와 함께 트래픽 분류 정책을 사용합니다

용량 제한 및 데이터 보호와 함께 트래픽 분류 정책을 사용하여 용량, 데이터 보호 및 성능에 대한 세부 정보를 제공하는 서비스 수준 계약(SLA)을 적용할 수 있습니다.

다음 예에서는 SLA의 세 가지 계층을 보여 줍니다. 트래픽 분류 정책을 작성하여 각 SLA 계층의 성능 목표를 달성할 수 있습니다.

[cols="1a,1a,1a,1a,1a"]
|===
| 서비스 수준 계층 | 용량 | 데이터 보호 | 최대 성능이 허용됩니다 | 비용 


 a| 
골드
 a| 
1PB의 스토리지가 허용됩니다
 a| 
ILM 규칙 3개 복사
 a| 
초당 25K 요청

5GB/sec(40Gbps) 대역폭
 a| 
$$/월



 a| 
실버
 a| 
250TB 스토리지 허용
 a| 
ILM 규칙 2개 복사
 a| 
초당 10K 요청

1.25GB/sec(10Gbps) 대역폭
 a| 
$$/월



 a| 
브론즈
 a| 
100TB 스토리지 허용
 a| 
ILM 규칙 2개 복사
 a| 
초당 5K 요청

1 GB/sec(8Gbps) 대역폭
 a| 
$/월

|===