---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: '오브젝트를 저장하거나 검색하기 위해 S3 클라이언트 애플리케이션은 모든 관리 노드 및 게이트웨이 노드에 포함된 로드 밸런서 서비스 또는 모든 스토리지 노드에 포함된 LDR(Local Distribution Router) 서비스에 연결됩니다.' 
---
= 요약: 클라이언트 연결을 위한 IP 주소 및 포트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
오브젝트를 저장하거나 검색하기 위해 S3 클라이언트 애플리케이션은 모든 관리 노드 및 게이트웨이 노드에 포함된 로드 밸런서 서비스 또는 모든 스토리지 노드에 포함된 LDR(Local Distribution Router) 서비스에 연결됩니다.

클라이언트 애플리케이션은 그리드 노드의 IP 주소와 해당 노드의 서비스 포트 번호를 사용하여 StorageGRID에 연결할 수 있습니다. 선택적으로, 로드 밸런싱 노드의 고가용성(HA) 그룹을 생성하여 가상 IP(VIP) 주소를 사용하는 고가용성 연결을 제공할 수 있습니다. IP 또는 VIP 주소 대신 FQDN(정규화된 도메인 이름)을 사용하여 StorageGRID에 연결하려는 경우 DNS 항목을 구성할 수 있습니다.

이 표에는 클라이언트가 StorageGRID에 연결할 수 있는 다양한 방법과 각 연결 유형에 사용되는 IP 주소 및 포트가 요약되어 있습니다. 로드 밸런서 엔드포인트 및 고가용성(HA) 그룹을 이미 생성한 경우 그리드 관리자에서 이러한 값을 찾으려면 을 참조하십시오.<<IP 주소를 찾을 위치>>

[cols="1a,1a,1a,1a"]
|===
| 연결 위치 | 클라이언트가 연결하는 서비스입니다 | IP 주소입니다 | 포트 


 a| 
HA 그룹
 a| 
로드 밸런서
 a| 
HA 그룹의 가상 IP 주소입니다
 a| 
로드 밸런서 끝점에 할당된 포트입니다



 a| 
관리자 노드
 a| 
로드 밸런서
 a| 
관리 노드의 IP 주소입니다
 a| 
로드 밸런서 끝점에 할당된 포트입니다



 a| 
게이트웨이 노드
 a| 
로드 밸런서
 a| 
게이트웨이 노드의 IP 주소입니다
 a| 
로드 밸런서 끝점에 할당된 포트입니다



 a| 
스토리지 노드
 a| 
LDR
 a| 
스토리지 노드의 IP 주소입니다
 a| 
기본 S3 포트:

* HTTPS: 18082
* HTTP: 18084


|===


== URL의 예

클라이언트 응용 프로그램을 게이트웨이 노드의 HA 그룹의 로드 밸런서 끝점에 연결하려면 아래와 같이 구조화된 URL을 사용합니다.

`https://_VIP-of-HA-group:LB-endpoint-port_`

예를 들어 HA 그룹의 가상 IP 주소가 192.0.2.5이고 로드 밸런서 끝점의 포트 번호가 10443인 경우 응용 프로그램에서 다음 URL을 사용하여 StorageGRID에 연결할 수 있습니다.

`\https://192.0.2.5:10443`



== IP 주소를 찾을 위치

. 을 사용하여 그리드 관리자에 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]로그인합니다.
. 그리드 노드의 IP 주소를 찾으려면
+
.. *노드*를 선택하세요.
.. 연결할 관리 노드, 게이트웨이 노드 또는 스토리지 노드를 선택합니다.
.. 개요 * 탭을 선택합니다.
.. 노드 정보 섹션에서 노드의 IP 주소를 확인합니다.
.. IPv6 주소 및 인터페이스 매핑을 보려면 * 더 보기 * 를 선택합니다.
+
클라이언트 응용 프로그램에서 목록의 IP 주소로의 연결을 설정할 수 있습니다.

+
*** eth0: * 그리드 네트워크
*** * eth1: * 관리 네트워크(옵션)
*** * eth2: * 클라이언트 네트워크(옵션)
+

NOTE: 관리 노드 또는 게이트웨이 노드를 보고 있고 고가용성 그룹의 활성 노드인 경우 HA 그룹의 가상 IP 주소가 eth2에 표시됩니다.





. 고가용성 그룹의 가상 IP 주소를 찾으려면 다음을 수행합니다.
+
.. *구성* > *네트워크* > *고가용성 그룹*을 선택합니다.
.. 표에서 HA 그룹의 가상 IP 주소를 확인합니다.


. 로드 밸런서 끝점의 포트 번호를 찾으려면 다음을 수행합니다.
+
.. *구성* > *네트워크* > *로드 밸런서 엔드포인트*를 선택합니다.
.. 사용할 끝점의 포트 번호를 확인합니다.
+

NOTE: 포트 번호가 80 또는 443인 경우 엔드포인트는 게이트웨이 노드에서만 구성됩니다. 이러한 포트는 관리 노드에 예약되기 때문입니다. 다른 모든 포트는 게이트웨이 노드와 관리 노드 모두에서 구성됩니다.

.. 테이블에서 끝점 이름을 선택합니다.
.. 클라이언트 유형 * (S3)이 끝점을 사용할 클라이언트 응용 프로그램과 일치하는지 확인합니다.



