---
permalink: admin/temporarily-disabling-and-reenabling-sso-for-admin-node.html 
sidebar: sidebar 
keywords: signing in when sso is down, single sign on failure 
summary: 'SSO(Single Sign-On) 시스템이 다운되면 Grid Manager에 로그인하지 못할 수 있습니다. 이 경우 한 관리 노드에 대해 SSO를 일시적으로 비활성화 및 다시 활성화할 수 있습니다. SSO를 비활성화한 다음 다시 활성화하려면 노드의 명령 셸에 액세스해야 합니다.' 
---
= 한 관리자 노드에 대해 SSO를 일시적으로 비활성화하고 다시 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSO(Single Sign-On) 시스템이 다운되면 Grid Manager에 로그인하지 못할 수 있습니다. 이 경우 한 관리 노드에 대해 SSO를 일시적으로 비활성화 및 다시 활성화할 수 있습니다. SSO를 사용하지 않도록 설정한 다음 다시 사용하도록 설정하려면 노드의 명령 셸에 액세스해야 합니다.

.시작하기 전에
* 있습니다. link:admin-group-permissions.html["특정 액세스 권한"]
*  `Passwords.txt`파일이 있습니다.
* 로컬 루트 사용자의 암호를 알고 있습니다.


.이 작업에 대해
한 관리 노드에 대해 SSO를 비활성화한 후 그리드 관리자에 로컬 루트 사용자로 로그인할 수 있습니다. StorageGRID 시스템을 보호하려면 로그아웃하는 즉시 노드의 명령 셸을 사용하여 관리자 노드에서 SSO를 다시 활성화해야 합니다.


TIP: 한 관리 노드에 대해 SSO를 비활성화해도 그리드의 다른 관리 노드에 대한 SSO 설정에는 영향을 주지 않습니다. Grid Manager의 Single Sign-On 페이지에 있는 * Enable SSO * 확인란은 선택된 상태로 남아 있으며, 기존 SSO 설정은 모두 업데이트하지 않는 한 유지됩니다.

.단계
. 관리자 노드에 로그인:
+
.. 다음 명령을 입력합니다. `ssh admin@Admin_Node_IP`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
.. 다음 명령을 입력하여 루트로 전환합니다. `su -`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
+
루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.



. 다음 명령을 실행합니다.``disable-saml``
+
명령이 이 관리 노드에만 적용된다는 메시지가 표시됩니다.

. SSO를 비활성화할지 확인합니다.
+
노드에서 SSO(Single Sign-On)가 비활성화되었다는 메시지가 표시됩니다.

. 웹 브라우저에서 동일한 관리 노드의 그리드 관리자에 액세스합니다.
+
이제 SSO가 비활성화되어 Grid Manager 로그인 페이지가 표시됩니다.

. 사용자 이름 루트와 로컬 루트 사용자 암호를 사용하여 로그인합니다.
. SSO 구성을 수정해야 하므로 SSO를 일시적으로 비활성화한 경우:
+
.. 구성 * > * 액세스 제어 * > * 단일 사인온 * 을 선택합니다.
.. 잘못된 또는 오래된 SSO 설정을 변경합니다.
.. 저장 * 을 선택합니다.
+
단일 사인온 페이지에서 * 저장 * 을 선택하면 전체 그리드에 대한 SSO가 자동으로 다시 활성화됩니다.



. 다른 이유로 인해 그리드 관리자에 액세스해야 하기 때문에 SSO를 일시적으로 비활성화한 경우:
+
.. 수행해야 할 작업 또는 작업을 모두 수행합니다.
.. 로그아웃 * 을 선택하고 그리드 관리자를 닫습니다.
.. 관리자 노드에서 SSO를 다시 활성화합니다. 다음 단계 중 하나를 수행할 수 있습니다.
+
*** 다음 명령을 실행합니다. `enable-saml`
+
명령이 이 관리 노드에만 적용된다는 메시지가 표시됩니다.

+
SSO를 활성화할지 확인합니다.

+
노드에서 Single Sign-On이 설정되었음을 나타내는 메시지가 표시됩니다.

*** 그리드 노드를 재부팅합니다. `reboot`




. 웹 브라우저에서 동일한 관리 노드에서 그리드 관리자에 액세스합니다.
. StorageGRID 로그인 페이지가 나타나고 그리드 관리자에 액세스하려면 SSO 자격 증명을 입력해야 합니다.

