---
permalink: admin/use-s3-setup-wizard.html 
sidebar: sidebar 
keywords: S3, S3 setup wizard 
summary: S3 설정 마법사를 사용하여 StorageGRID를 S3 애플리케이션의 오브젝트 스토리지 시스템으로 구성할 수 있습니다. 
---
= S3 설정 마법사 고려 사항 및 요구 사항을 사용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 설정 마법사를 사용하여 StorageGRID를 S3 애플리케이션의 오브젝트 스토리지 시스템으로 구성할 수 있습니다.



== S3 설정 마법사를 사용하는 경우

S3 설정 마법사는 S3 애플리케이션에서 사용할 StorageGRID를 구성하는 각 단계를 안내합니다. 마법사 완료 시 S3 애플리케이션에 값을 입력하는 데 사용할 수 있는 파일을 다운로드합니다. 마법사를 사용하여 시스템을 보다 빠르게 구성하고 설정이 StorageGRID 모범 사례에 맞는지 확인합니다.

를 사용하는 link:admin-group-permissions.html["루트 액세스 권한"]경우 StorageGRID 그리드 관리자를 사용하여 시작할 때 S3 설정 마법사를 완료할 수 있으며, 나중에 마법사를 액세스하여 완료할 수 있습니다. 요구 사항에 따라 필요한 항목의 일부 또는 전체를 수동으로 구성한 다음 마법사를 사용하여 S3 애플리케이션에 필요한 값을 조합할 수도 있습니다.



== 마법사를 사용하기 전에

마법사를 사용하기 전에 이러한 사전 요구 사항을 완료했는지 확인합니다.

IP 주소를 얻고 VLAN 인터페이스를 설정합니다:: 고가용성(HA) 그룹을 구성할 경우 S3 애플리케이션이 연결할 노드와 사용할 StorageGRID 네트워크를 알게 됩니다. 서브넷 CIDR, 게이트웨이 IP 주소 및 가상 IP(VIP) 주소에 대해 입력할 값도 알고 있습니다.
+
--
가상 LAN을 사용하여 S3 애플리케이션의 트래픽을 분리할 계획이라면 이미 VLAN 인터페이스를 구성한 것입니다. 을 link:../admin/configure-vlan-interfaces.html["VLAN 인터페이스를 구성합니다"]참조하십시오.

--
ID 페더레이션 및 SSO를 구성합니다:: StorageGRID 시스템에 대해 ID 페더레이션 또는 SSO(Single Sign-On)를 사용하려는 경우 이러한 기능을 활성화했습니다. 또한 S3 애플리케이션에서 사용할 테넌트 계정에 대한 루트 액세스 권한이 있어야 하는 통합 그룹도 알고 있습니다. link:../admin/using-identity-federation.html["ID 페더레이션을 사용합니다"]및 을 link:../admin/how-sso-works.html["Single Sign-On 구성"]참조하십시오.
도메인 이름 가져오기 및 구성:: StorageGRID에 사용할 FQDN(정규화된 도메인 이름)을 알고 있습니다. DNS(Domain Name Server) 항목은 이 FQDN을 마법사를 사용하여 생성한 HA 그룹의 가상 IP(VIP) 주소에 매핑합니다.
+
--
S3 가상 호스팅 방식의 요청을 사용하려는 경우 가 있어야 link:../admin/configuring-s3-api-endpoint-domain-names.html["S3 끝점 도메인 이름을 구성했습니다"]합니다. 가상 호스팅 방식의 요청을 사용하는 것이 좋습니다.

--
로드 밸런서 및 보안 인증서 요구 사항을 검토합니다:: StorageGRID 부하 분산 장치를 사용할 계획이라면 로드 밸런싱에 대한 일반적인 고려 사항을 검토했습니다. 업로드할 인증서 또는 인증서를 생성하는 데 필요한 값이 있습니다.
+
--
외부(타사) 로드 밸런서 끝점을 사용하려는 경우 해당 로드 밸런서에 대한 FQDN(정규화된 도메인 이름), 포트 및 인증서가 있어야 합니다.

--
모든 그리드 페더레이션 연결을 구성합니다:: S3 테넌트가 계정 데이터를 복제하고 그리드 통합 연결을 사용하여 버킷 오브젝트를 다른 그리드에 복제하도록 허용하려면 마법사를 시작하기 전에 다음을 확인하십시오.
+
--
* 있습니다. link:grid-federation-manage-connection.html["그리드 페더레이션 연결을 구성했습니다"]
* 연결 상태는 * 연결됨 * 입니다.
* 루트 액세스 권한이 있습니다.


--

