---
permalink: s3/custom-operations-on-buckets.html 
sidebar: sidebar 
keywords: operations, buckets, custom, storagegrid bucket operations 
summary: StorageGRID 시스템은 S3 REST API에 추가된 사용자 지정 작업을 지원합니다. 
---
= StorageGRID 사용자 정의 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템은 S3 REST API에 추가된 사용자 지정 작업을 지원합니다.

다음 표에서는 StorageGRID에서 지원하는 사용자 지정 작업을 보여 줍니다.

[cols="1a,2a"]
|===
| 작동 | 설명 


 a| 
link:get-bucket-consistency-request.html["버킷 일관성 확보"]
 a| 
특정 버킷에 적용되는 일관성을 반환합니다.



 a| 
link:put-bucket-consistency-request.html["버킷 일관성을 유지합니다"]
 a| 
특정 버킷에 적용되는 일관성을 설정합니다.



 a| 
link:get-bucket-last-access-time-request.html["버킷 최종 액세스 시간 가져오기"]
 a| 
특정 버킷에 대해 마지막 액세스 시간 업데이트를 사용할 수 있는지 여부를 반환합니다.



 a| 
link:put-bucket-last-access-time-request.html["버킷 최종 접근 시간"]
 a| 
특정 버킷에 대한 마지막 액세스 시간 업데이트를 활성화하거나 비활성화할 수 있습니다.



 a| 
link:delete-bucket-metadata-notification-configuration-request.html["버킷 메타데이터 알림 구성을 삭제합니다"]
 a| 
특정 버킷과 연결된 메타데이터 알림 구성 XML을 삭제합니다.



 a| 
link:get-bucket-metadata-notification-configuration-request.html["Bucket 메타데이터 알림 구성 가져오기"]
 a| 
특정 버킷과 연결된 메타데이터 알림 구성 XML을 반환합니다.



 a| 
link:put-bucket-metadata-notification-configuration-request.html["Put Bucket 메타데이터 알림 구성"]
 a| 
버킷에 대한 메타데이터 알림 서비스를 구성합니다.



 a| 
link:get-storage-usage-request.html["스토리지 사용량을 가져옵니다"]
 a| 
계정과 연결된 각 버킷에서 사용 중인 총 저장소 양을 나타냅니다.



 a| 
link:deprecated-put-bucket-request-modifications-for-compliance.html["사용되지 않음: 규정 준수 설정이 있는 CreateBucket"]
 a| 
더 이상 사용되지 않으며 지원되지 않음: Compliance를 사용하는 새 버킷을 더 이상 생성할 수 없습니다.



 a| 
link:deprecated-get-bucket-compliance-request.html["사용되지 않음: 버킷 준수 가져오기"]
 a| 
더 이상 사용되지 않지만 지원됨: 기존 레거시 준수 버킷에 대해 현재 적용되는 규정 준수 설정을 반환합니다.



 a| 
link:deprecated-put-bucket-compliance-request.html["사용되지 않음: 버킷 준수"]
 a| 
사용되지 않지만 지원됨: 기존 레거시 준수 버킷의 준수 설정을 수정할 수 있습니다.

|===