---
permalink: s3/error-responses.html 
sidebar: sidebar 
keywords: error, error responses 
summary: StorageGRID 시스템은 적용되는 모든 표준 S3 REST API 오류 응답을 지원합니다. 또한 StorageGRID 구현에는 여러 개의 사용자 지정 응답이 추가됩니다. 
---
= 오류 응답
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템은 적용되는 모든 표준 S3 REST API 오류 응답을 지원합니다. 또한 StorageGRID 구현에는 여러 개의 사용자 지정 응답이 추가됩니다.



== 지원되는 S3 API 오류 코드입니다

[cols="1a,1a"]
|===
| 이름 | HTTP 상태입니다 


 a| 
액세스가 거부되었습니다
 a| 
403 사용 금지



 a| 
배다이제스트
 a| 
400 잘못된 요청



 a| 
BuckketAlreadyExists를 참조하십시오
 a| 
409 충돌



 a| 
BuckketNotEmpty
 a| 
409 충돌



 a| 
IncompleteBody
 a| 
400 잘못된 요청



 a| 
내부 오류입니다
 a| 
500 내부 서버 오류입니다



 a| 
InvalidAccessKeyId 입니다
 a| 
403 사용 금지



 a| 
InvalidArgument 를 선택합니다
 a| 
400 잘못된 요청



 a| 
InvalidBuckName입니다
 a| 
400 잘못된 요청



 a| 
InvalidBuckketState입니다
 a| 
409 충돌



 a| 
InvalidDigest 를 선택합니다
 a| 
400 잘못된 요청



 a| 
InvalidEncryptionAlgorithmError 가 발생합니다
 a| 
400 잘못된 요청



 a| 
InvalidPart 를 선택합니다
 a| 
400 잘못된 요청



 a| 
InvalidPartOrder를 선택합니다
 a| 
400 잘못된 요청



 a| 
InvalidRange 를 선택합니다
 a| 
416 요청된 범위가 충분하지 않습니다



 a| 
InvalidRequest 입니다
 a| 
400 잘못된 요청



 a| 
InvalidStorageClass 의 값을 반환합니다
 a| 
400 잘못된 요청



 a| 
InvalidTag 를 선택합니다
 a| 
400 잘못된 요청



 a| 
InvalidURI입니다
 a| 
400 잘못된 요청



 a| 
키투롱
 a| 
400 잘못된 요청



 a| 
MalformedXML을 참조하십시오
 a| 
400 잘못된 요청



 a| 
MetadataTooLarge를 참조하십시오
 a| 
400 잘못된 요청



 a| 
MethodNotAllowed 를 참조하십시오
 a| 
405 메서드를 사용할 수 없습니다



 a| 
MissingContentLength를 참조하십시오
 a| 
411 길이 필요



 a| 
MissingRequestBodyError가 발생합니다
 a| 
400 잘못된 요청



 a| 
MissingSecurityHeader 를 참조하십시오
 a| 
400 잘못된 요청



 a| 
NoSuchBucket
 a| 
404를 찾을 수 없습니다



 a| 
NoSuchKey를 클릭합니다
 a| 
404를 찾을 수 없습니다



 a| 
NoSuchUpload 를 클릭합니다
 a| 
404를 찾을 수 없습니다



 a| 
구현되지 않았습니다
 a| 
501 구현되지 않음



 a| 
NoSuchBuckketPolicy를 참조하십시오
 a| 
404를 찾을 수 없습니다



 a| 
ObjectLockConfigurationNotFoundError 가 발생합니다
 a| 
404를 찾을 수 없습니다



 a| 
사전 조건에 실패했습니다
 a| 
412 전제 조건 실패



 a| 
RequestTimeTooSkewed 를 참조하십시오
 a| 
403 사용 금지



 a| 
서비스를 사용할 수 없습니다
 a| 
503 서비스를 사용할 수 없습니다



 a| 
SignatureDoesNotMatch 를 참조하십시오
 a| 
403 사용 금지



 a| 
투만이버킷
 a| 
400 잘못된 요청



 a| 
UserKeyMustBeSpecified 를 선택합니다
 a| 
400 잘못된 요청

|===


== StorageGRID 사용자 지정 오류 코드

[cols="2a,2a,1a"]
|===
| 이름 | 설명 | HTTP 상태입니다 


 a| 
XBuckketLifecycleNotAllowed를 참조하십시오
 a| 
버킷 수명 주기 구성은 레거시 준수 버킷에서 허용되지 않습니다
 a| 
400 잘못된 요청



 a| 
XBuckketPolicyParseException 을 참조하십시오
 a| 
수신된 버킷 정책 JSON을 구문 분석하지 못했습니다.
 a| 
400 잘못된 요청



 a| 
XComplianceConflictt
 a| 
레거시 준수 설정으로 인해 작업이 거부되었습니다.
 a| 
403 사용 금지



 a| 
XComplianceRedundancyForbidden을 선택합니다
 a| 
레거시 준수 버킷에서는 감소된 중복성이 허용되지 않습니다
 a| 
400 잘못된 요청



 a| 
XMaxBuckketPolicyLengthExceeded 를 참조하십시오
 a| 
정책이 허용되는 최대 버킷 정책 길이를 초과합니다.
 a| 
400 잘못된 요청



 a| 
XMissingInternalRequestHeader를 참조하십시오
 a| 
내부 요청의 헤더가 누락되었습니다.
 a| 
400 잘못된 요청



 a| 
XNoSuchBuckketCompliance
 a| 
지정된 버킷에 레거시 준법 기능이 설정되어 있지 않습니다.
 a| 
404를 찾을 수 없습니다



 a| 
XNotAcceptable(X 허용 가능)
 a| 
요청에 충족되지 않은 하나 이상의 수락 헤더가 있습니다.
 a| 
406 허용되지 않습니다



 a| 
XNotImplemented(XNotImplemented)
 a| 
제공한 요청은 구현되지 않은 기능을 의미합니다.
 a| 
501 구현되지 않음

|===