---
permalink: s3/get-bucket-metadata-notification-configuration-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET bucket metadata notification configuration 
summary: Get Bucket 메타데이터 알림 구성 요청을 사용하면 개별 버킷에 대한 검색 통합을 구성하는 데 사용되는 구성 XML을 검색할 수 있습니다. 
---
= Bucket 메타데이터 알림 구성 가져오기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Get Bucket 메타데이터 알림 구성 요청을 사용하면 개별 버킷에 대한 검색 통합을 구성하는 데 사용되는 구성 XML을 검색할 수 있습니다.

이 작업을 완료하려면 S3:GetBuckMetadataNotification 권한이 있거나 계정 루트여야 합니다.



== 요청 예

이 요청은 이름이 인 버킷에 대한 메타데이터 알림 구성을 `bucket` 검색합니다.

[listing, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== 응답

응답 본문에는 버킷에 대한 메타데이터 알림 구성이 포함됩니다. 메타데이터 알림 구성을 사용하면 버킷이 검색 통합을 위해 구성되는 방식을 결정할 수 있습니다. 즉, 인덱싱된 개체와 해당 개체 메타데이터가 전송되는 끝점을 확인할 수 있습니다.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:_region:account-ID_:domain/_mydomain/myindex/mytype_</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
각 메타데이터 알림 구성에는 하나 이상의 규칙이 포함됩니다. 각 규칙은 적용되는 오브젝트와 StorageGRID가 오브젝트 메타데이터를 보내야 하는 대상을 지정합니다. 대상은 StorageGRID 끝점의 URN을 사용하여 지정해야 합니다.

[cols="1a,2a,1a"]
|===
| 이름 | 설명 | 필수 요소입니다 


 a| 
MetadataNotificationConfiguration을 참조하십시오
 a| 
메타데이터 알림의 개체 및 대상을 지정하는 데 사용되는 규칙의 컨테이너 태그입니다.

하나 이상의 규칙 요소가 포함되어 있습니다.
 a| 
예



 a| 
규칙
 a| 
메타데이터를 지정된 인덱스에 추가해야 하는 개체를 식별하는 규칙의 컨테이너 태그입니다.

접두사가 겹치는 규칙은 거부됩니다.

MetadataNotificationConfiguration 요소에 포함되어 있습니다.
 a| 
예



 a| 
ID입니다
 a| 
규칙의 고유 식별자입니다.

Rule 요소에 포함되어 있습니다.
 a| 
아니요



 a| 
상태
 a| 
상태는 '활성화' 또는 '비활성화'가 될 수 있습니다. 비활성화된 규칙에 대해 어떠한 작업도 수행되지 않습니다.

Rule 요소에 포함되어 있습니다.
 a| 
예



 a| 
접두어
 a| 
접두사와 일치하는 개체는 규칙의 영향을 받으며 해당 메타데이터는 지정된 대상으로 전송됩니다.

모든 오브젝트를 일치시키려면 빈 접두사를 지정합니다.

Rule 요소에 포함되어 있습니다.
 a| 
예



 a| 
목적지
 a| 
규칙의 대상에 대한 컨테이너 태그입니다.

Rule 요소에 포함되어 있습니다.
 a| 
예



 a| 
urn
 a| 
객체 메타데이터가 전송되는 대상의 urn입니다. 다음 속성을 가진 StorageGRID 끝점의 URN이어야 합니다.

* `es` 세 번째 요소여야 합니다.
* URN은 메타데이터가 저장되는 인덱스 및 형식으로 끝나야 `domain-name/myindex/mytype` 합니다.


엔드포인트는 테넌트 관리자 또는 테넌트 관리 API를 사용하여 구성됩니다. 다음과 같은 형식을 취합니다.

* `arn:aws:es:_region:account-ID_:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


구성 XML을 제출하기 전에 끝점을 구성해야 합니다. 그렇지 않으면 404 오류로 인해 구성이 실패합니다.

urn은 Destination 요소에 포함됩니다.
 a| 
예

|===


== 응답 예

태그 사이에 포함된 XML은  `<MetadataNotificationConfiguration></MetadataNotificationConfiguration>`검색 통합 끝점과의 통합이 버킷에 대해 구성되는 방법을 보여 줍니다. 이 예제에서 개체 메타데이터는 이름이 인 AWS 도메인에서 호스팅되는 `records` 이름이 `2017` 인 Elasticsearch 인덱스로 보내집니다. `current`

[listing]
----
HTTP/1.1 200 OK
Date: Thu, 20 Jul 2017 18:24:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/11.0.0
x-amz-request-id: 3832973499
Content-Length: 264
Content-Type: application/xml

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix>2017</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/records/current/2017</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.관련 정보
link:../tenant/index.html["테넌트 계정을 사용합니다"]
