---
permalink: s3/get-object.html 
sidebar: sidebar 
keywords: get object 
summary: S3 오브젝트 가져오기 요청을 사용하여 S3 버킷에서 오브젝트를 검색할 수 있습니다. 
---
= GetObject 를 참조하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 GetObject 요청을 사용하여 S3 버킷에서 객체를 검색할 수 있습니다.



== GetObject 및 multipart 개체

요청 매개변수를 사용하여 멀티파트나 분할된 오브젝트의 특정 부분을 검색할 수 `partNumber` 있습니다.  `x-amz-mp-parts-count`응답 요소는 개체의 파트 수를 나타냅니다.

분할/다중 파트 오브젝트 및 비분할/비다중 파트 오브젝트 모두에 대해 1로 설정할 수 `partNumber` 있지만 `x-amz-mp-parts-count` 응답 요소는 분할된 오브젝트 또는 다중 파트 오브젝트에 대해서만 반환됩니다.



== 사용자 메타데이터의 UTF-8 문자

StorageGRID는 사용자 정의 메타데이터에서 이스케이프된 UTF-8 문자를 구문 분석하거나 해석하지 않습니다. 사용자 정의 메타데이터에서 이스케이프된 UTF-8 문자가 있는 개체에 대한 요청 가져오기 키 이름 또는 값에 인쇄할 수 없는 문자가 포함된 경우 헤더를 반환하지 `x-amz-missing-meta` 않습니다.



== 지원되는 요청 헤더

다음 요청 헤더가 지원됩니다.

* `x-amz-checksum-mode`: 지정합니다 `ENABLED`
+
 `Range`헤더는 GetObject 에 대해 지원되지 `x-amz-checksum-mode` 않습니다. 활성화된 상태로 요청에 `x-amz-checksum-mode` 포함하면 `Range` StorageGRID는 응답에 체크섬 값을 반환하지 않습니다.





== 지원되지 않는 요청 헤더입니다

다음 요청 헤더는 지원되지 않으며 `XNotImplemented` 반환됩니다.

* `x-amz-website-redirect-location`




== 버전 관리

하위 리소스가 지정되지 않은 경우 `versionId` 이 작업은 버전이 지정된 버킷에서 가장 최신 버전의 개체를 가져옵니다. 객체의 현재 버전이 삭제 마커인 경우 응답 헤더가 로 설정된 `true` 상태에서 "찾을 수 없음" 상태가 `x-amz-delete-marker` 반환됩니다.



== 고객이 제공한 암호화 키(SSE-C)를 사용하여 서버측 암호화를 위한 요청 헤더

사용자가 제공한 고유 키로 개체를 암호화한 경우 머리글 3개를 모두 사용합니다.

* `x-amz-server-side-encryption-customer-algorithm`: `AES256` 지정합니다.
* `x-amz-server-side-encryption-customer-key`: 개체의 암호화 키를 지정합니다.
* `x-amz-server-side-encryption-customer-key-MD5`: 개체의 암호화 키의 MD5 다이제스트를 지정합니다.



CAUTION: 제공한 암호화 키는 저장되지 않습니다. 암호화 키를 분실하면 해당 개체가 손실됩니다. 고객이 제공한 키를 사용하여 개체 데이터를 보호하기 전에 의 고려 사항을 검토하십시오link:using-server-side-encryption.html["서버측 암호화를 사용합니다"].



== 클라우드 스토리지 풀 객체에 대한 GetObject의 동작입니다

개체가 에 저장된 경우 link:../ilm/what-cloud-storage-pool-is.html["클라우드 스토리지 풀"]GetObject 요청의 동작은 개체의 상태에 따라 달라집니다. 자세한 내용은 을 link:head-object.html["HeadObject 를 선택합니다"]참조하십시오.


NOTE: 오브젝트가 클라우드 스토리지 풀에 저장되고 하나 이상의 오브젝트 복제본이 그리드에 있는 경우 GetObject 요청은 클라우드 스토리지 풀에서 검색하기 전에 그리드에서 데이터 검색을 시도합니다.

[cols="1a,1a"]
|===
| 개체의 상태입니다 | GetObject 의 동작입니다 


 a| 
StorageGRID로 수집되었지만 아직 ILM에 의해 평가되지 않은 오브젝트 또는 기존 스토리지 풀에 저장된 오브젝트 또는 삭제 코딩 사용
 a| 
`200 OK`

개체의 복사본이 검색됩니다.



 a| 
Cloud Storage Pool의 개체이지만 아직 검색할 수 없는 상태로 전환되지 않았습니다
 a| 
`200 OK`

개체의 복사본이 검색됩니다.



 a| 
개체가 검색할 수 없는 상태로 전환되었습니다
 a| 
`403 Forbidden`, `InvalidObjectState`

요청을 사용하여 link:post-object-restore.html["RestoreObject 를 선택합니다"]객체를 검색 가능한 상태로 복원합니다.



 a| 
복구할 수 없는 상태에서 복원 중인 개체입니다
 a| 
`403 Forbidden`, `InvalidObjectState`

RestoreObject 요청이 완료될 때까지 기다립니다.



 a| 
객체가 클라우드 스토리지 풀에 완전히 복구되었습니다
 a| 
`200 OK`

개체의 복사본이 검색됩니다.

|===


=== 클라우드 스토리지 풀에서 다중 또는 분할 오브젝트

여러 부분 개체를 업로드했거나 StorageGRID가 큰 개체를 세그먼트로 분할한 경우 StorageGRID는 개체의 부분 또는 세그먼트의 하위 집합을 샘플링하여 클라우드 저장소 풀에서 개체를 사용할 수 있는지 여부를 결정합니다. 개체의 일부 부분이 이미 검색할 수 없는 상태로 전환되었거나 개체의 일부 부분이 아직 복원되지 않은 경우 GetObject 요청이 잘못 반환될 수 `200 OK` 있습니다.

다음과 같은 경우:

* GetObject 요청에서 일부 데이터를 반환하지만 전송 도중에 중지됩니다.
* 이후의 GetObject 요청이 반환될 수 `403 Forbidden` 있습니다.




== GetObject 및 교차 그리드 복제

를 사용  중이며 link:../tenant/grid-federation-manage-cross-grid-replication.html["교차 그리드 복제"]버킷에 대해 활성화된 경우 link:../admin/grid-federation-overview.html["그리드 통합"]S3 클라이언트는 GetObject 요청을 실행하여 개체의 복제 상태를 확인할 수 있습니다. 응답에는 다음 값 중 하나가 있는 StorageGRID 관련 `x-ntap-sg-cgr-replication-status` 응답 헤더가 포함됩니다.

[cols="1a,2a"]
|===
| 그리드 | 복제 상태입니다 


 a| 
출처
 a| 
* * 완료됨 *: 복제가 성공했습니다.
* * 보류 중 *: 객체가 아직 복제되지 않았습니다.
* * 실패 *: 영구적인 장애로 인해 복제에 실패했습니다. 사용자가 오류를 해결해야 합니다.




 a| 
목적지
 a| 
* replica *: 객체가 소스 그리드에서 복제되었습니다.

|===

NOTE: StorageGRID는 헤더를 지원하지 `x-amz-replication-status` 않습니다.
