---
permalink: s3/index.html 
sidebar: sidebar 
keywords: about s3, s3 rest api, s3 overview 
summary: 'StorageGRID는 REST\(Representational State Transfer\) 웹 서비스 세트로 구현되는 S3(Simple Storage Service) API를 지원합니다.' 
---
= S3 REST API 지원 버전 및 업데이트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID는 REST(Representational State Transfer) 웹 서비스 세트로 구현되는 S3(Simple Storage Service) API를 지원합니다.

S3 REST API를 지원하므로 StorageGRID 시스템을 사용하는 사내 오브젝트 스토리지를 통해 S3 웹 서비스용으로 개발된 서비스 지향 애플리케이션을 연결할 수 있습니다. 클라이언트 애플리케이션의 현재 S3 REST API 호출 사용에 대한 최소 변경 사항이 필요합니다.



== 지원되는 버전

StorageGRID는 다음과 같은 S3 및 HTTP 버전을 지원합니다.

[cols="1a,1a"]
|===
| 항목 | 버전 


 a| 
S3 API 사양
 a| 
http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["AWS(Amazon Web Services) 문서: Amazon Simple Storage Service API Reference 를 참조하십시오"^]



 a| 
HTTP
 a| 
1.1

HTTP에 대한 자세한 내용은 HTTP/1.1(RFC 7230-35)을 참조하십시오.

https://datatracker.ietf.org/doc/html/rfc2616["IETF RFC 2616:HTTP/1.1(Hypertext Transfer Protocol)"^]

* 참고 *: StorageGRID는 HTTP/1.1 파이프라이닝을 지원하지 않습니다.

|===


== S3 REST API 지원 업데이트

[cols="1a,4a"]
|===
| 놓습니다 | 설명 


 a| 
11.9
 a| 
* 다음 요청 및 지원되는 헤더에 대해 미리 계산된 SHA-256 체크섬 값에 대한 지원이 추가되었습니다. 이 기능을 사용하여 업로드된 개체의 무결성을 확인할 수 있습니다.
+
** CompleteMultipartUpload: `x-amz-checksum-sha256`
** CreateMultipartUpload: `x-amz-checksum-algorithm`
** GetObject(개체 가져오기): `x-amz-checksum-mode`
** 제목 개체: `x-amz-checksum-mode`
** 목록 파트
** Put개체: `x-amz-checksum-sha256`
** 업로드 부품: `x-amz-checksum-sha256`


* 그리드 관리자가 테넌트 레벨 보존 및 규정 준수 설정을 제어할 수 있는 기능이 추가되었습니다. 이러한 설정은 S3 오브젝트 잠금 설정에 영향을 줍니다.
+
** 버킷 기본 보존 모드 및 객체 보존 모드: 그리드 관리자가 허용하는 경우 거버넌스 또는 규정 준수
** 버킷 기본 보존 기간 및 객체 유지 기한: 그리드 관리자가 설정한 최대 보존 기간에 허용되는 값보다 작거나 같아야 합니다.


* 콘텐츠 인코딩 및 스트리밍 `x-amz-content-sha256` 값에 대한 지원이 `aws-chunked` 향상되었습니다. 제한 사항:
+
** 있는 경우 `chunk-signature` 는 선택 사항이며 검증되지 않았습니다
** 있는 경우 `x-amz-trailer` 콘텐츠는 무시됩니다






 a| 
11.8
 a| 
에 사용된 이름과 일치하도록 S3 작업의 이름을 업데이트했습니다. http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["AWS(Amazon Web Services) 문서: Amazon Simple Storage Service API Reference 를 참조하십시오"^]



 a| 
11.7
 a| 
* link:quick-reference-support-for-aws-apis.html["빠른 참조: 지원되는 S3 API 요청"]추가되었습니다.
* S3 Object Lock을 통한 거버넌스 모드 사용을 지원합니다.
* Get Object 및 Head Object 요청에 대한 StorageGRID별 응답 헤더에 대한 지원이 추가되었습니다 `x-ntap-sg-cgr-replication-status`. 이 헤더는 크로스 그리드 복제를 위한 객체의 복제 상태를 제공합니다.
* SelectObjectContent 요청이 이제 Parquet 객체를 지원합니다.




 a| 
11.6
 a| 
* GET Object 및 HEAD Object 요청에서 REQUEST 매개 변수 사용에 대한 지원이 추가되었습니다 `partNumber`.
* S3 오브젝트 잠금의 버킷 레벨에서 기본 보존 모드 및 기본 보존 기간에 대한 지원이 추가되었습니다.
* 객체에 대해 허용되는 보존 기간의 범위를 설정하기 위해 정책 조건 키에 대한 지원이 추가되었습니다 `s3:object-lock-remaining-retention-days`.
* 단일 PUT 객체 작업의 Maximum_Recommended_size를 5GiB(5,368,709,120바이트)로 변경했습니다. 5GiB보다 큰 객체가 있는 경우 대신 멀티파트 업로드를 사용합니다.




 a| 
11.5
 a| 
* 버킷 암호화 관리에 대한 지원이 추가되었습니다.
* S3 오브젝트 잠금 및 더 이상 사용되지 않는 레거시 규정 준수 요청에 대한 지원 추가
* 버전이 있는 버킷에서 여러 오브젝트 삭제 사용에 대한 지원이 추가되었습니다.
*  `Content-MD5`이제 요청 헤더가 올바르게 지원됩니다.




 a| 
11.4
 a| 
* 버킷 태그 삭제, 버킷 태그 지정 가져오기 및 버킷 태그 지정을 위한 지원이 추가되었습니다. 비용 할당 태그는 지원되지 않습니다.
* StorageGRID 11.4에서 만든 버킷의 경우 성능 모범 사례에 맞게 개체 키 이름을 제한하는 것이 더 이상 필요하지 않습니다.
* 이벤트 유형에 버킷 알림에 대한 지원이 `s3:ObjectRestore:Post` 추가되었습니다.
* 이제 여러 파트에 대한 AWS 크기 제한이 적용됩니다. 멀티파트 업로드의 각 파트는 5MiB에서 5GiB 사이여야 합니다. 마지막 부분은 5MiB보다 작을 수 있습니다.
* TLS 1.3에 대한 지원이 추가되었습니다




 a| 
11.3
 a| 
* 고객이 제공한 키(SSE-C)를 사용하여 오브젝트 데이터의 서버측 암호화에 대한 지원이 추가되었습니다.
* 삭제, 가져오기 및 넣기 버킷 라이프사이클 작업(만료 작업에만 해당) 및 응답 헤더에 대한 지원이 추가되었습니다 `x-amz-expiration`.
* 수집 시 동기식 배치를 사용하는 ILM 규칙의 영향을 설명하기 위해 PUT 개체, Put Object-Copy 및 MultiPart Upload가 업데이트되었습니다.
* TLS 1.1 암호가 더 이상 지원되지 않습니다.




 a| 
11.2
 a| 
클라우드 스토리지 풀과 함께 사용할 POST 오브젝트 복원에 대한 지원이 추가되었습니다. 그룹 및 버킷 정책에서 ARN, 정책 조건 키 및 정책 변수에 대해 AWS 구문 사용을 지원합니다. StorageGRID 구문을 사용하는 기존 그룹 및 버킷 정책은 계속 지원됩니다.

* 참고: * 사용자 지정 StorageGRID 기능에 사용되는 것을 포함하여 다른 구성 JSON/XML에서 ARN/URN을 사용하는 것은 변경되지 않았습니다.



 a| 
11.1
 a| 
CORS(Cross-Origin Resource Sharing), 그리드 노드에 대한 S3 클라이언트 연결을 위한 HTTP 및 버킷에 대한 규정 준수 설정에 대한 지원이 추가되었습니다.



 a| 
11.0
 a| 
버킷에 대한 플랫폼 서비스(CloudMirror 복제, 알림 및 Elasticsearch 검색 통합) 구성 지원 추가 또한 버킷에 대한 객체 태그 위치 제약 조건 및 사용 가능한 정합성 보장에 대한 지원이 추가되었습니다.



 a| 
10.4
 a| 
버전 관리, 끝점 도메인 이름 페이지 업데이트, 정책, 정책 예제 및 PutOverwriteObject 권한에 대한 ILM 검색 변경 사항에 대한 지원이 추가되었습니다.



 a| 
10.3
 a| 
버전 관리 지원 추가.



 a| 
10.2
 a| 
그룹 및 버킷 액세스 정책 및 다중 파트 복제본(업로드 부분 복사)에 대한 지원이 추가되었습니다.



 a| 
10.1
 a| 
멀티파트 업로드, 가상 호스팅 스타일 요청 및 v4 인증에 대한 지원이 추가되었습니다.



 a| 
10.0
 a| 
StorageGRID 시스템에서 S3 REST API의 초기 지원. 현재 지원되는 _Simple Storage Service API Reference_는 2006-03-01입니다.

|===