---
permalink: s3/initiate-multipart-upload.html 
sidebar: sidebar 
keywords: initiate multipart upload, CreateMultipartUpload, upload ID 
summary: CreateMultipartUpload 작업은 개체에 대한 다중 부분 업로드를 시작하고 업로드 ID를 반환합니다. 
---
= CreateMultptUpload 를 클릭합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CreateMultipartUpload(이전에 이름이 Multipart Upload 시작) 작업은 개체에 대한 다중 부분 업로드를 시작하고 업로드 ID를 반환합니다.

 `x-amz-storage-class`요청 헤더가 지원됩니다. 에 제출된 `x-amz-storage-class` 값은 StorageGRID 시스템(ILM에 의해 결정됨)에 저장되는 오브젝트의 영구 사본의 수가 아니라 수집 중에 StorageGRID가 오브젝트 데이터를 보호하는 방법에 영향을 줍니다.

수집된 객체와 일치하는 ILM 규칙이 Strict 를 사용하는 경우 link:../ilm/data-protection-options-for-ingest.html["수집 옵션"] `x-amz-storage-class`헤더는 영향을 미치지 않습니다.

다음 값을 사용할 수 `x-amz-storage-class` 있습니다.

* `STANDARD` (기본값)
+
** * Dual Commit *: ILM 규칙이 Dual Commit Ingest 옵션을 지정하는 경우 오브젝트가 수집되는 즉시 해당 오브젝트의 두 번째 복사본이 생성되어 다른 스토리지 노드(Dual Commit)로 배포됩니다. ILM을 평가할 때 StorageGRID는 이러한 초기 중간 복사본이 규칙의 배치 지침을 충족하는지 여부를 결정합니다. 그렇지 않으면 새 오브젝트 복사본을 다른 위치에 만들어야 하고 초기 중간 복사본을 삭제해야 할 수 있습니다.
** * 균형 *: ILM 규칙이 균형 옵션을 지정하고 StorageGRID이 규칙에 지정된 모든 복사본을 즉시 만들 수 없는 경우 StorageGRID은 다른 스토리지 노드에 두 개의 임시 복사본을 만듭니다.
+
StorageGRID가 ILM 규칙(동기식 배치)에 지정된 모든 오브젝트 복사본을 즉시 생성할 수 있다면 `x-amz-storage-class` 헤더는 효과가 없습니다.



* `REDUCED_REDUNDANCY`
+
** * Dual Commit *: ILM 규칙이 Dual Commit 옵션을 지정하는 경우 StorageGRID는 개체가 수집될 때(단일 커밋) 하나의 중간 복사본을 생성합니다.
** * 균형 *: ILM 규칙이 균형 옵션을 지정하는 경우 StorageGRID은 시스템에서 규칙에 지정된 모든 사본을 즉시 만들 수 없는 경우에만 단일 중간 복사본을 만듭니다. StorageGRID에서 동기 배치를 수행할 수 있는 경우 이 머리글은 영향을 주지 않습니다. 이 `REDUCED_REDUNDANCY` 옵션은 오브젝트와 일치하는 ILM 규칙이 복제된 단일 복사본을 생성할 때 가장 적합합니다. 이 경우 를 `REDUCED_REDUNDANCY` 사용하면 모든 수집 작업에서 불필요한 추가 오브젝트 복사본을 생성하여 삭제할 필요가 없습니다.


+
다른 상황에서는 이 옵션을 사용하지 `REDUCED_REDUNDANCY` 않는 것이 좋습니다. `REDUCED_REDUNDANCY` 수집 중 오브젝트 데이터가 손실될 위험이 증가함 예를 들어, ILM 평가가 발생하기 전에 실패한 스토리지 노드에 단일 복사본이 처음 저장되는 경우 데이터가 손실될 수 있습니다.




CAUTION: 복제된 복사본이 항상 하나만 있으면 데이터가 영구적으로 손실될 위험이 있습니다. 복제된 객체 복제본이 하나만 있는 경우 스토리지 노드에 장애가 발생하거나 심각한 오류가 발생한 경우 해당 객체가 손실됩니다. 또한 업그레이드와 같은 유지보수 절차 중에는 개체에 대한 액세스가 일시적으로 중단됩니다.

 `REDUCED_REDUNDANCY`지정하면 오브젝트를 처음 수집할 때 생성되는 복사본의 개수만 영향을 줍니다. 활성 ILM 정책에 따라 오브젝트를 평가할 때 생성되는 오브젝트 복사본 수에 영향을 미치지 않으며 StorageGRID 시스템에서 더 낮은 수준의 이중화로 데이터가 저장되지는 않습니다.


NOTE: S3 오브젝트 잠금이 설정된 상태에서 오브젝트를 버킷에 수집하면 `REDUCED_REDUNDANCY` 옵션이 무시됩니다. 오브젝트를 레거시 준수 버킷에 수집하는 경우 `REDUCED_REDUNDANCY` 옵션은 오류를 반환합니다. StorageGRID은 규정 준수 요구 사항이 충족될 수 있도록 항상 이중 커밋 수집을 수행합니다.



== 지원되는 요청 헤더입니다

지원되는 요청 헤더는 다음과 같습니다.

* `Content-Type`
* `x-amz-checksum-algorithm`
+
현재는 의 SHA256 값만 `x-amz-checksum-algorithm` 지원됩니다.

* `x-amz-meta-`, 그 뒤에 사용자 정의 메타데이터를 포함하는 이름-값 쌍이 옵니다
+
사용자 정의 메타데이터에 대한 이름 값 쌍을 지정할 때 다음 일반 형식을 사용합니다.

+
[listing]
----
x-amz-meta-_name_: `value`
----
+
사용자 정의 생성 시간 * 옵션을 ILM 규칙의 참조 시간으로 사용하려면 객체를 생성할 때 기록하는 메타데이터의 이름으로 를 사용해야 `creation-time` 합니다. 예를 들면 다음과 같습니다.

+
[listing]
----
x-amz-meta-creation-time: 1443399726
----
+
의 값은 `creation-time` 1970년 1월 1일 이후 초로 계산됩니다.

+

NOTE:  `creation-time`기존 Compliance가 활성화된 버킷에 오브젝트를 추가하는 경우 사용자 정의 메타데이터로 추가할 수 없습니다. 오류가 반환됩니다.

* S3 오브젝트 잠금 요청 헤더:
+
** `x-amz-object-lock-mode`
** `x-amz-object-lock-retain-until-date`
** `x-amz-object-lock-legal-hold`
+
이러한 헤더 없이 요청이 이루어지면 버킷 기본 보존 설정을 사용하여 개체 버전 보존 기간을 계산합니다.

+
link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 오브젝트 잠금을 구성합니다"]



* SSE 요청 헤더:
+
** `x-amz-server-side-encryption`
** `x-amz-server-side-encryption-customer-key-MD5`
** `x-amz-server-side-encryption-customer-key`
** `x-amz-server-side-encryption-customer-algorithm`
+
<<서버측 암호화에 대한 요청 헤더>>



+

NOTE: StorageGRID에서 UTF-8 문자를 처리하는 방법에 대한 자세한 내용은 을 참조하십시오link:put-object.html["PutObject 를 선택합니다"].





== 서버측 암호화에 대한 요청 헤더

다음 요청 헤더를 사용하여 서버측 암호화를 사용하여 다중 파트 개체를 암호화할 수 있습니다. SSE 및 SSE-C 옵션은 상호 배타적입니다.

* * sse *: StorageGRID에서 관리하는 고유 키로 개체를 암호화하려면 CreateMultipartUpload 요청에서 다음 헤더를 사용합니다. UploadPart 요청에는 이 헤더를 지정하지 마십시오.
+
** `x-amz-server-side-encryption`


* * SSE-C *: 제공 및 관리하는 고유 키로 개체를 암호화하려면 CreateMultipartUpload 요청(및 이후의 각 UploadPart 요청)에 이 헤더 세 개를 모두 사용하십시오.
+
** `x-amz-server-side-encryption-customer-algorithm`: `AES256` 지정합니다.
** `x-amz-server-side-encryption-customer-key`: 새 개체에 대한 암호화 키를 지정합니다.
** `x-amz-server-side-encryption-customer-key-MD5`: 새 개체의 암호화 키의 MD5 다이제스트를 지정합니다.





CAUTION: 제공한 암호화 키는 저장되지 않습니다. 암호화 키를 분실하면 해당 개체가 손실됩니다. 고객이 제공한 키를 사용하여 개체 데이터를 보호하기 전에 에 대한 고려 사항을 link:using-server-side-encryption.html["서버 측 암호화 사용"]검토하십시오.



== 지원되지 않는 요청 헤더입니다

다음 요청 헤더는 지원되지 않습니다.

* `x-amz-website-redirect-location`
+
 `x-amz-website-redirect-location`헤더가 를 `XNotImplemented`반환합니다.





== 버전 관리

멀티파트 업로드는 업로드 시작, 리스팅 업로드, 파트 업로드, 업로드된 파트 조립 및 업로드 완료를 위한 별도의 작업으로 구성됩니다. CompleteMultipartUpload 작업이 수행될 때 객체가 생성되고 해당되는 경우 버전이 지정됩니다.
