---
permalink: s3/object-versioning.html 
sidebar: sidebar 
keywords: object version, object versioning 
summary: 오브젝트의 여러 버전을 유지하려면 버킷의 버전 관리 상태를 설정할 수 있습니다. 버킷에 대한 버전 관리를 사용하면 실수로 개체가 삭제되지 않도록 보호하고 이전 버전의 개체를 검색 및 복원할 수 있습니다. 
---
= 오브젝트 버전 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 오브젝트의 여러 버전을 유지하려면 버킷의 버전 관리 상태를 설정할 수 있습니다. 버킷에 대한 버전 관리를 사용하면 실수로 개체가 삭제되지 않도록 보호하고 이전 버전의 개체를 검색 및 복원할 수 있습니다.

StorageGRID 시스템은 대부분의 기능을 지원하는 버전 관리를 구현하지만 몇 가지 제한 사항이 있습니다. StorageGRID는 각 오브젝트의 버전을 최대 10,000개까지 지원합니다.

오브젝트 버전 관리를 StorageGRID ILM(정보 라이프사이클 관리) 또는 S3 버킷 라이프사이클 구성과 결합할 수 있습니다. 각 버킷에 대해 버전 관리를 명시적으로 설정해야 합니다. 버킷에 대해 버전 관리를 사용하도록 설정하면 버킷에 추가된 각 오브젝트에 버전 ID가 할당되며, StorageGRID 시스템에서 생성됩니다.

MFA(다중 요소 인증) 삭제 사용은 지원되지 않습니다.


NOTE: 버전 관리는 StorageGRID 버전 10.3 이상으로 생성된 버킷에서만 사용할 수 있습니다.



== ILM 및 버전 관리

ILM 정책은 개체의 각 버전에 적용됩니다. ILM 스캔 프로세스는 모든 개체를 지속적으로 스캔하고 현재 ILM 정책에 대해 다시 평가합니다. ILM 정책에 대한 모든 변경 사항은 이전에 수집된 모든 개체에 적용됩니다. 여기에는 버전 관리가 활성화된 경우 이전에 수집된 버전이 포함됩니다. ILM 스캐닝은 이전에 수집된 개체에 새로운 ILM 변경 사항을 적용합니다.

버전 관리 지원 버킷의 S3 객체의 경우 버전 관리 지원을 통해 "현재 시간"을 참조 시간으로 사용하는 ILM 규칙을 만들 수 있습니다(의 "이전 객체 버전에만 이 규칙을 적용하시겠습니까?"라는 질문에 대해 * 예 * 를 선택link:../ilm/create-ilm-rule-enter-details.html["ILM 규칙 만들기 마법사의 1단계"]). 개체가 업데이트되면 이전 버전은 업데이트되지 않습니다. "비현재 시간" 필터를 사용하면 이전 버전의 객체가 스토리지에 미치는 영향을 줄이는 정책을 만들 수 있습니다.


NOTE: 다중 파트 업로드 작업을 사용하여 새 버전의 개체를 업로드할 때 개체의 원래 버전에 대한 비현재 시간은 다중 파트 업로드가 완료될 때가 아닌 새 버전에 대해 다중 파트 업로드가 생성된 시점을 반영합니다. 제한된 경우 원래 버전의 비현재 시간이 현재 버전의 시간보다 몇 시간 또는 며칠 빨라질 수 있습니다.

.관련 정보
* link:../ilm/how-objects-are-deleted.html#delete-s3-versioned-objects["S3 버전 오브젝트 삭제 방법"]
* link:../ilm/example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["S3 버전 오브젝트 ILM 규칙 및 정책(예 4)"]..

