---
permalink: s3/put-bucket-consistency-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, PUT bucket consistency request 
summary: Put Bucket Consistency 요청을 사용하면 버킷에서 수행된 작업에 적용할 일관성을 지정할 수 있습니다. 
---
= 버킷 일관성을 유지합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Put Bucket Consistency 요청을 사용하면 버킷에서 수행된 작업에 적용할 일관성을 지정할 수 있습니다.

기본 정합성 보장은 새로 생성된 개체에 대해 쓰기 후 읽기를 보장하도록 설정됩니다.

.시작하기 전에
이 작업을 완료하려면 S3:PutBucketConsistency 권한이 있거나 계정 루트여야 합니다.



== 요청하십시오

매개 변수에는 `x-ntap-sg-consistency` 다음 값 중 하나가 포함되어야 합니다.

[cols="1a,2a"]
|===
| 정합성 | 설명 


 a| 
모두
 a| 
모든 노드가 데이터를 즉시 수신하거나 요청이 실패합니다.



 a| 
강함 - 글로벌
 a| 
모든 사이트에서 모든 클라이언트 요청에 대해 쓰기 후 읽기 정합성을 보장합니다.



 a| 
강력한 사이트
 a| 
사이트 내의 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.



 a| 
읽기-후-새로-쓰기
 a| 
(기본값) 새 객체에 대한 읽기 후 쓰기 정합성을 보장하고 객체 업데이트에 대한 최종 일관성을 제공합니다. 고가용성 및 데이터 보호 보장 제공 대부분의 경우에 권장됩니다.



 a| 
사용 가능
 a| 
새 개체 및 개체 업데이트 모두에 대한 최종 일관성을 제공합니다. S3 버킷의 경우 필요한 경우에만 사용하십시오(예: 거의 읽지 않는 로그 값이 포함된 버킷의 경우 또는 존재하지 않는 키의 헤드 또는 GET 작업의 경우). S3 FabricPool 버킷은 지원되지 않습니다.

|===
* 참고: * 일반적으로 "Read-after-new-write" 일관성을 사용해야 합니다. 요청이 올바르게 작동하지 않는 경우 가능한 경우 응용 프로그램 클라이언트 동작을 변경합니다. 또는 각 API 요청의 일관성을 지정하도록 클라이언트를 구성합니다. 버킷 수준의 일관성을 마지막 수단으로 설정합니다.



== 요청 예

[listing, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-consistency=strong-global HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
.관련 정보
link:consistency.html["정합성"]
