---
permalink: s3/put-bucket-last-access-time-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, put bucket last access time request 
summary: '[버킷 최종 액세스 시간 가져오기(Get Bucket Last Access Time) 요청 을 사용하면 개별 버킷에 대해 마지막 액세스 시간 업데이트가 활성화되거나 비활성화되었는지 확인할 수 있습니다.' 
---
= 버킷 최종 접근 시간
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Put Bucket Last Access Time 요청을 사용하면 개별 버킷에 대한 마지막 액세스 시간 업데이트를 활성화하거나 비활성화할 수 있습니다. 마지막 액세스 시간 업데이트를 비활성화하면 성능이 향상되고 버전 10.3.0 이상으로 생성된 모든 버킷의 기본 설정이 됩니다.

이 작업을 완료하려면 버킷에 대한 S3:PutBuckketLastAccessTime 권한이 있거나 계정 루트여야 합니다.


NOTE: StorageGRID 버전 10.3부터는 모든 새 버킷에 대해 마지막 액세스 시간에 대한 업데이트가 기본적으로 비활성화됩니다. 이전 버전의 StorageGRID를 사용하여 만든 버킷이 있고 새 기본 동작과 일치시키려면 이전의 각 버킷에 대해 마지막 액세스 시간 업데이트를 명시적으로 비활성화해야 합니다. Put Bucket 마지막 액세스 시간 요청을 사용하거나 Tenant Manager의 버킷에 대한 세부 정보 페이지에서 마지막 액세스 시간에 대한 업데이트를 활성화 또는 비활성화할 수 있습니다. 을 link:../tenant/enabling-or-disabling-last-access-time-updates.html["마지막 액세스 시간 업데이트를 사용하거나 사용하지 않도록 설정합니다"]참조하십시오.

버킷에 대해 마지막 액세스 시간 업데이트가 비활성화된 경우 버킷의 작업에 다음 동작이 적용됩니다.

* GetObject, GetObjectAcl, GetObjectTagging 및 HeadObject 요청은 마지막 액세스 시간을 업데이트하지 않습니다. ILM(정보 수명 주기 관리) 평가를 위해 객체가 대기열에 추가되지 않습니다.
* 메타데이터만 업데이트하는 CopyObject 및 PutObjectTagging 요청도 마지막 액세스 시간을 업데이트합니다. ILM 평가를 위해 오브젝트가 대기열에 추가됩니다.
* 소스 버킷에 대해 마지막 액세스 시간에 대한 업데이트를 사용할 수 없는 경우 CopyObject 요청이 소스 버킷의 마지막 액세스 시간을 업데이트하지 않습니다. 복사된 객체는 소스 버킷에 대한 ILM 평가를 위해 대기열에 추가되지 않습니다. 그러나 대상의 경우 CopyObject 요청은 항상 마지막 액세스 시간을 업데이트합니다. ILM 평가를 위해 개체의 복사본이 대기열에 추가됩니다.
* CompleteMultipartUpload 요청이 마지막 액세스 시간을 업데이트합니다. 완료된 객체가 ILM 평가를 위해 대기열에 추가됩니다.




== 예를 요청하십시오

이 예제에서는 버킷의 마지막 액세스 시간을 설정합니다.

[listing, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-lastaccesstime=enabled HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----
이 예제에서는 버킷의 마지막 액세스 시간을 비활성화합니다.

[listing, subs="specialcharacters,quotes"]
----
PUT /bucket?x-ntap-sg-lastaccesstime=disabled HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----