---
permalink: s3/upload-part.html 
sidebar: sidebar 
keywords: s3 UploadPart operation 
summary: UploadPart 작업은 객체에 대한 다중 부분 업로드의 파트를 업로드합니다. 
---
= 업로드 파트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UploadPart 작업은 객체에 대한 다중 부분 업로드의 파트를 업로드합니다.



== 지원되는 요청 헤더입니다

지원되는 요청 헤더는 다음과 같습니다.

* `x-amz-checksum-sha256`
* `Content-Length`
* `Content-MD5`




== 서버측 암호화에 대한 요청 헤더

CreateMultipartUpload 요청에 대해 SSE-C 암호화를 지정한 경우 각 UploadPart 요청에 다음 요청 머리글도 포함해야 합니다.

* `x-amz-server-side-encryption-customer-algorithm`: `AES256` 지정합니다.
* `x-amz-server-side-encryption-customer-key`: CreateMultipartUpload 요청에서 제공한 것과 동일한 암호화 키를 지정합니다.
* `x-amz-server-side-encryption-customer-key-MD5`: CreateMultipartUpload 요청에 제공한 것과 동일한 MD5 다이제스트를 지정합니다.



CAUTION: 제공한 암호화 키는 저장되지 않습니다. 암호화 키를 분실하면 해당 개체가 손실됩니다. 고객이 제공한 키를 사용하여 개체 데이터를 보호하기 전에 의 고려 사항을 검토하십시오link:using-server-side-encryption.html["서버측 암호화를 사용합니다"].

CreateMultipartUpload 요청 중에 SHA-256 체크섬을 지정한 경우 각 UploadPart 요청에 다음 요청 헤더도 포함해야 합니다.

* `x-amz-checksum-sha256`: 이 부품에 대한 SHA-256 체크섬을 지정합니다.




== 지원되지 않는 요청 헤더입니다

다음 요청 헤더는 지원되지 않습니다.

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`




== 버전 관리

멀티파트 업로드는 업로드 시작, 리스팅 업로드, 파트 업로드, 업로드된 파트 조립 및 업로드 완료를 위한 별도의 작업으로 구성됩니다. CompleteMultipartUpload 작업이 수행될 때 객체가 생성되고 해당되는 경우 버전이 지정됩니다.
