---
permalink: monitor/access-snmp-mib.html 
sidebar: sidebar 
keywords: mib, snmp, monitoring 
summary: MIB 파일에는 그리드의 노드에 대한 관리되는 리소스 및 서비스의 속성에 대한 정의 및 정보가 들어 있습니다. StorageGRID에 대한 객체 및 알림을 정의하는 MIB 파일에 액세스할 수 있습니다. 이러한 파일은 그리드를 모니터링하는 데 유용할 수 있습니다. 
---
= MIB 파일에 액세스합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MIB 파일에는 그리드의 노드에 대한 관리되는 리소스 및 서비스의 속성에 대한 정의 및 정보가 들어 있습니다. StorageGRID에 대한 객체 및 알림을 정의하는 MIB 파일에 액세스할 수 있습니다. 이러한 파일은 그리드를 모니터링하는 데 유용할 수 있습니다.

SNMP 및 MIB 파일에 대한 자세한 내용은 을 link:using-snmp-monitoring.html["SNMP 모니터링을 사용합니다"]참조하십시오.



== MIB 파일에 액세스합니다

MIB 파일에 액세스하려면 다음 단계를 수행하십시오.

.단계
. 구성 * > * 모니터링 * > * SNMP 에이전트 * 를 선택합니다.
. SNMP 에이전트 페이지에서 다운로드할 파일을 선택합니다.
+
** * NetApp-StorageGrid-MIB.txt *: 모든 관리 노드에서 액세스할 수 있는 알림 테이블 및 알림(트랩)을 정의합니다.
** * ES-NetApp-06-MIB.MIB *: E-Series 기반 어플라이언스에 대한 객체 및 알림을 정의합니다.
** * MIB_1_10.zip *: BMC 인터페이스를 사용하는 어플라이언스에 대한 객체 및 알림을 정의합니다.
+
[]
====

TIP: StorageGRID 노드의 다음 위치에서 MIB 파일에 액세스할 수도 있습니다. `/usr/share/snmp/mibs`

====


. MIB 파일에서 StorageGRID OID를 추출하려면:
+
.. StorageGRID MIB 루트의 OID를 가져옵니다.
+
`root@user-adm1:~ # snmptranslate -On -IR storagegrid`

+
결과 `.1.3.6.1.4.1.789.28669` (`28669`: 항상 StorageGRID의 OID입니다.)

.. 전체 트리에서 StorageGRID OID에 대한 GRIP(라인 합치기 위해 사용 `paste`):
+
`root@user-adm1:~ # snmptranslate -Tso | paste -d " " - - | grep 28669`






TIP:  `snmptranslate`명령에는 MIB를 탐색하는 데 유용한 여러 옵션이 있습니다. 이 명령은 모든 StorageGRID 노드에서 사용할 수 있습니다.



== MIB 파일 내용

모든 객체는 StorageGRID OID 아래에 있습니다.

[cols="1a,1a,2a"]
|===
| 개체 이름 | OID(개체 ID) | 설명 


| .iso.org.dod.internet 참조하십시오. 더 많은 프라이빗 클라우드 및 엔터프라이즈 NetApp과 StorageGrid가 더 적합합니다 | 1.3.6.1.4.1.789.28669  a| 
NetApp StorageGRID 엔터티용 MIB 모듈

|===


== MIB 개체

[cols="1a,1a,2a"]
|===
| 개체 이름 | OID(개체 ID) | 설명 


| 활성 경고 수 | .1.3.6.1.4.1. +789.28669.1.3  a| 
활성 경고 테이블의 활성 경고 수입니다.



| 활성 경고 테이블 | .1.3.6.1.4.1. +789.28669.1.4  a| 
StorageGRID의 활성 경고 테이블



| 활성 경고 ID입니다 | .1.3.6.1.4.1. +789.28669.1.4.1.1  a| 
알림의 ID입니다. 현재 활성 알림 집합에서 고유한 항목만 표시됩니다.



| 활성 경고 이름 | .1.3.6.1.4.1. +789.28669.1.4.1.2  a| 
알림의 이름입니다.



| 활성 경고 인스턴스 | .1.3.6.1.4.1. +789.28669.1.4.1.3  a| 
알림을 생성한 엔터티의 이름, 일반적으로 노드 이름입니다.



| 활성 경고 심각도 | .1.3.6.1.4.1. +789.28669.1.4.1.4  a| 
알림의 심각도입니다.



| 활성 경고 시작 시간 | .1.3.6.1.4.1. +789.28669.1.4.1.5  a| 
알림이 트리거된 날짜 및 시간입니다.

|===


== 알림 유형(트랩)

모든 알림은 varbind로 다음 변수를 포함합니다.

* 활성 경고 ID입니다
* 활성 경고 이름
* 활성 경고 인스턴스
* 활성 경고 심각도
* 활성 경고 시작 시간


[cols="1a,1a,2a"]
|===
| 알림 유형입니다 | OID(개체 ID) | 설명 


| 활성 MinorAlert | .1.3.6.1.4.1. +789.28669.0.6  a| 
경미하게 심각도가 있는 경고



| 활성 MajorAlert | .1.3.6.1.4.1. +789.28669.0.7  a| 
심각도를 나타내는 경고입니다



| 활성 CriticalAlert | .1.3.6.1.4.1. +789.28669.0.8  a| 
심각도를 나타내는 경고입니다

|===