---
permalink: monitor/alerts-reference.html 
sidebar: sidebar 
keywords: alerts reference 
summary: 이 참조에는 Grid Manager에 나타나는 기본 경고가 나열됩니다. 권장 조치는 수신하는 경고 메시지에 있습니다. 
---
= 경고 참조
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 참조에는 Grid Manager에 나타나는 기본 경고가 나열됩니다. 권장 조치는 수신하는 경고 메시지에 있습니다.

필요에 따라 시스템 관리 방식에 맞게 사용자 지정 경고 규칙을 만들 수 있습니다.

일부 기본 알림은 을 link:commonly-used-prometheus-metrics.html["Prometheus 측정 지표"]사용합니다.



== 어플라이언스 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
어플라이언스 배터리가 만료되었습니다
 a| 
제품의 저장소 컨트롤러 배터리가 만료되었습니다.



 a| 
어플라이언스 배터리 고장
 a| 
제품의 저장소 컨트롤러 에 있는 배터리가 실패했습니다.



 a| 
어플라이언스 배터리가 학습된 용량이 부족합니다
 a| 
제품의 저장 장치 컨트롤러의 배터리가 학습된 용량이 부족합니다.



 a| 
어플라이언스 배터리 수명이 거의 다 되었습니다
 a| 
어플라이언스 저장소 컨트롤러의 배터리 수명이 거의 다했습니다.



 a| 
제품 배터리가 제거되었습니다
 a| 
제품의 저장 컨트롤러에 배터리가 없습니다.



 a| 
제품 배터리가 너무 뜨겁습니다
 a| 
제품 보관 컨트롤러의 배터리가 과열되었습니다.



 a| 
어플라이언스 BMC 통신 오류입니다
 a| 
베이스보드 관리 컨트롤러(BMC)와의 통신이 끊어졌습니다.



 a| 
어플라이언스 부팅 장치 오류가 감지되었습니다
 a| 
어플라이언스의 부팅 장치에서 문제가 감지되었습니다.



 a| 
어플라이언스 캐시 백업 디바이스에 장애가 발생했습니다
 a| 
영구 캐시 백업 디바이스가 실패했습니다.



 a| 
어플라이언스 캐시 백업 디바이스의 용량이 부족합니다
 a| 
캐시 백업 디바이스 용량이 부족합니다.



 a| 
어플라이언스 캐시 백업 디바이스 쓰기 방지
 a| 
캐시 백업 디바이스가 쓰기 금지되어 있습니다.



 a| 
어플라이언스 캐시 메모리 크기가 일치하지 않습니다
 a| 
어플라이언스의 두 컨트롤러는 캐시 크기가 다릅니다.



 a| 
어플라이언스 CMOS 배터리 오류입니다
 a| 
어플라이언스의 CMOS 배터리에서 문제가 감지되었습니다.



 a| 
어플라이언스의 컴퓨팅 컨트롤러 섀시 온도가 너무 높습니다
 a| 
StorageGRID 어플라이언스의 컴퓨팅 컨트롤러 온도가 공칭 임계값을 초과했습니다.



 a| 
어플라이언스의 컴퓨팅 컨트롤러 CPU 온도가 너무 높습니다
 a| 
StorageGRID 어플라이언스의 컴퓨팅 컨트롤러에 있는 CPU 온도가 공칭 임계값을 초과했습니다.



 a| 
어플라이언스 컴퓨팅 컨트롤러에 주의가 필요합니다
 a| 
StorageGRID 어플라이언스의 컴퓨팅 컨트롤러에서 하드웨어 장애가 감지되었습니다.



 a| 
어플라이언스 컴퓨팅 컨트롤러 전원 공급 장치 A에 문제가 있습니다
 a| 
컴퓨팅 컨트롤러의 전원 공급 장치 A에 문제가 있습니다.



 a| 
어플라이언스 컴퓨팅 컨트롤러 전원 공급 장치 B에 문제가 있습니다
 a| 
컴퓨팅 컨트롤러의 전원 공급 장치 B에 문제가 있습니다.



 a| 
어플라이언스 컴퓨팅 하드웨어 모니터 서비스가 중단되었습니다
 a| 
스토리지 하드웨어 상태를 모니터링하는 서비스가 중단되었습니다.



 a| 
어플라이언스 DAS 드라이브가 일일 데이터 쓰기 제한을 초과합니다
 a| 
매일 과도한 양의 데이터가 드라이브에 기록되고 있으므로 보증이 무효화될 수 있습니다.



 a| 
어플라이언스 DAS 드라이브 장애가 감지되었습니다
 a| 
어플라이언스의 DAS(직접 연결 스토리지) 드라이브에서 문제가 감지되었습니다.



 a| 
어플라이언스 DAS 드라이브 로케이터 표시등이 켜집니다
 a| 
어플라이언스 스토리지 노드에서 하나 이상의 DAS(직접 연결 스토리지) 드라이브에 대한 드라이브 로케이터 표시등이 켜져 있습니다.



 a| 
어플라이언스 DAS 드라이브 재구축
 a| 
DAS(직접 연결 스토리지) 드라이브를 재구축하고 있습니다. 이는 최근에 교체 또는 제거/재삽입된 경우에 발생합니다.



 a| 
어플라이언스 팬 장애가 감지되었습니다
 a| 
제품의 팬 장치에 문제가 감지되었습니다.



 a| 
어플라이언스 Fibre Channel 장애가 감지되었습니다
 a| 
어플라이언스 스토리지 컨트롤러와 컴퓨팅 컨트롤러 간에 파이버 채널 링크 문제가 감지되었습니다



 a| 
어플라이언스 Fibre Channel HBA 포트 오류입니다
 a| 
Fibre Channel HBA 포트에 장애가 발생했거나 장애가 발생했습니다.



 a| 
어플라이언스 플래시 캐시 드라이브가 최적이 아닙니다
 a| 
SSD 캐시에 사용되는 드라이브가 최적화되지 않았습니다.



 a| 
어플라이언스 상호 연결/배터리 캐니스터가 제거되었습니다
 a| 
상호 연결/배터리 캐니스터가 없습니다.



 a| 
어플라이언스 LACP 포트가 누락되었습니다
 a| 
StorageGRID 어플라이언스의 포트가 LACP 결합에 사용되고 있지 않습니다.



 a| 
어플라이언스 NIC 장애가 감지되었습니다
 a| 
어플라이언스의 네트워크 인터페이스 카드(NIC)에 문제가 감지되었습니다.



 a| 
어플라이언스의 전체 전원 공급 장치 성능이 저하되었습니다
 a| 
StorageGRID 제품의 전원이 권장 작동 전압을 벗어나 있습니다.



 a| 
어플라이언스 SSD 위험 경고
 a| 
어플라이언스 SSD가 심각한 경고를 보고합니다.



 a| 
어플라이언스 스토리지 컨트롤러 A에 장애가 발생했습니다
 a| 
StorageGRID 어플라이언스의 스토리지 컨트롤러 A에 장애가 발생했습니다.



 a| 
어플라이언스 스토리지 컨트롤러 B에 장애가 발생했습니다
 a| 
StorageGRID 어플라이언스의 스토리지 컨트롤러 B에 장애가 발생했습니다.



 a| 
어플라이언스 스토리지 컨트롤러 드라이브 오류입니다
 a| 
StorageGRID 어플라이언스에 있는 하나 이상의 드라이브가 실패했거나 최적이 아닙니다.



 a| 
어플라이언스 스토리지 컨트롤러 하드웨어 문제입니다
 a| 
SANtricity 소프트웨어가 StorageGRID 어플라이언스의 구성 요소에 대해 "주의 필요"를 보고하고 있습니다.



 a| 
어플라이언스 스토리지 컨트롤러 전원 공급 장치 A 고장
 a| 
StorageGRID 제품의 전원 공급 장치 A가 권장 작동 전압을 벗어나고 있습니다.



 a| 
어플라이언스 스토리지 컨트롤러 전원 공급 장치 B 오류입니다
 a| 
StorageGRID 제품의 전원 공급 장치 B가 권장 작동 전압을 벗어나 있습니다.



 a| 
어플라이언스 스토리지 하드웨어 모니터 서비스가 중단되었습니다
 a| 
스토리지 하드웨어 상태를 모니터링하는 서비스가 중단되었습니다.



 a| 
어플라이언스 스토리지 쉘프 성능이 저하되었습니다
 a| 
스토리지 어플라이언스의 스토리지 쉘프에 있는 구성 요소 중 하나의 상태가 성능 저하입니다.



 a| 
제품 온도가 초과되었습니다
 a| 
제품 보관 컨트롤러의 공칭 또는 최대 온도를 초과했습니다.



 a| 
제품 온도 센서가 제거되었습니다
 a| 
온도 센서가 제거되었습니다.



 a| 
어플라이언스 UEFI 보안 부팅 오류
 a| 
어플라이언스가 안전하게 부팅되지 않았습니다.



 a| 
디스크 I/O가 매우 느립니다
 a| 
매우 느린 디스크 I/O는 그리드 성능에 영향을 줄 수 있습니다.



 a| 
스토리지 어플라이언스 팬 장애가 감지되었습니다
 a| 
스토리지 컨트롤러의 팬 장치에서 어플라이언스에 문제가 감지되었습니다.



 a| 
스토리지 어플라이언스 스토리지 연결이 저하되었습니다
 a| 
컴퓨팅 컨트롤러와 스토리지 컨트롤러 사이에 하나 이상의 연결에 문제가 있습니다.



 a| 
스토리지 디바이스를 액세스할 수 없습니다
 a| 
스토리지 디바이스를 액세스할 수 없습니다.

|===


== 감사 및 syslog 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
감사 로그가 인메모리 대기열에 추가되고 있습니다
 a| 
노드가 로컬 syslog 서버로 로그를 전송할 수 없고 인메모리 큐가 가득 찬 경우



 a| 
외부 syslog 서버 전달 오류입니다
 a| 
노드가 외부 syslog 서버로 로그를 전달할 수 없습니다.



 a| 
대규모 감사 대기열
 a| 
감사 메시지의 디스크 대기열이 가득 찼습니다. 이 상태가 해결되지 않으면 S3 또는 Swift 작업이 실패할 수 있습니다.



 a| 
로그가 디스크 대기열에 추가되고 있습니다
 a| 
노드가 외부 syslog 서버로 로그를 전달할 수 없고 디스크 내 대기열이 가득 찬 경우

|===


== 버킷 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
FabricPool 버킷은 버킷 정합성 설정을 지원하지 않습니다
 a| 
FabricPool 버킷은 지원되지 않는 사용 가능 또는 강력한 사이트 정합성 보장 수준을 사용합니다.



 a| 
FabricPool 버킷에 지원되지 않는 버전 관리 설정이 있습니다
 a| 
FabricPool 버킷에는 버전 관리 또는 S3 오브젝트 잠금이 설정되어 있지만 이는 지원되지 않습니다.

|===


== Cassandra 알림

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
Cassandra 자동 콤팩터 오류입니다
 a| 
Cassandra 자동 콤팩터에 오류가 발생했습니다.



 a| 
Cassandra 자동 콤팩터 메트릭이 최신 상태가 아닙니다
 a| 
Cassandra 자동 콤팩터를 설명하는 메트릭이 최신 상태가 아닙니다.



 a| 
Cassandra 통신 오류입니다
 a| 
Cassandra 서비스를 실행하는 노드는 서로 통신하는 데 문제가 있습니다.



 a| 
Cassandra 압축 과부하입니다
 a| 
Cassandra 컴팩션 프로세스가 과부하 상태입니다.



 a| 
Cassandra 크기 초과 쓰기 오류입니다
 a| 
내부 StorageGRID 프로세스에서 Cassandra에 대해 너무 큰 쓰기 요청을 전송했습니다.



 a| 
Cassandra 복구 메트릭이 최신 상태가 아닙니다
 a| 
Cassandra 복구 작업을 설명하는 메트릭이 최신 상태가 아닙니다.



 a| 
Cassandra 복구 진행률이 느립니다
 a| 
Cassandra 데이터베이스 복구 진행률이 느립니다.



 a| 
Cassandra 복구 서비스를 사용할 수 없습니다
 a| 
Cassandra 복구 서비스를 사용할 수 없습니다.



 a| 
Cassandra 테이블 손상
 a| 
Cassandra가 테이블 손상을 감지했습니다. 테이블 손상이 감지되면 Cassandra가 자동으로 다시 시작됩니다.

|===


== Cloud Storage Pool 알림

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
클라우드 스토리지 풀 연결 오류입니다
 a| 
클라우드 스토리지 풀의 상태 점검에서 하나 이상의 새 오류가 감지되었습니다.



 a| 
IAM 역할 모든 위치에서 최종 엔티티 인증 만료
 a| 
IAM 역할 모든 위치에서 최종 엔티티 인증서가 곧 만료됩니다.

|===


== 교차 그리드 복제 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
크로스 그리드 복제 영구 오류입니다
 a| 
그리드 간 복제 오류가 발생하여 사용자 개입이 필요합니다.



 a| 
교차 그리드 복제 리소스를 사용할 수 없습니다
 a| 
리소스를 사용할 수 없기 때문에 교차 그리드 복제 요청이 보류 중입니다.

|===


== DHCP 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
DHCP 리스가 만료되었습니다
 a| 
네트워크 인터페이스의 DHCP 리스가 만료되었습니다.



 a| 
DHCP 임대가 곧 만료됩니다
 a| 
네트워크 인터페이스의 DHCP 임대가 곧 만료됩니다.



 a| 
DHCP 서버를 사용할 수 없습니다
 a| 
DHCP 서버를 사용할 수 없습니다.

|===


== 디버그 및 추적 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
디버그 성능 영향
 a| 
디버그 모드가 활성화되면 시스템 성능에 부정적인 영향을 줄 수 있습니다.



 a| 
추적 구성이 활성화되었습니다
 a| 
추적 구성이 활성화되면 시스템 성능에 부정적인 영향을 줄 수 있습니다.

|===


== 이메일 및 AutoSupport 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
AutoSupport 메시지를 보내지 못했습니다
 a| 
가장 최근의 AutoSupport 메시지를 보내지 못했습니다.



 a| 
도메인 이름을 확인하지 못했습니다
 a| 
StorageGRID 노드에서 도메인 이름을 확인할 수 없습니다.



 a| 
이메일 알림 실패
 a| 
알림에 대한 이메일 알림을 보낼 수 없습니다.



 a| 
SNMP 알림 오류
 a| 
트랩 대상에 SNMP 알림 알림을 보내는 중 오류가 발생했습니다.



 a| 
SSH 또는 콘솔 로그인이 감지되었습니다
 a| 
지난 24시간 동안 사용자가 웹 콘솔 또는 SSH로 로그인했습니다.

|===


== EC(삭제 코딩) 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
EC 재조정 실패
 a| 
EC 재조정 절차가 실패했거나 중지되었습니다.



 a| 
EC 복구 실패
 a| 
EC 데이터에 대한 복구 작업이 실패했거나 중지되었습니다.



 a| 
EC 복구가 중단되었습니다
 a| 
EC 데이터에 대한 복구 작업이 중단되었습니다.



 a| 
삭제 코딩 조각 검증 오류입니다
 a| 
삭제 코딩 조각은 더 이상 검증할 수 없습니다. 손상된 조각은 복구되지 않을 수 있습니다.

|===


== 인증서 경고 만료

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
관리 프록시 CA 인증서 만료
 a| 
관리 프록시 서버 CA 번들에 있는 하나 이상의 인증서가 곧 만료됩니다.



 a| 
클라이언트 인증서 만료
 a| 
하나 이상의 클라이언트 인증서가 곧 만료됩니다.



 a| 
S3 및 Swift에 대한 글로벌 서버 인증서 만료
 a| 
S3 및 Swift에 대한 글로벌 서버 인증서가 곧 만료됩니다.



 a| 
로드 밸런서 끝점 인증서 만료
 a| 
하나 이상의 로드 밸런서 끝점 인증서가 곧 만료됩니다.



 a| 
관리 인터페이스에 대한 서버 인증서 만료
 a| 
관리 인터페이스에 사용되는 서버 인증서가 곧 만료됩니다.



 a| 
외부 syslog CA 인증서 만료
 a| 
외부 syslog 서버 인증서에 서명하는 데 사용되는 CA(인증 기관) 인증서가 곧 만료됩니다.



 a| 
외부 syslog 클라이언트 인증서 만료
 a| 
외부 syslog 서버에 대한 클라이언트 인증서가 곧 만료됩니다.



 a| 
외부 syslog 서버 인증서 만료
 a| 
외부 syslog 서버가 제공하는 서버 인증서가 곧 만료됩니다.

|===


== 그리드 네트워크 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
그리드 네트워크 MTU가 일치하지 않습니다
 a| 
그리드 네트워크 인터페이스(eth0)에 대한 MTU 설정은 그리드의 노드 간에 크게 다릅니다.

|===


== 그리드 페더레이션 알림

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
그리드 페더레이션 인증서의 만료
 a| 
하나 이상의 그리드 페더레이션 인증서가 곧 만료됩니다.



 a| 
그리드 페더레이션 연결에 실패했습니다
 a| 
로컬 그리드와 원격 그리드 간의 그리드 페더레이션 연결이 작동하지 않습니다.

|===


== 사용량이 높거나 지연 시간이 긴 알림

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
높은 Java 힙 사용
 a| 
Java 힙 공간의 높은 비율이 사용되고 있습니다.



 a| 
메타데이터 쿼리를 위한 높은 지연 시간
 a| 
Cassandra 메타데이터 쿼리의 평균 시간이 너무 깁니다.

|===


== ID 페더레이션 알림

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
ID 페더레이션 동기화 실패
 a| 
ID 소스에서 페더레이션 그룹과 사용자를 동기화할 수 없습니다.



 a| 
테넌트의 ID 페더레이션 동기화 실패
 a| 
테넌트가 구성한 ID 소스에서 페더레이션 그룹과 사용자를 동기화할 수 없습니다.

|===


== ILM(정보 수명 주기 관리) 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
ILM 배치를 달성 할 수 없습니다
 a| 
ILM 규칙의 배치 지침은 특정 개체에 대해 달성할 수 없습니다.



 a| 
ILM 스캔 속도가 낮습니다
 a| 
ILM 스캔 속도는 초당 100개 미만으로 설정됩니다.

|===


== KMS(키 관리 서버) 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
KMS CA 인증서 만료
 a| 
KMS(키 관리 서버) 인증서에 서명하는 데 사용되는 CA(인증 기관) 인증서가 곧 만료됩니다.



 a| 
KMS 클라이언트 인증서 만료
 a| 
키 관리 서버의 클라이언트 인증서가 곧 만료됩니다



 a| 
KMS 구성을 로드하지 못했습니다
 a| 
키 관리 서버에 대한 구성이 있지만 로드하지 못했습니다.



 a| 
KMS 연결 오류입니다
 a| 
어플라이언스 노드가 사이트의 키 관리 서버에 연결할 수 없습니다.



 a| 
KMS 암호화 키 이름을 찾을 수 없습니다
 a| 
구성된 키 관리 서버에 제공된 이름과 일치하는 암호화 키가 없습니다.



 a| 
KMS 암호화 키 회전이 실패했습니다
 a| 
모든 어플라이언스 볼륨이 성공적으로 해독되었지만 하나 이상의 볼륨이 최신 키로 회전할 수 없습니다.



 a| 
KMS가 구성되지 않았습니다
 a| 
이 사이트에 대한 키 관리 서버가 없습니다.



 a| 
킬로미터 키가 어플라이언스 볼륨을 해독하지 못했습니다
 a| 
노드 암호화가 활성화된 어플라이언스에서 하나 이상의 볼륨을 현재 KMS 키로 해독할 수 없습니다.



 a| 
KMS 서버 인증서 만료
 a| 
KMS(키 관리 서버)에서 사용하는 서버 인증서가 곧 만료됩니다.



 a| 
KMS 서버 연결 실패
 a| 
어플라이언스 노드가 해당 사이트의 키 관리 서버 클러스터에 있는 하나 이상의 서버에 연결할 수 없습니다.

|===


== 로드 밸런서 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
상승된 제로 요청 로드 밸런서 연결부
 a| 
요청을 수행하지 않고 연결이 끊어진 로드 밸런서 끝점에 대한 연결 비율입니다.

|===


== 로컬 클록 오프셋 경고입니다

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
로컬 시계 대형 시간 오프셋
 a| 
로컬 시계와 NTP(네트워크 시간 프로토콜) 시간 사이의 오프셋이 너무 큽니다.

|===


== 메모리 부족 또는 공간 부족 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
감사 로그 디스크 용량이 낮습니다
 a| 
감사 로그에 사용할 수 있는 공간이 부족합니다. 이 상태가 해결되지 않으면 S3 또는 Swift 작업이 실패할 수 있습니다.



 a| 
사용 가능한 노드 메모리가 부족합니다
 a| 
노드에서 사용할 수 있는 RAM 용량이 부족합니다.



 a| 
스토리지 풀의 사용 가능한 공간이 부족합니다
 a| 
스토리지 노드에 오브젝트 데이터를 저장하는 데 사용할 수 있는 공간이 부족합니다.



 a| 
설치된 노드 메모리가 부족합니다
 a| 
노드에 설치된 메모리 양이 부족합니다.



 a| 
낮은 메타데이터 스토리지
 a| 
오브젝트 메타데이터를 저장하는 데 사용할 수 있는 공간이 부족합니다.



 a| 
낮은 메트릭 디스크 용량
 a| 
메트릭 데이터베이스에 사용할 수 있는 공간이 부족합니다.



 a| 
오브젝트 데이터 스토리지가 부족합니다
 a| 
오브젝트 데이터를 저장하는 데 사용할 수 있는 공간이 부족합니다.



 a| 
읽기 전용 로우 워터마크가 무시됩니다
 a| 
스토리지 볼륨 소프트 읽기 전용 워터마크 재정의가 스토리지 노드에 대해 최적화된 최소 워터마크보다 작습니다.



 a| 
루트 디스크 용량이 부족합니다
 a| 
루트 디스크의 사용 가능한 공간이 부족합니다.



 a| 
시스템 데이터 용량이 부족합니다
 a| 
/var/local에 사용할 수 있는 공간이 부족합니다. 이 상태가 해결되지 않으면 S3 또는 Swift 작업이 실패할 수 있습니다.



 a| 
tmp 디렉토리 여유 공간이 부족합니다
 a| 
/tmp 디렉토리에 사용 가능한 공간이 부족합니다.

|===


== 노드 또는 노드 네트워크 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
관리 네트워크 수신 사용
 a| 
관리 네트워크의 수신 사용량이 높습니다.



 a| 
관리 네트워크 전송 사용
 a| 
관리 네트워크의 전송 사용량이 높습니다.



 a| 
방화벽 구성 실패
 a| 
방화벽 구성을 적용하지 못했습니다.



 a| 
대체 모드의 관리 인터페이스 끝점입니다
 a| 
모든 관리 인터페이스 엔드포인트가 너무 오래 기본 포트로 돌아가고 있습니다.



 a| 
노드 네트워크 연결 오류입니다
 a| 
노드 간에 데이터를 전송하는 동안 오류가 발생했습니다.



 a| 
노드 네트워크 수신 프레임 오류입니다
 a| 
노드에서 수신한 네트워크 프레임의 비율이 높은 경우 오류가 발생했습니다.



 a| 
노드가 NTP 서버와 동기화되지 않았습니다
 a| 
노드가 NTP(네트워크 시간 프로토콜) 서버와 동기화되지 않습니다.



 a| 
NTP 서버로 잠겨 있지 않은 노드입니다
 a| 
노드가 네트워크 시간 프로토콜(NTP) 서버에 잠기지 않았습니다.



 a| 
비어플라이언스 노드 네트워크가 다운되었습니다
 a| 
하나 이상의 네트워크 장치가 다운되었거나 연결이 끊어졌습니다.



 a| 
관리 네트워크에서 서비스 어플라이언스 링크가 다운되었습니다
 a| 
관리 네트워크(eth1)에 대한 어플라이언스 인터페이스가 다운되거나 연결이 끊겼습니다.



 a| 
관리 네트워크 포트 1에서 서비스 어플라이언스 링크가 다운되었습니다
 a| 
어플라이언스의 관리 네트워크 포트 1이 다운되었거나 연결이 해제되었습니다.



 a| 
클라이언트 네트워크에서 서비스 어플라이언스 링크가 다운되었습니다
 a| 
클라이언트 네트워크(eth2)에 대한 어플라이언스 인터페이스가 중단되거나 연결이 끊겼습니다.



 a| 
네트워크 포트 1에서 서비스 어플라이언스 링크가 다운되었습니다
 a| 
어플라이언스의 네트워크 포트 1가 다운되었거나 연결 해제되었습니다.



 a| 
네트워크 포트 2에서 서비스 어플라이언스 링크가 다운되었습니다
 a| 
어플라이언스의 네트워크 포트 2가 다운되었거나 연결 해제되었습니다.



 a| 
네트워크 포트 3에서 서비스 어플라이언스 링크가 다운되었습니다
 a| 
어플라이언스의 네트워크 포트 3가 다운되었거나 연결 해제되었습니다.



 a| 
네트워크 포트 4에서 서비스 어플라이언스 링크가 다운되었습니다
 a| 
어플라이언스의 네트워크 포트 4가 다운되었거나 연결 해제되었습니다.



 a| 
관리 네트워크에서 스토리지 어플라이언스 링크가 다운되었습니다
 a| 
관리 네트워크(eth1)에 대한 어플라이언스 인터페이스가 다운되거나 연결이 끊겼습니다.



 a| 
관리 네트워크 포트 1에서 스토리지 어플라이언스 링크가 다운되었습니다
 a| 
어플라이언스의 관리 네트워크 포트 1이 다운되었거나 연결이 해제되었습니다.



 a| 
클라이언트 네트워크에서 스토리지 어플라이언스 링크가 다운되었습니다
 a| 
클라이언트 네트워크(eth2)에 대한 어플라이언스 인터페이스가 중단되거나 연결이 끊겼습니다.



 a| 
네트워크 포트 1에서 스토리지 어플라이언스 링크가 다운되었습니다
 a| 
어플라이언스의 네트워크 포트 1가 다운되었거나 연결 해제되었습니다.



 a| 
네트워크 포트 2에서 스토리지 어플라이언스 링크가 다운되었습니다
 a| 
어플라이언스의 네트워크 포트 2가 다운되었거나 연결 해제되었습니다.



 a| 
네트워크 포트 3에서 스토리지 어플라이언스 링크가 다운되었습니다
 a| 
어플라이언스의 네트워크 포트 3가 다운되었거나 연결 해제되었습니다.



 a| 
네트워크 포트 4에서 스토리지 어플라이언스 링크가 다운되었습니다
 a| 
어플라이언스의 네트워크 포트 4가 다운되었거나 연결 해제되었습니다.



 a| 
스토리지 노드가 원하는 스토리지 상태가 아닙니다
 a| 
내부 오류 또는 볼륨 관련 문제로 인해 스토리지 노드의 LDR 서비스가 원하는 상태로 전환될 수 없습니다



 a| 
TCP 연결 사용
 a| 
이 노드의 TCP 연결 수가 추적할 수 있는 최대 수에 근접하고 있습니다.



 a| 
노드와 통신할 수 없습니다
 a| 
하나 이상의 서비스가 응답하지 않거나 노드에 연결할 수 없습니다.



 a| 
예기치 않은 노드 재부팅
 a| 
지난 24시간 동안 노드가 예기치 않게 재부팅되었습니다.

|===


== 개체 알림

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
개체 존재 여부를 확인하지 못했습니다
 a| 
개체 존재 확인 작업이 실패했습니다.



 a| 
개체 존재 검사가 중단되었습니다
 a| 
개체 존재 확인 작업이 중단되었습니다.



 a| 
객체가 손실되었습니다
 a| 
그리드에서 하나 이상의 오브젝트가 손실되었습니다.



 a| 
S3이 개체 크기를 너무 크게 설정합니다
 a| 
클라이언트가 S3 크기 제한을 초과하는 Put Object 작업을 시도하고 있습니다.



 a| 
알 수 없는 손상된 개체가 감지되었습니다
 a| 
복제된 오브젝트로 식별되지 않는 파일이 복제된 오브젝트 스토리지에 있습니다.

|===


== 플랫폼 서비스 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
플랫폼 서비스 보류 중인 요청 용량이 부족합니다
 a| 
대기 중인 플랫폼 서비스 요청 수가 용량에 근접하고 있습니다.



 a| 
플랫폼 서비스를 사용할 수 없습니다
 a| 
RSM 서비스가 실행 중이거나 사이트에서 사용 가능한 스토리지 노드가 너무 적습니다.

|===


== 스토리지 볼륨 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
스토리지 볼륨에 주의가 필요합니다
 a| 
스토리지 볼륨이 오프라인 상태이므로 주의가 필요합니다.



 a| 
스토리지 볼륨을 복원해야 합니다
 a| 
스토리지 볼륨이 복구되었으며 복원해야 합니다.



 a| 
스토리지 볼륨이 오프라인 상태입니다
 a| 
저장소 볼륨이 5분 이상 오프라인 상태입니다.



 a| 
스토리지 볼륨 다시 마운트가 시도되었습니다
 a| 
스토리지 볼륨이 오프라인 상태이고 자동 다시 마운트가 트리거되었습니다. 이는 드라이브 문제나 파일 시스템 오류를 나타낼 수 있습니다.



 a| 
볼륨 복원에서 복제된 데이터 복구를 시작하지 못했습니다
 a| 
복구된 볼륨에 대해 복제된 데이터 복구를 자동으로 시작할 수 없습니다.

|===


== StorageGRID 서비스 경고

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
백업 구성을 사용하는 Nginx 서비스
 a| 
nginx 서비스의 구성이 잘못되었습니다. 이제 이전 구성을 사용하고 있습니다.



 a| 
백업 구성을 사용하는 Nginx-GW 서비스
 a| 
nginx-GW 서비스의 구성이 유효하지 않습니다. 이제 이전 구성을 사용하고 있습니다.



 a| 
FIPS를 비활성화하려면 재부팅해야 합니다
 a| 
보안 정책에는 FIPS 모드가 필요하지 않지만 NetApp 암호화 보안 모듈이 활성화되어 있습니다.



 a| 
FIPS를 활성화하려면 재부팅해야 합니다
 a| 
보안 정책에는 FIPS 모드가 필요하지만 NetApp 암호화 보안 모듈이 비활성화되어 있습니다.



 a| 
백업 구성을 사용하는 SSH 서비스입니다
 a| 
SSH 서비스 구성이 잘못되었습니다. 이제 이전 구성을 사용하고 있습니다.

|===


== 테넌트 알림

[cols="1a,2a"]
|===
| 경고 이름입니다 | 설명 


 a| 
테넌트 할당량 사용량이 높습니다
 a| 
할당량 공간의 높은 비율이 사용되고 있습니다. 이 규칙은 너무 많은 알림을 발생시킬 수 있으므로 기본적으로 비활성화되어 있습니다.

|===