---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: 구성 데이터를 포함한 StorageGRID 로그 파일 및 시스템 데이터를 검색하여 기술 지원에 보낼 수 있습니다. 
---
= 로그 파일 및 시스템 데이터를 수집합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
구성 데이터를 포함한 StorageGRID 로그 파일 및 시스템 데이터를 검색하여 기술 지원에 보낼 수 있습니다.

.시작하기 전에
* 를 사용하여 기본 관리자 노드에서 그리드 관리자에 로그인되어 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 있습니다. link:../admin/admin-group-permissions.html["특정 액세스 권한"]
* 프로비저닝 암호가 있습니다.


.이 작업에 대해
그리드 관리자를 사용하여 link:logs-files-reference.html["로그 파일"]선택한 기간 동안 그리드 노드에서 시스템 데이터 및 구성 데이터를 수집합니다. 데이터가 수집되고 파일에 보관되며 `.tar.gz`, 이 파일을 로컬 컴퓨터에 다운로드하거나 기술 지원 부서에 전송할 수 있습니다.

선택적으로 감사 로그의 대상을 변경하고 감사 정보를 외부 syslog 서버로 보낼 수 있습니다. 외부 syslog 서버가 구성되면 감사 레코드의 로컬 로그가 계속 생성되고 저장됩니다. 을 link:../monitor/configure-audit-messages.html["감사 메시지 및 외부 syslog 서버를 구성합니다"]참조하십시오.

.단계
. 지원 * > * 도구 * > * 로그 * 를 선택합니다. 노드 표가 표시됩니다.
. 로그 파일을 수집할 그리드 노드를 선택합니다.
+
노드 이름, 사이트 및 노드 유형별로 정렬할 수 있습니다. 사이트 및 노드 유형 열에는 개별 사이트 및 노드 유형별로 선택하기 위한 필터가 포함되어 있습니다.

. Continue * 를 선택합니다.
. 로그 파일에 포함할 데이터의 날짜 및 시간 범위를 선택합니다.
+
매우 긴 기간을 선택하거나 큰 그리드의 모든 노드에서 로그를 수집할 경우 로그 아카이브가 너무 커서 노드에 저장할 수 없거나 너무 커서 기본 관리 노드에 다운로드할 수 없습니다. 두 시나리오 중 하나가 발생하면 더 작은 데이터 집합으로 로그 수집을 다시 시작합니다.

. 수집할 로그 유형을 선택합니다.
+
** * 응용 프로그램 로그 *: 기술 지원 부서에서 문제 해결을 위해 가장 자주 사용하는 응용 프로그램별 로그입니다. 수집된 로그는 사용 가능한 애플리케이션 로그의 하위 집합입니다.
** * 감사 로그 * : 정상적인 시스템 작동 중에 생성된 감사 메시지가 포함된 로그입니다.
** * 네트워크 추적 * : 네트워크 디버깅에 사용되는 로그.
** * Prometheus 데이터베이스 *: 모든 노드에 대한 서비스의 시계열 메트릭


. 필요한 경우 * Notes * 텍스트 상자를 사용하여 수집하는 로그 파일에 대한 메모를 입력합니다.
+
이러한 메모를 사용하여 로그 파일을 수집하라는 메시지가 표시되는 문제에 대한 기술 지원 정보를 제공할 수 있습니다. 로그 파일 수집에 대한 기타 정보와 함께 메모가 이라는 파일에 `info.txt` 추가됩니다.  `info.txt`파일이 로그 파일 보관 패키지에 저장됩니다.

. Provisioning passphrase * 텍스트 상자에 StorageGRID 시스템의 프로비저닝 암호를 입력합니다.
. 로그 수집 * 을 선택합니다.
+
로그 페이지를 사용하여 각 그리드 노드에 대한 로그 파일 수집 진행률을 모니터링할 수 있습니다.

+
로그 크기에 대한 오류 메시지가 표시되면 더 짧은 기간 또는 더 적은 수의 노드에 대해 로그를 수집해 보십시오.

. 로그 수집에 실패한 경우:
+
** "Log collection failed(로그 수집 실패)" 메시지가 나타나면 다시 시도하지 않고 로그 수집을 다시 시도하거나 세션을 완료할 수 있습니다.
** "로그 수집 부분 실패" 메시지가 나타나면 로그 수집을 다시 시도하거나, 세션을 완료하거나, 부분 로그 파일을 다운로드하거나, 부분 로그 파일을 AutoSupport에 보낼 수 있습니다.


. 로그 파일 수집이 완료된 경우:
+
** 파일을 다운로드하려면 * 다운로드 * 를 `.tar.gz` 선택하십시오.
** 파일을 기술 지원부에 보내려면 * AutoSupport로 보내기 * 를 선택합니다 `.tar.gz`.
+
이 `.tar.gz` 파일에는 로그 수집에 성공한 모든 그리드 노드의 모든 로그 파일이 포함됩니다. 결합된 `.tar.gz` 파일에는 각 그리드 노드에 대해 하나의 로그 파일 아카이브가 포함됩니다.

+
AutoSupport 패키지의 주제는 `USER_TRIGGERED_SUPPORT_BUNDLE` 입니다.



. 마침 * 을 선택합니다.
+

CAUTION:  `.tar.gz`Finish * 를 선택하면 파일이 삭제됩니다. 먼저 파일을 다운로드하거나 전송해야 합니다.


