---
permalink: monitor/monitoring-information-lifecycle-management.html 
sidebar: sidebar 
keywords: lifecycle management, lifecycle, monitoring, ILM, information lifecycle management 
summary: 'ILM(정보 수명 주기 관리) 시스템은 그리드에 저장된 모든 개체에 대한 데이터 관리를 제공합니다. ILM 작업을 모니터링하여 그리드가 현재 로드를 처리할 수 있는지 또는 추가 리소스가 필요한지 여부를 파악해야 합니다.' 
---
= 정보 수명 주기 관리를 모니터링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM(정보 수명 주기 관리) 시스템은 그리드에 저장된 모든 개체에 대한 데이터 관리 기능을 제공합니다. ILM 작업을 모니터링하여 그리드가 현재 로드를 처리할 수 있는지 또는 추가 리소스가 필요한지 여부를 파악해야 합니다.

.이 작업에 대해
StorageGRID 시스템은 활성 ILM 정책을 적용하여 오브젝트를 관리합니다. ILM 정책 및 관련 ILM 규칙은 생성할 복사본의 수, 생성할 복사본의 유형, 복사본을 배치할 위치 및 각 복사본을 보존할 기간을 결정합니다.

오브젝트 수집 및 기타 오브젝트 관련 활동이 StorageGRID에서 ILM을 평가할 수 있는 속도를 초과할 수 있으므로 시스템에서 ILM 배치 지침을 거의 실시간으로 이행할 수 없는 개체를 대기열에 추가할 수 있습니다. StorageGRID가 클라이언트 작업을 수행하고 있는지 모니터링해야 합니다.



== Grid Manager 대시보드 탭을 사용합니다

.단계
Grid Manager 대시보드의 ILM 탭을 사용하여 ILM 작업을 모니터링합니다.

. Grid Manager에 로그인합니다.
. 대시보드에서 ILM 탭을 선택하고 ILM 대기열(개체) 카드 및 ILM 평가율 카드의 값을 확인합니다.
+
대시보드의 ILM 대기열(개체) 카드가 일시적으로 급증할 수 있습니다. 그러나 대기열이 계속 증가하고 감소하지 않으면 그리드를 효율적으로 운영하는 데 더 많은 리소스가 필요합니다. 즉, 스토리지 노드를 추가하거나 ILM 정책에 따라 원격 위치에 개체를 배치하면 네트워크 대역폭이 증가합니다.





== 노드 페이지 사용

.단계
또한 *노드* 페이지를 사용하여 ILM 대기열을 조사하세요.


NOTE: *노드* 페이지의 차트는 향후 StorageGRID 릴리스에서 해당 대시보드 카드로 교체될 예정입니다.

. *노드*를 선택하세요.
. _GRID NAME_ * > * ILM * 을 선택합니다.
. ILM 대기열 그래프 위에 커서를 올려 놓으면 지정된 시점에 다음 속성의 값을 볼 수 있습니다.
+
** * 대기 중인 오브젝트(클라이언트 작업에서) *: 클라이언트 작업(예: 수집)으로 인해 ILM 평가를 대기 중인 총 오브젝트 수
** * 대기 중인 개체(모든 작업에서) *: ILM 평가를 대기 중인 총 개체 수.
** * 스캔 속도(개체/초) *: 그리드의 개체가 스캔되어 ILM을 위해 대기 중인 속도입니다.
** * 평가 속도(개체/초) *: 그리드의 ILM 정책에 따라 개체를 평가하는 현재 속도입니다.


+

NOTE: ILM 대기열 섹션은 그리드에만 포함됩니다. 이 정보는 사이트 또는 스토리지 노드의 ILM 탭에 표시되지 않습니다.

. ILM 대기열 섹션에서 다음 속성을 확인합니다.
+
** * 스캔 기간 - 추정 * : 모든 개체의 전체 ILM 스캔을 완료하는 데 걸리는 예상 시간입니다.
+

NOTE: 전체 스캔은 ILM이 모든 개체에 적용되었다고 보장하지 않습니다.

** * Repairs attemed *: 시도한 복제된 데이터에 대한 총 개체 복구 작업 수입니다. 이 수는 스토리지 노드가 고위험 객체를 복구하려고 할 때마다 증가합니다. 그리드가 사용 중인 경우 위험이 높은 ILM 수리의 우선 순위가 지정됩니다.
+
복구 후 복제가 실패하면 동일한 개체 복구가 다시 증가할 수 있습니다.  + 이러한 속성은 스토리지 노드 볼륨 복구 진행 상황을 모니터링할 때 유용할 수 있습니다.  수리 시도 횟수가 더 이상 증가하지 않고 전체 검사가 완료되면 수리가 완료된 것으로 추정됩니다.



. 또는 Prometheus 쿼리를 제출하세요. `storagegrid_ilm_scan_period_estimated_minutes` 그리고 `storagegrid_ilm_repairs_attempted` .

