---
permalink: monitor/monitoring-load-balancing-operations.html 
sidebar: sidebar 
keywords: load balancing, monitoring 
summary: 로드 밸런서를 사용하여 StorageGRID에 대한 클라이언트 연결을 관리하는 경우 시스템을 처음 구성한 후 또는 구성을 변경하거나 확장을 수행한 후에 로드 밸런싱 작업을 모니터링해야 합니다. 
---
= 로드 밸런싱 작업을 모니터링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
로드 밸런서를 사용하여 StorageGRID에 대한 클라이언트 연결을 관리하는 경우 시스템을 처음 구성한 후 또는 구성을 변경하거나 확장을 수행한 후에 로드 밸런싱 작업을 모니터링해야 합니다.

.이 작업에 대해
관리 노드 또는 게이트웨이 노드에서 로드 밸런서 서비스를 사용하거나 외부 타사 로드 밸런서를 사용하여 여러 스토리지 노드에 클라이언트 요청을 분산할 수 있습니다.

로드 밸런싱을 구성한 후에는 오브젝트 수집 및 검색 작업이 스토리지 노드 간에 균등하게 분산되는지 확인해야 합니다. 균등하게 분산된 요청은 StorageGRID가 로드 중인 클라이언트 요청에 계속 응답하도록 하며 클라이언트 성능을 유지하는 데 도움이 됩니다.

액티브-백업 모드에서 게이트웨이 노드 또는 관리 노드의 고가용성(HA) 그룹을 구성한 경우 그룹의 노드 중 하나만 클라이언트 요청을 능동적으로 분배합니다.

자세한 내용은 을 link:../admin/configuring-client-connections.html["S3 클라이언트 연결을 구성합니다"]참조하십시오.

.단계
. S3 클라이언트가 로드 밸런서 서비스를 사용하여 연결하는 경우 관리 노드 또는 게이트웨이 노드가 예상한 대로 트래픽을 적극적으로 분산하는지 확인하십시오.
+
.. 노드 * 를 선택합니다.
.. 게이트웨이 노드 또는 관리자 노드를 선택합니다.
.. Overview * 탭에서 노드 인터페이스가 HA 그룹에 있는지, 노드 인터페이스가 Primary 역할을 하는지 확인합니다.
+
운영 노드 및 HA 그룹에 속하지 않는 노드 역할이 있는 노드는 클라이언트에 요청을 능동적으로 분산해야 합니다.

.. 클라이언트 요청을 능동적으로 배포해야 하는 각 노드에 대해 을 link:viewing-load-balancer-tab.html["부하 분산 탭"]선택합니다.
.. 지난 주 로드 밸런서 요청 트래픽 차트를 검토하여 노드가 요청을 적극적으로 배포했는지 확인합니다.
+
액티브-백업 HA 그룹의 노드는 수시로 백업 역할을 수행할 수 있습니다. 이 시간 동안에는 노드가 클라이언트 요청을 배포하지 않습니다.

.. 지난 주 로드 밸런서 수신 요청 속도 차트를 검토하여 노드의 객체 처리량을 검토합니다.
.. StorageGRID 시스템의 각 관리 노드 또는 게이트웨이 노드에 대해 이 단계를 반복합니다.
.. 선택적으로 트래픽 분류 정책을 사용하여 부하 분산 서비스가 제공하는 트래픽에 대한 보다 자세한 분석을 볼 수 있습니다.


. 이러한 요청이 스토리지 노드에 고르게 분산되는지 확인합니다.
+
.. 스토리지 노드 * > * LDR * > * HTTP * 를 선택합니다.
.. 현재 설정된 수신 세션 수 * 를 검토합니다.
.. 그리드의 각 스토리지 노드에 대해 이 과정을 반복합니다.
+
세션 수는 모든 스토리지 노드에서 거의 같아야 합니다.




