---
permalink: monitor/reviewing-audit-messages.html 
sidebar: sidebar 
keywords: how to review audit messages, how to view audit messages 
summary: 감사 메시지를 통해 StorageGRID 시스템의 세부 작업을 보다 잘 이해할 수 있습니다. 감사 로그를 사용하여 문제를 해결하고 성능을 평가할 수 있습니다. 
---
= 감사 메시지를 검토합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 메시지를 통해 StorageGRID 시스템의 세부 작업을 보다 잘 이해할 수 있습니다. 감사 로그를 사용하여 문제를 해결하고 성능을 평가할 수 있습니다.

정상적인 시스템 작동 중에 모든 StorageGRID 서비스는 다음과 같이 감사 메시지를 생성합니다.

* 시스템 감사 메시지는 감사 시스템 자체, 그리드 노드 상태, 시스템 전체 작업 및 서비스 백업 작업과 관련되어 있습니다.
* 오브젝트 스토리지 감사 메시지는 오브젝트 스토리지 및 검색, 그리드 노드에서 그리드 노드 전송, 확인을 포함하여 StorageGRID 내의 오브젝트 스토리지 및 관리와 관련되어 있습니다.
* 클라이언트 읽기 및 쓰기 감사 메시지는 S3 클라이언트 애플리케이션이 오브젝트를 생성, 수정 또는 검색하도록 요청할 때 기록됩니다.
* 관리 감사 메시지는 관리 API에 사용자 요청을 기록합니다.


각 관리 노드는 감사 메시지를 텍스트 파일에 저장합니다. 감사 공유에는 활성 파일(audit.log)과 이전 일로부터의 압축된 감사 로그가 포함됩니다. 그리드의 각 노드는 노드에서 생성된 감사 정보의 복사본도 저장합니다.

관리자 노드의 명령줄에서 직접 감사 로그 파일에 액세스할 수 있습니다.

StorageGRID는 기본적으로 감사 정보를 보내거나 대상을 변경할 수 있습니다.

* StorageGRID의 기본값은 로컬 노드 감사 대상입니다.
* 그리드 관리자 및 테넌트 관리자 감사 로그 항목이 스토리지 노드로 전송될 수 있습니다.
* 선택적으로 감사 로그의 대상을 변경하고 감사 정보를 외부 syslog 서버로 보낼 수 있습니다. 외부 syslog 서버가 구성되면 감사 레코드의 로컬 로그가 계속 생성되고 저장됩니다.
* link:../monitor/configure-log-management.html["로그 관리 구성에 대해 알아보세요"] .


감사 로그 파일, 감사 메시지 형식, 감사 메시지 유형 및 감사 메시지 분석에 사용할 수 있는 도구에 대한 자세한 내용은 을 참조하십시오.link:../audit/index.html["감사 로그를 검토합니다"]
