---
permalink: monitor/storagegrid-software-logs.html 
sidebar: sidebar 
keywords: logs 
summary: StorageGRID 로그를 사용하여 문제를 해결할 수 있습니다. 
---
= StorageGRID 소프트웨어 로그
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 로그를 사용하여 문제를 해결할 수 있습니다.


NOTE: 로그를 외부 syslog 서버로 보내거나 감사 정보의 대상을 변경하려는 경우 `bycast.log` 그리고 `nms.log` , 보다link:../monitor/configure-log-management.html["로그 관리 구성"] .



== 일반 StorageGRID 로그

[cols="3a,3a,2a"]
|===
| 파일 이름입니다 | 참고 | 에 있습니다 


| /var/local/log/bycast.log 를 참조하십시오  a| 
기본 StorageGRID 문제 해결 파일입니다.
 a| 
모든 노드



| /var/local/log/bycast-err.log 를 참조하십시오  a| 
하위 집합을 포함합니다 `bycast.log` (심각도가 ERROR 및 CRITICAL인 메시지).  중요 메시지도 시스템에 표시됩니다.
 a| 
모든 노드



| /var/local/core/  a| 
프로그램이 비정상적으로 종료될 경우 생성된 코어 덤프 파일이 포함되어 있습니다. 가능한 원인으로는 어설션 실패, 위반 또는 스레드 시간 초과가 있습니다.

* 참고 *: 파일은 ``/var/local/core/kexec_cmd` 일반적으로 어플라이언스 노드에 존재하며 오류를 나타내지 않습니다.
 a| 
모든 노드

|===


== 암호화 관련 로그

[cols="3a,3a,2a"]
|===
| 파일 이름입니다 | 참고 | 에 있습니다 


| /var/local/log/ssh-config-generation.log 를 참조하십시오  a| 
SSH 구성 생성 및 SSH 서비스 재로드와 관련된 로그를 포함합니다.
 a| 
모든 노드



| /var/local/log/nginx/config-generation.log 를 참조하십시오  a| 
nginx 구성 생성 및 nginx 서비스 재로드와 관련된 로그를 포함합니다.
 a| 
모든 노드



| /var/local/log/nginx-GW/config-generation.log 를 참조하십시오  a| 
nginx-GW 구성 생성(및 nginx-GW 서비스 재로딩)과 관련된 로그를 포함합니다.
 a| 
관리자 및 게이트웨이 노드



| /var/local/log/update-cipher-configurations.log 를 참조하십시오  a| 
TLS 및 SSH 정책 구성과 관련된 로그를 포함합니다.
 a| 
모든 노드

|===


== 그리드 페더레이션 로그

[cols="3a,3a,2a"]
|===
| 파일 이름입니다 | 참고 | 에 있습니다 


| /var/local/log/update_grid_federation_config.log 를 참조하십시오  a| 
그리드 페더레이션 연결을 위한 nginx 및 nginx-GW 구성 생성과 관련된 로그를 포함합니다.
 a| 
모든 노드

|===


== NMS 로그

[cols="3a,3a,2a"]
|===
| 파일 이름입니다 | 참고 | 에 있습니다 


| /var/local/log/nms.log 를 참조하십시오  a| 
* Grid Manager 및 테넌트 관리자의 알림을 캡처합니다.
* NMS 서비스 작동과 관련된 이벤트를 캡처합니다. 예를 들어, 이메일 알림 및 구성 변경 사항이 있습니다.
* 시스템에서 변경한 구성 변경으로 인한 XML 번들 업데이트를 포함합니다.
* 하루에 한 번 수행된 속성 다운샘플링과 관련된 오류 메시지가 포함되어 있습니다.
* Java 웹 서버 오류 메시지(예: 페이지 생성 오류 및 HTTP 상태 500 오류)가 포함되어 있습니다.

 a| 
관리자 노드



| /var/local/log/NMS.errlog입니다  a| 
MySQL 데이터베이스 업그레이드와 관련된 오류 메시지가 포함되어 있습니다.

해당 서비스의 표준 오류(stderr) 스트림을 포함합니다. 서비스당 하나의 로그 파일이 있습니다. 서비스에 문제가 없는 경우 이러한 파일은 일반적으로 비어 있습니다.
 a| 
관리자 노드



| /var/local/log/NMS.requestlog입니다  a| 
관리 API에서 내부 StorageGRID 서비스로 나가는 연결에 대한 정보를 포함합니다.
 a| 
관리자 노드

|===


== 서버 관리자 로그

[cols="3a,3a,2a"]
|===
| 파일 이름입니다 | 참고 | 에 있습니다 


| /var/local/log/servermanager.log 를 참조하십시오  a| 
서버에서 실행 중인 Server Manager 응용 프로그램의 로그 파일입니다.
 a| 
모든 노드



| /var/local/log/GridstatBackend.errlog입니다  a| 
Server Manager GUI 백엔드 애플리케이션에 대한 로그 파일입니다.
 a| 
모든 노드



| /var/local/log/gridstat.errlog입니다  a| 
서버 관리자 GUI에 대한 로그 파일입니다.
 a| 
모든 노드

|===


== StorageGRID 서비스 로그

[cols="3a,3a,2a"]
|===
| 파일 이름입니다 | 참고 | 에 있습니다 


| /var/local/log/acct.errlog입니다  a| 
 a| 
ADC 서비스를 실행하는 스토리지 노드



| /var/local/log/ADC.errlog입니다  a| 
해당 서비스의 표준 오류(stderr) 스트림을 포함합니다. 서비스당 하나의 로그 파일이 있습니다. 서비스에 문제가 없는 경우 이러한 파일은 일반적으로 비어 있습니다.
 a| 
ADC 서비스를 실행하는 스토리지 노드



| /var/local/log/aMS.errlog입니다  a| 
 a| 
관리자 노드



| /var/local/log/cache-svc.log + /var/local/log/cache-svc.errlog  a| 
캐시 서비스 로그.
 a| 
게이트웨이 노드



| /var/local/log/cassandra/system.log 를 참조하십시오  a| 
새 스토리지 노드를 추가할 때 문제가 발생하거나 작업 중단 시 사용할 수 있는 메타데이터 저장소(Cassandra 데이터베이스)에 대한 정보입니다.
 a| 
스토리지 노드



| /var/local/log/cassandra-reaper.log 를 참조하십시오  a| 
Cassandra Reaper 서비스: Cassandra 데이터베이스 데이터의 복구를 수행합니다.
 a| 
스토리지 노드



| /var/local/log/cassandra-reaper.errlog  a| 
Cassandra Refaper 서비스에 대한 오류 정보입니다.
 a| 
스토리지 노드



| /var/local/log/chunk.errlog입니다  a| 
 a| 
스토리지 노드



| /var/local/log/CMN.errlog입니다  a| 
 a| 
관리자 노드



| /var/local/log/CMS.errlog 를 참조하십시오  a| 
이 로그 파일은 이전 버전의 StorageGRID에서 업그레이드된 시스템에 있을 수 있습니다. 기존 정보가 포함되어 있습니다.
 a| 
스토리지 노드



| /var/local/log/dS.errlog를 참조하십시오  a| 
 a| 
스토리지 노드



| /var/local/log/DMV.errlog입니다  a| 
 a| 
스토리지 노드



| /var/local/log/dynip * 를 참조하십시오  a| 
동적 IP 변경을 위해 그리드를 모니터링하고 로컬 구성을 업데이트하는 dynip 서비스와 관련된 로그를 포함합니다.
 a| 
모든 노드



| /var/local/log/grafana.log 를 참조하십시오  a| 
Grafana 서비스와 연관된 로그로, Grid Manager에서 메트릭 시각화에 사용됩니다.
 a| 
관리자 노드



| /var/local/log/hagroups.log 를 참조하십시오  a| 
고가용성 그룹과 연결된 로그입니다.
 a| 
관리 노드 및 게이트웨이 노드



| /var/local/log/hagroups_events.log 를 참조하십시오  a| 
백업에서 마스터로 전환 또는 오류와 같은 상태 변경을 추적합니다.
 a| 
관리 노드 및 게이트웨이 노드



| /var/local/log/idnt.errlog입니다  a| 
 a| 
ADC 서비스를 실행하는 스토리지 노드



| /var/local/log/jaeger.log 를 참조하십시오  a| 
추적 수집에 사용되는 Jaeger 서비스와 연관된 로그입니다.
 a| 
모든 노드



| /var/local/log/kstn.errlog입니다  a| 
 a| 
ADC 서비스를 실행하는 스토리지 노드



| /var/local/log/lambda *  a| 
S3 Select 서비스에 대한 로그를 포함합니다.
 a| 
관리자 및 게이트웨이 노드

특정 관리자 및 게이트웨이 노드에만 이 로그가 포함됩니다. 를 link:../admin/manage-s3-select-for-tenant-accounts.html["S3 관리자 및 게이트웨이 노드에 대한 요구 사항 및 제한 사항을 선택합니다"]참조하십시오.



| /var/local/log/LDR.errlog입니다  a| 
 a| 
스토리지 노드



| /var/local/log/miscd/ *.log  a| 
MISCd 서비스(정보 서비스 제어 데몬)에 대한 로그를 포함합니다. 이 로그는 다른 노드의 서비스를 쿼리 및 관리하고 다른 노드에서 실행 중인 서비스 상태를 쿼리하는 등 노드의 환경 구성을 관리하는 인터페이스를 제공합니다.
 a| 
모든 노드



| /var/local/log/nginx/ *.log  a| 
HTTPS API를 통해 다른 노드의 서비스와 통신할 수 있도록 다양한 그리드 서비스(예: Prometheus 및 Dynip)에 대한 인증 및 보안 통신 메커니즘 역할을 하는 nginx 서비스에 대한 로그를 포함합니다.
 a| 
모든 노드



| /var/local/log/nginx-GW/ *.log  a| 
오류 로그를 포함하여 nginx-GW 서비스와 관련된 일반 로그 및 관리 노드의 제한된 관리 포트에 대한 로그가 포함되어 있습니다.
 a| 
관리 노드 및 게이트웨이 노드



| /var/local/log/nginx-GW/cgr-access.log.gz 를 참조하십시오  a| 
교차 그리드 복제 트래픽과 관련된 액세스 로그를 포함합니다.
 a| 
그리드 통합 구성에 따라 관리 노드, 게이트웨이 노드 또는 둘 다 교차 그리드 복제용 대상 그리드에서만 찾을 수 있습니다.



| /var/local/log/nginx-GW/endpoint-access.log.gz 를 참조하십시오  a| 
클라이언트에서 스토리지 노드로의 S3 트래픽의 로드 밸런싱을 제공하는 로드 밸런서 서비스에 대한 액세스 로그를 포함합니다.
 a| 
관리 노드 및 게이트웨이 노드



| /var/local/log/persistence * 입니다  a| 
재부팅 시 유지되어야 하는 루트 디스크의 파일을 관리하는 Persistence 서비스에 대한 로그를 포함합니다.
 a| 
모든 노드



| /var/local/log/prometheus.log 를 참조하십시오  a| 
모든 노드에 대해 노드 수출자 서비스 로그 및 ade-Exporter 메트릭 서비스 로그를 포함합니다.

관리 노드의 경우 Prometheus 및 Alert Manager 서비스에 대한 로그도 포함됩니다.
 a| 
모든 노드



| /var/local/log/raft.log 를 참조하십시오  a| 
RAFT 프로토콜에 대해 RSM 서비스에서 사용하는 라이브러리의 출력을 포함합니다.
 a| 
RSM 서비스가 있는 스토리지 노드



| /var/local/log/rms.errlog  a| 
S3 플랫폼 서비스에 사용되는 RSM(Replicated State Machine Service) 서비스에 대한 로그를 포함합니다.
 a| 
RSM 서비스가 있는 스토리지 노드



| /var/local/log/ssm.errlog입니다  a| 
 a| 
모든 노드



| /var/local/log/update-s3vs-domains.log 를 참조하십시오  a| 
S3 가상 호스팅 도메인 이름 구성에 대한 업데이트 처리 관련 로그가 들어 있습니다. S3 클라이언트 애플리케이션 구현 지침을 참조하십시오.
 a| 
관리자 및 게이트웨이 노드



| /var/local/log/update-snmp-firewall. * 를 참조하십시오  a| 
SNMP를 위해 관리되는 방화벽 포트와 관련된 로그를 포함합니다.
 a| 
모든 노드



| /var/local/log/update-sysl.log 를 참조하십시오  a| 
시스템 syslog 구성에 대한 변경 사항과 관련된 로그를 포함합니다.
 a| 
모든 노드



| /var/local/log/update-traffic-classes.log 를 참조하십시오  a| 
트래픽 분류자 구성 변경과 관련된 로그를 포함합니다.
 a| 
관리자 및 게이트웨이 노드



| /var/local/log/update-utcn.log 를 참조하십시오  a| 
이 노드의 신뢰할 수 없는 클라이언트 네트워크 모드와 관련된 로그를 포함합니다.
 a| 
모든 노드

|===
.관련 정보
* link:about-bycast-log.html["bycast.log 정보"]
* link:../s3/index.html["S3 REST API 사용"]

