---
permalink: monitor/updating-snmp-agent.html 
sidebar: sidebar 
keywords: how to update the SNMP agent 
summary: SNMP 알림을 비활성화하거나 커뮤니티 문자열을 업데이트하거나 에이전트 주소, USM 사용자 및 트랩 대상을 추가 또는 제거할 수 있습니다. 
---
= SNMP 에이전트를 업데이트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMP 알림을 비활성화하거나 커뮤니티 문자열을 업데이트하거나 에이전트 주소, USM 사용자 및 트랩 대상을 추가 또는 제거할 수 있습니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:../admin/admin-group-permissions.html["루트 액세스 권한"]있습니다.


.이 작업에 대해
SNMP 에이전트 페이지의 각 필드에 대한 자세한 내용은 을 link:configuring-snmp-agent.html["SNMP 에이전트를 구성합니다"]참조하십시오. 각 탭에서 변경한 내용을 적용하려면 페이지 맨 아래에 있는 * 저장 * 을 선택해야 합니다.

.단계
. 구성 * > * 모니터링 * > * SNMP 에이전트 * 를 선택합니다.
+
SNMP 에이전트 페이지가 나타납니다.

. 모든 그리드 노드에서 SNMP 에이전트를 비활성화하려면 * Enable SNMP * 확인란을 선택 취소하고 * Save * 를 선택합니다.
+
SNMP 에이전트를 다시 활성화하면 이전의 모든 SNMP 구성 설정이 유지됩니다.

. 필요한 경우 기본 구성 섹션의 정보를 업데이트합니다.
+
.. 필요에 따라 * 시스템 연락처 * 및 * 시스템 위치 * 를 업데이트합니다.
.. 필요에 따라 StorageGRID SNMP 에이전트가 트랩 및 알림 알림을 전송할지 여부를 제어하려면 * SNMP 에이전트 알림 활성화 * 확인란을 선택하거나 선택 취소합니다.
+
이 확인란의 선택을 취소하면 SNMP 에이전트는 읽기 전용 MIB 액세스를 지원하지만 SNMP 알림을 보내지 않습니다.

.. 필요에 따라 * 인증 트랩 활성화 * 확인란을 선택하거나 선택 취소하여 StorageGRID SNMP 에이전트가 잘못 인증된 프로토콜 메시지를 받을 때 인증 트랩을 전송할지 여부를 제어합니다.


. SNMPv1 또는 SNMPv2c를 사용하는 경우 선택적으로 커뮤니티 문자열 섹션에서 * 읽기 전용 커뮤니티 * 를 업데이트하거나 추가합니다.
. 트랩 대상을 업데이트하려면 Other configuration(기타 구성) 섹션에서 Trap Destinations(트랩 대상) 탭을 선택합니다.
+
이 탭을 사용하여 StorageGRID 트랩 또는 알림 알림에 대한 하나 이상의 대상을 정의합니다. SNMP 에이전트를 활성화하고 * 저장 * 을 선택하면 StorageGRID는 경고가 트리거될 때 정의된 각 대상에 알림을 보냅니다. 지원되는 MIB-II 엔티티에 대해서도 표준 알림이 전송됩니다(예: ifdown 및 coldstart).

+
입력할 항목에 대한 자세한 내용은 을 link:../monitor/configuring-snmp-agent.html#create-trap-destinations["트랩 대상을 생성합니다"]참조하십시오.

+
** 필요한 경우 기본 트랩 커뮤니티를 업데이트하거나 제거합니다.
+
기본 트랩 커뮤니티를 제거하는 경우 먼저 기존 트랩 대상이 사용자 지정 커뮤니티 문자열을 사용하는지 확인해야 합니다.

** 트랩 대상을 추가하려면 * Create * 를 선택합니다.
** 트랩 대상을 편집하려면 라디오 버튼을 선택하고 * 편집 * 을 선택합니다.
** 트랩 대상을 제거하려면 라디오 버튼을 선택하고 * 제거 * 를 선택합니다.
** 변경 내용을 적용하려면 페이지 맨 아래에 있는 * 저장 * 을 선택합니다.


. 상담원 주소를 업데이트하려면 기타 구성 섹션에서 상담원 주소 탭을 선택합니다.
+
이 탭을 사용하여 하나 이상의 "수신 주소"를 지정할 수 있습니다. SNMP 에이전트가 쿼리를 수신할 수 있는 StorageGRID 주소입니다.

+
입력할 항목에 대한 자세한 내용은 을 link:../monitor/configuring-snmp-agent.html#create-agent-addresses["에이전트 주소를 만듭니다"]참조하십시오.

+
** 상담원 주소를 추가하려면 * 생성 * 을 선택합니다.
** 상담원 주소를 편집하려면 라디오 버튼을 선택하고 * 편집 * 을 선택합니다.
** 상담원 주소를 제거하려면 라디오 단추를 선택하고 * 제거 * 를 선택합니다.
** 변경 내용을 적용하려면 페이지 맨 아래에 있는 * 저장 * 을 선택합니다.


. USM 사용자를 업데이트하려면 Other configuration(기타 구성) 섹션에서 USM users(USM 사용자) 탭을 선택합니다.
+
이 탭을 사용하여 MIB를 쿼리하거나 트랩 및 알림을 받을 권한이 있는 USM 사용자를 정의합니다.

+
입력할 항목에 대한 자세한 내용은 을 link:../monitor/configuring-snmp-agent.html#create-usm-users["USM 사용자를 생성합니다"]참조하십시오.

+
** USM 사용자를 추가하려면 * Create * 를 선택합니다.
** USM 사용자를 편집하려면 라디오 버튼을 선택하고 * 편집 * 을 선택합니다.
+
기존 USM 사용자의 사용자 이름을 변경할 수 없습니다. 사용자 이름을 변경해야 하는 경우 사용자를 제거하고 새 사용자 이름을 만들어야 합니다.

+

NOTE: 사용자의 신뢰할 수 있는 엔진 ID를 추가 또는 제거하고 해당 사용자가 현재 대상에 대해 선택된 경우 대상을 편집하거나 제거해야 합니다. 그렇지 않으면 SNMP 에이전트 구성을 저장할 때 유효성 검사 오류가 발생합니다.

** USM 사용자를 제거하려면 라디오 버튼을 선택하고 * 제거 * 를 선택합니다.
+

NOTE: 제거한 사용자가 트랩 대상에 대해 현재 선택된 경우 대상을 편집하거나 제거해야 합니다. 그렇지 않으면 SNMP 에이전트 구성을 저장할 때 유효성 검사 오류가 발생합니다.

** 변경 내용을 적용하려면 페이지 맨 아래에 있는 * 저장 * 을 선택합니다.


. SNMP 에이전트 구성을 업데이트했으면 * Save * 를 선택합니다.

