---
permalink: maintain/accessing-server-manager-log-file.html 
sidebar: sidebar 
keywords: storagegrid, server manager, log file 
summary: Server Manager를 사용할 때 문제가 발생하면 로그 파일을 확인하십시오. 
---
= 서버 관리자 문제를 해결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Server Manager를 사용할 때 문제가 발생하면 로그 파일을 확인하십시오.

서버 관리자와 관련된 오류 메시지는 다음 위치에 있는 서버 관리자 로그 파일에 캡처됩니다. `/var/local/log/servermanager.log`

이 파일에서 장애와 관련된 오류 메시지를 확인하십시오. 필요한 경우 기술 지원 부서에 문제를 에스컬레이션합니다. 로그 파일을 기술 지원 부서에 전달하라는 메시지가 표시될 수 있습니다.



== 오류 상태의 서비스

서비스가 오류 상태로 전환되면 서비스를 다시 시작하십시오.

.시작하기 전에
 `Passwords.txt`파일이 있습니다.

.이 작업에 대해
Server Manager는 서비스를 모니터링하고 예기치 않게 중지된 서비스를 다시 시작합니다. 서비스에 오류가 발생하면 Server Manager가 서비스를 다시 시작합니다. 5분 내에 서비스 시작 시도가 세 번 실패하면 서비스가 오류 상태로 전환됩니다. 서버 관리자가 다시 시작하지 않습니다.

.단계
. 그리드 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
.. 다음 명령을 입력하여 루트로 전환합니다. `su -`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.


+
루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.

. 서비스의 오류 상태를 확인합니다. `service _servicename_ status`
+
예를 들면 다음과 같습니다.

+
[listing]
----
service ldr status
----
+
서비스가 오류 상태인 경우 다음 메시지가 반환됩니다 `_servicename_ in error state`. 예를 들면 다음과 같습니다.

+
[listing]
----
ldr in error state
----
+

NOTE: 서비스 상태가 인 경우 `disabled` 의 지침을 link:using-donotstart-file.html["서비스에 대한 DoNotStart 파일 제거"]참조하십시오.

. 서비스를 다시 시작하여 오류 상태를 제거해 보십시오. `service _servicename_ restart`
+
서비스가 다시 시작되지 않으면 기술 지원 부서에 문의하십시오.

. 명령 셸에서 로그아웃합니다. `exit`

