---
permalink: maintain/all-node-types-replacing-vmware-node.html 
sidebar: sidebar 
keywords: replace VMware node 
summary: VMware에서 호스팅되어 장애가 발생한 StorageGRID 노드를 복구하면 장애가 발생한 노드를 제거하고 복구 노드를 배포합니다. 
---
= VMware 노드를 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware에서 호스팅되어 장애가 발생한 StorageGRID 노드를 복구하면 장애가 발생한 노드를 제거하고 복구 노드를 배포합니다.

.시작하기 전에
가상 머신을 복구할 수 없으며 교체해야 한다고 판단했습니다.

.이 작업에 대해
먼저 VMware vSphere Web Client를 사용하여 장애가 발생한 그리드 노드와 연결된 가상 머신을 제거합니다. 그런 다음 새 가상 시스템을 구축할 수 있습니다.

이 절차는 그리드 노드 복구 프로세스의 한 단계일 뿐입니다. 노드 제거 및 구축 절차는 관리 노드, 스토리지 노드 및 게이트웨이 노드를 포함한 모든 VMware 노드에 대해 동일합니다.

.단계
. VMware vSphere Web Client에 로그인합니다.
. 장애가 발생한 그리드 노드 가상 시스템으로 이동합니다.
. 복구 노드를 구축하는 데 필요한 모든 정보를 기록해 둡니다.
+
.. 가상 컴퓨터를 마우스 오른쪽 단추로 클릭하고 * 설정 편집 * 탭을 선택한 다음 사용 중인 설정을 확인합니다.
.. 그리드 노드 네트워크 설정을 보고 기록하려면 * vApp Options * 탭을 선택합니다.


. 장애가 발생한 그리드 노드가 스토리지 노드인 경우 데이터 저장에 사용되는 가상 하드 디스크가 손상되지 않았는지 확인하고 복구된 그리드 노드에 다시 연결할 수 있도록 보존합니다.
. 가상 머신의 전원을 끕니다.
. 가상 머신을 삭제하려면 * Actions * > * All vCenter Actions * > * Delete from Disk * 를 선택합니다.
. 교체 노드가 될 새로운 가상 머신을 배포하고 하나 이상의 StorageGRID 네트워크에 연결합니다.  지침은 다음을 참조하세요.link:../swnodes/deploying-storagegrid-node-as-virtual-machine.html["StorageGRID 노드를 가상 시스템으로 구축"] .
+
노드를 배포할 때 선택적으로 노드 포트를 재매핑하거나 CPU 또는 메모리 설정을 늘릴 수 있습니다.

+

NOTE: 새 노드를 구축한 후 스토리지 요구 사항에 따라 새 가상 디스크를 추가하거나, 이전에 제거한 장애가 발생한 그리드 노드에서 보존된 가상 하드 디스크를 다시 연결하거나, 둘 다 다시 연결할 수 있습니다.

. 복구할 노드 유형에 따라 노드 복구 절차를 완료합니다.
+
[cols="1a,2a"]
|===
| 노드 유형입니다 | 로 이동합니다 


 a| 
기본 관리자 노드
 a| 
link:configuring-replacement-primary-admin-node.html["대체 운영 관리자 노드를 구성합니다"]



 a| 
운영 관리자 노드가 아닌 노드
 a| 
link:selecting-start-recovery-to-configure-non-primary-admin-node.html["복구 시작 을 선택하여 비 기본 관리 노드를 구성합니다"]



 a| 
게이트웨이 노드
 a| 
link:selecting-start-recovery-to-configure-gateway-node.html["Start Recovery(복구 시작) 를 선택하여 게이트웨이 노드를 구성합니다"]



 a| 
스토리지 노드
 a| 
link:selecting-start-recovery-to-configure-storage-node.html["복구 시작 을 선택하여 스토리지 노드를 구성합니다"]

|===

