---
permalink: maintain/configuring-ip-addresses.html 
sidebar: sidebar 
keywords: configure ip address, change IP tool, ethernet, dhcp, ha group 
summary: IP 변경 도구를 사용하여 그리드 노드에 대한 IP 주소를 구성하여 네트워크 구성을 수행할 수 있습니다. 
---
= IP 주소 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IP 변경 도구를 사용하여 그리드 노드에 대한 IP 주소를 구성하여 네트워크 구성을 수행할 수 있습니다.

그리드 배포 중에 처음 설정된 네트워킹 구성을 대부분 변경하려면 Change IP(IP 변경) 도구를 사용해야 합니다. 표준 Linux 네트워킹 명령 및 파일을 사용한 수동 변경 사항은 모든 StorageGRID 서비스에 전파되지 않을 수 있으며, 업그레이드, 재부팅 또는 노드 복구 절차 시에도 유지되지 않을 수 있습니다.


NOTE: IP 변경 절차는 중단 절차가 될 수 있습니다. 새 구성이 적용될 때까지 그리드의 부분을 사용할 수 없습니다.


NOTE: Grid Network Subnet List(그리드 네트워크 서브넷 목록)만 변경하는 경우 Grid Manager(그리드 관리자)를 사용하여 네트워크 구성을 추가하거나 변경합니다. 그렇지 않으면 네트워크 구성 문제로 인해 그리드 관리자에 액세스할 수 없거나 그리드 네트워크 라우팅 변경 및 기타 네트워크 변경을 동시에 수행하는 경우 IP 변경 도구를 사용합니다.


TIP: 그리드에 있는 모든 노드의 그리드 네트워크 IP 주소를 변경하려면 를 link:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["그리드 전체의 변경 특수 절차"]사용합니다.



== 이더넷 인터페이스

eth0에 할당된 IP 주소는 항상 그리드 노드의 그리드 네트워크 IP 주소입니다. eth1에 할당된 IP 주소는 항상 그리드 노드의 관리 네트워크 IP 주소입니다. eth2에 할당된 IP 주소는 항상 그리드 노드의 클라이언트 네트워크 IP 주소입니다.

StorageGRID 어플라이언스, eth0, eth1 및 eth2와 같은 일부 플랫폼에서는 종속 브리지 또는 물리적 또는 VLAN 인터페이스의 결합으로 구성된 통합 인터페이스일 수 있습니다. 이러한 플랫폼에서는 * SSM * > * Resources * 탭에 eth0, eth1 또는 eth2와 함께 다른 인터페이스에 할당된 Grid, Admin 및 Client Network IP 주소가 표시될 수 있습니다.



== DHCP를 선택합니다

배포 단계에서는 DHCP만 설정할 수 있습니다. 구성 중에는 DHCP를 설정할 수 없습니다. 그리드 노드의 IP 주소, 서브넷 마스크 및 기본 게이트웨이를 변경하려면 IP 주소 변경 절차를 사용해야 합니다. IP 변경 도구를 사용하면 DHCP 주소가 정적이 됩니다.



== 고가용성(HA) 그룹

* 클라이언트 네트워크 인터페이스가 HA 그룹에 포함되어 있는 경우에는 해당 인터페이스의 클라이언트 네트워크 IP 주소를 HA 그룹에 구성된 서브넷 외부의 주소로 변경할 수 없습니다.
* 클라이언트 네트워크 인터페이스에 구성된 HA 그룹에 할당된 기존 가상 IP 주소의 값으로 클라이언트 네트워크 IP 주소를 변경할 수 없습니다.
* 그리드 네트워크 인터페이스가 HA 그룹에 포함되어 있는 경우에는 해당 인터페이스의 그리드 네트워크 IP 주소를 HA 그룹에 구성된 서브넷 외부의 주소로 변경할 수 없습니다.
* 그리드 네트워크 IP 주소는 그리드 네트워크 인터페이스에 구성된 HA 그룹에 할당된 기존 가상 IP 주소의 값으로 변경할 수 없습니다.

