---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storage node decommission, considerations, appliance node clone 
summary: 스토리지 노드를 해제하기 전에 노드를 복제할 수 있는지 여부를 고려하십시오. 그런 다음 노드를 해제하기로 결정한 경우 서비스 해제 절차 동안 StorageGRID에서 오브젝트 및 메타데이터를 관리하는 방법을 검토하십시오. 
---
= 스토리지 노드 폐기에 대한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드를 해제하기 전에 노드를 복제할 수 있는지 여부를 고려하십시오. 그런 다음 노드를 해제하기로 결정한 경우 서비스 해제 절차 동안 StorageGRID에서 오브젝트 및 메타데이터를 관리하는 방법을 검토하십시오.



== 노드를 서비스 해제하지 않고 클론을 생성할 때

이전 어플라이언스 스토리지 노드를 최신 또는 더 큰 어플라이언스로 교체하려면 확장에 새 어플라이언스를 추가한 다음 이전 어플라이언스를 사용하지 않고 어플라이언스 노드의 클론을 생성하는 것이 좋습니다.

어플라이언스 노드 클론 생성을 사용하면 기존 어플라이언스 노드를 동일한 StorageGRID 사이트에서 호환되는 어플라이언스로 쉽게 교체할 수 있습니다. 클론 생성 프로세스는 모든 데이터를 새 어플라이언스로 전송하고 새 어플라이언스를 가동하고 이전 어플라이언스를 설치 전 상태로 둡니다.

다음과 같은 경우에 어플라이언스 노드를 클론 복제할 수 있습니다.

* 수명이 다한 제품을 교체하십시오.
* 향상된 어플라이언스 기술을 활용하려면 기존 노드를 업그레이드하십시오.
* StorageGRID 시스템에서 스토리지 노드 수를 변경하지 않고 그리드 스토리지 용량을 늘립니다.
* RAID 모드 변경과 같은 스토리지 효율성 향상


자세한 내용은 을 https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["어플라이언스 노드 클론 복제"^] 참조하십시오.



== 접속된 스토리지 노드에 대한 고려 사항

접속된 스토리지 노드 해체 시 고려 사항을 검토합니다.

* 단일 서비스 해제 노드 절차에서 10개 이상의 스토리지 노드를 서비스 해제할 수 없습니다.
* 시스템은 항상 및 활성 을 포함한 운영 요구 사항을 충족할 수 있는 충분한 스토리지 노드를 포함해야 link:understanding-adc-service-quorum.html["ADC 쿼럼"]link:reviewing-ilm-policy-and-storage-configuration.html["ILM 정책"]합니다. 이러한 제한을 충족하려면 기존 스토리지 노드를 폐기하기 전에 확장 작업에서 새 스토리지 노드를 추가해야 할 수 있습니다.
+
소프트웨어 기반 메타데이터 전용 노드가 포함된 그리드에서 스토리지 노드를 해제할 때는 주의하십시오. store_both_objects 및 메타데이터로 구성된 모든 노드를 해제하면 그리드에서 객체를 저장하는 기능이 제거됩니다. 메타데이터 전용 스토리지 노드에 대한 자세한 내용은 을 link:../primer/what-storage-node-is.html#types-of-storage-nodes["스토리지 노드 유형"]참조하십시오.

* 스토리지 노드를 제거하면 대량의 객체 데이터가 네트워크를 통해 전송됩니다. 이러한 전송은 정상적인 시스템 작동에 영향을 주지 않지만 StorageGRID 시스템에서 사용하는 총 네트워크 대역폭에 영향을 미칠 수 있습니다.
* 스토리지 노드 사용 중단과 관련된 작업은 일반 시스템 작업과 관련된 작업보다 우선 순위가 낮습니다. 즉, 서비스 해제는 정상적인 StorageGRID 시스템 작동을 방해하지 않으며 시스템 비활성 기간 동안 예약할 필요가 없습니다. 디커미셔닝 작업은 백그라운드에서 수행되므로 프로세스가 완료되는 데 걸리는 시간을 추정하기가 어렵습니다. 일반적으로 시스템이 정숙하거나 한 번에 하나의 스토리지 노드만 제거하는 경우 서비스 해제가 더 빠르게 완료됩니다.
* 스토리지 노드의 서비스를 해제하는 데 며칠 또는 몇 주가 걸릴 수 있습니다. 이에 따라 이 절차를 계획하십시오. 서비스 해제 프로세스는 시스템 운영에 영향을 주지 않도록 설계되었지만 다른 절차는 제한할 수 있습니다. 일반적으로 그리드 노드를 제거하기 전에 계획된 시스템 업그레이드 또는 확장을 수행해야 합니다.
* 스토리지 노드를 제거하는 동안 다른 유지 관리 절차를 수행해야 하는 경우 다른 절차가 완료된 후 다시 시작할 수 link:pausing-and-resuming-decommission-process-for-storage-nodes.html["서비스 해제 절차를 일시 중지합니다"]있습니다.
+

NOTE: ILM 평가 또는 삭제 코딩 데이터 사용 중단 단계에 도달한 경우에만 * 일시 중지 * 버튼이 활성화됩니다. 그러나 ILM 평가(데이터 마이그레이션)는 백그라운드에서 계속 실행됩니다.

* 서비스 해제 작업이 실행 중일 때는 그리드 노드에서 데이터 복구 작업을 실행할 수 없습니다.
* 스토리지 노드를 사용 중지하는 동안에는 ILM 정책을 변경하지 않아야 합니다.
* 데이터를 영구적으로 안전하게 제거하려면 서비스 해제 절차가 완료된 후 스토리지 노드의 드라이브를 지워야 합니다.




== 연결이 끊어진 스토리지 노드에 대한 고려 사항

연결이 끊어진 스토리지 노드를 해제할 때 고려해야 할 사항을 검토합니다.

* 연결이 끊긴 노드를 온라인 상태로 전환하거나 복구할 수 없다고 확신할 수 없는 경우에는 서비스를 해제하지 마십시오.
+

CAUTION: 노드에서 오브젝트 데이터를 복구할 수 있다고 생각되면 이 절차를 수행하지 마십시오. 대신 기술 지원 부서에 문의하여 노드 복구가 가능한지 확인하십시오.

* 연결이 끊긴 스토리지 노드를 서비스 해제하면 StorageGRID은 다른 스토리지 노드의 데이터를 사용하여 연결이 끊어진 노드에 있었던 오브젝트 데이터 및 메타데이터를 재구성합니다.
* 연결이 끊긴 스토리지 노드를 두 개 이상 해제하는 경우 데이터가 손실될 수 있습니다. 오브젝트 복사본, 삭제 코딩 조각 또는 오브젝트 메타데이터가 충분하지 않은 경우 시스템에서 데이터를 재구성하지 못할 수 있습니다. 소프트웨어 기반 메타데이터 전용 노드를 통해 그리드에서 스토리지 노드를 해제할 경우 오브젝트와 메타데이터를 모두 저장하도록 구성된 모든 노드를 서비스 해제하면 그리드에서 모든 오브젝트 스토리지가 제거됩니다. 메타데이터 전용 스토리지 노드에 대한 자세한 내용은 을 link:../primer/what-storage-node-is.html#types-of-storage-nodes["스토리지 노드 유형"]참조하십시오.
+

CAUTION: 복구할 수 없는 스토리지 노드가 두 개 이상 연결되어 있는 경우 기술 지원 부서에 문의하여 최상의 조치를 취하십시오.

* 연결이 끊긴 스토리지 노드를 폐기하는 경우 StorageGRID는 서비스 해제 프로세스가 끝날 때 데이터 복구 작업을 시작합니다. 이러한 작업은 연결이 끊긴 노드에 저장된 개체 데이터 및 메타데이터를 재구성하려고 시도합니다.
* 연결이 끊긴 스토리지 노드를 폐기하면 서비스 해제 절차가 비교적 빠르게 완료됩니다. 그러나 데이터 복구 작업을 실행하는 데 며칠 또는 몇 주가 걸릴 수 있으며 서비스 해제 절차를 통해 모니터링되지 않습니다. 이러한 작업을 수동으로 모니터링하고 필요에 따라 다시 시작해야 합니다. 을 link:checking-data-repair-jobs.html["데이터 복구 작업을 확인합니다"]참조하십시오.
* 개체의 복사본만 포함된 연결이 끊긴 스토리지 노드를 폐기하면 개체가 손실됩니다. 데이터 복구 작업은 현재 연결된 스토리지 노드에 하나 이상의 복제된 복사본 또는 충분한 삭제 코딩 조각이 있는 경우에만 오브젝트를 재구성 및 복구할 수 있습니다.

