---
permalink: maintain/convert-to-data-only-node.html 
sidebar: sidebar 
keywords: storagegrid, convert node, data-only node 
summary: 성능을 높이려면 느린 비 ADC 스토리지 노드를 데이터 전용 스토리지 노드로 변환할 수 있습니다. 
---
= 스토리지 노드를 데이터 전용 노드로 변환
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능을 높이려면 느린 비 ADC 스토리지 노드를 데이터 전용 스토리지 노드로 변환할 수 있습니다.

스토리지 노드의 성능 특성이 다르면 데이터에만 스토리지 노드를 사용하는 것이 적절합니다. 예를 들어, 성능을 잠재적으로 높이기 위해 메타데이터 전용 고성능 스토리지 노드와 함께 사용하는 데이터 전용 고용량 회전식 디스크 스토리지 노드를 사용할 수 있습니다.

또한 Cassandra에서 RAM이 적은 노드를 제거하면 노드당 메타데이터 용량 한도가 늘어나 더 많은 메타데이터 용량을 얻을 수 있습니다. link:../admin/managing-object-metadata-storage.html["오브젝트 메타데이터 스토리지 관리"] .

데이터 전용 노드를 변환할 때 그리드에는 사이트당 최소 3개의 결합된 스토리지 노드 또는 메타데이터 전용 스토리지 노드가 포함되어야 합니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:../admin/admin-group-permissions.html["유지 관리 또는 루트 액세스 권한"]있습니다.
* 변환하려는 스토리지 노드에 ADC 서비스가 포함되어 있지 않거나link:../maintain/move-adc-service.html["ADC 서비스를 옮겼습니다"] 다른 노드로.
* 저장 노드는 메타데이터 전용 노드도 아니고 데이터 전용 노드도 아닙니다.
* 변환하려는 스토리지 노드에 ADC 서비스가 포함되어 있지 않거나link:../maintain/move-adc-service.html["ADC 서비스를 옮겼습니다"] 다른 노드로.
* 사이트의 다른 노드에 충분한 메타데이터 공간이 있습니다(또는link:../expand/index.html["그리드를 확장했습니다"] ) 변환 중인 스토리지 노드에서 마이그레이션될 메타데이터를 수용합니다.
+
[CAUTION]
====
** 동일한 사이트의 다른 노드로 마이그레이션되는 메타데이터가 크기를 초과하는 경우link:../admin/managing-object-metadata-storage.html["메타데이터 예약 공간"] , 그리드가 불안정해질 것입니다.
** 변환을 시작한 후에는 그리드를 확장할 수 없습니다.


====


.이 작업에 대해
이 절차를 사용하면 ADC 서비스가 포함되지 않은 하나 이상의 결합된 스토리지 노드를 데이터 전용 노드로 변환할 수 있습니다.

이 절차는 스토리지 노드를 변환하는 것 외에도 노드에서 Cassandra를 해제합니다.  모든 메타데이터는 결합된 스토리지 노드나 메타데이터 전용 스토리지 노드로 마이그레이션됩니다.  마이그레이션해야 할 메타데이터의 양에 따라 이 절차를 완료하는 데 노드당 최대 며칠이 걸릴 수 있습니다.


TIP: 일반적으로 노드당 메타데이터 사용량이 1TB 미만이면 한 번에 최대 10개의 노드를 변환할 수 있습니다.  노드당 메타데이터 사용량이 1TB를 초과하는 경우 대신 프로시저당 최대 5개의 노드로 변환합니다.

.단계
. 변환하려는 비 ADC 스토리지 노드의 노드 ID를 기록합니다.
. Grid Manager 상단에서 도움말 아이콘을 선택하고 * API documentation * 을 선택합니다.
. 전용 API 문서로 이동 * 을 선택합니다.
. 선택하세요 `POST /private/convert-to-data-only-node/start` 작업. . link:../admin/using-grid-management-api.html#issue-api-requests["API 요청을 발행합니다"] 자세한 내용은.
+
이 절차가 진행되는 동안 각 노드가 재부팅됩니다.

. 사용할 수 있습니다 `GET /private/convert-to-data-only-node` 절차를 모니터링합니다.  오류가 발생하면 선택하세요 `POST /private/convert-to-data-only-node/retry` 절차를 다시 시도하세요.
. link:../maintain/downloading-recovery-package.html["복구 패키지 다운로드"]이 절차를 완료한 후.

