---
permalink: maintain/convert-to-data-only-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, power down host, power off host 
summary: 성능을 향상시키려면 속도가 느린 비 ADC 스토리지 노드를 데이터 전용 스토리지 노드로 변환할 수 있습니다. 
---
= 스토리지 노드를 데이터 전용 노드로 변환합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능을 향상시키려면 속도가 느린 비 ADC 스토리지 노드를 데이터 전용 스토리지 노드로 변환할 수 있습니다.

스토리지 노드의 성능 특성이 다르면 데이터에만 스토리지 노드를 사용하는 것이 적절합니다. 예를 들어, 성능을 잠재적으로 높이기 위해 메타데이터 전용 고성능 스토리지 노드와 함께 사용하는 데이터 전용 고용량 회전식 디스크 스토리지 노드를 사용할 수 있습니다.

또한 Cassandra에서 낮은 RAM 노드를 제거하면 메타데이터 용량을 더 많이 확보할 수 있으므로 노드당 메타데이터 용량 제한이 증가합니다. 을 link:../admin/managing-object-metadata-storage.html["오브젝트 메타데이터 스토리지 관리"]참조하십시오.

데이터 전용 노드를 설치할 때 그리드에는 다음이 포함되어야 합니다.

* 그리드당 최소 2개의 결합된 스토리지 노드 또는 데이터 전용 스토리지 노드
* 사이트당 하나 이상의 결합된 스토리지 노드 또는 데이터 전용 스토리지 노드
* 사이트당 최소 3개의 결합된 스토리지 노드 또는 메타데이터 전용 스토리지 노드


.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:admin-group-permissions.html["유지 관리 또는 루트 액세스 권한"]있습니다.
* 변환할 스토리지 노드에 ADC 서비스가 없거나 link:../maintain/move-adc-service.html["ADC 서비스를 이동했습니다"]다른 노드가 필요합니다.
* 스토리지 노드는 메타데이터 전용 노드 또는 데이터 전용 노드가 아닙니다.
* 사이트의 다른 노드에 변환 중인 스토리지 노드에서 마이그레이션할 메타데이터를 수용할 수 있는 충분한 메타데이터 공간이 있습니다.


.이 작업에 대해
이 절차를 사용하여 ADC 서비스가 포함되지 않은 하나 이상의 결합된 스토리지 노드 또는 메타데이터 전용 스토리지 노드를 데이터 전용 노드로 변환할 수 있습니다. 스토리지 노드는 동일한 사이트에 있어야 합니다.

스토리지 노드 변환과 더불어 이 절차는 노드에서 Cassandra의 실행 취소를 수행합니다. 모든 메타데이터는 결합된 스토리지 노드 또는 메타데이터 전용 스토리지 노드로 마이그레이션됩니다. 마이그레이션해야 하는 메타데이터의 양에 따라 이 절차를 완료하는 데 노드당 최대 며칠 걸릴 수 있습니다.


TIP: 일반적으로 노드당 메타데이터 사용량이 1TB 미만인 경우 한 번에 최대 10개의 노드를 변환할 수 있습니다. 노드당 메타데이터 사용량이 1TB 이상인 경우 절차당 최대 5개 노드로 변환합니다.

.단계
. 변환할 비 ADC 스토리지 노드의 노드 ID를 기록합니다.
. Grid Manager 상단에서 도움말 아이콘을 선택하고 * API documentation * 을 선택합니다.
. 전용 API 문서로 이동 * 을 선택합니다.
.  `POST /private/convert-to-data-only-node/start`작업을 선택합니다. 자세한 내용은 을 link:../admin/using-grid-management-api.html#issue-api-requests["API 요청을 발행합니다"] 참조하십시오.
+
절차를 수행하는 동안 각 노드가 재부팅됩니다.

. 를 사용하여 절차를 모니터링할 수 `GET /private/convert-to-data-only-node` 있습니다. 오류가 발생하면 을 `POST /private/convert-to-data-only-node/retry` 선택하여 절차를 다시 시도하십시오.
. link:../maintain/downloading-recovery-package.html["복구 패키지를 다운로드합니다"] 이 절차를 완료한 후

