---
permalink: maintain/copying-audit-logs-from-failed-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, audit log, copy audit log, copying audit log, primary admin node, primary admin node 
summary: 실패한 기본 관리 노드에서 감사 로그를 복사할 수 있는 경우, 감사 로그를 보존하여 시스템 활동 및 사용에 대한 그리드의 기록을 유지해야 합니다. 유지 감사 로그를 실행 및 실행한 후 복구된 기본 관리 노드에 복원할 수 있습니다. 
---
= 실패한 기본 관리 노드에서 감사 로그를 복사합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실패한 기본 관리 노드에서 감사 로그를 복사할 수 있는 경우 감사 로그를 보존하여 시스템 활동 및 사용에 대한 그리드의 기록을 유지해야 합니다. 유지 감사 로그를 실행 및 실행한 후 복구된 기본 관리 노드에 복원할 수 있습니다.

.이 작업에 대해
이 절차에서는 실패한 관리 노드의 감사 로그 파일을 별도의 그리드 노드의 임시 위치로 복사합니다. 이렇게 보존된 감사 로그를 대체 관리 노드에 복사할 수 있습니다. 감사 로그는 새 관리 노드에 자동으로 복사되지 않습니다.

실패 유형에 따라 실패한 관리 노드에서 감사 로그를 복사하지 못할 수 있습니다. 배포에 하나의 관리 노드만 있는 경우 복구된 관리 노드는 새 빈 파일의 감사 로그에 이벤트를 기록하기 시작하고 이전에 기록된 데이터가 손실됩니다. 배포에 둘 이상의 관리 노드가 포함된 경우 다른 관리 노드에서 감사 로그를 복구할 수 있습니다.


NOTE: 지금 실패한 관리 노드에서 감사 로그에 액세스할 수 없는 경우 호스트 복구 후 나중에 감사 로그에 액세스할 수 있습니다.

.단계
. 가능하다면 실패한 기본 관리 노드에 로그인하세요.  그렇지 않은 경우, 사용 가능한 관리 노드에 로그인하세요.
+
.. 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
.. 다음 명령을 입력하여 루트로 전환합니다. `su -`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
+
루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.



. AMS 서비스를 중지하면 새 로그 파일이 생성되지 않습니다.``service ams stop``
. 감사 내보내기 디렉터리로 이동합니다.
+
`cd /var/local/audit/export`

+
(또는 `cd /var/local/log` (이전 시스템에서는)

. 소스 로그 파일의 이름을 고유한 번호가 매겨진 파일 이름으로 변경합니다.
+
[NOTE]
====
** 로그 파일이 있는 경우 `/var/local/audit/export` 디렉토리의 이름은 다음과 같습니다. `audit.log` .
** 로그 파일이 있는 경우 `/var/local/log` 디렉토리의 이름은 다음과 같습니다. `localaudit.log` .


====
+
예를 들어, 이름을 바꾸세요 `localaudit.log` 파일로 `2025-10-22.txt.1` .

+
[listing]
----
ls -l
mv localaudit.log 2025-10-22.txt.1
----
. AMS 서비스를 다시 시작합니다. `service ams start`
. 디렉토리를 생성하여 모든 감사 로그 파일을 별도의 그리드 노드의 임시 위치에 복사합니다. `ssh admin@_grid_node_IP_ mkdir -p /var/local/tmp/saved-audit-logs`
+
메시지가 표시되면 admin의 암호를 입력합니다.

. 모든 감사 로그 파일을 임시 위치에 복사: `scp -p * admin@_grid_node_IP_:/var/local/tmp/saved-audit-logs`
+
메시지가 표시되면 admin의 암호를 입력합니다.

. 루트로 로그아웃: `exit`

