---
permalink: maintain/deploying-new-linux-hosts.html 
sidebar: sidebar 
keywords: storagegrid, deploy linux host, new host, new linux host 
summary: 몇 가지 예외가 있을 경우 초기 설치 프로세스 중에 했던 것처럼 새 호스트를 준비합니다. 
---
= 새 Linux 호스트를 배포합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
몇 가지 예외가 있을 경우 초기 설치 프로세스 중에 했던 것처럼 새 호스트를 준비합니다.

물리적 또는 가상 Linux 호스트를 새로 배포하거나 다시 설치하려면 Linux 운영 체제에 대한 StorageGRID 설치 지침에 따라 호스트를 준비하는 절차를 따르십시오.

* link:../rhel/installing-linux.html["Linux 설치(Red Hat Enterprise Linux)"]
* link:../ubuntu/installing-linux.html["Linux(Ubuntu 또는 Debian) 설치"]


이 절차에는 다음 작업을 수행하는 단계가 포함됩니다.

. Linux를 설치합니다.
. 호스트 네트워크를 구성합니다.
. 호스트 스토리지를 구성합니다.
. 컨테이너 엔진을 장착하십시오.
. StorageGRID 호스트 서비스를 설치합니다.
+

CAUTION: 설치 지침에서 "StorageGRID 호스트 서비스 설치" 작업을 완료한 후 중지합니다. "그리드 노드 배포" 작업을 시작하지 마십시오.



이 단계를 수행할 때 다음 중요 지침을 참고하십시오.

* 원래 호스트에서 사용한 것과 동일한 호스트 인터페이스 이름을 사용해야 합니다.
* 공유 스토리지를 사용하여 StorageGRID 노드를 지원하거나 의 일부 또는 전체 드라이브 또는 SSD를 장애가 발생한 노드에서 교체 노드로 이동한 경우 원래 호스트에 있던 것과 동일한 스토리지 매핑을 다시 설정해야 합니다. 예를 들어, 설치 지침에서 권장하는 대로 에서 WWID 및 별칭을 사용한 경우 `/etc/multipath.conf` 교체 호스트에서 에서 동일한 별칭/WWID 쌍을 `/etc/multipath.conf` 사용해야 합니다.
* StorageGRID 노드가 NetApp ONTAP 시스템에서 할당된 스토리지를 사용하는 경우 볼륨에 FabricPool 계층화 정책이 활성화되어 있지 않은지 확인합니다. StorageGRID 노드와 함께 사용되는 볼륨에 대해 FabricPool 계층화를 사용하지 않도록 설정하면 문제 해결과 스토리지 작업이 간소화됩니다.
+

CAUTION: FabricPool를 사용하여 StorageGRID 관련 데이터를 StorageGRID 자체로 계층화하지 마십시오. StorageGRID 데이터를 StorageGRID로 다시 계층화하면 문제 해결과 운영 복잡성이 늘어납니다.


