---
permalink: maintain/grid-node-decommissioning.html 
sidebar: sidebar 
keywords: storagegrid, decommission, remove grid node 
summary: 노드 서비스 해제 절차를 사용하여 하나 이상의 사이트에서 하나 이상의 그리드 노드를 제거할 수 있습니다. 운영 관리자 노드의 해제는 불가능합니다. 
---
= 그리드 노드 해제
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 서비스 해제 절차를 사용하여 하나 이상의 사이트에서 하나 이상의 그리드 노드를 제거할 수 있습니다. 기본 관리 노드를 해제할 수 없습니다.



== 노드를 해제해야 하는 경우

다음 중 하나가 참인 경우 노드 해제 절차를 사용하십시오.

* 확장에서 더 큰 스토리지 노드를 추가한 경우 하나 이상의 더 작은 스토리지 노드를 제거하는 동시에 객체를 보존하려고 합니다.
+

TIP: 이전 어플라이언스를 최신 어플라이언스로 교체하려면 확장 시 새 어플라이언스를 추가한 다음 기존 어플라이언스를 사용 중단하는 대신 고려해 https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["어플라이언스 노드 클론 생성"^] 보십시오.

* 필요한 총 스토리지 용량이 줄어듭니다.
* 더 이상 게이트웨이 노드가 필요하지 않습니다.
* 더 이상 비 기본 관리 노드가 필요하지 않습니다.
* 그리드에는 복구하거나 다시 온라인으로 전환할 수 없는 연결 해제된 노드가 포함되어 있습니다.
* 그리드에는 아카이브 노드가 포함되어 있습니다.




== 노드를 해제하는 방법

연결된 그리드 노드 또는 연결되지 않은 그리드 노드를 해제할 수 있습니다.

연결된 노드를 해제합니다:: 일반적으로 그리드 노드가 StorageGRID 시스템에 연결되어 있고 모든 노드가 정상 상태인 경우에만 그리드 노드를 해제해야 합니다(* nodes * 페이지와 * Decommission Nodes * 페이지에 녹색 아이콘이 있음).
+
--
자세한 내용은 을 link:decommissioning-connected-grid-nodes.html["연결된 그리드 노드 해제"]참조하십시오.

--
연결이 끊어진 노드를 해제합니다:: 경우에 따라 현재 그리드에 연결되어 있지 않은 그리드 노드(상태가 알 수 없음 또는 사용자 다운)를 해제해야 할 수도 있습니다.
+
--
자세한 내용은 을 link:decommissioning-disconnected-grid-nodes.html["연결이 끊긴 그리드 노드의 서비스 해제"]참조하십시오.

--




== 노드를 서비스 해제하기 전에 고려해야 할 사항

두 절차 중 하나를 수행하기 전에 각 노드 유형에 대한 고려 사항을 검토하십시오.

* link:considerations-for-decommissioning-admin-or-gateway-nodes.html["관리자 또는 게이트웨이 노드 서비스 해제를 위한 고려 사항"]
* link:considerations-for-decommissioning-storage-nodes.html["스토리지 노드 파기 관련 고려 사항"]

