---
permalink: maintain/how-site-recovery-is-performed-by-technical-support.html 
sidebar: sidebar 
keywords: storagegrid, site recovery, technical support, tech support 
summary: 전체 StorageGRID 사이트에 장애가 발생하거나 여러 스토리지 노드에 장애가 발생할 경우 기술 지원 부서에 문의해야 합니다. 기술 지원 부서에서는 상황을 평가하고 복구 계획을 개발한 다음 비즈니스 목표를 충족하는 방법으로 장애가 발생한 노드나 사이트를 복구하고 복구 시간을 최적화하며 불필요한 데이터 손실을 예방할 수 있습니다. 
---
= 기술 지원 부서에서 사이트를 복구하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전체 StorageGRID 사이트에 장애가 발생하거나 여러 스토리지 노드에 장애가 발생할 경우 기술 지원 부서에 문의해야 합니다. 기술 지원 부서에서는 상황을 평가하고 복구 계획을 개발한 다음 비즈니스 목표를 충족하는 방법으로 장애가 발생한 노드나 사이트를 복구하고 복구 시간을 최적화하며 불필요한 데이터 손실을 예방할 수 있습니다.


CAUTION: 사이트 복구는 기술 지원 부서에서 수행할 수 있습니다.

StorageGRID 시스템은 다양한 장애에 대한 복원력을 갖추고 있으므로 수많은 복구 및 유지 관리 절차를 직접 수행할 수 있습니다. 그러나 구체적인 단계는 상황에 특정한 요인에 따라 달라지기 때문에 간단한 일반화된 사이트 복구 절차를 만드는 것은 어렵습니다. 예를 들면 다음과 같습니다.

* * 비즈니스 목표 *: StorageGRID 사이트가 완전히 손실된 후에는 비즈니스 목표를 가장 잘 달성할 수 있는 방법을 평가해야 합니다. 예를 들어 손실된 사이트를 제자리에서 다시 빌드하시겠습니까? 새 위치에서 손실된 StorageGRID 사이트를 대체하시겠습니까? 고객의 모든 상황은 다르고 복구 계획은 고객의 우선순위를 고려하여 설계되어야 합니다.
* * 정확한 장애 특성 *: 사이트 복구를 시작하기 전에 장애가 발생한 사이트의 노드가 정상인지 또는 스토리지 노드에 복구 가능한 객체가 포함되어 있는지 확인하십시오. 유효한 데이터가 포함된 노드 또는 스토리지 볼륨을 재구축할 경우 불필요한 데이터 손실이 발생할 수 있습니다.
* * 활성 ILM 정책 *: 그리드에 있는 개체 복사본의 수, 유형 및 위치는 활성 ILM 정책에 의해 제어됩니다. ILM 정책의 세부 사항은 복구 가능한 데이터의 양과 복구에 필요한 특정 기술에 영향을 미칠 수 있습니다.
+

CAUTION: 사이트에 개체의 복사본만 포함되어 있고 사이트가 손실되면 개체가 손실됩니다.

* * 버킷(또는 컨테이너) 일관성 *: 버킷(또는 컨테이너)에 적용되는 일관성은 StorageGRID이 오브젝트 메타데이터를 모든 노드와 사이트에 완전히 복제하는지 여부에 영향을 미쳐 오브젝트 수집이 성공했음을 클라이언트에 알려줍니다. 정합성 보장 값이 최종 일관성을 허용하는 경우 사이트 장애 시 일부 개체 메타데이터가 손실되었을 수 있습니다. 이는 복구 가능한 데이터의 양과 복구 절차의 세부 정보에 영향을 줄 수 있습니다.
* * 최근 변경 내역 *: 복구 절차의 세부 사항은 오류 발생 시 유지 보수 절차가 진행 중이었는지 여부 또는 ILM 정책이 최근에 변경되었는지 여부에 따라 영향을 받을 수 있습니다. 기술 지원 부서에서는 사이트 복구를 시작하기 전에 그리드의 최근 내역과 현재 상황을 평가해야 합니다.



CAUTION: 사이트 복구는 기술 지원 부서에서 수행할 수 있습니다.

다음은 기술 지원 부서에서 장애가 발생한 사이트를 복구하는 데 사용하는 프로세스의 일반적인 개요입니다.

. 기술 지원:
+
.. 실패에 대한 자세한 평가를 수행합니다.
.. 귀사와 협력하여 비즈니스 목표를 검토합니다.
.. 고객의 상황에 맞는 복구 계획을 개발합니다.


. 기본 관리자 노드에 오류가 발생한 경우 기술 지원 부서에서 이를 복구합니다.
. 기술 지원은 다음 개요를 따라 모든 스토리지 노드를 복구합니다.
+
.. 필요에 따라 스토리지 노드 하드웨어 또는 가상 머신을 교체합니다.
.. 개체 메타데이터를 장애가 발생한 사이트로 복원합니다.
.. 객체 데이터를 복구된 스토리지 노드로 복구합니다.
+

CAUTION: 장애가 발생한 단일 스토리지 노드에 대한 복구 절차를 사용하면 데이터가 손실됩니다.

+

NOTE: 전체 사이트에 장애가 발생하면 기술 지원 부서에서는 특수한 명령을 사용하여 개체 및 개체 메타데이터를 성공적으로 복원합니다.



. 기술 지원은 장애가 발생한 다른 노드를 복구합니다.
+
개체 메타데이터 및 데이터가 복구된 후 기술 지원 부서에서는 표준 절차를 사용하여 장애가 발생한 게이트웨이 노드 또는 비기본 관리 노드를 복구합니다.



.관련 정보
link:site-decommissioning.html["사이트 파기"]
