---
permalink: maintain/how-your-system-is-affected-when-you-apply-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: 핫픽스를 적용할 때 StorageGRID 시스템이 어떤 영향을 받는지 알아야 합니다. 
---
= 핫픽스를 적용할 때 시스템이 영향을 받는 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
핫픽스를 적용할 때 StorageGRID 시스템이 어떤 영향을 받는지 알아야 합니다.



== StorageGRID 핫픽스는 무중단으로 운영됩니다

StorageGRID 시스템은 핫픽스 프로세스 전반에 걸쳐 클라이언트 응용 프로그램에서 데이터를 수집하고 검색할 수 있습니다. 같은 유형의 모든 노드를 핫픽스로 승인하면(예: 스토리지 노드) 노드가 한 번에 하나씩 다운되므로 모든 그리드 노드 또는 특정 유형의 모든 그리드 노드를 사용할 수 없는 시간이 없습니다.

지속적인 가용성을 보장하기 위해 ILM 정책에 각 개체의 여러 복사본을 저장하도록 지정하는 규칙이 포함되어 있는지 확인합니다. 또한 모든 외부 S3 클라이언트가 다음 중 하나로 요청을 보내도록 구성되었는지 확인해야 합니다.

* 고가용성(HA) 그룹 가상 IP 주소입니다
* 고가용성 타사 로드 밸런서
* 각 클라이언트에 대해 여러 게이트웨이 노드가 있습니다
* 각 클라이언트에 대해 여러 스토리지 노드




== 클라이언트 애플리케이션은 단기간 동안 중단될 수 있습니다

StorageGRID 시스템은 핫픽스 프로세스를 통해 클라이언트 애플리케이션에서 데이터를 수집하고 검색할 수 있습니다. 하지만 핫픽스가 해당 노드에서 서비스를 다시 시작해야 하는 경우 개별 게이트웨이 노드 또는 스토리지 노드에 대한 클라이언트 연결이 일시적으로 중단될 수 있습니다. 핫픽스 프로세스가 완료되고 개별 노드에서 서비스가 다시 시작된 후 연결이 복원됩니다.

짧은 기간 동안 연결이 끊어지지 않는 경우 핫픽스를 적용하기 위해 다운타임을 예약해야 할 수 있습니다. 선택적 승인을 사용하여 특정 노드가 업데이트되는 시기를 예약할 수 있습니다.


NOTE: 여러 게이트웨이 및 고가용성(HA) 그룹을 사용하여 핫픽스 프로세스 중에 자동 페일오버를 제공할 수 있습니다. 의 지침을 link:../admin/configure-high-availability-group.html["고가용성 그룹 구성"]참조하십시오.



== 경고 및 SNMP 알림이 트리거될 수 있습니다

서비스가 다시 시작되고 StorageGRID 시스템이 혼합 버전 환경으로 작동 중일 때(이전 버전을 실행하는 일부 그리드 노드와 이후 버전으로 업그레이드된 일부 그리드 노드) 알림 및 SNMP 알림이 트리거될 수 있습니다. 일반적으로 이러한 경고 및 알림은 핫픽스가 완료되면 지워집니다.



== 구성 변경이 제한됩니다

StorageGRID에 핫픽스를 적용할 경우:

* 핫픽스가 모든 노드에 적용될 때까지 그리드 구성 변경(예: 그리드 네트워크 서브넷 지정 또는 보류 중인 그리드 노드 승인)을 수행하지 마십시오.
* 핫픽스가 모든 노드에 적용될 때까지 ILM 구성을 업데이트하지 마십시오.

