---
permalink: maintain/monitor-repairs.html 
sidebar: sidebar 
keywords: restore replicated data, restore erasure-coded data, recover appliance storage node, recover storage volume 
summary: '명령줄의 스크립트를 사용하여 복구 작업의 상태를 모니터링할 수 `repair-data` 있습니다.' 
---
= 수리 - 데이터 작업을 모니터링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
명령줄의 스크립트를 사용하여 복구 작업의 상태를 모니터링할 수 `repair-data` 있습니다.

여기에는 수동으로 시작한 작업 또는 서비스 해제 절차의 일부로 StorageGRID가 자동으로 시작한 작업이 포함됩니다.


NOTE: 볼륨 복원 작업을 실행하는 경우 link:../maintain/restoring-volume.html["진행 상황을 모니터링하고 Grid Manager에서 해당 작업의 기록을 확인합니다"]대신

복제된 데이터 *, * 삭제 코딩(EC) 데이터 * 또는 둘 모두를 사용하는지 여부에 따라 작업 상태를 `repair-data` 모니터링합니다.

[role="tabbed-block"]
====
.복제된 데이터
--
* 복제된 복구의 예상 완료율을 얻으려면 repair-data 명령에 옵션을 추가합니다 `show-replicated-repair-status`.
+
`repair-data show-replicated-repair-status`

* 수리가 완료되었는지 확인하려면:
+
.. *노드* > *_수리 중인 스토리지 노드_* > *ILM*을 선택합니다.
.. 평가 섹션의 속성을 검토합니다. 복구가 완료되면 * Awaiting-all * 속성이 0 개체를 나타냅니다.


* 수리를 더 자세히 모니터링하려면:
+
.. *노드*를 선택하세요.
.. _GRID NAME_ * > * ILM * 을 선택합니다.
.. ILM 대기열 그래프 위에 커서를 놓으면 *스캔 속도(객체/초)* 속성 값을 볼 수 있습니다. 스캔 속도(객체/초)는 그리드에 있는 객체가 ILM을 위해 스캔되고 대기열에 추가되는 속도입니다.
.. ILM 대기열 섹션에서 다음 속성을 살펴보세요.
+
*** * 스캔 기간 - 추정 * : 모든 개체의 전체 ILM 스캔을 완료하는 데 걸리는 예상 시간입니다.
+
전체 검사를 수행해도 ILM이 모든 개체에 적용되었다는 보장은 없습니다.

*** *시도된 복구*: 위험도가 높은 것으로 간주되는 복제된 데이터에 대해 시도된 총 개체 복구 작업 수입니다.  고위험 객체는 ILM 정책에 의해 지정되었거나 사본이 분실되어 사본이 하나만 남아 있는 모든 객체를 말합니다.  이 수는 스토리지 노드가 고위험 객체를 복구하려고 할 때마다 증가합니다.  전력망이 혼잡해지면 위험성이 높은 ILM 수리가 우선시됩니다.
+
복구 후 복제가 실패하면 동일한 개체 복구가 다시 증가할 수 있습니다.  + 이러한 속성은 스토리지 노드 볼륨 복구 진행 상황을 모니터링할 때 유용할 수 있습니다.  수리 시도 횟수가 더 이상 증가하지 않고 전체 검사가 완료되면 수리가 완료된 것으로 추정됩니다.



.. 또는 Prometheus 쿼리를 제출하세요. `storagegrid_ilm_scan_period_estimated_minutes` 그리고 `storagegrid_ilm_repairs_attempted` .




--
.삭제 코딩(EC) 데이터
--
삭제 코딩 데이터의 복구를 모니터링하고 실패한 요청을 다시 시도하려면 다음을 수행하십시오.

. 삭제 코딩 데이터 복구 상태를 확인합니다.
+
** *지원* > *도구* > *측정항목*을 선택하면 현재 작업에 대한 예상 완료 시간과 완료율을 볼 수 있습니다.  그런 다음 Grafana 섹션에서 *EC 개요*를 선택합니다.  *Grid EC 작업 예상 완료 시간* 및 *Grid EC 작업 완료율* 대시보드를 살펴보세요.
** 다음 명령을 사용하여 특정 작업의 상태를 `repair-data` 확인합니다.
+
`repair-data show-ec-repair-status --repair-id repair ID`

** 이 명령을 사용하여 모든 수리를 나열합니다.
+
`repair-data show-ec-repair-status`

+
출력에는 이전 및 현재 실행 중인 모든 수리에 대한 정보가 `repair ID` 표시됩니다.



. 출력에 복구 작업이 실패했다고 표시되는 경우 옵션을 사용하여 `--repair-id` 복구를 재시도합니다.
+
이 명령은 복구 ID 6949309319275667690을 사용하여 실패한 노드 복구를 재시도합니다.

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
이 명령은 복구 ID 6949309319275667690을 사용하여 실패한 볼륨 복구를 다시 시도합니다.

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====