---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: ADC 서비스를 같은 사이트의 다른 저장소 노드로 이동할 수 있습니다. 
---
= ADC 서비스를 이동합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ADC 서비스를 같은 사이트의 다른 저장소 노드로 이동할 수 있습니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 있습니다. link:admin-group-permissions.html["유지 관리 또는 루트 액세스 권한"]
* 소스 노드에 ADC 서비스가 포함됩니다.
* 대상 노드에 ADC 서비스가 없습니다.
* 타겟 노드는 메타데이터 전용 또는 결합된 노드입니다(메타데이터 및 개체 데이터).
* 소스 노드와 타겟 노드가 같은 사이트에 있습니다.


.이 작업에 대해
다음과 같은 경우 Move ADC(ADC 이동) 절차를 사용합니다.

* ADC 서비스가 포함된 스토리지 노드의 서비스 해제
* ADC 노드를 데이터 전용 노드로 변환합니다
* ADC 관련 작업을 실행할 노드를 추가합니다


저장소 노드 또는 를 해제하려는 경우 link:../maintain/convert-to-data-only-node.html["스토리지 노드를 데이터 전용 노드로 변환합니다"]먼저 ADC 이동 절차를 사용해야 할 수 있습니다. 반드시 를 확인해야 link:../maintain/understanding-adc-service-quorum.html["ADC 쿼럼이 유지됩니다"]합니다.

이 절차는 ADC, IDNT, acct 및 RSM 서비스를 동일한 사이트의 한 스토리지 노드에서 다른 스토리지 노드로 이동합니다. RSM 및 acct 서비스는 ADC 서비스에 의존하므로 ADC 서비스가 이동되면 자동으로 이동합니다.

.단계
. 소스 및 타겟 노드의 노드 ID를 기록합니다.
+
Grid Management API에서 소스 노드 ID를 로 지칭합니다. `sourceNodeId` 타겟 노드 ID를 로 지칭합니다. `targetNodeId`

. Grid Manager 상단에서 도움말 아이콘을 선택하고 * API documentation * 을 선택합니다.
. 전용 API 문서로 이동 * 을 선택합니다.
.  `POST /private/move-adc/start`작업을 선택합니다. 자세한 내용은 을 link:../admin/using-grid-management-api.html#issue-api-requests["API 요청을 발행합니다"] 참조하십시오.
+
절차를 수행하는 동안 각 노드가 재부팅됩니다.

. 를 사용하여 절차를 모니터링할 수 `GET /private/move-adc` 있습니다. 오류가 발생하면 을 `POST /private/move-adc/retry` 선택하여 절차를 다시 시도하십시오.
. link:../maintain/downloading-recovery-package.html["복구 패키지를 다운로드합니다"] 이 절차를 완료한 후

