---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: 동일한 사이트의 다른 스토리지 노드로 ADC 서비스를 이동할 수 있습니다. 
---
= ADC 서비스 이동
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
동일한 사이트의 다른 스토리지 노드로 ADC 서비스를 이동할 수 있습니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 당신은 가지고있다link:../admin/admin-group-permissions.html["유지 관리 또는 루트 액세스 권한"] .
* 소스 노드에는 ADC 서비스가 포함되어 있습니다.
* 대상 노드에는 ADC 서비스가 없습니다.
* 대상 노드는 메타데이터 전용 노드이거나(메타데이터 및 개체 데이터) 결합 노드입니다.
* 소스 노드와 대상 노드가 동일한 사이트에 있습니다.


.이 작업에 대해
다음을 수행하려는 경우 ADC 이동 절차를 사용하세요.

* ADC 서비스를 호스팅하는 스토리지 노드를 해제합니다.
* ADC 서비스를 호스팅하는 스토리지 노드를 데이터 전용 스토리지 노드로 변환


저장 노드를 해제하려는 경우link:../maintain/convert-to-data-only-node.html["스토리지 노드를 데이터 전용 노드로 변환"] , 먼저 ADC 이동 절차를 사용해야 할 수도 있습니다.  다음을 확인해야 합니다.link:../maintain/understanding-adc-service-quorum.html["ADC 정족수가 유지됩니다."] .

이 절차는 ADC, IDNT, ACCT 및 RSM 서비스를 동일한 사이트의 한 스토리지 노드에서 다른 스토리지 노드로 이동합니다.  RSM, IDNT, ACCT 서비스는 ADC 서비스에 종속되어 있으므로 ADC 서비스가 이동하면 자동으로 이동합니다.

.단계
. 소스 및 대상 노드의 노드 ID를 기록합니다.
+
Grid Management API에서 소스 노드 ID는 다음과 같이 참조됩니다. `sourceNodeId` .  대상 노드 ID는 다음과 같이 지칭됩니다. `targetNodeId` .

. Grid Manager 상단에서 도움말 아이콘을 선택하고 * API documentation * 을 선택합니다.
. 전용 API 문서로 이동 * 을 선택합니다.
. 선택하세요 `POST /private/move-adc/start` 작업. . link:../admin/using-grid-management-api.html#issue-api-requests["API 요청을 발행합니다"] 자세한 내용은.
+
이 절차가 진행되는 동안 두 노드가 순서대로 재부팅됩니다.  소스 노드가 먼저 재부팅되고, 그 다음에 대상 노드가 재부팅됩니다.

. 사용할 수 있습니다 `GET /private/move-adc` 절차를 모니터링합니다.  오류가 발생하면 선택하세요 `POST /private/move-adc/retry` 절차를 다시 시도하세요.
. link:../maintain/downloading-recovery-package.html["복구 패키지 다운로드"]이 절차를 완료한 후.

