---
permalink: maintain/preparing-appliance-storage-node-for-reinstallation.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: 어플라이언스 스토리지 노드를 복구할 때는 먼저 StorageGRID 소프트웨어 재설치를 위한 어플라이언스를 준비해야 합니다. 
---
= 어플라이언스 스토리지 노드의 재설치를 준비합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
어플라이언스 스토리지 노드를 복구할 때는 먼저 StorageGRID 소프트웨어 재설치를 위한 어플라이언스를 준비해야 합니다.

.단계
. 장애가 발생한 스토리지 노드에 로그인:
+
.. 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
.. 다음 명령을 입력하여 루트로 전환합니다. `su -`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.


+
루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.

. StorageGRID 소프트웨어 설치를 위해 어플라이언스 스토리지 노드를 준비합니다. `sgareinstall`
. 계속하라는 메시지가 나타나면 다음을 입력합니다. `y`
+
어플라이언스가 재부팅되고 SSH 세션이 종료됩니다. StorageGRID 어플라이언스 설치 프로그램을 사용할 수 있게 되기까지 일반적으로 5분이 걸리지만 경우에 따라 최대 30분까지 기다려야 할 수도 있습니다.

+

CAUTION: 전원을 껐다가 켜거나 제품을 리셋하여 재부팅을 가속화하려고 하지 마십시오. 자동 BIOS, BMC 또는 기타 펌웨어 업그레이드를 중단할 수 있습니다.

+
StorageGRID 어플라이언스 스토리지 노드가 재설정되고 스토리지 노드의 데이터에 더 이상 액세스할 수 없습니다. 원래 설치 프로세스 중에 구성된 IP 주소는 그대로 유지되지만 절차가 완료되면 이를 확인하는 것이 좋습니다.

+
 `sgareinstall`명령을 실행하면 StorageGRID 프로비저닝된 모든 계정, 암호 및 SSH 키가 제거되고 새 호스트 키가 생성됩니다.


