---
permalink: maintain/rebooting-grid-node-from-grid-manager.html 
sidebar: sidebar 
keywords: reboot grid node, tasks tab 
summary: 노드 페이지의 작업 탭에서 개별 그리드 노드를 재부팅할 수 있습니다. 
---
= 작업 탭에서 그리드 노드를 재부팅합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 페이지의 작업 탭에서 개별 그리드 노드를 재부팅할 수 있습니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:../admin/admin-group-permissions.html["유지 관리 또는 루트 액세스 권한"]있습니다.
* 프로비저닝 암호가 있습니다.
* 기본 관리자 노드 또는 스토리지 노드를 재부팅하는 경우 다음 사항을 검토했습니다.
+
** 기본 관리자 노드를 재부팅하면 브라우저에서 그리드 관리자에 대한 액세스가 일시적으로 중단됩니다.
** 특정 사이트에서 두 개 이상의 스토리지 노드를 재부팅하면 재부팅 기간 동안 특정 객체에 액세스하지 못할 수 있습니다. 이 문제는 ILM 규칙이 * Dual commit * 수집 옵션을 사용하는 경우(또는 규칙이 * Balanced * 를 지정하고 필요한 모든 복제본을 즉시 생성할 수 없는 경우) 발생할 수 있습니다. 이 경우 StorageGRID는 새로 수집된 오브젝트를 동일한 사이트에 있는 두 스토리지 노드에 커밋하고 나중에 ILM을 평가합니다.
** 스토리지 노드가 재부팅되는 동안 모든 개체에 액세스할 수 있도록 노드를 재부팅하기 전에 약 1시간 동안 사이트에서 객체 인제스트를 중지하십시오.




.이 작업에 대해
StorageGRID가 그리드 노드를 재부팅하면 노드에서 명령을 발행하여 `reboot` 노드가 종료되고 재시작됩니다. 모든 서비스가 자동으로 다시 시작됩니다.

* VMware 노드를 재부팅하면 가상 머신이 재부팅됩니다.
* Linux 노드를 재부팅하면 컨테이너가 재부팅됩니다.
* StorageGRID 어플라이언스 노드를 재부팅하면 컴퓨팅 컨트롤러가 재부팅됩니다.



TIP: 둘 이상의 노드를 재부팅해야 하는 경우 를 사용할 수 있습니다link:../maintain/rolling-reboot-procedure.html["롤링 재부팅 절차"].

.단계
. 노드 * 를 선택합니다.
. 재부팅할 그리드 노드를 선택합니다.
. 작업 * 탭을 선택합니다.
. 재부팅 * 을 선택합니다.
+
확인 대화 상자가 나타납니다. 기본 관리 노드를 재부팅할 경우 서비스가 중지되면 브라우저에서 Grid Manager에 대한 연결이 일시적으로 끊겼다는 확인 대화 상자가 나타납니다.

. 프로비저닝 암호를 입력하고 * OK * 를 선택합니다.
. 노드가 재부팅될 때까지 기다립니다.
+
서비스가 종료되는 데 약간의 시간이 걸릴 수 있습니다.

+
노드가 재부팅 중인 경우 Nodes 페이지의 노드에 대해 회색 (Administrative Down) 아이콘이 나타납니다. 모든 서비스가 다시 시작되고 노드가 그리드에 성공적으로 연결되면 노드 페이지에 일반 상태(노드 이름 왼쪽에 아이콘 없음)가 표시되어야 하며, 이는 알림이 활성화되지 않고 노드가 그리드에 연결되어 있음을 나타냅니다.


