---
permalink: maintain/recovering-from-storage-node-failures.html 
sidebar: sidebar 
keywords: recover, storage node failure, Reaper 
summary: 장애가 발생한 스토리지 노드를 복구하는 절차는 장애 유형과 장애가 발생한 스토리지 노드 유형에 따라 다릅니다. 
---
= 스토리지 노드 장애 복구
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
장애가 발생한 스토리지 노드를 복구하는 절차는 장애 유형과 장애가 발생한 스토리지 노드 유형에 따라 다릅니다.

이 표를 사용하여 장애가 발생한 스토리지 노드에 대한 복구 절차를 선택합니다.

[cols="1a,1a,1a"]
|===
| 문제 | 조치 | 참고 


 a| 
* 둘 이상의 스토리지 노드에 장애가 발생했습니다.

 a| 
기술 지원 부서에 문의하십시오.
 a| 
스토리지 노드를 두 개 이상 복구할 경우 Cassandra 데이터베이스의 무결성이 영향을 미치며 데이터 손실이 발생할 수 있습니다.

기술 지원 부서에서는 보조 스토리지 노드의 복구를 시작하는 것이 안전한 시기를 결정할 수 있습니다.

* 참고 *: 한 사이트에서 ADC 서비스를 포함하는 스토리지 노드가 두 개 이상 장애가 발생하면 해당 사이트에 대한 보류 중인 플랫폼 서비스 요청이 손실됩니다.



 a| 
한 사이트에서 둘 이상의 스토리지 노드에 장애가 발생했거나 전체 사이트에 장애가 발생했습니다.
 a| 
기술 지원 부서에 문의하십시오. 사이트 복구 절차를 수행해야 할 수 있습니다.
 a| 
기술 지원 부서에서 고객의 상황을 평가하고 복구 계획을 개발합니다. 을 link:how-site-recovery-is-performed-by-technical-support.html["기술 지원 부서에서 사이트를 복구하는 방법"]참조하십시오.



 a| 
어플라이언스 스토리지 노드에 장애가 발생했습니다.
 a| 
link:recovering-storagegrid-appliance-storage-node.html["어플라이언스 스토리지 노드를 복구합니다"]
 a| 
어플라이언스 스토리지 노드의 복구 절차는 모든 장애 시 동일합니다.



 a| 
하나 이상의 스토리지 볼륨에 오류가 발생했지만 시스템 드라이브가 손상되지 않았습니다
 a| 
link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["시스템 드라이브가 손상되지 않은 스토리지 볼륨 장애로부터 복구합니다"]
 a| 
이 절차는 소프트웨어 기반 스토리지 노드에 사용됩니다.



 a| 
시스템 드라이브에 오류가 발생했습니다.
 a| 
link:reviewing-warnings-for-system-drive-recovery.html["시스템 드라이브 오류에서 복구합니다"]
 a| 
노드 교체 절차는 구축 플랫폼과 스토리지 볼륨의 장애 여부에도 따라 달라집니다.

|===

NOTE: 일부 StorageGRID 복구 절차에서는 리퍼를 사용하여 Cassandra 수리를 처리합니다. 관련 또는 필수 서비스가 시작되는 즉시 수리가 자동으로 이루어집니다. "Reaper" 또는 "Cassandra repair"라는 스크립트 출력을 확인할 수 있습니다. 복구가 실패했음을 나타내는 오류 메시지가 표시되면 오류 메시지에 표시된 명령을 실행합니다.
