---
permalink: maintain/rename-grid-site-node-overview.html 
sidebar: sidebar 
keywords: rename grid, rename site, rename node, display name, system name 
summary: 필요에 따라 전체 그리드, 각 사이트 및 각 노드에 대해 그리드 관리자 전체에 표시되는 표시 이름을 변경할 수 있습니다. 필요할 때마다 표시 이름을 안전하게 업데이트할 수 있습니다. 
---
= 이름 바꾸기 절차를 사용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
필요에 따라 전체 그리드, 각 사이트 및 각 노드에 대해 그리드 관리자 전체에 표시되는 표시 이름을 변경할 수 있습니다. 필요할 때마다 표시 이름을 안전하게 업데이트할 수 있습니다.



== 이름 바꾸기 절차는 무엇입니까?

처음에 StorageGRID를 설치할 때 그리드, 각 사이트 및 각 노드의 이름을 지정합니다. 이러한 초기 이름은 _system names_로 알려져 있으며 StorageGRID 전체에서 처음에 표시된 이름입니다.

시스템 이름은 내부 StorageGRID 작업에 필요하며 변경할 수 없습니다. 그러나 이름 바꾸기 절차를 사용하여 그리드, 각 사이트 및 각 노드에 대해 new_display names_를 정의할 수 있습니다. 이러한 표시 이름은 기본 시스템 이름 대신(또는 일부 경우) 다양한 StorageGRID 위치에 표시됩니다.

이름 바꾸기 절차를 사용하여 오타를 수정하거나, 다른 명명 규칙을 구현하거나, 사이트 및 모든 노드의 위치가 변경되었음을 나타낼 수 있습니다. 시스템 이름과 달리, 표시 이름은 StorageGRID 작업에 영향을 주지 않고 필요할 때마다 업데이트할 수 있습니다.



== 시스템 및 표시 이름은 어디에 표시됩니까?

다음 표에는 StorageGRID 사용자 인터페이스 및 StorageGRID 파일에서 시스템 이름과 표시 이름이 표시되는 위치가 요약되어 있습니다.

[cols="1a,1a,3a"]
|===
| 위치 | 시스템 이름입니다 | 표시 이름 


 a| 
Grid Manager 페이지
 a| 
항목의 이름이 바뀌지 않으면 표시됩니다
 a| 
항목의 이름이 변경된 경우 다음 위치에서 시스템 이름 대신 표시됩니다.

* 대시보드
* 노드 페이지
* 고가용성 그룹을 위한 구성 페이지, 로드 밸런서 엔드포인트, VLAN 인터페이스, 키 관리 서버, 그리드 암호, 방화벽 제어 기능을 제공합니다
* 경고
* 스토리지 풀 정의
* 개체 메타데이터 조회 페이지입니다
* 업그레이드, 핫픽스, SANtricity OS 업그레이드, 서비스 해제, 확장, 복구, 개체 존재 여부 검사
* 지원 페이지(로그 및 진단)
* 관리 노드 세부 정보에 대한 테이블의 관리자 노드 호스트 이름 옆에 있는 단일 로그인 페이지




 a| 
*노드* > 노드의 *개요* 탭
 a| 
항상 표시됩니다
 a| 
항목의 이름이 변경된 경우에만 표시됩니다



 a| 
* 노드 상태 * API
 a| 
항상 반환됩니다
 a| 
항목의 이름이 변경된 경우에만 반환됩니다



 a| 
SSH를 사용하여 노드에 액세스할 때 확인 메시지를 표시합니다
 a| 
항목의 이름이 바뀌지 않은 경우 기본 이름으로 표시됩니다.

`admin@SYSTEM-NAME: ~ $`

항목 이름이 변경될 때 괄호 안에 포함:

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`
 a| 
항목의 이름을 바꿀 때 기본 이름으로 표시됩니다.

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`



 a| 
`Passwords.txt`복구 패키지의 파일
 a| 
다음과 같이 표시됩니다 `Server Name`
 a| 
다음과 같이 표시됩니다 `Display Name`



 a| 
`/etc/hosts` 모든 노드의 파일

예를 들면 다음과 같습니다.

`10.96.99.128 SYSTEM-NAME 28989c59-a2c3-4d30-bb09-6879adf2437f DISPLAY-NAME localhost-grid # storagegrid-gen-host`
 a| 
항상 두 번째 열에 표시됩니다
 a| 
항목의 이름이 변경되면 네 번째 열에 표시됩니다



 a| 
`topology-display-names.json`AutoSupport 데이터에 포함되어 있습니다
 a| 
포함되지 않음
 a| 
항목의 이름이 바뀌지 않으면 비어 있고, 그렇지 않으면 그리드, 사이트 및 노드 ID가 표시 이름에 매핑됩니다.

|===


== 표시 이름 요구 사항

이 절차를 사용하기 전에 표시 이름에 대한 요구 사항을 검토하십시오.



=== 노드의 이름을 표시합니다

노드의 표시 이름은 다음 규칙을 따라야 합니다.

* StorageGRID 시스템에서 고유해야 합니다.
* StorageGRID 시스템의 다른 항목에 대한 시스템 이름과 같을 수 없습니다.
* 1자 이상 32자 이하여야 합니다.
* 숫자, 하이픈(-) 및 대문자와 소문자를 포함할 수 있습니다.
* 문자나 숫자로 시작하거나 끝날 수 있지만 하이픈으로 시작하거나 끝날 수 없습니다.
* 모든 숫자가 될 수 없습니다.
* 대/소문자를 구분하지 않습니다. 예를 들어, `DC1-ADM` 및 `dc1-adm` 은 중복 항목으로 간주됩니다.


이름 바꾸로 인해 표시 이름 또는 시스템 이름이 중복되지 않는 한, 다른 노드에서 이전에 사용한 표시 이름으로 노드 이름을 바꿀 수 있습니다.



=== 그리드 및 사이트의 이름을 표시합니다

눈금 및 사이트의 표시 이름은 다음과 같은 예외 사항과 동일한 규칙을 따릅니다.

* 공백을 포함할 수 있습니다.
* 다음 특수 문자를 포함할 수 있습니다. `= - _ : , . @ !`
* 하이픈을 포함하여 특수 문자로 시작하거나 끝날 수 있습니다.
* 모든 숫자 또는 특수 문자일 수 있습니다.




== 모범 사례를 제시합니다

여러 항목의 이름을 바꾸려는 경우 이 절차를 사용하기 전에 일반 명명 체계를 문서화합니다. 이름이 고유하고 일관되며 이해하기 쉽도록 한 눈에 파악할 수 있는 시스템을 제공합니다.

조직의 요구 사항에 맞는 명명 규칙을 사용할 수 있습니다. 다음과 같은 기본적인 권장 사항을 고려하십시오.

* * 사이트 표시기 *: 사이트가 여러 개인 경우 각 노드 이름에 사이트 코드를 추가합니다.
* * 노드 유형 *: 노드 이름은 일반적으로 노드 유형을 나타냅니다. , `adm` 및 `gw` (스토리지 노드, 관리자 노드 및 게이트웨이 노드)와 같은 약어를 사용할 수 `s` 있습니다.
* * 노드 번호 *: 사이트에 특정 노드 형식이 둘 이상 포함된 경우 각 노드 이름에 고유 번호를 추가합니다.


시간에 따라 변경될 수 있는 이름에 특정 세부 정보를 추가하기 전에 두 번 생각해 보십시오. 예를 들어, 노드 이름은 변경할 수 있으므로 IP 주소를 포함하지 마십시오. 마찬가지로, 장비를 이동하거나 하드웨어를 업그레이드할 경우 랙 위치 또는 어플라이언스 모델 번호가 변경될 수 있습니다.



=== 표시 이름의 예

StorageGRID 시스템에 세 개의 데이터 센터가 있고 각 데이터 센터에 서로 다른 유형의 노드가 있다고 가정해 보겠습니다. 표시 이름은 다음과 같이 간단할 수 있습니다.

* * 그리드 *: `StorageGRID Deployment`
* * 첫 번째 사이트 *: `Data Center 1`
+
** `dc1-adm1`
** `dc1-s1`
** `dc1-s2`
** `dc1-s3`
** `dc1-gw1`


* * 두 번째 사이트 *: `Data Center 2`
+
** `dc2-adm2`
** `dc2-s1`
** `dc2-s2`
** `dc2-s3`


* * 세 번째 사이트 *: `Data Center 3`
+
** `dc3-s1`
** `dc3-s2`
** `dc3-s3`



