---
permalink: maintain/restoring-audit-log-on-recovered-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore audit log, non-primary admin node 
summary: 실패한 비 기본 관리 노드에서 감사 로그를 보존할 수 있으므로 기록 감사 로그 정보를 보존할 수 있다면 복구 중인 비 기본 관리 노드에 복사할 수 있습니다. 
---
= 복구된 비 기본 관리자 노드에서 감사 로그를 복구합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실패한 비 기본 관리 노드에서 감사 로그를 보존할 수 있으므로 기록 감사 로그 정보를 보존할 수 있다면 복구 중인 비 기본 관리 노드에 복사할 수 있습니다.

.시작하기 전에
* 복구된 관리자 노드가 설치되고 실행 중입니다.
* 원래 관리 노드에 장애가 발생한 후 감사 로그를 다른 위치로 복사했습니다.


.이 작업에 대해
관리자 노드에 장애가 발생하면 해당 관리 노드에 저장된 감사 로그가 손실될 수 있습니다. 실패한 관리 노드에서 감사 로그를 복사한 다음 이러한 감사 로그를 복구된 관리 노드로 복원하여 손실로부터 데이터를 보존할 수 있습니다. 오류에 따라 실패한 관리 노드에서 감사 로그를 복사하지 못할 수 있습니다. 이 경우 배포에 둘 이상의 관리 노드가 있는 경우 감사 로그가 모든 관리 노드에 복제되므로 다른 관리 노드에서 감사 로그를 복구할 수 있습니다.

관리자 노드가 하나뿐이고 실패한 노드에서 감사 로그를 복사할 수 없는 경우 복구된 관리자 노드가 새 설치인 것처럼 감사 로그에 이벤트 기록을 시작합니다.

로깅 기능을 복원하려면 가능한 한 빨리 관리자 노드를 복구해야 합니다.

[NOTE]
====
기본적으로 감사 정보는 관리 노드의 감사 로그로 전송됩니다. 다음 중 하나가 적용되는 경우 이 단계를 건너뛸 수 있습니다.

* 외부 syslog 서버를 구성했으며 이제 감사 로그가 관리 노드 대신 syslog 서버로 전송됩니다.
* 감사 메시지를 생성한 로컬 노드에만 저장하도록 명시적으로 지정했습니다.


자세한 내용은 을 link:../monitor/configure-audit-messages.html["감사 메시지 및 외부 syslog 서버를 구성합니다"] 참조하십시오.

====
.단계
. 복구된 관리자 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. +
`ssh admin@recovery_Admin_Node_IP`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
.. 다음 명령을 입력하여 루트로 전환합니다. `su -`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.


+
루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.

. 어떤 감사 파일이 보존되었는지 확인합니다.
+
`cd /var/local/log`

. 보존된 감사 로그 파일을 복구된 관리 노드에 복사합니다.
+
`scp admin@grid_node_IP:/var/local/tmp/saved-audit-logs/YYYY*`

+
메시지가 표시되면 admin의 암호를 입력합니다.

. 보안을 위해 장애가 발생한 그리드 노드에서 복구된 관리 노드에 성공적으로 복사되었는지 확인한 후 감사 로그를 삭제합니다.
. 복구된 관리 노드에서 감사 로그 파일의 사용자 및 그룹 설정을 업데이트합니다.
+
`chown ams-user:bycast *`

. 루트로 로그아웃: `exit`

