---
permalink: maintain/restoring-admin-node-database-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore admin node database, restore database, non-primary admin node 
summary: 실패한 기본 관리자 노드가 아닌 관리자 노드에 대한 속성 및 경고에 대한 기록 정보를 보존하려면 기본 관리자 노드에서 관리자 노드 데이터베이스를 복구할 수 있습니다. 
---
= 비운영 관리자 노드를 복구할 때 관리 노드 데이터베이스를 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실패한 기본 관리자 노드가 아닌 관리자 노드에 대한 속성 및 경고에 대한 기록 정보를 보존하려면 기본 관리자 노드에서 관리자 노드 데이터베이스를 복구할 수 있습니다.

.시작하기 전에
* 복구된 관리자 노드가 설치되고 실행 중입니다.
* StorageGRID 시스템에는 최소 2개의 관리 노드가 포함됩니다.
*  `Passwords.txt`파일이 있습니다.
* 프로비저닝 암호가 있습니다.


.이 작업에 대해
관리 노드에 장애가 발생하면 해당 관리 노드 데이터베이스에 저장된 기록 정보가 손실됩니다. 이 데이터베이스에는 다음 정보가 포함되어 있습니다.

* 알림 기록
* 노드 페이지의 레거시 스타일 차트에서 사용되는 내역 특성 데이터입니다


관리 노드를 복구할 때 소프트웨어 설치 프로세스에서는 복구된 노드에 빈 관리 노드 데이터베이스를 생성합니다. 그러나 새 데이터베이스에는 현재 시스템에 포함되어 있거나 나중에 추가된 서버 및 서비스에 대한 정보만 포함됩니다.

운영 관리자 노드가 아닌 노드를 복원한 경우 운영 관리 노드(_source Admin Node_)에서 복구된 노드로 관리 노드 데이터베이스를 복사하여 기록 정보를 복원할 수 있습니다.


NOTE: 관리 노드 데이터베이스를 복사하는 데 몇 시간이 걸릴 수 있습니다. 일부 Grid Manager 기능은 소스 노드에서 서비스가 중지되는 동안 사용할 수 없습니다.

.단계
. 소스 관리 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
.. 다음 명령을 입력하여 루트로 전환합니다. `su -`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.


. 소스 관리 노드에서 다음 명령을 실행합니다. 그런 다음 메시지가 나타나면 프로비저닝 암호를 입력합니다. `recover-access-points`
. 소스 관리자 노드에서 MI 서비스를 중지합니다. `service mi stop`
. 소스 관리자 노드에서 관리 애플리케이션 프로그램 인터페이스(mgmt-API) 서비스를 중지합니다. `service mgmt-api stop`
. 복구된 관리자 노드에서 다음 단계를 완료합니다.
+
.. 복구된 관리자 노드에 로그인합니다.
+
... 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
... 다음 명령을 입력하여 루트로 전환합니다. `su -`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.


.. MI 서비스를 중지합니다. `service mi stop`
.. mgmt-API 서비스 중지: `service mgmt-api stop`
.. SSH 에이전트에 SSH 개인 키를 추가합니다. 다음을 입력합니다.``ssh-add``
.. 파일에 나열된 SSH 액세스 암호를 `Passwords.txt` 입력합니다.
.. 소스 관리자 노드에서 복구된 관리자 노드로 데이터베이스 복사: `/usr/local/mi/bin/mi-clone-db.sh Source_Admin_Node_IP`
.. 메시지가 표시되면 복구된 관리 노드의 MI 데이터베이스를 덮어쓸지 확인합니다.
+
데이터베이스와 해당 기록 데이터가 복구된 관리 노드에 복사됩니다. 복사 작업이 완료되면 스크립트는 복구된 관리자 노드를 시작합니다.

.. 다른 서버에 대한 암호 없는 액세스가 더 이상 필요하지 않으면 SSH 에이전트에서 개인 키를 제거합니다. 다음을 입력합니다.``ssh-add -D``


. 소스 관리자 노드에서 서비스를 다시 시작합니다. `service servermanager start`

