---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: 스토리지 노드의 장애가 발생한 시스템 드라이브를 복구하기 전에 그리드 노드 복구에 대한 일반 경고 및 고려 사항과 다음과 같은 특정 경고를 검토하십시오. 
---
= 스토리지 노드 시스템 드라이브 복구에 대한 경고
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드의 장애가 발생한 시스템 드라이브를 복구하기 전에 일반 link:warnings-and-considerations-for-grid-node-recovery.html["그리드 노드 복구에 대한 경고 및 고려 사항"]경고 및 다음 특정 경고를 검토하십시오.

스토리지 노드에는 개체 메타데이터가 포함된 Cassandra 데이터베이스가 있습니다. 다음과 같은 경우 Cassandra 데이터베이스가 재구축될 수 있습니다.

* 스토리지 볼륨이 실패하고 복구됩니다.
* 시스템 드라이브 및 하나 이상의 스토리지 볼륨이 실패하고 복구됩니다.


Cassandra가 재구성되면 시스템은 다른 스토리지 노드의 정보를 사용합니다. Cassandra가 최근에 다시 빌드된 경우, Cassandra 데이터가 그리드 전체에서 아직 일관되지 않을 수 있습니다. 너무 많은 스토리지 노드가 오프라인 상태인 경우:

* 일부 Cassandra 데이터를 사용하지 못할 수 있습니다.
* 데이터가 손실될 수 있습니다.



CAUTION: 둘 이상의 스토리지 노드에 장애가 있거나 오프라인 상태인 경우 기술 지원 부서에 문의하십시오. 다음 복구 절차를 수행하지 마십시오. 데이터가 손실될 수 있습니다. 자세한 내용은 을 link:how-site-recovery-is-performed-by-technical-support.html["기술 지원 부서에서 사이트를 복구하는 방법"]참조하십시오.


CAUTION: 이 스토리지 노드가 읽기 전용 유지 보수 모드에 있으면 스토리지 볼륨이 장애가 발생한 다른 스토리지 노드에서 객체를 검색할 수 있습니다. 장애가 발생한 스토리지 노드를 복구하기 전에 스토리지 노드의 볼륨을 장애가 발생한 스토리지 볼륨으로 복구합니다. 의 지침을 link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["시스템 드라이브가 손상되지 않은 스토리지 볼륨 장애로부터 복구합니다"]참조하십시오.


CAUTION: ILM 규칙이 복제된 복사본을 하나만 저장하도록 구성되어 있고 해당 복사본이 실패한 스토리지 볼륨에 있으면 개체를 복구할 수 없습니다.
