---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, volume warning 
summary: 스토리지 노드에 대해 장애가 발생한 스토리지 볼륨을 복구하기 전에 다음 경고를 검토해야 합니다. 
---
= 저장소 볼륨 복구에 대한 경고
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드의 실패한 스토리지 볼륨을 복구하기 전에 다음 경고를 검토하십시오.

스토리지 노드의 스토리지 볼륨(또는 범위)은 볼륨 ID라고 하는 16진수 번호로 식별됩니다. 예를 들어 0000은 첫 번째 볼륨이고 000F는 16번째 볼륨입니다. 각 스토리지 노드의 첫 번째 오브젝트 저장소(볼륨 0)는 오브젝트 메타데이터 및 Cassandra 데이터베이스 작업에 최대 4TB의 공간을 사용하며, 해당 볼륨의 나머지 공간은 오브젝트 데이터에 사용됩니다. 다른 모든 스토리지 볼륨은 오브젝트 데이터에만 사용됩니다.

다음과 같은 경우 Cassandra 데이터베이스가 볼륨 복구 절차의 일부로 재구축될 수 있습니다.

* 볼륨 0이 실패하고 복구됩니다.
* 시스템 드라이브 및 하나 이상의 스토리지 볼륨이 실패하고 복구됩니다.


Cassandra가 재구성되면 시스템은 다른 스토리지 노드의 정보를 사용합니다. Cassandra가 최근에 다시 빌드된 경우, Cassandra 데이터가 그리드 전체에서 아직 일관되지 않을 수 있습니다. 너무 많은 스토리지 노드가 오프라인 상태인 경우:

* 일부 Cassandra 데이터를 사용하지 못할 수 있습니다.
* 데이터가 손실될 수 있습니다.



CAUTION: 둘 이상의 스토리지 노드에 장애가 있거나 오프라인 상태인 경우 기술 지원 부서에 문의하십시오. 다음 복구 절차를 수행하지 마십시오. 데이터가 손실될 수 있습니다. 자세한 내용은 을 link:how-site-recovery-is-performed-by-technical-support.html["기술 지원 부서에서 사이트를 복구하는 방법"]참조하십시오.


CAUTION: ILM 규칙이 복제된 복사본을 하나만 저장하도록 구성되어 있고 장애가 발생한 스토리지 볼륨에 복사본이 있는 경우 개체를 복구할 수 없습니다.

.관련 정보
link:warnings-and-considerations-for-grid-node-recovery.html["그리드 노드 복구에 대한 경고 및 고려 사항"]
