---
permalink: maintain/reviewing-ilm-policy-and-storage-configuration.html 
sidebar: sidebar 
keywords: storagegrid, restore, ilm policy, storage configuration 
summary: 스토리지 노드의 서비스를 해제할 계획인 경우 서비스 해제 프로세스를 시작하기 전에 StorageGRID 시스템의 ILM 정책을 검토해야 합니다. 
---
= ILM 정책 및 스토리지 구성을 검토합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드의 서비스를 해제할 계획인 경우 서비스 해제 프로세스를 시작하기 전에 StorageGRID 시스템의 ILM 정책을 검토해야 합니다.

서비스 해제 중에 모든 오브젝트 데이터가 사용 중지된 스토리지 노드에서 다른 스토리지 노드로 마이그레이션됩니다.


NOTE: 사용 중인 ILM 정책은 _ 사용 중지 중 _ 사용 후 _ 이(가) 사용됩니다. 서비스 해제를 시작하기 전과 서비스 해제가 완료된 후에 이 정책이 데이터 요구사항을 충족해야 합니다.

각 규칙을 검토하여 StorageGRID 시스템이 스토리지 노드 폐기를 수용할 수 있는 올바른 유형과 올바른 위치에 충분한 용량을 계속 보유할 수 있는지 확인해야 link:../ilm/creating-ilm-policy.html["활성 ILM 정책"]합니다.

다음 사항을 고려하십시오.

* ILM 규칙 충족을 위해 ILM 평가 서비스가 오브젝트 데이터를 복사할 수 있습니까?
* 서비스 해제 중에 사이트를 일시적으로 사용할 수 없게 되면 어떻게 됩니까? 다른 위치에서 추가 사본을 만들 수 있습니까?
* 서비스 해제 프로세스는 콘텐츠의 최종 배포에 어떤 영향을 미칩니까? 에 설명된 바와 같이link:consolidating-storage-nodes.html["스토리지 노드 통합"], 이전 버전을 사용 중지하기 전에 해야 link:../expand/index.html["새 스토리지 노드를 추가합니다"]합니다. 더 작은 스토리지 노드를 해체한 후 더 큰 교체 스토리지 노드를 추가하면 기존 스토리지 노드의 용량이 거의 근접할 수 있고 새 스토리지 노드의 컨텐츠가 거의 없을 수 있습니다. 새 오브젝트 데이터에 대한 대부분의 쓰기 작업은 새 스토리지 노드로 보내되므로 시스템 작업의 전반적인 효율성이 감소합니다.
* 시스템에 활성 ILM 정책을 만족하기에 충분한 스토리지 노드가 항상 포함됩니까?
+

NOTE: 충족되지 않는 ILM 정책은 백로그와 경고를 발생시키고 StorageGRID 시스템 작동을 중단할 수 있습니다.



서비스 해제 프로세스로 인해 제안된 토폴로지가 표에 나열된 영역을 평가하여 ILM 정책을 충족하는지 확인합니다.

[cols="1a,2a"]
|===
| 평가할 영역 | 고려할 사항 


 a| 
사용 가능한 용량입니다
 a| 
스토리지 노드에 현재 저장되어 있는 오브젝트 데이터의 영구 복사본을 포함하여 StorageGRID 시스템에 저장된 모든 오브젝트 데이터를 수용할 수 있는 충분한 스토리지 용량이 있습니까?

사용 중단이 완료된 후 적절한 시간 동안 저장된 오브젝트 데이터의 예상 증가를 처리할 수 있는 용량이 충분합니까?



 a| 
저장 위치
 a| 
StorageGRID 시스템 전체에 충분한 용량이 남아 있는 경우, StorageGRID 시스템의 비즈니스 규칙을 충족하는 데 적합한 위치에 용량이 있습니까?



 a| 
스토리지 유형입니다
 a| 
해체 완료 후 적절한 유형의 스토리지가 충분합니까?

예를 들어 ILM 규칙은 콘텐츠가 노후화되면 한 스토리지 유형에서 다른 스토리지 유형으로 콘텐츠를 이동할 수 있습니다. 이 경우 StorageGRID 시스템의 최종 구성에서 적절한 유형의 스토리지를 충분히 사용할 수 있는지 확인해야 합니다.

|===