---
permalink: maintain/selecting-node-recovery-procedure.html 
sidebar: sidebar 
keywords: storagegrid, recover, procedure 
summary: 실패한 노드 유형에 대해 올바른 복구 절차를 선택해야 합니다. 
---
= 노드 복구 절차를 선택합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실패한 노드 유형에 대해 올바른 복구 절차를 선택해야 합니다.

[cols="1a,2a"]
|===
| 그리드 노드 | 복구 절차 


 a| 
둘 이상의 스토리지 노드
 a| 
기술 지원 부서에 문의하십시오. 둘 이상의 스토리지 노드에 장애가 발생한 경우 기술 지원 부서에서 복구를 지원하여 데이터 손실을 초래하는 데이터베이스 불일치를 방지해야 합니다. 사이트 복구 절차가 필요할 수 있습니다.

link:how-site-recovery-is-performed-by-technical-support.html["기술 지원 부서에서 사이트를 복구하는 방법"]



 a| 
단일 스토리지 노드
 a| 
스토리지 노드 복구 절차는 장애 유형과 기간에 따라 다릅니다.

link:recovering-from-storage-node-failures.html["스토리지 노드 장애 복구"]



 a| 
관리자 노드
 a| 
관리 노드 절차는 기본 관리 노드 또는 비 기본 관리 노드 복구 여부에 따라 달라집니다.

link:recovering-from-admin-node-failures.html["관리자 노드 오류에서 복구"]



 a| 
게이트웨이 노드
 a| 
link:replacing-gateway-node.html["게이트웨이 노드에서 복구"]



 a| 
아카이브 노드
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/recovering-from-archive-node-failures.html["아카이브 노드 장애 복구(StorageGRID 11.8 문서 사이트)"^]

|===

NOTE: 두 개 이상의 그리드 노드를 호스팅하는 서버에 장애가 발생하면 원하는 순서로 노드를 복구할 수 있습니다. 그러나 실패한 서버가 기본 관리 노드를 호스팅하고 기본이 아닌 관리 노드가 없는 경우 먼저 기본 관리 노드를 복구해야 합니다. 기본 관리 노드를 먼저 복구하면 다른 노드 복구가 기본 관리 노드에 연결하기 위해 기다리는 동안 중단되는 것을 방지할 수 있습니다.
