---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: 노드의 명령 셸에서 그리드 노드를 종료할 수 있습니다. 
---
= 그리드 노드를 종료합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드의 명령 셸에서 그리드 노드를 종료할 수 있습니다.

.시작하기 전에
*  `Passwords.txt`파일이 있습니다.


.이 작업에 대해
이 절차를 수행하기 전에 다음 사항을 검토하십시오.

* 일반적으로 중단을 방지하기 위해 노드를 한 번에 두 개 이상 종료해서는 안 됩니다.
* 설명서나 기술 지원 부서에서 명시적으로 지시하지 않는 한 유지보수 절차 중에 노드를 종료하지 마십시오.
* 종료 프로세스는 노드가 설치되는 위치를 기반으로 다음과 같이 진행됩니다.
+
** VMware 노드를 종료하면 가상 머신이 종료됩니다.
** Linux 노드를 종료하면 컨테이너가 종료됩니다.
** StorageGRID 어플라이언스 노드를 종료하면 컴퓨팅 컨트롤러가 종료됩니다.


* 한 사이트에서 둘 이상의 스토리지 노드를 종료할 계획이면 노드를 종료하기 전에 해당 사이트에서 약 1시간 동안 객체 인제스트를 중지합니다.
+
ILM 규칙이 * 이중 커밋 * 수집 옵션을 사용하는 경우(또는 규칙이 * 균형 * 옵션을 사용하고 모든 필수 복사본을 즉시 생성할 수 없는 경우), StorageGRID은 새로 수집된 개체를 즉시 동일한 사이트의 두 스토리지 노드에 커밋하고 나중에 ILM을 평가합니다. 한 사이트에 둘 이상의 스토리지 노드가 종료된 경우 종료 기간 동안 새로 수집된 개체에 액세스하지 못할 수 있습니다. 사이트에서 사용 가능한 스토리지 노드가 너무 적은 경우에도 쓰기 작업이 실패할 수 있습니다. 을 link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"]참조하십시오.



.단계
. 그리드 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
.. 다음 명령을 입력하여 루트로 전환합니다. `su -`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.


+
루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.

. 모든 서비스를 중지합니다. `service servermanager stop`
+
서비스를 종료하는 데 최대 15분이 걸릴 수 있으며, 종료 프로세스를 모니터링하기 위해 시스템에 원격으로 로그인하기를 원할 수 있습니다.

. 노드가 VMware 가상 머신에서 실행 중이거나 어플라이언스 노드인 경우 shutdown 명령을 실행합니다. `shutdown -h now`
+
명령 결과에 관계없이 이 단계를 `service servermanager stop` 수행합니다.

+

NOTE: 어플라이언스 노드에서 명령을 실행한 후에는 `shutdown -h now` 어플라이언스의 전원을 껐다가 켜서 노드를 다시 시작해야 합니다.

+
제품의 경우, 이 명령은 컨트롤러를 종료하지만 제품의 전원은 계속 켜져 있습니다. 다음 단계를 완료해야 합니다.

. 어플라이언스 노드의 전원을 끄는 경우 어플라이언스 단계를 따르십시오.
+
[role="tabbed-block"]
====
.SG6160
--
.. SG6100-CN 스토리지 컨트롤러의 전원을 끕니다.
.. SG6100-CN 스토리지 컨트롤러의 파란색 전원 LED가 꺼질 때까지 기다립니다.


--
.SGF6112를 참조하십시오
--
.. 제품의 전원을 끕니다.
.. 파란색 전원 LED가 꺼질 때까지 기다립니다.


--
.SG6000 을 참조하십시오
--
.. 스토리지 컨트롤러 후면의 녹색 캐시 활성 LED가 꺼질 때까지 기다립니다.
+
캐싱된 데이터를 드라이브에 기록해야 하는 경우 이 LED가 켜집니다. 전원을 끄기 전에 이 LED가 꺼질 때까지 기다려야 합니다.

.. 제품의 전원을 끄고 파란색 전원 LED가 꺼질 때까지 기다리십시오.


--
.SG5800을 참조하십시오
--
.. 스토리지 컨트롤러 후면의 녹색 캐시 활성 LED가 꺼질 때까지 기다립니다.
+
캐싱된 데이터를 드라이브에 기록해야 하는 경우 이 LED가 켜집니다. 전원을 끄기 전에 이 LED가 꺼질 때까지 기다려야 합니다.

.. SANtricity 시스템 관리자의 홈 페이지에서 * 진행 중인 작업 보기 * 를 선택합니다.
.. 다음 단계를 계속하기 전에 모든 작업이 완료되었는지 확인하십시오.
.. 컨트롤러 쉘프의 두 전원 스위치를 끄고 컨트롤러 쉘프의 모든 LED가 꺼질 때까지 기다립니다.


--
.SG5700입니다
--
.. 스토리지 컨트롤러 후면의 녹색 캐시 활성 LED가 꺼질 때까지 기다립니다.
+
캐싱된 데이터를 드라이브에 기록해야 하는 경우 이 LED가 켜집니다. 전원을 끄기 전에 이 LED가 꺼질 때까지 기다려야 합니다.

.. 제품의 전원을 끄고 모든 LED 및 7세그먼트 디스플레이 작동이 멈출 때까지 기다리십시오.


--
.SG100 또는 SG1000
--
.. 제품의 전원을 끕니다.
.. 파란색 전원 LED가 꺼질 때까지 기다립니다.


--
====

