---
permalink: maintain/starting-storagegrid-appliance-installation.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, appliance install 
summary: 어플라이언스 스토리지 노드에 StorageGRID를 설치하려면 어플라이언스에 포함된 StorageGRID 어플라이언스 설치 프로그램을 사용합니다. 
---
= StorageGRID 어플라이언스 설치를 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
어플라이언스 스토리지 노드에 StorageGRID를 설치하려면 어플라이언스에 포함된 StorageGRID 어플라이언스 설치 프로그램을 사용합니다.

.시작하기 전에
* 이 어플라이언스는 랙에 설치되어 있고 네트워크에 연결되어 있으며 전원이 켜져 있습니다.
* 네트워크 링크 및 IP 주소는 StorageGRID 어플라이언스 설치 프로그램을 사용하여 어플라이언스에 대해 구성되었습니다.
* StorageGRID 그리드에 대한 기본 관리 노드의 IP 주소를 알고 있습니다.
* StorageGRID 어플라이언스 설치 프로그램의 IP 구성 페이지에 나열된 모든 그리드 네트워크 서브넷은 기본 관리 노드의 그리드 네트워크 서브넷 목록에 정의되어 있습니다.
* 스토리지 어플라이언스의 설치 지침에 따라 이러한 필수 작업을 완료했습니다. 을 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/index.html["하드웨어 설치를 빠르게 시작합니다"^]참조하십시오.
* 을 사용하고 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 어플라이언스의 컴퓨팅 컨트롤러에 할당된 IP 주소 중 하나를 알고 있습니다. 관리 네트워크(컨트롤러의 관리 포트 1), 그리드 네트워크 또는 클라이언트 네트워크의 IP 주소를 사용할 수 있습니다.


.이 작업에 대해
어플라이언스 스토리지 노드에 StorageGRID를 설치하려면 다음을 따르십시오.

* 운영 관리 노드의 IP 주소와 노드의 호스트 이름(시스템 이름)을 지정하거나 확인합니다.
* 설치를 시작하고 볼륨이 구성되고 소프트웨어가 설치될 때까지 기다립니다.
+

NOTE: 어플라이언스 스토리지 노드를 복구할 때는 원래 어플라이언스와 동일한 스토리지 유형(결합, 메타데이터 전용 또는 데이터 전용)으로 다시 설치하세요.  다른 저장 유형을 지정하면 복구가 실패하고 올바른 저장 유형을 지정하여 어플라이언스를 다시 설치해야 합니다.

* 프로세스가 중간에 진행되면 설치가 일시 중지됩니다. 설치를 다시 시작하려면 그리드 관리자에 로그인하고 장애가 발생한 노드의 대체 노드로 보류 중인 스토리지 노드를 구성해야 합니다.
* 노드를 구성한 후에는 어플라이언스 설치 프로세스가 완료되고 어플라이언스가 재부팅됩니다.


.단계
. 브라우저를 열고 어플라이언스에서 컴퓨팅 컨트롤러의 IP 주소 중 하나를 입력합니다.
+
`https://_Controller_IP_:8443`

+
StorageGRID 어플라이언스 설치 관리자 홈 페이지가 나타납니다.

. 기본 관리 노드 연결 섹션에서 기본 관리 노드의 IP 주소를 지정해야 하는지 여부를 확인합니다.
+
StorageGRID 어플라이언스 설치 관리자는 기본 관리 노드 또는 admin_IP가 구성된 다른 그리드 노드가 동일한 서브넷에 있다고 가정하여 이 IP 주소를 자동으로 검색할 수 있습니다.

. 이 IP 주소가 표시되지 않거나 변경해야 하는 경우 주소를 지정합니다.
+
[cols="1a,2a"]
|===
| 옵션을 선택합니다 | 단계 


 a| 
수동 IP 입력
 a| 
.. 관리자 노드 검색 활성화 * 확인란의 선택을 취소합니다.
.. IP 주소를 수동으로 입력하세요.


*참고*: 설치하려면 노드를 설치하는 데 사용할 관리 노드의 IP 주소를 수동으로 입력하세요.  복구를 위해 기본 관리 노드의 IP가 있으면 이를 사용하고, 그렇지 않으면 기본이 아닌 관리 노드의 IP를 사용합니다.

.. 저장 * 을 선택합니다.
.. 새 IP 주소의 연결 상태가 "준비"가 될 때까지 기다립니다.




 a| 
연결된 모든 운영 관리 노드의 자동 검색
 a| 
.. 관리자 노드 검색 활성화 * 확인란을 선택합니다.
.. 검색된 IP 주소 목록에서 이 어플라이언스 스토리지 노드가 배포될 그리드의 관리 노드를 선택합니다.


*참고*: 복구를 위해 기본 관리 노드의 IP가 있으면 이를 사용하고, 그렇지 않으면 기본이 아닌 관리 노드의 IP를 사용하세요.

.. 저장 * 을 선택합니다.
.. 새 IP 주소의 연결 상태가 "준비"가 될 때까지 기다립니다.


|===


. Node Name * 필드에 복구 중인 노드에 사용된 것과 동일한 호스트 이름(시스템 이름)을 입력하고 * Save * 를 클릭합니다.
. 설치 섹션에서 현재 상태가 "기본 관리자 노드 '_ADMIN_IP_'를 사용하여 그리드로 설치를 시작할 준비가 되었습니다"이고 * 설치 시작 * 버튼이 활성화되어 있는지 확인합니다 `_node name_`.
+
설치 시작 * 버튼이 활성화되지 않은 경우 네트워크 구성 또는 포트 설정을 변경해야 할 수 있습니다. 자세한 내용은 제품의 유지보수 지침을 참조하십시오.

. StorageGRID 어플라이언스 설치 관리자 홈 페이지에서 * 설치 시작 * 을 클릭합니다.
+
현재 상태가 "Installation is in progress(설치 진행 중)"로 변경되고 Monitor Installation(모니터 설치) 페이지가 표시됩니다.

+

NOTE: 모니터 설치 페이지에 수동으로 액세스해야 하는 경우 메뉴 모음에서 * 모니터 설치 * 를 클릭합니다. 을 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/monitoring-appliance-installation.html["어플라이언스 설치를 모니터링합니다"^]참조하십시오.


