---
permalink: maintain/starting-software-installation-on-services-appliance-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, services appliance, start software installation 
summary: 서비스 어플라이언스에 게이트웨이 노드 또는 관리자 노드를 설치하려면 어플라이언스에 포함된 StorageGRID 어플라이언스 설치 프로그램을 사용합니다. 
---
= 서비스 어플라이언스에서 소프트웨어 설치를 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
서비스 어플라이언스에 게이트웨이 노드 또는 관리자 노드를 설치하려면 어플라이언스에 포함된 StorageGRID 어플라이언스 설치 프로그램을 사용합니다.

.시작하기 전에
* 이 어플라이언스는 랙에 설치되고 네트워크에 연결되고 전원이 켜집니다.
* 네트워크 링크 및 IP 주소는 StorageGRID 어플라이언스 설치 프로그램을 사용하여 어플라이언스에 대해 구성됩니다.
* 게이트웨이 노드 또는 비 기본 관리 노드를 설치하는 경우 StorageGRID 그리드에 대한 기본 관리 노드의 IP 주소를 알 수 있습니다.
* StorageGRID 어플라이언스 설치 프로그램의 IP 구성 페이지에 나열된 모든 그리드 네트워크 서브넷은 기본 관리 노드의 그리드 네트워크 서브넷 목록에 정의됩니다.
+
을 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/index.html["하드웨어 설치를 빠르게 시작합니다"^]참조하십시오.

* 을 사용하고 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 어플라이언스에 할당된 IP 주소 중 하나가 있습니다. 관리 네트워크, 그리드 네트워크 또는 클라이언트 네트워크의 IP 주소를 사용할 수 있습니다.
* 기본 관리자 노드를 설치하는 경우 이 버전의 StorageGRID에 대한 Ubuntu 또는 Debian 설치 파일을 사용할 수 있습니다.
+

NOTE: 최신 버전의 StorageGRID 소프트웨어는 제조 과정에서 서비스 어플라이언스에 사전 로드되어 있습니다. 사전 로드된 소프트웨어 버전이 StorageGRID 배포에서 사용 중인 버전과 일치하면 설치 파일이 필요하지 않습니다.



.이 작업에 대해
서비스 어플라이언스에 StorageGRID 소프트웨어를 설치하려면:

* 기본 관리 노드의 경우 노드 이름을 지정한 다음 적절한 소프트웨어 패키지를 업로드합니다(필요한 경우).
* 비 기본 관리 노드 또는 게이트웨이 노드의 경우 기본 관리 노드의 IP 주소와 노드 이름을 지정하거나 확인합니다.
* 설치를 시작하고 볼륨이 구성되고 소프트웨어가 설치될 때까지 기다립니다.
* 프로세스가 중간에 진행되면 설치가 일시 중지됩니다. 설치를 다시 시작하려면 그리드 관리자에 로그인하고 보류 중인 노드를 장애 발생 노드의 대체용으로 구성해야 합니다.
* 노드를 구성한 후에는 어플라이언스 설치 프로세스가 완료되고 어플라이언스가 재부팅됩니다.


.단계
. 브라우저를 열고 서비스 어플라이언스의 IP 주소 중 하나를 입력합니다.
+
`https://_Controller_IP_:8443`

+
StorageGRID 어플라이언스 설치 관리자 홈 페이지가 나타납니다.

. 기본 관리자 노드를 설치하려면 다음을 수행합니다.
+
.. 이 노드 섹션의 * 노드 유형 * 에서 * 기본 관리자 * 를 선택합니다.
.. Node Name * 필드에 복구 중인 노드에 사용된 이름과 동일한 이름을 입력하고 * Save * 를 클릭합니다.
.. 설치 섹션에서 현재 상태에 나열된 소프트웨어 버전을 확인합니다
+
설치할 준비가 된 소프트웨어 버전이 올바르면 으로 <<installation_section_step,설치 단계>>건너뜁니다.

.. 다른 버전의 소프트웨어를 업로드하려면 * 고급 * 메뉴에서 * StorageGRID 소프트웨어 업로드 * 를 선택합니다.
+
StorageGRID 소프트웨어 업로드 페이지가 나타납니다.

.. StorageGRID 소프트웨어용 * 소프트웨어 패키지 * 및 * 체크섬 파일 * 을 업로드하려면 * 찾아보기 * 를 클릭합니다.
+
파일을 선택하면 파일이 자동으로 업로드됩니다.

.. StorageGRID 어플라이언스 설치 관리자 홈 페이지로 돌아가려면 * 홈 * 을 클릭합니다.


. 게이트웨이 노드 또는 비기본 관리자 노드를 설치하려면 다음을 수행합니다.
+
.. 복원하는 노드 유형에 따라 이 노드 섹션에서 * 노드 유형 * 에 대해 * 게이트웨이 * 또는 * 비기본 관리자 * 를 선택합니다.
.. Node Name * 필드에 복구 중인 노드에 사용된 이름과 동일한 이름을 입력하고 * Save * 를 클릭합니다.
.. 기본 관리 노드 연결 섹션에서 기본 관리 노드의 IP 주소를 지정해야 하는지 여부를 확인합니다.
+
StorageGRID 어플라이언스 설치 관리자는 기본 관리 노드 또는 admin_IP가 구성된 다른 그리드 노드가 동일한 서브넷에 있다고 가정하여 이 IP 주소를 자동으로 검색할 수 있습니다.

.. 이 IP 주소가 표시되지 않거나 변경해야 하는 경우 주소를 지정합니다.


+
[cols="1a,2a"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
수동 IP 입력
 a| 
.. 관리자 노드 검색 활성화 * 확인란의 선택을 취소합니다.
.. IP 주소를 수동으로 입력합니다.
.. 저장 * 을 클릭합니다.
.. 새 IP 주소의 연결 상태가 "준비"가 될 때까지 기다립니다.




 a| 
연결된 모든 운영 관리 노드의 자동 검색
 a| 
.. 관리자 노드 검색 활성화 * 확인란을 선택합니다.
.. 검색된 IP 주소 목록에서 이 서비스 어플라이언스를 배포할 그리드의 기본 관리 노드를 선택합니다.
.. 저장 * 을 클릭합니다.
.. 새 IP 주소의 연결 상태가 "준비"가 될 때까지 기다립니다.


|===
. [[installation_section_step]] 설치 섹션에서 현재 상태가 노드 이름 설치를 시작할 준비가 되었으며 * 설치 시작 * 버튼이 활성화되었는지 확인합니다.
+
설치 시작 * 버튼이 활성화되지 않은 경우 네트워크 구성 또는 포트 설정을 변경해야 할 수 있습니다. 제품의 유지관리 지침을 참조하십시오.

. StorageGRID 어플라이언스 설치 관리자 홈 페이지에서 * 설치 시작 * 을 클릭합니다.
+
현재 상태가 "Installation is in progress(설치 진행 중)"로 변경되고 Monitor Installation(모니터 설치) 페이지가 표시됩니다.

+

NOTE: 모니터 설치 페이지에 수동으로 액세스해야 하는 경우 메뉴 모음에서 * 모니터 설치 * 를 클릭합니다.


