---
permalink: maintain/step-3-revise-ilm-policy.html 
sidebar: sidebar 
keywords: storagegrid, recover, revise ilm policies 
summary: '사이트 해제 마법사의 3단계\(ILM 정책 수정\)에서 사이트가 ILM 정책에 의해 참조되는지 여부를 확인할 수 있습니다.' 
---
= 3단계: ILM 정책을 수정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사이트 해제 마법사의 3단계(ILM 정책 수정)에서 사이트가 ILM 정책에 의해 참조되는지 확인할 수 있습니다.

.시작하기 전에
방법을 잘 알고 link:../ilm/index.html["ILM을 사용하여 오브젝트를 관리합니다"]있습니다. 스토리지 풀 및 ILM 규칙을 생성하고 ILM 정책을 시뮬레이션하고 활성화하는 데 익숙합니다.

.이 작업에 대해
StorageGRID는 정책(활성 또는 비활성)에서 ILM 규칙이 해당 사이트를 참조하는 경우 사이트를 해제할 수 없습니다.

ILM 정책이 폐기하려는 사이트를 참조하는 경우 해당 정책을 제거하거나 편집하여 다음 요구사항을 충족해야 합니다.

* 모든 오브젝트 데이터를 완벽하게 보호
* 사용 중단하는 사이트를 참조하지 마십시오.
* 사이트를 참조하는 스토리지 풀을 사용하거나 모든 사이트 옵션을 사용하지 마십시오.
* 사이트를 참조하는 삭제 코딩 프로필을 사용하지 마십시오.
* StorageGRID 11.6 이전 버전의 설치에서는 복사본 2개 만들기 규칙을 사용하지 마십시오.



CAUTION: 사이트 제거를 수용하기 위해 단일 복사본 ILM 규칙을 만들지 마십시오. 특정 기간 동안 복제된 복사본을 하나만 생성하는 ILM 규칙은 데이터가 영구적으로 손실될 위험이 있습니다. 복제된 객체 복제본이 하나만 있는 경우 스토리지 노드에 장애가 발생하거나 심각한 오류가 발생한 경우 해당 객체가 손실됩니다. 또한 업그레이드와 같은 유지보수 절차 중에는 개체에 대한 액세스가 일시적으로 중단됩니다.


TIP: 연결된 사이트 서비스 해제 _ 를 수행하는 경우 StorageGRID에서 제거할 사이트에서 현재 개체 데이터를 관리하는 방법을 고려해야 합니다. 데이터 보호 요구사항에 따라 새로운 규칙을 통해 기존 오브젝트 데이터를 다른 사이트로 이동하거나 더 이상 필요하지 않은 추가 오브젝트 복사본을 삭제할 수 있습니다.

새 정책을 설계하는 데 도움이 필요한 경우 기술 지원 부서에 문의하십시오.

.단계
. 3단계(ILM 정책 수정)에서 ILM 정책이 서비스 해제하도록 선택한 사이트를 참조하는지 확인합니다.
. 정책이 나열되지 않으면 * Next * 를 선택하여 로 이동합니다link:step-4-remove-ilm-references.html["4단계: ILM 참조 제거"].
. 하나 이상의_ACTIVE_ILM 정책이 나열되면 각 기존 정책을 클론하거나 사용 중지되는 사이트를 참조하지 않는 새 정책을 생성합니다.
+
.. Policy Name 열에서 정책 링크를 선택합니다.
+
정책에 대한 ILM 정책 세부 정보 페이지가 새 브라우저 탭에 나타납니다. 서비스 해제 사이트 페이지는 기타 탭에 계속 열려 있습니다.

.. 필요에 따라 다음 지침과 지침을 따르십시오.
+
*** ILM 규칙 작업:
+
**** link:../ilm/creating-storage-pool.html["하나 이상의 스토리지 풀을 생성합니다"] 사이트를 참조하지 않습니다.
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html["규칙을 편집하거나 바꿉니다"] 사이트를 참조하십시오.
+

NOTE: 2개 복사본 만들기 * 규칙을 선택하지 마십시오. 이 규칙은 허용되지 않는 * 모든 스토리지 노드 * 스토리지 풀을 사용하기 때문입니다.



*** ILM 정책 작업:
+
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#clone-ilm-policy["기존 ILM 정책을 복제합니다"]link:../ilm/creating-ilm-policy.html["새 ILM 정책을 생성합니다"] 또는.
**** 기본 규칙 및 기타 규칙이 사이트를 참조하지 않도록 합니다.
+

CAUTION: ILM 규칙이 올바른 순서로 되어 있는지 확인해야 합니다. 정책이 활성화되면 위에서 시작하여 나열된 순서대로 새 개체와 기존 개체가 평가됩니다.





.. 테스트 개체를 수집하고 정책을 시뮬레이션하여 올바른 규칙이 적용되도록 합니다.
+

CAUTION: ILM 정책의 오류로 인해 복구할 수 없는 데이터 손실이 발생할 수 있습니다. 정책을 활성화하기 전에 정책을 주의 깊게 검토하고 시뮬레이션하여 의도한 대로 작동하도록 확인합니다.

+

CAUTION: 새로운 ILM 정책을 활성화하면 StorageGRID은 이를 사용하여 기존 오브젝트 및 새로 수집된 오브젝트를 포함한 모든 오브젝트를 관리합니다. 새 ILM 정책을 활성화하기 전에 복제된 기존 오브젝트 및 삭제 코딩 오브젝트의 배치에 대한 변경 사항을 검토하십시오. 기존 오브젝트의 위치를 변경하면 새로운 배치가 평가되고 구현될 때 일시적인 리소스 문제가 발생할 수 있습니다.

.. 새 정책을 활성화하고 이전 정책이 비활성화되었는지 확인합니다.
+
여러 정책을 활성화하려면link:../ilm/creating-ilm-policy.html#activate-ilm-policy["단계에 따라 ILM 정책 태그를 생성합니다"],

+
연결된 사이트의 서비스 해제를 수행하는 경우 StorageGRID는 새 ILM 정책을 활성화하는 즉시 선택한 사이트에서 개체 데이터를 제거하기 시작합니다. 모든 오브젝트 복사본을 이동하거나 삭제하는 데 몇 주가 걸릴 수 있습니다. 사이트에 오브젝트 데이터가 아직 있는 동안 사이트의 폐기에 대한 안전한 사이트 폐기 시작 가능. 하지만 실제 서비스 해제 절차를 시작하기 전에 데이터를 사이트에서 이동할 수 있도록 하면 서비스 해제 절차가 더 빠르게 완료되고 운영 중단 및 성능에 미치는 영향이 줄어듭니다 (마법사 5단계에서 * 서비스 해제 시작 * 을 선택하여).



. 각_inactive_policy에 대해 이전 단계에서 설명한 대로 먼저 각 정책에 대한 링크를 선택하여 해당 링크를 편집하거나 제거합니다.
+
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy["정책을 편집합니다"] 따라서 사이트를 서비스 중단하는 것을 의미하지 않습니다.
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy["정책을 제거합니다"]..


. ILM 규칙 및 정책을 변경한 후에는 3단계(ILM 정책 수정)에 나열된 정책이 더 이상 없어야 합니다. 다음 * 을 선택합니다.
+
4단계(ILM 참조 제거)가 나타납니다.


