---
permalink: maintain/stopping-services-and-shutting-down-grid-nodes.html 
sidebar: sidebar 
keywords: recover, stop services, shut down nodes, node shutdown 
summary: StorageGRID 시스템의 전원을 끄기 전에 각 그리드 노드에서 실행 중인 모든 서비스를 중지한 다음 모든 VMware 가상 머신, 컨테이너 엔진 및 StorageGRID 어플라이언스를 종료해야 합니다. 
---
= 서비스를 중지하고 그리드 노드를 종료합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템의 전원을 끄기 전에 각 그리드 노드에서 실행 중인 모든 서비스를 중지한 다음 모든 VMware 가상 머신, 컨테이너 엔진 및 StorageGRID 어플라이언스를 종료해야 합니다.

.이 작업에 대해
먼저 관리 노드 및 게이트웨이 노드에서 서비스를 중지한 다음 스토리지 노드에서 서비스를 중지합니다.

이 접근 방식을 사용하면 기본 관리 노드를 사용하여 다른 그리드 노드의 상태를 가능한 한 오랫동안 모니터링할 수 있습니다.


NOTE: 단일 호스트에 둘 이상의 그리드 노드가 있는 경우 해당 호스트의 모든 노드를 중지할 때까지 호스트를 종료하지 마십시오. 호스트에 운영 관리 노드가 포함된 경우 해당 호스트를 마지막으로 종료합니다.


NOTE: 필요한 경우 그리드의 기능이나 가용성에 영향을 주지 않고 호스트 유지 관리를 수행할 수 link:linux-migrating-grid-node-to-new-host.html["Linux 호스트 간에 노드를 마이그레이션합니다"]있습니다.

.단계
. 모든 클라이언트 응용 프로그램이 그리드에 액세스하는 것을 중지합니다.
. [[log_in_to_gn] 각 게이트웨이 노드에 로그인:
+
.. 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
.. 다음 명령을 입력하여 루트로 전환합니다. `su -`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
+
루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.



. [[STOP_ALL_SERVICES]] 노드에서 실행 중인 모든 서비스를 중지합니다. `service servermanager stop`
+
서비스를 종료하는 데 최대 15분이 걸릴 수 있으며, 종료 프로세스를 모니터링하기 위해 시스템에 원격으로 로그인하기를 원할 수 있습니다.



. 위의 두 단계를 반복하여 모든 스토리지 노드 및 비기본 관리 노드에서 서비스를 중지합니다.
+
이러한 노드의 서비스는 순서에 관계없이 중지할 수 있습니다.

+

NOTE: 어플라이언스 스토리지 노드에서 서비스를 중지하는 명령을 실행하는 경우 `service servermanager stop` 어플라이언스 전원을 껐다가 켜서 노드를 다시 시작해야 합니다.

. 기본 관리자 노드에 대해 및 의 단계를 <<log_in_to_gn,노드에 로그인합니다>><<stop_all_services,노드에서 모든 서비스를 중지하는 중입니다>>반복합니다.
. Linux 호스트에서 실행 중인 노드의 경우:
+
.. 호스트 운영 체제에 로그인합니다.
.. 노드를 중지합니다. `storagegrid node stop`
.. 호스트 운영 체제를 종료합니다.


. VMware 가상 머신 및 어플라이언스 스토리지 노드에서 실행 중인 노드의 경우 shutdown 명령을 실행합니다. `shutdown -h now`
+
명령 결과에 관계없이 이 단계를 `service servermanager stop` 수행합니다.

+
어플라이언스의 경우 이 명령은 컴퓨팅 컨트롤러를 종료하지만 어플라이언스 전원은 여전히 켜져 있습니다. 다음 단계를 완료해야 합니다.

. 어플라이언스 노드가 있는 경우:
+
** 서비스 어플라이언스 또는 SGF6112 어플라이언스의 경우
+
... 제품의 전원을 끕니다.
... 파란색 전원 LED가 꺼질 때까지 기다립니다.


** SG6160 어플라이언스입니다
+
... SG6100-CN 스토리지 컨트롤러의 전원을 끕니다.
... SG6100-CN 스토리지 컨트롤러의 파란색 전원 LED가 꺼질 때까지 기다립니다.


** SG6000 어플라이언스입니다
+
... 스토리지 컨트롤러 후면의 녹색 캐시 활성 LED가 꺼질 때까지 기다립니다.
+
캐싱된 데이터를 드라이브에 기록해야 하는 경우 이 LED가 켜집니다. 전원을 끄기 전에 이 LED가 꺼질 때까지 기다려야 합니다.

... 제품의 전원을 끄고 파란색 전원 LED가 꺼질 때까지 기다리십시오.


** SG5800 어플라이언스입니다
+
... 스토리지 컨트롤러 후면의 녹색 캐시 활성 LED가 꺼질 때까지 기다립니다.
+
캐싱된 데이터를 드라이브에 기록해야 하는 경우 이 LED가 켜집니다. 전원을 끄기 전에 이 LED가 꺼질 때까지 기다려야 합니다.

... SANtricity 시스템 관리자의 홈 페이지에서 * 진행 중인 작업 보기 * 를 선택합니다.
... 다음 단계를 계속하기 전에 모든 작업이 완료되었는지 확인하십시오.
... 컨트롤러 쉘프의 두 전원 스위치를 끄고 컨트롤러 쉘프의 모든 LED가 꺼질 때까지 기다립니다.


** SG5700 어플라이언스입니다
+
... 스토리지 컨트롤러 후면의 녹색 캐시 활성 LED가 꺼질 때까지 기다립니다.
+
캐싱된 데이터를 드라이브에 기록해야 하는 경우 이 LED가 켜집니다. 전원을 끄기 전에 이 LED가 꺼질 때까지 기다려야 합니다.

... 제품의 전원을 끄고 모든 LED 및 7세그먼트 디스플레이 작동이 멈출 때까지 기다리십시오.




. 필요한 경우 명령 셸에서 로그아웃합니다. `exit`
+
StorageGRID 그리드가 이제 종료되었습니다.



.관련 정보
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["SGF6112 및 SG6160 스토리지 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["SG6000 스토리지 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/index.html["SG5800 스토리지 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["SG5700 스토리지 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/index.html["SG110 및 SG1100 서비스 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["SG100 및 SG1000 서비스 어플라이언스"^]

