---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: '사용 중단 후 관리 도메인 컨트롤러\(ADC\) 서비스가 너무 적을 경우 사이트에서 특정 스토리지 노드를 해제하지 못할 수 있습니다.' 
---
= ADC 쿼럼이란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
서비스 해제 후 남아 있는 관리 도메인 컨트롤러(ADC) 서비스가 너무 적은 경우 사이트에서 특정 스토리지 노드를 서비스 해제하지 못할 수 있습니다.

일부 스토리지 노드에 있는 ADC 서비스는 그리드 토폴로지 정보를 유지하고 그리드에 구성 서비스를 제공합니다. StorageGRID 시스템은 각 사이트에서 항상 사용할 수 있는 ADC 서비스 쿼럼을 필요로 합니다.

노드를 제거하면 ADC 쿼럼이 더 이상 충족되지 않는 경우 스토리지 노드를 해제할 수 없습니다. 서비스 해제 중 ADC 쿼럼을 충족하려면 각 사이트에서 최소 3개의 스토리지 노드에 ADC 서비스가 있어야 합니다. 사이트에 ADC 서비스가 포함된 스토리지 노드가 3개 이상 있는 경우 이러한 노드의 대부분은 서비스 해제 후에도 사용 가능한 상태로 유지되어야 합니다. `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: 소프트웨어 기반 메타데이터 전용 노드가 포함된 그리드에서 스토리지 노드를 해제할 때는 주의하십시오. store_both_objects 및 메타데이터로 구성된 모든 노드를 해제하면 그리드에서 객체를 저장하는 기능이 제거됩니다. 메타데이터 전용 스토리지 노드에 대한 자세한 내용은 을 link:../primer/what-storage-node-is.html#types-of-storage-nodes["스토리지 노드 유형"]참조하십시오.

예를 들어 사이트에 현재 ADC 서비스가 포함된 6개의 스토리지 노드가 있고 3개의 스토리지 노드를 해제하려는 경우를 가정해 보겠습니다. ADC quorum 요구 사항으로 인해 다음과 같이 2개의 서비스 해제 절차를 완료해야 합니다.

* 첫 번째 서비스 해제 절차에서는 ADC 서비스가 있는 4개의 스토리지 노드를 계속 사용할 수 있도록 해야 합니다 `((0.5 * 6) + 1)`. 즉, 처음에 2개의 스토리지 노드만 서비스 해제할 수 있습니다.
* 두 번째 서비스 해제 절차에서는 ADC 쿼럼에 세 가지 ADC 서비스만 사용 가능하도록 필요하므로 세 번째 스토리지 노드를 제거할 수 `((0.5 * 4) + 1)` 있습니다.


저장소 노드를 해제해야 하는 경우 에 새 저장소 노드를 추가하거나 link:../expand/index.html["확장"]ADC 서비스가 있어야 함을 지정하여 ADC 쿼럼 요구 사항을 계속 충족할 수 link:../upgrade/changes-to-grid-management-api.html#new-private-endpoints-for-move-adc["ADC 서비스를 같은 사이트의 다른 저장소 노드로 이동합니다"]있습니다. 그런 다음 쿼럼에 영향을 주지 않고 기존 스토리지 노드를 해제할 수 있습니다.
