---
permalink: primer/nodes-and-services.html 
sidebar: sidebar 
keywords: StorageGRID, services, grid nodes, primary admin, storage, gateway 
summary: StorageGRID 시스템의 기본 구성 요소는 그리드 노드입니다. 노드에는 그리드 노드에 일련의 기능을 제공하는 소프트웨어 모듈인 서비스가 포함됩니다. 
---
= StorageGRID 그리드 노드 및 서비스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템의 기본 구성 요소는 그리드 노드입니다. 노드에는 그리드 노드에 일련의 기능을 제공하는 소프트웨어 모듈인 서비스가 포함됩니다.



== 그리드 노드의 유형

StorageGRID 시스템은 세 가지 유형의 그리드 노드를 사용합니다.

관리자 노드:: 시스템 구성, 모니터링 및 로깅 등의 관리 서비스를 제공합니다. Grid Manager에 로그인하면 관리 노드에 연결됩니다. 각 그리드에는 1개의 기본 관리 노드가 있어야 하며 이중화를 위해 추가적인 비 기본 관리 노드가 있을 수 있습니다. 모든 관리 노드에 연결할 수 있으며 각 관리 노드에는 StorageGRID 시스템의 유사한 보기가 표시됩니다. 그러나 기본 관리 노드를 사용하여 유지 관리 절차를 수행해야 합니다.
+
--
관리 노드를 사용하여 S3 클라이언트 트래픽의 로드 밸런싱을 수행할 수도 있습니다.

을 참조하십시오 link:what-admin-node-is.html["관리 노드란 무엇입니까?"]

--
스토리지 노드:: 오브젝트 데이터 및 메타데이터를 관리 및 저장합니다. StorageGRID 시스템의 각 사이트에는 3개 이상의 스토리지 노드가 있어야 합니다.
+
--
새 스토리지 노드를 처음 설치하는 동안 해당 노드가 다음 용도로만 사용되도록 지정할 수 있습니다.link:../primer/what-storage-node-is.html#types-of-storage-nodes["메타데이터 저장"] .

을 참조하십시오 link:what-storage-node-is.html["스토리지 노드란?"]

--
게이트웨이 노드(선택 사항):: 클라이언트 애플리케이션이 StorageGRID에 연결하는 데 사용할 수 있는 로드 밸런싱 인터페이스를 제공합니다. 로드 밸런서는 클라이언트를 최적의 스토리지 노드로 원활하게 전달하여 노드 장애나 전체 사이트에 대한 투명성이 확보되도록 합니다.
+
--
을 참조하십시오 link:what-gateway-node-is.html["게이트웨이 노드란 무엇입니까?"]

--




== 하드웨어 및 소프트웨어 노드

StorageGRID 노드는 StorageGRID 어플라이언스 노드 또는 소프트웨어 기반 노드로 배포할 수 있습니다.  시스템당 최대 노드 수(모든 노드 유형 포함)는 220개입니다.



=== StorageGRID 어플라이언스 노드

StorageGRID 하드웨어 어플라이언스는 StorageGRID 시스템에서 사용하도록 특별히 설계되었습니다. 일부 어플라이언스는 스토리지 노드로 사용할 수 있습니다. 다른 어플라이언스를 관리 노드 또는 게이트웨이 노드로 사용할 수 있습니다. 어플라이언스 노드를 소프트웨어 기반 노드와 결합하거나, 외부 하이퍼바이저, 스토리지 또는 컴퓨팅 하드웨어에 종속되지 않는 완전히 엔지니어링된 모든 어플라이언스 그리드를 구축할 수 있습니다.

사용 가능한 어플라이언스에 대한 자세한 내용은 다음을 참조하십시오.

* https://docs.netapp.com/us-en/storagegrid-appliances/["StorageGRID 어플라이언스 설명서"^]
* https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]




=== 소프트웨어 기반 노드

소프트웨어 기반 그리드 노드는 VMware 가상 머신으로 배포되거나 Linux 호스트의 컨테이너 엔진 내에 배포될 수 있습니다. 보다 link:../swnodes/index.html["소프트웨어 기반 노드에 StorageGRID 설치"] .

를 사용하여 https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴(IMT)"^] 지원되는 버전을 확인합니다.



== StorageGRID 서비스

다음은 StorageGRID 서비스의 전체 목록입니다.

[cols="2a,3a,2a"]
|===
| 서비스 | 설명 | 위치 


 a| 
계정 서비스 전달자
 a| 
로드 밸런서 서비스가 원격 호스트에서 계정 서비스를 쿼리하도록 하는 인터페이스를 제공하고 로드 밸런서 끝점 구성 변경 사항을 로드 밸런서 서비스에 알려 줍니다.
 a| 
관리 노드 및 게이트웨이 노드의 로드 밸런서 서비스



 a| 
ADC(관리 도메인 컨트롤러)
 a| 
LDR 및 CMN 서비스의 토폴로지 정보 유지, 인증 서비스 제공 및 쿼리에 응답
 a| 
각 사이트에서 ADC 서비스가 포함된 최소 3개의 스토리지 노드



 a| 
AMS(감사 관리 시스템)
 a| 
감사된 모든 시스템 이벤트 및 트랜잭션을 모니터링하고 텍스트 로그 파일에 기록합니다.
 a| 
관리자 노드



 a| 
아파치 톰캣
 a| 
Java 기반 애플리케이션을 위한 웹 서버.
 a| 
관리자 노드



 a| 
아바히 데몬
 a| 
로컬 네트워크 내에서 이름 확인 및 서비스 검색에 사용되는 mDNS를 처리합니다.
 a| 
모든 노드



 a| 
캐시 서비스
 a| 
로드 밸런서(게이트웨이) 노드에서 실행되고 개체 콘텐츠의 로컬 캐시를 관리합니다.
 a| 
게이트웨이 노드



 a| 
Cassandra 를 클릭합니다
 a| 
개체 메타데이터에 대한 분산 데이터베이스를 관리합니다.
 a| 
저장 노드(데이터 전용 제외)



 a| 
Cassandra Refaper(Cassandra 성형기)
 a| 
오브젝트 메타데이터를 자동으로 복구합니다.
 a| 
스토리지 노드



 a| 
청크 서비스
 a| 
삭제 코딩 데이터 및 패리티 조각을 관리합니다.
 a| 
스토리지 노드



 a| 
CMN(구성 관리 노드)
 a| 
시스템 전체 구성 및 그리드 작업 관리 각 그리드에는 하나의 CMN 서비스가 있습니다.
 a| 
기본 관리자 노드



 a| 
DDS(분산 데이터 저장소)
 a| 
Cassandra 데이터베이스와 연결되어 개체 메타데이터를 관리합니다.
 a| 
스토리지 노드



 a| 
DMV(Data Mover)
 a| 
데이터를 클라우드 엔드포인트로 이동합니다.
 a| 
스토리지 노드



 a| 
동적 IP(Dynip)
 a| 
그리드를 모니터링하여 동적 IP 변경 사항을 모니터링하고 로컬 구성을 업데이트합니다.
 a| 
모든 노드



 a| 
그라파나
 a| 
Grid Manager에서 메트릭 시각화에 사용됩니다.
 a| 
관리자 노드



 a| 
고가용성
 a| 
High Availability Groups 페이지에 구성된 노드의 고가용성 가상 IP를 관리합니다. 이 서비스는 Keeepalived 서비스라고도 합니다.
 a| 
관리자 및 게이트웨이 노드



 a| 
ID(idnt)
 a| 
로컬 사용자 및 그룹, 인증을 관리하고 LDAP 및 Active Directory에서 사용자 ID를 연합합니다.
 a| 
ADC 서비스를 사용하는 스토리지 노드입니다



 a| 
람다 중재인
 a| 
S3 Select SelectObjectContent 요청을 관리합니다.
 a| 
모든 노드



 a| 
로드 밸런서(nginx-GW)
 a| 
클라이언트에서 스토리지 노드로의 S3 트래픽의 로드 밸런싱을 제공합니다. 부하 분산 서비스는 부하 분산 엔드포인트 구성 페이지를 통해 구성할 수 있습니다. 이 서비스는 nginx-GW 서비스라고도 합니다.
 a| 
관리자 및 게이트웨이 노드



 a| 
LDR(로컬 분배 라우터)
 a| 
그리드 내의 컨텐츠 저장 및 전송을 관리합니다.
 a| 
스토리지 노드



 a| 
MISCd 정보 서비스 제어 데몬
 a| 
다른 노드의 서비스를 쿼리 및 관리하고 다른 노드에서 실행 중인 서비스 상태를 쿼리하는 것과 같은 노드의 환경 구성을 관리하기 위한 인터페이스를 제공합니다.
 a| 
모든 노드



 a| 
Nginx
 a| 
HTTPS API를 통해 다른 노드의 서비스와 통신할 수 있도록 다양한 그리드 서비스(예: Prometheus 및 Dynamic IP)를 위한 인증 및 보안 통신 메커니즘 역할을 합니다.
 a| 
모든 노드



 a| 
nginx-gw 로드 밸런서
 a| 
클라이언트에서 스토리지 노드로의 S3 트래픽의 로드 밸런싱을 제공합니다. 부하 분산 서비스는 부하 분산 엔드포인트 구성 페이지를 통해 구성할 수 있습니다. 이 서비스는 nginx-GW 서비스라고도 합니다.
 a| 
관리자 및 게이트웨이 노드



 a| 
NMS(네트워크 관리 시스템)
 a| 
Grid Manager를 통해 표시되는 모니터링, 보고 및 구성 옵션을 강화합니다.
 a| 
관리자 노드



 a| 
노드 내보내기(Prometheus 데이터 수집)
 a| 
Prometheus 시계열 메트릭 수집을 위한 시스템 수준 통계를 게시합니다.
 a| 
모든 노드



 a| 
NTP
 a| 
네트워크 시간 프로토콜(NTP) 서비스.
 a| 
모든 노드



 a| 
지속성
 a| 
재부팅 시 유지되어야 하는 루트 디스크의 파일을 관리합니다.
 a| 
모든 노드



 a| 
프로메테우스
 a| 
모든 노드의 서비스에서 시계열 메트릭을 수집합니다.
 a| 
관리자 노드



 a| 
RSM(복제된 상태 시스템)
 a| 
플랫폼 서비스 요청이 각 엔드포인트로 전송되도록 합니다.
 a| 
ADC 서비스를 사용하는 스토리지 노드입니다



 a| 
SSM(서버 상태 모니터)
 a| 
하드웨어 조건을 모니터링하고 NMS 서비스에 보고합니다.
 a| 
모든 그리드 노드에 인스턴스가 있습니다



 a| 
서버 관리자
 a| 
StorageGRID 서비스를 관리합니다.
 a| 
모든 노드



 a| 
SNMP 에이전트
 a| 
SNMP 요청에 응답합니다.
 a| 
관리자 노드



 a| 
SNMP 포트 관리 서비스
 a| 
SNMP 포트의 동적 관리를 처리합니다.
 a| 
모든 노드



 a| 
SSH(보안 셸)
 a| 
보안 액세스와 원격 시스템 관리를 담당합니다.
 a| 
모든 노드



 a| 
SSM(시스템 상태 모니터)
 a| 
하드웨어 조건을 모니터링하고 NMS 서비스에 보고합니다.
 a| 
모든 노드



 a| 
통계
 a| 
S3 버킷과 관련된 추가 메트릭을 기록합니다.
 a| 
스토리지 노드



 a| 
추적 요원(jaeger-agent)
 a| 
추적 수집기(jaeger-collector)에서 제출된 추적 정보를 수신하고 처리합니다.
 a| 
모든 노드



 a| 
트레이스 컬렉터(jaeger-collector)
 a| 
기술 지원 부서에서 사용할 정보를 수집하기 위해 추적 수집을 수행합니다. 추적 수집기 서비스는 오픈 소스 Jaeger 소프트웨어를 사용합니다.
 a| 
관리자 노드

|===