---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: what is a storage node, how many storage nodes 
summary: '스토리지 노드: 오브젝트 데이터 및 메타데이터를 관리하고 저장합니다. 스토리지 노드에는 디스크의 오브젝트 데이터와 메타데이터를 저장, 이동, 확인 및 검색하는 데 필요한 서비스와 프로세스가 포함됩니다.' 
---
= 스토리지 노드란?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드: 오브젝트 데이터 및 메타데이터를 관리하고 저장합니다. 스토리지 노드에는 디스크의 오브젝트 데이터와 메타데이터를 저장, 이동, 확인 및 검색하는 데 필요한 서비스와 프로세스가 포함됩니다.

StorageGRID 시스템의 각 사이트에는 3개 이상의 스토리지 노드가 있어야 합니다.



== 스토리지 노드 유형

설치 중에 설치할 스토리지 노드 유형을 선택할 수 있습니다. 이러한 유형은 소프트웨어 기반 스토리지 노드와 기능을 지원하는 어플라이언스 기반 스토리지 노드에 사용할 수 있습니다.

* 결합된 데이터 및 메타데이터 스토리지 노드
* 메타데이터 전용 스토리지 노드입니다
* 데이터 전용 스토리지 노드


다음과 같은 상황에서 스토리지 노드 유형을 선택할 수 있습니다.

* 스토리지 노드를 처음 설치할 때
* StorageGRID 시스템 확장 중에 스토리지 노드를 추가하는 경우




=== 데이터 및 메타데이터 스토리지 노드(결합됨)

기본적으로 모든 새 스토리지 노드는 객체 데이터와 메타데이터를 모두 저장합니다. 이 유형의 스토리지 노드를 A_COMBINED_Storage Node라고 합니다.



=== 메타데이터 전용 스토리지 노드입니다

그리드에 많은 수의 작은 오브젝트가 저장되는 경우 메타데이터에만 스토리지 노드를 사용하는 것이 적절할 수 있습니다. 전용 메타데이터 용량을 설치하면 많은 수의 작은 개체에 필요한 공간과 이러한 개체에 대한 메타데이터에 필요한 공간 사이의 균형이 향상됩니다. 또한 고성능 어플라이언스에 호스팅되는 메타데이터 전용 스토리지 노드도 성능을 높일 수 있습니다.

메타데이터 전용 스토리지 노드에는 특정 하드웨어 요구 사항이 있습니다.

* StorageGRID 어플라이언스를 사용할 경우 1.9TB 또는 3.8TB 드라이브 12개가 있는 SGF6112 어플라이언스에서만 메타데이터 전용 노드를 구성할 수 있습니다.
* 소프트웨어 기반 노드를 사용할 경우 메타데이터 전용 노드 리소스가 기존 스토리지 노드 리소스와 일치해야 합니다. 예를 들면 다음과 같습니다.
+
** 기존 StorageGRID 사이트에서 SG6000 또는 SG6100 어플라이언스를 사용 중인 경우 소프트웨어 기반 메타데이터 전용 노드가 다음과 같은 최소 요구사항을 충족해야 합니다.
+
*** 128GB RAM
*** 8코어 CPU
*** Cassandra 데이터베이스용 8TB SSD 또는 동급 스토리지(rangedb/0)


** 기존 StorageGRID 사이트가 24GB RAM, 8코어 CPU, 3TB 또는 4TB의 메타데이터 스토리지를 갖춘 가상 스토리지 노드를 사용하는 경우, 소프트웨어 기반 메타데이터 전용 노드는 비슷한 리소스(24GB RAM, 8코어 CPU, 4TB의 메타데이터 스토리지(rangedb/0))를 사용해야 합니다.


* 새로운 StorageGRID 사이트를 추가할 때, 새로운 사이트의 총 메타데이터 용량은 최소한 기존 사이트와 일치해야 합니다.  새로운 사이트의 리소스는 기존 사이트의 스토리지 노드와 일치해야 합니다.



NOTE: 메타데이터 전용 스토리지 노드에는 가 포함되어 있고 S3 클라이언트 요청을 처리할 수 있지만 <<ldr-service,LDR 서비스>>StorageGRID 성능이 향상되지 않을 수 있습니다.



=== 데이터 전용 스토리지 노드

스토리지 노드의 성능 특성이 다르면 데이터에만 스토리지 노드를 사용하는 것이 적절합니다. 예를 들어, 성능을 잠재적으로 높이기 위해 메타데이터 전용 고성능 스토리지 노드와 함께 사용하는 데이터 전용 고용량 회전식 디스크 스토리지 노드를 사용할 수 있습니다.

또한 Cassandra에서 RAM이 적은 노드를 제거하면 노드당 메타데이터 용량 한도가 늘어나 더 많은 메타데이터 용량을 얻을 수 있습니다. link:../admin/managing-object-metadata-storage.html["오브젝트 메타데이터 스토리지 관리"] .

다음을 포함하지 않는 스토리지 노드를 변환할 수 있습니다.<<adc-service,ADC 서비스>> 데이터 전용 스토리지 노드로. link:../maintain/convert-to-data-only-node.html["스토리지 노드를 데이터 전용 노드로 변환"] .



== 그리드당 및 사이트당 필요한 스토리지 노드

토폴로지에서 사용할 스토리지 노드를 선택할 때 그리드 또는 그리드의 각 사이트에 다음 사항이 포함되어야 한다는 점을 명심하세요.

* 사이트당(단일 또는 다중 사이트 그리드): 3개<<adc-service,ADC>> 저장 노드(결합된 저장 노드와 메타데이터 전용 저장 노드의 조합이 될 수 있음)
* 단일 사이트 그리드: 최소 2개의 개체 스토리지 노드(결합 및 데이터 전용의 조합 가능)
* 다중 사이트 그리드: 사이트당 최소 하나의 개체 스토리지 노드(결합 또는 데이터 전용 가능)




== 스토리지 노드의 기본 서비스

다음 표에는 스토리지 노드의 기본 서비스가 나와 있지만 이 표에는 모든 노드 서비스가 나와 있지 않습니다.


NOTE: ADC 서비스 및 RSM 서비스와 같은 일부 서비스는 일반적으로 각 사이트의 세 스토리지 노드에만 존재합니다.

[cols="1a,3a"]
|===
| 서비스 | 키 기능 


 a| 
계정(acct)
 a| 
테넌트 계정을 관리합니다.

데이터 전용 스토리지 노드는 이 서비스를 호스팅하지 않습니다.



 a| 
[[adc-service]]관리 도메인 컨트롤러(ADC)
 a| 
토폴로지 및 그리드 전체의 구성 유지

데이터 전용 스토리지 노드는 이 서비스를 호스팅하지 않습니다.

.세부 정보
[%collapsible]
====
ADC(관리 도메인 컨트롤러) 서비스는 그리드 노드와 상호 연결을 인증합니다. ADC 서비스는 한 사이트에서 최소 3개의 스토리지 노드에 호스팅됩니다.

ADC 서비스는 서비스의 위치 및 가용성을 포함한 토폴로지 정보를 유지합니다. 그리드 노드에 다른 그리드 노드의 정보가 필요하거나 다른 그리드 노드에서 작업을 수행해야 하는 경우 ADC 서비스에 문의하여 요청을 처리할 최적의 그리드 노드를 찾습니다. 또한 ADC 서비스는 StorageGRID 배포의 구성 번들의 사본을 보유하므로 모든 그리드 노드가 현재 구성 정보를 검색할 수 있습니다.

분산 및 분산 작업을 용이하게 하기 위해 각 ADC 서비스는 인증서, 구성 번들 및 서비스 및 토폴로지에 대한 정보를 StorageGRID 시스템의 다른 ADC 서비스와 동기화합니다.

일반적으로 모든 그리드 노드는 하나 이상의 ADC 서비스에 대한 연결을 유지합니다. 이렇게 하면 그리드 노드가 항상 최신 정보에 액세스할 수 있습니다. 그리드 노드가 연결되면 다른 그리드 노드의 인증서를 캐시하여 ADC 서비스를 사용할 수 없는 경우에도 시스템이 알려진 그리드 노드에서 계속 작동할 수 있도록 합니다. 새 그리드 노드는 ADC 서비스를 통해서만 연결을 설정할 수 있습니다.

ADC 서비스는 각 그리드 노드의 연결을 통해 토폴로지 정보를 수집할 수 있습니다. 이 그리드 노드 정보에는 CPU 로드, 사용 가능한 디스크 공간(스토리지가 있는 경우), 지원되는 서비스 및 그리드 노드의 사이트 ID가 포함됩니다. 다른 서비스에서는 ADC 서비스에 토폴로지 쿼리를 통한 토폴로지 정보를 요청합니다. ADC 서비스는 StorageGRID 시스템에서 수신한 최신 정보로 각 쿼리에 응답합니다.

====


 a| 
Cassandra 를 클릭합니다
 a| 
오브젝트 메타데이터를 저장하고 보호합니다.

데이터 전용 스토리지 노드는 이 서비스를 호스팅하지 않습니다.



 a| 
Cassandra Refaper(Cassandra 성형기)
 a| 
오브젝트 메타데이터를 자동으로 복구합니다.

데이터 전용 스토리지 노드는 이 서비스를 호스팅하지 않습니다.



 a| 
청크
 a| 
삭제 코딩 데이터 및 패리티 조각을 관리합니다.



 a| 
Data Mover(DMV)
 a| 
데이터를 클라우드 스토리지 풀로 이동합니다.



 a| 
DDS(분산 데이터 저장소)
 a| 
오브젝트 메타데이터 스토리지를 모니터링합니다.

.세부 정보
[%collapsible]
====
각 스토리지 노드에는 DDS(Distributed Data Store) 서비스가 포함됩니다. 이 서비스는 Cassandra 데이터베이스와 연동되어 StorageGRID 시스템에 저장된 오브젝트 메타데이터에 대한 백그라운드 작업을 수행합니다.

DDS 서비스는 StorageGRID 시스템에 수집된 총 개체 수와 시스템의 지원되는 각 인터페이스(S3)를 통해 수집된 총 개체 수를 추적합니다.

====


 a| 
ID(idnt)
 a| 
LDAP 및 Active Directory에서 사용자 ID를 페더레이션합니다.

데이터 전용 스토리지 노드는 이 서비스를 호스팅하지 않습니다.



 a| 
[[LDR-SERVICE]] 로컬 분배 라우터(LDR)
 a| 
오브젝트 스토리지 프로토콜 요청을 처리하고 디스크의 오브젝트 데이터를 관리합니다.

.세부 정보
[%collapsible]
====
각 _Combined_, _data-only_ 및 _metadata-only_ 스토리지 노드에는 LDR(Local Distribution Router) 서비스가 포함됩니다. 이 서비스는 데이터 저장, 라우팅 및 요청 처리를 비롯한 콘텐츠 전송 기능을 처리합니다. LDR 서비스는 데이터 전송 로드 및 데이터 트래픽 기능을 처리하여 StorageGRID 시스템의 대부분의 작업을 수행합니다.

LDR 서비스는 다음 작업을 처리합니다.

* 쿼리
* ILM(정보 수명 주기 관리) 작업
* 개체 삭제
* 오브젝트 데이터 스토리지
* 다른 LDR 서비스(스토리지 노드)에서 오브젝트 데이터 전송
* 데이터 스토리지 관리
* S3 프로토콜 인터페이스


LDR 서비스는 각 S3 오브젝트도 고유한 UUID에 매핑합니다.

오브젝트 저장소:: LDR 서비스의 기본 데이터 스토리지는 고정된 수의 오브젝트 저장소(스토리지 볼륨이라고도 함)로 나뉩니다. 각 오브젝트 저장소는 별도의 마운트 지점입니다.
+
--
스토리지 노드의 오브젝트 저장소는 002F의 16진수 번호로 식별되며 볼륨 ID라고도 합니다. Cassandra 데이터베이스의 오브젝트 메타데이터에 대한 첫 번째 오브젝트 저장소(볼륨 0)에 공간이 예약되며, 해당 볼륨의 나머지 공간은 오브젝트 데이터에 사용됩니다. 다른 모든 오브젝트 저장소는 복제된 복사본 및 삭제 코딩 조각이 포함된 오브젝트 데이터에만 사용됩니다.

복제된 복사본에 대한 공간 사용이 고르게 되도록 지정된 개체의 개체 데이터는 사용 가능한 스토리지 공간을 기반으로 한 하나의 개체 저장소에 저장됩니다. 개체 저장소의 용량이 가득 차면 나머지 개체 저장소는 스토리지 노드에 더 이상의 공간이 없을 때까지 계속 개체를 저장합니다.

--
메타데이터 보호:: StorageGRID는 LDR 서비스와 상호 작용하는 Cassandra 데이터베이스에 개체 메타데이터를 저장합니다.
+
--
이중화를 보장하고 손실을 방지하기 위해 각 사이트에 오브젝트 메타데이터의 복사본 3개가 유지됩니다. 이 복제는 구성이 불가능하며 자동으로 수행됩니다. 자세한 내용은 을 참조하십시오 link:../admin/managing-object-metadata-storage.html["오브젝트 메타데이터 스토리지 관리"].

--


====


 a| 
복제된 상태 시스템(RSM)
 a| 
S3 플랫폼 서비스 요청이 해당 엔드포인트로 전송되도록 합니다.

데이터 전용 스토리지 노드는 이 서비스를 호스팅하지 않습니다.



 a| 
서버 상태 모니터(SSM)
 a| 
운영 체제 및 기본 하드웨어를 모니터링합니다.

|===