---
permalink: primer/what-gateway-node-is.html 
sidebar: sidebar 
keywords: gateway nodes, api gateway 
summary: 게이트웨이 노드는 S3 클라이언트 애플리케이션이 StorageGRID에 연결하는 데 사용할 수 있는 전용 로드 밸런싱 인터페이스를 제공합니다. 로드 밸런싱은 여러 스토리지 노드에 워크로드를 분산하여 속도와 연결 용량을 극대화합니다. 게이트웨이 노드는 선택 사항입니다. 
---
= 게이트웨이 노드란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
게이트웨이 노드는 S3 클라이언트 애플리케이션이 StorageGRID에 연결하는 데 사용할 수 있는 전용 로드 밸런싱 인터페이스를 제공합니다. 로드 밸런싱은 여러 스토리지 노드에 워크로드를 분산하여 속도와 연결 용량을 극대화합니다. 게이트웨이 노드는 선택 사항입니다.

StorageGRID 로드 밸런서 서비스는 모든 관리 노드 및 모든 게이트웨이 노드에 제공됩니다. 클라이언트 요청에 대한 TLS(Transport Layer Security) 종료를 수행하고 요청을 검사하며 스토리지 노드에 대한 새로운 보안 연결을 설정합니다. 로드 밸런서 서비스는 클라이언트를 최적의 스토리지 노드로 원활하게 전달하므로 노드 장애나 전체 사이트에 장애가 발생하지 않습니다.

게이트웨이 및 관리 노드의 부하 분산 서비스에 액세스하는 데 들어오는 클라이언트 및 나가는 클라이언트 요청에 사용할 포트 및 네트워크 프로토콜(HTTPS 또는 HTTP)을 정의하도록 하나 이상의 부하 분산 단말 장치를 구성합니다. 또한 로드 밸런서 엔드포인트는 클라이언트 유형(S3), 바인딩 모드 및 허용되는 테넌트 또는 차단된 테넌트 목록을 정의합니다. 을 link:../admin/managing-load-balancing.html["로드 균형 조정에 대한 고려 사항"]참조하십시오.

필요에 따라 여러 게이트웨이 노드와 관리 노드의 네트워크 인터페이스를 고가용성(HA) 그룹으로 그룹화할 수 있습니다. HA 그룹의 활성 인터페이스에 장애가 발생하면 백업 인터페이스에서 클라이언트 애플리케이션 워크로드를 관리할 수 있습니다. 을 link:../admin/managing-high-availability-groups.html["고가용성(HA) 그룹 관리"]참조하십시오.



== 게이트웨이 노드에 대한 기본 서비스

다음 표에서는 게이트웨이 노드의 기본 서비스를 보여 줍니다. 그러나 이 테이블에는 모든 노드 서비스가 나열되지는 않습니다.

[cols="1a,2a"]
|===
| 서비스 | 키 기능 


 a| 
캐시 서비스
 a| 
개체 콘텐츠의 로컬 캐시를 관리합니다.



 a| 
고가용성
 a| 
관리 노드 및 게이트웨이 노드 그룹의 고가용성 가상 IP 주소를 관리합니다.

* 참고: * 이 서비스는 관리 노드에서도 찾을 수 있습니다.



 a| 
로드 밸런서
 a| 
클라이언트에서 스토리지 노드까지 S3 트래픽의 계층 7 로드 밸런싱을 제공합니다. 이것은 권장되는 로드 밸런싱 메커니즘입니다.

* 참고: * 이 서비스는 관리 노드에서도 찾을 수 있습니다.



 a| 
서버 상태 모니터(SSM)
 a| 
운영 체제 및 기본 하드웨어를 모니터링합니다.

|===