---
permalink: primer/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 관리 노드는 시스템 구성, 모니터링 및 로깅과 같은 관리 서비스를 제공합니다. 관리 노드를 사용하여 S3 클라이언트 트래픽의 로드 밸런싱을 수행할 수도 있습니다. 각 그리드에는 1개의 기본 관리 노드가 있어야 하며 이중화를 위해 여러 개의 비기본 관리 노드가 있을 수 있습니다. 
---
= 관리 노드란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 노드는 시스템 구성, 모니터링 및 로깅과 같은 관리 서비스를 제공합니다. 관리 노드를 사용하여 S3 클라이언트 트래픽의 로드 밸런싱을 수행할 수도 있습니다. 각 그리드에는 1개의 기본 관리 노드가 있어야 하며 이중화를 위해 여러 개의 비기본 관리 노드가 있을 수 있습니다.



== 운영 관리 노드와 비운영 관리 노드 간의 차이점

Grid Manager 또는 Tenant Manager에 로그인하면 관리 노드에 연결됩니다.  모든 관리 노드에 연결할 수 있으며, 각 관리 노드에는 StorageGRID 시스템의 유사한 보기가 표시됩니다.  하지만 기본 관리 노드는 기본이 아닌 관리 노드보다 더 많은 기능을 제공합니다.  예를 들어, 대부분의 유지 관리 절차는 기본 관리 노드에서 수행해야 합니다.

이 표에는 기본 및 비기본 관리 노드의 기능이 요약되어 있습니다.

[cols="2a,1a,1a"]
|===
| 제공합니다 | 기본 관리자 노드 | 운영 관리자 노드가 아닌 노드 


 a| 
서비스가 포함됩니다<<ams,AMS>>
 a| 
예
 a| 
예



 a| 
서비스가 포함됩니다<<cmn,CMN>>
 a| 
예
 a| 
아니요



 a| 
서비스가 포함됩니다<<nms,NMS>>
 a| 
예
 a| 
예



 a| 
서비스가 포함됩니다<<prometheus,프로메테우스>>
 a| 
예
 a| 
예



 a| 
서비스가 포함됩니다<<ssm,SSM>>
 a| 
예
 a| 
예



 a| 
<<load-balancer,로드 밸런서>>및 <<high-availability,고가용성>> 서비스가 포함됩니다
 a| 
예
 a| 
예



 a| 
(mgmt-API) 지원<<mgmt-api,관리 애플리케이션 프로그램 인터페이스>>
 a| 
예
 a| 
예



 a| 
IP 주소 변경 및 NTP 서버 업데이트와 같은 모든 네트워크 관련 유지 관리 작업에 사용할 수 있습니다
 a| 
예
 a| 
아니요



 a| 
복구 패키지를 다운로드할 수 있습니다
 a| 
예
 a| 
예



 a| 
스토리지 노드 확장 후 EC 재조정을 수행할 수 있습니다
 a| 
예
 a| 
아니요



 a| 
볼륨 복원 절차에 사용할 수 있습니다
 a| 
예
 a| 
예



 a| 
하나 이상의 노드에서 로그 파일과 시스템 데이터를 수집할 수 있습니다
 a| 
예
 a| 
예



 a| 
스토리지, 게이트웨이 및 기본이 아닌 관리 노드를 복구할 수 있습니다.
 a| 
예
 a| 
예



 a| 
기본 관리 노드를 복구할 수 있습니다.
 a| 
예
 a| 
아니요



 a| 
알림, AutoSupport 패키지 및 SNMP 트랩을 보내고 알림을 보냅니다
 a| 
예. 의 역할을 <<preferred-sender,기본 보낸 사람>>합니다.
 a| 
예. 대기 발신자의 역할을 합니다.

|===


== [[preferred-sender]] 기본 보낸 사람 관리자 노드

StorageGRID 구축에 여러 관리자 노드가 포함된 경우 기본 관리자 노드가 경고 알림, AutoSupport 패키지, SNMP 트랩 및 알림을 보내는 기본 보낸 사람이 됩니다.

일반적인 시스템 작동에서는 선호하는 발신자만 알림을 보냅니다.  하지만 다른 모든 관리 노드는 선호하는 발신자를 모니터링합니다.  문제가 감지되면 다른 관리 노드가 대기 발신자 역할을 합니다.

다음과 같은 경우 여러 개의 알림이 전송될 수 있습니다.

* 관리 노드가 서로 "표시"되는 경우 기본 설정 보낸 사람과 대기 보낸 사람 모두 알림 보내기를 시도하며 여러 개의 알림 복사본이 수신될 수 있습니다.
* 대기 발신자가 기본 발신자에게서 문제를 감지하고 알림을 보내기 시작하면 기본 발신자가 알림을 보낼 수 있는 기능을 회복할 수 있습니다.  이런 경우 알림이 중복해서 전송될 수 있습니다.  대기 발신자는 기본 발신자에서 더 이상 오류를 감지하지 못하면 알림 전송을 중단합니다.
+

NOTE: AutoSupport 패키지를 테스트할 때 모든 관리 노드가 테스트를 보냅니다. 알림 알림을 테스트할 때는 모든 관리 노드에 로그인하여 연결을 확인해야 합니다.





== 관리 노드에 대한 기본 서비스

다음 표에서는 관리 노드의 기본 서비스를 보여 줍니다. 그러나 이 테이블에는 모든 노드 서비스가 나열되지는 않습니다.

[cols="1a,2a"]
|===
| 서비스 | 키 기능 


 a| 
[[AMS]] 감사 관리 시스템(AMS)
 a| 
시스템 활동 및 이벤트를 추적합니다.



 a| 
[[CMN]] 구성 관리 노드(CMN)
 a| 
시스템 전체 구성을 관리합니다.



 a| 
[[high-availability]] 고가용성
 a| 
관리 노드 및 게이트웨이 노드 그룹의 고가용성 가상 IP 주소를 관리합니다.

* 참고: * 이 서비스는 게이트웨이 노드에서도 찾을 수 있습니다.



 a| 
[[로드 밸런서]] 로드 밸런서
 a| 
클라이언트에서 스토리지 노드로의 S3 트래픽의 로드 밸런싱을 제공합니다.

* 참고: * 이 서비스는 게이트웨이 노드에서도 찾을 수 있습니다.



 a| 
[[mgmt-API]] 관리 응용 프로그램 인터페이스(mgmt-API)
 a| 
Grid Management API 및 Tenant Management API의 요청을 처리합니다.



 a| 
[[NMS]] 네트워크 관리 시스템(NMS)
 a| 
그리드 관리자를 위한 기능을 제공합니다.



 a| 
[[Prometheus]] 프로메테우스
 a| 
모든 노드의 서비스에서 시계열 메트릭을 수집 및 저장합니다.



 a| 
[[SSM]] 서버 상태 모니터(SSM)
 a| 
운영 체제 및 기본 하드웨어를 모니터링합니다.

|===