---
permalink: expand/adding-storage-capacity-for-replicated-objects.html 
sidebar: sidebar 
keywords: replication, replicated, copies, capacity, storage nodes, expand, expansion 
summary: '배포에 대한 ILM(정보 수명 주기 관리) 정책에 개체의 복제된 복사본을 만드는 규칙이 포함된 경우 추가할 스토리지 양과 새 스토리지 볼륨 또는 스토리지 노드를 추가할 위치를 고려해야 합니다.' 
---
= 복제된 객체에 대한 스토리지 용량을 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
배포에 대한 ILM(정보 수명 주기 관리) 정책에 개체의 복제된 복사본을 만드는 규칙이 포함된 경우 추가할 스토리지 양과 새 스토리지 볼륨 또는 스토리지 노드를 추가할 위치를 고려해야 합니다.

추가 스토리지 추가 위치에 대한 지침은 복제된 복사본을 생성하는 ILM 규칙을 검토하십시오. ILM 규칙이 두 개 이상의 오브젝트 복사본을 만드는 경우 오브젝트 복사본이 만들어지는 각 위치에 스토리지를 추가할 계획입니다. 간단한 예로, 2개 사이트 그리드와 각 사이트에 개체 복사본을 만드는 ILM 규칙이 있는 경우 각 사이트에 연결하여 그리드의 전체 개체 용량을 늘려야 합니다link:../expand/adding-storage-volumes-to-storage-nodes.html["스토리지 추가"]. 개체 복제에 대한 자세한 내용은 을 참조하십시오link:../ilm/what-replication-is.html["복제란 무엇입니까"].

성능을 위해 사이트 간에 스토리지 용량과 컴퓨팅 성능을 균형 있게 유지해야 합니다. 따라서 이 예에서는 각 사이트에 동일한 수의 스토리지 노드를 추가하거나 각 사이트에 추가 스토리지 볼륨을 추가해야 합니다.

버킷 이름 등의 기준에 따라 오브젝트를 다른 위치에 배치하는 규칙 또는 시간에 따라 오브젝트 위치를 변경하는 규칙을 포함하는 보다 복잡한 ILM 정책을 가진 경우 확장에 필요한 스토리지의 위치 분석은 비슷하지만 더 복잡합니다.

전체 스토리지 용량이 얼마나 빨리 소비되는지를 차트를 통해 확장에 추가할 스토리지의 양과 추가 스토리지 공간이 언제 필요한지 파악할 수 있습니다. 그리드 관리자를 사용하여 link:../monitor/monitoring-storage-capacity.html["스토리지 용량을 모니터링하고 차트로 작성합니다"]수행할 수 있습니다.

확장 시기를 계획할 때, 추가 저장 공간을 조달하고 설치하는 데 얼마나 걸릴지도 고려해야 합니다.  확장 계획을 간소화하려면 기존 스토리지 노드의 용량이 70%에 도달하면 스토리지 노드를 추가하는 것을 고려하세요.
