---
permalink: expand/adding-storage-capacity-for-erasure-coded-objects.html 
sidebar: sidebar 
keywords: erasure coding, capacity, storage nodes, ec, expand, expansion, StorageGRID 
summary: ILM 정책에 삭제 코딩 복사본을 만드는 규칙이 포함된 경우 새 스토리지를 추가할 위치와 새 스토리지를 추가할 시기를 계획해야 합니다. 추가하는 스토리지의 양과 추가 시기는 그리드의 사용 가능한 스토리지 용량에 영향을 줄 수 있습니다. 
---
= StorageGRID 에서 소거 부호화(EC) 데이터에 대한 확장 계획
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM 정책에 삭제 코딩 복사본을 만드는 규칙이 포함된 경우 새 스토리지를 추가할 위치와 새 스토리지를 추가할 시기를 계획해야 합니다. 추가하는 스토리지의 양과 추가 시점에 따라 그리드의 가용 스토리지 용량이 영향을 받을 수 있습니다.

스토리지 확장을 계획하는 첫 번째 단계는 삭제 코딩 오브젝트를 생성하는 ILM 정책의 규칙을 검토하는 것입니다. StorageGRID는 모든 삭제 코딩 오브젝트에 대해 _k+m_fagment를 생성하고 각 조각을 다른 스토리지 노드에 저장하기 때문에 확장 후 새로운 삭제 코딩 데이터를 위한 공간이 최소한 _k+m_개 이상 있어야 합니다. 삭제 코딩 프로파일이 사이트 손실 방지 기능을 제공하는 경우 각 사이트에 스토리지를 추가해야 합니다. 삭제 코딩 프로필에 대한 자세한 내용은 을 link:../ilm/what-erasure-coding-schemes-are.html["삭제 코딩 체계란 무엇입니까"]참조하십시오.

추가해야 하는 노드 수도 확장을 수행할 때 기존 노드의 전체 수에 따라 달라집니다.



== 삭제 코딩 오브젝트를 위한 스토리지 용량을 추가하는 일반 권장 사항입니다

자세한 계산을 방지하려면 기존 스토리지 노드가 70% 용량에 도달할 때 사이트당 두 개의 스토리지 노드를 추가할 수 있습니다.

이 일반적인 권장사항은 단일 사이트 그리드 및 삭제 코딩이 사이트 손실을 보호하는 그리드에 대한 광범위한 삭제 코딩 체계에서 합리적인 결과를 제공합니다.

이러한 권장 사항을 유발한 요인을 더 잘 이해하거나 사이트에 대한 보다 정확한 계획을 개발하려면 을(를) 참조하십시오link:considerations-for-rebalancing-erasure-coded-data.html["삭제 코딩 데이터의 재조정에 대한 고려사항"]. 귀사의 상황에 최적화된 맞춤형 권장사항을 보려면 NetApp 프로페셔널 서비스 컨설턴트에게 문의하십시오.
