---
permalink: expand/adding-new-site.html 
sidebar: sidebar 
keywords: expand, expansion, new site, add site, guidelines 
summary: 새 사이트를 추가하여 StorageGRID 시스템을 확장할 수 있습니다. 
---
= 새 사이트를 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 사이트를 추가하여 StorageGRID 시스템을 확장할 수 있습니다.



== 사이트 추가 지침

사이트를 추가하기 전에 다음 요구 사항 및 제한 사항을 검토하십시오.

* 확장 작업당 하나의 사이트만 추가할 수 있습니다.
* 동일한 확장의 일부로 기존 사이트에 그리드 노드를 추가할 수 없습니다.
* 모든 사이트에는 3개 이상의 스토리지 노드가 포함되어야 합니다.
* 새 사이트를 추가해도 저장할 수 있는 개체 수는 자동으로 늘어지지 않습니다. 그리드의 총 오브젝트 용량은 사용 가능한 스토리지 양, ILM 정책 및 각 사이트의 메타데이터 용량에 따라 달라집니다.
* 새 사이트를 사이징할 때는 충분한 메타데이터 용량이 포함되어야 합니다.
+
StorageGRID는 모든 사이트에 모든 오브젝트 메타데이터의 복사본을 보관합니다. 새 사이트를 추가할 때는 기존 오브젝트 메타데이터에 충분한 메타데이터 용량과 성장을 위한 충분한 메타데이터 용량이 포함되어야 합니다.

+
자세한 내용은 다음을 참조하십시오.

+
** link:../admin/managing-object-metadata-storage.html["오브젝트 메타데이터 스토리지 관리"]
** link:../monitor/monitoring-storage-capacity.html#monitor-object-metadata-capacity-for-each-storage-node["각 스토리지 노드의 객체 메타데이터 용량을 모니터링합니다"]


* 사이트 간에 사용 가능한 네트워크 대역폭과 네트워크 대기 시간 수준을 고려해야 합니다. 모든 오브젝트가 수집된 사이트에만 저장되어 있더라도 사이트 간에 메타데이터 업데이트가 지속적으로 복제됩니다.
* 확장 중에 StorageGRID 시스템이 계속 작동하므로 확장 절차를 시작하기 전에 ILM 규칙을 검토해야 합니다. 확장 절차가 완료될 때까지 오브젝트 복사본이 새 사이트에 저장되지 않도록 해야 합니다.
+
예를 들어 확장을 시작하기 전에 규칙에 기본 스토리지 풀(모든 스토리지 노드)이 사용되고 있는지 확인합니다. 이러한 경우 기존 스토리지 노드가 포함된 새 스토리지 풀을 생성하고 ILM 규칙을 업데이트하여 새 스토리지 풀을 사용해야 합니다. 그렇지 않으면 해당 사이트의 첫 번째 노드가 활성 상태가 되는 즉시 새 사이트에 개체가 복사됩니다.

+
새 사이트를 추가할 때 ILM을 변경하는 방법에 대한 자세한 내용은 를 참조하십시오link:../ilm/example-6-changing-ilm-policy.html["ILM 정책 변경 예"].


