---
permalink: expand/copying-admin-node-database.html 
sidebar: sidebar 
keywords: copy Admin Node database, alert history, Admin Node expansion 
summary: 확장 절차를 통해 관리 노드를 추가할 때 필요에 따라 기본 관리 노드에서 새 관리 노드로 데이터베이스를 복사할 수 있습니다. 데이터베이스를 복사하면 속성, 알림 및 알림에 대한 기간별 정보를 유지할 수 있습니다. 
---
= 관리 노드 데이터베이스를 복사합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
확장 절차를 통해 관리 노드를 추가할 때 필요에 따라 기본 관리 노드에서 새 관리 노드로 데이터베이스를 복사할 수 있습니다. 데이터베이스를 복사하면 속성, 알림 및 알림에 대한 기간별 정보를 유지할 수 있습니다.

.시작하기 전에
* 관리자 노드를 추가하는 데 필요한 확장 단계를 완료했습니다.
*  `Passwords.txt`파일이 있습니다.
* 프로비저닝 암호가 있습니다.


.이 작업에 대해
StorageGRID 소프트웨어 활성화 프로세스는 확장 관리 노드에서 NMS 서비스에 대한 빈 데이터베이스를 생성합니다. 확장 관리 노드에서 NMS 서비스가 시작되면 현재 시스템에 포함되어 있거나 나중에 추가된 서버 및 서비스에 대한 정보가 기록됩니다. 이 관리 노드 데이터베이스에는 다음 정보가 포함되어 있습니다.

* 알림 기록
* 노드 페이지의 레거시 스타일 차트에 사용되는 내역 특성 데이터입니다


노드 간에 관리 노드 데이터베이스가 일관성을 유지하도록 기본 관리 노드에서 확장 관리 노드로 데이터베이스를 복사할 수 있습니다.


NOTE: 기본 관리 노드(__source Admin Node_)에서 확장 관리 노드로 데이터베이스를 복사하는 데 최대 몇 시간이 걸릴 수 있습니다. 이 기간 동안 그리드 관리자에 액세스할 수 없습니다.

데이터베이스를 복사하기 전에 기본 관리 노드와 확장 관리 노드 모두에서 MI 서비스 및 관리 API 서비스를 중지하려면 다음 단계를 사용합니다.

.단계
. 기본 관리 노드에서 다음 단계를 완료합니다.
+
.. 관리자 노드에 로그인합니다.
+
... 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
... 다음 명령을 입력하여 루트로 전환합니다. `su -`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.


.. 다음 명령을 실행합니다. `recover-access-points`
.. 프로비저닝 암호를 입력합니다.
.. MI 서비스를 중지합니다. `service mi stop`
.. 관리 응용 프로그램 인터페이스(mgmt-API) 서비스를 중지합니다. `service mgmt-api stop`


. 확장 관리 노드에서 다음 단계를 완료합니다.
+
.. 확장 관리 노드에 로그인합니다.
+
... 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
... 다음 명령을 입력하여 루트로 전환합니다. `su -`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.


.. MI 서비스를 중지합니다. `service mi stop`
.. mgmt-API 서비스 중지: `service mgmt-api stop`
.. SSH 에이전트에 SSH 개인 키를 추가합니다. 다음을 입력합니다.``ssh-add``
.. 파일에 나열된 SSH 액세스 암호를 `Passwords.txt` 입력합니다.
.. 소스 관리자 노드에서 확장 관리자 노드로 데이터베이스 복사: `/usr/local/mi/bin/mi-clone-db.sh _Source_Admin_Node_IP_`
.. 메시지가 표시되면 확장 관리 노드의 MI 데이터베이스를 덮어쓸지 확인합니다.
+
데이터베이스와 해당 내역 데이터는 확장 관리 노드에 복사됩니다. 복사 작업이 완료되면 스크립트가 확장 관리 노드를 시작합니다.

.. 다른 서버에 대한 암호 없는 액세스가 더 이상 필요하지 않으면 SSH 에이전트에서 개인 키를 제거합니다. 다음을 입력합니다.``ssh-add -D``


. 기본 관리자 노드에서 서비스를 다시 시작합니다. `service servermanager start`

