---
permalink: expand/copying-prometheus-metrics.html 
sidebar: sidebar 
keywords: prometheus, copy metrics, Admin Node expansion, StorageGRID 
summary: 새 관리 노드를 추가한 후 선택적으로 Prometheus에서 관리하는 기간별 메트릭을 운영 관리 노드에서 새 관리 노드로 복사할 수 있습니다. 메트릭을 복사하면 관리 노드 간에 기간별 메트릭이 일관되게 유지됩니다. 
---
= StorageGRID 의 새 관리 노드에 Prometheus 메트릭을 복사합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 관리 노드를 추가한 후 선택적으로 Prometheus에서 관리하는 기간별 메트릭을 운영 관리 노드에서 새 관리 노드로 복사할 수 있습니다. 메트릭을 복사하면 관리 노드 간에 기간별 메트릭이 일관되게 유지됩니다.

.시작하기 전에
* 새 관리 노드가 설치되고 실행 중입니다.
*  `Passwords.txt`파일이 있습니다.
* 프로비저닝 암호가 있습니다.


.이 작업에 대해
관리 노드를 추가하면 소프트웨어 설치 과정에서 새 Prometheus 데이터베이스가 생성됩니다. 기본 관리 노드(_source 관리 노드_)에서 새 관리 노드로 Prometheus 데이터베이스를 복사하여 노드 간에 기간별 메트릭을 일관되게 유지할 수 있습니다.


NOTE: Prometheus 데이터베이스를 복사하는 데 1시간 이상이 걸릴 수 있습니다. 소스 관리 노드에서 서비스가 중지되는 동안에는 일부 Grid Manager 기능을 사용할 수 없습니다.

.단계
. 소스 관리 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
.. 다음 명령을 입력하여 루트로 전환합니다. `su -`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.


. 소스 관리자 노드에서 Prometheus 서비스를 중지합니다. `service prometheus stop`
. 새 관리 노드에서 다음 단계를 완료합니다.
+
.. 새 관리자 노드에 로그인합니다.
+
... 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
... 다음 명령을 입력하여 루트로 전환합니다. `su -`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.


.. Prometheus 서비스를 중지합니다. `service prometheus stop`
.. SSH 에이전트에 SSH 개인 키를 추가합니다. 다음을 입력합니다.``ssh-add``
.. 파일에 나열된 SSH 액세스 암호를 `Passwords.txt` 입력합니다.
.. 소스 관리자 노드에서 새 관리자 노드로 Prometheus 데이터베이스를 복사합니다. `/usr/local/prometheus/bin/prometheus-clone-db.sh _Source_Admin_Node_IP_`
.. 메시지가 표시되면 * Enter * 를 눌러 새 관리 노드에서 새 Prometheus 데이터베이스를 파기할지 확인합니다.
+
원래 Prometheus 데이터베이스와 해당 기록 데이터가 새 관리 노드에 복사됩니다. 복사 작업이 완료되면 스크립트가 새 관리 노드를 시작합니다. 다음 상태가 나타납니다.

+
`Database cloned, starting services`

.. 다른 서버에 대한 암호 없는 액세스가 더 이상 필요하지 않으면 SSH 에이전트에서 개인 키를 제거합니다. 입력:
+
`ssh-add -D`



. 소스 관리 노드에서 Prometheus 서비스를 다시 시작합니다.
+
`service prometheus start`


