---
permalink: expand/deploying-new-grid-nodes.html 
sidebar: sidebar 
keywords: expansion, add nodes 
summary: 확장 시 새 그리드 노드를 구축하는 단계는 그리드를 처음 설치할 때 사용한 단계와 동일합니다. 확장을 수행하려면 먼저 모든 새 그리드 노드를 배포해야 합니다. 
---
= 새 그리드 노드를 배포합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
확장 시 새 그리드 노드를 구축하는 단계는 그리드를 처음 설치할 때 사용한 단계와 동일합니다. 확장을 수행하려면 먼저 모든 새 그리드 노드를 배포해야 합니다.

그리드를 확장할 때 추가하는 노드가 기존 노드 유형과 일치하지 않아도 됩니다. VMware 노드, Linux 컨테이너 기반 노드 또는 어플라이언스 노드를 추가할 수 있습니다.



== VMware: 그리드 노드를 구축합니다

확장에 추가할 각 VMware 노드에 대해 VMware vSphere에 가상 머신을 구축해야 합니다.

.단계
. link:../vmware/deploying-storagegrid-node-as-virtual-machine.html["새 노드를 가상 머신으로 구축합니다"] 하나 이상의 StorageGRID 네트워크에 연결합니다.
+
노드를 배포할 때 선택적으로 노드 포트를 재매핑하거나 CPU 또는 메모리 설정을 늘릴 수 있습니다.

. 새로운 VMware 노드를 모두 구축한 후,link:performing-expansion.html["확장 절차를 수행합니다"]




== Linux: 그리드 노드 배포

그리드 노드는 새 Linux 호스트 또는 기존 Linux 호스트에 배포할 수 있습니다. 그리드에 추가하려는 StorageGRID 노드의 CPU, RAM 및 스토리지 요구 사항을 지원하기 위해 추가 Linux 호스트가 필요한 경우 호스트를 처음 설치할 때와 동일한 방법으로 준비합니다. 그런 다음 설치 중에 그리드 노드를 구축하는 것과 동일한 방식으로 확장 노드를 배포합니다.

.시작하기 전에
* 사용 중인 Linux 버전에 대한 StorageGRID 설치 지침이 있으며 하드웨어 및 스토리지 요구 사항을 검토했습니다.
+
** link:../rhel/index.html["Red Hat Enterprise Linux에 StorageGRID를 설치합니다"]
** link:../ubuntu/index.html["Ubuntu 또는 Debian에 StorageGRID를 설치합니다"]


* 기존 호스트에 새 그리드 노드를 배포하려는 경우 기존 호스트에 추가 노드에 대한 CPU, RAM 및 스토리지 용량이 충분한지 확인했습니다.
* 장애 도메인을 최소화할 계획이 있습니다. 예를 들어, 단일 물리적 호스트에 모든 게이트웨이 노드를 배포해서는 안 됩니다.
+

CAUTION: 운영 구축 시 단일 물리적 호스트 또는 가상 호스트에서 스토리지 노드를 두 개 이상 실행하지 마십시오. 각 스토리지 노드에 대해 전용 호스트를 사용하면 격리된 장애 도메인이 제공됩니다.

* StorageGRID 노드가 NetApp ONTAP 시스템에서 할당된 스토리지를 사용하는 경우 볼륨에 FabricPool 계층화 정책이 활성화되어 있지 않은지 확인합니다. StorageGRID 노드와 함께 사용되는 볼륨에 대해 FabricPool 계층화를 사용하지 않도록 설정하면 문제 해결과 스토리지 작업이 간소화됩니다.


.단계
. 새 호스트를 추가하는 경우 StorageGRID 노드 구축을 위한 설치 지침에 액세스합니다.
. 새 호스트를 구축하려면 호스트 준비 지침을 따르십시오.
. 노드 구성 파일을 생성하고 StorageGRID 구성을 검증하려면 그리드 노드 배포 지침을 따르십시오.
. 새 Linux 호스트에 노드를 추가하는 경우 StorageGRID 호스트 서비스를 시작합니다.
. 기존 Linux 호스트에 노드를 추가하는 경우 StorageGRID 호스트 서비스 CLI를 사용하여 새 노드를 시작합니다.``sudo storagegrid node start [<node name\>]``


.작업을 마친 후
모든 새 그리드 노드를 배포한 후 link:performing-expansion.html["확장을 수행합니다"]수행할 수 있습니다.



== 어플라이언스: 스토리지, 게이트웨이 또는 비 기본 관리 노드 배포

어플라이언스 노드에 StorageGRID 소프트웨어를 설치하려면 어플라이언스에 포함된 StorageGRID 어플라이언스 설치 프로그램을 사용합니다. 확장 시 각 스토리지 어플라이언스는 단일 스토리지 노드로 작동하며, 각 서비스 어플라이언스는 단일 게이트웨이 노드 또는 비기본 관리 노드로 작동합니다. 모든 어플라이언스는 그리드 네트워크, 관리 네트워크 및 클라이언트 네트워크에 연결할 수 있습니다.

.시작하기 전에
* 이 제품은 랙 또는 캐비닛에 설치되었고 네트워크에 연결되어 있으며 전원이 켜져 있습니다.
*  https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/configuring-hardware.html["하드웨어를 설정합니다"^]단계를 완료했습니다.
+
어플라이언스 하드웨어 설정에는 StorageGRID 연결(네트워크 링크 및 IP 주소)을 구성하는 데 필요한 단계와 노드 암호화 활성화, RAID 모드 변경 및 네트워크 포트 재매핑을 위한 선택적 단계가 포함됩니다.

* StorageGRID 어플라이언스 설치 프로그램의 IP 구성 페이지에 나열된 모든 그리드 네트워크 서브넷은 기본 관리 노드의 그리드 네트워크 서브넷 목록에 정의되어 있습니다.
* 교체 어플라이언스의 StorageGRID 어플라이언스 설치 프로그램 펌웨어는 현재 그리드에서 실행 중인 StorageGRID 소프트웨어 버전과 호환됩니다. 버전이 호환되지 않는 경우 StorageGRID 어플라이언스 설치 프로그램 펌웨어를 업그레이드해야 합니다.
* 가 있는 서비스 랩톱이 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]있습니다.
* 어플라이언스의 컴퓨팅 컨트롤러에 할당된 IP 주소 중 하나를 알고 있습니다. 연결된 모든 StorageGRID 네트워크에 대해 IP 주소를 사용할 수 있습니다.


.이 작업에 대해
어플라이언스 노드에 StorageGRID를 설치하는 과정은 다음과 같습니다.

* 기본 관리 노드의 IP 주소와 어플라이언스 노드의 이름을 지정하거나 확인합니다.
* 설치를 시작하고 볼륨이 구성되고 소프트웨어가 설치될 때까지 기다립니다.
+
어플라이언스 설치 작업이 중간에 중지되면 설치가 일시 중지됩니다. 설치를 다시 시작하려면 그리드 관리자에 로그인하고 모든 그리드 노드를 승인하고 StorageGRID 설치 프로세스를 완료합니다.

+

NOTE: 한 번에 여러 어플라이언스 노드를 배포해야 하는 경우 어플라이언스 설치 스크립트를 사용하여 설치 프로세스를 자동화할 수 `configure-sga.py` 있습니다.



.단계
. 브라우저를 열고 어플라이언스의 컴퓨팅 컨트롤러에 대한 IP 주소 중 하나를 입력합니다.
+
`https://_Controller_IP_:8443`

+
StorageGRID 어플라이언스 설치 관리자 홈 페이지가 나타납니다.

. Primary Admin Node* 연결 섹션에서 기본 관리 노드의 IP 주소를 지정해야 하는지 여부를 확인합니다.
+
이전에 이 데이터 센터에 다른 노드를 설치한 경우 StorageGRID 어플라이언스 설치 관리자는 기본 관리 노드 또는 admin_IP가 구성된 다른 그리드 노드가 동일한 서브넷에 있다고 가정하여 이 IP 주소를 자동으로 검색할 수 있습니다.

. 이 IP 주소가 표시되지 않거나 변경해야 하는 경우 주소를 지정합니다.
+
[cols="1a,2a"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
수동 IP 입력
 a| 
.. 관리자 노드 검색 활성화 * 확인란의 선택을 취소합니다.
.. IP 주소를 수동으로 입력합니다.
.. 저장 * 을 클릭합니다.
.. 새 IP 주소가 준비될 때까지 연결 상태를 기다립니다.




 a| 
연결된 모든 운영 관리 노드의 자동 검색
 a| 
.. 관리자 노드 검색 활성화 * 확인란을 선택합니다.
.. 검색된 IP 주소 목록이 표시될 때까지 기다립니다.
.. 이 어플라이언스 스토리지 노드를 구축할 그리드의 기본 관리 노드를 선택합니다.
.. 저장 * 을 클릭합니다.
.. 새 IP 주소가 준비될 때까지 연결 상태를 기다립니다.


|===
. 노드 이름 * 필드에 이 어플라이언스 노드에 사용할 이름을 입력하고 * 저장 * 을 선택합니다.
+
노드 이름은 StorageGRID 시스템의 이 어플라이언스 노드에 할당됩니다. 그리드 관리자의 노드 페이지(개요 탭)에 표시됩니다. 필요한 경우 노드를 승인할 때 이름을 변경할 수 있습니다.

. Installation * 섹션에서 현재 상태가 "기본 Admin Node_admin_IP_로 _node name_into GRID 설치를 시작할 준비가 되었습니다"이고 * 설치 시작 * 버튼이 활성화되어 있는지 확인합니다.
+
설치 시작 * 버튼이 활성화되지 않은 경우 네트워크 구성 또는 포트 설정을 변경해야 할 수 있습니다. 자세한 내용은 제품의 유지보수 지침을 참조하십시오.

. StorageGRID 어플라이언스 설치 관리자 홈 페이지에서 * 설치 시작 * 을 선택합니다.
+
현재 상태가 "Installation is in progress(설치 진행 중)"로 변경되고 Monitor Installation(모니터 설치) 페이지가 표시됩니다.

. 확장에 여러 어플라이언스 노드가 포함된 경우 각 어플라이언스에 대해 이전 단계를 반복합니다.
+

NOTE: 여러 어플라이언스 스토리지 노드를 한 번에 배포해야 하는 경우 configure-sga.py 어플라이언스 설치 스크립트를 사용하여 설치 프로세스를 자동화할 수 있습니다.

. 모니터 설치 페이지에 수동으로 액세스해야 하는 경우 메뉴 모음에서 * 모니터 설치 * 를 선택합니다.
+
Monitor Installation(모니터 설치) 페이지에 설치 진행률이 표시됩니다.

+
파란색 상태 표시줄은 현재 진행 중인 작업을 나타냅니다. 녹색 상태 표시줄은 성공적으로 완료된 작업을 나타냅니다.

+

NOTE: 설치 프로그램은 이전 설치에서 완료된 작업이 다시 실행되지 않도록 합니다. 설치를 다시 실행하는 경우 다시 실행할 필요가 없는 작업은 녹색 상태 표시줄과 "건너뜀"으로 표시됩니다.

. 처음 두 설치 단계의 진행 상황을 검토합니다.
+
* 1. 어플라이언스 구성 *

+
이 단계에서 다음 프로세스 중 하나가 발생합니다.

+
** 스토리지 어플라이언스의 경우 설치 프로그램이 스토리지 컨트롤러에 연결하고, 기존 구성을 지우고, SANtricity OS와 통신하여 볼륨을 구성하고, 호스트 설정을 구성합니다.
** 서비스 어플라이언스의 경우 설치 프로그램이 컴퓨팅 컨트롤러의 드라이브에서 기존 구성을 지우고 호스트 설정을 구성합니다.
+
* 2. OS * 를 설치합니다

+
이 단계에서 설치 프로그램은 StorageGRID의 기본 운영 체제 이미지를 어플라이언스에 복사합니다.



. 그리드 관리자를 사용하여 노드를 승인하라는 메시지가 콘솔 창에 나타날 때까지 설치 진행 상태를 계속 모니터링합니다.
+

NOTE: 이 확장에서 추가한 모든 노드가 승인을 받을 준비가 될 때까지 기다린 다음 그리드 관리자로 이동하여 노드를 승인합니다.


