---
permalink: expand/guidelines-for-adding-object-capacity.html 
sidebar: sidebar 
keywords: adding storage capacity, guidelines, storage volumes, expansion 
summary: '기존 스토리지 노드에 스토리지 볼륨을 추가하거나 기존 사이트에 새 스토리지 노드를 추가하여 StorageGRID 시스템의 오브젝트 스토리지 용량을 확장할 수 있습니다. ILM(정보 수명 주기 관리) 정책의 요구 사항을 충족하는 방법으로 스토리지 용량을 추가해야 합니다.' 
---
= 오브젝트 용량 추가 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 스토리지 노드에 스토리지 볼륨을 추가하거나 기존 사이트에 새 스토리지 노드를 추가하여 StorageGRID 시스템의 오브젝트 스토리지 용량을 확장할 수 있습니다. ILM(정보 수명 주기 관리) 정책의 요구 사항을 충족하는 방법으로 스토리지 용량을 추가해야 합니다.



== 스토리지 볼륨 추가 지침

기존 스토리지 노드에 스토리지 볼륨을 추가하기 전에 다음 지침 및 제한 사항을 검토하십시오.

* 현재 ILM 규칙을 검토하여 또는 에 사용할 수 있는 스토리지를 증가시킬 link:../ilm/what-replication-is.html["복제된 개체"]위치 및 시기를 link:../expand/adding-storage-volumes-to-storage-nodes.html["스토리지 볼륨을 추가합니다"]link:../ilm/what-erasure-coding-schemes-are.html["삭제 코딩 오브젝트"]결정해야 합니다.
* 오브젝트 메타데이터는 볼륨 0에만 저장되기 때문에 스토리지 볼륨을 추가하여 시스템의 메타데이터 용량을 늘릴 수 없습니다.
* 각 소프트웨어 기반 스토리지 노드는 최대 16개의 스토리지 볼륨을 지원할 수 있습니다. 그 이상으로 용량을 추가해야 하는 경우 새 스토리지 노드를 추가해야 합니다.
* 각 SG6060 어플라이언스에 하나 또는 두 개의 확장 쉘프를 추가할 수 있습니다. 각 확장 쉘프에는 16개의 스토리지 볼륨이 추가됩니다. 두 확장 셸프가 모두 설치된 SG6060은 총 48개의 스토리지 볼륨을 지원할 수 있습니다.
* 각 SG6160 어플라이언스에 하나 또는 두 개의 확장 쉘프를 추가할 수 있습니다. 각 확장 쉘프에는 60개의 스토리지 볼륨이 추가됩니다. 두 확장 셸프가 모두 설치된 SG6160은 총 180개의 스토리지 볼륨을 지원할 수 있습니다.
* 스토리지 볼륨을 다른 스토리지 어플라이언스에 추가할 수 없습니다.
* 기존 스토리지 볼륨의 크기는 늘릴 수 없습니다.
* 시스템 업그레이드, 복구 작업 또는 다른 확장을 수행하는 동시에 스토리지 볼륨을 스토리지 노드에 추가할 수 없습니다.


스토리지 볼륨을 추가하고 ILM 정책을 충족하기 위해 확장해야 하는 스토리지 노드를 결정한 후에는 사용 중인 스토리지 노드 유형에 대한 지침을 따르십시오.

* 하나 또는 두 개의 확장 쉘프를 SG6060 스토리지 어플라이언스에 추가하려면 로 이동합니다 https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/adding-expansion-shelf-to-deployed-sg6060.html["배포된 SG6060에 확장 쉘프를 추가합니다"^].
* 하나 또는 두 개의 확장 쉘프를 SG6160 스토리지 어플라이언스에 추가하려면 로 이동합니다 https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/adding-expansion-shelf-to-deployed-sg6160.html["배포된 SG6160에 확장 쉘프를 추가합니다"^]
* 소프트웨어 기반 노드의 경우 의 지침을 link:adding-storage-volumes-to-storage-nodes.html["스토리지 노드에 스토리지 볼륨을 추가하는 중입니다"]따릅니다.




== 스토리지 노드 추가 지침

기존 사이트에 스토리지 노드를 추가하기 전에 다음 지침 및 제한 사항을 검토하십시오.

* 현재 ILM 규칙을 검토하여 또는 에 사용할 수 있는 스토리지를 늘리기 위해 스토리지 노드를 추가할 위치와 시기를 결정해야 link:../ilm/what-replication-is.html["복제된 개체"]link:../ilm/what-erasure-coding-schemes-are.html["삭제 코딩 오브젝트"]합니다.
* 단일 확장 절차에서 스토리지 노드를 10개 이상 추가할 수 없습니다.
* 단일 확장 절차에서 여러 사이트에 스토리지 노드를 추가할 수 있습니다.
* 단일 확장 절차에서 스토리지 노드 및 다른 유형의 노드를 추가할 수 있습니다.
* 확장 절차를 시작하기 전에 복구의 일부로 수행된 모든 데이터 복구 작업이 완료되었는지 확인해야 합니다. 을 link:../maintain/checking-data-repair-jobs.html["데이터 복구 작업을 확인합니다"]참조하십시오.
* 확장을 수행하기 전이나 후에 스토리지 노드를 제거해야 하는 경우 단일 서비스 해제 노드 절차에서 10개 이상의 스토리지 노드를 서비스 해제할 수 없습니다.




== 스토리지 노드의 ADC 서비스에 대한 지침

확장을 구성할 때 각 새 스토리지 노드에 관리 도메인 컨트롤러(ADC) 서비스를 포함할지 여부를 선택해야 합니다. ADC 서비스는 그리드 서비스의 위치 및 가용성을 추적합니다.

* 할 수 link:../maintain/move-adc-service.html["ADC 서비스를 한 스토리지 노드에서 동일한 사이트의 다른 스토리지 노드로 이동합니다"]있습니다.
* StorageGRID 시스템은 각 사이트에서 그리고 항상 을 사용할 수 있어야 link:../maintain/understanding-adc-service-quorum.html["ADC 서비스 쿼럼입니다"]합니다.
* 각 사이트에 적어도 3개의 스토리지 노드가 ADC 서비스를 포함해야 합니다.
* ADC 서비스를 모든 스토리지 노드에 추가하는 것은 권장되지 않습니다. 너무 많은 ADC 서비스를 포함시키면 노드 간 통신 증가로 인해 속도가 느려지게 될 수 있습니다.
* 단일 그리드에는 ADC 서비스가 있는 48개 이상의 스토리지 노드가 있을 수 없습니다. 이는 각 사이트에 3개의 ADC 서비스를 제공하는 16개 사이트와 동일합니다.
* 일반적으로 새 노드에 대해 * ADC 서비스 * 설정을 선택할 때 * 자동 * 을 선택해야 합니다. 새 노드가 ADC 서비스를 포함하는 다른 스토리지 노드를 교체할 경우에만 * 예 * 를 선택합니다. ADC 서비스가 너무 적은 경우 스토리지 노드를 해제할 수 없으므로 * Yes * 를 선택하면 이전 서비스가 제거되기 전에 새 ADC 서비스를 사용할 수 있습니다.

