---
permalink: expand/updating-subnets-for-grid-network.html 
sidebar: sidebar 
keywords: expand, expansion, add subnets, Grid Network 
summary: 확장 시 그리드 노드 또는 새 사이트를 추가할 때 그리드 네트워크에 서브넷을 업데이트하거나 추가해야 할 수 있습니다. 
---
= 그리드 네트워크에 대한 서브넷을 업데이트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
확장 시 그리드 노드 또는 새 사이트를 추가할 때 그리드 네트워크에 서브넷을 업데이트하거나 추가해야 할 수 있습니다.

StorageGRID는 그리드 네트워크(eth0)의 그리드 노드 간에 통신하는 데 사용되는 네트워크 서브넷 목록을 유지합니다. 이러한 항목에는 StorageGRID 시스템의 각 사이트에서 그리드 네트워크에 사용되는 서브넷과 그리드 네트워크 게이트웨이를 통해 액세스되는 NTP, DNS, LDAP 또는 기타 외부 서버에 사용되는 서브넷이 포함됩니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:../admin/admin-group-permissions.html["유지 관리 또는 루트 액세스 권한"]있습니다.
* 프로비저닝 암호가 있습니다.
* 구성할 서브넷의 네트워크 주소(CIDR 표기법)가 있습니다.


.이 작업에 대해
새 노드의 그리드 네트워크 IP 주소가 이전에 사용되지 않은 서브넷에 있는 경우 확장을 시작하기 전에 그리드 네트워크 서브넷 목록에 새 서브넷을 추가해야 합니다. 그렇지 않으면 확장을 취소하고 새 서브넷을 추가한 다음 절차를 다시 시작해야 합니다.

.단계
. 유지보수 * > * 네트워크 * > * 그리드 네트워크 * 를 선택합니다.
. CIDR 표시법으로 새 서브넷을 추가하려면 * 다른 서브넷 추가 * 를 선택합니다.
+
예를 들어, 을 `10.96.104.0/22`입력합니다.

. 프로비저닝 암호를 입력하고 * Save * 를 선택합니다.
. 변경 사항이 적용될 때까지 기다린 다음 새 복구 패키지를 다운로드합니다.
+
.. 유지보수 * > * 시스템 * > * 복구 패키지 * 를 선택합니다.
.. Provisioning Passphrase * 를 입력합니다.
+

CAUTION: 복구 패키지 파일은 StorageGRID 시스템에서 데이터를 가져오는 데 사용할 수 있는 암호화 키와 암호가 포함되어 있으므로 보안을 유지해야 합니다. 또한 기본 관리 노드를 복구하는 데 사용됩니다.





지정한 서브넷은 StorageGRID 시스템에 대해 자동으로 구성됩니다.
