---
permalink: expand/vmware-adding-storage-volumes-to-storage-node.html 
sidebar: sidebar 
keywords: expand, expansion, storage node, add storage volumes, VMware 
summary: 스토리지 노드에 16개 미만의 스토리지 볼륨이 포함된 경우 VMware vSphere를 사용하여 볼륨을 추가하여 용량을 늘릴 수 있습니다. 
---
= VMware: 스토리지 노드에 스토리지 볼륨을 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드에 16개 미만의 스토리지 볼륨이 포함된 경우 VMware vSphere를 사용하여 볼륨을 추가하여 용량을 늘릴 수 있습니다.

.시작하기 전에
* VMware 배포용 StorageGRID 설치 지침을 액세스할 수 있습니다.
+
** link:../vmware/index.html["VMware에 StorageGRID를 설치합니다"]


*  `Passwords.txt`파일이 있습니다.
* 있습니다. link:../admin/admin-group-permissions.html["특정 액세스 권한"]



CAUTION: 소프트웨어 업그레이드, 복구 절차 또는 다른 확장 절차가 활성화되어 있는 동안에는 스토리지 노드를 스토리지 노드에 추가하지 마십시오.

.이 작업에 대해
스토리지 볼륨을 추가할 때 잠시 동안 스토리지 노드를 사용할 수 없습니다. 클라이언트 대상 그리드 서비스에 영향을 주지 않도록 한 번에 하나의 스토리지 노드에서 이 절차를 수행해야 합니다.

.단계
. 필요한 경우 새 스토리지 하드웨어를 설치하고 새 VMware 데이터 저장소를 생성합니다.
. 스토리지로 사용할 하나 이상의 하드 디스크를 가상 머신에 추가합니다(오브젝트 저장소).
+
.. VMware vSphere Client를 엽니다.
.. 가상 시스템 설정을 편집하여 하나 이상의 추가 하드 디스크를 추가합니다.


+
하드 디스크는 일반적으로 VMDK(Virtual Machine Disk)로 구성됩니다. VMDK는 일반적으로 더 많이 사용되며 관리가 더 쉽지만 RDM은 더 큰 개체 크기(예: 100MB 이상)를 사용하는 워크로드에 더 나은 성능을 제공할 수 있습니다. 가상 머신에 하드 디스크를 추가하는 방법에 대한 자세한 내용은 VMware vSphere 설명서를 참조하십시오.

. VMware vSphere Client에서 * Restart Guest OS * 옵션을 사용하거나 가상 머신에 대한 ssh 세션에 다음 명령을 입력하여 가상 머신을 다시 시작합니다.``sudo reboot``
+

NOTE: 가상 컴퓨터를 다시 시작하기 위해 * Power Off * 또는 * Reset * 을 사용하지 마십시오.

. 스토리지 노드에서 사용할 새 스토리지를 구성합니다.
+
.. 그리드 노드에 로그인합니다.
+
... 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
... 다음 명령을 입력하여 루트로 전환합니다. `su -`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다. 루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.


.. 새 스토리지 볼륨 구성:
+
`sudo add_rangedbs.rb`

+
이 스크립트는 새 스토리지 볼륨을 찾아 포맷하라는 메시지를 표시합니다.

.. y * 를 입력하여 서식을 적용합니다.
.. 이전에 포맷된 볼륨이 있는 경우 다시 포맷할지 여부를 결정합니다.
+
*** 다시 포맷하려면 * y * 를 입력합니다.
*** 포맷을 건너뛰려면 * n * 을 입력합니다.




+
 `setup_rangedbs.sh`스크립트가 자동으로 실행됩니다.

. 서비스가 올바르게 시작되는지 점검한다.
+
.. 서버에 있는 모든 서비스의 상태 목록을 봅니다.
+
`sudo storagegrid-status`

+
상태가 자동으로 업데이트됩니다.

.. 모든 서비스가 실행 중이거나 검증될 때까지 기다립니다.
.. 상태 화면을 종료합니다.
+
`Ctrl+C`



. 스토리지 노드가 온라인 상태인지 확인합니다.
+
.. 을 사용하여 그리드 관리자에 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]로그인합니다.
.. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다.
.. site_ * > *_Storage Node_ * > * LDR * > * Storage * 를 선택합니다.
.. Configuration * 탭을 선택한 다음 * Main * 탭을 선택합니다.
.. 스토리지 상태 - 원하는 * 드롭다운 목록이 읽기 전용 또는 오프라인으로 설정된 경우 * 온라인 * 을 선택합니다.
.. Apply Changes * 를 선택합니다.


. 새 오브젝트 저장소를 보려면 다음을 수행합니다.
+
.. 노드 * > *_site_ * > *_Storage Node_ * > * Storage * 를 선택합니다.
.. Object Stores * 표에서 세부 정보를 봅니다.




.결과
스토리지 노드의 확장된 용량을 사용하여 오브젝트 데이터를 저장할 수 있습니다.
