---
permalink: troubleshoot/investigating-potentially-lost-objects.html 
sidebar: sidebar 
keywords: lost objects, investigating, objects 
summary: *분실 가능성이 있는 물건* 경고가 발생하면 즉시 조사해야 합니다.  영향을 받은 객체에 대한 정보를 수집하고 기술 지원팀에 문의하세요. 
---
= 분실 가능성이 있는 물건을 조사하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
*분실 가능성이 있는 물건* 경고가 발생하면 즉시 조사해야 합니다.  영향을 받은 객체에 대한 정보를 수집하고 기술 지원팀에 문의하세요.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인해야 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]합니다.
* 있습니다. link:../admin/admin-group-permissions.html["특정 액세스 권한"]
* 파일이 있어야 `Passwords.txt` 합니다.


.이 작업에 대해
*잠재적으로 손실된 객체* 경고는 StorageGRID 에서 사용 가능한 정보에 따르면 그리드에 객체의 사본이 없음을 나타냅니다.  데이터가 영구적으로 손실되었을 수 있습니다.

손실된 개체 경고를 즉시 조사합니다. 추가 데이터 손실을 방지하기 위해 조치를 취해야 할 수 있습니다. 경우에 따라 프롬프트 작업을 수행하면 손실된 개체를 복원할 수 있습니다.


CAUTION: 10개 이상의 물건이 분실되었다고 보고된 경우, 기술 지원팀에 문의하세요.  이 절차를 직접 따르지 마세요.

.단계
. *노드*를 선택하세요.
. 스토리지 노드 * > * 오브젝트 * 를 선택합니다.
. 개체 수 표에 표시된 손실된 개체의 수를 검토합니다.
+
이 숫자는 그리드 노드가 전체 StorageGRID 시스템에서 누락된 것으로 감지한 총 오브젝트 수를 나타냅니다. 값은 LDR 및 DDS 서비스 내에서 데이터 저장소 구성 요소의 손실된 개체 카운터의 합계입니다.

. 관리 노드에서link:../audit/accessing-audit-log-file.html["감사 로그에 액세스합니다"] *잠재적으로 분실된 객체* 경고를 발생시킨 객체의 고유 식별자(UUID)를 확인하려면:
+
.. 그리드 노드에 로그인합니다.
+
... 다음 명령을 입력합니다. `ssh admin@grid_node_IP`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
... 다음 명령을 입력하여 루트로 전환합니다. `su -`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다. 루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.


.. 감사 로그가 있는 디렉토리로 변경합니다.
+
--
감사 로그 디렉터리 및 적용 가능한 노드는 감사 대상 설정에 따라 다릅니다.

[cols="1a,2a"]
|===
| 옵션을 선택합니다 | 목적지 


 a| 
로컬 노드(기본값)
 a| 
`/var/local/log/localaudit.log`



 a| 
관리 노드/로컬 노드
 a| 
*** 관리 노드(기본 및 비기본): `/var/local/audit/export/audit.log`
*** All nodes(모든 노드): `/var/local/log/localaudit.log` 이 모드에서는 일반적으로 파일이 비어 있거나 없습니다.




 a| 
외부 syslog 서버
 a| 
`/var/local/log/localaudit.log`

|===
감사 대상 설정에 따라, 또는 `/var/local/audit/export/` 를 입력합니다 `cd /var/local/log`

자세한 내용은 다음을 참조하세요.link:../monitor/configure-log-management.html#select-log-location["로그 위치 선택"] .

--
.. grep를 사용하여 OLST(Object Lost) 감사 메시지를 추출합니다. 다음을 입력합니다. `grep OLST audit_file_name`
.. 메시지에 포함된 UUID 값을 확인합니다.
+
[listing]
----
Admin: # grep OLST audit.log
2020-02-12T19:18:54.780426 [AUDT:[CBID(UI64):0x38186FE53E3C49A5][UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"]
[PATH(CSTR):"source/cats"][NOID(UI32):12288733][VOLI(UI64):3222345986][RSLT(FC32):NONE][AVER(UI32):10]
[ATIM(UI64):1581535134780426][ATYP(FC32):OLST][ANID(UI32):12448208][AMID(FC32):ILMX][ATID(UI64):7729403978647354233]]
----


. UUID를 사용하여 손실된 개체의 메타데이터를 찾습니다.
+
.. ILM * > * 개체 메타데이터 조회 * 를 선택합니다.
.. UUID를 입력하고 * 조회 * 를 선택합니다.
.. 메타데이터의 위치를 검토하고 적절한 작업을 수행합니다.
+
[cols="2a,4a"]
|===
| 메타데이터 | 결론 


 a| 
객체 <object_identifier>를 찾을 수 없습니다
 a| 
객체를 찾을 수 없는 경우 "ERROR":"" 메시지가 반환됩니다.

해당 객체를 찾을 수 없는 경우,<<reset-lost-obj-count,잠재적으로 손실된 객체 카운터를 재설정합니다.>> 알림을 해제하려면.  객체가 없다는 것은 해당 객체가 의도적으로 삭제되었음을 나타냅니다.



 a| 
위치 > 0
 a| 
출력에 위치가 나열되어 있는 경우 *잠재적으로 분실된 개체* 경고는 거짓 양성일 수 있습니다.

객체가 존재하는지 확인합니다. 출력에 나열된 노드 ID 및 파일 경로를 사용하여 개체 파일이 나열된 위치에 있는지 확인합니다.

객체가 존재하는 경우,<<reset-lost-obj-count,잠재적으로 손실된 객체 카운터를 재설정합니다.>> 알림을 해제하려면.



 a| 
위치 = 0
 a| 
출력에 위치가 나열되지 않으면 해당 개체가 누락되었을 가능성이 있습니다.  기술 지원팀에 문의하세요.

기술 지원 부서에서 진행 중인 스토리지 복구 절차가 있는지 확인하도록 요청할 수 있습니다. 및 에 대한 정보를 link:../maintain/restoring-volume.html["Grid Manager를 사용하여 개체 데이터를 복원합니다"]link:../maintain/restoring-object-data-to-storage-volume.html["오브젝트 데이터를 스토리지 볼륨에 복원 중입니다"]참조하십시오.

|===


. [[reset-lost-obj-count]]분실된 개체 문제를 해결한 후 잠재적으로 분실된 개체 카운터를 재설정하여 알림이 거짓 양성이 아닌지 확인하세요.
+
.. *노드*를 선택하세요.
.. *_저장 노드_* > *작업*을 선택합니다.
.. 잠재적으로 분실된 개체 카운터 재설정 섹션에서 *재설정*을 선택합니다.



