---
permalink: troubleshoot/searching-for-and-restoring-potentially-lost-objects.html 
sidebar: sidebar 
keywords: how to search lost object, how to restore lost object, how to find lost object 
summary: '객체 손실 * 경고와 기존 객체 손실(손실) 경보를 트리거하고 잠재적으로 손실된 것으로 식별된 객체를 찾아 복원할 수 있습니다.' 
---
= 잠재적으로 손실된 개체를 검색하여 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
객체 손실 * 경고와 기존 객체 손실(손실) 경보를 트리거하고 잠재적으로 손실된 것으로 식별된 객체를 찾아 복원할 수 있습니다.

.시작하기 전에
* 에서 식별된 대로 손실된 개체의 UUID가 있습니다link:../troubleshoot/investigating-lost-objects.html["손실된 개체를 조사합니다"].
*  `Passwords.txt`파일이 있습니다.


.이 작업에 대해
이 절차에 따라 그리드의 다른 위치에서 손실된 개체의 복제된 복사본을 찾을 수 있습니다. 대부분의 경우 손실된 개체를 찾을 수 없습니다. 그러나 경우에 따라 즉각적인 조치를 취할 경우 손실된 복제 개체를 찾아 복원할 수 있습니다.


CAUTION: 이 절차에 대한 지원은 기술 지원 부서에 문의하십시오.

.단계
. 관리 노드에서 감사 로그에서 가능한 객체 위치를 검색합니다.
+
.. 그리드 노드에 로그인합니다.
+
... 다음 명령을 입력합니다. `ssh admin@grid_node_IP`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
... 다음 명령을 입력하여 루트로 전환합니다. `su -`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다. 루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.


.. [[substep-1b]] 감사 로그가 위치한 디렉토리로 변경합니다.
+
--
감사 로그 디렉터리 및 적용 가능한 노드는 감사 대상 설정에 따라 다릅니다.

[cols="1a,2a"]
|===
| 옵션을 선택합니다 | 목적지 


 a| 
로컬 노드(기본값)
 a| 
`/var/local/log/localaudit.log`



 a| 
관리 노드/로컬 노드
 a| 
*** 관리 노드(운영 및 비운영): `/var/local/audit/export/audit.log`
*** All nodes(모든 노드): `/var/local/log/localaudit.log` 이 모드에서는 일반적으로 파일이 비어 있거나 없습니다.




 a| 
외부 syslog 서버
 a| 
`/var/local/log/localaudit.log`

|===
감사 대상 설정에 따라, 또는 `/var/local/audit/export/` 를 입력합니다 `cd /var/local/log`

자세한 내용은 을 link:../monitor/configure-audit-messages.html#select-audit-information-destinations["감사 정보 대상을 선택합니다"]참조하십시오.

--
.. grep를 사용하여 의 압축을 link:../audit/object-ingest-transactions.html["잠재적으로 손실된 개체와 관련된 감사 메시지입니다"]풀고 출력 파일로 보냅니다. 다음을 입력합니다. `grep uuid-value audit_file_name > output_file_name`
+
예를 들면 다음과 같습니다.

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > /var/local/tmp/messages_about_lost_object.txt
----
.. grep를 사용하여 이 출력 파일에서 LLST(Location Lost) 감사 메시지를 추출합니다. 다음을 입력합니다. `grep LLST output_file_name`
+
예를 들면 다음과 같습니다.

+
[listing]
----
Admin: # grep LLST /var/local/tmp/messages_about_lost_objects.txt
----
+
LLST 감사 메시지는 이 예제 메시지와 같습니다.

+
[listing]
----
[AUDT:[NOID(UI32):12448208][CBIL(UI64):0x38186FE53E3C49A5]
[UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"][LTYP(FC32):CLDI]
[PCLD(CSTR):"/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA#3tN6"]
[TSRC(FC32):SYST][RSLT(FC32):NONE][AVER(UI32):10][ATIM(UI64):1581535134379225]
[ATYP(FC32):LLST][ANID(UI32):12448208][AMID(FC32):CLSM][ATID(UI64):7086871083190743409]]
----
.. LLST 메시지에서 PCLD 필드와 noid 필드를 찾습니다.
+
PCLD 값이 있는 경우 누락된 복제 객체 복사본에 대한 디스크의 전체 경로입니다. noid 값은 개체의 복사본을 찾을 수 있는 LDR의 노드 ID입니다.

+
개체 위치를 찾으면 개체를 복원할 수 있습니다.

.. 이 LDR 노드 ID와 연결된 스토리지 노드를 찾습니다. Grid Manager에서 * 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_데이터 센터_ * > *_스토리지 노드_ * > * LDR * 을 선택합니다.
+
LDR 서비스의 노드 ID는 Node Information 테이블에 있습니다. 이 LDR을 호스팅하는 스토리지 노드를 찾을 때까지 각 스토리지 노드에 대한 정보를 검토하십시오.



. 감사 메시지에 표시된 스토리지 노드에 객체가 있는지 확인합니다.
+
.. 그리드 노드에 로그인합니다.
+
... 다음 명령을 입력합니다. `ssh admin@grid_node_IP`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
... 다음 명령을 입력하여 루트로 전환합니다. `su -`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
+
루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.



.. 개체의 파일 경로가 있는지 확인합니다.
+
객체의 파일 경로에 LLST 감사 메시지의 PCLD 값을 사용한다.

+
예를 들어 다음을 입력합니다.

+
[listing]
----
ls '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+

NOTE: 특수 문자를 이스케이프하려면 항상 명령에서 개체 파일 경로를 작은따옴표로 묶어야 합니다.

+
*** 개체 경로를 찾을 수 없으면 개체가 손실되어 이 절차를 사용하여 복원할 수 없습니다. 기술 지원 부서에 문의하십시오.
*** 개체 경로가 발견되면 다음 단계를 계속 진행합니다. 검색된 객체를 다시 StorageGRID로 복원할 수 있습니다.




. 개체 경로를 찾은 경우 개체를 StorageGRID로 복원해 보십시오.
+
.. 동일한 스토리지 노드에서 StorageGRID에서 관리할 수 있도록 객체 파일의 소유권을 변경합니다. 다음을 입력합니다. `chown ldr-user:bycast 'file_path_of_object'`
.. LDR 콘솔에 액세스하려면 localhost 1402에 Telnet을 사용합니다. 다음을 입력합니다. `telnet 0 1402`
.. 다음을 입력합니다. `cd /proc/STOR`
.. 다음을 입력합니다. `Object_Found 'file_path_of_object'`
+
예를 들어 다음을 입력합니다.

+
[listing]
----
Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+
명령을 실행하면 `Object_Found` 개체의 위치를 그리드에 알립니다. 또한 활성 ILM 정책이 트리거되어 각 정책에 지정된 대로 추가 복사본이 생성됩니다.

+

NOTE: 객체를 찾은 스토리지 노드가 오프라인인 경우 온라인 상태인 스토리지 노드에 객체를 복사할 수 있습니다. 객체를 온라인 스토리지 노드의 /var/local/rangedb 디렉토리에 배치합니다. 그런 다음 `Object_Found` 개체에 대한 해당 파일 경로를 사용하여 명령을 실행합니다.

+
*** 개체를 복원할 수 없으면 `Object_Found` 명령이 실패합니다. 기술 지원 부서에 문의하십시오.
*** 개체가 StorageGRID로 복원되면 성공 메시지가 나타납니다. 예를 들면 다음과 같습니다.
+
[listing]
----
ade 12448208: /proc/STOR > Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'

ade 12448208: /proc/STOR > Object found succeeded.
First packet of file was valid. Extracted key: 38186FE53E3C49A5
Renamed '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6' to '/var/local/rangedb/1/p/17/11/00rH0%DkRt78Ila#3udu'
----
+
다음 단계를 계속합니다.





. 개체가 StorageGRID에 성공적으로 복원된 경우 새 위치가 생성되었는지 확인합니다.
+
.. 을 사용하여 그리드 관리자에 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]로그인합니다.
.. ILM * > * 개체 메타데이터 조회 * 를 선택합니다.
.. UUID를 입력하고 * 조회 * 를 선택합니다.
.. 메타데이터를 검토하고 새 위치를 확인합니다.


. 관리 노드에서 이 객체에 대한 ORLM 감사 메시지에 대한 감사 로그를 검색하여 ILM(정보 수명 주기 관리)이 필요에 따라 복제본을 배치했는지 확인합니다.
+
.. 그리드 노드에 로그인합니다.
+
... 다음 명령을 입력합니다. `ssh admin@grid_node_IP`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
... 다음 명령을 입력하여 루트로 전환합니다. `su -`
... 파일에 나열된 암호를 `Passwords.txt` 입력합니다. 루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.


.. 감사 로그가 있는 디렉토리로 변경합니다. 을 <<substep-1b,하위 단계 1.b>> 참조하십시오.
.. grep를 사용하여 개체와 관련된 감사 메시지를 출력 파일에 추출합니다. 다음을 입력합니다. `grep uuid-value audit_file_name > output_file_name`
+
예를 들면 다음과 같습니다.

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > /var/local/tmp/messages_about_restored_object.txt
----
.. grep를 사용하여 이 출력 파일에서 ORLM(Object Rules MET) 감사 메시지를 추출합니다. 다음을 입력합니다. `grep ORLM output_file_name`
+
예를 들면 다음과 같습니다.

+
[listing]
----
Admin: # grep ORLM /var/local/tmp/messages_about_restored_object.txt
----
+
ORLM 감사 메시지는 이 예제 메시지와 같습니다.

+
[listing]
----
[AUDT:[CBID(UI64):0x38186FE53E3C49A5][RULE(CSTR):"Make 2 Copies"]
[STAT(FC32):DONE][CSIZ(UI64):0][UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"]
[LOCS(CSTR):"**CLDI 12828634 2148730112**, CLDI 12745543 2147552014"]
[RSLT(FC32):SUCS][AVER(UI32):10][ATYP(FC32):ORLM][ATIM(UI64):1563398230669]
[ATID(UI64):15494889725796157557][ANID(UI32):13100453][AMID(FC32):BCMS]]
----
.. 감사 메시지에서 Locs 필드를 찾습니다.
+
있는 경우 Locs의 CLDI 값은 노드 ID 및 객체 복제본이 생성된 볼륨 ID입니다. 이 메시지는 ILM이 적용되었으며 그리드의 두 위치에서 두 개의 개체 복사본이 생성되었음을 나타냅니다.



. link:resetting-lost-and-missing-object-counts.html["분실 및 누락된 개체 수를 재설정합니다"] 그리드 관리자

