---
permalink: troubleshoot/troubleshooting-admin-node-and-user-interface-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot admin node issues, how to troubleshoot user interface issues 
summary: 관리 노드 및 StorageGRID 사용자 인터페이스와 관련된 문제의 원인을 파악하는 데 도움이 되는 몇 가지 작업을 수행할 수 있습니다. 
---
= 관리 노드 및 사용자 인터페이스 문제를 해결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 노드 및 StorageGRID 사용자 인터페이스와 관련된 문제의 원인을 파악하는 데 도움이 되는 몇 가지 작업을 수행할 수 있습니다.



== 관리자 노드 로그인 오류

StorageGRID 관리자 노드에 로그인할 때 오류가 발생하는 경우 시스템에 OR https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/troubleshooting-hardware-installation-sg100-and-sg1000.html["하드웨어"^] 문제, link:../primer/what-admin-node-is.html["관리자 노드 서비스"]또는 link:../maintain/recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["Cassandra 데이터베이스 관련 문제입니다"]연결된 스토리지 노드에 문제가 있을 수 있습니다link:../troubleshoot/troubleshooting-network-hardware-and-platform-issues.html["네트워킹"].

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
*  `Passwords.txt`파일이 있습니다.
* 있습니다. link:../admin/admin-group-permissions.html["특정 액세스 권한"]


.이 작업에 대해
관리 노드에 로그인하려고 할 때 다음 오류 메시지가 나타나면 다음 문제 해결 지침을 사용하십시오.

* `Your credentials for this account were invalid. Please try again.`
* `Waiting for services to start...`
* `Internal server error. The server encountered an error and could not complete your request. Please try again. If the problem persists, contact Technical Support.`
* `Unable to communicate with server. Reloading page...`


.단계
. 10분 정도 기다린 후 다시 로그인하세요.
+
오류가 자동으로 해결되지 않으면 다음 단계로 이동합니다.

. StorageGRID 시스템에 둘 이상의 관리자 노드가 있는 경우 다른 관리자 노드에서 그리드 관리자에 로그인하여 사용할 수 없는 관리자 노드의 상태를 확인하십시오.
+
** 로그인이 가능하다면 *대시보드*, *노드*, *알림*, *지원* 옵션을 사용하여 오류의 원인을 파악할 수 있습니다.
** 관리 노드가 하나뿐이거나 여전히 로그인할 수 없는 경우 다음 단계로 이동합니다.


. 노드의 하드웨어가 오프라인인지 확인합니다.
. StorageGRID 시스템에 대해 SSO(Single Sign-On)가 활성화된 경우 다음 단계를 참조하세요.link:../admin/configure-sso.html["Single Sign-On 구성"] .
+
문제를 해결하려면 단일 관리 노드에 대해 SSO를 일시적으로 비활성화하고 다시 활성화해야 할 수 있습니다.

+

NOTE: SSO가 활성화된 경우 제한된 포트를 사용하여 로그인할 수 없습니다. 포트 443을 사용해야 합니다.

. 사용 중인 계정이 통합 사용자에 속하는지 확인합니다.
+
통합 사용자 계정이 작동하지 않는 경우 그리드 관리자에 root 와 같은 로컬 사용자로 로그인합니다.

+
** 로컬 사용자가 로그인할 수 있는 경우:
+
... 알림을 검토합니다.
... *구성* > *액세스 제어* > *ID 페더레이션*을 선택합니다.
... LDAP 서버에 대한 연결 설정을 확인하려면 * 연결 테스트 * 를 클릭합니다.
... 테스트에 실패한 경우 구성 오류를 해결합니다.


** 로컬 사용자가 로그인할 수 없고 자격 증명이 올바르다는 확신이 있으면 다음 단계로 이동합니다.


. SSH(Secure Shell)를 사용하여 관리자 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@Admin_Node_IP`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
.. 다음 명령을 입력하여 루트로 전환합니다. `su -`
.. 파일에 나열된 암호를 `Passwords.txt` 입력합니다.
+
루트로 로그인하면 프롬프트가 에서 `$` 로 `#`변경됩니다.



. 그리드 노드에서 실행 중인 모든 서비스의 상태를 봅니다. `storagegrid-status`
+
NMS, mi, nginx 및 관리 API 서비스가 모두 실행 중인지 확인합니다.

+
서비스 상태가 변경되면 출력이 즉시 업데이트됩니다.

+
....
$ storagegrid-status
Host Name                      99-211
IP Address                     10.96.99.211
Operating System Kernel        4.19.0         Verified
Operating System Environment   Debian 10.1    Verified
StorageGRID Webscale Release   11.4.0         Verified
Networking                                    Verified
Storage Subsystem                             Verified
Database Engine                5.5.9999+default Running
Network Monitoring             11.4.0         Running
Time Synchronization           1:4.2.8p10+dfsg Running
ams                            11.4.0         Running
cmn                            11.4.0         Running
nms                            11.4.0         Running
ssm                            11.4.0         Running
mi                             11.4.0         Running
dynip                          11.4.0         Running
nginx                          1.10.3         Running
tomcat                         9.0.27         Running
grafana                        6.4.3          Running
mgmt api                       11.4.0         Running
prometheus                     11.4.0         Running
persistence                    11.4.0         Running
ade exporter                   11.4.0         Running
alertmanager                   11.4.0         Running
attrDownPurge                  11.4.0         Running
attrDownSamp1                  11.4.0         Running
attrDownSamp2                  11.4.0         Running
node exporter                  0.17.0+ds      Running
sg snmp agent                  11.4.0         Running
....
. nginx-GW 서비스가 실행 중인지 확인한다 `# service nginx-gw status`
. [[use_lumberjack_to_collect_logs]] lumberjack을 사용하여 로그를 수집합니다. `# /usr/local/sbin/lumberjack.rb`
+
이전에 실패한 인증이 발생한 경우 -- start 및 - end lumberjack 스크립트 옵션을 사용하여 적절한 시간 범위를 지정할 수 있습니다. 이러한 옵션에 대한 자세한 내용은 lumberjack-h를 사용하십시오.

+
터미널에 대한 출력은 로그 아카이브가 복사된 위치를 나타냅니다.

. [[review_logs, start=10]] 다음 로그를 검토합니다.
+
** `/var/local/log/bycast.log`
** `/var/local/log/bycast-err.log`
** `/var/local/log/nms.log`
** `**/*commands.txt`


. 관리 노드에서 문제를 식별할 수 없는 경우 다음 명령 중 하나를 실행하여 사이트에서 ADC 서비스를 실행하는 세 개의 스토리지 노드의 IP 주소를 확인합니다. 일반적으로 사이트에 설치된 처음 세 개의 스토리지 노드입니다.
+
[listing]
----
# cat /etc/hosts
----
+
[listing]
----
# gpt-list-services adc
----
+
관리 노드는 인증 프로세스 중에 ADC 서비스를 사용합니다.

. 관리자 노드에서 ssh를 사용하여 식별한 IP 주소를 사용하여 각 ADC 스토리지 노드에 로그인합니다.
. 그리드 노드에서 실행 중인 모든 서비스의 상태를 봅니다. `storagegrid-status`
+
idnt, acct, nginx 및 cassandra 서비스가 모두 실행 중인지 확인합니다.

. 및 <<review_logs,로그를 검토합니다>>단계를 반복하여 <<use_Lumberjack_to_collect_logs,로그를 수집하려면 Lumberjack을 사용합니다>>스토리지 노드의 로그를 검토합니다.
. 문제를 해결할 수 없는 경우 기술 지원 부서에 문의하십시오.
+
기술 지원 팀에 수집한 로그를 제공합니다. 도 link:../monitor/logs-files-reference.html["로그 파일 참조"]참조하십시오.





== 사용자 인터페이스 문제

StorageGRID 소프트웨어를 업그레이드한 후 그리드 관리자 또는 테넌트 관리자의 사용자 인터페이스가 예상대로 응답하지 않을 수 있습니다.

.단계
. 을 사용하고 있는지 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]확인합니다.
. 웹 브라우저 캐시를 지웁니다.
+
캐시를 지우면 이전 버전의 StorageGRID 소프트웨어에서 사용된 오래된 리소스가 제거되고 사용자 인터페이스가 다시 올바르게 작동할 수 있습니다. 자세한 내용은 웹 브라우저 설명서를 참조하십시오.


