---
permalink: troubleshoot/troubleshooting-load-balancer-caching.html 
sidebar: sidebar 
keywords: how to troubleshoot load balancer caching 
summary: 로드 밸런서 캐싱과 관련된 가능한 문제와 이를 해결하는 방법에 대해 알아보세요. 
---
= 로드 밸런서 캐싱 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
로드 밸런서 캐싱과 관련된 가능한 문제와 이를 해결하는 방법에 대해 알아보세요.



== 요청이 캐시 히트인지 확인

* X-Cache 헤더는 캐시 서비스에서 처리하는 요청에 대한 응답으로 설정됩니다.  가능한 코드:
+
** `HIT`: 객체가 캐시에서 제공되었습니다.
** `PARTIAL-HIT`: 버킷/키에 캐시에 레코드가 있었지만 요청된 범위 중 일부를 캐시에서 제공할 수 없었습니다.
** `STALE`: 버킷/키에 캐시에 레코드가 있었지만 개체는 캐시에서 마지막으로 제공된 이후 업데이트되었습니다.
** `MISS`: 객체가 캐시에 없었습니다.


* 그만큼 `nginx-gw/endpoint-access.log.gz` 캐시에서 처리하는 요청에 대한 "unix:/run/cache-svc/cache-svc.sock"이 요청에 대한 레코드에 포함됩니다.
* 그만큼 `cache-svc/cache-svc.log` "요청 320390: 성공적으로 완료되었습니다(캐시 적중)" 또는 "요청 320375: 성공적으로 완료되었습니다(캐시 미스)"와 같은 메시지를 보고합니다.  동일한 "Request _<number>_" 문자열을 포함하는 다른 레코드를 검색하여 요청된 경로를 찾습니다.




== 낮은 캐시 적중률

* 새로운 작업 부하가 추가되거나 작업 부하에서 액세스하는 작업 세트가 변경되면 캐시 적중률이 낮아질 수 있습니다.  이런 상황에서는 시간이 지날수록 적중률이 증가할 것으로 예상됩니다.
* 여러 워크로드가 캐싱을 사용하는 경우 캐시에서 서비스되는 워크로드의 일부를 분리하기 위해 트래픽 분류 정책을 추가하는 것을 고려하세요.  캐시 적중률 측정항목은 트래픽 분류 정책에 따라 제공됩니다.  일부 작업 부하가 좋은 캐시 적중률을 경험하지 못하는 경우 캐싱이 활성화되지 않은 다른 엔드포인트로 해당 작업 부하를 이동하는 것을 고려하세요.
* 캐시 제거율을 평가합니다.  캐시가 작업 세트에 비해 너무 작으면 높은 추방률을 경험하게 되고 적중률이 낮아질 수 있습니다.
* FPVR에서는 특정 작업 부하의 적중률을 개선하는 옵션을 사용할 수 있습니다.




== 낮은 성능

* 캐시 적중률을 평가합니다.  캐시 적중률이 낮으면 전반적인 성능이 저하될 수 있습니다.
* 캐시 제거율을 평가합니다.  추방 중에 일부 저장 리소스는 디스크에서 기존 객체를 제거하는 데 사용됩니다.  퇴거 프로세스가 새 객체의 액세스를 따라가지 못하면 시스템이 하드 워터마크 임계값에 도달하여 캐시를 우회하기 시작할 수 있습니다.
* "네트워크 인터페이스 사용량 수신" 및 "네트워크 인터페이스 사용량 전송" 진단을 사용하여 네트워크 제한을 확인합니다.

