---
permalink: troubleshoot/troubleshooting-syslog-server.html 
sidebar: sidebar 
keywords: how to troubleshoot the external syslog server 
summary: 다음 표에는 외부 syslog 서버와 관련하여 발생할 수 있는 오류 메시지와 해결 조치가 나와 있습니다. 
---
= 외부 syslog 서버의 문제를 해결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 표에는 외부 syslog 서버와 관련하여 발생할 수 있는 오류 메시지와 해결 조치가 나와 있습니다.

이러한 오류는 외부 syslog 서버가 올바르게 구성되었는지 확인하기 위해 테스트 메시지를 보내는 데 문제가 있는 경우 외부 syslog 서버 구성 마법사에서 표시됩니다.

런타임에 문제가 보고될 수 있습니다.link:../monitor/alerts-reference.html#audit-and-syslog-alerts["외부 syslog 서버 전달 오류입니다"] 알리다.  이 경고를 받으면 경고의 지침에 따라 테스트 메시지를 다시 보내 자세한 오류 메시지를 받으세요.

외부 syslog 서버로 감사 정보를 보내는 방법에 대한 자세한 내용은 다음을 참조하십시오.

* link:../monitor/considerations-for-external-syslog-server.html["외부 syslog 서버 사용 시 고려 사항"]
* link:../monitor/configure-log-management.html["로그 관리 및 외부 syslog 서버 구성"]


[cols="1a,3a"]
|===
| 오류 메시지 | 설명 및 권장 조치 


 a| 
호스트 이름을 확인할 수 없습니다
 a| 
syslog 서버에 대해 입력한 FQDN을 IP 주소로 확인할 수 없습니다.

. 입력한 호스트 이름을 확인하십시오. IP 주소를 입력한 경우 W.X.Y.Z("점분리 십진수") 표기법에서 유효한 IP 주소인지 확인합니다.
. DNS 서버가 올바르게 구성되었는지 확인합니다.
. 각 노드가 DNS 서버의 IP 주소에 액세스할 수 있는지 확인합니다.




 a| 
연결이 거부되었습니다
 a| 
syslog 서버에 대한 TCP 또는 TLS 연결이 거부되었습니다. 호스트의 TCP 또는 TLS 포트에서 수신 대기 중인 서비스가 없거나 방화벽이 액세스를 차단하고 있을 수 있습니다.

. syslog 서버에 대해 올바른 FQDN 또는 IP 주소, 포트 및 프로토콜을 입력했는지 확인합니다.
. syslog 서비스의 호스트가 지정된 포트에서 수신 대기하는 syslog 데몬을 실행 중인지 확인합니다.
. 방화벽이 노드에서 syslog 서버의 IP 및 포트로의 TCP/TLS 연결에 대한 액세스를 차단하지 않는지 확인합니다.




 a| 
네트워크에 연결할 수 없습니다
 a| 
syslog 서버가 직접 연결된 서브넷에 없습니다. 라우터가 ICMP 오류 메시지를 반환하여 나열된 노드의 테스트 메시지를 syslog 서버로 전달할 수 없음을 나타냅니다.

. syslog 서버에 대한 올바른 FQDN 또는 IP 주소를 입력했는지 확인합니다.
. 나열된 각 노드에 대해 그리드 네트워크 서브넷 목록, 관리 네트워크 서브넷 목록 및 클라이언트 네트워크 게이트웨이를 확인합니다. 트래픽이 예상 네트워크 인터페이스 및 게이트웨이(Grid, Admin 또는 Client)를 통해 syslog 서버로 라우팅되도록 구성되었는지 확인합니다.




 a| 
호스트에 연결할 수 없습니다
 a| 
syslog 서버는 직접 연결된 서브넷(그리드, 관리 또는 클라이언트 IP 주소에 대해 나열된 노드에서 사용하는 서브넷)에 있습니다. 노드가 테스트 메시지를 보내려고 시도했지만 syslog 서버의 MAC 주소에 대한 ARP 요청에 대한 응답을 수신하지 못했습니다.

. syslog 서버에 대한 올바른 FQDN 또는 IP 주소를 입력했는지 확인합니다.
. syslog 서비스를 실행 중인 호스트가 작동 중인지 확인합니다.




 a| 
연결 시간이 초과되었습니다
 a| 
TCP/TLS 연결을 시도했지만 오랫동안 syslog 서버로부터 응답이 수신되지 않았습니다. 라우팅 구성이 잘못되거나 방화벽이 응답을 보내지 않고 트래픽을 떨어뜨릴 수 있습니다(공통 구성).

. syslog 서버에 대한 올바른 FQDN 또는 IP 주소를 입력했는지 확인합니다.
. 나열된 각 노드에 대해 그리드 네트워크 서브넷 목록, 관리 네트워크 서브넷 목록 및 클라이언트 네트워크 게이트웨이를 확인합니다. syslog 서버에 도달할 것으로 예상되는 네트워크 인터페이스 및 게이트웨이(그리드, 관리 또는 클라이언트)를 사용하여 트래픽을 syslog 서버로 라우팅하도록 구성되었는지 확인합니다.
. 방화벽이 syslog 서버의 IP 및 포트에 나열된 노드에서 TCP/TLS 연결에 대한 액세스를 차단하지 않는지 확인합니다.




 a| 
파트너가 연결을 닫았습니다
 a| 
syslog 서버에 대한 TCP 연결이 성공적으로 설정되었지만 나중에 종료되었습니다. 그 이유는 다음과 같습니다.

* syslog 서버가 다시 시작되었거나 재부팅되었을 수 있습니다.
* 노드와 syslog 서버의 TCP/TLS 설정이 다를 수 있습니다.
* 중간 방화벽이 유휴 TCP 연결을 닫는 중일 수 있습니다.
* syslog 서버 포트에서 수신 대기하는 비 syslog 서버가 연결을 닫았을 수 있습니다.


이 문제를 해결하려면:

. syslog 서버에 대해 올바른 FQDN 또는 IP 주소, 포트 및 프로토콜을 입력했는지 확인합니다.
. TLS를 사용하는 경우 syslog 서버도 TLS를 사용하고 있는지 확인합니다. TCP를 사용하는 경우 syslog 서버도 TCP를 사용하고 있는지 확인합니다.
. 유휴 TCP 연결을 종료하도록 중간 방화벽이 구성되어 있지 않은지 확인합니다.




 a| 
TLS 인증서 오류입니다
 a| 
syslog 서버로부터 받은 서버 인증서가 제공된 CA 인증서 번들 및 클라이언트 인증서와 호환되지 않습니다.

. CA 인증서 번들 및 클라이언트 인증서(있는 경우)가 syslog 서버의 서버 인증서와 호환되는지 확인합니다.
. syslog 서버의 서버 인증서 ID에 예상 IP 또는 FQDN 값이 포함되어 있는지 확인합니다.




 a| 
전달이 일시 중단되었습니다
 a| 
syslog 레코드가 더 이상 syslog 서버로 전달되지 않으며 StorageGRID에서 이유를 감지할 수 없습니다.

이 오류와 함께 제공된 디버깅 로그를 검토하여 근본 원인을 확인합니다.



 a| 
TLS 세션이 종료되었습니다
 a| 
syslog 서버가 TLS 세션을 종료했으며 StorageGRID에서 이유를 감지할 수 없습니다.

. 이 오류와 함께 제공된 디버깅 로그를 검토하여 근본 원인을 확인합니다.
. syslog 서버에 대해 올바른 FQDN 또는 IP 주소, 포트 및 프로토콜을 입력했는지 확인합니다.
. TLS를 사용하는 경우 syslog 서버도 TLS를 사용하고 있는지 확인합니다. TCP를 사용하는 경우 syslog 서버도 TCP를 사용하고 있는지 확인합니다.
. CA 인증서 번들 및 클라이언트 인증서(있는 경우)가 syslog 서버의 서버 인증서와 호환되는지 확인합니다.
. syslog 서버의 서버 인증서 ID에 예상 IP 또는 FQDN 값이 포함되어 있는지 확인합니다.




 a| 
결과 쿼리에 실패했습니다
 a| 
syslog 서버 구성 및 테스트에 사용된 관리자 노드가 나열된 노드에서 테스트 결과를 요청할 수 없습니다. 하나 이상의 노드가 다운되었을 수 있습니다.

. 표준 문제 해결 단계를 수행하여 노드가 온라인 상태이고 모든 예상 서비스가 실행 중인지 확인합니다.
. 나열된 노드에서 오류 서비스를 다시 시작합니다.


|===