---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords: how to troubleshoot lost object data, how to troubleshoot missing object data 
summary: 클라이언트 애플리케이션의 읽기 요청, 복제된 오브젝트 데이터의 백그라운드 검증, ILM 재평가, 스토리지 노드 복구 중 오브젝트 데이터 복원을 비롯한 여러 가지 이유로 오브젝트를 검색할 수 있습니다. 
---
= 분실하거나 누락된 오브젝트 데이터 문제를 해결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클라이언트 애플리케이션의 읽기 요청, 복제된 오브젝트 데이터의 백그라운드 검증, ILM 재평가, 스토리지 노드 복구 중 오브젝트 데이터 복원을 비롯한 여러 가지 이유로 오브젝트를 검색할 수 있습니다.

StorageGRID 시스템은 객체의 메타데이터에 있는 위치 정보를 사용하여 객체를 검색할 위치를 결정합니다.  예상 위치에서 객체의 사본을 찾을 수 없는 경우, 시스템은 ILM 정책에 객체의 사본을 두 개 이상 만드는 규칙이 포함되어 있다고 가정하고 시스템의 다른 곳에서 객체의 다른 사본을 검색하려고 시도합니다.

이 검색이 성공하면 StorageGRID 시스템은 해당 개체의 누락된 사본을 대체합니다.  그렇지 않으면 다음과 같이 *잠재적으로 분실된 객체* 경고가 발생합니다.

* 복제된 복사본의 경우 다른 복사본을 검색할 수 없으면 개체가 손실된 것으로 간주되어 경고가 트리거됩니다.
* 삭제 코딩 복제본의 경우 예상 위치에서 복제본을 검색할 수 없는 경우 다른 위치에서 복사본을 검색하려고 시도하기 전에 ECOR(Corrupt Copies Detected) 속성이 1씩 증가합니다. 다른 복사본을 찾을 수 없으면 경고가 트리거됩니다.


*잠재적으로 손실된 객체* 경고를 모두 즉시 조사하여 손실의 근본 원인을 파악하고 해당 객체가 오프라인 또는 현재 사용할 수 없는 스토리지 노드에 여전히 존재할 수 있는지 확인해야 합니다. 보다 link:../troubleshoot/investigating-potentially-lost-objects.html["분실 가능성이 있는 물건을 조사하세요"] .  분실물 알림은 주의를 기울이지 않아 잘못 울릴 수 있습니다.

사본이 없는 객체 데이터가 손실된 경우 복구 솔루션은 없습니다.  하지만 당신은해야합니다link:../troubleshoot/investigating-potentially-lost-objects.html#reset-lost-obj-count["잠재적으로 손실된 객체 카운터를 재설정합니다."] 알려진 분실물이 새로운 분실물을 가리는 것을 방지하기 위함입니다.
