---
permalink: ilm/advantages-disadvantages-of-ingest-options.html 
sidebar: sidebar 
keywords: ingest options, balance ingest, strict ingest, dual commit ingest 
summary: '수집 시 데이터를 보호하기 위한 세 가지 옵션(균형, 엄격 또는 이중 커밋\)의 각 장단점을 이해하면 ILM 규칙에 대해 선택할 항목을 결정하는 데 도움이 됩니다.' 
---
= 수집 옵션의 장점, 단점 및 제한 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
수집 시 데이터를 보호하기 위한 세 가지 옵션(균형, 엄격 또는 이중 커밋)의 각 장단점을 이해하면 ILM 규칙에 대해 선택할 항목을 결정하는 데 도움이 됩니다.

수집 옵션에 대한 개요는 를 참조하십시오link:data-protection-options-for-ingest.html["수집 옵션"].



== 균형 및 엄격 옵션의 장점

수집하는 동안 임시 사본을 생성하는 이중 커밋과 비교할 때 두 개의 동기식 배치 옵션은 다음과 같은 이점을 제공합니다.

* * 더 나은 데이터 보안 *: ILM 규칙의 배치 지침에 지정된 대로 개체 데이터가 즉시 보호됩니다. ILM은 둘 이상의 스토리지 위치 장애를 포함하여 다양한 장애 조건을 보호하도록 구성할 수 있습니다. 이중 커밋은 단일 로컬 복사본의 손실로부터 보호할 수 있습니다.
* * 더 효율적인 그리드 작업 *: 각 오브젝트는 수집될 때 한 번만 처리됩니다. StorageGRID 시스템은 중간 복사본을 추적하거나 삭제할 필요가 없으므로 처리 부하가 줄어들고 데이터베이스 공간이 더 적게 사용됩니다.
* * (Balanced) 권장 *: 최적의 ILM 효율성을 제공하는 균형 잡힌 옵션입니다. 엄격한 수집 동작이 필요하거나 그리드가 이중 커밋 사용에 대한 모든 기준을 충족하지 않는 한 균형 옵션을 사용하는 것이 좋습니다.
* * (Strict) 개체 위치에 대한 확실성 * : Strict 옵션은 ILM 규칙의 배치 지침에 따라 개체를 즉시 저장합니다.




== 균형 및 엄격 옵션의 단점

이중 커밋과 비교할 때 균형 및 엄격 옵션에는 다음과 같은 몇 가지 단점이 있습니다.

* * 더 긴 클라이언트 인제스트 *: 클라이언트 인제스트 지연 시간이 더 길어질 수 있습니다. Balanced 또는 Strict 옵션을 사용하는 경우 삭제 코딩 단편이나 복제된 복제본이 모두 생성 및 저장될 때까지 "수집 성공" 메시지가 클라이언트에 반환되지 않습니다. 하지만 오브젝트 데이터는 최종 위치에 훨씬 더 빠르게 도달할 수 있습니다.
* * (Strict) 수집 실패 비율 증가 *: Strict 옵션을 사용하면 StorageGRID에서 ILM 규칙에 지정된 모든 복사본을 즉시 만들 수 없을 때마다 수집이 실패합니다. 필요한 스토리지 위치가 일시적으로 오프라인이거나 네트워크 문제로 인해 사이트 간에 오브젝트 복제가 지연될 경우 수집 장애가 발생할 가능성이 높습니다.
* * (Strict) S3 멀티파트 업로드 배치가 일부 상황에서 예상과 다를 수 있습니다. *: Strict 를 사용하면 ILM 규칙에 설명된 대로 개체를 배치하거나 수집하지 못할 수 있습니다. 하지만 S3 멀티파트 업로드를 사용하면 ILM이 수집되는 개체의 각 부분에 대해 계산되고, 멀티파트 업로드가 완료되면 개체 전체에 대해 평가됩니다. 다음과 같은 상황에서는 예상과 다른 배치를 초래할 수 있습니다.
+
** * S3 멀티파트 업로드가 진행 중일 때 ILM이 변경되는 경우 *: 각 파트는 파트를 인제스트할 때 활성 규칙에 따라 배치되므로 멀티파트 업로드가 완료될 때 개체의 일부 부분이 현재 ILM 요구 사항을 충족하지 못할 수 있습니다. 이 경우 오브젝트 수집은 실패하지 않습니다. 대신 올바르게 배치되지 않은 모든 부품은 ILM 재평가를 위해 대기하다가 나중에 올바른 위치로 이동됩니다.
** * ILM 규칙이 크기 * 를 기준으로 필터링할 때: 파트에 대한 ILM을 평가할 때 StorageGRID은 개체의 크기가 아닌 파트 크기를 필터링합니다. 즉, 개체의 일부를 개체에 대한 ILM 요구 사항을 전체가 충족하지 않는 위치에 저장할 수 있습니다. 예를 들어, 규칙이 모든 오브젝트 10GB 이상이 DC1에 저장되는 반면 모든 작은 오브젝트는 DC2에 저장되는 것으로 지정하는 경우 10개 부분 멀티파트 업로드의 각 1GB 부분은 DC2에 저장됩니다. 개체에 대한 ILM을 평가할 때 개체의 모든 부분이 DC1로 이동합니다.


* * (Strict) Ingest는 오브젝트 태그 또는 메타데이터를 업데이트하고 새로 필요한 배치를 만들 수 없을 때 실패합니다. * : Strict 를 사용하면 ILM 규칙에 설명된 대로 개체를 배치하거나 수집 실패가 발생할 수 있습니다. 하지만 이미 그리드에 저장된 개체의 메타데이터 또는 태그를 업데이트하는 경우 객체가 다시 수집되지 않습니다. 즉, 업데이트로 인해 트리거되는 오브젝트 위치는 즉시 변경되지 않습니다. ILM을 정상적인 배경 ILM 프로세스에 의해 재평가할 때 배치 변경이 이루어집니다. 필요한 위치를 변경할 수 없는 경우(예: 새로 필요한 위치를 사용할 수 없는 경우), 업데이트된 개체는 배치를 변경할 수 있을 때까지 현재 위치를 유지합니다.




== 균형 및 엄격 옵션을 사용한 개체 배치 제한

다음 배치 지침이 있는 ILM 규칙에는 균형 또는 엄격 옵션을 사용할 수 없습니다.

* 0일에 클라우드 스토리지 풀에 배치.
* 규칙에 사용자 정의 생성 시간이 레퍼런스 시간으로 설정된 경우의 클라우드 스토리지 풀 배치


이러한 제한 사항은 StorageGRID가 클라우드 스토리지 풀에 대한 복제본을 동기식으로 만들 수 없고 사용자 정의 생성 시간이 현재로 해결될 수 있기 때문입니다.



== ILM 규칙 및 일관성이 상호 작용하여 데이터 보호에 영향을 미치는 방법

ILM 규칙과 정합성 보장 선택은 모두 오브젝트를 보호하는 방법에 영향을 미칩니다. 이러한 설정은 상호 작용할 수 있습니다.

예를 들어, ILM 규칙을 위해 선택된 수집 동작은 오브젝트 복사본의 초기 배치에 영향을 미치며, 오브젝트가 저장될 때 사용되는 일관성은 오브젝트 메타데이터의 초기 배치에 영향을 미칩니다. StorageGRID에서는 클라이언트 요청을 이행하기 위해 오브젝트의 데이터와 메타데이터에 모두 액세스해야 하기 때문에 정합성 보장 및 수집 동작에 대해 일치하는 보호 수준을 선택하면 초기 데이터 보호 수준을 높이고 시스템 응답을 예측할 수 있습니다.

다음은 StorageGRID에서 사용할 수 있는 정합성 보장 값에 대한 간략한 요약입니다.

* * ALL *: 모든 노드가 즉시 객체 메타데이터를 수신하거나 요청이 실패합니다.
* *강력한 글로벌*: 모든 사이트의 모든 클라이언트 요청에 대해 읽기-쓰기 일관성을 보장합니다.  Quorum 의미 체계가 구성되면 다음 동작이 적용됩니다.
+
** 그리드에 사이트가 3개 이상 있는 경우 클라이언트 요청에 대한 사이트 장애 허용을 허용합니다.  2개 사이트 그리드는 사이트 장애 허용 범위를 갖지 않습니다.
** 다음 S3 작업은 한 사이트가 다운되면 성공할 수 없습니다.
+
*** DeleteBucketEncryption
*** PutBucketBranch
*** PutBucketEncryption을 참조하십시오
*** PutBucketVersioning을 참조하십시오
*** PutObjectLegalHold를 선택합니다
*** PutObjectLockConfiguration 을 참조하십시오
*** PutObjectRetention




+
필요한 경우 다음을 수행할 수 있습니다. https://kb.netapp.com/hybrid/StorageGRID/Object_Mgmt/Configuring_StorageGRID_quorum_semantics_for_strong-global_consistency["강력한 글로벌 일관성을 위해 StorageGRID Quorum 의미 체계를 구성합니다."^] .

* *Strong-site*: 개체 메타데이터가 사이트의 다른 노드에 즉시 배포됩니다. 사이트 내의 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.
* *Read-after-new-write*: 새 개체에 대해 읽기-쓰기 후 일관성을 제공하고 개체 업데이트에 대한 최종 일관성을 제공합니다. 고가용성 및 데이터 보호 보장 제공 대부분의 경우에 권장됩니다.
* * 사용 가능 *: 새 객체 및 객체 업데이트 모두에 대한 최종 일관성을 제공합니다. S3 버킷의 경우 필요한 경우에만 사용하십시오(예: 거의 읽지 않는 로그 값이 포함된 버킷의 경우 또는 존재하지 않는 키의 헤드 또는 GET 작업의 경우). S3 FabricPool 버킷은 지원되지 않습니다.



NOTE: 일관성 값을 선택하기 전에link:../s3/consistency.html["일관성에 대한 전체 설명을 읽어 보십시오"] .  기본값을 변경하기 전에 이점과 제한 사항을 이해해야 합니다.



== 일관성과 ILM 규칙이 상호 작용하는 방법의 예

다음 ILM 규칙과 일관성을 갖춘 3개 사이트 그리드가 있다고 가정해 보겠습니다.

* *ILM 규칙*: 로컬 사이트에 하나씩, 원격 사이트마다 하나씩, 총 세 개의 개체 복사본을 만듭니다.  엄격한 수집 동작을 사용합니다.
* *일관성*: 강력한 글로벌(객체 메타데이터가 여러 사이트에 즉시 배포됨).


클라이언트가 그리드에 객체를 저장하면 StorageGRID 세 개의 객체 사본을 모두 만들고 메타데이터를 여러 사이트에 배포한 후 클라이언트에 성공을 반환합니다.

해당 객체는 성공적인 메시지 수집 시점에 손실로부터 완벽하게 보호됩니다.  예를 들어, 로컬 사이트가 수집 직후 손실되더라도 개체 데이터와 개체 메타데이터의 사본은 모두 원격 사이트에 남아 있습니다.  해당 객체는 다른 사이트에서도 완전히 검색 가능합니다.

대신 동일한 ILM 규칙과 강력한 사이트 일관성을 사용하면 개체 데이터가 원격 사이트에 복제되고 개체 메타데이터가 해당 사이트에 배포되기 전에 클라이언트가 성공 메시지를 받을 수 있습니다.  이 경우, 객체 메타데이터의 보호 수준이 객체 데이터의 보호 수준과 일치하지 않습니다.  수집 직후 로컬 사이트가 손실되면 개체 메타데이터도 손실됩니다.  해당 객체를 검색할 수 없습니다.

일관성과 ILM 규칙 간의 상호 관계는 복잡할 수 있습니다. 도움이 필요하면 NetApp에 문의하십시오.

.관련 정보
link:example-5-ilm-rules-and-policy-for-strict-ingest-behavior.html["예 5: 엄격한 수집 동작을 위한 ILM 규칙 및 정책"]
