---
permalink: ilm/advantages-disadvantages-and-requirements-for-ec.html 
sidebar: sidebar 
keywords: erasure coding advantages, disadvantages, EC requirements 
summary: 오브젝트 데이터의 손실로부터 보호하기 위해 복제 또는 삭제 코딩을 사용할지 결정하기 전에 삭제 코딩의 장점, 단점 및 요구 사항을 이해해야 합니다. 
---
= 삭제 코딩의 장점, 단점 및 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
오브젝트 데이터의 손실로부터 보호하기 위해 복제 또는 삭제 코딩을 사용할지 결정하기 전에 삭제 코딩의 장점, 단점 및 요구 사항을 이해해야 합니다.



== 삭제 코딩의 장점

삭제 코딩은 복제와 비교할 때 안정성, 가용성 및 스토리지 효율성을 향상시킵니다.

* *신뢰성*: 데이터 손실 없이 견딜 수 있는 동시 실패 횟수로 측정합니다.
+
** 복제: 여러 개의 동일한 객체 사본이 서로 다른 노드와 사이트 전체에 저장됩니다.
** 삭제 코딩: 객체는 데이터와 패리티 조각으로 인코딩되어 여러 노드와 사이트에 분산됩니다.  이러한 분산은 사이트와 노드 장애에 대한 보호 기능을 제공합니다.


* *가용성*: 스토리지 노드에 장애가 발생하거나 접근이 불가능해질 경우 객체를 가져올 수 있는 기능입니다.  복제와 비교했을 때, 삭제 코딩은 비슷한 저장 비용으로 가용성을 높여줍니다.
* *저장 효율성*: 비슷한 가용성과 안정성을 제공하지만, 삭제 코딩된 객체는 복제된 객체보다 디스크 공간을 덜 사용합니다.  예를 들어, 두 사이트에 복제된 10MB 객체는 20MB의 디스크 공간(두 개의 사본)을 사용하는 반면, 6+3 삭제 코딩 방식을 사용하여 세 사이트에 삭제 코딩된 객체는 15MB의 디스크 공간만 사용합니다.
+

NOTE: 삭제 코딩 오브젝트를 위한 디스크 공간은 오브젝트 크기와 스토리지 오버헤드로 계산됩니다. 스토리지 오버헤드 비율은 패리티 조각 수를 데이터 조각 수로 나눈 값입니다.





== 삭제 코딩의 단점

복제와 비교할 때 삭제 코딩에는 다음과 같은 단점이 있습니다.

* 삭제 코딩 체계에 따라 스토리지 노드 및 사이트의 수를 늘리는 것이 좋습니다. 반면, 오브젝트 데이터를 복제할 경우 각 복제본마다 스토리지 노드가 하나만 필요합니다. link:what-erasure-coding-schemes-are.html#erasure-coding-schemes-for-storage-pools-containing-three-or-more-sites["3개 이상의 사이트가 포함된 스토리지 풀의 삭제 코딩 체계"]및 을 link:what-erasure-coding-schemes-are.html#erasure-coding-schemes-for-one-site-storage-pools["단일 사이트 스토리지 풀에 대한 삭제 코딩 구성표"]참조하십시오.
* 스토리지 확장의 비용 및 복잡성 증가 복제를 사용하는 배포를 확장하려면 개체 복사본이 만들어지는 모든 위치에 스토리지 용량을 추가해야 합니다. 삭제 코딩을 사용하는 배포를 확장하려면 사용 중인 삭제 코딩 체계와 기존 스토리지 노드의 전체 용량을 고려해야 합니다. 예를 들어, 기존 노드가 100%로 꽉 찰 때까지 기다린 경우 스토리지 노드를 하나 이상 추가해야 `k+m` 하지만, 기존 노드가 70% 차 있을 때 확장하는 경우 사이트당 2개의 노드를 추가하여 사용 가능한 스토리지 용량을 최대화할 수 있습니다. 자세한 내용은 을 link:../expand/adding-storage-capacity-for-erasure-coded-objects.html["삭제 코딩 오브젝트를 위한 스토리지 용량을 추가합니다"]참조하십시오.
* 지리적으로 분산된 사이트에서 삭제 코딩을 사용하면 검색 지연 시간이 늘어납니다. 삭제 코딩되어 원격 사이트에 배포된 오브젝트의 오브젝트 조각은 복제되고 로컬에서 사용 가능한 오브젝트(클라이언트가 연결하는 동일한 사이트)에 비해 WAN 연결을 통해 검색하는 데 시간이 더 오래 걸립니다.
* 지리적으로 분산된 사이트에서 삭제 코딩을 사용하는 경우 검색 및 복구를 위해 WAN 네트워크 트래픽 사용량이 증가하고, 특히 자주 검색하는 오브젝트 또는 WAN 네트워크 연결을 통한 오브젝트 복구에서 더욱 그렇습니다.
* 사이트 간에 삭제 코딩을 사용하면 사이트 간 네트워크 지연 시간이 증가함에 따라 최대 개체 처리량이 급격히 감소합니다.  이러한 감소는 TCP 네트워크 처리량이 감소한 결과이며, 이는 StorageGRID 시스템이 객체 조각을 얼마나 빨리 저장하고 검색할 수 있는지에 영향을 미칩니다.
* 컴퓨팅 리소스 사용량 증가.




== 삭제 코딩 사용 시기

다음 요구 사항에는 삭제 코딩을 사용하세요.

* 크기가 1MB를 초과하는 객체
+

NOTE: 삭제 코딩은 1MB 이상의 오브젝트에 가장 적합합니다. 매우 작은 삭제 코딩 조각을 관리해야 하는 오버헤드를 방지하기 위해 200KB 미만의 오브젝트에 삭제 코딩을 사용하지 마십시오.

* 자주 검색되지 않는 콘텐츠의 장기 또는 콜드 스토리지
* 높은 데이터 가용성 및 안정성
* 전체 사이트 및 노드 장애로부터 보호
* 스토리지 효율성:
* 여러 개의 복제된 복사본이 아닌 하나의 삭제 코딩 복사본만으로 효율적인 데이터 보호가 필요한 단일 사이트 배포
* 사이트 간 지연 시간이 100ms 미만인 다중 사이트 구축

