---
permalink: ilm/comparing-cloud-storage-pools-to-cloudmirror-replication.html 
sidebar: sidebar 
keywords: cloud storage pools, cloudmirror replication 
summary: 클라우드 스토리지 풀을 사용할 때는 클라우드 스토리지 풀과 StorageGRID CloudMirror 복제 서비스의 유사점과 차이점을 이해하는 것이 좋습니다. 
---
= 클라우드 스토리지 풀 및 CloudMirror 복제 비교
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클라우드 스토리지 풀을 사용할 때는 클라우드 스토리지 풀과 StorageGRID CloudMirror 복제 서비스의 유사점과 차이점을 이해하는 것이 좋습니다.

[cols="1a,3a,3a"]
|===
|  | 클라우드 스토리지 풀 | CloudMirror 복제 서비스 


 a| 
주요 목적은 무엇입니까?
 a| 
아카이브 타겟 역할을 합니다. Cloud Storage Pool의 오브젝트 복사본은 개체의 유일한 복사본이거나 추가 복사본일 수 있습니다. 즉, 복사본을 두 개에 유지하는 대신 StorageGRID 내에 하나의 복사본을 유지하고 복사본을 클라우드 스토리지 풀에 보낼 수 있습니다.
 a| 
테넌트가 StorageGRID(소스)의 버킷에서 외부 S3 버킷(대상)으로 오브젝트를 자동으로 복제할 수 있습니다. 독립 S3 인프라에서 개체의 독립적인 복사본을 생성합니다.



 a| 
어떻게 설정합니까?
 a| 
그리드 관리자 또는 그리드 관리 API를 사용하여 스토리지 풀과 동일한 방식으로 정의됩니다. ILM 규칙의 배치 위치로 선택할 수 있습니다. 스토리지 풀은 스토리지 노드 그룹으로 구성되지만, 클라우드 스토리지 풀은 원격 S3 또는 Azure 엔드포인트(IP 주소, 자격 증명 등)를 사용하여 정의됩니다.
 a| 
테넌트 관리자 또는 S3 API를 사용하여 CloudMirror 엔드포인트(IP 주소, 자격 증명 등)를 정의하여 테넌트 사용자link:../tenant/configuring-cloudmirror-replication.html["CloudMirror 복제 구성"] CloudMirror 엔드포인트를 설정한 후 해당 테넌트 계정이 소유한 모든 버킷이 CloudMirror 엔드포인트를 가리키도록 구성할 수 있습니다.



 a| 
누가 설정해야 합니까?
 a| 
일반적으로 그리드 관리자
 a| 
일반적으로 테넌트 사용자입니다



 a| 
대상은 무엇입니까?
 a| 
* 호환 가능한 S3 인프라(Amazon S3 포함)
* Azure Blob 아카이브 계층입니다
* Google Cloud Platform(GCP)

 a| 
* 호환 가능한 S3 인프라(Amazon S3 포함)
* Google Cloud Platform(GCP)




 a| 
오브젝트를 대상으로 이동하는 원인은 무엇입니까?
 a| 
활성 ILM 정책에 있는 하나 이상의 ILM 규칙. ILM 규칙은 StorageGRID이 클라우드 스토리지 풀로 이동하는 오브젝트와 오브젝트를 이동할 시기를 정의합니다.
 a| 
CloudMirror 엔드포인트로 구성된 소스 버킷으로 새 객체를 인스팅하는 작업. 버킷이 CloudMirror 엔드포인트로 구성되기 전에 소스 버킷에 있던 객체는 수정되지 않으면 복제되지 않습니다.



 a| 
객체를 검색하는 방법은 무엇입니까?
 a| 
애플리케이션이 StorageGRID에 요청을 보내 클라우드 스토리지 풀로 이동된 객체를 검색해야 합니다. 개체의 복사본만 아카이브 스토리지로 전환된 경우 StorageGRID는 개체를 복원하는 프로세스를 관리하여 검색할 수 있습니다.
 a| 
타겟 버킷의 미러링된 복사본은 독립 복사본이므로 애플리케이션이 StorageGRID 또는 S3 타겟에 요청을 함으로써 오브젝트를 검색할 수 있습니다. 예를 들어 CloudMirror 복제를 사용하여 객체를 파트너 조직에 미러링한다고 가정합니다. 파트너는 자체 애플리케이션을 사용하여 S3 대상에서 직접 오브젝트를 읽거나 업데이트할 수 있습니다. StorageGRID를 사용할 필요가 없습니다.



 a| 
목적지에서 직접 읽을 수 있습니까?
 a| 
아니요. 클라우드 스토리지 풀로 이동된 오브젝트는 StorageGRID에서 관리합니다. 읽기 요청은 StorageGRID으로 전달되어야 합니다(StorageGRID은 클라우드 스토리지 풀에서 검색을 담당함).
 a| 
예, 미러링된 복사본은 독립 복사본이므로 그렇습니다.



 a| 
소스에서 개체를 삭제하면 어떻게 됩니까?
 a| 
이 오브젝트는 클라우드 스토리지 풀에서도 삭제됩니다.
 a| 
삭제 작업은 복제되지 않습니다. 삭제된 객체가 StorageGRID 버킷에 더 이상 존재하지 않지만 대상 버킷에는 계속 존재합니다. 마찬가지로, 소스에 영향을 주지 않고 대상 버킷의 오브젝트를 삭제할 수 있습니다.



 a| 
재해 발생 후 개체에 어떻게 액세스합니까(StorageGRID 시스템이 작동하지 않음)?
 a| 
장애가 발생한 StorageGRID 노드를 복구해야 합니다. 이 프로세스 중에 Cloud Storage Pool의 복사본을 사용하여 복제된 개체의 복사본을 복원할 수 있습니다.
 a| 
CloudMirror 대상에 있는 오브젝트 복사본은 StorageGRID와 독립적이므로 StorageGRID 노드를 복구하기 전에 직접 액세스할 수 있습니다.

|===