---
permalink: ilm/creating-cloud-storage-pool.html 
sidebar: sidebar 
keywords: how to create cloud storage pool 
summary: 클라우드 스토리지 풀은 단일 외부 Amazon S3 버킷 또는 기타 S3 호환 공급자 또는 Azure Blob 스토리지 컨테이너를 지정합니다. 
---
= 클라우드 스토리지 풀을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클라우드 스토리지 풀은 단일 외부 Amazon S3 버킷 또는 기타 S3 호환 공급자 또는 Azure Blob 스토리지 컨테이너를 지정합니다.

클라우드 스토리지 풀을 생성할 때 StorageGRID에서 오브젝트를 저장할 외부 버킷 또는 컨테이너의 이름과 위치, 클라우드 공급자 유형(Amazon S3/GCP 또는 Azure Blob 스토리지) 및 StorageGRID이 외부 버킷 또는 컨테이너에 액세스하는 데 필요한 정보를 지정합니다.

StorageGRID는 저장하는 즉시 클라우드 스토리지 풀을 검증하므로, 클라우드 스토리지 풀에 지정된 버킷이나 컨테이너가 존재하고 연결 가능한지 확인해야 합니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:../admin/admin-group-permissions.html["액세스 권한이 필요합니다"]있습니다.
* 를 검토했습니다.link:considerations-for-cloud-storage-pools.html["클라우드 스토리지 풀에 대한 고려 사항"]
* 클라우드 스토리지 풀에서 참조하는 외부 버킷 또는 컨테이너가 이미 있으며 이 <<service-endpoint-info,서비스 끝점 정보입니다>>있습니다.
* 버킷 또는 컨테이너에 접근하려면 를 선택할 수 <<authentication-account-info,인증 유형에 대한 계정 정보입니다>>있습니다.


.단계
. ILM * > * 스토리지 풀 * > * 클라우드 스토리지 풀 * 을 선택합니다.
. Create * 를 선택한 후 다음 정보를 입력합니다.
+
[cols="1a,3a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
클라우드 스토리지 풀 이름입니다
 a| 
Cloud Storage Pool과 그 용도를 간략하게 설명하는 이름입니다. ILM 규칙을 구성할 때 쉽게 식별할 수 있는 이름을 사용합니다.



 a| 
공급자 유형입니다
 a| 
이 클라우드 스토리지 풀에 사용할 클라우드 공급자:

** * Amazon S3/GCP *: Amazon S3, C2S(Commercial Cloud Services) S3, GCP(Google Cloud Platform) 또는 기타 S3 호환 공급자의 경우 이 옵션을 선택합니다.
** * Azure Blob 저장소 *




 a| 
버킷 또는 용기
 a| 
외부 S3 버킷 또는 Azure 컨테이너의 이름입니다. 클라우드 스토리지 풀을 저장한 후에는 이 값을 변경할 수 없습니다.

|===
. [[service-endpoint-info]] 제공자 유형 선택에 따라 서비스 끝점 정보를 입력합니다.
+
[role="tabbed-block"]
====
.Amazon S3/GCP
--
.. 프로토콜에서 HTTPS 또는 HTTP를 선택합니다.
+

NOTE: 중요한 데이터에 HTTP 연결을 사용하지 마십시오.

.. 호스트 이름을 입력합니다. 예:
+
`s3-_aws-region_.amazonaws.com`

.. URL 스타일 선택:
+
[cols="1a,3a"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
자동 감지
 a| 
제공된 정보를 기반으로 사용할 URL 스타일을 자동으로 감지해 봅니다. 예를 들어, IP 주소를 지정하면 StorageGRID는 경로 스타일 URL을 사용합니다. 사용할 특정 스타일을 모르는 경우에만 이 옵션을 선택합니다.



 a| 
가상 호스팅 방식
 a| 
가상 호스팅 방식의 URL을 사용하여 버킷에 액세스합니다. 가상 호스팅 방식의 URL에는 도메인 이름의 일부로 버킷 이름이 포함됩니다. 예: `+https://bucket-name.s3.company.com/key-name+`



 a| 
경로 스타일
 a| 
경로 스타일 URL을 사용하여 버킷에 액세스합니다. 경로 스타일 URL의 끝에는 버킷 이름이 포함됩니다 예: `+https://s3.company.com/bucket-name/key-name+`

* 참고: * 경로 스타일 URL 옵션은 권장되지 않으며 향후 StorageGRID 릴리스에서 더 이상 사용되지 않습니다.

|===
.. 필요한 경우 포트 번호를 입력하거나 기본 포트 443을 HTTPS에 사용하거나 80을 HTTP에 사용합니다.


--
.Azure Blob 저장소
--
.. 다음 형식 중 하나를 사용하여 서비스 끝점의 URI를 입력합니다.
+
*** `+https://host:port+`
*** `+http://host:port+`




예: `https://_myaccount_.blob.core.windows.net:443`

포트를 지정하지 않으면 기본적으로 포트 443이 HTTPS에 사용되고 포트 80은 HTTP에 사용됩니다.

--
====


. [[authentication-account-info]] * Continue * 를 선택합니다. 그런 다음 인증 유형을 선택하고 Cloud Storage Pool 엔드포인트를 위한 필수 정보를 입력합니다.
+
[role="tabbed-block"]
====
.액세스 키
--
_ Amazon S3/GCP 또는 기타 S3 호환 제공업체의 경우 _

.. * 액세스 키 ID *: 외부 버킷을 소유한 계정의 액세스 키 ID를 입력하십시오.
.. * 비밀 액세스 키 * : 비밀 액세스 키를 입력합니다.


--
.어디서나 IAM 역할 수행
--
_ AWS IAM 역할 Anywhere 서비스의 경우 _

StorageGRID은 AWS STS(Security Token Service)를 사용하여 AWS 리소스에 액세스하기 위한 단기 토큰을 동적으로 생성합니다.

.. * AWS IAM 역할 Anywhere 지역 *: 클라우드 스토리지 풀의 지역을 선택합니다.  `us-east-1`예를 들어,
.. *Trust anchor URN*: 단기간 STS 자격 증명에 대한 요청의 유효성을 검사하는 신뢰 앵커의 URN을 입력합니다. 루트 또는 중간 CA일 수 있습니다.
.. * Profile URN *: IAM Roles Anywhere 프로파일의 URN을 입력합니다. 이 프로파일에는 신뢰할 수 있는 사람이 추론할 수 있는 역할이 나열되어 있습니다.
.. * 역할 URN * : 신뢰할 수 있는 사람이 추정하는 IAM 역할의 URN을 입력하십시오.
.. * 세션 기간 *: 임시 보안 자격 증명과 역할 세션의 기간을 입력합니다. 15분 이상 12시간 이내로 입력하십시오.
.. * 서버 CA 인증서 * (선택 사항): 하나 이상의 신뢰할 수 있는 CA 인증서(PEM 형식), IAM 역할 Anywhere 서버 확인을 위한 인증서. 생략하면 서버가 확인되지 않습니다.
.. *최종 엔터티 인증서*: 신뢰 앵커에서 서명한 X509 인증서의 PEM 형식의 공개 키입니다. AWS IAM Roles Anywhere는 이 키를 사용하여 STS 토큰을 발급합니다.
.. * 최종 엔티티 개인 키 *: 최종 엔티티 인증서의 개인 키입니다.


--
.CAP(C2S 액세스 포털)
--
_C2S(Commercial Cloud Services) S3 서비스 _

.. * 임시 자격 증명 URL *: C2S 계정에 할당된 모든 필수 및 선택적 API 매개 변수를 포함하여 StorageGRID가 CAP 서버에서 임시 자격 증명을 얻기 위해 사용할 전체 URL을 입력하십시오.
.. * 서버 CA 인증서 *: * 찾아보기 * 를 선택하고 StorageGRID가 CAP 서버를 확인하는 데 사용할 CA 인증서를 업로드합니다. 인증서는 PEM으로 인코딩되어 적절한 CA(정부 인증 기관)에서 발급해야 합니다.
.. * 클라이언트 인증서 *: * 찾아보기 * 를 선택하고 StorageGRID가 CAP 서버에 자신을 식별하는 데 사용할 인증서를 업로드합니다. 클라이언트 인증서는 PEM 인코딩되어 적절한 CA(정부 인증 기관)에서 발급되고 C2S 계정에 대한 액세스 권한이 부여되어야 합니다.
.. * 클라이언트 개인 키 *: * 찾아보기 * 를 선택하고 클라이언트 인증서에 대한 PEM 인코딩된 개인 키를 업로드합니다.
.. 클라이언트 개인 키가 암호화된 경우 클라이언트 개인 키의 암호를 해독하기 위한 암호를 입력합니다. 그렇지 않으면 * 클라이언트 개인 키 암호 * 필드를 비워 둡니다.



NOTE: 클라이언트 인증서가 암호화될 경우 암호화에 기존 형식을 사용합니다. PKCS #8 암호화된 형식은 지원되지 않습니다.

--
.Azure Blob 저장소
--
_ Azure Blob 스토리지의 경우, 공유 키만 _

.. * 계정 이름 *: 외부 컨테이너를 소유하는 저장소 계정의 이름을 입력합니다
.. * 계정 키 *: 스토리지 계정의 비밀 키를 입력합니다


Azure 포털을 사용하여 이러한 값을 찾을 수 있습니다.

--
.익명
--
추가 정보가 필요하지 않습니다.

--
====
. Continue * 를 선택합니다. 그런 다음 사용할 서버 확인 유형을 선택합니다.
+
[cols="1a,2a"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
스토리지 노드 OS에서 루트 CA 인증서를 사용합니다
 a| 
운영 체제에 설치된 Grid CA 인증서를 사용하여 연결을 보호합니다.



 a| 
사용자 지정 CA 인증서를 사용합니다
 a| 
사용자 지정 CA 인증서를 사용합니다. 찾아보기 * 를 선택하고 PEM 인코딩된 인증서를 업로드합니다.



 a| 
인증서를 확인하지 않습니다
 a| 
이 옵션을 선택하면 클라우드 스토리지 풀에 대한 TLS 연결이 안전하지 않습니다.

|===
. 저장 * 을 선택합니다.
+
클라우드 스토리지 풀을 저장할 때 StorageGRID은 다음을 수행합니다.

+
** 버킷 또는 컨테이너와 서비스 엔드포인트가 있는지, 그리고 지정한 자격 증명을 사용하여 해당 엔드포인트에 도달할 수 있는지 검증합니다.
** 버킷이나 컨테이너에 마커 파일을 기록하여 클라우드 스토리지 풀로 식별합니다. 이름이 인 이 파일은 제거하지 마십시오 `x-ntap-sgws-cloud-pool-uuid`.
+
Cloud Storage Pool 검증이 실패하면 검증에 실패한 이유를 설명하는 오류 메시지가 표시됩니다. 예를 들어 인증서 오류가 있거나 지정한 버킷 또는 컨테이너가 이미 없는 경우 오류가 보고될 수 있습니다.



. 오류가 발생하면link:troubleshooting-cloud-storage-pools.html["클라우드 스토리지 풀 문제 해결을 위한 지침"], 문제를 해결한 다음 클라우드 스토리지 풀을 다시 저장해 보십시오.

