---
permalink: ilm/editing-cloud-storage-pool.html 
sidebar: sidebar 
keywords: edit cloud storage pool 
summary: Cloud Storage Pool을 편집하여 이름, 서비스 끝점 또는 기타 세부 정보를 변경할 수 있지만 Cloud Storage Pool의 S3 버킷 또는 Azure 컨테이너를 변경할 수는 없습니다. 
---
= 클라우드 스토리지 풀을 편집합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cloud Storage Pool을 편집하여 이름, 서비스 끝점 또는 기타 세부 정보를 변경할 수 있지만 Cloud Storage Pool의 S3 버킷 또는 Azure 컨테이너를 변경할 수는 없습니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 있습니다. link:../admin/admin-group-permissions.html["특정 액세스 권한"]
* 를 검토했습니다.link:considerations-for-cloud-storage-pools.html["클라우드 스토리지 풀에 대한 고려 사항"]


.단계
. ILM * > * 스토리지 풀 * > * 클라우드 스토리지 풀 * 을 선택합니다.
+
클라우드 스토리지 풀 테이블에는 기존 클라우드 스토리지 풀이 나열됩니다.

. 편집할 클라우드 스토리지 풀의 확인란을 선택한 다음 * Actions * > * Edit * 를 선택합니다.
+
또는 클라우드 스토리지 풀의 이름을 선택한 다음 * Edit * 를 선택합니다.

. 필요에 따라 클라우드 스토리지 풀 이름, 서비스 끝점, 인증 자격 증명 또는 인증서 확인 방법을 변경합니다.
+

NOTE: 클라우드 스토리지 풀의 공급자 유형 또는 S3 버킷 또는 Azure 컨테이너는 변경할 수 없습니다.

+
이전에 서버 또는 클라이언트 인증서를 업로드한 경우 * 인증서 세부 정보 * 아코디언을 확장하여 현재 사용 중인 인증서를 검토할 수 있습니다.

. 저장 * 을 선택합니다.
+
클라우드 스토리지 풀을 저장할 때 StorageGRID는 버킷 또는 컨테이너와 서비스 엔드포인트가 있는지 확인하고 지정한 자격 증명을 사용하여 해당 풀에 연결할 수 있는지 검증합니다.

+
Cloud Storage Pool 검증이 실패하면 오류 메시지가 표시됩니다. 예를 들어 인증서 오류가 있는 경우 오류가 보고될 수 있습니다.

+
지침을 link:troubleshooting-cloud-storage-pools.html["클라우드 스토리지 풀 문제 해결"]참조하여 문제를 해결한 다음 클라우드 스토리지 풀을 다시 저장해 보십시오.


