---
permalink: ilm/editing-storage-pool.html 
sidebar: sidebar 
keywords: edit storage pool 
summary: 스토리지 풀을 편집하여 이름을 변경하거나 사이트 및 스토리지 등급을 업데이트할 수 있습니다. 
---
= 스토리지 풀을 편집합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 풀을 편집하여 이름을 변경하거나 사이트 및 스토리지 등급을 업데이트할 수 있습니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 있습니다. link:../admin/admin-group-permissions.html["특정 액세스 권한"]
* 를 검토했습니다.link:guidelines-for-creating-storage-pools.html["스토리지 풀 생성 지침"]
* 활성 ILM 정책의 규칙에 의해 사용되는 스토리지 풀을 편집하려는 경우 변경 사항이 개체 데이터 배치에 미치는 영향을 고려했습니다.


.이 작업에 대해
활성 ILM 정책에 사용되는 스토리지 풀에 새 사이트 또는 스토리지 등급을 추가하는 경우 새 사이트 또는 스토리지 등급의 스토리지 노드가 자동으로 사용되지 않는다는 점에 유의하십시오. StorageGRID에서 새 사이트 또는 스토리지 등급을 사용하도록 강제하려면 편집된 스토리지 풀을 저장한 후 새 ILM 정책을 활성화해야 합니다.

.단계
. ILM * > * 스토리지 풀 * 을 선택합니다.
. 편집할 스토리지 풀의 확인란을 선택합니다.
+
모든 스토리지 노드 스토리지 풀(StorageGRID 11.6 이하)은 편집할 수 없습니다.

. 편집 * 을 선택합니다.
. 필요에 따라 스토리지 풀 이름을 변경합니다.
. 필요에 따라 다른 사이트 및 저장 등급을 선택합니다.
+
스토리지 풀이 삭제 코딩 프로필에 사용되는 경우 사이트 또는 스토리지 등급을 변경할 수 없으며 이로 인해 삭제 코딩 체계가 유효하지 않게 됩니다. 예를 들어, 삭제 코딩 프로필에 사용된 스토리지 풀에 현재 사이트가 하나만 있는 스토리지 등급이 포함된 경우, 이 변경 사항으로 인해 삭제 코딩 체계가 무효화되기 때문에 두 사이트에 대해 스토리지 등급을 사용할 수 없습니다.

+

CAUTION: 기존 스토리지 풀에서 사이트를 추가하거나 제거하더라도 삭제 인코딩된 데이터는 이동되지 않습니다. 사이트에서 기존 데이터를 이동하려면 새 스토리지 풀과 EC 프로필을 생성하여 데이터를 다시 인코딩해야 합니다.

. 저장 * 을 선택합니다.


.작업을 마친 후
활성 ILM 정책에 사용된 스토리지 풀에 새 사이트 또는 스토리지 성적을 추가한 경우 새 ILM 정책을 활성화하여 StorageGRID가 새 사이트 또는 스토리지 등급을 사용하도록 강제합니다. 예를 들어, 기존 ILM 정책을 클론 복제한 다음 클론을 활성화합니다. 을 link:working-with-ilm-rules-and-ilm-policies.html["ILM 규칙 및 ILM 정책 작업"]참조하십시오.
