---
permalink: ilm/example-7-compliant-ilm-policy-for-s3-object-lock.html 
sidebar: sidebar 
keywords: ILM policy,S3 Object Lock 
summary: 이 예제에서 S3 오브젝트 잠금이 활성화된 버킷의 오브젝트에 대한 오브젝트 보호 및 보존 요구사항을 충족하기 위해 ILM 정책을 정의할 때 시작 지점으로 S3 버킷, ILM 규칙 및 ILM 정책을 사용할 수 있습니다. 
---
= 예 7: S3 오브젝트 잠금에 대한 규정 준수 ILM 정책
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 예제에서 S3 오브젝트 잠금이 활성화된 버킷의 오브젝트에 대한 오브젝트 보호 및 보존 요구사항을 충족하기 위해 ILM 정책을 정의할 때 시작 지점으로 S3 버킷, ILM 규칙 및 ILM 정책을 사용할 수 있습니다.


NOTE: 이전 StorageGRID 릴리스에서 레거시 규정 준수 기능을 사용한 경우 이 예제를 사용하여 레거시 규정 준수 기능이 활성화된 기존 버킷을 관리할 수도 있습니다.


CAUTION: 다음 ILM 규칙 및 정책은 예일 뿐입니다. ILM 규칙을 구성하는 방법은 여러 가지가 있습니다. 새 정책을 활성화하기 전에 시뮬레이션하여 콘텐츠 손실을 방지하기 위한 의도대로 작동하는지 확인합니다.

.관련 정보
* link:managing-objects-with-s3-object-lock.html["S3 오브젝트 잠금으로 오브젝트 관리"]
* link:creating-ilm-policy.html["ILM 정책을 생성합니다"]




== S3 오브젝트 잠금의 버킷 및 오브젝트 예

이 예에서는 ABC의 Bank라는 S3 테넌트 계정이 테넌트 관리자를 사용하여 중요한 은행 레코드를 저장할 수 있는 S3 Object Lock이 활성화된 버킷을 만들었습니다.

[cols="2a,2a"]
|===
| 버킷 정의 | 예제 값 


 a| 
테넌트 계정 이름입니다
 a| 
ABC 은행



 a| 
버킷 이름
 a| 
은행 - 레코드



 a| 
버킷 영역
 a| 
미국 - 동부 - 1(기본값)

|===
은행 레코드 버킷에 추가된 각 오브젝트 및 오브젝트 버전은 및 `legal hold` 설정에 다음 값을 `retain-until-date` 사용합니다.

[cols="1a,2a"]
|===
| 각 개체에 대한 설정입니다 | 예제 값 


 a| 
`retain-until-date`
 a| 
"2030-12-30T23:59:59Z"(2030년 12월 30일)

각 개체 버전에는 고유한 `retain-until-date` 설정이 있습니다. 이 설정은 늘릴 수 있지만 줄일 수는 없습니다.



 a| 
`legal hold`
 a| 
"꺼짐"(적용되지 않음)

보존 기간 동안 언제든지 개체 버전에 대한 법적 지류를 설정하거나 인양할 수 있습니다. 목적물이 법적 증거 자료 보관 중인 경우에는 에 도달하였더라도 그 목적물을 삭제할 `retain-until-date` 수 없다.

|===


== S3 오브젝트 잠금에 대한 ILM 규칙 1 예: 버킷 일치를 포함하는 삭제 코딩 프로필

이 ILM 규칙 예는 Bank of ABC라는 S3 테넌트 계정에만 적용됩니다. 버킷의 모든 오브젝트를 일치시킨 다음 `bank-records` 삭제 코딩을 사용하여 6+3 삭제 코딩 프로필을 사용하여 3개의 데이터 센터 사이트에 있는 스토리지 노드에 오브젝트를 저장합니다. 이 규칙은 S3 오브젝트 잠금이 설정된 버킷의 요구 사항을 충족합니다. 즉, 인제스트 시간을 참조 시간으로 사용하여 복사본을 0일부터 영원까지 스토리지 노드에 보관합니다.

[cols="1a,2a"]
|===
| 규칙 정의 | 예제 값 


 a| 
규칙 이름
 a| 
준수 규칙: 은행 내 EC 객체 - 레코드 버킷 - ABC 은행



 a| 
테넌트 계정
 a| 
ABC 은행



 a| 
버킷 이름
 a| 
`bank-records`



 a| 
고급 필터
 a| 
객체 크기(MB)가 1보다 큽니다

* 참고: * 이 필터는 오브젝트 1MB 이하의 오브젝트에 삭제 코딩이 사용되지 않도록 합니다.

|===
[cols="1a,2a"]
|===
| 규칙 정의 | 예제 값 


 a| 
참조 시간
 a| 
수집 시간



 a| 
배치
 a| 
0일째부터 영원히



 a| 
삭제 코딩 프로필
 a| 
* 3개의 데이터 센터 사이트에서 스토리지 노드에 삭제 코딩 복사본을 생성합니다
* 6+3 삭제 코딩 방법을 사용합니다


|===


== S3 오브젝트 잠금에 대한 ILM 규칙 2 예: 비준수 규칙

이 ILM 규칙은 처음에 두 개의 복제된 오브젝트 복사본을 스토리지 노드에 저장합니다. 1년이 지나면 Cloud Storage Pool에 하나의 복사본이 영구 저장됩니다. 이 규칙은 Cloud Storage Pool을 사용하기 때문에 S3 Object Lock이 설정된 버킷의 오브젝트에는 적용되지 않고 호환되지 않습니다.

[cols="1a,2a"]
|===
| 규칙 정의 | 예제 값 


 a| 
규칙 이름
 a| 
규정을 준수하지 않는 규칙: 클라우드 스토리지 풀 사용



 a| 
테넌트 계정
 a| 
지정되지 않음



 a| 
버킷 이름
 a| 
지정되지 않았지만 S3 오브젝트 잠금(또는 레거시 규정 준수 기능)이 활성화되지 않은 버킷에만 적용됩니다.



 a| 
고급 필터
 a| 
지정되지 않음

|===
[cols="1a,2a"]
|===
| 규칙 정의 | 예제 값 


 a| 
참조 시간
 a| 
수집 시간



 a| 
배치
 a| 
* 0일째, 데이터 센터 1의 스토리지 노드에 복제된 복사본 2개를 유지하고 365일 동안 데이터 센터 2를 유지합니다
* 1년 후에는 복제된 복사본 하나를 Cloud Storage Pool에 영구 보관합니다


|===


== S3 오브젝트 잠금에 대한 ILM 규칙 3 예: 기본 규칙

이 ILM 규칙 예에서는 오브젝트 데이터를 두 데이터 센터의 스토리지 풀로 복사합니다. 이 규정 준수 규칙은 ILM 정책의 기본 규칙으로 설계되었습니다. 이 노드에는 필터가 포함되지 않으며, 비현재 참조 시간을 사용하지 않으며, S3 오브젝트 잠금이 설정된 버킷의 요구 사항을 충족합니다. 즉, Ingest를 참조 시간으로 사용하여 오브젝트 복사본 2개가 0부터 영원까지 스토리지 노드에 보관됩니다.

[cols="1a,2a"]
|===
| 규칙 정의 | 예제 값 


 a| 
규칙 이름
 a| 
기본 규정 준수 규칙: 두 개의 데이터 센터를 복사합니다



 a| 
테넌트 계정입니다
 a| 
지정되지 않음



 a| 
버킷 이름
 a| 
지정되지 않음



 a| 
고급 필터
 a| 
지정되지 않음

|===
[cols="1a,2a"]
|===
| 규칙 정의 | 예제 값 


 a| 
참조 시간
 a| 
수집 시간



 a| 
배치
 a| 
0일째부터 영구, 복제된 복사본 두 개 유지 - 하나는 데이터 센터 1의 스토리지 노드에, 다른 하나는 데이터 센터 2의 스토리지 노드에 있습니다.

|===


== S3 오브젝트 잠금에 대한 규정 준수 ILM 정책 예

S3 Object Lock이 설정된 버킷에 포함된 개체를 포함하여 시스템의 모든 개체를 효과적으로 보호하는 ILM 정책을 생성하려면 모든 개체의 스토리지 요구사항을 충족하는 ILM 규칙을 선택해야 합니다. 그런 다음 정책을 시뮬레이션하고 활성화해야 합니다.



=== 정책에 규칙을 추가합니다

이 예에서 ILM 정책에는 다음 순서로 세 가지 ILM 규칙이 포함되어 있습니다.

. S3 오브젝트 잠금이 활성화된 특정 버킷에서 삭제 코딩을 사용하여 1MB 이상의 오브젝트를 보호하는 규정 준수 규칙입니다. 오브젝트는 0일부터 영원까지 스토리지 노드에 저장됩니다.
. 1년 동안 스토리지 노드에 2개의 복제된 오브젝트 복사본을 생성한 다음 하나의 오브젝트 복사본을 클라우드 스토리지 풀로 영구적으로 이동하는 규정을 준수하지 않습니다. 이 규칙은 클라우드 스토리지 풀을 사용하기 때문에 S3 오브젝트 잠금이 설정된 버킷에는 적용되지 않습니다.
. 스토리지 노드에 복제된 오브젝트 복사본 2개를 생성하는 기본 규정 준수 규칙입니다.




=== 정책을 시뮬레이션합니다

정책에 규칙을 추가하고 기본 준수 규칙을 선택하고 다른 규칙을 정렬한 후에는 S3 오브젝트 잠금이 설정된 상태로 버킷에서 오브젝트를 테스트하여 정책을 시뮬레이션해야 합니다. 예를 들어, 예제 정책을 시뮬레이션할 때 테스트 개체는 다음과 같이 평가됩니다.

* 첫 번째 규칙은 Bank of ABC Tenant의 버킷 뱅크 레코드에 1MB보다 큰 테스트 오브젝트만 일치시킵니다.
* 두 번째 규칙은 다른 모든 테넌트 계정에 대해 모든 비준수 버킷의 모든 오브젝트를 일치시킵니다.
* 기본 규칙은 다음 개체와 일치합니다.
+
** BANK BANK BANK BANK에서 객체 1MB 이하 - BANC 테넌트의 레코드
** 다른 모든 테넌트 계정에 대해 S3 Object Lock이 활성화된 다른 버킷의 오브젝트






=== 정책을 활성화합니다

새 정책이 예상대로 개체 데이터를 보호한다고 완전히 만족할 경우 이를 활성화할 수 있습니다.
