---
permalink: ilm/how-object-retention-is-determined.html 
sidebar: sidebar 
keywords: how object retention is determined 
summary: StorageGRID는 그리드 관리자와 개별 테넌트 사용자 모두에게 개체 저장 기간을 지정할 수 있는 옵션을 제공합니다. 일반적으로 테넌트 사용자가 제공한 보존 지침은 그리드 관리자가 제공한 보존 지침보다 우선합니다. 
---
= 개체 보존이 결정되는 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID는 그리드 관리자와 개별 테넌트 사용자 모두에게 개체 저장 기간을 지정할 수 있는 옵션을 제공합니다. 일반적으로 테넌트 사용자가 제공한 보존 지침은 그리드 관리자가 제공한 보존 지침보다 우선합니다.



== 테넌트 사용자가 객체 보존을 제어하는 방식

테넌트 사용자는 다음 방법을 사용하여 개체가 StorageGRID에 저장되는 기간을 제어할 수 있습니다.

* 그리드에 대해 글로벌 S3 오브젝트 잠금 설정이 활성화된 경우 S3 테넌트 사용자는 S3 오브젝트 잠금이 활성화된 상태로 버킷을 생성한 다음 각 버킷에 대해 * 기본 보존 기간 * 을 선택할 수 있습니다.
* 그리드에 글로벌 S3 오브젝트 잠금 설정이 활성화된 경우 S3 테넌트 사용자는 S3 오브젝트 잠금이 활성화된 버킷을 생성한 다음 S3 REST API를 사용하여 해당 버킷에 추가된 각 오브젝트 버전에 대한 보관 기한 및 법적 보류 설정을 지정할 수 있습니다.
+
** 법적 증거 자료 보관 중인 개체 버전은 어떤 방법으로도 삭제할 수 없습니다.
** 개체 버전의 보존 기한 에 도달하기 전에 어떤 방법으로도 해당 버전을 삭제할 수 없습니다.
** S3 오브젝트 잠금이 설정된 버킷의 오브젝트는 ILM이 "영구"로 유지합니다. 그러나 보존 기한에 도달한 후에는 클라이언트 요청 또는 버킷 라이프사이클의 만료에 의해 오브젝트 버전을 삭제할 수 있습니다. 을 link:managing-objects-with-s3-object-lock.html["S3 오브젝트 잠금으로 오브젝트 관리"]참조하십시오.


* S3 테넌트 사용자는 만료 작업을 지정하는 버킷에 라이프사이클 구성을 추가할 수 있습니다. 버킷 라이프사이클이 있는 경우 StorageGRID는 클라이언트가 먼저 오브젝트를 삭제하지 않는 한 만료 작업에 지정된 날짜 또는 일 수가 충족될 때까지 오브젝트를 저장합니다. 을 link:../s3/create-s3-lifecycle-configuration.html["S3 라이프사이클 구성을 생성합니다"]참조하십시오.
* S3 클라이언트에서 객체 삭제 요청을 실행할 수 있습니다. StorageGRID는 항상 S3 버킷 라이프사이클 또는 ILM을 통해 클라이언트 삭제 요청의 우선순위를 지정하고 오브젝트를 삭제 또는 보존 할 것인지 결정합니다.




== 그리드 관리자가 개체 보존을 제어하는 방법

그리드 관리자는 다음 방법을 사용하여 객체 보존을 제어할 수 있습니다.

* 각 테넌트의 S3 오브젝트 잠금 최대 보존 기간을 설정합니다. 그런 다음 테넌트 사용자는 각 버킷에 대해 기본 보존 기간을 설정할 수 있습니다. 최대 보존 기간은 해당 버킷에 대해 새로 수집된 객체(객체의 유지 종료 날짜)에도 적용됩니다.
* ILM 배치 지침을 생성하여 개체 저장 기간을 제어합니다. ILM 규칙에 따라 오브젝트가 일치하는 경우 StorageGRID는 ILM 규칙의 마지막 기간이 경과할 때까지 해당 오브젝트를 저장합니다. 배치 명령에 "영구"가 지정된 경우 객체는 무기한 유지됩니다.
* 누가 오브젝트 보존 기간을 제어하든 ILM 설정은 저장되는 오브젝트 복사본(복제 또는 삭제 코딩)과 복사본의 위치(스토리지 노드 또는 클라우드 스토리지 풀)를 제어합니다.




== S3 버킷 수명 주기와 ILM이 상호 작용하는 방식

S3 버킷 라이프사이클이 구성된 경우 라이프사이클 만료 작업이 라이프사이클 필터와 일치하는 오브젝트에 대한 ILM 정책을 재정의합니다. 따라서 개체를 배치하기 위한 ILM 명령이 만료된 후에도 개체가 그리드에 유지될 수 있습니다.



== 오브젝트 보존의 예

S3 오브젝트 잠금, 버킷 수명 주기 설정, 클라이언트 삭제 요청 및 ILM 간의 상호 작용을 더 잘 이해하려면 다음 예제를 고려해 보십시오.



=== 예 1: S3 버킷 수명 주기는 ILM보다 개체를 더 오래 유지합니다

ILM을 참조하십시오:: 1년(365일) 동안 2부 보관
버킷 수명 주기:: 2년 후 개체 만료(730일)
결과:: StorageGRID 는 개체를 730일 동안 저장합니다. StorageGRID는 버킷 수명 주기 설정을 사용하여 오브젝트를 삭제 또는 유지할지 여부를 결정합니다.



NOTE: 버킷 라이프사이클에서 ILM에서 지정한 것보다 더 오래 개체를 유지해야 한다고 지정하는 경우 StorageGRID는 저장할 복사본의 수와 유형을 결정할 때 ILM 배치 지침을 계속 사용합니다. 이 예제에서는 두 개의 개체 복사본이 StorageGRID에 계속 저장됩니다. 이 기간은 366일에서 730일입니다.



=== 예 2: S3 버킷 라이프사이클이 ILM 전에 오브젝트를 만기합니다

ILM을 참조하십시오:: 2년(730일) 동안 2부 보관
버킷 수명 주기:: 1년 후 개체 만료(365일)
결과:: StorageGRID에서는 365일 이후에 개체의 복사본을 모두 삭제합니다.




=== 예 3: 클라이언트 삭제는 버킷 수명 주기와 ILM을 재정의합니다

ILM을 참조하십시오:: 스토리지 노드에 "영구" 복사본 2개 저장
버킷 수명 주기:: 2년 후 개체 만료(730일)
클라이언트 삭제 요청:: 400일째 발행
결과:: StorageGRID는 클라이언트 삭제 요청에 대한 응답으로 400일째에 두 객체 복제본을 모두 삭제합니다.




=== 예 4: S3 오브젝트 잠금이 클라이언트 삭제 요청을 재정의합니다

S3 오브젝트 잠금:: 개체 버전에 대한 보존 기한은 2026-03-31입니다. 법적 증거 자료 보관 은 적용되지 않습니다.
ILM 규칙 준수:: 스토리지 노드에 "영구" 복사본 2개 저장
클라이언트 삭제 요청:: 2024-03-31일에 발행되었습니다
결과:: 보존 기한이 2년 남지 않았으므로 StorageGRID는 개체 버전을 삭제하지 않습니다.

