---
permalink: ilm/manage-ilm-policy-tags.html 
sidebar: sidebar 
keywords: ILM policy tag 
summary: ILM 정책 태그 세부 정보를 보거나 태그를 편집하거나 태그를 제거할 수 있습니다. 
---
= ILM 정책 태그를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM 정책 태그 세부 정보를 보거나 태그를 편집하거나 태그를 제거할 수 있습니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:../admin/admin-group-permissions.html["액세스 권한이 필요합니다"]있습니다.




== ILM 정책 태그 세부 정보를 봅니다

태그에 대한 세부 정보를 보려면:

. ILM * > * 정책 태그 * 를 선택합니다.
. 테이블에서 정책 이름을 선택합니다. 태그에 대한 세부 정보 페이지가 나타납니다.
. 세부 정보 페이지에서 할당된 정책의 이전 기록을 봅니다.
. 정책을 선택하여 봅니다.




== ILM 정책 태그를 편집합니다


NOTE: Tenant에서 태그 이름과 설명을 볼 수 있습니다. 테넌트가 버킷에 할당할 정책 태그를 선택할 때 정보에 입각한 결정을 내리는 데 도움이 되는 값을 선택합니다. 예를 들어, 할당된 정책이 일정 시간이 지난 후 개체를 삭제하는 경우 설명에 해당 정보를 전달할 수 있습니다. 이러한 필드에는 중요한 정보를 포함하지 마십시오.

기존 태그에 대한 설명을 편집하려면:

. ILM * > * 정책 태그 * 를 선택합니다.
. 태그 확인란을 선택한 다음 * 편집 * 을 선택합니다.
+
또는 태그 이름을 선택합니다. 태그에 대한 세부 정보 페이지가 나타나고 해당 페이지에서 * 편집 * 을 선택할 수 있습니다.

. 필요에 따라 태그 설명을 변경합니다
. 저장 * 을 선택합니다.




== ILM 정책 태그를 제거합니다

정책 태그를 제거하면 해당 태그가 지정된 모든 버킷에 기본 정책이 적용됩니다.

태그 제거하기:

. ILM * > * 정책 태그 * 를 선택합니다.
. 태그 확인란을 선택한 다음 * 제거 * 를 선택합니다. 확인 대화 상자가 나타납니다.
+
또는 태그 이름을 선택합니다. 태그에 대한 세부 정보 페이지가 나타나고 해당 페이지에서 * 제거 * 를 선택할 수 있습니다.

. 태그를 삭제하려면 * Yes * 를 선택합니다.


.관련 정보
link:creating-ilm-policy.html#activate-ilm-policy["ILM 정책 태그 생성에 대해 알아보세요"]
