---
permalink: ilm/managing-objects-with-s3-object-lock.html 
sidebar: sidebar 
keywords: s3 object lock, manage objects with object lock 
summary: 그리드 관리자는 StorageGRID 시스템에 S3 오브젝트 잠금을 설정하고 호환되는 ILM 정책을 구현하여 특정 S3 버킷의 오브젝트가 지정된 시간 동안 삭제 또는 덮어쓰지 않도록 할 수 있습니다. 
---
= S3 오브젝트 잠금으로 오브젝트 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리자는 StorageGRID 시스템에 S3 오브젝트 잠금을 설정하고 호환되는 ILM 정책을 구현하여 특정 S3 버킷의 오브젝트가 지정된 시간 동안 삭제 또는 덮어쓰지 않도록 할 수 있습니다.



== S3 오브젝트 잠금이란 무엇입니까?

StorageGRID S3 오브젝트 잠금 기능은 Amazon S3(Amazon Simple Storage Service)의 S3 오브젝트 잠금과 동등한 오브젝트 보호 솔루션입니다.

StorageGRID 시스템에 대해 글로벌 S3 오브젝트 잠금 설정이 활성화된 경우 S3 테넌트 계정에서 S3 오브젝트 잠금이 활성화되어 있거나 사용되지 않고 버킷을 생성할 수 있습니다. 버킷에 S3 오브젝트 잠금이 활성화된 경우 버킷 버전 관리가 필요하며 자동으로 활성화됩니다.

*S3 오브젝트 잠금이 없는 버킷은 보존 설정이 지정되지 않은 오브젝트만 가질 수 있습니다. 수집된 객체에는 보존 설정이 없습니다.

* S3 오브젝트 잠금이 있는 버킷은 S3 클라이언트 애플리케이션에 지정된 보존 설정이 있거나 없는 객체를 포함할 수 있습니다. 수집된 일부 객체에는 보존 설정이 있습니다.

* S3 오브젝트 잠금 및 기본 보존이 구성된 버킷 * 은 보존 설정이 지정된 객체와 보존 설정이 없는 새 객체를 업로드할 수 있습니다. 개체 수준에서 보존 설정이 구성되지 않았기 때문에 새 개체는 기본 설정을 사용합니다.

기본적으로 보존이 구성되면 새로 수집된 모든 객체에 보존 설정이 적용됩니다. 개체 보존 설정이 없는 기존 개체는 영향을 받지 않습니다.



=== 보존 모드

StorageGRID S3 오브젝트 잠금 기능은 두 가지 보존 모드를 지원하여 오브젝트에 다양한 보호 수준을 적용합니다. 이러한 모드는 Amazon S3 보존 모드에 해당합니다.

* 규정 준수 모드:
+
** 보존 기한 에 도달할 때까지 개체를 삭제할 수 없습니다.
** 오브젝트의 보존 기한 을 늘릴 수 있지만 줄일 수는 없습니다.
** 개체의 보존 기한 은 해당 날짜에 도달할 때까지 제거할 수 없습니다.


* 거버넌스 모드:
+
** 특수 권한이 있는 사용자는 요청에서 우회 헤더를 사용하여 특정 보존 설정을 수정할 수 있습니다.
** 이러한 사용자는 보존 기한이 되기 전에 개체 버전을 삭제할 수 있습니다.
** 이러한 사용자는 개체의 보존 기간(Retain-until-date)을 증가, 감소 또는 제거할 수 있습니다.






=== 개체 버전에 대한 보존 설정입니다

버킷이 S3 오브젝트 잠금이 설정된 상태로 생성된 경우 사용자는 S3 클라이언트 애플리케이션을 사용하여 버킷에 추가되는 각 오브젝트에 대해 다음 보존 설정을 선택적으로 지정할 수 있습니다.

* * 보존 모드 *: 규정 준수 또는 거버넌스 중 하나입니다.
* * Retain-until-date *: 개체 버전의 Retain-until-date가 미래인 경우 개체를 검색할 수 있지만 삭제할 수 없습니다.
* * 법적 증거 자료 보관 *: 개체 버전에 법적 증거 자료 보관 기능을 적용하면 해당 개체가 즉시 잠깁니다. 예를 들어 조사 또는 법적 분쟁과 관련된 객체에 법적 보류를 지정해야 할 수 있습니다. 법적 보류는 만료 날짜가 없지만 명시적으로 제거될 때까지 유지됩니다. 법적 보류는 보존 기한 과 무관합니다.
+

NOTE: 개체가 법적 보류 중인 경우 보존 모드에 관계없이 개체를 삭제할 수 없습니다.

+
개체 설정에 대한 자세한 내용은 을 참조하십시오link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 오브젝트 잠금을 구성합니다"].





=== 버킷을 위한 기본 보존 설정입니다

버킷이 S3 오브젝트 잠금이 활성화된 상태로 생성된 경우 사용자는 버킷에 대해 다음 기본 설정을 선택적으로 지정할 수 있습니다.

* * 기본 보존 모드 *: 규정 준수 또는 거버넌스 중 하나입니다.
* * 기본 보존 기간 *: 이 버킷에 추가된 새 오브젝트 버전이 추가되는 날부터 보존되어야 하는 기간입니다.


기본 버킷 설정은 고유한 보존 설정이 없는 새 오브젝트에만 적용됩니다. 이러한 기본 설정을 추가하거나 변경할 때 기존 버킷 개체는 영향을 받지 않습니다.

link:../tenant/creating-s3-bucket.html["S3 버킷을 생성합니다"]및 을 link:../tenant/update-default-retention-settings.html["S3 오브젝트 잠금 기본 보존 업데이트"]참조하십시오.



== S3 오브젝트 잠금을 레거시 규정 준수와 비교합니다

S3 오브젝트 잠금은 이전 StorageGRID 버전에서 사용할 수 있었던 규정 준수 기능을 대체합니다. S3 오브젝트 잠금 기능은 Amazon S3 요구사항을 준수하므로 "레거시 규정 준수"라고 하는 독점적인 StorageGRID 규정 준수 기능이 더 이상 사용되지 않습니다.


NOTE: 글로벌 규정 준수 설정은 더 이상 사용되지 않습니다. 이전 버전의 StorageGRID를 사용하여 이 설정을 활성화하면 S3 오브젝트 잠금 설정이 자동으로 활성화됩니다. StorageGRID를 계속 사용하여 기존 준수 버킷의 설정을 관리할 수 있지만 새로운 준수 버킷을 생성할 수는 없습니다. 자세한 내용은 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp 기술 자료: StorageGRID 11.5에서 레거시 준수 버킷을 관리하는 방법"^].

이전 버전의 StorageGRID에서 레거시 규정 준수 기능을 사용한 경우 다음 표를 참조하여 StorageGRID의 S3 오브젝트 잠금 기능과 어떻게 다른지 알아보십시오.

[cols="1a,1a,1a"]
|===
|  | S3 오브젝트 잠금 | 규정 준수(레거시) 


 a| 
이 기능은 전역적으로 어떻게 활성화됩니까?
 a| 
그리드 관리자에서 *구성* > *시스템* > *S3 객체 잠금*을 선택합니다.
 a| 
더 이상 지원되지 않습니다.



 a| 
버킷에 대한 기능은 어떻게 활성화됩니까?
 a| 
사용자는 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 새 버킷을 생성할 때 S3 오브젝트 잠금을 활성화해야 합니다.
 a| 
더 이상 지원되지 않습니다.



 a| 
버킷 버전 관리가 지원됩니까?
 a| 
예. 버킷에 대해 S3 오브젝트 잠금이 활성화된 경우 버킷 버전 관리가 필요하며 자동으로 활성화됩니다.
 a| 
아니요



 a| 
개체 보존은 어떻게 설정됩니까?
 a| 
사용자는 각 오브젝트 버전에 대해 보존 기간을 설정하거나 각 버킷에 대한 기본 보존 기간을 설정할 수 있습니다.
 a| 
사용자는 전체 버킷의 보존 기간을 설정해야 합니다. 보존 기간은 버킷의 모든 객체에 적용됩니다.



 a| 
보존 기간을 변경할 수 있습니까?
 a| 
* 규정 준수 모드에서는 오브젝트 버전의 보존 기간을 늘릴 수 있지만 줄일 수는 없습니다.
* 거버넌스 모드에서 특수 권한이 있는 사용자는 개체의 보존 설정을 줄이거나 제거할 수도 있습니다.

 a| 
버킷의 보존 기간은 늘릴 수 있지만 줄일 수는 없습니다.



 a| 
법적 보류가 통제되는 곳은 어디입니까?
 a| 
사용자는 법적 증거 자료 보관 또는 버킷의 모든 개체 버전에 대한 법적 증거 자료 보관 장치를 들어 올릴 수 있습니다.
 a| 
법적 구속이 버킷에 배치되어 버킷의 모든 물체에 영향을 미칩니다.



 a| 
언제 오브젝트를 삭제할 수 있습니까?
 a| 
* 규정 준수 모드에서는 개체가 법적 증거 자료 보관 상태에 있지 않은 경우, 보존 기한이 만료된 후에도 개체 버전을 삭제할 수 있습니다.
* 거버넌스 모드에서 특수 권한이 있는 사용자는 개체가 법적 증거 자료 보관 상태에 있지 않은 경우 보존 기한이 되기 전에 개체를 삭제할 수 있습니다.

 a| 
버킷이 법적 증거 자료 보관 중이 아닌 경우, 보존 기간이 만료된 후에는 오브젝트를 삭제할 수 있습니다. 개체를 자동으로 또는 수동으로 삭제할 수 있습니다.



 a| 
버킷 라이프사이클 구성이 지원됩니까?
 a| 
예
 a| 
아니요

|===