---
permalink: ilm/removing-cloud-storage-pool.html 
sidebar: sidebar 
keywords: remove cloud storage pool 
summary: ILM 규칙에 사용되지 않고 오브젝트 데이터가 없는 경우 클라우드 스토리지 풀을 제거할 수 있습니다. 
---
= 클라우드 스토리지 풀을 제거합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM 규칙에 사용되지 않고 오브젝트 데이터가 없는 경우 클라우드 스토리지 풀을 제거할 수 있습니다.

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:../admin/admin-group-permissions.html["액세스 권한이 필요합니다"]있습니다.




== 필요한 경우 ILM을 사용하여 오브젝트 데이터를 이동합니다

제거하려는 Cloud Storage Pool에 오브젝트 데이터가 포함된 경우 ILM을 사용하여 데이터를 다른 위치로 이동해야 합니다. 예를 들어 데이터를 그리드의 스토리지 노드 또는 다른 클라우드 스토리지 풀로 이동할 수 있습니다.

.단계
. ILM * > * 스토리지 풀 * > * 클라우드 스토리지 풀 * 을 선택합니다.
. 표에서 ILM 사용 열을 확인하여 클라우드 스토리지 풀을 제거할 수 있는지 확인합니다.
+
클라우드 스토리지 풀을 ILM 규칙 또는 삭제 코딩 프로필에 사용 중인 경우에는 제거할 수 없습니다.

. 클라우드 스토리지 풀을 사용 중인 경우 *_cloud 스토리지 풀 이름_ * > * ILM 사용량 * 을 선택합니다.
. link:working-with-ilm-rules-and-ilm-policies.html["각 ILM 규칙을 복제합니다"] 현재 제거할 클라우드 스토리지 풀에 객체가 배치됩니다.
. 복제한 각 규칙에 의해 관리되는 기존 개체를 이동할 위치를 결정합니다.
+
하나 이상의 스토리지 풀 또는 다른 클라우드 스토리지 풀을 사용할 수 있습니다.

. 복제한 각 규칙을 편집합니다.
+
ILM 규칙 생성 마법사의 2단계에 대해 * copies at * 필드에서 새 위치를 선택합니다.

. link:creating-ilm-policy.html["새 ILM 정책을 생성합니다"] 이전 규칙을 각각 복제된 규칙으로 바꿉니다.
. 새 정책을 활성화합니다.
. ILM이 클라우드 스토리지 풀에서 개체를 제거하고 새 위치에 놓을 때까지 기다립니다.




== 클라우드 스토리지 풀을 삭제합니다

Cloud Storage Pool이 비어 있고 ILM 규칙에 사용되지 않는 경우 삭제할 수 있습니다.

.시작하기 전에
* 풀을 사용했을 수 있는 ILM 규칙을 제거했습니다.
* S3 버킷 또는 Azure 컨테이너에 오브젝트가 포함되지 않음을 확인했습니다.
+
클라우드 스토리지 풀에 객체가 포함된 경우 해당 풀을 제거하려고 하면 오류가 발생합니다. 을 link:troubleshooting-cloud-storage-pools.html["클라우드 스토리지 풀 문제 해결"]참조하십시오.

+

NOTE: 클라우드 스토리지 풀을 생성할 때 StorageGRID은 마커 파일을 버킷 또는 컨테이너에 작성하여 클라우드 스토리지 풀로 식별합니다. 이름이 인 이 파일은 제거하지 `x-ntap-sgws-cloud-pool-uuid`마십시오.



.단계
. ILM * > * 스토리지 풀 * > * 클라우드 스토리지 풀 * 을 선택합니다.
. ILM 사용 열에 클라우드 스토리지 풀이 사용되지 않고 있다고 표시되면 확인란을 선택합니다.
. Actions * > * Remove * 를 선택합니다.
. OK * 를 선택합니다.

