---
permalink: ilm/requirements-for-s3-object-lock.html 
sidebar: sidebar 
keywords: requirements, s3 object lock, compliant ilm rule, compliant ilm policy 
summary: 글로벌 S3 오브젝트 잠금 설정을 사용하기 위한 요구사항, 호환되는 ILM 규칙 및 ILM 정책을 만들기 위한 요구사항 및 StorageGRID가 S3 오브젝트 잠금을 사용하는 버킷과 오브젝트에 배치하는 제한을 검토해야 합니다. 
---
= S3 오브젝트 잠금에 대한 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
글로벌 S3 오브젝트 잠금 설정을 사용하기 위한 요구사항, 호환되는 ILM 규칙 및 ILM 정책을 만들기 위한 요구사항 및 StorageGRID가 S3 오브젝트 잠금을 사용하는 버킷과 오브젝트에 배치하는 제한을 검토해야 합니다.



== 전역 S3 오브젝트 잠금 설정 사용 요구 사항

* S3 테넌트가 S3 오브젝트 잠금이 활성화된 버킷을 생성하려면 먼저 그리드 관리자 또는 그리드 관리 API를 사용하여 글로벌 S3 오브젝트 잠금 설정을 활성화해야 합니다.
* 글로벌 S3 오브젝트 잠금 설정을 활성화하면 모든 S3 테넌트 계정에서 S3 오브젝트 잠금이 설정된 버킷을 생성할 수 있습니다.
* 전역 S3 오브젝트 잠금 설정을 활성화한 후에는 설정을 비활성화할 수 없습니다.
* 모든 활성 ILM 정책의 기본 규칙이 _compliant_(즉, 기본 규칙이 S3 오브젝트 잠금이 설정된 버킷 요구사항을 준수해야 함)가 아니면 글로벌 S3 오브젝트 잠금을 활성화할 수 없습니다.
* 글로벌 S3 오브젝트 잠금 설정을 사용하는 경우 정책의 기본 규칙이 준수되지 않는 한 새 ILM 정책을 생성하거나 기존 ILM 정책을 활성화할 수 없습니다. 전역 S3 개체 잠금 설정이 활성화된 후 ILM 규칙 및 ILM 정책 페이지는 어떤 ILM 규칙이 준수되는지 나타냅니다.




== 규정 준수 ILM 규칙 요구 사항

글로벌 S3 오브젝트 잠금 설정을 사용하려면 모든 활성 ILM 정책의 기본 규칙이 준수되는지 확인해야 합니다. 규정 준수 규칙은 S3 오브젝트 잠금이 활성화된 두 버킷의 요구 사항과 레거시 규정 준수가 활성화된 기존 버킷의 요구 사항을 모두 충족합니다.

* 복제된 오브젝트 복사본 2개 이상 또는 삭제 코딩 복사본 1개를 생성해야 합니다.
* 이러한 복제본은 배치 지침에서 각 행의 전체 기간 동안 스토리지 노드에 있어야 합니다.
* 오브젝트 복사본은 클라우드 스토리지 풀에 저장할 수 없습니다.
* 최소 한 줄의 배치 지침은 * Ingest Time * 을 기준 시간으로 사용하여 0일에 시작해야 합니다.
* 배치 지침의 최소 한 줄은 "영구"여야 합니다.




== ILM 정책 요구 사항

글로벌 S3 오브젝트 잠금 설정이 활성화되면 활성 및 비활성 ILM 정책에 준수 규칙과 비준수 규칙이 모두 포함될 수 있습니다.

* 활성 또는 비활성 ILM 정책의 기본 규칙은 준수해야 합니다.
* 비준수 규칙은 S3 오브젝트 잠금이 활성화되지 않았거나 레거시 규정 준수 기능이 활성화되지 않은 버킷의 오브젝트에만 적용됩니다.
* 규정 준수 규칙은 모든 버킷의 오브젝트에 적용할 수 있습니다. 버킷에 대해 S3 오브젝트 잠금이나 레거시 규정 준수를 활성화할 필요는 없습니다.


link:example-7-compliant-ilm-policy-for-s3-object-lock.html["S3 오브젝트 잠금에 대한 규정 준수 ILM 정책의 예"]



== S3 오브젝트 잠금이 설정된 버킷의 요구 사항

* StorageGRID 시스템에 대해 글로벌 S3 오브젝트 잠금 설정이 활성화된 경우 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 S3 오브젝트 잠금이 활성화된 버킷을 생성할 수 있습니다.
* S3 오브젝트 잠금을 사용하려는 경우 버킷을 생성할 때 S3 오브젝트 잠금을 활성화해야 합니다. 기존 버킷에 S3 오브젝트 잠금을 설정할 수 없습니다.
* 버킷에 대해 S3 오브젝트 잠금이 활성화된 경우 StorageGRID는 해당 버킷의 버전 관리를 자동으로 활성화합니다. 버킷의 S3 오브젝트 잠금을 비활성화하거나 버전 관리를 일시 중단할 수 없습니다.
* 필요에 따라 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 각 버킷의 기본 보존 모드 및 보존 기간을 지정할 수 있습니다. 버킷의 기본 보존 설정은 고유한 보존 설정이 없는 버킷에 추가된 새 오브젝트에만 적용됩니다. 이 기본 설정은 업로드할 때 각 개체 버전에 대해 보존 모드 및 보존 종료 날짜를 지정하여 재정의할 수 있습니다.
* S3 오브젝트 잠금이 설정된 버킷에 대해 버킷 라이프사이클 구성이 지원됩니다.
* S3 오브젝트 잠금이 설정된 버킷에는 CloudMirror 복제가 지원되지 않습니다.




== S3 오브젝트 잠금이 설정된 버킷의 오브젝트 요구사항

* 개체 버전을 보호하려면 버킷의 기본 보존 설정을 지정하거나 각 오브젝트 버전에 대한 보존 설정을 지정할 수 있습니다. 오브젝트 레벨의 보존 설정은 S3 클라이언트 애플리케이션 또는 S3 REST API를 사용하여 지정할 수 있습니다.
* 보존 설정은 개별 개체 버전에 적용됩니다. 개체 버전에는 보존 기한 및 법적 보류 설정이 둘 다 있을 수 있으며, 둘 중 하나만 설정할 수도 있고 둘 다 가질 수도 없습니다. 개체에 대한 보존 기한 또는 법적 보류 설정을 지정하면 요청에 지정된 버전만 보호됩니다. 이전 버전의 개체는 잠겨 있는 상태에서 새 버전의 개체를 만들 수 있습니다.




== S3 오브젝트 잠금이 설정된 버킷의 오브젝트 라이프사이클

S3 오브젝트 잠금이 설정된 버킷에 저장된 각 오브젝트는 다음 단계를 거칩니다.

. * 오브젝트 수집 *
+
오브젝트 버전이 S3 오브젝트 잠금이 설정된 버킷에 추가되면 보존 설정이 다음과 같이 적용됩니다.

+
** 개체에 대한 보존 설정이 지정된 경우 개체 수준 설정이 적용됩니다. 기본 버킷 설정은 무시됩니다.
** 개체에 대해 보존 설정을 지정하지 않으면 기본 버킷 설정이 적용됩니다(있는 경우).
** 오브젝트 또는 버킷에 대해 보존 설정을 지정하지 않으면 S3 오브젝트 잠금으로 오브젝트가 보호되지 않습니다.


+
보존 설정이 적용되는 경우 오브젝트와 S3 사용자 정의 메타데이터는 모두 보호됩니다.

. * 개체 보존 및 삭제 *
+
StorageGRID는 지정된 보존 기간 동안 보호된 각 개체의 복사본을 여러 개 저장합니다. 오브젝트 복사본 및 스토리지 위치의 정확한 수와 유형은 활성 ILM 정책의 규정 준수 규칙에 따라 결정됩니다. 보존 기한이 되기 전에 보호된 개체를 삭제할 수 있는지 여부는 보존 모드에 따라 다릅니다.

+
** 개체가 법적 보류 중인 경우 보존 모드에 관계없이 개체를 삭제할 수 없습니다.




.관련 정보
* link:../tenant/creating-s3-bucket.html["S3 버킷을 생성합니다"]
* link:../tenant/update-default-retention-settings.html["S3 오브젝트 잠금 기본 보존 업데이트"]
* link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 오브젝트 잠금을 구성합니다"]
* link:example-7-compliant-ilm-policy-for-s3-object-lock.html["예 7: S3 오브젝트 잠금에 대한 규정 준수 ILM 정책"]

