---
permalink: ilm/troubleshooting-cloud-storage-pools.html 
sidebar: sidebar 
keywords: cloud storage pool, troubleshoot 
summary: 클라우드 스토리지 풀을 생성, 편집 또는 삭제할 때 발생할 수 있는 오류를 해결하려면 다음 문제 해결 단계를 사용하십시오. 
---
= 클라우드 스토리지 풀 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클라우드 스토리지 풀을 생성, 편집 또는 삭제할 때 발생할 수 있는 오류를 해결하려면 다음 문제 해결 단계를 사용하십시오.



== 오류가 발생했는지 확인합니다

StorageGRID는 알려진 개체를 읽어 모든 클라우드 스토리지 풀에 대한 간단한 상태 점검을 수행하여 클라우드 스토리지 풀에 `x-ntap-sgws-cloud-pool-uuid` 액세스할 수 있고 올바르게 작동하는지 확인합니다. StorageGRID는 엔드포인트에서 오류가 발생하면 각 스토리지 노드에서 1분마다 상태 점검을 수행합니다. 오류가 해결되면 상태 검사가 중지됩니다. 상태 검사에서 문제가 감지되면 스토리지 풀 페이지의 클라우드 스토리지 풀 테이블의 마지막 오류 열에 메시지가 표시됩니다.

이 표에는 각 클라우드 스토리지 풀에 대해 감지된 가장 최근 오류가 표시되며 오류가 발생한 시간이 표시됩니다.

또한, 상태 점검 시 지난 5분 내에 하나 이상의 새 Cloud Storage Pool 오류가 발생한 것을 감지하면 * Cloud Storage Pool connectivity error * 경고가 트리거됩니다. 이 알림에 대한 e-메일 알림을 받으면 스토리지 풀 페이지(* ILM * > * 스토리지 풀 * 선택)로 이동하여 마지막 오류 열의 오류 메시지를 검토하고 아래의 문제 해결 지침을 참조하십시오.



== 오류가 해결되었는지 확인합니다

근본적인 문제를 해결한 후 오류가 해결되었는지 확인할 수 있습니다. 클라우드 스토리지 풀 페이지에서 엔드포인트를 선택하고 * 오류 지우기 * 를 선택합니다. 확인 메시지는 StorageGRID에서 클라우드 스토리지 풀에 대한 오류를 제거했음을 나타냅니다.

기본 문제가 해결된 경우 오류 메시지가 더 이상 표시되지 않습니다. 그러나 기본 문제가 해결되지 않았거나 다른 오류가 발생한 경우 몇 분 내에 마지막 오류 열에 오류 메시지가 표시됩니다.



== 오류: 상태를 확인하지 못했습니다. 끝점에서 오류가 발생했습니다

이 버킷을 클라우드 스토리지 풀에 사용하기 시작한 후 Amazon S3 버킷에 대해 기본 보존으로 S3 오브젝트 잠금을 설정하면 이 오류가 발생할 수 있습니다. 이 오류는 PUT 작업에 과 같은 페이로드 체크섬 값을 가진 HTTP 헤더가 없을 때 `Content-MD5` 발생합니다. 이 헤더 값은 S3 오브젝트 잠금이 설정된 버킷으로 작업을 수행하는 데 AWS에서 필요합니다.

이 문제를 해결하려면 변경하지 않고 의 단계를 link:editing-cloud-storage-pool.html["클라우드 스토리지 풀을 편집합니다"]수행하십시오. 이 작업은 클라우드 스토리지 풀 엔드포인트 구성에서 S3 오브젝트 잠금 플래그를 자동으로 감지하고 업데이트하는 클라우드 스토리지 풀 구성의 검증을 트리거합니다.



== 오류: 이 클라우드 스토리지 풀에 예기치 않은 콘텐츠가 있습니다

클라우드 스토리지 풀을 생성, 편집 또는 삭제하려고 하면 이 오류가 발생할 수 있습니다. 이 오류는 버킷 또는 컨테이너에 마커 파일이 포함되어 있지만 해당 파일에 예상 UUID가 있는 메타데이터 필드가 없는 경우 `x-ntap-sgws-cloud-pool-uuid` 발생합니다.

일반적으로 새 클라우드 스토리지 풀을 생성하고 StorageGRID의 다른 인스턴스가 이미 동일한 클라우드 스토리지 풀을 사용 중인 경우에만 이 오류가 표시됩니다.

다음 단계 중 하나를 수행하여 문제를 해결하십시오.

* 새 클라우드 스토리지 풀을 구성하는 경우 다음 예제와 유사한 파일 및 추가 오브젝트 키가 버킷에 포함되어 있는 경우 `x-ntap-sgws-cloud-pool-uuid` 새 버킷을 생성하고 이 새 버킷을 대신 사용하십시오.
+
추가 개체 키의 예: `my-bucket.3E64CF2C-B74D-4B7D-AFE7-AD28BC18B2F6.1727326606730410`

* 파일이 버킷에서 유일한 오브젝트인 경우 `x-ntap-sgws-cloud-pool-uuid` 이 파일을 삭제합니다.


이러한 단계가 시나리오에 적용되지 않으면 지원 팀에 문의하십시오.



== 오류: 클라우드 스토리지 풀을 생성하거나 업데이트할 수 없습니다. 끝점에서 오류가 발생했습니다

다음과 같은 상황에서 이 오류가 발생할 수 있습니다.

* 클라우드 스토리지 풀을 생성하거나 편집하려는 경우
* 새로운 클라우드 스토리지 풀을 구성할 때 S3 Object Lock과 함께 지원되지 않는 플랫폼, 인증 또는 프로토콜 조합을 선택하는 경우 을 link:../ilm/considerations-for-cloud-storage-pools.html["클라우드 스토리지 풀에 대한 고려 사항"]참조하십시오.


이 오류는 접속 또는 구성 문제로 인해 StorageGRID가 클라우드 스토리지 풀에 쓸 수 없음을 나타냅니다.

문제를 해결하려면 끝점에서 오류 메시지를 검토하십시오.

* 오류 메시지에 이 포함되어 있으면 `Get _url_: EOF` 클라우드 스토리지 풀에 사용된 서비스 끝점에서 HTTPS가 필요한 컨테이너나 버킷에 대해 HTTP를 사용하지 않는지 확인합니다.
* 오류 메시지에 이 포함되어 있으면 `Get _url_: net/http: request canceled while waiting for connection` 네트워크 구성에서 스토리지 노드가 클라우드 스토리지 풀에 사용되는 서비스 끝점에 액세스할 수 있는지 확인합니다.
* 지원되지 않는 플랫폼, 인증 또는 프로토콜로 인해 오류가 발생한 경우 S3 오브젝트 잠금을 사용하여 지원되는 구성으로 변경하고 새 클라우드 스토리지 풀을 다시 저장해 보십시오.
* 다른 모든 끝점 오류 메시지에 대해 다음 중 하나 이상을 시도합니다.
+
** Cloud Storage Pool에 입력한 것과 동일한 이름의 외부 컨테이너 또는 버킷을 생성한 다음, 새 Cloud Storage Pool을 다시 저장하십시오.
** Cloud Storage Pool에 지정한 컨테이너 또는 버킷 이름을 수정하고 새 Cloud Storage Pool을 다시 저장하십시오.






== 오류: CA 인증서를 구문 분석하지 못했습니다

클라우드 스토리지 풀을 생성하거나 편집하려고 할 때 이 오류가 발생할 수 있습니다. StorageGRID에서 클라우드 스토리지 풀을 구성할 때 입력한 인증서를 구문 분석할 수 없는 경우 오류가 발생합니다.

문제를 해결하려면 제공한 CA 인증서에 문제가 있는지 확인하십시오.



== 오류: 이 ID가 인 클라우드 스토리지 풀을 찾을 수 없습니다

Cloud Storage Pool을 편집하거나 삭제하려고 하면 이 오류가 발생할 수 있습니다. 이 오류는 끝점에서 404 응답을 반환할 때 발생하며, 이는 다음 중 하나를 의미할 수 있습니다.

* Cloud Storage Pool에 사용된 자격 증명에 버킷에 대한 읽기 권한이 없습니다.
* 클라우드 스토리지 풀에 사용되는 버킷에는 마커 파일이 포함되지 `x-ntap-sgws-cloud-pool-uuid` 않습니다.


다음 단계 중 하나 이상을 시도하여 문제를 해결하십시오.

* 구성된 액세스 키와 연결된 사용자에게 필요한 권한이 있는지 확인합니다.
* 필요한 권한이 있는 자격 증명을 사용하여 클라우드 스토리지 풀을 편집합니다.
* 사용 권한이 올바르면 지원 부서에 문의하십시오.




== 오류: 클라우드 스토리지 풀의 콘텐츠를 확인할 수 없습니다. 끝점에서 오류가 발생했습니다

클라우드 스토리지 풀을 삭제하려고 하면 이 오류가 발생할 수 있습니다. 이 오류는 StorageGRID에서 클라우드 스토리지 풀 버킷의 내용을 읽지 못하는 연결 또는 구성 문제가 발생했음을 나타냅니다.

문제를 해결하려면 끝점에서 오류 메시지를 검토하십시오.



== 오류: 객체가 이 버킷에 이미 배치되었습니다

클라우드 스토리지 풀을 삭제하려고 하면 이 오류가 발생할 수 있습니다. ILM을 통해 이동한 데이터, Cloud Storage Pool을 구성하기 전에 버킷에 있던 데이터 또는 Cloud Storage Pool을 생성한 후 다른 소스에서 버킷을 포함한 데이터가 Cloud Storage Pool에 포함된 경우에는 Cloud Storage Pool을 삭제할 수 없습니다.

다음 단계 중 하나 이상을 시도하여 문제를 해결하십시오.

* "클라우드 스토리지 풀 개체의 라이프사이클"에서 오브젝트를 StorageGRID로 다시 이동하는 지침을 따릅니다.
* ILM을 통해 나머지 객체가 Cloud Storage Pool에 포함되지 않은 것으로 확신하는 경우 버킷에서 객체를 수동으로 삭제하십시오.
+

NOTE: ILM에 의해 배치된 클라우드 스토리지 풀에서 개체를 수동으로 삭제하지 마십시오. 나중에 StorageGRID에서 수동으로 삭제된 개체에 액세스하려고 하면 삭제된 개체를 찾을 수 없습니다.





== 오류: 프록시에서 클라우드 스토리지 풀에 연결하려고 시도하는 동안 외부 오류가 발생했습니다

스토리지 노드와 클라우드 스토리지 풀에 사용되는 외부 S3 끝점 간에 투명하지 않은 스토리지 프록시를 구성한 경우 이 오류가 발생할 수 있습니다. 이 오류는 외부 프록시 서버가 Cloud Storage Pool 끝점에 연결할 수 없는 경우에 발생합니다. 예를 들어 DNS 서버가 호스트 이름을 확인할 수 없거나 외부 네트워킹 문제가 있을 수 있습니다.

다음 단계 중 하나 이상을 시도하여 문제를 해결하십시오.

* 클라우드 스토리지 풀(* ILM * > * 스토리지 풀 *)의 설정을 확인합니다.
* 스토리지 프록시 서버의 네트워킹 구성을 확인합니다.




== 오류: X.509 인증서의 유효 기간이 만료되었습니다

클라우드 스토리지 풀을 삭제하려고 하면 이 오류가 발생할 수 있습니다. 이 오류는 올바른 외부 클라우드 스토리지 풀의 유효성을 검사하고 클라우드 스토리지 풀 구성이 삭제되기 전에 외부 풀이 비어 있는지 확인하기 위해 인증에 X.509 인증서가 필요할 때 발생합니다.

다음 단계를 수행하여 문제를 해결하십시오.

* 인증을 위해 구성된 인증서를 클라우드 스토리지 풀에 업데이트합니다.
* 이 클라우드 스토리지 풀에 대한 인증서 만료 경고가 모두 해결되었는지 확인합니다.


.관련 정보
link:lifecycle-of-cloud-storage-pool-object.html["Cloud Storage Pool 개체의 수명주기입니다"]
