---
permalink: ilm/using-last-access-time-in-ilm-rules.html 
sidebar: sidebar 
keywords: last access time, ilm rule reference time 
summary: ILM 규칙에서 마지막 액세스 시간을 참조 시간으로 사용할 수 있습니다. 예를 들어, 최근 3개월 동안 표시된 객체를 로컬 스토리지 노드에 그대로 두고, 최근에 외부 위치로 표시되지 않은 객체를 이동할 수 있습니다. ILM 규칙을 특정 날짜에 마지막으로 액세스한 개체에만 적용하려면 마지막 액세스 시간을 고급 필터로 사용할 수도 있습니다. 
---
= ILM 규칙에서 마지막 액세스 시간을 사용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM 규칙에서 마지막 액세스 시간을 참조 시간으로 사용할 수 있습니다. 예를 들어, 최근 3개월 동안 표시된 객체를 로컬 스토리지 노드에 그대로 두고, 최근에 외부 위치로 표시되지 않은 객체를 이동할 수 있습니다. ILM 규칙을 특정 날짜에 마지막으로 액세스한 개체에만 적용하려면 마지막 액세스 시간을 고급 필터로 사용할 수도 있습니다.

.이 작업에 대해
ILM 규칙에서 마지막 액세스 시간을 사용하기 전에 다음 고려 사항을 검토하십시오.

* 마지막 액세스 시간을 참조 시간으로 사용하는 경우 개체의 마지막 액세스 시간을 변경해도 즉각적인 ILM 평가가 트리거되지 않습니다. 그 대신, 개체의 배치를 평가하고 배경 ILM이 개체를 평가할 때 필요에 따라 개체를 이동합니다. 개체에 액세스한 후 2주 이상이 걸릴 수 있습니다.
+
마지막 액세스 시간을 기반으로 ILM 규칙을 생성할 때 이 지연 시간을 고려하고 짧은 기간(1개월 미만)을 사용하는 배치를 피하십시오.

* 마지막 액세스 시간을 고급 필터로 사용하거나 참조 시간으로 사용하는 경우 S3 버킷에 대한 마지막 액세스 시간 업데이트를 활성화해야 합니다. 또는 을 사용할 수 link:../tenant/enabling-or-disabling-last-access-time-updates.html["테넌트 관리자"]link:../s3/put-bucket-last-access-time-request.html["테넌트 관리 API"]있습니다.
+

NOTE: S3 버킷의 경우 마지막 액세스 시간 업데이트가 기본적으로 해제되어 있습니다.

+

NOTE: 마지막 액세스 시간 업데이트를 사용하면 특히 개체가 작은 시스템에서 성능이 저하될 수 있습니다. 개체가 검색될 때마다 StorageGRID에서 새 타임스탬프로 개체를 업데이트해야 하므로 성능에 미치는 영향이 발생합니다.



다음 표에는 버킷의 모든 오브젝트에 대해 서로 다른 유형의 요청에 대해 마지막 액세스 시간이 업데이트되었는지 여부가 요약되어 있습니다.

[cols="1a,1a,1a"]
|===
| 요청 유형입니다 | 마지막 액세스 시간 업데이트가 비활성화되었을 때 마지막 액세스 시간이 업데이트되는지 여부를 나타냅니다 | 마지막 액세스 시간 업데이트를 사용할 때 마지막 액세스 시간을 업데이트할지 여부를 나타냅니다 


 a| 
개체, 해당 액세스 제어 목록 또는 해당 메타데이터를 검색하는 요청입니다
 a| 
아니요
 a| 
예



 a| 
개체의 메타데이터를 업데이트하도록 요청합니다
 a| 
예
 a| 
예



 a| 
한 버킷에서 다른 버킷으로 오브젝트 복사 요청
 a| 
* 아니요, 소스 복제본입니다
* 예, 대상 복사본에 대해 입니다

 a| 
* 예. 소스 복제본에 대해 가능합니다
* 예, 대상 복사본에 대해 입니다




 a| 
여러 부분 업로드를 완료하도록 요청합니다
 a| 
예. 조립된 개체에 대해 가능합니다
 a| 
예. 조립된 개체에 대해 가능합니다

|===