---
permalink: ilm/what-erasure-coding-schemes-are.html 
sidebar: sidebar 
keywords: erasure-coding scheme 
summary: 삭제 코딩 스키마를 통해 각 오브젝트에 대해 생성되는 데이터 조각과 패리티 조각의 수를 제어합니다. 
---
= 삭제 코딩 체계란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
삭제 코딩 스키마를 통해 각 오브젝트에 대해 생성되는 데이터 조각과 패리티 조각의 수를 제어합니다.

ILM 규칙을 생성하거나 편집할 때 사용 가능한 삭제 코딩 체계를 선택합니다. 사용할 스토리지 풀을 구성하는 스토리지 노드 및 사이트의 수에 따라 StorageGRID에서 삭제 코딩 체계를 자동으로 생성합니다.



== 데이터 보호

StorageGRID 시스템은 Reed-Solomon 삭제 코딩 알고리즘을 사용합니다. 알고리즘은 오브젝트를 데이터 `m` 조각으로 분할하고 `k` 패리티 조각을 계산합니다.

 `k + m = n`조각은 다음과 같이 데이터 보호를 제공하기 위해 스토리지 노드 전체에 분산됩니다. `n`

* 오브젝트를 검색하거나 복구하려면 `k` 조각이 필요합니다.
* 오브젝트는 손실되거나 손상된 조각까지 유지할 수 `m` 있습니다. 값이 클수록 `m` 오류 허용 오차가 커집니다.


최고의 데이터 보호는 스토리지 풀 내에서 가장 높은 노드 또는 볼륨 장애를 허용하는 삭제 코딩 체계를 통해 제공됩니다.



== 스토리지 오버헤드

삭제 코딩 체계의 스토리지 오버헤드는 패리티 조각의 (`m`수를 데이터 조각의 수로 나누어 (`k`계산합니다. 스토리지 오버헤드를 사용하여 각 삭제 코딩 오브젝트에 필요한 디스크 공간을 계산할 수 있습니다.

`_disk space_ = _object size_ + (_object size_ * _storage overhead_)`

예를 들어, 스토리지 오버헤드가 50%인 4+2 체계를 사용하여 10MB 오브젝트를 저장할 경우 오브젝트는 15MB의 그리드 스토리지를 사용합니다. 스토리지 오버헤드가 33%인 6+2 체계를 사용하여 동일한 10MB 개체를 저장하는 경우, 개체는 약 13.3MB를 사용합니다.

귀사의 요구사항을 충족하는 의 총액이 가장 낮은 삭제 코딩 체계를 선택합니다 `k+m`. 조각 수가 적은 삭제 코딩 체계를 사용하는 것이 보다 효율적인 이유는 다음과 같습니다.

* 오브젝트당 생성 및 분산(또는 검색)되는 조각의 수가 더 적습니다
* 조각 크기가 크기 때문에 성능이 더 좋습니다
* 따라서 에 추가할 수 있는 노드 수를 줄일 수 있습니다 link:../expand/index.html["추가 스토리지가 필요할 때 확장"]




== 스토리지 풀에 대한 지침

삭제 코딩 복사본을 생성할 규칙에 사용할 스토리지 풀을 선택할 때는 스토리지 풀에 대해 다음 지침을 따르십시오.

* 스토리지 풀에는 3개 이상의 사이트 또는 정확히 하나의 사이트가 포함되어야 합니다.
+

NOTE: 스토리지 풀에 두 개의 사이트가 포함된 경우 삭제 코딩을 사용할 수 없습니다.

+
** <<3개 이상의 사이트가 포함된 스토리지 풀의 삭제 코딩 체계,3개 이상의 사이트가 포함된 스토리지 풀의 삭제 코딩 체계>>
** <<단일 사이트 스토리지 풀에 대한 삭제 코딩 구성표,단일 사이트 스토리지 풀에 대한 삭제 코딩 구성표>>


* 모든 사이트 사이트를 포함하는 스토리지 풀을 사용하지 마십시오.
* 스토리지 풀에는 오브젝트 데이터를 저장할 수 있는 스토리지 노드 이상이 `_k+m_ +1` 포함되어야 합니다.
+

NOTE: 설치 중에 객체 데이터 및 메타데이터("결합된" 스토리지 노드), 객체 메타데이터만 포함하거나 객체 데이터만 포함하도록 스토리지 노드를 구성할 수 있습니다. 자세한 내용은 을 link:../primer/what-storage-node-is.html#types-of-storage-nodes["스토리지 노드 유형"]참조하십시오.

+
필요한 최소 스토리지 노드 수는 입니다 `k+m`. 그러나 필요한 스토리지 노드를 일시적으로 사용할 수 없는 경우 하나 이상의 추가 스토리지 노드를 사용하면 수집 실패 또는 ILM 백로그를 방지할 수 있습니다.





== 3개 이상의 사이트가 포함된 스토리지 풀의 삭제 코딩 체계

다음 표에서는 3개 이상의 사이트가 포함된 스토리지 풀에 대해 StorageGRID에서 현재 지원하는 삭제 코딩 스키마를 설명합니다. 이러한 모든 스키마를 통해 사이트 손실을 보호할 수 있습니다. 한 사이트는 손실될 수 있으며 개체는 계속 액세스할 수 있습니다.

사이트 손실 보호를 제공하는 삭제 코딩 구성의 경우 각 사이트에는 최소 3개의 스토리지 노드가 필요하므로 스토리지 풀에서 권장 스토리지 노드 수가 을 초과합니다 `_k+m_ +1`.

[cols="1a,1a,1a,1a,1a,1a"]
|===
| 삭제 코딩 체계(_k+m_) | 배포된 사이트의 최소 수입니다 | 각 사이트에 권장되는 스토리지 노드 수입니다 | 총 권장 스토리지 노드 수입니다 | 사이트 손실 방지 | 스토리지 오버헤드 


 a| 
4 + +2
 a| 
3
 a| 
3
 a| 
9
 a| 
예
 a| 
50%



 a| 
6 + +2
 a| 
4
 a| 
3
 a| 
12
 a| 
예
 a| 
33%



 a| 
8 + +2
 a| 
5
 a| 
3
 a| 
15
 a| 
예
 a| 
25%



 a| 
6 + 3
 a| 
3
 a| 
4
 a| 
12
 a| 
예
 a| 
50%



 a| 
9 + 3
 a| 
4
 a| 
4
 a| 
16
 a| 
예
 a| 
33%



 a| 
2 + +1
 a| 
3
 a| 
3
 a| 
9
 a| 
예
 a| 
50%



 a| 
4 + +1
 a| 
5
 a| 
3
 a| 
15
 a| 
예
 a| 
25%



 a| 
6 + +1
 a| 
7
 a| 
3
 a| 
21
 a| 
예
 a| 
17%



 a| 
7 + +5
 a| 
3
 a| 
5
 a| 
15
 a| 
예
 a| 
71%

|===

NOTE: StorageGRID에는 사이트당 최소 3개의 스토리지 노드가 필요합니다. 7+5 스키마를 사용하려면 각 사이트에 최소 4개의 스토리지 노드가 필요합니다. 사이트당 5개의 스토리지 노드를 사용하는 것이 좋습니다.

사이트 보호를 제공하는 삭제 코딩 스키마를 선택할 때는 다음 요소의 상대적 중요도를 균형 있게 조정합니다.

* * 조각 수 *: 전체 조각 수가 적으면 성능과 확장 유연성이 일반적으로 더 좋습니다.
* * 내결함성 *: 패리티 세그먼트가 많을수록 내결함성(즉, 값이 더 높은 경우 `m`)이 증가합니다.
* * 네트워크 트래픽 * : 실패에서 복구 할 때 더 많은 조각이 있는 체계(즉, 더 높은 총계 `k+m`)를 사용하면 더 많은 네트워크 트래픽이 생성됩니다.
* * 스토리지 오버헤드 *: 오버헤드가 높은 구성일수록 오브젝트당 스토리지 공간이 더 필요합니다.


예를 들어, 4+2 체계와 6+3 체계(둘 다 50%의 스토리지 오버헤드를 가짐) 중에서 결정할 때 추가 내결함성을 필요로 하는 경우 6+3 체계를 선택합니다. 네트워크 리소스가 제한된 경우 4+2 구성표를 선택합니다. 다른 모든 요소가 같으면 총 단편 수가 더 낮기 때문에 4+2를 선택합니다.


NOTE: 사용할 체계가 확실하지 않으면 4+2 또는 6+3을 선택하거나 기술 지원 부서에 문의하십시오.



== 단일 사이트 스토리지 풀에 대한 삭제 코딩 구성표

사이트에 충분한 스토리지 노드가 있는 경우 한 사이트 스토리지 풀은 세 개 이상의 사이트에 대해 정의된 모든 삭제 코딩 스키마를 지원합니다.

필요한 최소 스토리지 노드 수는 `k+m` 이지만 스토리지 노드가 있는 스토리지 풀을 사용하는 `k+m +1` 것이 좋습니다. 예를 들어, 2+1 삭제 코딩 구성표에 최소 3개의 스토리지 노드가 있는 스토리지 풀이 필요하지만 4개의 스토리지 노드를 사용하는 것이 좋습니다.

[cols="1a,1a,1a,1a"]
|===
| 삭제 코딩 체계(_k+m_) | 최소 스토리지 노드 수입니다 | 권장되는 스토리지 노드 수입니다 | 스토리지 오버헤드 


 a| 
4 + +2
 a| 
6
 a| 
7
 a| 
50%



 a| 
6 + +2
 a| 
8
 a| 
9
 a| 
33%



 a| 
8 + +2
 a| 
10
 a| 
11
 a| 
25%



 a| 
6 + 3
 a| 
9
 a| 
10
 a| 
50%



 a| 
9 + 3
 a| 
12
 a| 
13
 a| 
33%



 a| 
2 + +1
 a| 
3
 a| 
4
 a| 
50%



 a| 
4 + +1
 a| 
5
 a| 
6
 a| 
25%



 a| 
6 + +1
 a| 
7
 a| 
8
 a| 
17%



 a| 
7 + +5
 a| 
12
 a| 
13
 a| 
71%

|===