---
permalink: ilm/when-to-use-cloud-storage-pools.html 
sidebar: sidebar 
keywords: use cloud storage pool, benefits of cloud storage pools 
summary: Cloud Storage Pool을 사용하면 데이터를 외부 위치에 백업하거나 계층화할 수 있습니다. 또한 둘 이상의 클라우드에 데이터를 백업하거나 계층화할 수 있습니다. 
---
= 클라우드 스토리지 풀을 사용하는 경우
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cloud Storage Pool을 사용하면 데이터를 외부 위치에 백업하거나 계층화할 수 있습니다. 또한 둘 이상의 클라우드에 데이터를 백업하거나 계층화할 수 있습니다.



== StorageGRID 데이터를 외부 위치에 백업합니다

클라우드 스토리지 풀을 사용하여 StorageGRID 객체를 외부 위치에 백업할 수 있습니다.

StorageGRID의 복사본에 액세스할 수 없는 경우 클라우드 스토리지 풀의 오브젝트 데이터를 사용하여 클라이언트 요청을 처리할 수 있습니다. 그러나 클라우드 스토리지 풀의 백업 오브젝트 복사본에 액세스하려면 S3 RestoreObject 요청을 실행해야 할 수도 있습니다.

스토리지 볼륨 또는 스토리지 노드 장애로 인해 클라우드 스토리지 풀의 오브젝트 데이터를 사용하여 StorageGRID에서 손실된 데이터를 복구할 수도 있습니다. 개체의 나머지 복사본만 클라우드 스토리지 풀에 있는 경우 StorageGRID는 개체를 일시적으로 복원하고 복구된 스토리지 노드에 새 복사본을 생성합니다.

백업 솔루션을 구축하려면 다음을 따르십시오.

. 단일 Cloud Storage Pool을 생성합니다.
. 스토리지 노드에 오브젝트 복사본(복제된 복사본 또는 삭제 코딩 복사본)을 동시에 저장하고 클라우드 스토리지 풀에 단일 오브젝트 복사본을 저장하는 ILM 규칙을 구성합니다.
. ILM 정책에 규칙을 추가합니다. 그런 다음 정책을 시뮬레이션하고 활성화합니다.




== StorageGRID에서 외부 위치로 데이터 계층화

클라우드 스토리지 풀을 사용하여 StorageGRID 시스템 외부에 개체를 저장할 수 있습니다. 예를 들어, 보존해야 하는 오브젝트가 많은 경우 해당 오브젝트에 거의 액세스하지 않을 것으로 예상한다고 가정합니다. 클라우드 스토리지 풀을 사용하여 오브젝트를 저비용 스토리지로 계층화하거나 StorageGRID에서 공간을 확보할 수 있습니다.

계층화 솔루션을 구축하려면 다음을 따르십시오.

. 단일 Cloud Storage Pool을 생성합니다.
. 거의 사용되지 않는 오브젝트를 스토리지 노드에서 클라우드 스토리지 풀로 이동하는 ILM 규칙을 구성합니다.
. ILM 정책에 규칙을 추가합니다. 그런 다음 정책을 시뮬레이션하고 활성화합니다.




== 여러 클라우드 엔드포인트 유지 관리

오브젝트 데이터를 두 개 이상의 클라우드에 계층화하거나 백업하려는 경우 여러 Cloud Storage Pool 엔드포인트를 구성할 수 있습니다. ILM 규칙의 필터를 사용하여 각 클라우드 스토리지 풀에 저장할 오브젝트를 지정할 수 있습니다. 예를 들어, 일부 테넌트 또는 버킷의 오브젝트를 Amazon S3 빙하에 저장하고 다른 테넌트 또는 버킷의 오브젝트를 Azure Blob 스토리지에 저장할 수 있습니다. 또는 Amazon S3 Glacier와 Azure Blob 스토리지 간에 데이터를 이동할 수 있습니다.


NOTE: 여러 Cloud Storage Pool 엔드포인트를 사용할 경우 한 번에 하나의 Cloud Storage Pool에만 개체를 저장할 수 있습니다.

여러 클라우드 엔드포인트를 구현하려면:

. 최대 10개의 클라우드 스토리지 풀을 생성합니다.
. 각 Cloud Storage Pool에 적절한 시간에 적절한 오브젝트 데이터를 저장하도록 ILM 규칙을 구성합니다. 예를 들어, 버킷 A의 오브젝트를 클라우드 스토리지 풀 A에 저장하고 버킷 B의 오브젝트를 클라우드 스토리지 풀 B에 저장합니다. 또는 일정 시간 동안 오브젝트를 클라우드 스토리지 풀 A에 저장한 다음 클라우드 스토리지 풀 B로 이동합니다
. ILM 정책에 규칙을 추가합니다. 그런 다음 정책을 시뮬레이션하고 활성화합니다.

