---
permalink: fabricpool/best-practices-ilm.html 
sidebar: sidebar 
keywords: FabricPool, StorageGRID, best practices, ILM, information lifecycle management, ILM rule, ILM policy, erasure-coding, replication 
summary: 'FabricPool를 사용하여 데이터를 StorageGRID에 계층화할 경우 FabricPool 데이터에 대한 StorageGRID 정보 라이프사이클 관리(ILM)를 사용하기 위한 요구사항을 이해해야 합니다.' 
---
= FabricPool 데이터와 함께 StorageGRID ILM을 사용하는 모범 사례
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool를 사용하여 데이터를 StorageGRID에 계층화할 경우 FabricPool 데이터에 대한 StorageGRID 정보 라이프사이클 관리(ILM)를 사용하기 위한 요구사항을 이해해야 합니다.


CAUTION: FabricPool에는 StorageGRID ILM 규칙 또는 정책에 대한 지식이 없습니다. StorageGRID ILM 정책이 잘못 구성된 경우 데이터 손실이 발생할 수 있습니다. 자세한 내용은  및 을 link:../ilm/what-ilm-rule-is.html["ILM 규칙을 사용하여 오브젝트를 관리합니다"]link:../ilm/creating-ilm-policy.html["ILM 정책을 생성합니다"]참조하십시오.



== FabricPool에서 ILM 사용 지침

FabricPool 설정 마법사를 사용하면 마법사는 사용자가 생성하는 각 S3 버킷에 대한 새 ILM 규칙을 자동으로 생성하고 해당 규칙을 비활성 정책에 추가합니다. 정책을 활성화하라는 메시지가 표시됩니다. 자동으로 생성된 규칙은 권장되는 모범 사례를 따릅니다. 단일 사이트에서 2+1 삭제 코딩을 사용합니다.

FabricPool 설정 마법사를 사용하지 않고 StorageGRID를 수동으로 구성하는 경우에는 이러한 지침을 검토하여 ILM 규칙 및 ILM 정책이 FabricPool 데이터 및 비즈니스 요구 사항에 적합한지 확인하십시오. 이러한 지침을 충족하기 위해 새 규칙을 생성하고 활성 ILM 정책을 업데이트해야 할 수 있습니다.

* 복제 및 삭제 코딩 규칙을 조합하여 클라우드 계층 데이터를 보호할 수 있습니다.
+
가장 권장되는 모범 사례는 비용 효율적인 데이터 보호를 위해 사이트 내에서 2+1 삭제 코딩을 사용하는 것입니다. 삭제 코딩은 더 많은 CPU를 사용하지만 복제에 비해 스토리지 용량이 훨씬 적습니다. 4+1 및 6+1 구성표는 2+1 구성표보다 적은 용량을 사용합니다. 그러나 그리드 확장 중에 스토리지 노드를 추가해야 하는 경우 4+1 및 6+1 구성표는 유연하지 않습니다. 자세한 내용은 을 참조하십시오 link:../expand/adding-storage-capacity-for-erasure-coded-objects.html["삭제 코딩 오브젝트를 위한 스토리지 용량을 추가합니다"].

* FabricPool 데이터에 적용되는 각 규칙은 삭제 코딩을 사용하거나 적어도 두 개의 복제된 복사본을 만들어야 합니다.
+

CAUTION: 특정 기간 동안 복제된 복사본을 하나만 생성하는 ILM 규칙은 데이터가 영구적으로 손실될 위험이 있습니다. 복제된 객체 복제본이 하나만 있는 경우 스토리지 노드에 장애가 발생하거나 심각한 오류가 발생한 경우 해당 객체가 손실됩니다. 또한 업그레이드와 같은 유지보수 절차 중에는 개체에 대한 액세스가 일시적으로 중단됩니다.

* 필요한 경우link:remove-fabricpool-data.html["StorageGRID에서 FabricPool 데이터를 제거합니다"], ONTAP를 사용하여 FabricPool 볼륨에 대한 모든 데이터를 검색하고 성능 계층으로 승격합니다.
+

CAUTION: 데이터 손실을 방지하려면 FabricPool 클라우드 계층 데이터를 만료 또는 삭제할 ILM 규칙을 사용하지 마십시오. 각 ILM 규칙의 보존 기간을 * Forever * 로 설정하여 StorageGRID ILM에서 FabricPool 개체가 삭제되지 않도록 합니다.

* FabricPool 클라우드 계층 데이터를 버킷에서 다른 위치로 이동할 규칙을 만들지 마십시오. 클라우드 스토리지 풀을 사용하여 FabricPool 데이터를 다른 오브젝트 저장소로 이동할 수는 없습니다.
+

NOTE: FabricPool에서 클라우드 스토리지 풀 타겟의 객체를 검색하는 지연 시간이 추가되었기 때문에 클라우드 스토리지 풀을 사용할 수 없습니다.

* ONTAP 9.8부터 객체 태그를 생성하여 계층형 데이터를 쉽게 분류하고 정렬할 수 있습니다. 예를 들어, StorageGRID에 연결된 FabricPool 볼륨에만 태그를 설정할 수 있습니다. 그런 다음 StorageGRID에서 ILM 규칙을 만들 때 개체 태그 고급 필터를 사용하여 이 데이터를 선택하고 배치할 수 있습니다.

