---
permalink: fabricpool/best-practices-for-load-balancing.html 
sidebar: sidebar 
keywords: fabricPool, load balancer endpoint, load balancing, Layer 7, best practices, certificate, CA, certificate authority, tls, ssl 
summary: StorageGRID를 FabricPool 클라우드 계층으로 연결하기 전에 로드 밸런서와 FabricPool를 함께 사용하는 모범 사례를 검토하십시오. 
---
= FabricPool의 로드 밸런싱 모범 사례
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID를 FabricPool 클라우드 계층으로 연결하기 전에 로드 밸런서와 FabricPool를 함께 사용하는 모범 사례를 검토하십시오.

StorageGRID 로드 밸런서 및 로드 밸런서 인증서에 대한 일반적인 내용은 을 참조하십시오.link:../admin/managing-load-balancing.html["로드 균형 조정에 대한 고려 사항"]



== FabricPool에 사용되는 로드 밸런서 끝점에 대한 테넌트 액세스에 대한 모범 사례

특정 부하 분산 엔드포인트를 사용하여 해당 버킷에 액세스할 수 있는 테넌트를 제어할 수 있습니다. 모든 테넌트를 허용하거나, 일부 테넌트를 허용하거나, 일부 테넌트를 차단할 수 있습니다. FabricPool 사용을 위해 로드 균형 조정 끝점을 만들 때 * 모든 테넌트 허용 * 을 선택합니다. ONTAP는 StorageGRID 버킷에 저장된 데이터를 암호화하므로 이 추가 보안 계층에서는 추가 보안이 제공되지 않습니다.



== 보안 인증서에 대한 모범 사례

FabricPool 사용을 위해 StorageGRID 로드 밸런서 끝점을 만들 때 ONTAP가 StorageGRID를 사용하여 인증할 수 있도록 하는 보안 인증서를 제공합니다.

대부분의 경우 ONTAP와 StorageGRID 간의 연결은 TLS(전송 계층 보안) 암호화를 사용해야 합니다. TLS 암호화 없이 FabricPool를 사용하는 것은 지원되지만 권장되지 않습니다. StorageGRID 로드 밸런서 끝점에 대한 네트워크 프로토콜을 선택할 때 * HTTPS * 를 선택합니다. 그런 다음 ONTAP에서 StorageGRID를 인증할 수 있도록 보안 인증서를 제공합니다.

로드 밸런싱 끝점의 서버 인증서에 대한 자세한 내용은 다음을 참조하십시오.

* link:../admin/using-storagegrid-security-certificates.html["보안 인증서를 관리합니다"]
* link:../admin/managing-load-balancing.html["로드 균형 조정에 대한 고려 사항"]
* link:../harden/hardening-guideline-for-server-certificates.html["서버 인증서에 대한 강화 지침"]




=== ONTAP에 인증서를 추가합니다

StorageGRID를 FabricPool 클라우드 계층으로 추가하는 경우 루트 및 하위 CA(인증 기관) 인증서를 포함하여 ONTAP 클러스터에 동일한 인증서를 설치해야 합니다.



=== 인증서 만료 관리


CAUTION: ONTAP와 StorageGRID 간의 연결을 보호하는 데 사용되는 인증서가 만료되면 FabricPool가 일시적으로 작동을 멈추고 ONTAP가 StorageGRID로 계층화된 데이터에 대한 액세스를 일시적으로 상실합니다.

인증서 만료 문제를 방지하려면 다음 모범 사례를 따르십시오.

* 로드 밸런서 엔드포인트 인증서 만료 * 및 * S3 API용 글로벌 서버 인증서 만료 * 경고와 같이 인증서 만료 날짜가 다가올 경우 경고를 주의 깊게 모니터링하십시오.
* 항상 인증서의 StorageGRID 및 ONTAP 버전을 동기화된 상태로 유지합니다. 로드 밸런서 끝점에 사용되는 인증서를 교체하거나 갱신하는 경우 클라우드 계층에 대해 ONTAP에서 사용하는 것과 동일한 인증서를 교체하거나 갱신해야 합니다.
* 공개적으로 서명된 CA 인증서를 사용합니다. CA에서 서명한 인증서를 사용하는 경우 그리드 관리 API를 사용하여 인증서 회전을 자동화할 수 있습니다. 따라서 만료 임박한 인증서를 중단 없이 교체할 수 있습니다.
* 자체 서명된 StorageGRID 인증서를 생성했으며 인증서가 곧 만료될 경우 기존 인증서가 만료되기 전에 StorageGRID 및 ONTAP에서 수동으로 인증서를 교체해야 합니다. 자체 서명된 인증서가 이미 만료된 경우 ONTAP에서 인증서 유효성 검사를 해제하면 액세스 손실이 방지됩니다.
+
자세한 내용은 을 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_configure_a_new_StorageGRID_self-signed_server_certificate_on_an_existing_ONTAP_FabricPool_deployment["NetApp 기술 자료: 기존 ONTAP FabricPool 배포에서 새로운 StorageGRID 자체 서명 서버 인증서를 구성하는 방법"^] 참조하십시오.


