---
permalink: fabricpool/configure-dns-server.html 
sidebar: sidebar 
keywords: fabricPool, StorageGRID, dns, vip, virtual ip, fqdn, server name 
summary: 고가용성 그룹, 로드 밸런서 끝점 및 S3 도메인 이름을 구성한 후에는 DNS에 StorageGRID에 필요한 항목이 포함되어 있는지 확인해야 합니다. 
---
= FabricPool를 사용하여 StorageGRID에 대한 DNS 서버 항목 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
고가용성 그룹, 로드 밸런서 끝점 및 S3 끝점 도메인 이름을 구성한 후에는 DNS에 StorageGRID에 필요한 항목이 포함되어 있는지 확인해야 합니다. 보안 인증서와 사용할 수 있는 각 IP 주소에 각 이름에 대한 DNS 항목을 포함해야 합니다.

을 link:../admin/managing-load-balancing.html["로드 균형 조정에 대한 고려 사항"]참조하십시오.



== StorageGRID 서버 이름에 대한 DNS 항목입니다

DNS 항목을 추가하여 StorageGRID 서버 이름(정규화된 도메인 이름)을 사용할 각 StorageGRID IP 주소에 연결합니다. DNS에 입력하는 IP 주소는 로드 밸런싱 노드의 HA 그룹을 사용하는지 여부에 따라 달라집니다.

* HA 그룹을 구성한 경우 ONTAP는 해당 HA 그룹의 가상 IP 주소에 연결됩니다.
* HA 그룹을 사용하지 않는 경우 ONTAP는 게이트웨이 노드 또는 관리 노드의 IP 주소를 사용하여 StorageGRID 로드 밸런서 서비스에 연결할 수 있습니다.
* 서버 이름이 둘 이상의 IP 주소로 확인되는 경우 ONTAP는 모든 IP 주소(최대 16개의 IP 주소)를 사용하여 클라이언트 연결을 설정합니다. 연결이 설정되면 IP 주소가 라운드 로빈 방식으로 선택됩니다.




== 가상 호스팅 스타일 요청에 대한 DNS 항목

을  정의하고 가상 호스팅 스타일 요청을 사용할 경우 link:../admin/configuring-s3-api-endpoint-domain-names.html["S3 끝점 도메인 이름"]모든 와일드카드 이름을 포함하여 필요한 모든 S3 끝점 도메인 이름에 DNS 항목을 추가합니다.
