---
permalink: fabricpool/creating-load-balancer-endpoint-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, load balancer, endpoint, load balancing, create, creating, certificate 
summary: StorageGRID는 로드 밸런서를 사용하여 FabricPool와 같은 클라이언트 애플리케이션에서 워크로드를 관리합니다. 로드 밸런싱은 여러 스토리지 노드에서 속도와 연결 용량을 극대화합니다. 
---
= FabricPool용 로드 밸런서 끝점을 만듭니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID는 로드 밸런서를 사용하여 FabricPool와 같은 클라이언트 애플리케이션에서 워크로드를 관리합니다. 로드 밸런싱은 여러 스토리지 노드에서 속도와 연결 용량을 극대화합니다.

FabricPool와 함께 사용하도록 StorageGRID를 구성할 때는 로드 밸런서 끝점을 구성하고 ONTAP와 StorageGRID 간의 연결을 보호하는 데 사용되는 로드 밸런서 끝점 인증서를 업로드하거나 생성해야 합니다.

FabricPool 설정 마법사를 사용하여 이 작업을 완료하려면 로 이동합니다link:use-fabricpool-setup-wizard-steps.html["FabricPool 설정 마법사를 액세스하고 완료합니다"].

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 이 link:../admin/admin-group-permissions.html["루트 액세스 권한"]있습니다.
* 일반 및 에 대한 검토를 link:../admin/managing-load-balancing.html["로드 균형 조정에 대한 고려 사항"]link:best-practices-for-load-balancing.html["FabricPool의 로드 밸런싱 모범 사례"]마쳤습니다.


.단계
. 구성 * > * 네트워크 * > * 로드 밸런서 엔드포인트 * 를 선택합니다.
. Create * 를 선택합니다.
. Enter endpoint details * 단계에서 다음 필드를 입력합니다.
+
[cols="1a,2a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
이름
 a| 
끝점에 대한 설명 이름입니다.



 a| 
포트
 a| 
로드 밸런싱에 사용할 StorageGRID 포트입니다. 이 필드는 처음 생성한 엔드포인트에 대해 기본적으로 10433으로 설정되지만 사용하지 않는 외부 포트는 입력할 수 있습니다. 80 또는 443을 입력하면 끝점이 게이트웨이 노드에서만 구성됩니다. 이러한 포트는 관리 노드에 예약되어 있습니다.

* 참고: * 다른 그리드 서비스에서 사용하는 포트는 허용되지 않습니다. 를 link:../network/internal-grid-node-communications.html["네트워크 포트 참조"]참조하십시오.

StorageGRID를 FabricPool 클라우드 계층으로 첨부하면 ONTAP에 이 번호를 제공할 수 있습니다.



 a| 
클라이언트 유형입니다
 a| 
S3 * 를 선택합니다.



 a| 
네트워크 프로토콜
 a| 
HTTPS * 를 선택합니다.

* 참고 *: TLS 암호화 없이 StorageGRID와 통신하는 것은 지원되지만 권장되지 않습니다.

|===
. Select binding mode * 단계에서 binding 모드를 지정합니다. 바인딩 모드는 임의의 IP 주소를 사용하거나 특정 IP 주소 및 네트워크 인터페이스를 사용하여 끝점에 액세스하는 방법을 제어합니다.
+
[cols="1a,3a"]
|===
| 모드를 선택합니다 | 설명 


 a| 
글로벌(기본값)
 a| 
클라이언트는 게이트웨이 노드 또는 관리 노드의 IP 주소, 네트워크에 있는 HA 그룹의 가상 IP(VIP) 주소 또는 해당 FQDN을 사용하여 끝점에 액세스할 수 있습니다.

이 끝점의 접근성을 제한할 필요가 없는 경우 * Global * (글로벌 *) 설정(기본값)을 사용합니다.



 a| 
HA 그룹의 가상 IP입니다
 a| 
클라이언트는 HA 그룹의 가상 IP 주소(또는 해당 FQDN)를 사용하여 이 끝점에 액세스해야 합니다.

이 바인딩 모드의 엔드포인트는 엔드포인트에 대해 선택한 HA 그룹이 겹치지 않는 한 모두 동일한 포트 번호를 사용할 수 있습니다.



 a| 
노드 인터페이스
 a| 
클라이언트는 선택한 노드 인터페이스의 IP 주소(또는 해당 FQDN)를 사용하여 이 끝점에 액세스해야 합니다.



 a| 
노드 유형입니다
 a| 
선택한 노드 유형에 따라 클라이언트는 관리 노드의 IP 주소(또는 해당 FQDN)나 게이트웨이 노드의 IP 주소(또는 해당 FQDN)를 사용하여 이 끝점에 액세스해야 합니다.

|===
. Tenant access * 단계에서 다음 중 하나를 선택합니다.
+
[cols="1a,2a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
모든 테넌트 허용(기본값)
 a| 
모든 테넌트 계정은 이 엔드포인트를 사용하여 해당 버킷에 액세스할 수 있습니다.

* 모든 테넌트 허용 * 은 거의 항상 FabricPool에 사용되는 로드 밸런서 끝점에 적합한 옵션입니다.

테넌트 계정을 아직 생성하지 않은 경우 이 옵션을 선택해야 합니다.



 a| 
선택한 테넌트 허용
 a| 
선택한 테넌트 계정만 이 끝점을 사용하여 해당 버킷을 액세스할 수 있습니다.



 a| 
선택한 테넌트 차단
 a| 
선택한 테넌트 계정은 이 끝점을 사용하여 해당 버킷을 액세스할 수 없습니다. 다른 모든 테넌트는 이 끝점을 사용할 수 있습니다.

|===
. 인증서 연결 * 단계에서 다음 중 하나를 선택합니다.
+
[cols="1a,2a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
인증서 업로드(권장)
 a| 
CA 서명 서버 인증서, 인증서 개인 키 및 선택적 CA 번들을 업로드하려면 이 옵션을 사용합니다.



 a| 
인증서를 생성합니다
 a| 
자체 서명된 인증서를 생성하려면 이 옵션을 사용합니다. 입력할 내용에 대한 자세한 내용은 을 link:../admin/configuring-load-balancer-endpoints.html["로드 밸런서 엔드포인트를 구성합니다"]참조하십시오.



 a| 
StorageGRID S3 인증서를 사용합니다
 a| 
이 옵션은 StorageGRID 글로벌 인증서의 사용자 지정 버전을 이미 업로드했거나 생성한 경우에만 사용할 수 있습니다. 자세한 내용은 을 link:../admin/configuring-custom-server-certificate-for-storage-node.html["S3 API 인증서를 구성합니다"] 참조하십시오.

|===
. Create * 를 선택합니다.



NOTE: 끝점 인증서 변경 내용을 모든 노드에 적용하는 데 최대 15분이 걸릴 수 있습니다.
