---
permalink: fabricpool/creating-tenant-account-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, StorageGRID, tenant, SSO 
summary: FabricPool용 그리드 관리자에서 테넌트 계정을 만들어야 합니다. 
---
= StorageGRID에서 FabricPool에 대한 테넌트 계정 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool용 그리드 관리자에서 테넌트 계정을 만들어야 합니다.

테넌트 계정을 사용하면 클라이언트 애플리케이션이 StorageGRID에 객체를 저장하고 검색할 수 있습니다. 각 테넌트 계정에는 고유한 계정 ID, 인증된 그룹 및 사용자, 버킷 및 객체가 있습니다.

이 작업에 대한 자세한 내용은 을 link:../admin/creating-tenant-account.html["테넌트 계정을 생성합니다"]참조하십시오. FabricPool 설정 마법사를 사용하여 이 작업을 완료하려면 로 이동합니다link:use-fabricpool-setup-wizard-steps.html["FabricPool 설정 마법사를 액세스하고 완료합니다"].

.시작하기 전에
* 을 사용하여 그리드 관리자에 로그인되어 있습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]
* 있습니다. link:../admin/admin-group-permissions.html["특정 액세스 권한"]


.단계
. *세입자*를 선택하세요.
. Create * 를 선택합니다.
. 세부 정보 입력 단계에 대해 다음 정보를 입력합니다.
+
[cols="1a,3a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
이름
 a| 
테넌트 계정의 이름입니다. 테넌트 이름은 고유해야 할 필요가 없습니다. 테넌트 계정이 생성되면 고유한 숫자 계정 ID를 받습니다.



 a| 
설명(선택 사항)
 a| 
테넌트를 식별하는 데 도움이 되는 설명입니다.



 a| 
클라이언트 유형입니다
 a| 
FabricPool의 경우 * S3 * 이어야 합니다.



 a| 
스토리지 할당량(선택 사항)
 a| 
FabricPool의 경우 이 필드를 비워 둡니다.

|===
. 권한 선택 단계의 경우:
+
.. 플랫폼 서비스 허용 * 을 선택하지 마십시오.
+
FabricPool 테넌트는 일반적으로 CloudMirror 복제와 같은 플랫폼 서비스를 사용할 필요가 없습니다.

.. 필요에 따라 * 고유 ID 소스 사용 * 을 선택합니다.
.. S3 선택 허용 * 을 선택하지 마십시오.
+
FabricPool 테넌트는 일반적으로 S3 Select를 사용할 필요가 없습니다.

.. 필요에 따라 * Use GRID Federation connection * 을 선택하여 테넌트가 계정 클론 및 교차 그리드 복제에 를 사용할 수 있도록 link:../admin/grid-federation-overview.html["그리드 페더레이션 연결"]합니다. 그런 다음 사용할 그리드 페더레이션 연결을 선택합니다.


. 루트 액세스 정의 단계에서 StorageGRID 시스템에서 사용하는지 여부에 따라 테넌트 계정에 대한 초기 루트 액세스 권한이 있는 사용자를 지정합니다.link:../admin/using-identity-federation.html["ID 제휴"] ,link:../admin/how-sso-works.html["SSO(Single Sign-On)"] , 또는 둘 다.
+
[cols="1a,2a"]
|===
| 옵션을 선택합니다 | 이렇게 하십시오 


 a| 
ID 페더레이션이 활성화되지 않은 경우
 a| 
테넌트에 로컬 루트 사용자로 로그인할 때 사용할 암호를 지정합니다.



 a| 
ID 페더레이션이 활성화된 경우
 a| 
.. 테넌트에 대한 루트 액세스 권한이 있는 기존 통합 그룹을 선택합니다.
.. 필요에 따라 테넌트에 로컬 루트 사용자로 로그인할 때 사용할 암호를 지정합니다.




 a| 
ID 페더레이션 및 SSO(Single Sign-On)가 모두 활성화된 경우
 a| 
테넌트에 대한 루트 액세스 권한이 있는 기존 통합 그룹을 선택합니다. 로컬 사용자는 로그인할 수 없습니다.

|===
. 테넌트 생성 * 을 선택합니다.

