---
permalink: fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, best practices, audit log, encryption, compressions, tiering, ontap, consistency 
summary: FabricPool와 함께 사용하도록 StorageGRID 시스템을 구성할 때 다른 StorageGRID 옵션을 변경해야 할 수 있습니다. 글로벌 설정을 변경하기 전에 변경이 다른 S3 애플리케이션에 어떤 영향을 미치는지 고려하십시오. 
---
= 기타 StorageGRID 및 FabricPool 모범 사례
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool와 함께 사용하도록 StorageGRID 시스템을 구성할 때 다른 StorageGRID 옵션을 변경해야 할 수 있습니다. 글로벌 설정을 변경하기 전에 변경이 다른 S3 애플리케이션에 어떤 영향을 미치는지 고려하십시오.



== 감사 메시지 및 로그 대상

FabricPool 워크로드는 읽기 작업의 비율이 높아 대량의 감사 메시지를 생성할 수 있는 경우가 많습니다.

* FabricPool 또는 다른 S3 응용 프로그램에 대한 클라이언트 읽기 작업 기록이 필요하지 않은 경우 * 구성 * > * 모니터링 * > * 감사 및 syslog 서버 * 로 이동합니다. 클라이언트 읽기 * 설정을 * 오류 * 로 변경하여 감사 로그에 기록되는 감사 메시지 수를 줄입니다. 자세한 내용은 을 link:../monitor/configure-audit-messages.html["감사 메시지 및 외부 syslog 서버를 구성합니다"] 참조하십시오.
* 대규모 그리드가 있거나, 여러 유형의 S3 애플리케이션을 사용하거나, 모든 감사 데이터를 보존하려는 경우, 외부 syslog 서버를 구성하고 감사 정보를 원격으로 저장합니다. 외부 서버를 사용하면 감사 데이터의 완성도를 낮추지 않고도 감사 메시지 로깅의 성능 영향을 최소화할 수 있습니다. 자세한 내용은 을 link:../monitor/considerations-for-external-syslog-server.html["외부 syslog 서버에 대한 고려 사항"] 참조하십시오.




== 오브젝트 암호화

StorageGRID를 구성할 때 다른 StorageGRID 클라이언트에 데이터 암호화가 필요한 경우 을 선택적으로 설정할 수 link:../admin/changing-network-options-object-encryption.html["저장된 오브젝트 암호화에 대한 글로벌 옵션입니다"]있습니다. FabricPool에서 StorageGRID로 계층화된 데이터는 이미 암호화되므로 StorageGRID 설정을 활성화할 필요가 없습니다. 클라이언트측 암호화 키는 ONTAP의 소유입니다.



== 오브젝트 압축

StorageGRID를 구성할 때는 를 활성화하지 마십시오.link:../admin/configuring-stored-object-compression.html["저장된 개체를 압축하는 전역 옵션"] FabricPool에서 StorageGRID로 계층화된 데이터는 이미 압축된 상태입니다. StorageGRID 옵션을 사용하면 개체의 크기가 더 작아지지 않습니다.



== 버킷 일관성

FabricPool 버킷의 경우 새 버킷의 기본 정합성 보장인 * 새 버킷의 경우 Read-after-new-write * 가 권장됩니다. 사용 가능 * 또는 * 강력한 사이트 * 를 사용하도록 FabricPool 버킷을 편집하지 마십시오.



== FabricPool 계층화

StorageGRID 노드에서 NetApp ONTAP 시스템에서 할당된 스토리지를 사용하는 경우 볼륨에 FabricPool 계층화 정책이 활성화되어 있지 않은지 확인합니다. 예를 들어 StorageGRID 노드가 VMware 호스트에서 실행 중인 경우 StorageGRID 노드의 데이터 저장소를 백업하는 볼륨에 FabricPool 계층화 정책이 설정되어 있지 않은지 확인합니다. StorageGRID 노드와 함께 사용되는 볼륨에 대해 FabricPool 계층화를 사용하지 않도록 설정하면 문제 해결과 스토리지 작업이 간소화됩니다.


CAUTION: FabricPool를 사용하여 StorageGRID 관련 데이터를 StorageGRID 자체로 계층화하지 마십시오. StorageGRID 데이터를 StorageGRID로 다시 계층화하면 문제 해결과 운영 복잡성이 늘어납니다.
